### ISSUE TITLE
[Feature Request] Make the ClaimConstants class public again

### ISSUE THREAD

**Issue by o1oo11oo** [AzureAD/microsoft-identity-web#100]
**Is your feature request related to a problem? Please describe.**
As part of a web API, we're using integration tests with a custom authentication handler like the one suggested [on the Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests#mock-authentication). To build a similar ClaimsPrincipal and have the extension functions like `User.GetObjectId()` working, I'm adding a bunch of claims from ClaimConstants to the principal, namely `Name`, `ObjectId` and `PreferredUserName`. This stopped working after #75 was merged, because the ClaimConstants class was set to internal.

**Describe the solution you'd like**
To me it seems like the easiest solution is to set the ClaimConstants class to public again, or provide a limited subset of claims, that can be public, if not everything should be publically available.

**Describe alternatives you've considered**
I could copy the constants I need from ClaimConstants or just define those as strings where I need them, but that might break in case those claims get changed at some point. Having them as constants that can be used prevents that.

**Comment by jennyf19** [comment]
Thanks for the feedback @o1oo11oo 
cc: @jmprieur

**Comment by jmprieur** [comment]
@jennyf19 @pmaytak : let's prioritize this to unblock the customers.

**Comment by jennyf19** [comment]
@jmprieur sounds good. will get this in the next release.

**Comment by jennyf19** [comment]
@o1oo11oo @chris5287 included in [0.1.1-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.1-preview
