### ISSUE TITLE
[Bug] RequiredScope RequiredScopesConfigurationKey - possible bug (or at least docs issue)

### ISSUE THREAD

**Issue by jbradt-stiles** [AzureAD/microsoft-identity-web#1036]
**Which version of Microsoft Identity Web are you using?**
1.7

**Where is the issue?**
* Web API
    * [x] Protected web APIs (validating scopes)

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft Identity Web.

**Repro**

following the documentation located at https://github.com/AzureAD/microsoft-identity-web/wiki/Web-APIs#using-the-requiredscopes-attribute

I've added the attribute 
````
[RequiredScope(RequiredScopesConfigurationKey = "AzureAd:Scopes")
````
(btw, there is a end brace missing in the docs)

and attempt to use the controller.

An exception is thrown
````
System.InvalidOperationException: A suitable constructor for type 'Microsoft.Identity.Web.Resource.RequiredScopeFilter' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
````

If I use
````
[RequiredScope("access_as_user")
````
(again, missing end brace in the docs)

there is no exception.

So, is there a dependency that needs to be configured?  If so, can the doc's be updated to reflect that requirement?

Or, should this 'just work'?

Thanks,
James

**Expected behavior**
Have the docs reflect what is required and exceptions not thrown

**Actual behavior**
exceptions are being thrown

**Comment by jmprieur** [comment]
@jbradt-stiles this is fixed in 1.12.0 released today
