### ISSUE TITLE
IDW10201: Neither scope or roles claim was found in the bearer token

### ISSUE THREAD

**Issue by levalencia** [AzureAD/microsoft-identity-web#1038]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
I added the nuget package yesterday so its the latest:
<PackageReference Include="Microsoft.Identity.Web" Version="1.*" />
   
**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [X] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
c. This is a new app or an experiment.

I have an app registration like this:

[![enter image description here][1]][1]

In my webappi my app settings.json: I have this:

    {
      "AzureAd": {
        "Instance": "https://login.microsoftonline.com/",
        "Domain": "xx.com.co",
        "TenantId": "xx-c220-48a2-a73f-1177fa2c098e",
        "ClientId": "xx-3737-48a5-a6c0-7e3bc4f9a5c9",
        "CallbackPath": "/signin-oidc",
        "Scopes" : "userimpersonation"
    
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*"
    }

In my Startup.cs:

    services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(Configuration.GetSection("AzureAd"));

And in my controller:

  

    [Authorize]
        [RequiredScope(RequiredScopesConfigurationKey = "AzureAd:Scopes")]
        [ApiController]
        [Route("api/[controller]")]
        public class WeatherForecastController : ControllerBase
        {

So, I run thhe web app, and I get a token via postman:

    curl --location --request POST 'https://login.microsoftonline.com/xx-c220-48a2-a73f-1177fa2c098e/oauth2/v2.0/token' \
    --header 'Content-Type: application/x-www-form-urlencoded' \
    --header 'Cookie: wlidperf=FR=L&ST=1526512036088; fpc=AnqPVmkUS_BIgf3y-QfBcFEzTZcDBQAAAKAv0dcOAAAA; stsservicecookie=ests; x-ms-gateway-slice=prod' \
    --form 'grant_type="client_credentials"' \
    --form 'client_secret="xx"' \
    --form 'client_id="xx-3737-48a5-a6c0-7e3bc4f9a5c9
    "' \
    --form 'scope="api://xx-3737-48a5-a6c0-7e3bc4f9a5c9/.default
    "'

That works fine, however if I channge the scope to: api://xx-3737-48a5-a6c0-7e3bc4f9a5c9/userimpersonation.

Then I get this error:

    AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid

If I use the token provided with the default scope, when I call my controller, I get the following error:

    System.UnauthorizedAccessException: IDW10201: Neither scope or roles claim was found in the bearer token. 
       at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_1.<<AddMicrosoftIdentityWebApiImplementation>b__1>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
       at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
       at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
       at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
       at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
       at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
       at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

  [1]: https://i.stack.imgur.com/Uicos.png

**Comment by jmprieur** [comment]
@levalencia

**Summary**
You acquire a token using the client credential grant, whereas your API is designed to be called on behalf of users

**Details**
- If your API is called by a daemon app (which seems to be the case since you acquired a token using the **client credential** grant), your need do define app-roles, not scopes. 
   See:
   - https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-registration#if-your-web-api-is-called-by-a-daemon-app and 
   -  https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-verification-scope-app-roles#verify-app-roles-in-apis-called-by-daemon-apps.

   Then when you require a token, it will have these app-roles.

   Alternatively, if you don't want to define app roles, but protect your API using access control list, see [To support ACL-based authorization](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#to-support-acl-based-authorization)

- If, on the contrary, your protected web API is supposed to be called by a daemon and you were just testing it using postman, don't use the client_credential grant.

**Comment by jmprieur** [comment]
@jennyf19, @henrik-me  : 
Proposing to take a supportability enhancement on this one, by adding an aka.ms link at the end of this error message

**Comment by levalencia** [comment]
my webapi will be called by a frontend app in react.
Before handling this to my developers however I need to test the authentication in postman.

so I am confused if I really need roles in this case.

**Comment by jmprieur** [comment]
@levalencia : does your react frontend sign-in users? if it does you don't need app roles (you are in the case of the second bullet point:

> * If, on the contrary, your protected web API is supposed to be called by a daemon and you were just testing it using postman, don't use the client_credential grant.

What is wrong, then, is that, to test your web API, you are using an un-adapted flow

```
--form 'grant_type="client_credentials"' \
```

You need to use something else than **client_credentials** (for instance, in postman, username password? although this might cause issues if there is conditional access)

**Comment by jennyf19** [comment]
closing as answered.
