### ISSUE TITLE
[Feature Request] Distributed cache is eventually consistent (does not wait for L2)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1047]
**Eventual consistency** is a programming model in which programmers make the assumption that over a long enough period of time and without changes to a system, the current version of a particular program will eventually distribute until every replica of the program is consistent.

**Is your feature request related to a problem? Please describe.**
Today the Distributed token cache adapter awaits for asynchronous operations on the underlying `IDistributedCache`

**Describe the solution you'd like**
- Don't wait for write and remove operations.
- This might require managing an event list of operations.

**Describe alternatives you've considered**
Task.Run() => { try/catch to do the operation} was tried out. See https://github.com/AzureAD/microsoft-identity-web/pull/1043

**Additional context**
See also Wilson's cache: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1605/files

**Comment by jennyf19** [comment]
Released in [2.5.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.5.0)
