### ISSUE TITLE
[Documentation] Under h4 "With Azure AD B2C", mislabelled Add

### ISSUE THREAD

**Issue by paul1923** [AzureAD/microsoft-identity-web#1049]
### Documentation related to component
Under h4 "With Azure AD B2C"

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in the example
- [ ] needs an example

### Description of the issue
Example given as 
  public void ConfigureServices(IServiceCollection services)
  {
   ...
      AddMicrosoftIdentityWebApp(Configuration, "AzureAdB2C");
   ...
  }

Shouldn't it be...

1) Missing services
2) Missing AddMicrosoftIdentityWebAppAuthentication

  public void ConfigureServices(IServiceCollection services)
  {
   ...
      services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureAdB2C");
   ...
  }

Using AddMicrosoftIdentityWebApp, I get...
           
CS1929: 'IServiceCollection' does not contain a definition for 'AddMicrosoftIdentityWebApp' and the best extension method overload 

![2021-03-07_15-56-21](https://user-images.githubusercontent.com/2419754/110229843-6b606700-7f60-11eb-8e79-29203baa9eeb.png)

**Comment by jmprieur** [comment]
Thanks @paul1923. This is fixed.
https://github.com/AzureAD/microsoft-identity-web/wiki/Web-Apps#with-azure-ad-b2c
