### ISSUE TITLE
Query - Using Micrsoft Identity Web For Token Validation with multiple B2C Policies

### ISSUE THREAD

**Issue by rsrinivasanhome** [AzureAD/microsoft-identity-web#1050]
I have a single api which is invoked from two applications using different polices say App1 - AAA  policy,  App2 - BBB.

{
"AzureAdB2C": {
"Instance": "https://mytenant.b2clogin.com",
"Domain": "mytenant.onmicrosoft.com",
"ClientId": "",
**"SignUpSignInPolicyId": "AAA"**
}

So far I have noticed as long as I configure one of the policies (AAA or BBB) the API works .  
Can I assume the keys returned from the below url(s) will always be same 
https://login.microsoftonline.com/xx.onmicrosoft.com/discovery/v2.0/keys?p=AAA  
https://login.microsoftonline.com/xx.onmicrosoft.com/discovery/v2.0/keys?p=BBB

Is my assumption that discovery keys are unique per tenant and do not vary based on policy correct ?

**Comment by jmprieur** [comment]
I would think so. Adding @nickgmicrosoft to confirm

**Comment by jmprieur** [comment]
@rsrinivasanhome you should be able to do it now with the multiple authentication scheme support:
https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes

Proposing to close, but feel free to reopen if you disagree.
