### ISSUE TITLE
Consume enterprise APIs secured with microsoft-identity-web in SharePoint Framework

### ISSUE THREAD

**Issue by justin0522** [AzureAD/microsoft-identity-web#1055]
call web api from spfx webpart with AadHttpClient
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi
the sample is Azure Function service
when i do that with enterprise APIs secured with microsoft-identity-web, the result is  302 (redirct to the https://login.microsoftonline.com)
so did I miss something?

**Comment by justin0522** [comment]
@jmprieur 
my API is a simple asp.net core web service which add microsoft-identity-web 

https://github.com/SharePoint/sp-dev-docs/issues/6248
exactly the same question
they saied 

> this isn't a SharePoint development issue... the problem is with how you've set up your API with Azure AD

**Comment by jennyf19** [comment]
@justin0522 why do you have the web app configuration -> `.AddMicrosoftIdentityWebApp()` if it's a web API? In the web API controller use the [right scheme](https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes)?

**Comment by justin0522** [comment]
you are right , i should set different scheme on the controller.
