### ISSUE TITLE
Able to change default endpoint for SignOut and SignIn

### ISSUE THREAD

**Issue by peirens-bart** [AzureAD/microsoft-identity-web#1069]
I created a asp.net core web app that runs inside a kubernetes cluster, in this cluster there is a configured ingress controller that send request from [domain]/app1/[controller]/[action] to the correct pod. this works because we have an environment variable that configures the vertical path for the app so all URL and redirects are sent to app1 (like js, css , a tags, ...)
now I can I add the virtual path the accountcontroller so the path [domain]/app1/MicrosoftIdentity/Account/[action]/[scheme?] can work. I tried to setup a new endpoint mapping in the startup as well as creating a new controller that inherits from the account controller but none of that is working.

**Comment by jennyf19** [comment]
closing. This was fixed in [1.18.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.18.0)
