### ISSUE TITLE
Add analyzers for public API compat and changes

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#107]
Investigate adding [Roslyn public API analyzers](https://github.com/dotnet/roslyn-analyzers/blob/master/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md) and any other API Compat tools.

**Comment by jmprieur** [comment]
@pmaytak : I believe you've done that already?

**Comment by pmaytak** [comment]
@jmprieur This is for ApiCompat stuff that George made. #76 was for the Roslyn/FxCop package.

**Comment by jennyf19** [comment]
closing for now.
