### ISSUE TITLE
[Feature Request] Support Azure regions in GetTokenForAppAsync

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1075]
**Is your feature request related to a problem? Please describe.**
MSAL.NET exposes [WithPreferredAzureRegion](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.acquiretokenforclientparameterbuilder.withpreferredazureregion?view=azure-dotnet)

**Describe the solution you'd like**
TBD

**Comment by sander1095** [comment]
Any update on this? I believe this might be related to logs I see about my code not specifying a region when requesting a token, right? 

Without this issue fixed, how do I get rid of that?

**Comment by jmprieur** [comment]
@sander1095. Sorry, we missed assigning it to the right milestone (because there was nothing to do in Microsoft.Identity.Web per se: the fix was in MSAL.NET):

you can enable your region by using the `AzureRegion` property of the `ConfidentialClientApplicationOptions`. 
In practice, just add a property named `AzureRegion`  in the "AzureAD" section of your appsetttings.json with:
- either the name of the region if you know it.
- or "TryAutoDetect" if you want MSAL.NET to attempt auto-detecting the region.

```JSon
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    // etc
   "AzureRegion" : "TryAutoDetect",

    "ClientSecret": "[Copy the client secret added to the app from the Azure portal]"
  },
...
}
```

See https://aka.ms/msal-net-region-discovery for more details.

**Comment by sander1095** [comment]
Hello, thanks for your reply.

Could you provide me a link to all the properies that can be set in the AzureAD object? I have never heard of this one. And I know for example there is also stuff like Authority/Domain, right? (How) is that related to my previous comment?

**Comment by jmprieur** [comment]
@sander1095: "AzureAd" is not an object, it's a configuration section, which is mapped to several classes:
- [MicrosoftIdentityOptions](https://docs.microsoft.com/dotnet/api/microsoft.identity.web.microsoftidentityoptions?view=azure-dotnet-preview)
- [ConfidentialClientApplicationOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplicationoptions?view=azure-dotnet-preview)
