### ISSUE TITLE
Should default audience validation for v1.0 tokens handle {ClientID} form?

### ISSUE THREAD

**Issue by KenKozman-GE** [AzureAD/microsoft-identity-web#1081]
I am new to all the AAD and Microsoft.Identity.Web world but... 

It seems like it is possible to get a token from a v1.0 app registration (e.g. an app registration with `accesstokenAcceptedVersion` of `null` or `1`) that has just the GUID form of the client id and NOT the `api://{ClientID}` form.

I was able to get one of these using grant_type=password and where the client_id and scope are both the client id (the scope in that case was `{ClientID}/.default`).

Also [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims) documentation seems to indicate that for v1.0 tokens the `aud` claim can be either the GUID or the App URI form.

The other place I have seen this is if you set the `aud` optional claim settings in the application to always return a GUID. In that case you get just a GUID as well (but for any way you request an access token, at least that I could find). See [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#additional-properties-of-optional-claims) for details on setting the `use_guid` option.

My thought is that perhaps the v1 logic block could set ValidAudiences instead and include both the App URI and GUID forms?

https://github.com/AzureAD/microsoft-identity-web/blob/061e118645c9f48c103ce66ca844065f8f977a29/src/Microsoft.Identity.Web/Resource/RegisterValidAudience.cs#L41-L42

Also a minor nitpick: "ClientId" is misspelled in the comment on line 44:
https://github.com/AzureAD/microsoft-identity-web/blob/061e118645c9f48c103ce66ca844065f8f977a29/src/Microsoft.Identity.Web/Resource/RegisterValidAudience.cs#L44

**Comment by jmprieur** [comment]
@KenKozman-GE you can always specify the audience you want by the "Audience" property in the appsettings.json / the configuration.

Thanks for the heads-up for the typo. cc: @jennyf19

**Comment by KenKozman-GE** [comment]
Good call, I did not think of that workaround.

Using the v2 form of the access token in the App Registration works as well (without needing to set "Audience"). That is the path we are looking at going down right now.

**Comment by jennyf19** [comment]
closing as answered

cc: @jennyf19 to fix above comments
