### ISSUE TITLE
[Feature Request]  Microsoft.Identity.Web support for .Net framework 4.6.2.

### ISSUE THREAD

**Issue by dhmahidawork** [AzureAD/microsoft-identity-web#1086]
current version of Microsoft.Identity.Web support  .Net framework 4.7.2 or later. is it possible for you guys to provide support for  .Net framework 4.6.2 ?

**Comment by jennyf19** [comment]
Included in [1.9.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.9.0)
