### ISSUE TITLE
Enable AuthorizeForScopes to be applied to a controller (was Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException')

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#11]
from @jasonshave and copied from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/216

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [X ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [X ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1. Start the website in debug mode using VS2019 and observe the execution work correctly when pulling the user's photo from MS Graph.
2. Stop the website.
3. Start the debug session again and observe the call to MS Graph fail.

**Expected behavior**
I would expect the website to retrieve a previously obtained, and stored, token to be used to authenticate to the MS Graph. 

**Actual behavior**
An exception is thrown in Microsoft.Identity.Web when trying to obtain a token:

Message="No account or login hint was passed to the AcquireTokenSilent call."

While executing: 

```
private async Task<string> GetAccessTokenOnBehalfOfUserAsync(
            IConfidentialClientApplication application,
            string accountIdentifier,
            IEnumerable<string> scopes,
            string loginHint,
            string tenant)
```

The code falls into: `IAccount account = await application.GetAccountAsync(accountIdentifier).ConfigureAwait(false);`

Which returns `null`. LoginHint is observed with the user's UPN just fine (from line 383). 

Next, it executes: `var accounts = await application.GetAccountsAsync().ConfigureAwait(false);`

...and falls into `private async Task OnBeforeAccessAsync(TokenCacheNotificationArgs args)`

This appears to try and read a cache of some sort. The `cacheKey` from line 88 in MsalAbstractTokenCacheProvider is populated, but then the following line returns null:
`byte[] tokenCacheBytes = await ReadCacheBytesAsync(cacheKey).ConfigureAwait(false);`

Next, line 399 executes and the `authority` variable is populated with the "login.microsoftonline.com/{tenantID}" value. 

The application throws at line 400 which is: 

```
result = await application
                    .AcquireTokenSilent(scopes.Except(_scopesRequestedByMsalNet), account)
                    .WithAuthority(authority)
                    .ExecuteAsync()
                    .ConfigureAwait(false);
```

**Possible Solution**
I used a previous version which had an attribute class for `[MsalUiRequiredExceptionFilter(Scopes = new[] { ScopeConstants.ScopeUserRead })]` which helped this issue I had previously. With the latest version things have changed quite a bit so I'm not sure if that old attribute extension class is even valid anymore. I did try adding it back to the project and decorated one of my controllers with it but it doesn't seem to help.

If I clear out the browser cache/cookies, I can get authenticated just fine. It's only on the subsequent attempts is when it fails.

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
Windows 10

### Versions
ASP.NET Core 2.2

**Comment by baywet** [comment]
For context I believe this attribute is now replaced by AuthorizeForScopes, let me know if I'm mistaking here @jmprieur

**Comment by jmprieur** [comment]
@baywet : this is now possible and documented in https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-mvc-controllers
