### ISSUE TITLE
[Feature Request] Web APIs accept Proof of Possession tokens

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#110]
**Is your feature request related to a problem? Please describe.**
Microsoft.IdentityModel now support Proof Of Possession (PoP = SignedHttpRequest). This is illustrated in the following sample https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/4.-Console-app-calls-web-API-with-PoP which contains a folder named [Microsoft.Identity.Web.Future](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/4.-Console-app-calls-web-API-with-PoP/Microsoft.Identity.Web.Future)

See usage in [4.-Console-app-calls-web-API-with-PoP/TodoListService/Startup.cs#L23-L29](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/53a2a35244ccc9da7320ea44a174f02b8f9da2ae/4.-Console-app-calls-web-API-with-PoP/TodoListService/Startup.cs#L23-L29)

```CSharp
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddProtectedWebApi(Configuration)
                    .AddProtectedWebApiCallsProtectedWebApi(Configuration)
                    .AddPop(Configuration)
                    .AddInMemoryTokenCaches();
```

**What needs to be done?**
Import in Microsoft.Identity.Web:
- [Microsoft.Identity.Web.Future/SignedHttpRequest](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/4.-Console-app-calls-web-API-with-PoP/Microsoft.Identity.Web.Future/SignedHttpRequest)
- [Microsoft.Identity.Web.Future/WebApiServiceCollectionExtensions.cs](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/4.-Console-app-calls-web-API-with-PoP/Microsoft.Identity.Web.Future/WebApiServiceCollectionExtensions.cs)
- Add unit tests

Note: the other files are duplicates of existing files in MIcrosoft.Identity.Web as these are internal and Microsoft.Identity.Web.Future is not friend of Microsoft.Identity.Web

**Comment by jmprieur** [comment]
@jennyf19 @pmaytak : do we think that, from an Engineering point of view it's better to do this work early to avoid divergence of the duplicated files?

**Comment by jennyf19** [comment]
@jmprieur yes, probably, but maybe for next next release...like not 0.1.2, but 0.1.3, as we have several items for 0.1.2, unless you want to move that up, move something else out. my 2 cents.

**Comment by jmprieur** [comment]
@henrik-me : do you think this becomes more important to do it soon?

**Comment by dpomBF** [comment]
Can you please add Microsoft.Identity.Web.Future to Microsoft.Identity.Web or at least publish it as a nuget package? I'd like to use the POP Authentication Scheme it offers and don't want to clone the library. Thanks! 
Here's where I found the code:
https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/4-Call-OwnApi-Pop/Microsoft.Identity.Web.Future

**Comment by chrisls121** [comment]
Would love to see this get integrated soon.

**Comment by jennyf19** [comment]
closing, as will be handled by open source SAL.
