### ISSUE TITLE
[Bug] WWW-Authenticate: Bearer error="invalid_token", error_description="The signature is invalid"

### ISSUE THREAD

**Issue by senal** [AzureAD/microsoft-identity-web#1117]
**Which version of Microsoft Identity Web are you using?**
1.8.2

**Where is the issue?**

* Web API
    * [ ] Protected web APIs (validating tokens)

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**
My reference is the following sample application provided by Microsoft. To generate the token.
Then pass the token as a 'Bearer'

microsoft-authentication-library-for-js\samples\msal-react-samples\typescript-sample

[(https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/typescript-sample)]

In my WebAPI I have registered the following middleware with the following configuration fields.

`services.AddMicrosoftIdentityWebApiAuthentication(Configuration);`

`"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "ClientId": "client_id_as_it_appear_in_azure_portal",
    "TenantId": "tenant_id_as_it_appear_in_azure_portal",
    "AllowWebApiToBeAuthorizedByACL": true
  }`

**Expected behavior**
Expecting the validate the token and allow users to consume procted resources

**Actual behavior**
Following error with 401 https status

`WWW-Authenticate: Bearer error="invalid_token", error_description="The signature is invalid"`

**Possible solution**

**Additional context / logs / screenshots**
![image](https://user-images.githubusercontent.com/2841066/113501664-516b7180-956a-11eb-8125-a03d0242f893.png)

**Comment by jmprieur** [comment]
@senal which scope did you request? didn't you request a scope for Microsoft Graph instead of your web API?

**Comment by senal** [comment]
@jmprieur ,

When I made a request to get a token, I made it with;
`scopes: ["User.Read"]`
as in the sample.

I just tried calling Microsoft Graph instead my WebAPI and it worked.

Am I missing any configurations in my WebAPI or something wrong with service configurations?

**Comment by jmprieur** [comment]
@senal yes, you need to request a token for your web API, not for Microsoft Graph.
I believe that this sample will give you all the answers to the questions you have: https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo

cc: @derisen

**Comment by senal** [comment]
@jmprieur,

Thanks for the infor.

Let me follow the steps given in the above sample.
I will keep updating my progress.

**Comment by senal** [comment]
@jmprieur, @derisen,
I registered my SPA and API applications in Azure as per the steps listed in the tutorial.
However, when I'm trying to get a token, I received 400 (bad request) error.
Please see the screenshot:
![image](https://user-images.githubusercontent.com/2841066/113510096-4f220b00-959c-11eb-9146-db18dd428552.png)

Also error shown in the network tab:
![image](https://user-images.githubusercontent.com/2841066/113510129-94ded380-959c-11eb-811a-80eb193eca0e.png)

Do you have any idea of this error?

**Comment by senal** [comment]
@jmprieur, @derisen,

When registering spa, I did select **single tenant** as "Supported account types" instead  **Personal Microsoft accounts only**". 
Please see the below image.
![image](https://user-images.githubusercontent.com/2841066/113511306-8b586a00-95a2-11eb-8f9a-7ba68daf3907.png)

And in the msalConfig: I pass the authority as below:

` 
 authority: 'https://login.microsoftonline.com/<tenant_id>',
`

Please note that when I set the following url as the  authority:

`authority: "https://login.microsoftonline.com/consumers"`

It does show an error on the loginPopup(...);

![image](https://user-images.githubusercontent.com/2841066/113511528-8ea02580-95a3-11eb-83e2-ab550aed0516.png)

However, when I try to retrieve a token to call my webApi,  the SPA throws the bellow error:

![image](https://user-images.githubusercontent.com/2841066/113511637-23a31e80-95a4-11eb-8c7d-687de7b69c10.png)

Any thoughts on this error?

**Comment by derisen** [comment]
@senal This sample was meant to be used with personal Microsoft accounts (`consumers` endpoint). If you want to change that, [see this please](https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/blob/master/ReadmeFiles/howto-common.md).

Basically you need to make sure both the SPA and the web API configurations are aligned (with each other AND with how you registered your app on Azure portal).

**Comment by senal** [comment]
@derisen,
Thanks for this.

Trying to configure SPA cofig values as per the instructions.
Note that I'm using TS with the `Configuration` object. 
Seems like `validateAuthority` is not valid property of the object:

See the screenshot:
![image](https://user-images.githubusercontent.com/2841066/113521559-9b416f80-95dd-11eb-8b99-e2c50c9d8004.png)

Please advise.

**Comment by derisen** [comment]
@senal ah, sorry, `validateAuthority` property is deprecated. Just remove it and it should be fine. I'll fix the docs.

**Comment by senal** [comment]
Was able to get it working.

Thanks @jmprieur for your advices right directions.
@derisen , big thanks to your advices and support.

**Comment by senal** [comment]
I was able to fix my issue with by following the above tutorial and the provided technical guidance.

**Comment by JasonBermeo** [comment]
PUEDE COMPARTIR LA SOLUCION? LINK CAIDO
