### ISSUE TITLE
[Bug] IDX10609: Decryption failed. No Keys tried: token:

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-identity-web#1118]
Microsoft Identity Web 1.8.2

**Where is the issue?**
* Web API
    * [ ] Protected web APIs (validating scopes)
    * [x ] Protected web APIs call downstream web APIs

**Is this a new or an existing app?**
I am upgrading from the old forked Microsoft.Identity.Web repo using .NET Core 2+ to the latest .NET Core 5.0 and Identity Webb 1.8.2.

This is a first party app registration.

**Repro**
I am trying to validate a downstream API token.

I have this code here. 
```
 services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd")
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddDownstreamWebApi("FlightService", Configuration.GetSection("Flight"))
                .AddInMemoryTokenCaches();

            services.AddOptions<JwtBearerOptions>(jwtBearerScheme)
                .Configure<IServiceProvider, IOptionsMonitor<MicrosoftIdentityOptions>>((options, serviceProvider, microsoftIdentityOptionsMonitor) =>
            {

                // When an access token for our own Web API is validated, we add it to MSAL.NET's cache so that it can
                // be used from the controllers.
                options.Events = new JwtBearerEvents();

                options.Events.OnAuthenticationFailed = async context =>
                {
                    //Log failed authentications
                    var test = context;
                    await Task.CompletedTask;
                };

                options.Events.OnTokenValidated = async context =>
                {
                    // This check is required to ensure that the Web API only accepts tokens from tenants where it has been consented and provisioned.
                    if (!context.Principal.Claims.Any(x => x.Type == ClaimConstants.Scope)
                       && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Scp)
                       && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Roles))
                    {
                        throw new UnauthorizedAccessException("Neither scope or roles claim was found in the bearer token.");
                    }

                    await Task.FromResult(0);
                };

               // options.Events = JwtBearerMiddlewareDiagnostics.Subscribe(options.Events);
            });
```

I tried both of there cert settings.
```
  "ClientCertificates": [
    {
      "SourceType": "StoreWithDistinguishedName",
      "CertificateStorePath": "CurrentUser/My",
      "CertificateDistinguishedName": "CN=insider.windows.com"
    }
  ],
```

```
    "ClientCertificates": [
      {
        "SourceType": "KeyVault",
        "KeyVaultUrl": "https://wipssladmin.vault.azure.net",
        "KeyVaultCertificateName": "InsiderWindowsCom-OneCert"
      }
    ],
```

**Expected behavior**
Not receive IDX10609 error

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.

**Possible solution**
Use MicrosoftIdentityOptions and do the cert progrmattically but not sure where to get the MicrosoftIdentityOptions  delegate.

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.
![image](https://user-images.githubusercontent.com/4327773/113526388-7e764f00-957f-11eb-8fe9-f71dbf722ccc.png)

**Comment by jmprieur** [comment]
@jrmcdona : did you find the answer to your question yourself? did you use DecryptCertificates (instead of ClientCertificates)?

**Comment by jrmcdona** [comment]
Yes.  I was able to get something to work but DecryptCertificates  does not work for me.   Here is what I had.

```
 "TenantId": "common", // MicrosoftServices
    // To call an API
    "ClientCertificates": [
      {
        "SourceType": "StoreWithDistinguishedName",
        "CertificateStorePath": "CurrentUser/My",
        "CertificateDistinguishedName": "CN=referrals.azurewebsites.net"
      }
    ],
    "TokenDecryptionCertificates": [
      {
        "SourceType": "StoreWithDistinguishedName",
        "CertificateStorePath": "CurrentUser/My",
        "CertificateDistinguishedName": "CN=insider.windows.com"
      }
    ]
```

The way I got passed the Decryption error was this, which is similar to how I was doing it before migrating to .NET 5

```
services.AddOptions<JwtBearerOptions>(jwtBearerScheme)
                .Configure<IServiceProvider, IOptionsMonitor<MicrosoftIdentityOptions>>((options, serviceProvider, microsoftIdentityOptionsMonitor) =>
            {

                X509Certificate2 tokenDecryptionCertificate = GetCertificateFromStore("CN=insider.windows.com");
                // If you provide a token decryption certificate, it will be used to decrypt the token
                if (tokenDecryptionCertificate != null)
                {
                    options.TokenValidationParameters.TokenDecryptionKey = new X509SecurityKey(tokenDecryptionCertificate);
                }
            });
```

We can reopen the bug on this to solve this particular issue.

**Comment by jmprieur** [comment]
@jrmcdona 

1. I would replace `services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd")` by
  
   ```services.AddAuthentication(jwtBearerScheme)
       .AddMicrosoftIdentityWebApi(Configuration, "AzureAd")
   ```

   to be sure you are using the same authentication scheme.

2. you don't need the ` services.AddOptions<JwtBearerOptions>(jwtBearerScheme)
                .Configure<IServiceProvider, IOptionsMonitor<MicrosoftIdentityOptions>>((options, serviceProvider, microsoftIdentityOptionsMonitor) => {}`. This is already all done by Microsoft.Identity.Web, and by re-declaring the events etc .. without chaining them you loose the processing that Microsoft.Identity.Web provides by default. See [Customization](https://github.com/AzureAD/microsoft-identity-web/wiki/customization) for chaining events.

3. you need / want to use `TokenDecryptionCertificates`. For details see [Token Decryption](https://github.com/AzureAD/microsoft-identity-web/wiki/Token-Decryption), but they will only be picked-up if you don't override Microsoft.Identity.Web processing.

**Comment by jennyf19** [comment]
closing as answered
