### ISSUE TITLE
[Documentation] 1.9.0 is released on NuGet but no documentation

### ISSUE THREAD

**Issue by erwinkramer** [AzureAD/microsoft-identity-web#1134]
### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
I can pull the 1.9.0 version but I see that there's still issues open on this milestone. Also I don't see any release info in github releases. What's going on?

**Comment by jmprieur** [comment]
@erwinkramer we have done the technical release (releasing to nuget), but have not finished the release process yet.
This is coming

**Comment by erwinkramer** [comment]
Thanks
