### ISSUE TITLE
[Bug] Remove claims name mapping workaround when Wilson releases fix.

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#1140]
See [issue](https://github.com/AzureAD/microsoft-identity-web/issues/1136) for details.

**Comment by jmprieur** [comment]
Wilson's fix is merged to Wilson's master: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1629

**Comment by jmprieur** [comment]
@jennyf19 : proposing it for 1.10, as Wilson 6.10.2 has been published to nuget.org.

**Comment by jennyf19** [comment]
Included in [1.9.2 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.9.2)
