### ISSUE TITLE
Advantage of Microsoft Identity Web Over JWT Bearer Advantages [Documentation] 

### ISSUE THREAD

**Issue by rsrinivasanhome** [AzureAD/microsoft-identity-web#1143]
### Documentation related to component
General benefit of Microsoft identity web over normal JWT bearer validation 
### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
To validate AD and B2C token I can also use the jwtbearer validation.  Example is below .   What advantage does microsoft Identity web provide over the below code ?

```
Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                options.Authority = "https://login.microsoftonline.com/xxxx;
                options.Audience = "https://xxxx.onmicrosoft.com/aud";
              
            });

```

**Comment by jmprieur** [comment]
@rsrinivasanhome 

What would you want in addition to [Why use Microsoft Identity Web?](https://github.com/AzureAD/microsoft-identity-web/wiki/Microsoft-Identity-Web-basics) and [Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web/wiki/1.0.0) ?

**Comment by rsrinivasanhome** [comment]
Thanks for your reply . The ticket can be closed
