### ISSUE TITLE
[Feature Request] DefaultAzureCredential to be included in token acquisition

### ISSUE THREAD

**Issue by NWessel** [AzureAD/microsoft-identity-web#1144]
**Is your feature request related to a problem? Please describe.**
When wanting to use Azure easy auth, i just figured out i can use 'new DefaultAzureCredential()'
It gets annoying having to implement that everywhere when we have ITokenAcquisition

**Describe the solution you'd like**
Perhaps in the startup, we currently have the possibility to do the following.
services.AddMicrosoftIdentityWebApiAuthentication(Configuration)
                .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddInMemoryTokenCaches();

It would be great if we could somehow incorporate the token acquisition to use defaultazurecredential or having an extended call of some sort

**Comment by jmprieur** [comment]
@NWessel : 
- Microsoft.Identity.Web already leverages DefaultAzureCredentials to get certificates
- if you want a `TokenCredential`, it also exposes a `TokenAcquisitionTokenCredential`.

Does it work for you? or otherwise what is the scenario that this does not cover?

**Comment by NWessel** [comment]
@jmprieur 
Perhaps it is covered then.

But lets say i have this
![image](https://user-images.githubusercontent.com/9061380/114921966-69c17300-9e2b-11eb-9364-f4f930c97598.png)

Would that run in context of my VisualStudio user when doing local development?
That is what i want i guess. So the aquisition is the same way if im on my local dev machine or running azure app service with easyauth. 
I would never have to worry about doing authentication in my SPA layer again then :)
Does it make sense?

**Comment by jmprieur** [comment]
@NWessel:
- if you want to use the same user as you use for Visual Studio, the best is to [enable system web browser](https://docs.microsoft.com/visualstudio/ide/work-with-multi-factor-authentication?view=vs-2019#enabling-system-web-browser) in the Visual Studio settings.
- if you were to use DefaultAzureCredential, you would only be able to do so if you request the same scopes as what Visual Studio does (which is probably not what you'd want)
- if you have an app registration, you don't need to use Easy Auth (you don't need to enable App services **authentication**).

**Comment by NWessel** [comment]
This seems odd to me, I might be missing something.

I will try to paint the complete picture.
So my goal is to make authentication require as little code as possible. Which i thought was what i did with EasyAuth and DefaultAzureCredential.

What i'm making is a asp.net core api, where im using the
AddMicrosoftIdentityWebApiAuthentication
.EnableTokenAc.....
.AddMicrosoftGraph

And then on the same web service i'm also using a Single Page Application in react, where i would have to implement the user authentication normally, with MSAL perhaps in javascript.

It seems to me i can skip the MSAL javascript part if i use EasyAuth, as that will handle login and authenticated requests for me.
This is when the app is published into an Azure Service ofcourse.

I want the local development experience to be somewhat similar in behavior, and that is where DefaultAzureCredential comes into the picture.
![image](https://user-images.githubusercontent.com/9061380/114981699-aecac100-9e8e-11eb-81db-c6f509cd5d35.png)

Imagine the tokenAcquisition would actually just give me what DefaultAzureCredential does.
That way I wouldn't have to think about DefaultAzureCredential if it was some kind of standard or fallback in the tokenAcquisition.

Am i missing the point here and thinking this is something else? :)

**Comment by jmprieur** [comment]
Closing.
rel/v2 brings signed assertions coming from managed identity,
