### ISSUE TITLE
Ocelot callback

### ISSUE THREAD

**Issue by yongkeecho** [AzureAD/microsoft-identity-web#1145]
Our company uses Ocelot for reverse proxy. My app authentication with AzureAD works perfect in localhost. When it's deployed and routed by Ocelot, it doesn't.
The main issue is the callback url's **redirect_uri** parameter value (http://myapp.local/signin-oidc) is pre-Ocelot routed and doesn't match post-Ocelot routed uri (https://myapp.mycompany.com/signin-oidc) registered in the Azure Portal.

https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/authorize?redirect_uri=http%3A%2F%2Fmyapp.local%2Fsignin-oidc

Can we provide with the routed hostname? `Domain` parameter in appsettings.json seems not help.

```
    "AzureAd": {
        "Instance": "https://login.microsoftonline.com/",
        "Domain": "myapp.mycompany.com,
        "CallbackPath": "/signin-oidc",
        ...
    },
```

**Comment by jmprieur** [comment]
@yongkeecho : would this help? https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers#how-to-fix-it ?

**Comment by yongkeecho** [comment]
The forwarded headers didn't change the redirect_uri value, which resulted in forwarding to local address instead of proxy address. The issue seems not fixed according to a posting at https://docs.microsoft.com/en-us/answers/questions/144558/azure-application-proxy-not-passing-x-forwarded-ho.html

**Comment by jmprieur** [comment]
@Tratcher would you have an idea?

**Comment by Tratcher** [comment]
The linked issue was specific to the AAD Application Proxy service not providing X-Forwarded headers. Are you using that service _and_ Ocelot?

Ocelot looks like it can be configured to add these headers:
https://ocelot.readthedocs.io/en/latest/features/headerstransformation.html#add-to-request
https://ocelot.readthedocs.io/en/latest/features/headerstransformation.html#placeholders

**Comment by jennyf19** [comment]
closing, please reopen if needed.
