### ISSUE TITLE
[Bug] /Account/SignOut triggers a redirect loop with Azure B2C

### ISSUE THREAD

**Issue by leoogh** [AzureAD/microsoft-identity-web#1154]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

Microsoft Identity Web.UI 1.9.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

/Account/SignOut controller action 

**Is this a new or an existing app?**

This is a new app or an experiment.

**Repro**

```csharp
<a asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut">Sign out</a>
```

**Expected behavior**
1. Should redirect the user to the IdP signout endpoint. This indeed it does correctly (the IdP is an Azure AD B2C custom policy)
2. Should then redirect to https://localhost/Account/SignedOut. This it doesn't do

**Actual behavior**
redirects to https://localhost/Account/SignOut?page=%2FAccount%2FSignedOut 

This triggers a redirect loop, since it hits the /Account/SignOut action again, which redirects to the Idp again, which redirects to the /Account/SignOut action etc.

**Possible solution**
```csharp
// the current /Account/SignOut controller implementation computes the post-signout redirect url as

 var callbackUrl = Url.Page("/Account/SignedOut", pageHandler: null, values: null, protocol: Request.Scheme);

// this seems to produce "https://localhost/Account/SignOut?page=%2FAccount%2FSignedOut" instead of 
// the expected "https://localhost/Account/SignedOut"
```

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@leoogh did you try with the most recent version of Microsoft.Identity.Web ?

**Comment by jmprieur** [comment]
Closing as you have not answered, @leeogh 
but feel free to reopen and provide a repro if you are still blocked.

**Comment by JefSchraag** [comment]
I ran into this redirect loop problem. 

For me the fix was to add `app.MapRazorPages();` to my app pipeline. The `Url.Page()` creates the hard dependency on a Razor **Page** with the `/Account/SignedOut`. Putting a Razor _Component_ (Blazor) there will not be detected and then the `Url.Page()`  method creates the looping redirect.
