### ISSUE TITLE
args.suggestedcachekey null for public client

### ISSUE THREAD

**Issue by Ricky1997** [AzureAD/microsoft-identity-web#1155]
I want to use distributed token caching ( like SQL ) for public client apps.  I have tried the identity.web msal tokencacheproviders but they do not work as with a public client app args.suggestedcachekey value is null. 

Is there a way I can use the msalDistributedTokenCacheAdapter with app.userTokenCache of public client ?

At present I receive the error like "Key is null".

**Comment by jmprieur** [comment]
@Ricky1997 thanks for raising this.
This is actually an MSAL.NET bug.
cc: @bgavrilMS as we were discussing this yesterday (another customer asked for the same thing)

What is your scenario?
which flow do you use? why do you want a distributed cache in a public client application?

**Comment by Ricky1997** [comment]
Thanks for your reply @jmprieur 

I want to acquire tokens using a public client id using username password flow. Now at the same time I want to cache the user Token cache ( access token, refresh token ) in distributed DB (sql, redis ) and use this db later on to be able to get tokens silently. 
Will this be possible to do at present ?

**Comment by jmprieur** [comment]
@Ricky1997 do you mind sharing a diagram of your architecture?
with a common terminology for apps: https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios

**Comment by jennyf19** [comment]
closing as not related to MS Id web, but @Ricky1997 , we can continue the conversation here if needed.
