### ISSUE TITLE
401 response despite what looks like a validated token with user in the claim

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-identity-web#1156]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
1.9.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [x ] Protected web APIs (validating tokens)
    * [ x] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

This is a new app I am trying to get working.
I am sending an encrypted bearer token from client to my API currently via Postman.  I can see the Bearer token was successfully decrypted and I can see a user in the claims.

However, on the controller I get 401.   The debugger does not fire in OnAuthenticationFailed or OnForbidden so I am not sure what is failling and why it throws a 401.  Where can I get the logs for why it 401s?

The token seems to validate and you can see we have a user with the User.Access scope.
![image](https://user-images.githubusercontent.com/4327773/115798747-9251eb80-a39c-11eb-9a39-202f92ce68c6.png)

Am I missing something in this code?

```csharp
  services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd");


            services.AddOptions<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme)
                .Configure<IServiceProvider, IOptionsMonitor<MicrosoftIdentityOptions>>((options, serviceProvider, microsoftIdentityOptionsMonitor) =>
                {
                    options.TokenValidationParameters = new TokenValidationParameters { 
                        ValidAudiences =  new string[]
                    {
                        clientId, $"api://{options.Audience}"
                    },
                       ValidateIssuer = true, ValidateAudience = true, SaveSigninToken = true };
                    // Instead of using the default validation (validating against a single tenant, as we do in line of business apps),
                    // we inject our own multi-tenant validation logic (which even accepts both v1.0 and v2.0 tokens)
                    MicrosoftIdentityIssuerValidatorFactory microsoftIdentityIssuerValidatorFactory =
                    serviceProvider.GetRequiredService<MicrosoftIdentityIssuerValidatorFactory>();
                    options.TokenValidationParameters.IssuerValidator = microsoftIdentityIssuerValidatorFactory.GetAadIssuerValidator(options.Authority).Validate;

                    X509Certificate2 tokenDecryptionCertificate = GetCertificateFromStore("CN=identity.windowscommunity.azclient.ms");
                    // If you provide a token decryption certificate, it will be used to decrypt the token
                    if (tokenDecryptionCertificate != null)
                    {
                        options.TokenValidationParameters.TokenDecryptionKey = new X509SecurityKey(tokenDecryptionCertificate);
                    }
                    // When an access token for our own Web API is validated, we add it to MSAL.NET's cache so that it can
                    // be used from the controllers.
                    options.Events = new JwtBearerEvents();
                    options.Events.OnMessageReceived = async context =>
                    {
                        await Task.FromResult(0);
                    };
                    options.Events.OnAuthenticationFailed = async context =>
                    {
                        //Log failed authentications
                        var test = context;
                        await Task.CompletedTask;
                    };
                    options.Events.OnForbidden = async context =>
                    {
                        await Task.FromResult(0);
                    };
                    options.Events.OnChallenge = async context =>
                    {
                        await Task.FromResult(0);
                    };
                    options.Events.OnTokenValidated = async context =>
                    {
                        // This check is required to ensure that the Web API only accepts tokens from tenants where it has been consented and provisioned.
                        if (!context.Principal.Claims.Any(x => x.Type == ClaimConstants.Scope)
                           && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Scp)
                           && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Roles))
                        {
                            throw new UnauthorizedAccessException("Neither scope or roles claim was found in the bearer token.");
                        }
                    };
                    //options.Events = JwtBearerMiddlewareDiagnostics.Subscribe(options.Events);
                });
            services.AddControllers();
```

On the controller I have tried RequiredScope and also  [RequiredScope(RequiredScopesConfigurationKey = "AzureAd:Scopes")] but neither changes the outcome
```controller

    [ApiController]
    [Route("[controller]")]
    [Authorize]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        [RequiredScope("User.Access")]
        public IEnumerable<WeatherForecast> Get()
        {
            ClaimsPrincipal principal = HttpContext.User as ClaimsPrincipal;
            if (principal.Identity.IsAuthenticated)
            {
                //return "success!";
            }
            else
            {
                //return "not authenticated!";
            }

            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
```

```config
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "ClientId": "35d1c2f3-da6f-425b-9eee-65726f26f86d",
    "TenantId": "consumers",
    "Scopes": "User.Access",
    "Audience": "35d1c2f3-da6f-425b-9eee-65726f26f86d"
  },
```
**Expected behavior**
I would expect to not be getting a 401 on the controller

**Actual behavior**
I am getting a 401 even though a user is being found in token validation and has the scope.

**Comment by jmprieur** [comment]
@jrmcdona : why are you re-doing what  services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd") is doing? You shouldn't need to write any of that.? I think that you probably override (instead of chaining) some of the events that Microsoft.Identity.Web needs.

A few remarks:

For the token decrypt certificate, you can express it in the config file (not sure if you use CurrentUser or CurrentMachine, but you can adjust this one)

```JSon
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "ClientId": "35d1c2f3-da6f-425b-9eee-65726f26f86d",
    "TenantId": "consumers",
    "Scopes": "User.Access",
    "Audience": "35d1c2f3-da6f-425b-9eee-65726f26f86d",
    "TokenDecryptionCertificates": [
      {
        "SourceType": "StoreWithDistinguishedName",
        "CertificateStorePath": "CurrentUser/My",
        "CertificateDistinguishedName": "CN=CN=identity.windowscommunity.azclient.ms"
      }
     ]
  },
```

More about certificates in: https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates#decryption-certificates
Microsoft.Identity.Web will support certificate rotation from keyvault soon

You seem to have the "Audience" in the config file and override ValidAudiences in the code? you can do all by config file.

On the controller: 
- Given the presence of the [Authorize] attribute, I believe that the user will always be authenticated (the test `if (principal.Identity.IsAuthenticated)` shouldn't be needed)
- This is a web API which doesn't seem to call anything ,so RequiredScopes is not needed. You might want to check that scopes in the token contain your own scope. For details on how to write a web API, please see:
  - https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis
  - https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview

And do you want to have a look at the samples, for instance: https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsWebApiCallsGraph/TodoListService/Startup.cs#L56

**Comment by jrmcdona** [comment]
@jmprieur thanks, still getting 401.   I have reduced my code down to just this and moved the TokenDescryption to the config.

services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd");

How can I catch the log for why it is a 401?

**Comment by jmprieur** [comment]
@jrmcdona. you can enable logging, with log level "Information" ?
https://github.com/AzureAD/microsoft-identity-web/wiki/Logging

**Comment by jmprieur** [comment]
@jrmcdona : Closing as this is pretty old.
Feel free to reopen if this is still and issue for you.
