### ISSUE TITLE
[Feature Request] For .Net Framework 4.6.2, can we have lower version (v2.*)  of Microsoft.Extensions.Options dependency?

### ISSUE THREAD

**Issue by dnl-q** [AzureAD/microsoft-identity-web#1171]
**Is your feature request related to a problem? Please describe.**
Version 1.9.1 has dependencies .NETFramwork, Version=4.62 Microsoft.Extensions.Options (>=5.0.0)

**Describe the solution you'd like**
See whether it can dependency on lower version of Microsoft.Extensions.Options, for instance 2.*

**Additional context**
We are using some nuget package which has dependency on lower version of Microsoft.Extensions.Options (v2.11 - v2.22) for .NET Framework 4.6.2. While Identity.Web requires Microsoft.Extension.Options >=5.0.0.  So they are confict.

**Comment by jennyf19** [comment]
@dnl-q I tried referencing just v2.* for net462, but we lose too many features, such as EventId, ILogger, and other Logging features.  We won't be able to move off of the current package dependency.

**Comment by jennyf19** [comment]
@dnl-q mentioned they'll be moving to net core 3.1
