### ISSUE TITLE
[Bug] No authenticationScheme was specified, and there was no DefaultChallengeScheme found in 1.9.2 release

### ISSUE THREAD

**Issue by santosh-jallapuram** [AzureAD/microsoft-identity-web#1190]
Hi,

I am getting `No authenticationScheme was specified, and there was no DefaultChallengeScheme found` issue in version 1.9.2. I literally have no changes apart from package upgrade. 

Here is the full error. 

`{"ClassName":"System.InvalidOperationException","Message":"No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"Microsoft.AspNetCore.Authentication.Core","WatsonBuckets":null}`

And app is working fine when I revert back to 1.9.1.

**Comment by jmprieur** [comment]
@santosh-jallapuram thanks for the heads-up.
Do you have repro steps?

**Comment by santosh-jallapuram** [comment]
@jmprieur I do not have separate repro steps. But am using Azure AD Cookie based login in a .Net 5 MVC app. 


Here is the code that am using.

        services
        .AddAuthentication(o =>
        {
            o.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            o.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
        })
        .AddMicrosoftIdentityWebApp(this.configuration.GetSection("AzureAd"));


package upgrade was the only step to reproduce it.

**Comment by santosh-jallapuram** [comment]
I tried your code @jmprieur 

But unfortunately am getting this error.  Not sure if I am referring to the correct package. 

Startup error 
![image](https://user-images.githubusercontent.com/10022914/117678351-f06c3480-b1cc-11eb-919c-ec04f67ec17f.png)

AuthenticationServiceCollectionExtensions 
![image](https://user-images.githubusercontent.com/10022914/117678443-0548c800-b1cd-11eb-846b-330c5287d142.png)

csproj SDK 
![image](https://user-images.githubusercontent.com/10022914/117678493-11cd2080-b1cd-11eb-803f-620e13eae038.png)


installed dotnet versions 
![image](https://user-images.githubusercontent.com/10022914/117678588-2d382b80-b1cd-11eb-9876-9ed6dc186a3f.png)

global json 

![image](https://user-images.githubusercontent.com/10022914/117678629-345f3980-b1cd-11eb-9045-58e8c6bb846f.png)

**Comment by jmprieur** [comment]
@santosh-jallapuram.

Just try this following:

```CSharp
services
    .AddAuthentication(OpenIdConnectDefault.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(this.configuration.GetSection("AzureAd"));
```

**Comment by jmprieur** [comment]
@santosh-jallapuram : did you try the code?
You might also want to move to the latest version of Microsoft.Identity.Web which is about supporting multiple authentication scheme.

**Comment by jennyf19** [comment]
closing, but feel free to reopen @santosh-jallapuram
