### ISSUE TITLE
[Feature Request] Merge AadIssuerValidatorOptions class into MicrosoftIdentityOptions

### ISSUE THREAD

**Issue by Lex45x** [AzureAD/microsoft-identity-web#1209]
# The Problem

Our AspNetCore application is hosted 'on-premises'. The purpose of the app is internal financial reporting.  
Because of that we have plenty of Firewall rules that are outside of my team's control.

One day we spotted, that occasionally, some of the requests to get `IssuerMetadata` reached HttpClient default timeout of 100s. The problem is related to internal routing and can occur intermittently.
```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1'.\r\n ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1'.\r\n ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```
I've tried different options to change default timeout and/or introduce some retry-policy for HttpClient using [HttpClientFactoryServiceCollectionExtensions.AddHttpClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=dotnet-plat-ext-5.0).
However, all my attempts were unsuccessful because of MicrosoftIdentityIssuerValidatorFactory constructor:
```csharp
public MicrosoftIdentityIssuerValidatorFactory(
        IOptions<AadIssuerValidatorOptions> aadIssuerValidatorOptions, //I've never seen this options before.
        IHttpClientFactory httpClientFactory)
    {
        //factory was registered, but the HttpClientName was 'null'.
        if (aadIssuerValidatorOptions?.Value?.HttpClientName != null && httpClientFactory != null)
        {
            _configManager =
            new ConfigurationManager<IssuerMetadata>(
                Constants.AzureADIssuerMetadataUrl,
                new IssuerConfigurationRetriever(),
                httpClientFactory.CreateClient(aadIssuerValidatorOptions.Value.HttpClientName));
        }
        else
       {
            _configManager =
            //default ConfigurationManager constructor will create HttpDocumentRetriever with default constructor which will lead to HttpClient isntance created manually.
            new ConfigurationManager<IssuerMetadata>(                 
                Constants.AzureADIssuerMetadataUrl,
                new IssuerConfigurationRetriever());
        }
    }
```

And here is [ConfigurationManager](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs) constructor that is called when no HttpClient name is assigned:
```csharp
/// <summary>
/// Instantiates a new <see cref="ConfigurationManager{T}"/> that manages automatic and controls refreshing on configuration data.
/// </summary>
/// <param name="metadataAddress">The address to obtain configuration.</param>
/// <param name="configRetriever">The <see cref="IConfigurationRetriever{T}"/></param>
public ConfigurationManager(string metadataAddress, IConfigurationRetriever<T> configRetriever)
    : this(metadataAddress, configRetriever, new HttpDocumentRetriever())
{
}
```
Also, [HttpDocumentRetriever](https://raw.githubusercontent.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/dev/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs) will use static readonly HttpClient in case specific instance is not passed in the constructor.

# Current workaround
In order to make MicrosoftIdentityIssuerValidatorFactory use HttpClient I need, I have to separately configure AadIssuerValidatorOptions:
```csharp
services.Configure<AadIssuerValidatorOptions>(validatorOptions =>
{
    validatorOptions.HttpClientName = ""; //desired HttpClientName goes here.
});
```

# Proposal
To make this configuration more obvious, would be great to have HttpClientName defined inside `MicrosoftIdentityOptions`, and not inside a separate `AadIssuerValidatorOptions`.
This might help to reduce time needed to find a solution, as `AadIssuerValidatorOptions` is mentioned only in the Wiki's changelog.

**Comment by jennyf19** [comment]
thanks for all the details @Lex45x

**Comment by jmprieur** [comment]
This issue is no longer relevant, as AadIssuerValidator moved to Microsoft.IdentityModel
