### ISSUE TITLE
Update scenario landing page documents

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#121]
@jmprieur

**Comment by jmprieur** [comment]
For Web apps: PR is https://github.com/MicrosoftDocs/azure-docs-pr/pull/112615

**Comment by jmprieur** [comment]
@mmacy : I'm blocking this one as we'll do API changes (required by the ASP.NET Core team to integrate the templates in .NET 5)

**Comment by mmacy** [comment]
@jmprieur I'm starting on the .NET Core tutorials and quickstart soon - you may consider this your 3-day warning. :smile:

**Comment by jmprieur** [comment]
Web App scenarios: https://github.com/MicrosoftDocs/azure-docs-pr/pull/122288
Web API scenarios: https://github.com/MicrosoftDocs/azure-docs-pr/pull/122459
