### ISSUE TITLE
[Bug] Unable to call downstream API (Azure Service Management API). 

### ISSUE THREAD

**Issue by gmantri** [AzureAD/microsoft-identity-web#1217]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [x] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment.

**Repro**

I have a Web API that is protected by Azure AD. Using a front-end application, I am able to successfully acquire token for the Web API. Now what I want to do is call Azure Service Management API from my API however when I try to acquire the token, I am getting the following error:

```
Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException: IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent.
```

Here's what I did:

1. In my API App's manifest, I have added the front-end application's client id under `knownClientApplications`.

```
"knownClientApplications": ["font-end-application-client-id"],
```

2. Here's my `appSettings.json` file look like:

```
  "ApiSettings": {
    "Instance": "https://login.microsoftonline.com/",
    "ClientId": "API application's client id",
    "ClientSecret": "API application's client secret",
    "TenantId": "my tenant id",
    "Audience": "api://some-guid",
    "IssuerEndpoint": "https://sts.windows.net/",
    "AzureManagementEndpoint": "https://management.azure.com/",
    "GraphApiEndpoint": "https://graph.windows.net/"
  },
  "AzureServiceManagementApiSettings": {
    "BaseUrl": "https://management.azure.com",
    "Scopes": "user_impersonation"
  },
```

3. This is what I did in my `Startup.cs` file:

```
_ = services
    .AddMicrosoftIdentityWebApiAuthentication(Configuration, "ApiSettings")
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddDownstreamWebApi("AzureServiceManagementApi", Configuration.GetSection("AzureServiceManagementApiSettings"))
    .AddInMemoryTokenCaches();
```

4. And finally this is how I am getting the token in my controller:

```
string token = await _tokenAcquisition.GetAccessTokenForUserAsync(new[] {"https://management.azure.com/user_impersonation"});
```

Please note that the user has already consented to both my API application and `Azure Service Management API`.

**Expected behavior**
I should be able to acquire token for Azure Service Management API.

**Actual behavior**
I am getting the following error:

```
Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException: IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent. 
 ---> MSAL.NetCore.4.30.1.0.MsalUiRequiredException: 
	ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS65001: The user or administrator has not consented to use the application with ID 'my-application-id' named 'my-application-name'. Send an interactive authorization request for this user and resource.
Trace ID: 476a2aba-3239-469f-876b-8db8faad6c00
Correlation ID: f4ca50f2-ee1c-4b8e-ac19-bfbf22022ed5
Timestamp: 2021-05-26 14:23:38Z
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.HandleTokenRefreshError(MsalServiceException e, MsalAccessTokenCacheItem cachedAccessTokenItem)
   at Microsoft.Identity.Client.Internal.Requests.OnBehalfOfRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenOnBehalfOfParameters onBehalfOfParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForWebApiToCallDownstreamApiAsync(IConfidentialClientApplication application, String authority, IEnumerable`1 scopes, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
	StatusCode: 400 
	ResponseBody: {"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID 'my-application-id' named 'my-application-name'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 476a2aba-3239-469f-876b-8db8faad6c00\r\nCorrelation ID: f4ca50f2-ee1c-4b8e-ac19-bfbf22022ed5\r\nTimestamp: 2021-05-26 14:23:38Z","error_codes":[65001],"timestamp":"2021-05-26 14:23:38Z","trace_id":"476a2aba-3239-469f-876b-8db8faad6c00","correlation_id":"f4ca50f2-ee1c-4b8e-ac19-bfbf22022ed5","suberror":"consent_required"} 
	Headers: Cache-Control: no-store, no-cache
```

**Additional context**
I can call other actions in my controller just fine using the access token I acquired for my application.

**Comment by jennyf19** [comment]
@gmantri In the app registration, the web API needs to declare that it needs to access ARM and this needs to be pre-consented by a tenant admin. See [this sample](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph) for more details.

**Comment by gmantri** [comment]
@jennyf19 - Thanks for replying. I was actually looking at that sample only just now. Unfortunately I don't think that is the case. To the best of my knowledge, ARM API's are always executed in context of the signed-in user. In fact, there's no option to grant admin consent for ARM API. For this API, "admin consent required" is always "No". Same is not true for Graph API where certain scopes require admin consent.

**Comment by jennyf19** [comment]
@gmantri True, but the admin granting consent does pre-approval, which is needed for web APIs.

**Comment by gmantri** [comment]
@jennyf19 - Sadly no luck :(. I gave admin consent as well and still the same result.

<img width="915" alt="Screenshot 2021-05-26 at 9 39 12 PM" src="https://user-images.githubusercontent.com/2417437/119694475-df791f80-be6a-11eb-98d4-8bf6e57f8c3c.png">

**Comment by jennyf19** [comment]
@gmantri did you clear the cache in the client? also, the first level API should be called w/`/.default` as in `{apiURI/.default}`

You need to do [this](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/README.md#configure-known-client-applications-for-service-todolistservicems-identity-dotnet-native-aspnetcore-v2)

and [this](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/89f54ad1599c4089ba0d98d6be68ee4d362b3134/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListClient/App.config#L36).

**Comment by gmantri** [comment]
@jennyf19 - Apologies for the delayed response. It finally worked! 

I ended up starting from scratch. Deleted the old applications and created brand new ones. This time I followed the instructions you linked above to the T. BTW, I need not give admin consent to the app for executing ARM APIs.

Thanks for all your help. I really appreciate it.

**Comment by jennyf19** [comment]
awesome. thanks for the follow-up. @gmantri and glad it's working.
