### ISSUE TITLE
[Feature Request] client assertions

### ISSUE THREAD

**Issue by schmitch** [AzureAD/microsoft-identity-web#1224]
**Is your feature request related to a problem? Please describe.**
it would be great to support client assertions, since they are often more secure than client secrets

**Comment by jmprieur** [comment]
Duplicate of #203

**Comment by jmprieur** [comment]
@schmitch Microsoft.Identity.Web supports certificate credentials (which produce client assertion).
What is your specific scenario? how would you use client assertions? which kind of claims would you like to sign?

**Comment by schmitch** [comment]
@jmprieur what exactly do you mean with "supports certificate credentials" basically what we want is instead of using a `client_secret` we want to upload a public certificate and use the public cert+private key to actually generate assertions, so that a `client_secret` is not needed. we now that it works: https://docs.microsoft.com/de-de/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token-with-a-certificate-credential but I could not find any good docs, how to use that with `microsoft.identity.web`.

**Comment by jmprieur** [comment]
@schmitch this is supported: https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates

**Comment by schmitch** [comment]
oha, sorry @jmprieur i did not see that.

I always looked at the official docs.microsoft.com, because most often that documentation is really good! so I did not know that there is a wiki that explain how to add that.

so sorry for the disturbance.

**Comment by jmprieur** [comment]
No worries, @schmitch : we try to move this wiki doc to docs.ms, but this takes a lot of time :(

**Comment by schmitch** [comment]
yeah I can understand that, so now worries ! I'm a developer by myself and I hate writing docs ;-)
