### ISSUE TITLE
[Feature Request] Simplify AuthenticationBuilder.AddSignIn extension method for web app

### ISSUE THREAD

**Issue by AquilaSands** [AzureAD/microsoft-identity-web#123]
**Is your feature request related to a problem? Please describe.**
On the AddSignIn method signature https://github.com/AzureAD/microsoft-identity-web/blob/7d33e9f4351ac679382cd3c0f1bc61140376e34f/src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs#L60-L66 is it necessary to have both the `configureOpenIdConnectOptions` and `configureMicrosoftIdentityOptions` parameters?

Given that `MicrosoftIdentityOptions` inherits from `OpenIdConnectOptions` I find this confusing as it is not clear which takes precedence or even if the inherited options must be set in the `configureOpenIdConnectOptions` delegate or if setting everything in the  `configureMicrosoftIdentityOptions` delegate is fine.

**Describe the solution you'd like**
Remove the `configureOpenIdConnectOptions` parameter so there is a single point of configuration.

**Comment by jmprieur** [comment]
The same thing happens with .AddWebAppCallsProtectedWebApi between the MicrosoftIdentityOptions and the ConfidentialClientApplicationOptions

**Comment by jmprieur** [comment]
I wonder if we could not use an approach such as this one: https://github.com/dotnet/aspnetcore/blob/master/src/Azure/AzureAD/Authentication.AzureAD.UI/src/AzureADOpenIdConnectOptionsConfiguration.cs where the OpenIdConnectOptions were computed from the AzureADOptions in AzureAD.UI

cc: @jennyf19 @pmaytak @henrik-me

**Comment by jmprieur** [comment]
@Tratcher: what would be the best way of achieving this?

**Comment by Tratcher** [comment]
> Given that `MicrosoftIdentityOptions` inherits from `OpenIdConnectOptions`

Why does it derive from OIDC options? I didn't see anywhere where that relationship was used. The Options model wasn't designed with inherited options in mind, this might be difficult to take advantage of.

> I wonder if we could not use an approach such as this one ... where the OpenIdConnectOptions were computed from the AzureADOptions in AzureAD.UI

That has been one of the biggest complaints about the existing packages, it's hard to configure any OpenIdConnectOptions property that's not exposed on AzureADOptions. The derivation relationship makes things more interesting though, as all properties will be available. Options has a [DI pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#use-di-services-to-configure-options) that should allow you to configure the OpenIdConnectOptions by injecting an `IOptions<MicrosoftIdentityOptions>` and then manually copying everything across.

Not sure how you'd handle the JWT scenario though, it exposes a few different options from OIDC.

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
