### ISSUE TITLE
Azure AD B2C - Blazor Server Side

### ISSUE THREAD

**Issue by raedg2000** [AzureAD/microsoft-identity-web#1231]
Dears,

I am developing a Blazor server side app and using Azure AD B2C. I am having an issue with the signout method. I need to navigate to the home page. Is there a way to modify the RedirectURl in the signout method of the AccountController?

regards,
Raed

**Comment by jmprieur** [comment]
You can override the SignedOut page.
See https://github.com/AzureAD/microsoft-identity-web/wiki/customization#ui-customization
