### ISSUE TITLE
[Bug] Logout error when using Easy Auth v2

### ISSUE THREAD

**Issue by jwevansgam** [AzureAD/microsoft-identity-web#1234]
**Which version of Microsoft Identity Web are you using?**
1.10

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)
    * [x] Sign-out users

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**

The Issue is described in this discussion #1222

Basic summary is that the the environment variable WEBSITE_AUTH_LOGOUT_PATH has been deprecated with App Service Authentication v2 (Easy Auth) so I get the below exception when logging out. 

**Expected behavior**
The user should be logged out of the Easy Auth session.

**Actual behavior**
The following exception is thrown 

`Value cannot be null or empty: (Parameter: 'localUrl')`

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@navyasric what would be your recommendation?

**Comment by jmprieur** [comment]
•	EasyAuth took a breaking change by not adding the logout path environment variable in v2 where it would be added in v1.
•	if auth is enabled on the app (the enabled env var is set to true), then we can assume no WEBSITE_AUTH_LOGOUT_PATH environment variable to mean that the logout path is at WEBSITE_AUTH_API_PREFIX/logout, and if now api prefix is specified, then the logout path is at the default "/.auth/logout"

**Comment by jwevansgam** [comment]
What a great turnaround, 13 days from reporting to being added to the code base. Thanks so much for this. I have just tested today and can confirm that this has resolved my issue.

**Comment by jmprieur** [comment]
Thanks for confirming, @jwevansgam
