### ISSUE TITLE
[Bug] NullReferenceException when calling GetAccessTokenForAppAsync to get App Token

### ISSUE THREAD

**Issue by tjkb** [AzureAD/microsoft-identity-web#1236]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.12.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [X] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
The app is in production and I have **upgraded from version 1.10.0** to 1.11.0 when this error started to appear. Also in 1.12.0 it is not fixed.

**Repro**

Getting an app token like this
```csharp
var accessToken = await tokenAcquisition.GetAccessTokenForAppAsync("https://graph.microsoft.com/.default", tenant: "the-tenant-id");
```

Startup.cs
```csharp
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
  .AddMicrosoftIdentityWebApp(configuration)
  .EnableTokenAcquisitionToCallDownstreamApi()
  .AddDistributedTokenCaches();
```

appsettings.json
```json
"AzureAd": {
  "Instance": "https://login.microsoftonline.com/",
  "TenantId": "common",
  "ClientId": "the-client-id",
  "ClientCertificates": [
    {
      "SourceType": "StoreWithThumbprint",
      "CertificateStorePath": "CurrentUser/My",
      "CertificateThumbprint": "the-thumbprint"
    }
  ],
    "CallbackPath": "/signin-oidc"
}
```

**Expected behavior**
The access token should be returned.

**Actual behavior**
The following exception is thrown:
```
Object reference not set to an instance of an object.
   at Microsoft.Identity.Web.MergedOptions.PrepareAuthorityInstanceForMsal()
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.<GetAccessTokenForAppAsync>d__18.MoveNext()
```

**Possible solution**
I don't know, it all worked up to version 1.10.0 with the exact same code.

**Additional context / logs / screenshots**
none

**Comment by jmprieur** [comment]
@tjkb thanks for reporting this regression
We'll investigate and fix. 

Does it work if you specify the authenticationScheme?

```CSharp
var accessToken = await tokenAcquisition.GetAccessTokenForAppAsync("https://graph.microsoft.com/.default", tenant: "the-tenant-id", authenticationScheme: OpenIdConnectDefaults.AuthenticationScheme);
```

**Comment by jmprieur** [comment]
@tjkb 
we cannot repro it. do you have repro steps? or can you please enable more logs? https://github.com/AzureAD/microsoft-identity-web/wiki/Logging

**Comment by tjkb** [comment]
@jmprieur setting the authentication scheme does not help. So I'll try with more logs or provide more detailed repro steps. I'll let you know. Thanks for the help so far

**Comment by tjkb** [comment]
We don't have a solution yet, but it's somehow related to our container. The error happens only in an Azure Function. In the Web App it works. So we have to look on our side. Thanks for the help 👍
