### ISSUE TITLE
[Feature Request] Add support for CancellationToken

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1239]
**Is your feature request related to a problem? Please describe.**
MSAL.NET 4.32.0 brings support for: `CancellationToken` on `GetAccountAsync`, `RemoveAsync` and `TokenCacheNotificationArgs`.

```CSharp
 public abstract class ClientApplicationBase : IClientApplicationBase 
{
  public Task<IAccount> GetAccountAsync(string accountId, CancellationToken cancellationToken=default(CancellationToken));
  public Task RemoveAsync(IAccount account, CancellationToken cancellationToken=default(CancellationToken));
 }
```

```CSharp
    public sealed class TokenCacheNotificationArgs {
        public CancellationToken CancellationToken { get; }
    }
```

**Describe the solution you'd like**
- Have new overrides in MsalAbstractTokenCacheProvider to support the cancellation tokens, implemented in MsalDistributedCacheAdapter. (trying avoiding a breaking change)
- Add a CancellationToken property in [TokenAcquisitionOptions](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/TokenAcquisitionOptions.cs) and, if available use it in TokenAcquisition in calls to:
  - AcquireTokenXXX methods
  - GetAccountAsync()
  - RemoveAsync

**Additional context**
MSAL.NET 4.32.0 also supports:
- `.WithTenant()` in all flows (which could be used instead of `.WithAuthority`). This would be to remove technical debt
- `WithExtraHttpHeaders` on AcquireTokenXXX

**Comment by jennyf19** [comment]
Fixed in [1.13 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.13.0).
