### ISSUE TITLE
Override appsettings clientId, clientSecret for specific scenarios 

### ISSUE THREAD

**Issue by ferronsw** [AzureAD/microsoft-identity-web#1240]
Hello,

I'm using version 1.12 of the Microsoft.Identity.Web package. 
I need to acquire an accesstoken for a background app registration that only contains app permissions.
The background app registration has another clientid and secret then the delegated permissions app where the users sign in with.
How can I achieve this?

**Comment by jmprieur** [comment]
@ferronsw 
you could use the multiple authentication scheme: https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes.

**Comment by ferronsw** [comment]
Thanks! I will give it a try.

**Comment by jennyf19** [comment]
closing as answered, but feel free to reopen if you have further questions @ferronsw
