### ISSUE TITLE
[Bug] B2C API token validation reports invalid issuer

### ISSUE THREAD

**Issue by mrochon** [AzureAD/microsoft-identity-web#1249]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

1.12.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [X ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
Sample app in development.

**Repro**
1. Token to API obtained from B2C includes issuer: https://mrochonb2cprod.b2clogin.com/cf6c572c-c72e-4f31-bd0b-75623d040495/v2.0/
2. Fiddlr shows that the API is obtaining .well-known metadata with the same issuer
3. App errors with: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDW10303: Issuer: 'https://mrochonb2cprod.b2clogin.com/cf6c572c-c72e-4f31-bd0b-75623d040495/v2.0/', does not match any of the valid issuers provided for this application. Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDW10303: Issuer: 'https://mrochonb2cprod.b2clogin.com/cf6c572c-c72e-4f31-bd0b-75623d040495/v2.0/', does not match any of the valid issuers provided for this application. 

```json
  "B2C": {
    "Instance": "https://login.microsoftonline.com/tfp/",
    //"Instance": "https://mrochonb2cprod.onmicrosoft.com",
    "TenantId": "cf6c572c-c72e-4f31-bd0b-75623d040495",
    "Domain": "mrochonb2cprod.onmicrosoft.com",
    "ClientId": "5e976aba-65ee-4185-8fdc-d317f7c34959",
    "RedirectUri": "https://b2crestapis",
    "SignUpSignInPolicyId": "B2C_1_BasicSUSI"
  }
```

**Expected behavior**
Issuer should be accepted as valid

**Actual behavior**
Error: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDW10303: Issuer: 'https://mrochonb2cprod.b2clogin.com/cf6c572c-c72e-4f31-bd0b-75623d040495/v2.0/', does not match any of the valid issuers provided for this application. 

**Possible solution**
Will experiment with TokenValidationParameters as per some other bugs mentioned here.

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@mrochon : would you mind trying the following configuration:

```Json
"Instance": "https://mrochonb2cprod.b2clogin.com",
```

**Comment by mrochon** [comment]
Yes, that worked. No errors. Thanks.
