### ISSUE TITLE
[Bug] Wrong callback 'state' without decodeURIComponent

### ISSUE THREAD

**Issue by cention-sany** [AzureAD/microsoft-identity-web#125]
**Which Version of Microsoft Identity Web are you using ?**
I no idea. Sorry about this. Actually I not even sure if this is the right place filing this problem.

**Where is the issue?**
* Web App
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Oauth2 Authorization Code Flow
    * [x] Callback `state` with wrong data

**Is this a new or existing app?**
* new app

**Repro**
Add an application with permission `EWS.AccessAsUser.All offline_access openid profile` on tenant A. Then, uses a non-admin user of Exchange Online of tenant B to authenticate the application using oauth2 authorization code flow, with query parameter `state` uses something like `https%3a%2f%2fcloud.cust.cention.se%2fng%2foauth%3fevent%3doauth.microsoft.ews%26provider%3dMicrosoft%26service%3dEWS` which is encodeURIComponent of string `https://cloud.cust.cention.se/ng/oauth?event=oauth.microsoft.ews&provider=Microsoft&service=EWS`. Microsoft will return `Need admin approval`. Then if user clicks `Return to the application without granting consent` will get this bug.

**Expected behavior**
I expect to get this:
```csharp
https://d5ab662b.ngrok.io/oauth/redirect?error=access_denied&error_subcode=cancel&state=https%3a%2f%2fcloud.cust.cention.se%2fng%2foauth%3fevent%3doauth.microsoft.ews%26provider%3dMicrosoft%26service%3dEWS
```
which my application oauth2 redirect URI is `https://d5ab662b.ngrok.io/oauth/redirect`.

**Actual behavior**
I got this callback from Microsoft. Note the `state` value is wrong and different from above:
```csharp
https://d5ab662b.ngrok.io/oauth/redirect?error=access_denied&error_subcode=cancel&state=https%253a%252f%252fcloud.cust.cention.se%252fng%252foauth%253fevent%253doauth.microsoft.ews%2526provider%253dMicrosoft%2526service%253dEWS
```

**Possible Solution**
Microsoft server should decodeURIComponent first before encodeURIComponent again when returning this type of error.

**Additional context/ Logs / Screenshots**
This error screenshot:
![image](https://user-images.githubusercontent.com/12839593/80107730-08ffb180-85ae-11ea-9c67-19a80ec6a9ad.png)
Note that if an admin user select `Cancel` instead of `Accept` the consent, the state return the correct callback data:
`https://d5ab662b.ngrok.io/oauth/redirect?error=consent_required&error_description=AADSTS65004%3a+User+declined+to+consent+to+access+the+app.%0d%0aTrace+ID%3a+5e587149-19c8-4f98-8500-369594c82700%0d%0aCorrelation+ID%3a+da32b2fd-4cec-41e9-872f-5a67d6fff68f%0d%0aTimestamp%3a+2020-04-23+11%3a38%3a08Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d65004&state=https%3a%2f%2fcloud.cust.cention.se%2fng%2foauth%3fevent%3doauth.microsoft.ews%26provider%3dMicrosoft%26service%3dEWS`

EDIT:
* Explain the redirect URI.
* Update Repro steps.

**Comment by jmprieur** [comment]
@cention-sany : 
I'm a big confused by this issue?
- what is https://d5ab662b.ngrok.io ? this does not seem to be Azure AD?
- What do you mean by Microsoft server ?

Do you have repro steps for us? like a configuration for one of the test apps?

**Comment by cention-sany** [comment]
`https://d5ab662b.ngrok.io/oauth/redirect` is my application's oauth2 redirect URI.

**Comment by jmprieur** [comment]
We cannot repro this.
Please try with the latest version of Microsoft.Identity.Web and the project templates. 

Closing for now
feel free to reopen if this still repros (with repro steps)
