### ISSUE TITLE
[Feature Request] Token acquisition for downstream API when using OIDC

### ISSUE THREAD

**Issue by markhobson** [AzureAD/microsoft-identity-web#1256]
**Is your feature request related to a problem? Please describe.**
Configuring a webapp to authenticate against AzureAD and provide the JWT to a web API is [well documented](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-configuration) and works. It's not so clear how to achieve this with a different OIDC identity server, like Okta, though.

For example, to authenticate against AzureAD and store the token:

```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
    .EnableTokenAcquisitionToCallDownstreamApi(new[] { "api://xxx/access_as_user" })
    .AddInMemoryTokenCaches();
```

The token can then be obtained from `ITokenAcquisition` to invoke the downstream web API:

```
var accessToken = await tokenAcquisition.GetAccessTokenForUserAsync(new[] { "api://xxx/access_as_user" });
```

Now, switching from AzureAD to a different OIDC identity server, our configuration becomes:

```
services
    .AddAuthentication(options =>
    {
        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
    })
    .AddCookie()
    .AddOpenIdConnect(options => Configuration.GetSection("OpenIdConnect").Bind(options));
//  .EnableTokenAcquisitionToCallDownstreamApi(new[] { "access_as_user" })
//  .AddInMemoryTokenCaches();
```

But `EnableTokenAcquisitionToCallDownstreamApi` is not available after `AddOpenIdConnect`, only after `AddMicrosoftIdentityWebApp` which is AzureAD specific.

(Note that `AddInMemoryTokenCaches` _is_ available without `AddMicrosoftIdentityWebApp` via the extension method `services.AddInMemoryTokenCaches()`.)

**Describe the solution you'd like**
I would like to see a non-AzureAD-specific equivalent of `EnableTokenAcquisitionToCallDownstreamApi` as an extension method on `AuthenticationBuilder` that can be used following `AddOpenIdConnect`:

```
services
    .AddAuthentication(...)
    ...
    .AddOpenIdConnect(options => Configuration.GetSection("OpenIdConnect").Bind(options))
    .EnableTokenAcquisitionToCallDownstreamApi(new[] { "access_as_user" });
services.AddInMemoryTokenCaches();
```

So that I can then use `ITokenAcquisition` to obtain the token and invoke my web API, as before.

**Describe alternatives you've considered**
I've considered lifting the [pertinent parts of EnableTokenAcquisitionToCallDownstreamApi](https://github.com/AzureAD/microsoft-identity-web/blob/c29f1a7950b940208440bebf0bcb524a7d6bee22/src/Microsoft.Identity.Web/WebAppExtensions/WebAppCallsWebApiAuthenticationBuilderExtensions.cs#L140), but this requires access to the internal type `ITokenAcquisitionInternal`. This would then entail lifting `TokenAcquisition`, which is a large class, and it's unclear how much of this implementation is tied to AzureAD.

There is also [`RemoteAuthenticationOptions.SaveTokens`](https://github.com/dotnet/aspnetcore/blob/6a929c3796f048d619bdd05969972d3a84669aac/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L135) that can store the token for later access from `IHttpContextAccessor` (as suggested by [Okta](https://developer.okta.com/blog/2017/06/29/oidc-user-auth-aspnet-core#add-authentication) and [Auth0](https://auth0.com/docs/quickstart/webapp/aspnet-core#store-and-retrieve-the-tokens)):

```
var accessToken = await httpContextAccessor.HttpContext.GetTokenAsync("access_token");
```

Although this persists the token in the authentication cookie, which isn't ideal. It also raises questions about how access token refresh and [incremental consent](https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access) would work in this scenario.

**Additional context**
N/A

**Comment by jmprieur** [comment]
This scenario is possible in rel/v2
services.AddTokenAcquisistion(), however Token acquisition uses MSAL.NET which is only for AAD, AAD b2c, AAD CIAM
