### ISSUE TITLE
[Bug] Graph WithAuthenticationScheme not working with multiple schemes

### ISSUE THREAD

**Issue by ferronsw** [AzureAD/microsoft-identity-web#1261]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Microsoft Identity Web 1..12.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [X] Sign-in users and call web APIs
* Token cache serialization
     * [X] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of Microsoft Identity Web.

**Repro**
```
await graphClient.Groups.Request().WithAuthenticationScheme("AzureAdBackground").WithAppOnly(true, tenantId).GetAsync();
```

**Expected behavior**
Get the group with the specified authenticationscheme and app only permissions

**Actual behavior**
Requests with the other authenticationschema called "AzureAd"

**Possible solution**
None

**Additional context / logs / screenshots**

Startup.cs
```
            //Add authentication with inMemory cache Controlplane app registration
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApp(options =>
            {
                Configuration.Bind("AzureAd", options);
            }).EnableTokenAcquisitionToCallDownstreamApi(options => Configuration.Bind("AzureAd", options), new string[] { "https://graph.microsoft.com/.default" })
                .AddMicrosoftGraph(Configuration.GetSection("Graph"))
                .AddInMemoryTokenCaches();

            //Add authentication with inMemory cache client background app registration
            services.AddAuthentication()
            .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAdBackground"), "AzureAdBackground", "CookiesAzureAdBackground")
                .EnableTokenAcquisitionToCallDownstreamApi(new string[] { "https://graph.microsoft.com/.default" })
                .AddMicrosoftGraph(Configuration.GetSection("Graph"))
                .AddInMemoryTokenCaches();

```

appsettings (AzureAdBackground is multi tenant)

```
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "<domain>.onmicrosoft.com",
    "TenantId": "<tenantid>",
    "ClientId": "<clientid>",
    "ClientSecret": "<clientsecret>",
    "Scopes": "openid email profile offline_access",
    "CallbackPath": "/signin-oidc",
    "BaseUrl": "https://localhost:44386"
  },
  "AzureAdBackground": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "<domain>.onmicrosoft.com",
    "TenantId": "organizations",
    "ClientId": "<clientid>",
    "ClientSecret": "<clientsecret>"
  },
 "Graph": {
    "BaseUrl": "https://graph.microsoft.com/v1.0",
    "Scopes": "https://graph.microsoft.com/.default"
  }
```
Error message:

```
"AADSTS700016: Application with identifier '<clientid>' was not found in the directory '<tenantid>'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 45ef2129-9f0a-4dd7-ae85-d166bafb7300\r\nCorrelation ID: c32e21ab-171f-488a-8ce7-8472b0e83756\r\nTimestamp: 2021-06-11 10:41:36Z"
```

**Comment by jmprieur** [comment]
@ferronsw.
I see that you have 2 authentication schemes:
- OpenIdConnectDefaults.AuthenticationScheme (and this is the default one). This one is associated with the "AzureAD" configuration, but its name is "OpenIdConnect" (the value of OpenIdConnectDefaults.AuthenticationScheme)
- "AzureAdBackground": which is the other one.

Do we agree that you don't have an authenticationScheme named "AzureAD" ?

**Comment by ferronsw** [comment]
@jmprieur 
I agree. I have changed it:

```
            //Add authentication with inMemory cache Controlplane app registration
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApp(options =>
            {
                Configuration.Bind("AzureAD", options);
            }).EnableTokenAcquisitionToCallDownstreamApi(options => Configuration.Bind("AzureAD", options), new string[] { "https://graph.microsoft.com/.default" })
                .AddMicrosoftGraph(Configuration.GetSection("Graph"))
                .AddInMemoryTokenCaches();
```

```
  "AzureAD": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "<domain>.onmicrosoft.com",
    "TenantId": "<tenantid>",
    "ClientId": "<clientid>",
    "ClientSecret": "<clientsecret>",
    "Scopes": "openid email profile offline_access",
    "CallbackPath": "/signin-oidc",
    "BaseUrl": "https://localhost:44386"
  },
  "AzureAdBackground": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "<domain>.onmicrosoft.com",
    "TenantId": "organizations",
    "ClientId": "<clientid>",
    "ClientSecret": "<clientsecret>"
  },
 "Graph": {
    "BaseUrl": "https://graph.microsoft.com/v1.0",
    "Scopes": "https://graph.microsoft.com/.default"
  }
```

Unfortunatly I still have the same problem.

**Comment by ferronsw** [comment]
@jmprieur any ideas how to solve this problem?

**Comment by ferronsw** [comment]
@jmprieur @jennyf19 I think I found where it goes wrong. Line 371 from 'TokenAcquisition.cs' the ConfidentialClient is build:
```
var application = GetOrBuildConfidentialClientApplication(mergedOptions);
```

The mergedOptions contain the information I supplied for the AzureAdBackground scheme.

The method 'GetOrBuildConfidentialClientApplication' checks if there is already a ConfidentialClientApplication:

```
internal /* for testing */ IConfidentialClientApplication GetOrBuildConfidentialClientApplication(
           MergedOptions mergedOptions)
        {
            if (_application == null)
            {
                lock (_applicationSyncObj)
                {
                    if (_application == null)
                    {
                        _application = BuildConfidentialClientApplication(mergedOptions);
                    }
                }
            }

            return _application;
        }
```

This '_application' is not null but contains the information of the AzureAd authenticationscheme.
How can we fix this?

**Comment by jmprieur** [comment]
@ferronsw TokenAcquisition is a scoped service ... so it should be recreated for each query.

Can you please provide a bit more context on how you call Graph? it it from a controller action? . 
Do you have precise repro steps.

**Comment by ferronsw** [comment]
@jmprieur that is what I thought to.

I call a controller where the GraphServiceClient is injected.
I call this method with an ajax (xhr) request:

```
        [HttpGet]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> GetMultiGroups(Guid customerId, string searchString)
        {
            var customer = _context.Customers.Where(x => x.Id == customerId).FirstOrDefault();
            return Json(await GraphService.GetMultiGroups(_graphServiceClient, searchString, customer.TenantId));
        }

```
GraphService is a static class.

GetMultiGroups method in GraphService class:

```
        public static async Task<List<SelectListVM>> GetMultiGroups(GraphServiceClient graphClient, string searchString, string tenantId)
        {
            IGraphServiceGroupsCollectionPage groups;

            if (searchString == "" || searchString == "undefined" || searchString == null)
            {
                groups = await graphClient.Groups.Request().WithAuthenticationScheme("AzureAdBackground")
                    .WithAppOnly(true, tenantId).GetAsync();
            }
            else
            {
                groups = await graphClient.Groups.Request().WithAuthenticationScheme("AzureAdBackground")
                    .WithAppOnly(true, tenantId).Filter(string.Format("startswith(displayName, '{0}')", searchString)).GetAsync();
            }

            List<SelectListVM> groupSelectList = new List<SelectListVM>();

            foreach (var group in groups)
            {
                groupSelectList.Add(new SelectListVM { id = " " + ";" + group.Id + ";" + group.DisplayName , text = group.DisplayName });
            }

            return groupSelectList.OrderBy(x => x.text).ToList() ?? new List<SelectListVM>();

        }
```

**Comment by jmprieur** [comment]
@ferronsw : why don't you inject the GraphServiceClient provided by Microsoft.Identity.Web in your controller?
See https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-call-api?tabs=aspnetcore#option-1-call-microsoft-graph-with-the-sdk

**Comment by ferronsw** [comment]
@jmprieur I do inject it, but I pass it to the static function.

```
 public CustomersController(
            GraphServiceClient graphServiceClientr)
        {
          
            _graphServiceClient = graphServiceClient;
        }
```

As you can see I pass it to the static function ("GraphService.GetMultiGroups").

```
[HttpGet]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> GetMultiGroups(Guid customerId, string searchString)
        {
            var customer = _context.Customers.Where(x => x.Id == customerId).FirstOrDefault();
            return Json(await GraphService.GetMultiGroups(_graphServiceClient, searchString, customer.TenantId));
        }
```

```
 public static class GraphService
 {
      public static async Task<List<SelectListVM>> GetMultiGroups(GraphServiceClient graphClient, string searchString, string tenantId)
        {
            IGraphServiceGroupsCollectionPage groups;

            if (searchString == "" || searchString == "undefined" || searchString == null)
            {
                groups = await graphClient.Groups.Request().WithAuthenticationScheme("AzureAdBackground")
                    .WithAppOnly(true, tenantId).GetAsync();
            }
            else
            {
                groups = await graphClient.Groups.Request().WithAuthenticationScheme("AzureAdBackground")
                    .WithAppOnly(true, tenantId).Filter(string.Format("startswith(displayName, '{0}')", searchString)).GetAsync();
            }

            List<SelectListVM> groupSelectList = new List<SelectListVM>();

            foreach (var group in groups)
            {
                groupSelectList.Add(new SelectListVM { id = " " + ";" + group.Id + ";" + group.DisplayName , text = group.DisplayName });
            }

            return groupSelectList.OrderBy(x => x.text).ToList() ?? new List<SelectListVM>();

        }
 }
```
That shouldn't be a problem right?

**Comment by Luismvm** [comment]
I'm also experiencing issue, the repro steps are different but the issue seems to be the same.

It's very easy to repo:

- add 2 auth schemes, one for AAD and one for B2C, 
- try to use TokenAcquisition to call graph with the AAD scheme
- It will always try to fetch the token against the B2C token endpoint
- Remove the B2C scheme, everything works fine

When having two authentication schemes, one with AAD and one with AAD B2C, the TokenAcquisition, seems to always call the B2C endpoints.

Here's my code:

`
            services.AddAuthentication("AAD")
                    .AddMicrosoftIdentityWebApi(Configuration.GetSection("AzureAd"), "AAD")
                    .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddInMemoryTokenCaches();

            services.AddAuthentication("B2C")
                    .AddMicrosoftIdentityWebApi(Configuration.GetSection("AzureAdB2C"), "B2C");

`

I've had fiddler running I can confirm, as soon as I add the B2C credentials, the token acquisition service tries to retrieve the token against the B2C token endpoints, even if i'm not enabling downstreamapi for that scheme.

I didn't go deep into the code but it might have to do with the mergedoptions in the [TokenAcquisition.cs](https://github.com/AzureAD/microsoft-identity-web/blob/6b506ebb241b69dd79975b5899418af825dc1882/src/Microsoft.Identity.Web/TokenAcquisition.cs#L134).

**Comment by jennyf19** [comment]
@Luismvm with `.AddAuthentication()` the last one is taken if you define a value for the scheme. So don't define anything in `.AddAuthentication()` for both, and then you give the scheme in the `.AddMicrosoftIdentityWebApi(Configuration.GetSection("AzureAd"), "AAD")` for both respectively.

Do you set the authentication schemes authorize property on the authorize attribute? example: [B2C controller](https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes#controllers): `[Authorize(AuthenticationSchemes = "B2C")]`

**Comment by Luismvm** [comment]
@jennyf19 I've tried without the schemes in the AddAuthentication too, same issue still happens. I've also tried with the authorization attribute set to either AAD only, same issue... as long as both schemes are provided, the TokenAcquisition always uses the B2C one.

**Comment by jmprieur** [comment]
@ferronsw : I don't think you should really use both schemes in the same request. My recommendation would be to trigger another request (for instance by navigating to another page/controller).

**Comment by jmprieur** [comment]
@Luismvm can you also share the code in your controller / page:
- did you add the authorize attribute with AuthenticationSchemes ?
- did you explicitly pass-in the authentication scheme parameter to the ITokenAcquisition methods? (or used .WithAuthenticationScheme, on the request to MicrosoftGraph)?

@ferronsw @Luismvm : I've updated the article with an improved sample and reference to the test app:
https://github.com/AzureAD/microsoft-identity-web/wiki/Multiple-Authentication-Schemes#variation-of-the-sample

**Comment by jmprieur** [comment]
@ferrons: note that you could use the same application for both application and delegated permissions. See [Specify scopes and app-permissions for GraphServiceClient](https://github.com/AzureAD/microsoft-identity-web/wiki/1.2.0#you-can-now-specify-scopes-and-app-permissions-for-graphserviceclient).

For the consent issue, I think this would work if you only pre-authorize (admin consent) the app-only permissions, but not the delegated permissions?

**Comment by ferronsw** [comment]
So far I know and tested it's not possible to give only pre-authorize (admin consent) for app-only permissions when delegated permissions are also specified. Besides that I want to be able to pre-authorize (admin consent) delegated permissions as well.
So users don't have to do that. The application is for organizational use (that's why it's pre-authorized) and not personal.

**Comment by jmprieur** [comment]
So, if you can pre-authorize everything, @ferronsw, just use  `new [] { $"{ApiAppIdUri}/.default"} ` as `scopes` to get the tokens, and you'll be good?

**Comment by ferronsw** [comment]
@jmprieur unfortunately no. Some scopes we use can't be granted, because they don't exist in the tenant of our customers. Some customers not have access to certain Office 365 or Azure services like Yammer or Windows Virtual Desktop. 

Because of this problem we had to split our app registration in two pieces like I described.

**Comment by Luismvm** [comment]
@jmprieur code is in different places but i'll try my best to bring it all together here for you.

Startup.cs:

![image](https://user-images.githubusercontent.com/29466233/125434855-0abd1a40-935e-4bfe-800b-762edb7976e5.png)

Adding the authorization policy:

![image](https://user-images.githubusercontent.com/29466233/125434937-3a076702-4dfd-41b5-8735-a3171b78769a.png)

Using the token acquistion:

![image](https://user-images.githubusercontent.com/29466233/125435075-b057321c-c129-4424-8f11-9a614e38239f.png)

![image](https://user-images.githubusercontent.com/29466233/125435116-0436818f-f376-4402-b691-732c050cae3c.png)


**I'm not specifying the authorization scopes or user flow at the controller levels, and i'm using the token acquisition directly as seen above**

Do I need to specify the tenantid / userflow when calling the token service?

**Comment by psignoret** [comment]
@ferronsw Can you share some more details on how you've configured and are requesting permissions today? Which permissions do you two app registrations have configured, and which ones (if any) are requested dynamically?

**Comment by Luismvm** [comment]
> @jmprieur code is in different places but i'll try my best to bring it all together here for you.
> 
> Startup.cs:
> 
> ![image](https://user-images.githubusercontent.com/29466233/125434855-0abd1a40-935e-4bfe-800b-762edb7976e5.png)
> 
> Adding the authorization policy:
> 
> ![image](https://user-images.githubusercontent.com/29466233/125434937-3a076702-4dfd-41b5-8735-a3171b78769a.png)
> 
> Using the token acquistion:
> 
> ![image](https://user-images.githubusercontent.com/29466233/125435075-b057321c-c129-4424-8f11-9a614e38239f.png)
> 
> ![image](https://user-images.githubusercontent.com/29466233/125435116-0436818f-f376-4402-b691-732c050cae3c.png)
> 
> **I'm not specifying the authorization scopes or user flow at the controller levels, and i'm using the token acquisition directly as seen above**
> 
> Turns out, i need to update my packages i'll try and do that and specify the authentication scheme in the token acquisition

I've updated the packages and passed the authentication scheme to the tokenacquistion service, and everything seems to work fine now :)

The only issue seems to be using the policy builder to add the authorization filter doesn't seem to work, even if you specify the schemes to authenticate against, the authorization always seems to fail... so i moved the authorization filter to the controllers and everything seems to work fine now.

@jmprieur @psignoret @jennyf19 thanks for the help 👍

**Comment by jmprieur** [comment]
@Luismvm:
- the app authentication scheme means that all your controller actions will be authenticated with AAD
- If you want to use a different auth scheme when requesting your token you need to user `_tokenAcquisition.GetAccessTokenForUserAsync(scopes, authenticationScheme: "YourDesiredAuthScheme")`

**Comment by ferronsw** [comment]
@psignoret I request the dynamic scopes like this for the delegated app registration

```
https://login.microsoftonline.com/organizations/v2.0/adminconsent?client_id={clientId}&redirect_uri={baseUrl}/Customers/AADAuthorization&state=02091995&scope={scopes_sperated_by_whitespace} 
```
The scopes that can be requested are:

Directory.AccessAsUser.All
Files.Read.All
offline_access
profile
user_impersonation (Yammer)
email
User.Access (WVD)
openid
Mail.Read
Calendars.Read

For the application permissions app registration I use this:

```
https://login.microsoftonline.com/organizations/v2.0/adminconsent?client_id={clientId}&redirect_uri={baseUrl}/Customers/AADAuthorization&scope=https://graph.microsoft.com/.default&state=02091995_background
```

**Comment by jmprieur** [comment]
@ferronsw : do we agree that your initial issue is solved?

**Comment by ferronsw** [comment]
@jmprieur  yes

**Comment by jmprieur** [comment]
do you mind closing this issue @ferronsw ?

**Comment by ferronsw** [comment]
No
