### ISSUE TITLE
[Bug] NonceCookie and CorrelationCookie configurations provided in AddMicrosoftIdentityWebApp are not honored

### ISSUE THREAD

**Issue by vh-vahan** [AzureAD/microsoft-identity-web#1262]
**Which version of Microsoft Identity Web are you using?** 1.12.0
Note that to get help, you need to run the latest version. 

**Where is the issue?** [AddMicrosoftIdentityWebApp ](https://github.com/AzureAD/microsoft-identity-web/blob/dcd998173eb9b5ee7c8377d585d51626ca96de30/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L117)method accepts Action to configure the [MicrosoftIdentityOptions](https://github.com/AzureAD/microsoft-identity-web/blob/bba91c4298411e780c9f082e8e3843eacd8e543c/src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs#L13). MicrosoftIdentityOptions inherits from OpenIdConnectOptions, so it is possible to configure the [Nonce cookie](https://github.com/dotnet/aspnetcore/blob/be5ba495b4872fa055385463da655ae4c4318898/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L295) and [Correlation cookie](https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L141) using the NonceCookie and CorrelationCookie properties that return CookieBuilder(for example change the samesite or secure settings). Though what i can see is that the provided configuration is ignored and the default is being returned as defined in the OpenIdConnectOptions.
* Web app
    * [x] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?** This is a new app

**Repro**

**Expected behavior**
A clear and concise description of what you expected to happen (or code).
Nonce and Correlation cookies set in response should have the provided configuration(secure, samesite)

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.
Nonce and Correlation cookies have the defaults set in OpenIdConnectOptions constructor

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jennyf19** [comment]
@vh-vahan do you mind trying this [branch](https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/fixNonce) to see if the issue is resolved?

**Comment by jennyf19** [comment]
Included in [1.16 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.16.0)
