### ISSUE TITLE
[Feature Request] Better long running process support

### ISSUE THREAD

**Issue by NWessel** [AzureAD/microsoft-identity-web#1279]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [X ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
App is in development

**Repro**
Using ITokenAcquisition in a long running thread providing it a ClaimsPrincipal that is extracted before the httpcontext is disposed.

```csharp
var response = await _tokenAcquisition.GetAccessTokenForUserAsync(new List<string> { "https://management.azure.com/.default" }, user: dto.User);
```

**Expected behavior**
I recieve a token

**Actual behavior**
I get an error -
![image](https://user-images.githubusercontent.com/9061380/122812024-74880080-d2d1-11eb-8c82-f98c31fa2892.png)

![image](https://user-images.githubusercontent.com/9061380/122811963-6508b780-d2d1-11eb-9b12-1373f5ed42f7.png)

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by ski-pub** [comment]
I get the same error when I upgraded from 1.10.0 to 1.11.0, 1.12.0 or 1.13.1.

my startup is set up as follows:

            services.AddMicrosoftIdentityWebApiAuthentication(configuration, configSectionName)
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddInMemoryTokenCaches();

            var validationParameters = new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidateAudience = true,
                ValidateIssuerSigningKey = true,
                RequireExpirationTime = true,
                ValidateLifetime = settings.ValidateLifetime,
                ValidAudiences = settings.ValidAudiences
            };

            services.AddSingleton(validationParameters);

            services.Configure<JwtBearerOptions>(AuthenticationScheme,
                options => { options.TokenValidationParameters = validationParameters; });


But when I call: 

serviceScope.ServiceProvider.GetRequiredService<ITokenAcquisition>()
                        .GetAccessTokenForAppAsync(scope);

I get the following error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Identity.Web.MergedOptions.PrepareAuthorityInstanceForMsal()
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)


This seems similar to https://github.com/AzureAD/microsoft-identity-web/issues/1286 also.

**Comment by NWessel** [comment]
I think it is noteworthy to say that your example is trying to get a token for app while mine is trying for user :)

**Comment by jmprieur** [comment]
@NWessel : we released Ms.Id.Web 1.14.0 today that supports OBO token refresh (long running processes).
See https://github.com/AzureAD/microsoft-identity-web/wiki/get-token-in-event-handler for the guidance

**Comment by jmprieur** [comment]
@ski-pub on which version are you?

**Comment by ski-pub** [comment]
I'm currently using 1.10.0.  Versions prior to 1.11.0 doesn't throw the exception.  I 'm ok staying on version 1.10.0, but at somepoint I'll need to upgrade.

**Comment by NWessel** [comment]
@jmprieur This looks very nice, my only concern is that i'm starting my long running process like this 

![image](https://user-images.githubusercontent.com/9061380/123144259-c9f01900-d45b-11eb-8f9d-e43ae0dcd61d.png)

At which point the httpcontext gets disposed. Would i be able to just new up a httpcontext and just set that key?
`var httpContext = new HttpContext()`
`httpContext.Items["JwtSecurityTokenUsedToCallWebAPI"] = tokenToUse;`

**Comment by jmprieur** [comment]
That's probably difficult to do that. I think we should provide a solution out of the box.
I've also raised an issue on MSAL.NET, releated to this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2733

**Comment by NWessel** [comment]
@jmprieur 
Just want to share my temporary solution which finally works!
So inspiration is clearly used from the link you sent my way!
![image](https://user-images.githubusercontent.com/9061380/123862018-1ccc4380-d928-11eb-84f9-42a8fd1bc296.png)

Here i use the longcontext and start it up with the key right away when i start a new thread
![image](https://user-images.githubusercontent.com/9061380/123862125-42594d00-d928-11eb-9d51-3b69ade6e2bf.png)


Finally i am able to use it in a delegating handler.
![image](https://user-images.githubusercontent.com/9061380/123862293-746aaf00-d928-11eb-975b-6549707b0f93.png)

**Comment by jmprieur** [comment]
@NWessel awesome!
Thanks for sharing!

Do you think it's ok for the moment to let developers do it on their own (with a good sample)? or would you think it's vital to have Microsoft.Identity.Web provide a solution out of the box?

**Comment by NWessel** [comment]
I want to say it is vital that it is out of the box - That way we have a common way of doing it, and a one place to fix/optimize it.
On the other hand, it might not fit all situations still (cant think of any right now) and having an example to work from would be good.

There are some things in my LongRunningProcessContext that i dont think looks very nice. The way i need to "move" the absoluteurl from the real request to the fake request in order to get ITokenAquasition to work.

I guess the answer it, i'm not sure :) It would be super good to have it out of the box though

**Comment by jennyf19** [comment]
@NWessel Long running process has a better dev ex starting in [1.21.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.21.0).
