### ISSUE TITLE
Not recognised authenticated user in a multiple AAD authentication configuration

### ISSUE THREAD

**Issue by alexandrejobin** [AzureAD/microsoft-identity-web#1280]
**Which version of Microsoft Identity Web are you using?**
Microsoft.Identity.Web v1.13.0
Microsoft.Identity.Web.MicrosoftGraph v1.13.0
Microsoft.Identity.Web.UI v1.13.0

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [x] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches

**Is this a new or an existing app?**
This is a new app or an experiment.

**Repro**

**Startup.cs**
```csharp
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"), OpenIdConnectDefaults.AuthenticationScheme)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddInMemoryTokenCaches();

services.AddAuthentication()
    .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAdB2C"), openIdConnectScheme: "AzureAdB2C", cookieScheme: "AzureAdB2CCookies")
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddInMemoryTokenCaches();

services.AddControllersWithViews(options =>
{
    var policy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
    options.Filters.Add(new AuthorizeFilter(policy));
});
```

**_Layout.cshtml**

```html
<ul class="navbar-nav">
@if (User.Identity.IsAuthenticated)
{
        <li class="nav-item">
            <span class="navbar-text text-dark">Hello @User.Identity.Name!</span>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="/MicrosoftIdentity/Account/SignOut">Sign out</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="/MicrosoftIdentity/Account/SignOut/AzureAdB2C">B2C Sign out</a>
        </li>
}
else
{
        <li class="nav-item">
            <a class="nav-link text-dark" href="/MicrosoftIdentity/Account/SignIn">Sign in</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="/MicrosoftIdentity/Account/SignIn/AzureAdB2C">B2C Sign in</a>
        </li>
}
</ul>
```

**Expected behavior**
I expect that the logged user, from Azure AD or Azure AD B2C, will have access to all the site and the `Request.User` object will contain the information about that user on every request. My application doesn't have to apply specific security depending if the user come from Azure AD or B2C.

**Actual behavior**
When I log with Azure AD, everything works as expected but if I log with Azure AD B2C, the login works but I don't have any information about the logged user in the `Request.User` object. The cookie exists but the framework doesn't seems to recognize it.

I have followed the [Multiple authentication schemes doc](https://github.com/AzureAD/microsoft-identity-web/wiki/Multiple-Authentication-Schemes) without any success.

**Comment by jennyf19** [comment]
@alexandrejobin I wasn't able to repro it...could you provide a link to your code? 
Here is what I see when signing-in with B2C:
![image](https://user-images.githubusercontent.com/19942418/122850696-8e6e1700-d2c2-11eb-8ca1-d7251d8efb2f.png)
I'm using this [sample](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/MultipleAuthSchemes), if you want to compare. thanks!

**Comment by alexandrejobin** [comment]
I will provide you with a sample shortly. In the meantime, with your sample, if you put a home page with the AnonymousAttribute, I think you will get the issue.

**Comment by jmprieur** [comment]
@alexandrejobin : when you use the AllowAnonymous attribute, the user is not authenticated, and threfore, there is no User (no claims)

**Comment by alexandrejobin** [comment]
@jmprieur I know that but if the user is already authenticated, I would like to retreive the user information on whatever page he have requested. I've found a way this morning but not sure if it's the way to go. I must declare this:

```csharp
services.AddControllersWithViews(options =>
{
    var policy = new AuthorizationPolicyBuilder(
        OpenIdConnectDefaults.AuthenticationScheme,
        "AzureAdB2C")
        .RequireAuthenticatedUser()
        .Build();

    options.Filters.Add(new AuthorizeFilter(policy));
});

services.AddAuthorization(options =>
{
    options.DefaultPolicy = new AuthorizationPolicyBuilder(
        OpenIdConnectDefaults.AuthenticationScheme,
        "AzureAdB2C")
        .RequireAuthenticatedUser()
        .Build();
});
```

**Comment by alexandrejobin** [comment]
Here's the simple demo of the issue. With the "AAD Sign in" button, everything works correctly but if you use the "AADB2C Sign In" button, the application doesn't see you at all.

[WebApplication11.zip](https://github.com/AzureAD/microsoft-identity-web/files/6696300/WebApplication11.zip)

**Comment by jennyf19** [comment]
@alexandrejobin I believe this was fixed. Does it repro with the latest version of Id.Web? If so, please re-open.
