### ISSUE TITLE
[Bug] NullRefException MergeOptions property Instance is null

### ISSUE THREAD

**Issue by tango-charly** [AzureAD/microsoft-identity-web#1286]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.12.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [x] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app for an experiment ! :) 
But we definitely need it for production development 

**Repro**
Create a Blazor Server Side
Startup.cs
```Csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Identity.Web;

namespace WebApplication
{
    public class Startup
    {
        public IConfiguration Configuration { get; }

        public Startup(IConfiguration configuration)
            => Configuration = configuration;

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddHttpContextAccessor();
            services.AddDistributedMemoryCache();
            services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
                .EnableTokenAcquisitionToCallDownstreamApi(new[] { Configuration["Scope:Api"] })
                .AddInMemoryTokenCaches();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseDeveloperExceptionPage();
            app.UseExceptionHandler("/Error");
            app.UseHsts();
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseRouting();
            app.UseEndpoints(
                endpoints =>
                {
                    endpoints.MapBlazorHub();
                    endpoints.MapFallbackToPage("/_Host");
                });
        }
    }
}
```

Index.razor.cs
```csharp
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.Extensions.Configuration;
using Microsoft.Identity.Web;

namespace WebApplication.Pages
{
    [Authorize]
    public partial class Index
    {
        [Inject]
        public ITokenAcquisition TokenAcquisition { get; set; }
        [Inject]
        public IConfiguration Configuration { get; set; }
        private string AccesToken { get; set; }

        protected override async Task OnInitializedAsync()
        {
            AccesToken = await TokenAcquisition.GetAccessTokenForUserAsync(new[] { Configuration["Scope:Api"] });
        }
    }
}
```

Index.razor
```html
@page "/"

<h1>Access Token : @AccesToken </h1>

```

appsettings.json
```json
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "https://{company}.com.onmicrosoft.com",
    "TenantId": "00000000-0000-0000-000-000000000000",
    "ClientId": "00000000-0000-0000-000-000000000000",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc",
    "ClientSecret": "ABCD123456789.ABC_DEF_123~ABC123-A"
  },
  "Scope": {
    "Api": "api://00000000-0000-0000-000-000000000000/{name}"
  }
}
```

**Expected behavior**
An other type exception than NullRefException should be thrown 

**Actual behavior**
NullRefException is thrown by PrepareAuthorityInstanceForMsal() in MergedOptions class, MicrosoftIdentityWebAppServiceCollectionExtension.cs (line 350)

**Possible solution**
Even if my my configuration seems correct. It could be easier to debug if we handle ArgumentNullException with an other Exception type with a more comprehensible error message, just an example :
```csharp
            if(Instance is null)
                throw new ArgumentNullException("Missing configuration for Instance in options")
```

** Additionals  informations **
Options should be correctly hydrated (section name is AzureAd as defined in default parameter)
![image](https://user-images.githubusercontent.com/8989885/123005426-1b2cd980-d384-11eb-94f3-01ae3b20f2aa.png)

Null instance for Instance property at class MergedOptions => method PrepareAuthorityInstanceForMsal()
![image](https://user-images.githubusercontent.com/8989885/123005687-7eb70700-d384-11eb-8b27-f6795c64dca9.png)

**Comment by jennyf19** [comment]
@tango-charly i'm not able to repro this. I tried with blazor server and we are checking for the values that are required to sign-in:
![image](https://user-images.githubusercontent.com/19942418/123019409-4532cb80-d385-11eb-9b03-b2a0a879fdde.png)

have you tried with 1.13.1?

**Comment by tango-charly** [comment]
@jennyf19 yep, I missed that verification, so that's means my issue is in the merged options.

I checked with latest version (1.14.0)
Indeed at this state my options property are not null. 

I realized, properties options are null after GetOptions from cache (mergeOptions)
At this stage, Instance is null
![image](https://user-images.githubusercontent.com/8989885/123105981-3ccea500-d406-11eb-82c6-49728ab6980c.png)

My problem seems to be located in cache access. 
![image](https://user-images.githubusercontent.com/8989885/123105748-0d1f9d00-d406-11eb-9fbe-5a97b323ac2a.png)

Did I miss something in the startup configuration ?

**Comment by jmprieur** [comment]
Which cache access is it about, @tango-charly ? Is it part of Microsoft.Identity.Web? this does not look like code we have?

**Comment by tango-charly** [comment]
Yep, it's not in your project, but you consume theses classes.

IOptionsMonitor<MergedOptions> is injected in Microsoft.Identity.Web.TokenAcquisition, and it's called by GetOptions : 
![image](https://user-images.githubusercontent.com/8989885/123114373-3ee83200-d40d-11eb-8978-6319cf94726f.png)

Then IOptionsMonitorCache<TOptions> is injected in Microsoft.Extensions.Options.OptionsMonitor 
![image](https://user-images.githubusercontent.com/8989885/123114900-a8684080-d40d-11eb-8c79-5af33fc26e15.png)


And finally when OptionsCache<[DynamicallyAccessedMembers(Options.DynamicallyAccessedMembers)] TOptions> is called to retrieve / merge options properties from Azure Ad Options are null
![image](https://user-images.githubusercontent.com/8989885/123115305-01d06f80-d40e-11eb-946b-ae6a6f2ccaf7.png)

It looks like Options are not set in cache memory at Startup, and then I can't retrieve my AzureAd configuration values.

Actually, I don't know if it's really added in a cache, I'm just relying on the names of the classes and properties, but it makes sense

**Comment by jmprieur** [comment]
@tango-charly:
- in `Configure(IApplicationBuilder app, IWebHostEnvironment env)`, you're missing:

  ```CSharp
            app.UseAuthentication();
            app.UseAuthorization();
  ```

- In `ConfigureServices(IServiceCollection services)`, I would move the following lines first:

  ```CSharp
    services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
                .EnableTokenAcquisitionToCallDownstreamApi(new[] { Configuration["Scope:Api"] })
                .AddInMemoryTokenCaches();
  ```

**Comment by tango-charly** [comment]
Oh ! I missed the obvious !
Thank's ! Hope it will help to debug for someone one day :)
