### ISSUE TITLE
[Bug]  System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline

### ISSUE THREAD

**Issue by rsrinivasanhome** [AzureAD/microsoft-identity-web#1291]
**Which version of Microsoft Identity Web are you using?** microsoft identity web 1.8.2 version 
Note that to get help, you need to run the latest version. 

**Where is the issue?** After making request to pods after 30 days of dormancy we are getting - IDX20803: Unable to obtain configuration from: 'https://login.mic  '  errors.  This error gets resolved on recreating the pod

* Web app
    * [ ] Sign-in users
     [* ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
     [*] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

**Repro**
`More or less followed the standard sample .   We had not used a pod for 30 days.  When requests starting coming after 30 days we got this error in one pod 

**Expected behavior**
We assume the endpoint may have been not reachable for a small period of time .  We tried the curl command inside the pod and we were getting a response .   We expect the Pod to start working as the endpoints at least now are available .  Instead we get more errors with code IDX20803, IDX20804.  This error get resolved on recreating the pod.

 For more details see the logs.

**Additional context / logs / screenshots**
 An unhandled exception was thrown by the application.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1'.
       ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1'

Could you please give us some guidance on how to prevent this issue from occurring? More elaborate logs below

[NewIssue.txt](https://github.com/AzureAD/microsoft-identity-web/files/6714225/NewIssue.txt)

**Comment by jmprieur** [comment]
@rsrinivasanhome this seems like a network issue (IDX errors are send by ASP.NET Core)
BTW, don't you want to upgrade to the latest Microsoft.Identity.Web ?

**Comment by rsrinivasanhome** [comment]
We will upgrade from 1.8.2 to 1.14.0  will this help fix the issue .   Can you give us some pointers to handle such type of issues ?  It appears even after network connectivity is restored to the end point we still get this error until we restart the pod

**Comment by jmprieur** [comment]
@rsrinivasanhome : 1.14.0 leverages recent versions of Identity.Model 6.10.2+, which handles the metadata refresh better. This should solve your issue without having to restart the pod.

BTW, just to be sure, what do you mean by pod?

**Comment by rsrinivasanhome** [comment]
kubernetes pods .  We will upgrade to the latest version of microsoft.identity.web and create a new ticket if we still face the issue.
