### ISSUE TITLE
[Feature Request] Update to .NET 6-preview.*

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#1293]
https://github.com/dotnet/aspnetcore/issues/33944

Propose a PR for ASP.NET Core to:

- [ ] Update the version of Microsoft.Identity.Web (currently it's 1.1.0)
- [ ] In the web API controller, and the Server of the blasorwasm hosted temlate:
  - [ ] `[RequiredScope("access_as_user")]` on the controller
  - [ ] Remove `scopeRequiredByApi` field
  - [ ] Remove `HttpContext.VerifyUserHasAnyAcceptedScope(scopeRequiredByApi);`

**Comment by jmprieur** [comment]
## Proposed work, @jennyf19 

Propose a PR for ASP.NET Core to:

- [ ] Update the version of Microsoft.Identity.Web (currently it's 1.1.0)
- [ ] In the controller of the web API, and the Server of the blasorwasm hosted template:
  - [ ] `[RequiredScope("access_as_user")]` on the controller (Or use the configuration ?)
  - [ ] Remove `scopeRequiredByApi` field.
  - [ ] Remove `HttpContext.VerifyUserHasAnyAcceptedScope(scopeRequiredByApi);`

**Comment by jmprieur** [comment]
https://github.com/dotnet/aspnetcore/pull/34492
