### ISSUE TITLE
[Feature Request] Leverage the new .WithCssRoutingHint in MSAL.NET 4.34.0

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1303]
**Is your feature request related to a problem? Please describe.**
- Microsoft.Identity.Web:
  -  currently uses it own extension methods to provide the routing hint.
  - uses the .WithHttpHeaders method: https://github.com/AzureAD/microsoft-identity-web/blob/9824659a5cdd8e64b5bea9fe7308e0b0b2fdf262/src/Microsoft.Identity.Web/TokenAcquisition.cs#L178

- MSAL.ENT 4.33.0 retro-fitted a similar API

  ```CSharp
  public sealed class AcquireTokenByAuthorizationCodeParameterBuilder : 
    AbstractConfidentialClientAcquireTokenParameterBuilder<AcquireTokenByAuthorizationCodeParameterBuilder> {
        public AcquireTokenByAuthorizationCodeParameterBuilder WithCcsRoutingHint(string userName);
        public AcquireTokenByAuthorizationCodeParameterBuilder WithCcsRoutingHint(string userObjectIdentifier, string tenantIdentifier);
    }
    public sealed class AcquireTokenOnBehalfOfParameterBuilder : 
    AbstractConfidentialClientAcquireTokenParameterBuilder<AcquireTokenOnBehalfOfParameterBuilder> {
        public AcquireTokenOnBehalfOfParameterBuilder WithCcsRoutingHint(string userName);
        public AcquireTokenOnBehalfOfParameterBuilder WithCcsRoutingHint(string userObjectIdentifier, string tenantIdentifier);
    }
    public sealed class GetAuthorizationRequestUrlParameterBuilder : 
    AbstractConfidentialClientAcquireTokenParameterBuilder<GetAuthorizationRequestUrlParameterBuilder> {
        public GetAuthorizationRequestUrlParameterBuilder WithCcsRoutingHint(string userObjectIdentifier, string tenantIdentifier);
    }
  ```

**Describe the solution you'd like**
- Update the current code in Id.Web (still nice as it takes a ClaimsPrincipal), to use the new MSAL.NET 4.34.0 API
  https://github.com/AzureAD/microsoft-identity-web/blob/9824659a5cdd8e64b5bea9fe7308e0b0b2fdf262/src/Microsoft.Identity.Web/CcsHintExtensions.cs#L23-L49

- Use the new API instead of the `.WithExtraHttpHeaders`:
  https://github.com/AzureAD/microsoft-identity-web/blob/9824659a5cdd8e64b5bea9fe7308e0b0b2fdf262/src/Microsoft.Identity.Web/TokenAcquisition.cs#L178

**Describe alternatives you've considered**
Leave the current code in Id.Web

**Comment by jennyf19** [comment]
Included in [1.15 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.15.0)
