### ISSUE TITLE
[Documentation] 

### ISSUE THREAD

**Issue by dalibor-sanzeru** [AzureAD/microsoft-identity-web#1316]
### Documentation related to component
AzureAd configuration not read on Azure App Service

### Please check all that apply

- [ ] typo
- [X ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ x] needs an example

### Description of the issue
Hi,
I am using Azure App Service to host .net5 API using AzureAD loaded from JSON config. After deployment values are reading from Azure configuration, but section of AzureAd looks not readed at all.

```
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(this.Configuration);
```

With error:
2021-07-14 15:11:28.7868 | ERROR | Connection ID "16717261818412074516", Request ID "81b10040-0000-e800-b63f-84710c6997bb": An unhandled exception was thrown by the application. | System.ArgumentNullException: IDW10106: The **'ClientId' option must be provided.** 
   at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__0(JwtBearerOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---

How to properly setup values in AZURE App Service, so they are readed correctly? I found this with : splitter but it is not working.

![image](https://user-images.githubusercontent.com/19836016/125647302-7ebcb78a-399b-435c-8c21-2733d5bb3cce.png)

Thanks for advice.

**Comment by jennyf19** [comment]
@dalibor-sanzeru I think App Services won't work for a web API. have you seen this [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview) on protected web APIs.

**Comment by dalibor-sanzeru** [comment]
> @dalibor-sanzeru I think App Services won't work for a web API. have you seen this [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview) on protected web APIs. Maybe this will help: https://docs.microsoft.com/en-us/azure/api-management/api-management-key-concepts

Jenny, 
What and why should not work? 
https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-5.0

I am looking way how to rewrite appjson configuration with section AzureAd into azuri-sh app-config, so used extension method can read it correctly.

**Comment by jennyf19** [comment]
@dalibor-sanzeru closing, but feel free to reopen if you're still having issues.

**Comment by ataraxia89** [comment]
This is still an issue and the only discussion here has been questioning whether App Services should be used for APIs, which they **obviously** should.

Any chance of a sensible answer?

**Comment by dalibor-sanzeru** [comment]
In startup ConfigureServices:

```
            //Auhentication/Authorization
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(
                    (jwtOptions) =>
                    {
                        // The claim in the Jwt token where App roles are available. (e.g. you setuo in AZURE AD use groups claims instead roles.)
                        // jwtOptions.TokenValidationParameters.RoleClaimType = "groups";
                    },
                    (options) =>
                    {
                        //Configuration is IConfiguration type stored as local property in Startup filled with Ctor injection.
                        options.ClientId = this.Configuration["AzureAd:ClientId"];
                        options.TenantId = this.Configuration["AzureAd:TenantId"];
                        options.Domain = this.Configuration["AzureAd:Domain"];
                        options.Instance = this.Configuration["AzureAd:Instance"];
                    });
```

This will read form appsettings.json and from Azure web service as well.
_In case of AZure App service configuration use splitter with : as on my image above in proprty keys.
In case of config use standard JSON section nesting._

In my case on local development json config is used, but in azure app service azure app service UI config is used.

**Comment by ataraxia89** [comment]
@dalibor-sanzeru that didn't work either, still got exactly the same issue.

**Comment by ataraxia89** [comment]
I've now found the issue, I had logic to deploy an appsettings file and then use that to build an `IConfiguration` instance and set that in `webBuilder.UserConfiguration` and for some reason that's screwed it up.

Don't know why, because this has been working for months until I added this Azure stuff, I needed that code so I could deploy different appsettings files for unit testing (mainly to use a different SQL connection because I obviously don't want it to use the live db). Now I have over 1,000 tests that are ruined.

**Comment by jmprieur** [comment]
Do you have a repro?

**Comment by ataraxia89** [comment]
The problem was that the logic I had that deployed the appsettings file checked if the file existed already and, because it did, it didn't update the file. I also discovered that the Sign Up/Sign In policy that issued the token needs to be included in the issuer URL.

I don't have a public repro, but this is essentially the code I'm running with business details changed:

**appsettings.json**
```
{
  "AzureAdB2C": {
    "Instance": "https://login.mydomain.net",
    "ClientId": "00000000-0000-0000-0000-000000000000",
    "TenantId": "11111111-1111-1111-1111-111111111111",
    "SignUpSignInPolicyId": "B2C_1_SignUpIn"
  },
  "ConnectionStrings": {
    "SQLConnection": "Data Source=MyAppDebug.db;Cache=Shared"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*"
}
```

**Startup.cs**
```
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration ?? throw new Exception("Startup: Configuration is null.");
    }

    public IConfiguration Configuration { get; }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        if (Configuration.GetConnectionString("SQLConnection") == null)
        {
            throw new InvalidOperationException("ConfigureServices: Connection string 'SQLConnection' returned null.");
        }

        services.AddDbContext<MyAppDbContext>(
            option => option.UseSqlite(Configuration.GetConnectionString("SQLConnection")));

        services.AddAuthentication(options => { options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme; })
            .AddJwtBearer(jwtOptions =>
            {
                jwtOptions.Authority =
                    $"{Configuration["AzureAdB2C:Instance"]}/{Configuration["AzureAdB2C:TenantId"]}/{Configuration["AzureAdB2C:SignUpSignInPolicyId"]}/v2.0/";
                jwtOptions.Audience = Configuration["AzureAdB2C:ClientId"];
            });

        services.AddControllers();

        services.AddScoped<IMyRepository1, MyRepository1>();
        services.AddScoped<IMyRepository2, MyRepository2>();
        services.AddScoped<IMyRepository3, MyRepository3>();
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
            app.UseStatusCodePages();
        }
        else
        {
            // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
            app.UseHsts();
        }

        app.UseHttpsRedirection();
        app.UseAuthentication();
        app.UseRouting();
        app.UseAuthorization();
        app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
    }
}
```

**Comment by dalibor-sanzeru** [comment]
Ataraxia89,
few things to mention.

1) You are using a) Azure Active direoctory for JWT bearer token issuing or b) you issue it yourself? I beieve b) is true. Correct?


In eah case, if you get error:  'ClientId' option must be provided. you get it because you dont read it from config here (you are reding authority/audience only):
```
services.AddAuthentication(options => { options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme; })
            .AddJwtBearer(jwtOptions =>
            {
                jwtOptions.Authority =
                    $"{Configuration["AzureAdB2C:Instance"]}/{Configuration["AzureAdB2C:TenantId"]}/{Configuration["AzureAdB2C:SignUpSignInPolicyId"]}/v2.0/";
                jwtOptions.Audience = Configuration["AzureAdB2C:ClientId"];
            });
```

**Comment by ataraxia89** [comment]
I have two web services running on Azure - a website and a web API. The website obtains a JWT token from Azure, then provides that token to the API.

So it's option 1), Azure is issuing the token. Anyway, it's fixed now.

**Comment by dalibor-sanzeru** [comment]
Fixed how?

**Comment by ataraxia89** [comment]
I did, in my [comment above](https://github.com/AzureAD/microsoft-identity-web/issues/1316#issuecomment-925292990), this is working code.

**Comment by Louspirit** [comment]
For me it was a problem with the `appSettings.json` not read because I launched the app from another folder... Ok the appsettings is gotten automatically but I didn't know it was relatively.


```
echo "====== Start application"
# Important to be in the right folder or the appsettings etc would not be taken
cd /app
dotnet /app/Eni.Editions.InterfaceSuiviSurveillances.BackEndApp.dll
```


For me the ":" character is not allowed in App Service. But it can be set with double underscores if I remember well.
