### ISSUE TITLE
[Question]/[Documentation] How are refresh tokens handled in Blazor server applications?

### ISSUE THREAD

**Issue by TheXenocide** [AzureAD/microsoft-identity-web#1320]
### Documentation related to component
Microsoft.Identity.Web

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [x] needs an example

### Description of the issue

[This issue](https://github.com/AzureAD/microsoft-identity-web/issues/221) appears to have been closed after a one sentence answer that seems to imply, based on the question, things should "just work" but I haven't seen any documentation or samples that explain how and the sample that is available would seem to suggest that Blazor server may not "just work" for common scenarios, so it leaves me confused.

Where do I find how refresh tokens are/should be handled by Microsoft.Identity.Web particularly in a Blazor server context. Do we have to perform the refresh ourselves or will it automatically refresh at some threshold? What threshold (e.g. after 50% of access token expiration has passed)? Is it configurable?

If it is in fact automatically handled, what happens when the same user has multiple tabs open? How are the tokens for the scoped service you recommend creating to associate access tokens with the user's SignalR circuit supposed to get updated by this background refresh token process? The answer to the linked question references the token cache, but I don't know how/where we would be using that based on the examples/documentation available.

If refresh tokens are NOT automatically handled, what would be the best practice of using existing Microsoft.Identity.Web functionality to ensure a user's auth doesn't expire while they're still actively using the app? It would be really helpful to know "the right way" to do these things. I suppose maybe it's possible to store the refresh token in the same scoped object that holds the access token, but I don't understand how this relates to the token caching functionality mentioned in the "answer" to this post. Are we supposed to be using the token cache library in addition to or instead of the scoped service in the sample? 

My first instinct was that refresh tokens didn't exist in this context because the sample/documentation doesn't reference them anywhere; I legitimately thought we might need to write our own system for popping up a window to re-auth so as not to cause the page the user may have pending unsaved changes on to be lost which gets further complicated by users having more than one tab open (a high likelihood). We would really rather not interrupt the user experience for an active (or idle but still connected/in-progress) user if it's at all possible to avoid.

Could you guys please elaborate more on what it looks like for a Blazor server app to have an active user that lives longer than the expiration of their initial access token? Thanks kindly.

**Comment by TheXenocide** [comment]
After cleaning up some tabs and re-reading the question, I thought it might help to clarify some things.

First, it looks like maybe I was a little confused between a StackOverflow answer or early blog post and the MS docs because the scoped service I mentioned (which is actually under the "[additional scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0)" does have a RefreshToken property in the MS sample, although it doesn't say much about how best to use it.

Also, just to detail our usage scenario a little more, we have a Blazor server application that requires users to authenticate before accessing it. From there we will use the same access token for the web app to access Web APIs from the same app registration (they are the same application, one does not work without the other). Users will likely leave tabs open for extended periods of time in addition to the same user having multiple tabs open at a time. Besides accessing our own application APIs we will also need to provide an access token to Power BI Embedded to apply Azure SQL row-level security (which is a different resource entirely).

The main concern I'm trying to solve for here is how to ensure that all tabs of the same user are using the most recent token and are refreshing that token when necessary. Does any of the tooling provided make this easier/more secure and how much of it is available out-of-the-box vs. what will we need to hand roll. The sheer quantity of documentation is daunting so apologies if I missed something somewhere, but I believe I've read through most of the relevant resources. We're really hoping not to reinvent the wheel with any of this security-critical behavior.

Besides that, we do have a longer term consideration for passing a token along to PowerBI Embedded, which I believe will need to be a separate token than the one used to log into the application (the Azure SQL Server instance is in a separate multi-tenant Azure instance with a separate Azure AD that has guest accounts which map to the single-tenant of the customer's on-premise/local domain mapped installation used with our [sometimes] locally installed product). Managing this token and refreshing it accordingly will also be an objective when we get to this part of the project, though we've already considered the likelihood that this will be a little more manual than our primary authentication scenario, but any insight on best practices and reusable MS-defined implementation would be very helpful as we move through this first phase we would ideally like to pave the way for (and design in consideration of) this secondary objective in the near future.

Thanks so much for the help!

**Comment by jennyf19** [comment]
@TheXenocide 

Blazor server is like any web app (mvc, webapp templates), and Microsoft.Identity.Web delegates to MSAL.NET to refresh tokens when they are requested, if needed.

If the token acquired is a long lived token because your app calls an API that supports [CAE](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-continuous-access-evaluation) and you have enabled the [client capabilities](https://github.com/AzureAD/microsoft-identity-web/wiki/client-capabilities#client-capabilities), then the token will be proactively refreshed at mid life (under direction of Azure AD). This is not configurable by the app developer other than adding the client capabilities. Microsoft.Identity.Web handles this for you.

For Blazor servers, see [Web Apps](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps) and also [Web App Template](https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template#use-the-web-app-blazor-server-template) .

There is no background process to refresh the tokens, but a refresh happens when tokens are needed (that is when an API is called). If the token was to expire because the user wouldn't use the app for more than one hour, there is an automatic (and most of the times silent) user challenge mechanism, as explained in [Managing incremental consent and conditional access](https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access).

You shouldn't have to use any extra caches than the ones provided in Microsoft.Identity.Web. Just create a blazorserver app and that will be it.

If you need a sample, you have this app: [microsoft-identity-web/tests/BlazorServerCallsGraph](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/BlazorServerCallsGraph). It's for AAD, but B2C is almost the same.

We recommend you create a new app with `dotnet new` as explained in the template link above.

cc: @jmprieur

**Comment by TheXenocide** [comment]
Thanks for the resources, I'm reviewing now. As a side note, we're actually not using B2C; our primary auth for the application/APIs in question are just using the customer's traditional Azure AD and our longterm plans mentioned are using B2B with our own instance using guest accounts linked to their Azure AD accounts used with the main application. We haven't determined yet if we'll need to request tokens on-behalf-of the  guest user to authenticate/authorize with the Azure SQL Server row-level security under the Power BI Embedded components or if we'll be able to request scopes/resources that allow tokens from the customer's Azure AD to work with our B2B instance transparently or not, but that isn't our immediate concern either (though any insight would be appreciated, nonetheless).

I think I still have some concerns regarding how the transparent refresh works in the context of a Blazor server application, but I'll get back to you once I've reviewed everything you've linked more thoroughly.

Thanks again for the help.

**Comment by jmprieur** [comment]
@TheXenocide : great. If you are building an AAD app, you have more options.
For mixing AAD and B2C, you'd want to use multiple authentication schemes (applied to web APIs): https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes

**Comment by TheXenocide** [comment]
Thanks again, I think I'm understanding what you're describing here, but I'd like to break down what we have currently, what we were thinking before this conversation, make sure I understand the suggestions, and then discuss some remaining questions and implementation/user experience details.

For the sake of keeping this simple, let's ignore our future plans with Power BI for the moment and start with the application we're trying to release in our first iteration. That element is a new offering we're working on that is rather different from what the rest of the application does and it's not set to be part of our first release (in its current prototype phase it is more like an independent SaaS solution which also happens to have UI integration with the existing produce, whereas the existing product is often installed on-premise). Without the SaaS portion, there is no B2B/B2C element in this first implementation, what remains is purely hooked up to the customer's own Azure AD which they are using for SSO throughout their organization.

It's probably worth noting that this is an existing enterprise application with multiple different client UIs (WPF, Xamarin, and we are currently developing a Web UI using Blazor). In this context, we're primarily concerned with the Blazor portion, but I wanted to mention the others just in case there are any special notes worth considering that could impact them as we discuss possible design decisions here. 

In the absence of that future Power BI project, we are not using Azure AD for authorization, only for identity/authentication. Our software has its own Authorization functionality built in which is managed by users within the application itself. In this first iteration we do not need consent for any APIs outside of our own application with the possible exception that (for now) we need the user's upn and on-premise SID and I haven't determined if we can still request those with the initial authentication request as we have in the past or if we'll need to use Graph for those on first login. We have several separate Web APIs for the sake of separation of concerns and different load balancing/deployment configurations, but they are all conceptually one application (a user that has access to one has access to all of them). The existing product allows either Windows Authentication or OIDC-based authentication using IdentityServer solely as an authentication/identity proxy which homogenizes/maps identities from 3rd party providers (Azure AD, ADFS, etc.); we do not define any additional scopes/claims and we only request those required to provide the identity information we need from the 3rd party. For a variety of reasons, in this first iteration of a Blazor client we have made the decision to get rid of the IdentityServer portion for the entire product and convert all user-facing applications (Mobile, Desktop, Web) to use Azure AD directly. Our long term plan is a more comprehensive overhaul, but for the time being we need to take it in steps.

I think part of where our current design thoughts diverge from the advice you've given here starts with how our design has been informed by the existing codebase built around IdentityServer and how we use the tokens it provides (much of which is based around older, harder to use libraries as well), but here's our recent thinking:

- We will have a single app registration for all APIs/clients in the product (which is really a single enterprise application)
- Unless we need one for some reason, we don't currently have need of defining any new scopes or resources (authentication itself is the only authorization we need from Azure AD at this time)
- Our existing solutions have been using the same access token acquired when logging in to the client for all of our backend APIs the client communicates with, which all share the same ClientId/audiences/provider/etc. 
  - API Client implementations have been using an injectable TokenProvider-like interface to get the current access token, which does have implementations that perform expiration-based semi-transparent refreshes (no-UI if possible, with a UI fallback).
  - Based on the "[additional scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0)" which looked incredibly similar to our existing implementation, it felt like this was going to be the easiest way to take our Blazor app's access token and send it along to the backend APIs.
  - We also thought we might either have to use APIs more manually to refresh the token or that we might need to provide our own hooks for UI-based re-authentication (and we were really hoping to avoid this when this conversation started)

Given those thoughts, we really hadn't been considering incremental consent OR conditional access in our first phase design (essentially trying to keep things as simple as possible, for now). What I'm seeing here is that there is (somewhat newer) support for these features which appear to be well implemented for and designed around current best practices (like downstream APIs requiring different authorization details), though they look to be much easier to use (programmatically) than what we're used to, but are also designed for a more complicated arrangement of configurations. 

So the main question is how much will our design need to change in order to utilize your implementation of these features, or should we call some lower level functionality more directly while we await further improvements to our adoption of Microsoft Identity Platform.

First, it's unclear to me how it would be used to get the access token that is also currently being used to access the Blazor application (or am I just thinking about that the wrong way because of our existing code?) to use in my client's bearer auth header.

I tried to check the `MicrosoftIdentityConsentAndConditionalAccessHandler ` documentation to see if it mentioned much detail about the user experience behavior when UI is required but had to go to the source to understand what it was doing (to the extent that this started as a documentation request, it might helpful to add a bit of detail there). Based on usage patterns of our desktop client and issues that have popped up in the past, one of the concerns I have is that it looks like the user's browser is redirected away from the Blazor application, which will result in the loss of state when the underlying circuit is closed. When we were considering our own solutions the thought was to try to manage popping up a new self-closing window if that was necessary. Do I understand the behavior correctly and, if so, do you have guidance on how best to change this behavior to happen in such a way that it doesn't interrupt the user's pending edits? I imagine we won't be the only ones who would like to preserve the existing circuit state.

I feel like I had one more question but I wasn't able to finish typing up this reply before I had to run out on Friday and now it seems to be slipping my memory. I'll try to review everything to see if it comes back to mind, but in the meantime I figure this is a large enough message as it is.

**Comment by TheXenocide** [comment]
I remembered my other question: with the "refresh tokens just work" bit, does that mean the user's authentication for the Blazor application itself (which they aren't able to access without performing Azure AD auth in the first place) will stay up-to-date (i.e. will it automatically refresh the token used to access the SPA application itself such that their auth cookie is updated automatically when necessary)? The guidance I've seen here is more about accessing downstream applications that the Blazor UI experience, so I wasn't sure how that part would work. Is there somewhere I can read more about the underlying behaviors/implementation details/user experience, rather than getting started tutorials and such (or perhaps there are some more places in code that would be helpful for me to review)?

**Comment by TheXenocide** [comment]
> ...with the possible exception that (for now) we need the user's upn and on-premise SID and I haven't determined if we can still request those with the initial authentication request as we have in the past...

Per "Configuring optional claims" it looks like we should still be able to get these in our access tokens by configuring them in our app registration, much like how our current IdentityServer-based solution does so I don't believe we currently have need for any Graph information about the user.

**Comment by jmprieur** [comment]
@TheXenocide : 
- MSAL.NET / Id.Web handle the refresh tokens in Blazor server applications when there are access tokens and refresh tokens, that is when these call web APIs

### If you just want to authenticate a user:
- Just do `dotnet new blazorserver --auth SingleOrg` and that will produce the code you need to sign-in a user. There is no access token involved as you won't call any web APIs

### Later when you want to call PowerBI,
- `dotnet new blazorserver --called-api-uri "powerBIUrL" --called-api-scopes "PowerBiScopes"` and that will produce the code you need to call downstream web APIs
 
If you need help for the app registration, see https://github.com/AzureAD/microsoft-identity-web/tree/master/tools/app-provisioning-tool

**Comment by jennyf19** [comment]
@TheXenocide Are there open questions or issues? Going to close, but please re-open if there is more to discuss here. Thank you.

**Comment by arman-g** [comment]
> @TheXenocide Are there open questions or issues? Going to close, but please re-open if there is more to discuss here. Thank you.

My question is where is the documentation that clearly explains how auto refresh works? I am dadding the internet a few days and can't find any definite answer and examples. @TheXenocide is not the only one that is confused, I am too and believe more people as well.

We have multi-tenant web application (ASP.NET Core and Angular) that accesses an API using access_token which expires after an hour. Reading bunch of documentation, it seems that Microsoft.Identity.Web supposed to handle the refreshing of the toke automatically, but is doesn't in our case.
Here is our configuration under the Startup.cs, what are we missing here?

```
        var authBuilder = services.AddAuthentication(options =>
        {
            options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        });

        authBuilder.AddMicrosoftIdentityWebApp(options =>
        {
            options.Authority = "https://login.microsoftonline.com/organizations/v2.0/";
            options.ClientId = config.GetConfigValue<string>("Azure:AD:Identity:ClientId");
            options.ClientSecret = config.GetConfigValue<string>("Azure:AD:Identity:ClientSecret");
            options.AccessDeniedPath = config.GetConfigValue<string>("Azure:AD:Identity:AccessDeniedPath");
            options.SaveTokens = true;
            options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
            options.Scope.Add(OpenIdConnectScope.OfflineAccess);
            foreach (var scope in config.GetConfigValue<IEnumerable<string>>("Azure:AD:Identity:Scopes"))
            {
                options.Scope.Add(scope);
            }
            options.TokenValidationParameters = new TokenValidationParameters
            {
                NameClaimType = "name",
                ValidateIssuer = false
            };

            options.Events.OnTokenValidated = context =>
            {
                #region ' Set the App Admin Claim for the current user '

                var admins = config.GetConfigValue("Application:Admins", Array.Empty<string>());
                if (!admins.Any(x => x.Equals(context.Principal.GetUsername(), StringComparison.OrdinalIgnoreCase)))
                    return Task.CompletedTask;
                var identity = (ClaimsIdentity)context.Principal?.Identity;
                identity?.AddClaim(new Claim("http://schemas.microsoft.com/ws/2008/06/identity/claims/role", $"{UserRoles.AppAdmin}"));

                #endregion

                return Task.CompletedTask;
            };
        }).EnableTokenAcquisitionToCallDownstreamApi(
            config.GetConfigValue<IEnumerable<string>>("Azure:AD:Identity:Scopes")
            ).AddInMemoryTokenCaches(options =>
        {
            options.AbsoluteExpirationRelativeToNow = TimeSpan.FromDays(90);
        });
```

And this is how we try to get the access_token to use in API call:
```
var accessToken = await httpContext.GetTokenAsync(
    OpenIdConnectParameterNames.AccessToken);
```

What are we doing wrong here?

**Comment by TheXenocide** [comment]
Apologies that I didn't see the question before and just now saw the notification from the newest comment.

While I think our application is doing okay at this point, and seems to refresh well enough on its own during active use, I just wanted to add a comment that it would really also be nice to support an auth popup that could be used when an interactive login *will* be needed for a currently logged in user such that it doesn't require the current page to navigate away and lose its state (preferably while the current token is still functional).

We also had some challenges that seemed to stem from leftover non-expired cookies (at least clearing them resolved the issue as a workaround) after a client cert/secret expired, but when I went back to try to reproduce the issue to report back here, the behavior has either improved at the Entra ID end, within MSAL, or some other other confluence of changes that weren't intentionally implemented to fix this specific issue. Still, knowing what behavior to expect for already logged in users when key rotation season comes around would be helpful as I couldn't find much to describe best practices from the library consumption side and what to account for as it pertains to the ASP.NET Core integration for cookies, token cache, and so on.

Overall, I think MSAL.NET definitely "just works" a lot better than its predecessors, but it does still feel like more advanced considerations could still use some more detail in the documentation.
