### ISSUE TITLE
incorrect English grammar means unclear explanation

### ISSUE THREAD

**Issue by jsquire** [AzureAD/microsoft-identity-web#1325]
# Issue Transfer

This issue has been transferred from the Azure SDK .NET repository, [#22717](https://github.com/Azure/azure-sdk-for-net/issues/22717).

### Please be aware that @kbdguy is the author of the original issue and include them on any questions or responses.

---
"...on behalf of the user account which claims are provided in the User member..."

Not clear what that means.  Possibly "... on behalf of the user account in the User member..." and related to the claims requested on the call, but since I can't understand the original statement, I don't know.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 712b76af-89ea-f3a8-1efc-eef633348d92
* Version Independent ID: 8e15c5d3-3129-889f-587d-34f30a6d4de0
* Content: [ITokenAcquisition.GetAccessTokenForUserAsync Method (Microsoft.Identity.Web) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.itokenacquisition.getaccesstokenforuserasync?view=azure-dotnet-preview#Microsoft_Identity_Web_ITokenAcquisition_GetAccessTokenForUserAsync_System_Collections_Generic_IEnumerable_System_String__System_String_System_String_System_Security_Claims_ClaimsPrincipal_Microsoft_Identity_Web_TokenAcquisitionOptions_)
* Content Source: [xml/Microsoft.Identity.Web/ITokenAcquisition.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web/ITokenAcquisition.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jmprieur** [comment]
@jennyf19, let's try to improve this sentence

**Comment by jennyf19** [comment]
Included in [1.15 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.15.0)
