### ISSUE TITLE
[Bug] 401 on MicrosoftIdentity/Account/Signin when deployed to App Service

### ISSUE THREAD

**Issue by atrevers** [AzureAD/microsoft-identity-web#1333]
**Which version of Microsoft Identity Web are you using?**
Microsoft.Identity.Web 1.14.1

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is an existing app to which I'm adding authentication.

**Repro**

`Startup` class from ASP.NET Core Razor Pages web application, note anonymous access to index page is allowed:

```csharp
public class Startup
    {
        public Startup(IConfiguration configuration, IWebHostEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();

            Configuration = builder.Build();
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"));

            services.AddOptions();

            services.Configure<List<string>>(Configuration.GetSection("Colours"));
            services.Configure<List<LinkPageOptions>>(Configuration.GetSection("LinkPages"));

            services.AddRazorPages(options => {
                options.Conventions.AllowAnonymousToPage("/Index");
            }).AddMicrosoftIdentityUI();
            
            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseAuthentication();
            app.UseRouting();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
            });
        }
    }
```

Signin link on index page:
`<a asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Sign in</a>`

**Expected behavior**
Redirect to Azure AD sign in page when Sign in link is clicked.

**Actual behavior**
Running in development environment, the application redirects to the Azure AD sign in page. However, when deployed to Azure App Services, the redirect gives a 401 error.

**Additional context / logs / screenshots**
Downgrading to Microsoft.Identity.Web versions <= 1.9.1 works as expected when deployed to Azure App Services without any code or configuration changes.

**Comment by jmprieur** [comment]
@atrevers: are you using app services authentication (EasyAuth)?
What would be the title of your bug?

**Comment by atrevers** [comment]
> @atrevers: are you using app services authentication (EasyAuth)?
> What would be the title of your bug?

No, I've registered my application in Azure AD with corresponding values in appsettings.json, and haven't configured any authentication through the App Service.
Sorry, title of the bug is updated.

**Comment by jmprieur** [comment]
ok. Next question
did you add a redirect URI in your app registration for the deployed application? (that is replacing localhost:port by the URL where your app is deployed in app service?

**Comment by jmprieur** [comment]
@atrevers do you have an update?

**Comment by jennyf19** [comment]
closing, please re-open with update. Thanks, @atrevers
