### ISSUE TITLE
[Feature Request] Create Microsoft.Identity.Web.Downstream package

### ISSUE THREAD

**Issue by rymeskar** [AzureAD/microsoft-identity-web#1336]
**Is your feature request related to a problem? Please describe.**

We like to keep our dependency structure clean and concise with the ability to pick and choose particular and granular solutions. That is why, we would like to rely on the Id.Web MSAL extensions and the IDownstreamApi without onboarding to the inbound authentication stack.

**Describe the solution you'd like**
Split the Microsoft.Identity.Web package into 2:
* Microsoft.Identity.Web.Downstream
  * Extract out the pure MSAL-outbound related code & the IDownstreamAPI.
* Microsoft.Identity.Web.Downstream
  * Depend on Microsoft.Identity.Web.Downstream
  *  The rest stays the same.

**Describe alternatives you've considered**
Alternative is to bring the whole dependency tree of Id.Web (possibly even causing some dll issues)

**Comment by jmprieur** [comment]
@rymeskar : We'd actually want to provide a similar experience in MSAL.NET for both public client and confidential client applications.
But I want to take the time to propose a good spec and design for this.

**Comment by rymeskar** [comment]
Thanks @jmprieur 

Do you require the mentioned extension of the supported clients and the lib split to be solved in the same iteration?

**Comment by jmprieur** [comment]
Done in rel/v2
