### ISSUE TITLE
[Bug] ITokenAcquisition.GetAuthenticationResultForUserAsync ignores scopes parameter when running in AppService

### ISSUE THREAD

**Issue by GeorgeNarcis** [AzureAD/microsoft-identity-web#1337]
**Which version of Microsoft Identity Web are you using?**
  Microsoft.Identity.Web Version 1.14.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

This is a new app in development.

**Repro**

```csharp
 services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
  .AddMicrosoftIdentityWebApp(o =>
  {
      o.Instance = adConfig.Instance;
      o.TenantId = adConfig.TenantId;
      o.ClientId = adConfig.ClientId;
      o.ClientSecret = configuration.GetValue<string>("secretName");
      o.CallbackPath = adConfig.CallbackPath;
  })
  .EnableTokenAcquisitionToCallDownstreamApi()
  .AddInMemoryTokenCaches();
...........................
...........................
var scopes = new[] { $"{webApi.AppId}/user_impersonation" };
var tokenAcquisition = sp.GetService<ITokenAcquisition>();
var accessToken = await tokenAcquisition.GetAccessTokenForUserAsync(scopes);
```

**Expected behavior**
Access Token returned by GetAccessTokenForUserAsync should have the correct audience and scope claims based on the scope passed to the method.

**Actual behavior**
The Access Token that is returned contains a wrong audience and scope token, not the ones for the downstream API which was passed in the scopes parameters. This happens only when running in Azure App service, when run locally the right token is returned.

**Additional context / logs / screenshots**
The application is a Blazor Server WebApp that has permissions to both Microsoft Graph and also to a downstream API. When running it locally everything works fine and the returned access token contains the correct claims based on the scope passed to the GetAccessTokenForUserAsync method.
When running the application inside an AppService with EasyAuth turned on the scopes parameters seems to be completely ignored, and we always receive a token intended for Microsoft Graph and not for the downstream API specified in the scopes parameter.
Looking through the source code I suspect the problem is in AppServicesAuthenticationTokenAcquisition class GetAccessTokenForUserAsync method - which seems to be ignoring completely the scopes parameters passed to it.

**Comment by jmprieur** [comment]
@GeorgeNarcis, did you enabled App Service authentication (EasyAuth)?

**Comment by GeorgeNarcis** [comment]
Hi @jmprieur  thank you for your answer, yes we use app service authentication with Microsoft Identity provider.  This is what we did to get it working, we've added the scope parameter in the loginParameters config section of the AppService. But this will work to get tokens only for one downstream API.
What if you want to get access tokens programmatically for multiple APIs, do I understand correctly that this is a limitation of the AppService authentication ? 
Also it seems very confusing that you still can set the scopes parameter on the GetAccessTokenForUser method, but this gets ignored.

**Comment by jmprieur** [comment]
@GeorgeNarcis yes that is a limitation of Easy auth

Did you try to add several resources in the manifest: https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=azure-resource-explorer%2Ccommand-line#configure-app-service-to-return-a-usable-access-token ?

but frankly, in your scenario:
- copy the client ID that EasyAuth generated from you
- copy the client secret it has generated for you
- copy the tenant ID
- provide them in the configuration (appsettings.json or through the delegate as you've done)

and disable the "authentication" part of EasyAuth.

This will work seamlessly locally and in app service, without the limitations;

**Comment by GeorgeNarcis** [comment]
@jmprieur we are using auth v2 where resource is not supported anymore and I needed to use scopes.

So I ve added in the manifest in the loginParameters section in the scope property the scope for the downstream API I wanted to get access tokens in the format {appId}/{scopeName} and that worked, after this the GetAccessTokenForUserAsync  started returning the right tokens with audience set for the API I wanted.

But I don't see how you can accommodate this for multiple APIs since the GetAccessTokenForUserAsync  will always return the same token regardless of the scopes parameter you send, but I now understand this is a limitation of the AppService authentication that maybe should be made clear somewhere in the docs.
 Thank you for your support !

**Comment by jennyf19** [comment]
seems to be resolved. closing, but feel free to reopen if needed. thanks.
