### ISSUE TITLE
[Bug] AddProtectedWebApi is missing on IServiceCollection

### ISSUE THREAD

**Issue by makemefeelgr8** [AzureAD/microsoft-identity-web#1338]
This issue is still not fixed:
https://github.com/AzureAD/microsoft-identity-web/issues/78

I installed Microsoft.Identity.Web 1.14.1 nuget package into my .NET 5 solution and tried to use Azure AD to authenticate users, like:

    services.AddProtectedWebApi(Configuration);

But it said there is no such method on IServiceCollection.
Please, fix.
Thanks.

**Comment by jennyf19** [comment]
That is the old API. Please use `.AddMicrosoftIdentityWebApi(Configuration)`

@makemefeelgr8  Is there a doc which says to use `services.AddProtectedWebApi(Configuration);`? Asking so we can fix it. Thanks.

**Comment by makemefeelgr8** [comment]
> That is the old API. Please use `.AddMicrosoftIdentityWebApi(Configuration)`

Thanks, it worked.

> Is there a doc which says to use `services.AddProtectedWebApi(Configuration);`?

No, it's just that most of 3rd party tutorials and stackoverflow answers are relying on this function.

**Comment by jennyf19** [comment]
@makemefeelgr8  if you come across them again, feel free to let us know, or provide the updated answer. thank you for the follow-up!
