### ISSUE TITLE
claims transformation question

### ISSUE THREAD

**Issue by vsarunov** [AzureAD/microsoft-identity-web#1339]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [X] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

**Repro**

**Expected behavior**
When adding `[RequiredScope(RequiredScope)]` expected to authorize the endpoint if the scope is present.

**Actual behavior**
'IDW10203: The 'scope' or 'scp' claim does not contain scopes 'search:users' or was not found. '

**Possible solution**
inside `RequiredScopeFilter.cs` add another claim type or allow to specify the name of the claim.

**Additional context / logs / screenshots**
![image](https://user-images.githubusercontent.com/13823101/126791246-9af19a1a-1fbc-41af-b993-fc8b80fdcd46.png)

**Comment by jennyf19** [comment]
@vsarunov How is `search:users` a scope? is there a standard defining this as a scope?

**Comment by jennyf19** [comment]
closing, but feel free to reopen.
