### ISSUE TITLE
[Bug] No way to specify tenant id to instantiate GraphServiceClient with when using AddMicrosoftGraphAppOnly

### ISSUE THREAD

**Issue by vvolodin** [AzureAD/microsoft-identity-web#1343]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.15.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app.

**Repro**

I'm using `AddMicrosoftGraphAppOnly` to call Graph using my app's client credentials. After I've added `EnableTokenAcquisitionToCallDownstreamApi` I can successfully get the token using `TokenAcquisition.GetAccessTokenForAppAsync("https://graph.microsoft.com/.default", tenantId.ToString(), null)`. However when I've added `AddMicrosoftGraphAppOnly` and tried using injected `GraphServiceClient` I couldn't find a way to set tenantId for the request.

**Expected behavior**
Make it possible to specify tenant Id to use when constructing `GraphServiceClient`.

**Actual behavior**
`TokenAcquisitionAuthenticationProviderOption` only has one property set - `AppOnly`. TenantId is null.

**Possible solution**
Make it possible to change TenantId in `graphServiceClientFactory`.

**Comment by jennyf19** [comment]
@vvolodin you can use [`.WithAppOnly()`](https://github.com/AzureAD/microsoft-identity-web/blob/14429b8cb93352d78b6e1618d3a0bb50f203602d/src/Microsoft.Identity.Web.MicrosoftGraph/BaseRequestExtensions.cs#L35) and specify the tenantId. 

```csharp
var messages = await _graphServiceClient.Applications
                .Request()
                .WithAppOnly(tenant:"some_tenant")
                .GetAsync();
```

**Comment by vvolodin** [comment]
I don't have WithAppOnly available on Request(). What package does it come from? Anyway, I don't really understand how would this fetch the confidential client token for the given tenant...

**Comment by jennyf19** [comment]
@vvolodin it comes from Microsoft.Identity.Web.MicrosoftGraph.

**Comment by vvolodin** [comment]
Ok, checked the source code out, that's what I need. Thank you very much for you help.

**Comment by jennyf19** [comment]
closing. feel free to reopen.
