### ISSUE TITLE
[Bug] Issue w/default view

### ISSUE THREAD

**Issue by cmydur** [AzureAD/microsoft-identity-web#1349]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

I'm using 1.15.1

**Where is the issue?**
* Web app
    * [ x] Sign-in users 

**Is this a new or an existing app?**

**Repro**

```csharp
  public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews().AddMicrosoftIdentityUI();
            services.AddAuthentication(options =>
                {
                    options.DefaultScheme = OpenIdConnectDefaults.AuthenticationScheme;
                }
                ).AddMicrosoftIdentityWebApp(Configuration, AppSettingsKeys.ADConfigKey);
        }


...
 app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");                
            });

```

``` json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
  ,
  "AzureAdB2C": {
      "Instance": "https://***.b2clogin.com",
      "Domain": "***.onmicrosoft.com",
      "TenantId": "***",
      "ClientId": "***",
      "SignedOutCallbackPath": "/",
      "SignUpSignInPolicyId": "B2C_1_login",
      "ResetPasswordPolicyId": "B2C_1_password_reset",
      "EditProfilePolicyId": "b2c_1_edit_profile"  
    }
}

```

**Expected behavior**
The default route should render the view, however it is not. 

**Actual behavior**
<img width="1552" alt="Screen Shot 2021-07-27 at 8 59 27 AM" src="https://user-images.githubusercontent.com/16563092/127157705-3745cc68-05f0-4990-85ae-d0004000265b.png">

However if I navigate to /Home or /Home/Index the view renders
<img width="1102" alt="Screen Shot 2021-07-27 at 9 01 29 AM" src="https://user-images.githubusercontent.com/16563092/127158085-06f403e3-41d1-4614-a604-bbce1289d76d.png">

**Possible solution**

**Additional context / logs / screenshots**

If I remove .AddMicrosoftIdentityWebApp(Configuration, AppSettingsKeys.ADConfigKey); then it starts working, but the authentication does not work.

**Comment by jennyf19** [comment]
@cmydur did you try this:
```charp
services.AddAuthentication(options =>
    {
            options.DefaultScheme = OpenIdConnectDefaults.AuthenticationScheme;
     }
     ).AddMicrosoftIdentityWebApp(Configuration, AppSettingsKeys.ADConfigKey);
services.AddControllersWithViews().AddMicrosoftIdentityUI();
```

**Comment by cmydur** [comment]
Yes I did and I'm still having same issue

**Comment by cmydur** [comment]
I just found the issue. 

I had  `"SignedOutCallbackPath": "/"` in the appsetting. For some reason having the "/" was causing the issue, when I remove this fields or add something to the path e.g "/singout-oidc", it started working.

How can we debug these kind of issues, was it an error from Azure ADB2C that was unhandled somewhere?

**Comment by jennyf19** [comment]
that's interesting. I will need to take a look and get back to you. glad you are unblocked now. appreciate the quick follow-up.

**Comment by jennyf19** [comment]
@Tratcher any tips on how to debug this?

**Comment by Tratcher** [comment]
Turning all the log levels up to Debug is the first step.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging

**Comment by jennyf19** [comment]
@cmydur closing as you have the issue figured out.  i'll look into updating our documentation to be more specific.
