### ISSUE TITLE
[Bug] - [Client Credential Flow] - IDW10106: The 'ClientId' option must be provided. 

### ISSUE THREAD

**Issue by LeonorTeixeiraUA** [AzureAD/microsoft-identity-web#1350]
**Which version of Microsoft Identity Web are you using?**
1.15.1

**Where is the issue?**
* Web API
    * [x] Protected web APIs (Configurating Client Credential Flow)

**Is this a new or an existing app?**
This was working with the **On Behalf flow**, once we changed to a **Client Credential Flow**, we started getting a "IDW10106: The 'ClientId' option must be provided. "

**Repro**

```csharp
            services.AddMicrosoftIdentityWebApiAuthentication(Configuration)
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddDownstreamWebApi("BcApi", Configuration.GetSection("BCApiConfig"))
                .AddInMemoryTokenCaches();
```

```json
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "ClientId": "---",	
    "ClientSecret": "---",	
    "CallbackPath": "/<not used>",	
    "Domain": "---",
    "TenantId": "---",

  },
  "BCApiConfig": {
    "BaseUrl": "https://api.businesscentral.dynamics.com/v2.0/---/sandbox/api",
    "Scopes": "https://api.businesscentral.dynamics.com/.default"
  }
}
```

**Expected behavior**
A working configuration.

**Actual behavior**
Although **ClientId** is configured, when calling the API, we get an error: **"IDW10106: The 'ClientId' option must be provided. "**

**Comment by jennyf19** [comment]
@LeonorTeixeiraUA what do you mean by client credentials? what specifically did do you mean when you say you changed from OBO to client credentials?

**Comment by jennyf19** [comment]
Closing, as we need more info. Please re-open if needed. Thanks, @LeonorTeixeiraUA .
