### ISSUE TITLE
The ResponseType is reset to Code in the EnableTokenAcquisitionToCallDownstreamApi call

### ISSUE THREAD

**Issue by Shazwazza** [AzureAD/microsoft-identity-web#1366]
**Which version of Microsoft Identity Web are you using?**

1.15.2

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

The issue is that the ResponseType is reset to `Code` in the EnableTokenAcquisitionToCallDownstreamApi when it calls `WebAppCallsWebApiImplementation` at https://github.com/AzureAD/microsoft-identity-web/blob/ce9d7322072b0ffd08cd8abd9027c958d1a52e1b/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs#L123

**Is this a new or an existing app?**

This app is in development and not in production yet.

**Repro**

```csharp
auth.AddMicrosoftIdentityWebApp(
                        microsoftIdentityOptions =>
                        {
                            // This callback will be called twice.

                            // This will be overwritten by EnableTokenAcquisitionToCallDownstreamApi + WebAppCallsWebApiImplementation
                            microsoftIdentityOptions.ResponseType = OpenIdConnectResponseType.CodeIdToken;                            
                        },
                        openIdConnectScheme: "MyTestScheme",
                        // no cookie scheme
                        cookieScheme: null)
                        // Enable the MSAL magic
                        .EnableTokenAcquisitionToCallDownstreamApi();

// TODO: Add this to services.ConfigureOptions<ConfigureMicrosoftIdentityOptions>();
public class ConfigureMicrosoftIdentityOptions : IPostConfigureOptions<MicrosoftIdentityOptions>
{
    public void PostConfigure(string name, MicrosoftIdentityOptions options)
    {
        if (name != "MyTestScheme")
        {
            return;
        }

        // This will be overwritten by EnableTokenAcquisitionToCallDownstreamApi + WebAppCallsWebApiImplementation
        options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
}

// TODO: Add this to services.ConfigureOptions<ConfigureOpenIdConnectOptions>();
public class ConfigureOpenIdConnectOptions : IPostConfigureOptions<OpenIdConnectOptions>
{
    public void PostConfigure(string name, OpenIdConnectOptions options)
    {
        if (name != "MyTestScheme")
        {
            return;
        }

        // This will work
        options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
    }
}

```

**Expected behavior**

We configure the `MicrosoftIdentityOptions` with `IPostConfigureOptions` which will get merged to the open id connect options. But, these options are resolved before the call to  `WebAppCallsWebApiImplementation` which means `WebAppCallsWebApiImplementation` overwrites any configured options.  We require this to be `code id_token` but we cannot configure this on `MicrosoftIdentityOptions`.

**Actual behavior**

`MicrosoftIdentityOptions` (and therefore OpenIdConnectOptions) values get overridden by `WebAppCallsWebApiImplementation` because `MicrosoftIdentityOptions` are resolved in all cases before this method is called.

**Possible solution**

There are 2 work arounds for now. I can change the ResponseType directly within the `OnRedirectToIdentityProvider` or I can implement `IPostConfigureOptions<OpenIdConnectOptions>`. 

**Additional context / logs / screenshots**

I'm wondering:

* is it a bug that the options are pre-resolved before the `WebAppCallsWebApiImplementation` code for `AddOptions<OpenIdConnectOptions>(openIdConnectScheme)` is called? This means you can't configure the `MicrosoftIdentityOptions` for this and need to directly configure `OpenIdConnectOptions`.
* is this by design that no matter what or how options are configured that `WebAppCallsWebApiImplementation` overwrites the response type?
* Even if you configure options via the callback in the `AddMicrosoftIdentityWebApp` method, the ResponseType value will be overwritten. 
* It's worth noting that the options configuration callback in `AddMicrosoftIdentityWebApp` gets called twice by this code: `MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(msIdOptionsMonitor.Get(openIdConnectScheme), mergedOptions);` @ https://github.com/AzureAD/microsoft-identity-web/blob/8a1c8f4669bc75f078af1eb66a3a86b6e7b7d608/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L286

**Comment by jennyf19** [comment]
This should be addressed in [2.5.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.5.0), if the issue still repros, please reopen.
