### ISSUE TITLE
[Documentation] How to get log messages from caches in .NET classic

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-identity-web#1375]
### Documentation related to component

Token Caches

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

MIW allows .NET Classic developers to use token cache implementations. But I have not found a way to get log messages associated with the caches (not with MSAL) .

**Comment by jennyf19** [comment]
updated & [PR](https://github.com/Azure-Samples/active-directory-dotnet-v1-to-v2/pull/41) to add logging to the sample.
https://github.com/AzureAD/microsoft-identity-web/wiki/Logging#logging-in-net-framework-or-net-core
