### ISSUE TITLE
[Investigate] developer experience when required`"SignUpSignInPolicyId": "",` is not included in configuration options

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#138]
Currently, we detect B2C if the `"SignUpSignInPolicyId": "b2c_1_susi",` is present in the configuration. with the changes i've made to checking the required options parameters, if the above is not present, we assume it's AAD (this has not changed) and then we will throw a missing tenant-id error, as tenant-id is required for AAD but not B2C:
`System.ArgumentNullException: 'The TenantId parameter cannot be null or whitespace, and must be included in the configuration of the web app. For instance, in the appsettings.json file.  (Parameter 'TenantId')'`

Need to investigate further the developer experience and decide if this is the best way to detect b2c or not...probably not a better way as b2c can have custom domains (we'll hit the same issue MSAL has today with detecting B2C).

PS. I'm not sure what happens today if the su-si policy is not present, will check and update here.

@jmprieur thoughts?

**Comment by pmaytak** [comment]
- Does B2C have to have user flow in path?
- Does B2C have anything required specific in it's path or can both B2C and AAD technically be like so `"{pathBase}/{tenantId}/v2.0"`
- Maybe there's some other metadata that we can find out from if this is B2C?
- Lastly we can just add a remark to that error message - TenantId is required for AAD, UserFlow is required for B2C. User will have to figure out which one applies.

**Comment by jennyf19** [comment]
- B2C has to have a user flow, everything in B2C is based off of the user flow. Each user flow is a separate sts. 
- There is nothing specific to identify an authority as b2c, this is the same issue we have in all the MSALs. B2C accepts custom domains, so the authority could be anything.  The only way to know is to do string parsing or take the user flow separately, or make the developer specific a B2C authority, as in MSAL .NET (`.WithB2CAuthority`) or in native Android, iOS and JS, they have a known authorities list, where the developer gives all the authority URL strings up front.
B2C doesn't have instance discovery, like AAD does, which would help w/this. this is hopefully part of the merge.
- I thought of adding something to the error message, but in MSAL .NET, we got feedback that developers didn't like getting errors messages that did not pertain to them.
- Take a look at the B2C samples in the ASP .NET Core repo:
[sign in user](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C)
[call web api](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C)

**Comment by jennyf19** [comment]
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/357

**Comment by jmprieur** [comment]
We always have a tenant ID (now that we use the userinfo endpoint)

**Comment by jennyf19** [comment]
closing.
