### ISSUE TITLE
[Bug] The AzureADB2COpenIDConnectEventHandlers calls HandleResponse disallowing further middleware

### ISSUE THREAD

**Issue by Shazwazza** [AzureAD/microsoft-identity-web#1381]
**Which version of Microsoft Identity Web are you using?**

1.15.2

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

In development

**Expected behavior**

Custom middleware that is declared to keep processing after an OAuth error occurs and `AzureADB2COpenIDConnectEventHandlers .OnRemoteFailure` has executed. 

This is not possible currently because `AzureADB2COpenIDConnectEventHandlers .OnRemoteFailure` calls `context.HandleResponse();` but I don't think it should. I understand this library is opinionated but it is used outside of the opinionated UI that it tries to impose. The `AzureADB2COpenIDConnectEventHandlers .OnRemoteFailure` sets up redirects based on specific error states which is fine, but our OnRemoteFailure handler resets these redirects and we need our other custom middleware to continue executing.  Unfortunately, its not possible to undo a call to `context.HandleResponse();` due to setters on the `context.Result` not being public.

**Actual behavior**

Any custom middleware registered after auth providers will not execute once `AzureADB2COpenIDConnectEventHandlers .OnRemoteFailure` has been executed.

**Possible solution**

Don't call `context.HandleResponse();`

**Comment by jennyf19** [comment]
@Tratcher thoughts on this one? Seems similar to `context.Success();`

**Comment by Tratcher** [comment]
> Custom middleware that is declared to keep processing after an OAuth error occurs and `AzureADB2COpenIDConnectEventHandlers .OnRemoteFailure` has executed.

Can you share an example of your custom middleware?

The use of HandleResponse seems appropriate given OnRemoteFailure has generated redirects as the expected end of the request. To customize that could you wrap or replace the OnRemoteFailure event?

**Comment by Shazwazza** [comment]
@Tratcher yes that is what I've resorted to doing which means duplicating the code from the middleware to run explicitly in the `OnRemoteFailure` call. I understand that this has generated redirects but I don't see why it needs to short circuit the rest of the middleware. 

In this case, I have middleware that will write out a cookie based on if the HttpContext.Items contains specific information (similar to how TempData would work with cookies). This is generic middleware for handling any OAuth provider failures and we have generic methods to add this data to the HttpContext for any OAuth middleware on failures. 

For this particular OAuth provider, since it short circuits the request by calling `HandleResponse` in it's `OnRemoteFailure`, it means any downstream middleware does not execute. 

Hope that makes sense.

**Comment by Tratcher** [comment]
> I understand that this has generated redirects but I don't see why it needs to short circuit the rest of the middleware.

Only one middleware can respond to any request. A redirect is considered a full response and processing should not continue or else that redirect is likely to be overwritten by mistake.

These redirects are direct hooks back into the UI flow, I don't see how they could be implemented otherwise.

The other part of this I don't understand is how you expect to be able to handle a failure after the auth middleware? If the OnRemoteFailure event does not handle it then it's going to throw and fail the request, not continue executing middleware.
https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L132-L135

**Comment by Shazwazza** [comment]
I guess because this implementation is pretty opinionated and tied to an already implemented UI (which we do not use) I can understand what you mean. In our case, we don't use the UI we just use the underlying implementation so we don't have to rewrite this whole project like we did in the past :) Currently we change the redirect in our own `OnRemoteFailure` and handle any custom logic there which is working.

For other OAuth implementations for our app (Umbraco) which OOTB don't explicitly handle the errors or redirects, we have a custom middleware that does this - and now I realize we also short circuit when we redirect there too just like this one.

Appreciate the feedback, I'll close this one 👍
