### ISSUE TITLE
[Bug] Functions app with Downstream API - No ClientId was specified

### ISSUE THREAD

**Issue by Choonster** [AzureAD/microsoft-identity-web#1385]
**Which version of Microsoft Identity Web are you using?**
Currently using Microsoft.Identity.Web 1.14.1, because 1.15x versions aren't compatible with Azure Functions on .NET Core 3.1 due to differing versions of System.IdentityModel.Tokens.Jwt (see #1386).

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

c. This is a new app or an experiment.

**Repro**
- Create a new Functions app with the `func2` template and `SingleOrg` auth: `dotnet new func2 -i Microsoft.Identity.Web.ProjectTemplates::1.14.1  --auth SingleOrg`
- Add `.EnableTokenAcquisitionToCallDownstreamApi().AddInMemoryTokenCaches()` to the auth setup
- Configure the `AzureAd` settings in **appsettings.json**, including `ClientId`
- Add a new timer function that injects `ITokenAcquisition` and calls `GetAccessTokenForAppAsync`

Full code: https://github.com/Choonster/AzureFunctionsMicrosoftIdentityWebTest

**Expected behavior**
Function receives access token for the application.

**Actual behavior**
An exception about a missing `ClientId` is thrown:
```
MSAL.NetCore.4.34.0.0.MsalClientException: 
	ErrorCode: no_client_id
Microsoft.Identity.Client.MsalClientException: No ClientId was specified. 
   at Microsoft.Identity.Client.AbstractApplicationBuilder`1.Validate()
   at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Validate()
   at Microsoft.Identity.Client.AbstractApplicationBuilder`1.BuildConfiguration()
   at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.BuildConcrete()
   at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.Build()
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at azure_functions_ms_identity_web.TimerFunc.RunAsync(TimerInfo myTimer, ILogger log) in C:\Users\USER\source\repos\azure-functions-ms-identity-web\TimerFunc.cs:line 26
```

**Possible solution**
N/A

**Additional context / logs / screenshots**
The issue seems to be that the `MergedOptions.ConfidentialClientApplicationOptions` property getter is first called during options binding, which creates the `ConfidentialClientApplicationOptions` instance and copies the values from the `MergedOptions` instance before any of the configuration values have been bound. The `ConfidentialClientApplicationOptions` instance never seems to be updated after that, even by the `configureConfidentialClientApplicationOptions` action.

In my actual application, I'm trying to acquire a token to call an API from a durable activity function triggered by a timer. The Functions app and the API are both using EasyAuth with separate Azure AD app registrations. I'm configuring the authentication [here](https://github.com/Choonster/catalogue-scanner/blob/ff08a8abe0366db5a67cf817eca18c9472945503/CatalogueScanner.WebScraping/WebScrapingCatalogueScannerPlugin.cs#L47-L49), and acquiring the token [here](https://github.com/Choonster/catalogue-scanner/blob/ff08a8abe0366db5a67cf817eca18c9472945503/CatalogueScanner.WebScraping/Service/ColesOnlineService.cs#L54) (called from [this function](https://github.com/Choonster/catalogue-scanner/blob/ff08a8abe0366db5a67cf817eca18c9472945503/CatalogueScanner.WebScraping/Functions/DownloadColesOnlineSpecials/DownloadColesOnlineSpecials.cs#L24)).

**Comment by Choonster** [comment]
I've managed to work around this for now by injecting `IOptionsMonitor<JwtBearerOptions>` and calling `jwtBearerOptions.Get(Constants.Bearer)`, which triggers the merging of the options. I don't know if there's a better way to do this.

**Comment by tomseida** [comment]
I also am encountering this exception and tried the workaround specified by Choonster on Sept 12 comment. I am receiving the same exception blakesparkes. I using MIW 1.20.0. Is there a way to solve this issue?

**Comment by jennyf19** [comment]
This is fixed on the latest Azure Functions. Or you can use this [sample](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/DevApps/ContosoWorker) instead. Please reopen if necessary. Thank you.
