### ISSUE TITLE
Difference between two ways of acquiring a JWT from the same authoritative tenant

### ISSUE THREAD

**Issue by tango-charly** [AzureAD/microsoft-identity-web#1401]
Hello,

It's not an issue, but a simple **question**.

This is the context :

Two projects acquire an acces_token to authenticate the user by the same authority for the same target (ContosoApi).

The first is a web app that uses  `ITokenAcquisition` to acquire acces_token

```csharp
await this._tokenAcquisition.GetAccessTokenForUserAsync(scopes) 
```

The second is an console app that uses `IPublicClientApplication` to instantiate a web context and make the request with the user's information.

```csharp
await _application.AcquireTokenInteractive(scopes);
```

However, the access_token provided by the authority is not the same at all.

Access_Token acquired by TokenAcquisition service from Web App : 
Header :
```json
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "string",
  "kid": "string"
}
```
Payload :
```json
{
  "aud": "api://{clientId}",
  "iss": "https://sts.windows.net/{tenantId}/",
  "iat": 000,
  "nbf": 00,
  "exp": 000,
  "acr": 0,
  "aio": "",
  "amr": ["",""],
  "appid": "{clientId}",
  "appidacr": 0,
  "deviceid": "guid",
  "family_name": "",
  "given_name": "",
  "groups": ["Guid",".."],
  "ipaddr": "",
  "name": "",
  "oid": "Guid",
  "onprem_sid": "",
  "rh": "",
  "scp": ["{scopes}", ".."],
  "sub": "",
  "tid": "",
  "unique_name": "",
  "upn": "",
  "uti": "",
  "ver": ""
}
```
Access_Token acquired by PublicClientApplication from Console App : 

Header : 
```json
{
  "typ": "JWT",
  "nonce": "string",
  "alg": "RS256",
  "x5t": "string",
  "kid": "string"
}
```
Payload : 
```json
{
  "aud": "Guid",
  "iss": "string",
  "iat": 0,
  "nbf": 0,
  "exp": 0,
  "acct": 0,
  "acr": "1",
  "aio": "string",
  "amr": [
    "pwd",
    "rsa",
    "wia",
    "wiaormfa",
    "mfa"
  ],
  "app_displayname": "string",
  "appid": "guid",
  "appidacr": "0",
  "deviceid": "guid",
  "family_name": "string",
  "given_name": "string",
  "idtyp": "user",
  "ipaddr": "",
  "name": "string",
  "oid": "guid",
  "onprem_sid": "Guid",
  "platf": "string",
  "puid": "string",
  "rh": "string",
  "scp": "string",
  "signin_state": [
    "string"    
  ],
  "sub": "string",
  "tenant_region_scope": "string",
  "tid": "string",
  "unique_name": "string",
  "upn": "string",
  "uti": "string",
  "ver": "0",
  "wids": [
    "guid"
  ],
  "xms_st": {
    "sub": "string"
  },
  "xms_tcdt": 0
}
``` 

I had to understand what is the origin of this difference and what are the mechanisms behind these requests.

And why I can't use he second in Postman man ?
 I thought nonce was a protection to avoid the reuse of a token, but if I don't use the acces_token in the console app but in postman instead, the nonce token should be still valid, no ?

**Comment by jmprieur** [comment]
@tango-charly 
I don't understand your question. you seem to have processed the second one?

**Comment by tango-charly** [comment]
Ok, sorry i'm not clear.

In fact, both tokens are working fine.

However, when I retrieve the tokens right after acquiring them and testing them in postman, the token acquired by the App Console is not accepted by my API (signature invalid).
However, the one acquired by the web app is accepted.
In addition, payload tokens are different in their content.

However, the two projects have the same authority with the same scope.

I'm trying to understand what makes this difference ?

**Comment by tango-charly** [comment]
My questioning no longer needs to be. The configuration had a typo the scopes were not the same for the projects.
This explains the difference in results.
Sorry for the confusion.
