### ISSUE TITLE
[Feature Request] Improve the experience with long running process in web APIs leveraging MSAL.NET new API

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1414]
**Is your feature request related to a problem? Please describe.**
- Today, the developer experience with long running process is described in  https://github.com/AzureAD/microsoft-identity-web/wiki/get-token-in-event-handler
- MSAL introduces new public APIs to support this scenario better. See issue https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2733 and PR  https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2820.

**Describe the solution you'd like**

- Option 1: Surface the verbs in ITokenAcquisition or rather an extension class of ITokenAcquisition to avoid a breaking changes
- Option 2: Have an interface derived from ITokenAcquisition 
- Option 3: add a longRunningProcessSessionKey in TokenAquisitionOptions.

**Comment by jennyf19** [comment]
Included in [1.21.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.21.0)
