### ISSUE TITLE
[S360] Complete Service Life Cycle Onboarding and Compliance Onboarding

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-identity-web#142]
Complete the tasks needed to onboard to [Identity Service Life Cycle](https://greenlight.msftcloudes.com/Manage/9b914a88-dd55-4e23-962d-0004b4328f8f/Public?cloudFilter=1&timespanFilter=%3C%3D1,%3E1%20%26%26%20%3C5,%3E%3D5%20%26%26%20%3C10,%3E%3D10%20%26%26%20%3C30,%3E%3D30%20%26%26%20%3C90,%3E%3D90&stateFilter=0,1,2&taskId=ff5fb49b-9509-49f8-8db5-de17430cf107) and [compliance onboarding](https://microsoft.sharepoint.com/teams/Azure_Compliance/SitePages/Compliance%20Onboarding.aspx).

**Comment by jmprieur** [comment]
@pmaytak : is this finished? or do you have more to do ?
cc: @henrik-me

**Comment by pmaytak** [comment]
Working on it. Finishing up public facing work.

**Comment by jmprieur** [comment]
What is public facing work? compliance is not public facing?

**Comment by pmaytak** [comment]
I mean public facing as in issue fixes #182, #175, code work and compliance as in internal service requirements.

**Comment by jennyf19** [comment]
Last item to onboarding to ICM.
