### ISSUE TITLE
Both 'id_token' and 'access_token' should be present error should not be raised 

### ISSUE THREAD

**Issue by mrochon** [AzureAD/microsoft-identity-web#1422]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Microsoft Identity Web 1.1.0

**Where is the issue?**
* Web app
    * [ X] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment.

**Repro**

```            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAdB2C"));;

ResponseType = "code" set in appSettings.json
```

**Expected behavior**
No exception should be raised. It's OK to use Authz Code exchange to get just an id_token, without asking for an access_token as well. I do not want to use the hybrid flow to authenticate users to my app.

**Actual behavior**
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: IDX21336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateTokenResponse(OpenIdConnectProtocolValidationContext validationContext)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()

**Possible solution**
Remove code checking for presence of access token if no non-OIDC scopes were used in original request for authz code.

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@mrochon this exception is not raised by Microsoft.identity.web but by Microsoft.IdentityModel
Please raise your issue in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues

**Comment by jennyf19** [comment]
closing, as opened in another repo and external.
