### ISSUE TITLE
[Bug] Thread block issue in Assembly Microsoft.Identity.Web, Version=1.14.0.0

### ISSUE THREAD

**Issue by sheetalchhabra** [AzureAD/microsoft-identity-web#1424]
**Which version of Microsoft Identity Web are you using?**
Version=1.14.0.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [**] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft Identity Web 1.14.0

**Repro**

We migrated ADAL to MSAL 4.33.0 and we started seeing high thread count issue for many of our customers. 
 
Thread count keeps spiking up and never goes down even after traffic reduces, until app is restarted. 
Thread count ~12k

![image](https://user-images.githubusercontent.com/89986256/131855962-994c9e38-7c8d-49c6-8da2-80d130d79df8.png)

We narrowed down that problem seems to be with token cache serializer for which we use AddInMemoryTokenCache(..) method of Microsoft.Identity.Web assembly. Below is the exact snippet of code:

 
this.app.AddInMemoryTokenCache();

 
Complete method:

![image](https://user-images.githubusercontent.com/89986256/131856831-11baadd5-4666-4e8f-a5ab-bd45182a2b78.png)

After removing this.app.AddInMemoryTokenCache() method call, thread count is ~100
 
![image](https://user-images.githubusercontent.com/89986256/131856041-57d86a98-8074-48eb-974e-5e15e0cc6bc0.png)

When we looked at thread dump, we saw exceptions related to semaphoreslim lock
 
[[GCFrame]]
[[HelperMethodFrame_1OBJ] (System.Threading.Monitor.ObjWait)] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
mscorlib_ni!System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(Int32, UInt32, System.Threading.CancellationToken)+8b
mscorlib_ni!System.Threading.SemaphoreSlim.Wait(Int32, System.Threading.CancellationToken)+151
System!System.Collections.Concurrent.BlockingCollection`1[[Microsoft.Extensions.Logging.Console.LogMessageEntry, Microsoft.Extensions.Logging.Console]].TryTakeWithNoTimeValidation(Microsoft.Extensions.Logging.Console.LogMessageEntry ByRef, Int32, System.Threading.CancellationToken, System.Threading.CancellationTokenSource)+101
System!System.Collections.Concurrent.BlockingCollection`1+d__68[[Microsoft.Extensions.Logging.Console.LogMessageEntry, Microsoft.Extensions.Logging.Console]].MoveNext()+c9
Microsoft_Extensions_Logging_Console!Microsoft.Extensions.Logging.Console.ConsoleLoggerProcessor.ProcessLogQueue()+67
mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+172
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+15
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+55
mscorlib_ni!System.Threading.ThreadHelper.ThreadStart()+55
[[GCFrame]]
[[DebuggerU2MCatchHandlerFrame]]
[[ContextTransitionFrame]]
[[DebuggerU2MCatchHandlerFrame]] 
 
Second stacktrace:
[[HelperMethodFrame_1OBJ] (System.Threading.WaitHandle.WaitOneNative)] System.Threading.WaitHandle.WaitOneNative(System.Runtime.InteropServices.SafeHandle, UInt32, Boolean, Boolean)
mscorlib_ni!System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean)+1c
mscorlib_ni!System.Threading.WaitHandle.WaitOne(System.TimeSpan, Boolean)+4b
mscorlib_ni!System.Threading.WaitHandle.WaitOne(System.TimeSpan)+12
Microsoft_ApplicationInsights!Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.Runner()+64
mscorlib_ni!System.Threading.Tasks.Task.Execute()+47
mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+172
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+15
mscorlib_ni!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)+231
mscorlib_ni!System.Threading.Tasks.Task.ExecuteEntry(Boolean)+a1
mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+172
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+15
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+55
mscorlib_ni!System.Threading.ThreadHelper.ThreadStart(System.Object)+60 
 
**Expected behavior**
Thread count shouldn't spike when there is no traffic on app.

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.
Thread count goes high, eats the computations resources of webapp and users experience performance degradation.

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jennyf19** [comment]
Does this repro with the latest version? Please use 1.16 and let us know if the issue continues. thanks
