### ISSUE TITLE
Enable authorization code flow

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#1438]
According to [Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow), authorization code flow is preferred; however with the code and configuration below, Microsoft.Identity.Web appears to be using the implicit grant flow. 

- Is there a reason auth code flow is not turned on by default by Microsoft.Identity.Web? 
- How do I turn on auth code flow with Microsoft.Identity.Web if it is supproted?

`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=f3ec7f30-549c-4f41-9c94-2d9894c5c81d&redirect_uri=https%3A%2F%2Fomadeviacpi02.csgidev.com%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=637668075182143470.NTdlNjVlNzItZWMwZC00NTA5LWIwNzAtMTE4N2QxYmRhNjhkYjQ5YWRkY2EtNjQxNy00ZmYwLTgxYjYtZmQ0MWYzZjUwYTEz&client_info=1&x-client-brkrver=IDWeb.1.15.2.0&state=CfDJ8JozLpj9MHlDhrLpAtKTOb0srCB6xwOh84ZaRrji3UZGEbvmkzbDJGV3Uyr377K1zldS7KlTyp-sLQuym7MjM742OwvlH4SG1GSKBeV94dW1utPeXp6JTksRrlZ71CoFRe634mKu2k4MAVMc0ORXlA6SXvE3NjxxMAwzlah2DSatonE7Gn45kZtWimmB5Z8Vy5R27-xkK8P0eDv7XlLukKRYxmK3ZIVUf_YcTLp6XI71xVA9SO2uraXQobd8ID05YAye8iB7nCA7OemkEXarkWCvRUhk6hgJdLF24h60bxG1mjNap03s6yWrTro5Yezlcw&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.12.0.0`

```
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"));
```

```
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "common",
    "ClientId": "f3ec7f30-549c-4f41-9c94-2d9894c5c81d",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc"
  },
```

**Comment by WenningQiu** [comment]
Looks like the code below turns on the auth code flow:

`            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration, "AzureAd")
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddInMemoryTokenCaches();`

**Comment by jmprieur** [comment]
Yes, @WenningQiu. It does.

With:

```CSharp
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"));
```

you just let the user sign-in. You don't get a token to call an API from your web app.
Do you want to close this issue?

**Comment by WenningQiu** [comment]
@jmprieur Thanks for the confirmation. I'll close the ticket.

**Comment by nikosft** [comment]
> Yes, @WenningQiu. It does.
> 
> With:
> 
> ```cs
> services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
>                 .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"));
> ```
> 
> you just let the user sign-in. You don't get a token to call an API from your web app. Do you want to close this issue?

Still this does either [implicit flow](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitFlowAuth) (i.e., the request includes `response_type=id_token`), or [hybrid flow](https://openid.net/specs/openid-connect-core-1_0.html#HybridFlowAuth) (i.e., the request includes `response_type=code+id_token`). The  authorization code flow is a two step process: you get the authorization code (using response_type=code) and then you exchange it with the id token by invoking the token endpoint. 

This what the specs says, this is what [auth0 does](https://auth0.com/docs/get-started/authentication-and-authorization-flow/call-your-api-using-the-authorization-code-flow) this is what [amazon does](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html). I really don't get this mix up in Microsoft.Identity
