### ISSUE TITLE
[Enhancement] Infer authentication scheme from the request

### ISSUE THREAD

**Issue by dmcweeney** [AzureAD/microsoft-identity-web#1439]
**Which version of Microsoft Identity Web are you using?**
MIW 1.16.1
MIC 4.36.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
a. The app is in production but on my dev env I upgraded to a new version of Microsoft Identity Web.
More specifically I upgraded:
- MIW from 1.16.0 to 1.16.1
- MIC from 4.35.1 to 4.36.1

**Expected behavior**
Should still work!

**Actual behavior**
Getting the following exception from GetAccessTokenForUserAsync

Microsoft.Identity.Web.TokenAcquisition: [MsIdWeb] An error occured during token acquisition: No account or login hint was passed to the AcquireTokenSilent call. 
MSAL.NetCore.4.36.1.0.MsalUiRequiredException: 
	ErrorCode: user_null
Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call. 
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForWebAppWithAccountFromCacheAsync(IConfidentialClientApplication application, ClaimsPrincipal claimsPrincipal, IEnumerable1 scopes, String authority, MergedOptions mergedOptions, String userFlow, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
	StatusCode: 0 
	ResponseBody:  
	Headers: 

I reverted back to the previous versions of MIW and MIC and app is working again.

**Comment by jmprieur** [comment]
Do you have repro steps, @dmcweeney ?
also do you need to update MSAL.NET? (given it's available by transitive closure through MSAL.NET) ?

**Comment by dmcweeney** [comment]
@jmprieur 
Yes MSAL.Net (MIC) was updated to 4.36.1.

As regards repro steps - I literally updated the packages and reran the app ensuring I did a sign in. Then triggered a piece of code that called GetAccessTokenForUserAsync to call the graph api requiring User.ReadBasic.All scope and aforementioned exception was throw.

I reverted to the previous version of the 2 packages, did a full rebuild and repeated the above steps and it ran fine.

Do you want to see logs of both runs...

**Comment by jmprieur** [comment]
what happens if you remove the MIC nuget pacakge, @dmcweeney ?

**Comment by dmcweeney** [comment]
@jmprieur I will have to do that Monday - (having problems downloading a different package)

**Comment by dmcweeney** [comment]
@jmprieur 

If I remove the explicit reference to the MIC package the behaviour is the same.

Using MIW 1.16.1 the above "bug" happens. This pulls in MIC 4.36.0.

![image](https://user-images.githubusercontent.com/1087374/133078685-7e5d3cfa-ee02-421c-b8cd-74395fb35baf.png)

If I revert to MIW 1.16.0 it works. This pulls in MIC 4.35.1.

![image](https://user-images.githubusercontent.com/1087374/133078824-109f8b0f-0d50-4ca1-8c88-6d9463a472dd.png)

I notice here that when using MIW 1.16.0 my Asp.Net Core authentication Jwtbearer and OIDC packages have reverted back to 3.1.8 from 3.1.18

Let me know if you need anything else...

**Comment by jennyf19** [comment]
@dmcweeney we had a security alert to move from 3.1.8 to 3.1.18, which is why 1.16.1 is on 3.1.18. do you have a link to your code or repro code you can share? thanks.

**Comment by dmcweeney** [comment]
@jennyf19  
I do not have the code available publically but more than happy to share a debugging session with you over Teams.
Also I can send you the logs of the MSAL logging for AuthorizationCodeReceived and GetAccessTokenForUserAsync for both 1.16.0 and 1.16.1 (to your private email - save me scrubbing the logs).

**Comment by jennyf19** [comment]
@dmcweeney we can start with the logs, thanks. jeferrie@microsoft.com

**Comment by dmcweeney** [comment]
@jennyf19 wondering if ye made any progress on this issue?

**Comment by jennyf19** [comment]
no, sorry @dmcweeney will try to before end of week. sorry for the delay.

**Comment by dmcweeney** [comment]
@jmprieur  @jennyf19  sent ye invites to repo that contains repro app...

**Comment by jennyf19** [comment]
what are you using in your controller?

**Comment by jennyf19** [comment]
We are not able to find a way to infer the scheme from the request. Closing.
