### ISSUE TITLE
[Feature Request] Adding a method on downstreamWebApi to call without an access token

### ISSUE THREAD

**Issue by v-fearam** [AzureAD/microsoft-identity-web#1445]
**Is your feature request related to a problem? Please describe.**
I have an API, some methods are private and need a token and the downstreamWebApi  is great, but it has one public method which is used on the home page which doesn't require to be sigin.
In the service I need to add a http client to do that call.

**Describe the solution you'd like**
I would like to call the public endpoint throught the downstreamWebApi  

**Describe alternatives you've considered**
N/A

**Additional context**
Example:
https://github.com/mspnp/multitenant-saas-guidance/pull/124#discussion_r708515676
https://github.com/mspnp/multitenant-saas-guidance/blob/a99058120927aec5f4180543c9a4d85aaa4c3890/src/Tailspin.Surveys.Web/Services/SurveyService.cs#L70-L76

**Comment by jmprieur** [comment]
@brentschmaltz FYI, as I was telling you.

**Comment by jmprieur** [comment]
Done in rel/v2 (don't pass scopes)
