### ISSUE TITLE
Using ITokenAcquisition in the IHostedService.StartAsync doesn't work

### ISSUE THREAD

**Issue by qetza** [AzureAD/microsoft-identity-web#1449]
Hello,

I'm trying to create a hosted service in aspnet core that needs to call during its startup (`StartAsync`) an API with an application token (client id & client secret).

When calling `GetAccessTokenForAppAsync` i'm getting a null reference exception from `MergedOptions.PrepareAuthorityInstanceForMsal`. After some testing the issue seems to be that my call in the hosted service `StartAsync` is done before the MergedOptions is configured (if i comment the code in the service i can see that the delegate on `AddMicrosoftIdentityWebApp` is called later).

Is there a way force the configuration of all the options so that i can use `ITokenAcquisition` in the `StartAsync` of an `IHostedService`?

Thanks

**Comment by jmprieur** [comment]
@qetza : are you using the latest Ms.Id.Web? We believe that this was fixed in [1.16.1](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.16.1)

If it isn't fixed, please share some repro code with us.
cc: @jennyf19

**Comment by qetza** [comment]
Hello @jmprieur,
Here is a simple web app to repro the issue based on 1.16 : [HostedServiceWithTokenAcquisition.zip](https://github.com/AzureAD/microsoft-identity-web/files/7184130/HostedServiceWithTokenAcquisition.zip)

This is a base new aspnet core webapp project where i added a hosted service with a dependency on ITokenAcquisition and the needed code in the Startup to register everything. The code is logging the calls and exception so by running the app you can see in the console the order of the calls.

Some remarks:
- i only need the ITokenAcquisition but to have it available i need to go through the full `AddAuthentication` code and we need to call `UseAuthentication` which is a lot of code and services added.
- as the ITokenAcquisition is registered as scoped and hosted service is a singleton we need a workaround to resolve the ITokenAcquisition, maybe we could have back the option to register it as a singleton or have an accessor class to hide this issue.
- my scenario is to have a hosted service which connects to a azure signalr service using negotiate endpoint which needs authorization so i'm generating a token in the AccessTokenProvider deletage of SignalR.

Maybe i should use directly MSAL library?

**Comment by qetza** [comment]
Using directly MSAL.Net (`IConfidentialClientApplication`) is working so maybe for this scenario were we just need to get a token for an app we will switch to MSAL.Net

**Comment by jmprieur** [comment]
Closing as answered, feel free to reopen, @qetza
