### ISSUE TITLE
[Documentation] Incorrect authentication scheme shown in replacement example

### ISSUE THREAD

**Issue by RobSiklos** [AzureAD/microsoft-identity-web#1453]
### Documentation related to component
Web Apps

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in the example
- [ ] needs an example

### Description of the issue
In https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps, in the first C# example, the auth scheme should be replaced with `OpenIdConnectDefaults.AuthenticationScheme`, but the replacement still shows `AzureADDefaults.AuthenticationScheme` which is incorrect.

**Comment by jennyf19** [comment]
@RobSiklos thanks, have fixed.
