### ISSUE TITLE
[Bug] Microsoft Signing Key endpoint is not returning constant keys

### ISSUE THREAD

**Issue by apoorvkapil** [AzureAD/microsoft-identity-web#1459]
**Which version of Microsoft Identity Web are you using?**
Latest

**Where is the issue?**
* Other (please describe)
[Microsoft Discovery key](https://login.microsoftonline.com/common/discovery/keys) returning different keys intermittently.

**Repro**
calling below url from multiple source returning different keys.
```csharp  
https://login.microsoftonline.com/common/discovery/keys 
```

**Expected behavior**
Expected to return same public keys even if MS rotating the keys.

**Actual behavior**
above URL returning different keys sets (sometime 4, sometimes 5 or 6)

**Possible solution**

**Additional context / logs / screenshots**
As Microsoft state that "the keys can be changed any time we have created scripts to detect if there is a change in Keys's 'kid' from Microsoft Discovery Keys endpoint". It really works well we identified a change in keys 3 days back in Night and it rolled out as expected. however we identified the issue when we saw that rollout is happening periodically. after troubleshooting we experienced this unexpected behavior from AAD Endpoint [Microsoft Discovery key](https://login.microsoftonline.com/common/discovery/keys), which intermittently responding with 4 or 5 keys. I have attached 2 files for reference with different response.
[azureKeys5.txt](https://github.com/AzureAD/microsoft-identity-web/files/7235543/azureKeys5.txt)
[response-loginkeyMS.txt](https://github.com/AzureAD/microsoft-identity-web/files/7235549/response-loginkeyMS.txt)

**Comment by jmprieur** [comment]
@apoorvkapil is it a Microsoft.Identity.Web bug?

**Comment by apoorvkapil** [comment]
Well this is the only service I could relate it to, these Keys are used for OAuth2.0 and Enterprise Application , which is part of Microsoft Identity. If you think it shouldn't, please help to tag to the right team.

**Comment by jmprieur** [comment]
@hpsin do you have an idea?

**Comment by hpsin** [comment]
Investigating, thanks @jmprieur.  I have repro'd this behavior, and can't quickly explain it. Working with engineers to understand this.

**Comment by hpsin** [comment]
Hey all, 
We're adding a new key to our signing keys list, and to ensure a clean rollout this is done in rings.  You are seeing requests to different rings here - some rings have the old set of 3 keys, inner rings have 4 keys.  As part of adding a new key though, yes, you will see different numbers of keys at different times.  We do not use the new keys until they've been in all rings for a sufficient time to be picked up by RPs, so getting different numbers of keys should not be considered a blocker to app operation - as long as the key referenced by the `kid`/`x5t` claim.

**Comment by apoorvkapil** [comment]
@hpsin Thanks for clarifying.
although it not blocking the app functionality, yet creating lot's of minor 'changes' since 7 days at our end. We have a logic to check in script if there is a key change(comparing host keys kid with azure source key kids from the URL) . Now we thought the URL is source of truth for keys and even in case of a new key rollout by azure, script will detect the change and update it. yet this loop is continue since 7 days due this inconsistency.
Please answer below questions !
1. How much time does it takes to rollout key to all the rings ? what we can expect in a happy case scenario and worst case ?
2.  Is there any recommendation from Microsoft to manage these keys at the client end.

**Comment by apoorvkapil** [comment]
Closing the issue, as it the issue has been solved. I would still want MS to reconsider the strategy to deploy these keys and provide a source of truth for pub keys, which returns constant keys no matter if there are changes going on at backend, Newly added key should only be available for public (login URL) when It's deployed on all rings and after a certain time MS can start using it for Signing.

@hpsin  Thanks for clarification.
