### ISSUE TITLE
Web farm scenario

### ISSUE THREAD

**Issue by peterson4ts** [AzureAD/microsoft-identity-web#148]
### Documentation Related To Component:
Distributed memory and other relevant related configurations.

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
I believe it would be interesting for the community at large if we had instructions and examples of configuration for scenarios where applications are hosted on a web farm.
I am currently facing a series of problems related to the subject, as soon as I manage to resolve I intend to contribute with the solutions.

**Comment by strisys** [comment]
I ran into an issue with one aspect of this as I attempted to [store access tokens in Redis](https://github.com/AzureAD/microsoft-identity-web/issues/136).

**Comment by jmprieur** [comment]
@peterson4ts : did you read this: https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#distributed-redis-cache 
 ?

**Comment by peterson4ts** [comment]
> I ran into an issue with one aspect of this as I attempted to [store access tokens in Redis](https://github.com/AzureAD/microsoft-identity-web/issues/136).

I can confirm that my issue is different.
By using a reverse proxy between the client and the application, in case the request header is greater than the configured limit, in my case Nginx, an error occurs after the authentication process and during returning to the callback page.

**Comment by peterson4ts** [comment]
As it is not possible to collaborate on the project wiki and it does not make sense to have an example not referenced on the wiki I am closing this issue, but at least I’ll give you a summary that can help someone who’s going through the same problem.

**It may be possible that the limit size of the header**, defined in your reverse proxy, **is exceeded**, resulting in several errors depending on the current configuration of your application. This can occur due to the encryption process increasing the size of the cookie or depending on the number of claims that the token has, to resolve interact with your operation team by defining a new limit for the header.
In IIs this limit is 32kb.

It is worth mentioning that the bigger the header, the more bandwidth will be used for each request, so if your focus is on performance and cost reduction, a fine adjustment needs to be made in this sense.

In my case because I am not using the GRAPH API, I did the OAuth process with PKCE and using Redis as a distributed cache for the application. To avoid problems with configuring the cache, set the configuration to OIDC and DataProtection linking them to Redis.
I share below as an example of the code where these configurations described above were made:

```
services.AddStackExchangeRedisCache(setup =>
        {
             setup.Configuration = "yourRedisConn";
             setup.InstanceName = "yourAppName";
        })
        .AddDistributedMemoryCache();

services.Configure<CookiePolicyOptions>(options =>
{
      options.HandleSameSiteCookieCompatibility();
      options.Secure = CookieSecurePolicy.Always;
      options.CheckConsentNeeded = _ => true;
});

services.AddResponseCompression(options =>
{
     options.Providers.Add<BrotliCompressionProvider>();
     options.Providers.Add<GzipCompressionProvider>();
     options.EnableForHttps = true;
});
            
```

```
static void DefaultAuthenticationSetup(AuthenticationOptions options)
{
      options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
      options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
}

services.AddAuthentication(DefaultAuthenticationSetup)
        .AddCookie()
        .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, "Azure AD", options =>
        {
               options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
               options.Authority = "${configuration["AzureAd:Instance"].TrimEnd('/')}/{configuration["AzureAd:TenantId"]}/v2.0"";
               options.RequireHttpsMetadata = true;
               options.ClientId = configuration["AzureAd:ClientId"];
               options.ClientSecret = configuration["AzureAd:ClientSecret"];
               options.ResponseType = OpenIdConnectResponseType.Code;
               options.ResponseMode = OpenIdConnectResponseMode.FormPost;
               options.UsePkce = true;
               options.Scope.Add("profile");
               options.Scope.Add("offline_access");
               options.SaveTokens = true;
               options.CallbackPath = configuration["AzureAd:CallbackPath"];
               options.SignedOutCallbackPath = configuration["AzureAd:SignedOutCallbackPath"];

               options.TokenValidationParameters = new TokenValidationParameters
               {
                   NameClaimType = ClaimConstants.PreferredUserName,
               };

               options.RemoteAuthenticationTimeout = TimeSpan.FromSeconds(30);                        
        });

services.AddOidcStateDataFormatterCache();
```

```
services.AddRazorPages()
        .AddMvcOptions(options =>
        {
            options.Filters.Add(new AuthorizationPolicyBuilder()
                  .RequireAuthenticatedUser()
                  .AddAuthenticationSchemes(OpenIdConnectDefaults.AuthenticationScheme)
                  .Build());
        })
        .AddMicrosoftIdentityUI();

services.AddServerSideBlazor();
```

```
services.AddDataProtection()
        .PersistKeysToStackExchangeRedis(ConnectionMultiplexer.Connect("yourRedisConn"))
        .SetApplicationName("yourAppName");
```

**Some Observations:**
As you can see I am using **Blazor** and **forcing the use of HTTPS**, also for general application scope I apply settings so that HttpClient uses version 2.0 and TLS 1.2 (_not included here for brevity_).
**UsePkce = true is a valid instruction when using .net core 3.1** , so if it is in 2.2 it must be implemented, as shown in this [example](https://www.scottbrady91.com/OpenID-Connect/ASPNET-Core-using-Proof-Key-for-Code-Exchange-PKCE).
