### ISSUE TITLE
[Feature Request] Move AadIssuerValidator (and co) to its own library

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1487]
**Is your feature request related to a problem? Please describe.**
`AadIssuerValidator` is usable in many applications that need to validate tokens, not only in Microsoft.Identity.Web. In particular this is needed in SAL and MISE. Ideally it should be in Wilson, but this needs to be discussed and planned.

**Describe the solution you'd like**
- Extract AadIssuerValidator and MicrosoftIdentityWebIssuerValidator to a new assembly
  - Microsoft.Identity.Web.AadIssuerValidator or Microsoft.IdentityModel.Aad?
- allow minimum dependencies, which means we might want to remove the Options.
 
**Describe alternatives you've considered**
Force all applications to depend on IdWeb, but MISE and SAL won't.

**Comment by jennyf19** [comment]
Released in [1.19.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.19.0
