### ISSUE TITLE
[Bug] Setting OpenIdConnectOptions.EventsType to custom OpenIdConnectEvents results in MsalUiRequiredException

### ISSUE THREAD

**Issue by melix-dev** [AzureAD/microsoft-identity-web#1499]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.18.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment.

**Repro**
For the repro I used the sample code from here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-1-MyOrg. And walked through all required steps (creating app registrations + adding the necessary information to the appSettings files). This example works fine. 

But then I added `CustomOpenIdConnectEvents` class to the TodoListClient project, which just simply inherits from OpenIdConnectEvents. 

```csharp
using Microsoft.AspNetCore.Authentication.OpenIdConnect; 

namespace TodoListClient.Events 
{
    public class CustomOpenIdConnectEvents : OpenIdConnectEvents
    { 
        public CustomOpenIdConnectEvents() : base()  // I tried with and without ':base()'
        { }
    }
}
```

The next step I did, was changing Startup.cs in the same project, TodoListClient from this: 
```csharp 
    services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
        .EnableTokenAcquisitionToCallDownstreamApi(new string[] { Configuration["TodoList:TodoListScope"]})
        .AddInMemoryTokenCaches();
```
to this:
```csharp 
    services.AddScoped<CustomOpenIdConnectEvents>();
    services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
        .AddMicrosoftIdentityWebApp(Configuration)
        .EnableTokenAcquisitionToCallDownstreamApi()
        .AddInMemoryTokenCaches();
    services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
    {
        options.EventsType = typeof(CustomOpenIdConnectEvents);
    });
```
Eventually I want to override the OnTokenValidated method in the CustomOpenIdConnectEvents class.

**Expected behavior**
When navigating in the TodoListClient web app to the TodoList menu item, it will call ITokenAcquisition GetAccessTokenForUserAsync(new[] {_TodoListScope}) without an error when configuring a custom OpenIdConnectEvents class.

**Actual behavior**
When navigating in the TodoListClient web app to the TodoList menu item, it will call ITokenAcquisition GetAccessTokenForUserAsync(new[] {_TodoListScope}) and throws an MsalUiRequiredException. 
> Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException: 'IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent. '
> Inner Exception
> MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.
And this is in a loop for quite a while. Eventually showing an error in the browser that I cannot be logged in again. 

If I comment out the eventstype part in Startup.cs, it works again.
```csharp 
    ...
    services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
    {
        // options.EventsType = typeof(CustomOpenIdConnectEvents);
    });
```

**Possible solution**
...

**Additional context / logs / screenshots**
![image](https://user-images.githubusercontent.com/20542194/138447063-f5c7b588-6e93-45c1-9f72-f2b66c8d6e3b.png)

**Comment by jmprieur** [comment]
@melix-dev : you'd want to derive from `MicrosoftIdentityOptions` (which itself derives from `OpenIdConnectOptions`)

There are simpler ways to override the OnTokenValidated event though: See https://github.com/AzureAD/microsoft-identity-web/wiki/customization#openidconnectoptions
