### ISSUE TITLE
WebApi service calling downstream Graph API doesn't return all user data.

### ISSUE THREAD

**Issue by dotnetjunky** [AzureAD/microsoft-identity-web#1505]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.18.0
Microsoft.Identity.Web.MicrosoftGraphBeta 1.18.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [X] Protected web APIs call downstream web APIs
* Token cache serialization
     * [X] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**

I'm writing an Office App add-in which obtains a single-sign-on bootstrap token. It will then send the token to my ASP.NET Core Web API service which in turn calls the Microsoft Graph API. I have followed the instructions to set up Azure AD app.

In my Web API startup code, I have: 

```cs
builder.Services
	.AddMicrosoftIdentityWebApiAuthentication(builder.Configuration)
	.EnableTokenAcquisitionToCallDownstreamApi()
	.AddMicrosoftGraph(
		"https://graph.microsoft.com/beta", 
		"user.read user.readbasic.all profile openid")
	.AddInMemoryTokenCaches();
```

In my Controller's Action method, I want to obtain some basic information of **other users** in my organization. Here's the code in which I look up user based on email address and select a few data from the user:

```cs
 var selectRequest = _graphServiceClient.Users.Request()
            .Filter("mail eq 'someone@mycompany.com'")
            .Select((user) => new {
                Id = user.Id,
                DisplayName = user.DisplayName,
                UserPrincipalName = user.UserPrincipalName,
                City = user.City,
                Country = user.Country,
                BusinessPhones = user.BusinessPhones
            });
```

On the client side, I initiate a consent dialog which requires user to agree to the `user.read` and `user.basicread.all` permissions. 

At runtime, the Graph API call succeeds, but it returns only the `Id`, `DisplayName` and `UserPrincipalName` data. The `City`, `Country` and `BusinessPhones` properties are all `null`. 

When I tried the following query on Graph Explorer, it returned the all the data, including city, country and business phones. 

`https://graph.microsoft.com/beta/users?$filter=mail eq 'someone@mycompany.com'&$select=Id,city,country,businessPhones`

I'm at lost with why my code returns different results than Graph Explorer. How I can debug and fix my code so that it can return all the data? Any help is appreciated.

**Comment by jennyf19** [comment]
closing as external, but we can continue the conversation here.

**Comment by dotnetjunky** [comment]
@jennyf19  why is it external? Isn't it related to the Microsoft.Identity.Web API? Could you please point me to the more appropriate place to ask this question?

**Comment by jennyf19** [comment]
It's external because it's the Graph SDK. @darrelmiller was tagged earlier, he is from the Graph SDK.

**Comment by dotnetjunky** [comment]
@darrelmiller Do you have any hint as to why my code doesn't return all user data like the Graph Explorer?

**Comment by jmprieur** [comment]
@dotnetjunky reading https://stackoverflow.com/questions/48229949/get-all-user-properties-from-microsoft-graph, I believe that what you wrote should work

**Comment by darrelmiller** [comment]
The permission User.ReadBasic.All only allows you to get "display name, first and last name, email address, open extensions and photo."  https://docs.microsoft.com/en-us/graph/permissions-reference#delegated-permissions-73

Your Graph Explorer has probably been consented to User.Read.All so it can access all the information for all users.

**Comment by dotnetjunky** [comment]
@darrelmiller  Thanks for the answer. I checked Graph Explorer, and I saw that **User.Read.All** is _not_ consented, but **User.ReadWrite.All** is consented. I'm not clear how Graph Explorer can have the **User.ReadWrite.All** permission, given that it requires Admin consent. Any idea why?

**Comment by dotnetjunky** [comment]
This is the screenshot of the permissions.

![image](https://user-images.githubusercontent.com/7623075/139561691-b1869e8d-f5f2-4502-869f-9d2a32df614f.png)

**Comment by darrelmiller** [comment]
@dotnetjunky  CSEO has consented Graph Explorer to some permissions in the Microsoft tenant.  As Graph Explorer only makes delegated calls, users can only access information they have access rights for, even though Graph Explorer has been consented to User.ReadWrite.All.

**Comment by dotnetjunky** [comment]
Thank you for your explanation. That makes sense now.

**Comment by dotnetjunky** [comment]
@darrelmiller  Do you know who/how I can contact CSEO to request similar permissions for my app?
