### ISSUE TITLE
[Bug] PrepareAuthorityInstanceForMsal() throws NullReferenceException

### ISSUE THREAD

**Issue by thestillheron** [AzureAD/microsoft-identity-web#1507]
**Which version of Microsoft Identity Web are you using?**
```
<PackageReference Include="Microsoft.Identity.Web" Version="1.18.0" />
<PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="1.18.0" />
<PackageReference Include="Microsoft.Identity.Web.UI" Version="1.18.0" />
```

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment. Specifically, an existing app with a new requirement to call Microsoft Graph API endpoints.

**Repro**

```csharp Startup.cs
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    private IConfiguration Configuration { get; }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        var appConfig = Configuration.GetSection(nameof(ApplicationConfig)).Get<ApplicationConfig>();
        var adConfig = Configuration.GetSection(nameof(AzureAd)).Get<AzureAd>();

        services.AddSingleton(appConfig);
        services.AddSingleton(adConfig);

        services.AddHttpContextAccessor();
        services.AddApplicationInsightsTelemetry();

        services.AddMemoryCache();
        services.AddSingleton<IAzureSqlTokenProvider, AzureIdentityAzureSqlTokenProvider>();
        services.Decorate<IAzureSqlTokenProvider, MemoryCacheAzureSqlTokenProvider>();
        services.AddScoped<AzureAdAuthenticationDbConnectionInterceptor>();

        services
            .AddAuthentication(AzureADDefaults.AuthenticationScheme)
            .AddAzureAD(options =>
                {
                    Configuration.Bind("AzureAd", options);
                })
            .AddMicrosoftIdentityWebApp(options =>
            {
                Configuration.Bind("AzureAd", options);
            })
            .EnableTokenAcquisitionToCallDownstreamApi(new string[] { "profile" })
            .AddMicrosoftGraph("https://graph.microsoft.com/v1.0", "profile")
            .AddInMemoryTokenCaches();

        services
            .AddMvc(options =>
            {
                options.Filters.Add(new AuthorizeFilter());
                options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
            })
            .AddRazorPagesOptions(options =>
            {
                options.Conventions.AddPageRoute("/Systems/Index", "");
            }).AddMicrosoftIdentityUI();
        
        ...
    }
}
```

```csharp Startup.cs
// My Razor Page
[AuthorizeForScopes(Scopes = new[] { "user.read" })]
public class IndexModel : PageModel
{
    private readonly GraphServiceClient _graphServiceClient;

    public IndexModel(GraphServiceClient graphClient)
    {
        _graphServiceClient = graphClient;
    }

    public PaginatedList<Domain.Models.System> System { get; set; }

    public async System.Threading.Tasks.Task OnGetAsync(int? pageIndex, string searchString, string currentFilter)
    {
        var response = await _graphServiceClient.Me.Request().GetAsync();
    }
}
```

**Expected behavior**
The code should not throw, and should either successfully invoke the graph api, or redirect to login.microsoft.com in order to prompt the user for their consent for the authorised scopes.

**Actual behavior**
A null reference exception is thrown by PrepareAuthorityInstanceForMsal.

Stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Identity.Web.MergedOptions.PrepareAuthorityInstanceForMsal()
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisitionAuthenticationProvider.AuthenticateRequestAsync(HttpRequestMessage request)
   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
```

**Possible solution**

**Additional context / logs / screenshots**
It is worth noting that when I revert to 1.16.0, I no longer experience this issue. However, when I revert to 1.16.0, the same code instead enters an infinite redirect loop. From what I can see, this is because the ChallengeResult that AuthoriseForScopes should return is no including a `prompt=consent` query parameter in its redirect to login.microsoft.com.

**Comment by thestillheron** [comment]
Digging a little deeper:
![image](https://user-images.githubusercontent.com/4918277/139639433-faa5899d-c50c-41d1-a1e6-91eb32404675.png)

It should be getting set here: https://github.com/AzureAD/microsoft-identity-web/blob/24645e5dcaecb8771e0b6709aafbebd00ccc45f3/src/Microsoft.Identity.Web/MergedOptions.cs#L288

But `confidentialClientApplicationOptions.Instance` is null when the update is run. Looking into why that might be next.

**Comment by thestillheron** [comment]
It doesn't look like any of the mergeOptions are binding. In the debugger I see null for all the values that look to be correctly defined here in my app settings:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug"
    }
  },
  "AzureAd": {
    "ClientId": "<>",
    "Domain": "dummy.net",
    "TenantId": "<>",
    "Scopes": [ "https://graph.microsoft.com/.default" ],
    "ClientSecret": "<>",
    "Instance": "https://login.microsoftonline.com/",
    "CallbackPath": "/signin-oidc"
  },
  "Graph": {
    "BaseUrl": "https://graph.microsoft.com/v1.0",
    "Scopes": "user.read"
  },
  "ApplicationConfig": {
    "ConnectionString": "Data Source=.\\SQLEXPRESS01; Initial Catalog=ADS_Config;User=dbo;Integrated Security=true;"
  }
}
```

**Comment by thestillheron** [comment]
Worth noting at this line it's trying to look for options with the value "AzureAD", which is the AuthenticationScheme I'm using. In my config that section is labeled "AzureAd" (note the different casing). However, changing the config to line up with "AzureAD" did not resolve the issue.

https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/TokenAcquisition.cs#L259

**Comment by thestillheron** [comment]
Note: I noticed 1.19.0 was released a few hours ago. I've retargeted to that, but I still experience the same problem.

**Comment by jmprieur** [comment]
@thestillheron : 

why do you have this code?

```CSharp
 services
            .AddAuthentication(AzureADDefaults.AuthenticationScheme)
            .AddAzureAD(options =>
                {
                    Configuration.Bind("AzureAd", options);
                })
```

It's mixing 2 generation of authentication libraries, which we didn't test. The `AddAzureAD` is being deprecated by the ASP.NET Core team.

I suggest you just replace that code by only:

```CSharp
 services
            .AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
```

**Comment by thestillheron** [comment]
Making that change has resolved the issue.

I did try removing the AddAzureAD call earlier, but experienced a different error. But I hadn't also changed the authentication scheme to `OpenIdConnectDefaults.AuthenticationScheme`.

Thanks very much for your assistance!

**Comment by MattHartz** [comment]
Hi all, I am building a service that authenticates with Auth0 for the web app, but the service itself authenticates with other services using Azure AD. It seems like I have to remove my commented out auth0 code to get this to work based on the previous comments.

Is there something i can do to have these two code sections play nicely?

**Comment by MattHartz** [comment]
@jmprieur

**Comment by jimitndiaye** [comment]
I'm having this exact problem with version 1.22.3 of Microsoft.Identity.Web. Unlike @thestillheron there is no other authentication but Microsoft.Identity.Web. The relevant code is as below:
```
            services.AddAuthentication()
                .AddMicrosoftIdentityWebApp(
                    openIdConnectScheme: OpenIdConnectDefaults.AuthenticationScheme,
                    displayName: "Azure AD B2C",
                    configureMicrosoftIdentityOptions: options =>
                        ConfigureMicrosoftIdentityOptions(
                            options,
                            shellSettings),
                    configureCookieAuthenticationOptions: ConfigureCookieAuthenticationOptions,
                    cookieScheme: null,
                    subscribeToOpenIdConnectMiddlewareDiagnosticsEvents: env.IsDevelopment())
                .EnableTokenAcquisitionToCallDownstreamApi(options =>
                {
                    Configuration.GetSection(PortalAuthenticationConfigSection).Bind(options);
                    options.EnablePiiLogging = env.IsDevelopment();
                })
                .AddDownstreamWebApi(AuthenticationConstants.IdentityApiName,
                    options => { Configuration.GetSection("Portal:Authentication:Api").Bind(options); })
                .AddDistributedTokenCaches();
```
I initially didn't provide a callback to ```EnableTokenAcquisitionToCallDownstreamApi``` but ran into the null reference exception and added that callback to make sure ```Instance``` is being set. To my amazement, even after the call back is executed and the ```Instance``` property is set via configuration as depicted above, I still get a null reference exception - it is being overwritten somehow.

**Comment by oledid** [comment]
After struggling with the PrepareAuthorityInstanceForMsal() NullReferenceException from  for a while after upgrading from an older Microsoft.Identity.Web, I found a way to get it to work with `<PackageReference Include="Microsoft.Identity.Web" Version="1.23.1" />`:

I am using app authentication for azure maps separately from an AzureAd user login (which occupies the "AzureAD" hard coded configuration section) and other configurations.

Simple setup:

```js
// appsettings.json or secrets
{
  "Secrets": {
    "AzureMaps": {
      "Instance": "https://login.microsoftonline.com/",
      "ClientId": "",
      "TenantId": "",
      "ClientSecret": "",
      "CallbackPath": "/myCustomLocalUrlPrefix/azureMaps/signin-oidc",
      "SignedOutCallbackPath ": "/myCustomLocalUrlPrefix/azureMaps/signout-callback-oidc",
      "MapsClientId": "",
      "SubscriptionKey": ""
    },
  }
}
```

```csharp
// Startup.cs, ConfigureServices

var myCustomSchemeName = "AzureMapsScheme";
services.AddMicrosoftIdentityWebApiAuthentication(configuration, configSectionName: "Secrets:AzureMaps", jwtBearerScheme: myCustomSchemeName )
  .EnableTokenAcquisitionToCallDownstreamApi()
  .AddInMemoryTokenCaches();

// the important bit here is that I am setting the authenticationScheme parameter ("jwtBearerScheme"), to my custom scheme name
```

```csharp
// Controller
private readonly ITokenAcquisition tokenAcquisition;
private readonly IConfiguration configuration;

public AccessController(ITokenAcquisition tokenAcquisition, IConfiguration configuration)
{
	this.tokenAcquisition = tokenAcquisition;
	this.configuration = configuration;
}

public async Task<IActionResult> AzureMapsToken()
{
        var myCustomSchemeName = "AzureMapsScheme"; // same as in startup, make it a shared constant somewhere

	var accessToken = await tokenAcquisition.GetAccessTokenForAppAsync("https://atlas.microsoft.com/.default", myCustomSchemeName, configuration["Secrets:AzureMaps:TenantId"], new TokenAcquisitionOptions());
	return Content(accessToken, "text/plain");
}
```

---

### Conclusion:
Value supplied to parameter name "jwtBearerScheme" in AddMicrosoftIdentityWebApiAuthentication() must match value supplied to parameter "authenticationScheme" in tokenAcquisition.GetAccessTokenForAppAsync(), it's easy to miss because it is called "jwtBearerScheme". I would suggest renaming it "authenticationScheme"
