### ISSUE TITLE
[Documentation]  UseInMemoryTokenCaches vs AddInMemoryTokenCaches

### ISSUE THREAD

**Issue by mikeblakeuk** [AzureAD/microsoft-identity-web#1515]
### Documentation related to component
https://github.com/AzureAD/microsoft-identity-web/wiki/asp-net

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in the example
- [ ] needs an example

### Description of the issue
Please confirm .UseInMemoryTokenCaches  vs .AddInMemoryTokenCaches

**Comment by jennyf19** [comment]
I have updated the documentation, we only have .AddInMemoryTokenCache(). Thanks for opening the issue.
