### ISSUE TITLE
[Question] How to extend WWW-Authenticate header values?

### ISSUE THREAD

**Issue by superman-lopez** [AzureAD/microsoft-identity-web#1516]
I am trying to extend the information in the response header when the authentication is challenged (the [reason](https://stackoverflow.com/q/64602313/10340388) for this is that I want MS Excel to connect to my Protected Web API).  After trying a few things I [got closest](https://stackoverflow.com/a/69841451/10340388) by customising the `JwtBearerOptions` configuration (see below).  However this code seems to be run before the middleware handler (or Kestrel?) creates the `WWW-Authenticate` key-value pair.  As a result I can add an _additional_ `WWW-Authenticate` key-value pair, but not overwrite or remove the default value.  In my configuration both key-value pairs will start the value with 'Bearer' and I am concerned that this might give unexpected results.

I don't want to write and maintain my own handler for the OnChallenge event.  What hook or approach in configuration can I use to include the additional information for `WWW-Authenticate` in the response header and overwrite or remove the default key-value pair?

```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(Configuration)

services.Configure<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme, options =>
{
    var existingOnChallengeHandler = options.Events.OnChallenge;
    options.Events.OnChallenge = async context =>
    {
        await existingOnChallengeHandler(context);

        string headerInfo = context.Options.Challenge;
        headerInfo += " resource=\"https://management.azure.com/\"";
        context.Response.Headers.Append(HeaderNames.WWWAuthenticate, headerInfo);
    };
});
```

The resulting response header shows:
   | key | value|
|---|---|
|WWW-Authenticate | Bearer resource=https://management.azure.com/|
|WWW-Authenticate | Bearer|

My project is on Asp.Net Core 3.1, I am using Microsoft.Identity.Web Version 1.19.0 to protect my Web API.

**Comment by jmprieur** [comment]
@tratcher, would you know?

**Comment by superman-lopez** [comment]
Thanks, I will review this!
