### ISSUE TITLE
[Bug] Setting options on the in-memory cache leads to a large perf hit  (>100X) in multi-tenant apps

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-identity-web#1527]
When using the in-memory cache without options, the TokenCache package relies on MSAL's internal cache, which does not use JSON serialization. When setting eviction options however, it switches to use MemoryCache + json serialization. The latency of the cache drops significantly. See table below for app cache.

|                    Method | Tenants | TokensPerTenant |    Mean |    Error |   StdDev |  Median |     Min |     Max |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|-------------------------- |-------- |---------------- |--------:|---------:|---------:|--------:|--------:|--------:|-----------:|----------:|----------:|----------:|
| AcquireTokenForClient_Old |       1 |           10000 | 3.690s  | 0.0459s  | 0.0407s  | 3.677s  | 3.632s  | 3.778s  | 11000.0000 | 8000.0000 | 2000.0000 |     60 MB |
| AcquireTokenForClient_New |       1 |           10000 | 4.062ms | 0.3862ms |  1.139ms | 3.899ms | 2.393ms | 6.831ms |          - |         - |         - |      1 MB |
| AcquireTokenForClient_Old |       1 |          100000 |    14m  |        - |        - |       - |       - |       - |          - |         - |         - |         - |
| AcquireTokenForClient_New |       1 |          100000 | 54.42ms |  1.061ms |  0.940ms | 54.03ms | 53.52ms | 56.77ms |  1000.0000 | 1000.0000 |         - |      9 MB |
| AcquireTokenForClient_Old |     100 |           10000 | 4.856s  | 0.0560s  | 0.0497s  | 4.864s  | 4.752s  | 4.921s  | 12000.0000 | 9000.0000 | 3000.0000 |     60 MB |
| AcquireTokenForClient_New |     100 |           10000 | 3.385ms | 0.1073ms | 0.3096ms | 3.282ms | 2.725ms | 4.222ms |          - |         - |         - |      1 MB |
| AcquireTokenForClient_Old |    1000 |            1000 | 51.40ms |  0.958ms |  0.896ms | 51.59ms | 48.83ms | 52.54ms |  1000.0000 | 1000.0000 |         - |      6 MB |
| AcquireTokenForClient_New |    1000 |            1000 | 514.8μs |  25.47μs |  70.15μs | 494.1μs | 416.7μs | 735.3μs |          - |         - |         - |    107 KB |
| AcquireTokenForClient_Old |   10000 |             100 | 1.707ms | 0.0458ms | 0.1292ms | 1.725ms | 1.475ms | 2.011ms |          - |         - |         - |    644 KB |
| AcquireTokenForClient_New |   10000 |             100 | 191.0μs |  10.03μs |  25.70μs | 187.2μs | 164.2μs | 329.2μs |          - |         - |         - |     30 KB |

**Comment by jennyf19** [comment]
@bgavrilMS This is a .NET Core issue. Not an Id.Web issue. When there is eviction, there is CPU consumed to perform the eviction and there is serialization. How is this issue actionable in Id.Web?

**Comment by bgavrilMS** [comment]
No, I'm not talking about the eviction perf hit, that's negligible / expected. I am talking about 2 things: 

1. MSAL's internal cache does not have eviction policies. So TokenCache package has to use MemoryCache instead of MSAL's internal cache. This implies JSON which leads to the perf hit above. As such, the API behaves in an unexpected way.

2. On .NET classic, the TokenCache package does not even use MSAL's internal cache, as it does not have access to the application builder. We'll need to do some work in MSAL first to expose the settings at the ITokenCache level. PR https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2980

**Comment by jmprieur** [comment]
@bgavrilMS : I'm confused about why this issue is on Id.Web:
1. Is determined by MSAL.NET 
2. IdWeb will be updated as soon as MSAL.NET ships (as usual)?

**Comment by jmprieur** [comment]
@bgavrilMS : do we want `app.AddInMemoryTokenCache()` to set the static cache both for the app token cache and app token cache? (I would think so)

**Comment by bgavrilMS** [comment]
Hi @jmprieur. 

I believe this is a bug, not a feature request. From an app developer perspective, the history or interaction of MSAL / TokenCache package is not relevant. What is relevant is the API surface:

```csharp

// If I use just this, I get latency of 1-3 ms
app.AddInMemoryCache();


// If I add this simple option, I get latencies of ~10-30ms
 services.Configure<MemoryCacheOptions>(options =>
      {
          options.SizeLimit = 5000000; // in bytes (5 Mb)
      });
```

For an app developer, this is a surprise, as a simple eviction option should not be so slow. We know the root case (json serialization).

**Comment by jmprieur** [comment]
@bgavrilMS how is this actionable in the Microsoft.Identity.Web library?
can Microsoft.Identity.Web use reflection to access the MSAL cache directly?

**Comment by bgavrilMS** [comment]
I think that `AddInMemoryCache` should at least have an API comment stating this perf problem as a known issue. 

If it's easier to deal with GH issues, let's move the TokenCache project to MSAL repo. This will better align it with the releases of MSAL and should not have an impact of Id.Web, as long as we agree to maintain the existing version numbers.

**Comment by jmprieur** [comment]
Ok. I get it now it was a documentation issue. Why didn't you clearly express it in the first place.

Let's take the movement of the NuGet packages from one repo to another later, part of my bigger vision document consolidating feature between Wilson, MSAL, SAL, MISE, Id.Web (to come in the future), so that features are where they should be, not where they were developed historically.
I'd want to do it in a consistent way, part of a strategy to simplify the messaging for customers and partners, not tactically.

**Comment by bgavrilMS** [comment]
@jmprieur - MSAL 4.38 will not have a static cache with eviction. It will just allow non-ASP.NET Core apps to configure the cache. The eviction issue remains.

**Comment by jmprieur** [comment]
@bgavrilMS : i understand what you meant now. We'll update the doc

**Comment by jmprieur** [comment]
Fixed by https://github.com/MicrosoftDocs/azure-docs/pull/83982
