### ISSUE TITLE
[Bug] TenantId is not honor in .WithAppOnly() extension

### ISSUE THREAD

**Issue by xubinzheng** [AzureAD/microsoft-identity-web#1536]
**Which version of Microsoft Identity Web are you using?**
**Microsoft Identity Web 1.20.0**

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [x] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment.

**Repro**
Following this doc (https://github.com/AzureAD/microsoft-identity-web/wiki/calling-graph#specify-a-tenant) to call MS Graph with a specified tenantId by using `.WithAppOnly(false, "41294ac5-d6e5-4b36-9f8d-c9d69145abed")`

```
                var servicePrincipalObject = (
                    await graphServiceClient
                        .ServicePrincipals
                        .Request()
                        .WithAppOnly(false, "41294ac5-d6e5-4b36-9f8d-c9d69145abed")
                        .Filter($"AppId eq '{appId}'").GetAsync()).SingleOrDefault();
                return servicePrincipalObject;
```
However, the actual access token still points to my default tenant.
The token request was sent to `POST /f686d426-8d16-42db-81b7-ab578e110ccd/oauth2/v2.0/token HTTP/1.1` instead of the tenantId I provided "41294ac5-d6e5-4b36-9f8d-c9d69145abed"

**Expected behavior**
Access token should have my specified tenantId in there, and calling MS Graph with that tenantId.

**Actual behavior**
Access token points to my default tenant.

**Additional context / logs / screenshots / link to code**
TenantId has been passed into the `AuthenticationProviderOption`, but some how the library didn't use it when doing the token acquisition. 
<img width="1809" alt="image" src="https://user-images.githubusercontent.com/9353989/142514554-e98fe730-140b-4cc4-934d-4d633cecc73f.png">

EVO token request
<img width="560" alt="image" src="https://user-images.githubusercontent.com/9353989/142514830-6ab14d78-1331-4351-b8c6-13f436310df9.png">

**Comment by jennyf19** [comment]
Included in [1.21.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.21.0)
