### ISSUE TITLE
[Compliance] Add the BOM generation to the release builds

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1546]
**Is your feature request related to a problem? Please describe.**
Compliance: add the BOM generation to the release builds

**Describe the solution you'd like**
See [ADA SBOM generator](https://www.1eswiki.com/wiki/ADO_sbom_Generator#Classic_Pipelines)

**Comment by jennyf19** [comment]
Included in the [1.22.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.22.00
