### ISSUE TITLE
Weird "Unable to unprotect the message.State" error

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#1555]
My Web app uses Microsoft.Identity.Web and Microsoft.Identity.Web.UI (1.16.1) to authentication the users. The Web apps are behind BIG-IP for load-balancing and redundancy.

I recently run into an authentication error (500 on the callback URL) on a particular workstation with the browser hitting the load balancer. The Fiddler trace (attached) shows that the .AspNetCore.Correlation and .AspNetCore.OpenIdConnect.Nounce cookies are not included in the request message sent to the callback URL (signin-oidc). The Web app reports "Unable to unprotect the message.State" error as below:   

```
System.Exception: An error was encountered while handling the remote login.
   at async Task<bool> Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
   at async Task Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at async Task CSG.Configuration.AzureSsoService.MiddleWare.RequestResponseLogger.TraceResponseMessage(HttpContext context) in d:/Jenkins/workspace/22.1.0.0.0-ACPx-Configuration-DSM/Src/WorkerService/AzureSsoService/MiddleWare/RequestResponseLogger.cs:line 62
   at async Task CSG.Configuration.AzureSsoService.MiddleWare.RequestResponseLogger.TraceResponseMessage(HttpContext context) in d:/Jenkins/workspace/22.1.0.0.0-ACPx-Configuration-DSM/Src/WorkerService/AzureSsoService/MiddleWare/RequestResponseLogger.cs:line 76
   at async Task CSG.Configuration.AzureSsoService.MiddleWare.RequestResponseLogger.Invoke(HttpContext context) in d:/Jenkins/workspace/22.1.0.0.0-ACPx-Configuration-DSM/Src/WorkerService/AzureSsoService/MiddleWare/RequestResponseLogger.cs:line 26
   at async Task Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)+Awaited(?) ---> System.Exception: Unable to unprotect the message.State.

   --- End of inner exception stack trace ---
```

Some other facts:

1. On the workstation that has the above error, the authentication goes through if the browser bypasses the load balancer and hits the Web app host directly.
2. On other hosts the authentication is successful using the same account and going through the load balancer.

I am puzzled how the load balancer and the particular workstation can interact to prevent the .AspNet.Core.* cookies from being included in the signin-oidc request message.

[AzureSsoTrace.saz.gz](https://github.com/AzureAD/microsoft-identity-web/files/7672168/AzureSsoTrace.saz.gz)

**Comment by jmprieur** [comment]
Hello @WenningQiu 
Did you read this article?
https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers#issue-with-scaled-out-web-apps-in-app-services

**Comment by WenningQiu** [comment]
Thanks @jmprieur, I just read it. 

We addressed the server affinity issue by turning on BIG-IP persistent connections so all HTTP messages for one authentication attempt are directed to the same server. I think the "Unable to unprotect the message.State" error I am getting is probably related to .AspNetCore.Correlation and .AspNetCore.OpenIdConnect.Nounce cookies not being included in the HTTP request in the signin-oidc request message, but cannot think of a reason why.

**Comment by jmprieur** [comment]
@tratcher do you have an idea?

**Comment by Tratcher** [comment]
Can you share a Fiddler trace of the login flow? Cookies wouldn't be included in subsequent requests if their attributes were wrong on the first response.

**Comment by WenningQiu** [comment]
@Tratcher The fiddler trace was included in the original post.

**Comment by Tratcher** [comment]
So it was 😁.

I see the first request is HTTP and the second is HTTPS. Does it work if the first is changed to HTTPS?

Everything else in the trace looks fine.

**Comment by WenningQiu** [comment]
@Tratcher I think that's the root cause. I was messing with the browser's cache and probably had lost HSTS cache and then accidently used HTTP instead of HTTPs...

Thanks a lot!

**Comment by jmprieur** [comment]
Thanks @Tratcher

**Comment by MikeMcWilliams** [comment]
I am getting the same on an AWS Cluster -- first time encountering this on a new site we're trying to publish.  We have a simple OIDC client that works perfectly locally on a dev box.

```
`System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Unable to unprotect the message.State.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
````
Any help is greatly appreciated.

**Comment by michiproep** [comment]
I'm currently facing the same issue. This is usually related to DataProtection while running multiple replicas of an app. I'll keep you updated...

**Comment by mahdibx** [comment]
Any news on this? I'm running a test server for some integration tests, and when trying to post to signin-oidc I have this same error. 

```
    System.Exception : An error was encountered while handling the remote login.
  ----> System.Exception : Unable to unprotect the message.State.

  Stack Trace: 
RemoteAuthenticationHandler`1.HandleRequestAsync()
AuthenticationMiddleware.Invoke(HttpContext context)
<<SendAsync>g__RunRequestAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
```

**Comment by michiproep** [comment]
Yes, actually there are news.
You need to plug in a "distributed cache/store" like Database, Redis or FileShare.

services.AddDataProtection()
//    .PersistKeysToDbContext<Infrastructure.DataProtectionDbContext>();
// OR
.PersistKeysToStackExchangeRedis

**Comment by deadlydog** [comment]
I was able to work around this issue by using cookie affinity on my ingress instead of a distributed cache / data store. Explanation at https://stackoverflow.com/a/73367639/602585.

**Comment by Simkiw** [comment]
> Yes, actually there are news. You need to plug in a "distributed cache/store" like Database, Redis or FileShare. `services.AddDataProtection() // .PersistKeysToDbContext<Infrastructure.DataProtectionDbContext>(); // OR .PersistKeysToStackExchangeRedis`

Hi @michiproep and @Tratcher 

Could you elaborate a little bit?  
Should I add it in identity server startup or my client web app startup?
And if I may ask, what happens behind the scenes that solves this issue?  (if it's not complex to summarize, because I'm reading [the asp doc on it](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/?view=aspnetcore-6.0) and it's not an easy topic.

I'm still looking for the information because it doesn't seem to be trivial and I haven't seen a proper solution yet.  
That's too bad it's not included in identity server docs (it's easy to say it's related to data protection).

I'm not using kubernetes, or azure. Just my machine: a web app, identity server acting as a gateway to other IdPs (cIAM for example)

my client startup:
```
services.AddAuthentication(options =>
                                       {
                                           options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                                           options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                                       })
                    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme)
                    .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
                                      {
                                          // options.MetadataAddress = Configuration["CiamIdp:DiscoveryDoc"];
                                          options.Authority    = Configuration["Is4Idp:Authority"];
                                          options.ClientId     = Configuration["Is4Idp:ClientId"];
                                          options.ClientSecret = Configuration["Is4Idp:ClientSecret"];

                                          options.ResponseType = "code";
                                          options.UsePkce      = false;
```

As for identity server:
```
services.AddAuthentication()
                    .AddOpenIdConnect("oidc", "cIAM", options =>
                                                      {
                                                          options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                                                          options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                                                          options.SaveTokens = true;
                                                          
                                                          options.MetadataAddress = Configuration["CiamIdp:DiscoveryDoc"];
                                                          options.ClientId     = Configuration["CiamIdp:ClientId"];
                                                          options.ClientSecret = Configuration["CiamIdp:ClientSecret"];
                                                          options.ResponseType = "code";
                                                          options.UsePkce      = false;
                                                          options.SignedOutRedirectUri =  Configuration["CiamIdp:SignedOutRedirectUri"];
                                                          options.Events = new OpenIdConnectEvents
                                                          {
                                                              OnRedirectToIdentityProvider = context =>
                                                              {
                                                                  context.ProtocolMessage.SetParameter("app", "IandT");
                                                                  return Task.FromResult(0);
                                                              }
                                                          };
                                                      });
```
If I use the same IdP config directly on my client (without identity server), it works fine.  
I would appreciate your helps guys, thank you.

**Comment by Tratcher** [comment]
Identity server and a web app shouldn't need a shared data protection configuration, they should be able to function independently. You need a shred data protection setup when you have multiple instances of an application running that need to be able to decrypt eachothers cookies, tokens, etc.. Do you have multiple instances of the web app?

**Comment by sxseba1** [comment]
I receiving the same issue for multiple pods running in a K8 cluster. Looks like this will be an issue for any deployments in a kubernetes or load balanced deployment.
Is there a workaround for such scenarios?

**Comment by michiproep** [comment]
this is not an issue of this library. Data Protection in general depends on shared secrets. if you find a secure workaround you should get nominated for the Nobel prize 😜

**Comment by sxseba1** [comment]
@deadlydog ,
Thanks for the pointer to using cookie affinity on ingress / load balancer. I was able to fix it with the same solution.

@michiproep , 
Well, this is the first time I am implementing in dotnet core web app that uses oidc.
I didn't have to worry about these in Angular SPA implementations as it will be the same browser client and do not have to worry about server load balancing.

**Comment by michiproep** [comment]
well, that's true then. but most companies / people have to use server side / bff solutions for security policies. remember : whenever you can use a backend, use it. no token in the Frontend is always the best approach

**Comment by OliverRC** [comment]
In a clustered deployment environment, the ASPNetCore apps must share a data protection key so that traffic can be load-balanced across them.

It works locally because there is no horizontal scale, so all requests arrive back at the app that created them.
When configuring the DataProtection provider e.g `services.AddDataProtection()` you can extend additional provide where the keys can be persisted so they can be shared across running instances. 

There are several ways to persist the keys, AzureKeyVault, AWS Systems Manager etc. You can pick which works for your environment
