### ISSUE TITLE
[Bug] Cannot call the same downstream API using different authority types for client and user calls

### ISSUE THREAD

**Issue by mevans-medpace** [AzureAD/microsoft-identity-web#1560]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.21.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [X] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment.

**Repro**

```csharp
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                {
                    configuration.Bind("AzureAdB2C", options);
                    options.SaveTokens = true;
                    options.RefreshOnIssuerKeyNotFound = true;
                    options.UseTokenLifetime = true;
                }, openIdConnectScheme: OpenIdConnectDefaults.AuthenticationScheme)
                .EnableTokenAcquisitionToCallDownstreamApi(configuration.GetValue<string>("DownstreamB2CApi:Scopes")?.Split(' '))
                .AddDownstreamWebApi("DownstreamB2CApi", configuration.GetSection("DownstreamB2CApi"))
                .AddInMemoryTokenCaches();
            
            services.AddAuthentication()
                .AddMicrosoftIdentityWebApp(configuration.GetSection("AzureAd"), "AAD", "cookiesAAD")
                .EnableTokenAcquisitionToCallDownstreamApi(configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' '))
                .AddDownstreamWebApi("DownstreamApi", configuration.GetSection("DownstreamApi"))
                .AddInMemoryTokenCaches();
```

```csharp
    public static class DownstreamWebApiExtensions
    {
        public static async Task<HttpResponseMessage> CallWebApiForCorePortalAppAsync(this IDownstreamWebApi downstreamWebApi, string baseUrl, string relativePath, HttpMethod httpMethod, string content = null)
        {
            return await downstreamWebApi.CallWebApiForAppAsync(
                serviceName: "DownstreamApi",
                authenticationScheme: "AAD",
                options =>
                {
                    options.BaseUrl = baseUrl;
                    options.RelativePath = relativePath;
                    options.HttpMethod = httpMethod;
                },
                content: !string.IsNullOrEmpty(content) ? new StringContent(content, Encoding.UTF8, "application/json") : null);
        }

        public static async Task<HttpResponseMessage> CallWebApiForCorePortalUserAsync(this IDownstreamWebApi downstreamWebApi, string baseUrl, string relativePath, ClaimsPrincipal claimsPrincipal, HttpMethod httpMethod, string content = null)
        {
            return await downstreamWebApi.CallWebApiForUserAsync(
                serviceName: "DownstreamB2CApi",
                authenticationScheme: OpenIdConnectDefaults.AuthenticationScheme,
                options =>
                {
                    options.BaseUrl = baseUrl;
                    options.RelativePath = relativePath;
                    options.HttpMethod = httpMethod;
                    options.AuthenticationScheme = OpenIdConnectDefaults.AuthenticationScheme;
                },
                user: claimsPrincipal,
                content: !string.IsNullOrEmpty(content) ? new StringContent(content, Encoding.UTF8, "application/json") : null);
        }
    }

```

**Expected behavior**
I expect to be able to call a downstream API using different authentication schemes that have different authority types. Because B2C does not support client_credentials flow, we need to use an AAD authority to make client-based calls, and B2C to make user-based calls.

**Actual behavior**
In the code above, calling the extension method CallWebApiForCorePortalAppAsync works - we are able to call the API using downstreamWebApi.CallWebApiForAppAsync. However, the extension method CallWebApiForCorePortalAppAsync does not work. downstreamWebApi.CallWebApiForUserAsync throws an exception of type Microsoft.Identity.Client.MsalClientException with the message:

`A authority of type Aad was used at the application and of type B2C at the request level. Please use the same authority type between the two.`

**Additional context / logs / screenshots / link to code**
We are following the instructions here: [Multiple Authentication Schemes](https://github.com/AzureAD/microsoft-identity-web/wiki/Multiple-Authentication-Schemes) to allow our app to use AAD and B2C as different authorities. The example there shows using the AAD scheme to call a Microsoft Graph API and B2C to call a different downstream API.

Our use case is that we need to make some calls to the same API using client-based authentication and some using user-based authentication. We are adding a different named service to each authentication scheme in each call to `AddDownstreamWebApi` and specifying the configuration section.

However when we inject the IDownstreamWebApi it seems like it's injecting the first scheme's DownstreamApi. Then when we change the authentication scheme in the call to CallWebApiForUserAsync there is a mismatch in the authority type. Is there a way we can retrieve the DownstreamWebApi associated with the correct scheme?

The relevant portion of the appsettings.json looks like this:

```json
  "AzureAdB2C": {
    "Instance": "https://<our-tenant>.b2clogin.com",
    "Domain": "<our-tenant>.onmicrosoft.com",
    "TenantId": "<our-b2c-tenant-id>",
    "ClientId": "<our-b2c-client-id>",
    "ClientSecret": "<our-b2c-client-secret>",
    "SignedOutCallbackPath": "/signout/B2C_1_Sign_Up_And_Sign_In_Default",
    "SignUpSignInPolicyId": "B2C_1_Sign_Up_And_Sign_In_Default",
    "CallbackPath": "/signin-oidc"
  },
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "<our-tenant>.onmicrosoft.com",
    "TenantId": "<our-aad-tenant>",
    "ClientId": "<our-aad-client-id>",
    "ClientSecret": "<our-aad-client-secret>",
    "CallbackPath": "/signin-oidc-aad"
  },
  "DownstreamApi": {
    "BaseUrl": "http://localhost:5010",
    "Scopes": "https://<our-tenant>.onmicrosoft.com/<api-name>/.default"
  },
  "DownstreamB2CApi": {
    "BaseUrl": "http://localhost:5010",
    "Scopes": "https://<our-tenant>.onmicrosoft.com/<api-name>/.default"
  }

```

**Comment by jmprieur** [comment]
Thanks for raising this issue, @mevans-medpace
this is a recent regression introduced by MSAL.NET when it started preventing to override the environment.
cc: @bgavrilMS

**Comment by jmprieur** [comment]
@jennyf19 : to work around this issue, we could create one confidential client application by authentication scheme, and keep them in a dictionary in the TokenAcquisition.

**Comment by jmprieur** [comment]
Fixed in rel/v2 with the IDownstreamRestApi
