### ISSUE TITLE
[Documentation] Switching tenant in runtime

### ISSUE THREAD

**Issue by ferronsw** [AzureAD/microsoft-identity-web#1563]
### Documentation related to component
OpenId

### Please check all that apply

- [ ] typo
- [X] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
Hello,

I've a multi tenant app that is accessible trough multiple domain names. The user view is based on their tenantId.
The problem is that I want to be able to sign in Guest users from a specific tenants. This doesn't work trough the `organizations` endpoint I was using to obtain a token. I tested the guest user scenario by changing the appsettings `AzureAd:TenantId` to the tenantId of the tenant with guest users. With this is was able to sign in with guest users from that specific tenant. 

My question is how can I change the tenantId value in runtime for a specific request? I want to look at the domain a user is coming from and depending on that value I want to change the tenantId to sign in guest users if needed. I tried doing this trough the `OnRedirectToIdentityProvider` OpenId event, but that doesn't seem to work.

**Comment by jmprieur** [comment]
@ferronsw : do you mean when you call a downstream API?
Did you see:
- https://github.com/AzureAD/microsoft-identity-web/wiki/calling-graph
- the customization of IDownstreamWebApi and ITokenAcquisition methods?

**Comment by ferronsw** [comment]
@jmprieur no when the user signs in to the MVC web app.

**Comment by harris-boyce** [comment]
@ferronsw like the Azure Portal?  I'm guessing this would require some combination of sign-out/clear current `id_token`, redirect specifying a desired target tenant for authentication, and signing-in against the selected tenant.

Would be interested in this functionality as well...

**Comment by ferronsw** [comment]
@harris-boyce no not like the Azure portal. Our application is not one where you want to switch between Azure tenants with the same account. It's just to sign in with your guest account to the correct tenant. I fixed it like this:

```
  options.Events.OnRedirectToIdentityProvider = context => 
                {
                    //Redirect to customer tenant endpoint if guest access is enabled. Otherwise guest users won't be able to sign in.
                    var _context = context.HttpContext.RequestServices.GetRequiredService<OLW_Context>();
                    var domain = _context.SignInDomains.Include(x => x.Customer).FirstOrDefault(x => x.Domain == context.Request.Host.ToString().ToLower());
                    if (domain != null && domain.Customer.AllowGuests) {
                        context.ProtocolMessage.IssuerAddress = context.ProtocolMessage.IssuerAddress.Replace("organizations", domain.Customer.TenantId);
                    }
                   
                    return Task.CompletedTask; 
                };
```
