### ISSUE TITLE
[Bug] Eviction is not set on L2 token cache nodes 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-identity-web#1566]
**Which version of Microsoft Identity Web are you using?**
1.21.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [x] Distributed caches
* Other (please describe)

L2 nodes should be evicted when the underlying tokens are known to expire. MSAL offers this information and IdWeb uses it for L1 eviction, but not for L2. MSAL will offer this information for **client_credential** and **OBO**. 

To fix, I propose: 

- if app developer has set L2 eviction themselves via the options, use it
- if they have not, use MSAL suggested eviction, where available.

**Comment by bgavrilMS** [comment]
PS: I created the "token acquisition" label for bugs that should be handled by the MSAL team. Token cache bugs fall into this category.

**Comment by jennyf19** [comment]
Included in the [1.22.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.22.00
