### ISSUE TITLE
[Bug] unclear support for Net Framework, code excluded from compile

### ISSUE THREAD

**Issue by willportnoy** [AzureAD/microsoft-identity-web#1577]
Most of the entry points (e.g. AddMicrosoftIdentityWebAppAuthentication) seem to be excluded from the Net Framework compilation of this library:

https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj#L112

Is this library usable within Net Framework?

It seems to be a NuGet target framework:

https://www.nuget.org/packages/Microsoft.Identity.Web/1.21.1

and issues imply "yes":

https://github.com/AzureAD/microsoft-identity-web/issues/1086

**Comment by jmprieur** [comment]
@willportnoy : Microsoft.Identity.Web has limited support for .NET Framework as explained in: [Minimal support for .NET FW Classic](https://github.com/AzureAD/microsoft-identity-web/wiki/asp-net)

We have a goal of providing the full experience for .NET framework, but, to be honest, this is not the highest priority, given ASP.NET FW is in maintenance mode (wheareas a lot of innovation happens in ASP.NET for .NET Core / .NET 5.0, .NET 6.0, .NET 7.0.

Where would you apply AddMicrosoftIdentityWebAppAuthentication in an ASP.NET application? On the app builder?

**Comment by willportnoy** [comment]
@jmprieur I'm using ASP.NET Core with Net Framework.

ASP.Net Core (web framework) is packaged as Net Standard (library format) and can be used in Net Framework (runtime environment).

Moving our runtime environment from Net Framework to Net Core requires a substantial effort e.g. all library dependencies have to be available as netstandard or netcore.

**Comment by jmprieur** [comment]
@willportnoy do you have an example of code that I could see?
It's pretty old ... and I don't think dotnet new, or Visual Studio create these projects any longer.

**Comment by willportnoy** [comment]
I followed up offline, to share source code of an ASP.NET Core web app running on Net Framework runtime.

**Comment by celluj34** [comment]
What was the resolution on this? I am running into this right now and would _really_ like to be able to use `AddMicrosoftIdentityWebApi`.
