### ISSUE TITLE
[Bug] When used with MISE, client certificates are not taken into account when calling downstream APIs in controllers

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1583]
**Which version of Microsoft Identity Web are you using?**
1.21.1

**Where is the issue?**
* Web API
    * [x ] Protected web APIs call downstream web APIs

Integrated with MISE
 
**Repro**
See Mise webApiCallGraph sample

**Expected behavior**
Client certificates are taken into account

**Actual behavior**
Neither cert or client secret

**Additional context / logs / screenshots / link to code**
The internal method EnableTokenAcquisition initializes the CcaOptions from the delegate, but not the MicrosoftIdentityOptions. However, the client certs are in MicrosoftIdentityOptions, not CcaOptions

The fix is easy. just bind the configuration with the mergeOptions (which have all the members of MicrosoftIdentityOptions)

**Comment by jmprieur** [comment]
As we are here, let's make sure that the configuration is an `IConfigurationSection` instead of an `IConfiguration`

**Comment by jennyf19** [comment]
Included in the [1.22.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.22.00
