### ISSUE TITLE
[Documentation] Difference between .AddInMemoryTokenCaches() and .AddDistributedMemoryCaches()

### ISSUE THREAD

**Issue by Fresher900** [AzureAD/microsoft-identity-web#1594]
I am working on a .net 6 API project which uses OBO flow to call Graph API and get the user profile.

In the development I am using .AddInMemoryTokenCaches(), which works fine.
I read in production Distributed Token Cache is better.

I can see that for distributed token cache as well there is a memory saving option.

So what is the difference between .AddInMemoryTokenCaches() and .AddDistributedMemoryCaches()?
Is there any performance and memory advantage?
My API has high traffic in that case would .AddDistributedMemoryCaches() be ok? 

Would there be a need to clear the cache in the code? or will it be automatically cleared?

![image](https://user-images.githubusercontent.com/81688354/149372635-01dcd26d-02e5-41f8-b673-e501fcfbb272.png)

**Comment by bgavrilMS** [comment]
In memory caches are discussed here: https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization#inmemory-vs-distributedmemory-cache-options. They are not persistent.

In production a combination of L1 (memory) and persistent token cache - like Redis - (L2) is recommended.

**Comment by newbiedev123** [comment]
@bgavrilMS , thanks for the link. The document reads,

![image](https://user-images.githubusercontent.com/81688354/149387882-41f86855-eaa2-4c32-824a-494b042b8ffd.png)

Doesn't that mean the Distributed in memory cache is persistent?

Is there any documentation explaining the L1+L2 combination? Not sure how to approach it.

Is there any performance benefit in using the combination?

I hope Azure SQL can be used instead of Redis?

We could have around 1000 simultaneous users, would Distributed memory cache work fine in that kind of scenario?Or is L1+L2 the only best approach.

The only concern I have is if we store the cache in our sql we will have to maintain it. The Distributed memory cache seem to be a simpler option.

Thanks

**Comment by luismanez** [comment]
That paragraph maybe is not very well explained.

The Distributed Cache is just an abstraction (using __IDistributedCache__ interface). Using Distributed cache, you can inject later the store you want to use. Asp.net supports currently:
  - Distributed memory cache: this one is an in memory cache, likely works the same that when you do _AddInMemoryCache_
  - SQL Server: yeah, you can use SQL Server with Ditributed memory cache (https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-5.0#distributed-sql-server-cache-1)
  - Redis
  - NCache
  - and basically, even if you want to create your own implementation of the _IDistributedCache_ interface an use any other store (mysql, CosmosDb, filesystem ... don´t do it XD

So, for your API, use Redis or SQL Server (I usually use Redis, as is more performant)

If you use SQL or Redis, you don´t have to maintain anything, the library will update the tokens in there when need it (not sure if I´m understanding what you mean by "maintain it"

There´s an example on how to use DistributedCache and Redis here: https://github.com/AzureAD/microsoft-identity-web/blob/26f1a1514c799f50a0584e70bc471a04056ab9b1/tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs

**Comment by luismanez** [comment]
@bgavrilMS I think there´s an issue in the _token-cache-serialization_ wiki page. When saying:

> By using the DistributedMemory cache, you get the benefits of a more performant L1/L1 cache. Note that when using the DistributedMemory cache from Microsoft Identity Web, the memory cache (L1) has a default limit of 500 MB, which can also be configured with the MsalDistributedTokenCacheAdapterOptions.

I think it should say __more performant L1/L2 cache__ (as it´s pointing to the _L1-Cache-in-Distributed-(L2)-Token-Cache_ wiki page.

I´ve tried to fork the wiki repo to make a PR, but seems not possible.

Thanks!

**Comment by bgavrilMS** [comment]
@luismanez - thanks for the clarifications and pointing out the doc issues, I'll get them fixed. Looks like contributing to the official docs is not an easy process. 

Indeed the "DistributedMemoryCache" is a bit of a contradiction. It's just a memory cache which implements `IDistributedCache`. It's there to provide a default implementation for `IDistributedCache`. It's not distributed and it's not persistent :).

Let me try to clarify the guidance. 

## The goals of token caching 

1. Minimizes calls to AAD. If you call AAD too often, with similar requests, it'll throttle you 
2. In user flows like authorization_code, it avoids prompting the user to re-login. You can measure "auth success" by the number of times the user is prompted. Ideally it should be 1 prompt per device (browser) per user. Of course, if the security stance changes (e.g. password change, MFA added), there will be a re-prompt.

## Guidance for user authentication

- Do not rely on memory caching only. A token entry for 1 user (access token, id token etc.) is about 7KB in size. You web app / web api will run out of memory. Also, if the machine or if the web server is restarted, the memory cache is wiped. Use an implementation of `IDistributedCache` other than `DistributedMemoryCache` in production.
- The token cache package enables an L1 / L2 implementation by default. The L1 is `MemoryCache` and the L2 is IDistributedCache, for which you should provide an implementation.
- Make sure to set some eviction policies on L1 (e.g. max size) and L2 (e.g. sliding expiration). The token cache package does not set limits for you.
- If your system is distributed (e.g. multiple servers), but there is no guarantee that a user hits the machine (see `sticky sessions` or `session affinity`, then it's better to disable L1 caching. This avoids the problem where the user needs a more powerful set of tokens (e.g. user needs MFA) and the L1 caches get de-syncronized. The downside is perf, as an L2 access is (very roughly) ~50ms 
- Single machine systems and distributed systems with session affinity can continue to utilize L1 cache (which is the default)

## Guidance for app 2 app authentication (client_credentials)

- You can choose to rely on memory caching (L1) only. 
- There is 1 token per **tenant**. So if your service talks to another service which exists in N tenants, there will be N tokens. A token entry is about 2KB in size. There are over 1M tenants in AAD, but many services are not multi-tenant.
- There is no need to disable L1 caching if you go with L1 / L2 (i.e. the session stickyness concept does not play a role here)
- The TokenCache package (version 1.22+) will set a time eviction  for L1/L2 as the expiration time of access token

Hope this helps.

**Comment by bgavrilMS** [comment]
@jmprieur @jennyf19 - can you please review my comment in case I said smth wrong?

Also, I think we need to make a few changes to the token cache doc: 

- clarify that by default Id.Web uses an L1 / L2 cache, where L2 is based on IDistributedCache. It's not clear that there is actually an L1 there.
- I don't think there is any difference between MemoryCache / DistributedMemoryCache. We should all mention of this and just state that the default implementation for IDistributedCache - i.e. `DistributedMemoryCache` - is not distributed and is not persisted.

Thoughts?

**Comment by luismanez** [comment]
Awesome clarification @bgavrilMS ! many thanks. I´m just curious, how can you disable L1 cache??

**Comment by bgavrilMS** [comment]
Something like: 

![image](https://user-images.githubusercontent.com/12273384/149515063-aa7e0126-821f-44d2-981c-096cb028ff7b.png)

**Comment by luismanez** [comment]
Great! thanks @bgavrilMS ... I haven´t worked with the library in the last months, and seems the team has done a lot of improvements!!

**Comment by jennyf19** [comment]
> * I don't think there is any difference between MemoryCache / DistributedMemoryCache. We should all mention of this and just state that the default implementation for IDistributedCache - i.e. `DistributedMemoryCache` - is not distributed and is not persisted.

It is not persisted, but it is distributed. We have the difference [documented here](https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization#inmemory-vs-distributedmemory-cache-options)

**Comment by newbiedev123** [comment]
Thank you all for your valuable suggestions.

We are planning to go for a distributed (redis/sql/cosmos), but we are thinking of trying in memory first. The UI which calls this API caches the API response at its end, so only occasional calls will reach the API. So not sure if we will need a distributed option.

I was trying out In memory (both distributed and non distributed) to see for the difference. How can I log the below info to app insights to see which performs better.

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnetcore#monitor-cache-hit-ratios-and-cache-performance

**Comment by bgavrilMS** [comment]
@jennyf19 - according to https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-6.0#distributed-memory-cache

`the Distributed Memory Cache isn't an actual distributed cache. Cached items are stored by the app instance on the server where the app is running.` I'll update our docs.

@newbiedev123 - sounds good, let us know the results, although in-memory cannot be distributed. Our libraries do not integrate directly with App Insights, but App Insights allow you to send them various datapoints such as numbers (laltency) and booleans (was the cache hit?).
