### ISSUE TITLE
[Question] Localization on flow cancellation with Azure B2C

### ISSUE THREAD

**Issue by Ponant** [AzureAD/microsoft-identity-web#1596]
Following https://github.com/AzureAD/microsoft-identity-web/issues/1458 , localization works nicely when redirecting to the identity provider from an .Net  6 application using the library with Azure B2C.

When the user cancels an Azure B2C signin flow, the OnRemoteFailure is invoked and the user redirection is handled here
 https://github.com/AzureAD/microsoft-identity-web/blob/52c4f8b6ca0217b303669417b57f962409cf342e/src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs#L89

The process of cancelling the flow, however, makes me lose the ui_locales, so that the default language is displayed to the user, instead of what was sent at the beginning of the sign in flow.

For example, if the default language in the app and azure b2c is set to French, but the user sets the localization to english (cookie) using the localization library, and clicks the sign in button from the .Net 6 razor Pages app, he is properly channelled to an english version of the Azure B2C sign in flow, but if he cancels the operation, he will go back to the app in the (default) French locale.

It seems that in `OnRemoteFailure` the ui_locales is already lost on its way back to the app, so that I fail to do something like in the issue https://github.com/AzureAD/microsoft-identity-web/issues/1458 .

Any help on how to do this is greatly appreciated.

**Comment by Ponant** [comment]
Hi @jennyf19 , sorry I can't tell you because I shifted from the library and I fxed it on my own (and that was some time ago...).
Felle free to close and thanks for the input.

**Comment by Eagle3386** [comment]
@jennyf19 Almost 1 year later, I can confirm that the issue persists:

I added `ui_locales` set to `de` to the `extraQueryParameters` parameter within my standalone Blazor WASM app's login prompt & upon explicitly canceling the popup window, i.e., closing it, the error message reads `User cancelled the flow.` instead of something like `Anmeldung durch Nutzer abgebrochen.`.

Please fix this.

**Comment by jmprieur** [comment]
@Eagle3386: Blazorwasm does not use MSAL.NET, but MSAL.js.
you'd want to raise this issue in the asp.net core repo. Not in Microsoft.Identity.Web.

**Comment by jmprieur** [comment]
Closing as external.
