### ISSUE TITLE
[Feature Request] More Flexible Default Appication ID URI's for AddMicrosoftIdentityWebApiAuthentication in Web API's

### ISSUE THREAD

**Issue by Hofermania** [AzureAD/microsoft-identity-web#1604]
**Is your feature request related to a problem? Please describe.**
AddMicrosoftIdentityWebApiAuthentication configures the JWT Bearer middleware to only accept audiences in the form of "api://{applicationId}"  This is appears to be problematic for app registrations that have updated the Application ID URI in the "Expose an API" configuration in Azure

**Describe the solution you'd like**
Perhaps also allow audiences like "{applicationId}"

**Describe alternatives you've considered**
Maybe a more prominent configuration field, and I'm just missing something?  If that is the case I apologize.

**Additional context**
I was updating an old app registration that was used for ADAL to use MSAL when I came across this problem.  When I updated the client scopes to "api://{applicationId}", I would get an error that the particular scope did not exist on the tenant I was using, but I was able to create an access token if the scope used either just the GUID (like in a V1 app registration) or when I used the actual Application ID URI for the API.  The problem here is that these tokens would fail validation on the web API because the audience did not match "api://{ApplicationId}".  I do not know why the application ID URI had been changed from what the probable default was (maybe old troubleshooting?) but it definitely caused a few hours of pain for me.

Thanks

**Comment by jmprieur** [comment]
@Hofermania there is no limitation to the format of the App Id URI(s).
- You can use the `Audience` configuration to specify the audience (with any content you want). See https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#what-if-the-app-id-uri-of-your-application-is-not-apiclientid
- If you several audiences this is also possible by overriding the `JwtBearerOptions`

**Comment by Hofermania** [comment]
Thank you for the response @jmprieur.  Obviously I never saw that piece of documentation and that clears everything up.  The only thing I will add is that the {applicationId}/{whatever scope} seems to resolve in the MSAL API regardless of App ID URI.  It may still be nice to include that in accepted audiences as that is how it is framed as a possible scope in the sample client without mention of updating audience in the service:

` 
    <add key="todo:TodoListScope" [value="api://[Enter_client_ID_Of_TodoListService-v2_from_Azure_Portal,_e.g._2ec40e65-ba09-4853-bcde-bcb60029e596]/access_as_user"/>`

Thanks again

**Comment by jmprieur** [comment]
Right, @Hofermania.
This is something that is really under the control of ASP.NET Core (not Id.Web), but we'll work with them.
