### ISSUE TITLE
[Documentation] Token cache encryption aka.ms link doesn't exist

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#1611]
### Description of the issue

The link (https://aka.ms/ms-id-web/token-cache-encryption) doesn't exist anymore. Not sure if we have cache encryption documented anywhere, so maybe at least point to [ASP.NET Core Data Protection doc](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0)? 

Also maybe helpful to include a link to [Token cache troubleshooting wiki](https://github.com/AzureAD/microsoft-identity-web/wiki/Token-Cache-Troubleshooting) that Bogdan wrote, maybe somewhere in AddMemory/DistributedTokenCache methods XML comments.

Found it to be referenced in two locations:
https://github.com/AzureAD/microsoft-identity-web/blob/983d43ed2e3a3000bf611f28162e2fefd3244963/src/Microsoft.Identity.Web.TokenCache/MsalAbstractTokenCacheProvider.cs#L24

https://github.com/AzureAD/microsoft-identity-web/blob/983d43ed2e3a3000bf611f28162e2fefd3244963/src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs#L45

**Comment by jennyf19** [comment]
I fixed the aka.ms link. thanks. The troubleshooting guide should actually be moved to this page: https://aka.ms/msal-net-token-cache-serialization which we already reference in the xml comments.
