### ISSUE TITLE
[Bug] OnTokenValidated event (and others) doesn't seem to play nicely with async

### ISSUE THREAD

**Issue by VaticanUK** [AzureAD/microsoft-identity-web#1625]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

1.22.2

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**

```csharp
            services.Configure<MicrosoftIdentityOptions>(options =>
            {
                options.Events ??= new OpenIdConnectEvents();
                options.Events.OnTokenValidated = async context =>
                {
                    throw new AuthenticationException("Sorry, you cannot log in");
                };
            });
```

**Expected behavior**
Exception should prevent login

**Actual behavior**
Login succeeds..

remove the async:
```csharp
            services.Configure<MicrosoftIdentityOptions>(options =>
            {
                options.Events ??= new OpenIdConnectEvents();
                options.Events.OnTokenValidated = context =>
                {
                    throw new AuthenticationException("Sorry, you cannot log in");
                };
            });
```

and login fails as expected

full explanation, further details and link to a demo in github here: https://stackoverflow.com/questions/71012036/microsoft-identity-web-ontokenvalidated-event-doesnt-seem-to-play-nicely-with-a

**Possible solution**
Well, a workaround is to not have any async code, or run the async code synchronously, but that doesn't seem ideal :/

**Additional context / logs / screenshots / link to code**
I'm not 100% sure if this is a problem with this library, or ASP.NET core where a lot of the functionality that this uses exists, or whether I'm just doing something moronic (the latter is most likely 🤣🤣)

I have taken one of the official MS examples (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2) and added the customisation of MicrosoftIdentityOptions in Startup.cs: (https://github.com/VaticanUK/msal_so_fail_example/blob/master/Startup.cs#L40) using the pattern shown in the documentation: https://github.com/AzureAD/microsoft-identity-web/wiki/customization#customization-in-the-startupcs

To run the example, you need to create an app in Azure and set your client ID in appsettings.json.

As-is, the example will work, by which I mean login will fail (since there is no async keyword):

![image](https://user-images.githubusercontent.com/1851814/153190200-90ee6624-522b-454d-85ba-beeaee2969f8.png)

Exception thrown, and login aborted

If you add the async keyword, the exception will not prevent login: Exception thrown, but login succeeded
![image](https://user-images.githubusercontent.com/1851814/153190278-3fadf9f4-d8ab-493a-a3fc-830b209306ff.png)

The definition for the event is: 
`Func<TokenValidatedContext,Task> OnTokenValidated`

And I think it's called from here: https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L146

where the call is awaited, and as far as I can tell all calls up the stack are also awaited, so I can't work out why making the function async causes it to not work?

**Comment by jmprieur** [comment]
@[VaticanUK](https://github.com/VaticanUK)
1. I would not think you should throw in the OnTokenValidated method (authentication is done), but rather use authorization policies to let ASP.NET Core do the right thing. See https://github.com/AzureAD/microsoft-identity-web/wiki/authorization-policies
2. When you configure the options, you need to specify the authentication scheme `services.Configure<MicrosoftIdentityOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>`

**Comment by VaticanUK** [comment]
Hi @jmprieur thanks for your reply. Sorry I should have been clearer. Throwing is just a quick and dirty way of trying to impact the login flow in this example.

If I use an async handler, I cannot impact the login flow in any way, for example, my original use case was to add additional claims. If I get the values for those claims by forcing the code to run synchronously (and importantly remove the async keyword from the handler...) It works. If I get those same values asynchronously, the code in my handler executes but the new claims are not added to the Principal.

It was in trying to debug this that tried throwing and discovered that throwing is impacted in the same way and is a far simpler example

**Comment by VaticanUK** [comment]
I'll try out your second point shortly and reply further 🙂

**Comment by ibrahimuludag** [comment]
I had the same problem. Using 
`services.Configure<MicrosoftIdentityOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>` solved.
