### ISSUE TITLE
Connection with Azure Redis Cache is not reestablished after failover

### ISSUE THREAD

**Issue by ferronsw** [AzureAD/microsoft-identity-web#1640]
**Which version of Microsoft Identity Web are you using?**
1.22.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [X] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of Microsoft Identity Web.

**Repro**

```
if (Configuration.GetConnectionString("Redis") != null) 
          { 
              services.AddStackExchangeRedisCache(options =>
              {
                  options.Configuration = Configuration.GetConnectionString("Redis");
              });
          }

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApp(Configuration)
			.EnableTokenAcquisitionToCallDownstreamApi(options => Configuration.Bind("AzureAd", options), Configuration.GetValue<string>("AzureAd:Scopes").Split(" "))
			.AddMicrosoftGraph(Configuration.GetSection("Graph"))
			.AddDistributedTokenCaches();
```

Used connectionstring:
`<name>.cache.windows.net:6380,password=<password>,ssl=True,abortConnect=False,connectTimeout=15000`

**Expected behavior**
Reconnect with the Azure Redis cache when it's available again.

**Actual behavior**
When Microsoft updates a node the connection is terminated (failover). 
![image](https://user-images.githubusercontent.com/19926383/155143439-75744e4e-4679-4fe5-a9d7-cdb2c31ab96d.png)

The following error occurs:

```
Timeout awaiting response (outbound=0KiB, inbound=1KiB, 6920ms elapsed, timeout is 5000ms), inst: 0, qu: 0, qs: 158, aw: False, rs: ReadAsync, ws: Idle, in: 8322, serverEndpoint: Unspecified/olw-client.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: 6a43457b9b16, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=77,Free=32690,Min=1,Max=32767), v: 2.0.593.37019 (Please take a look at this article for some common client-side issues that can cause timeouts) 
```
The app won't reconnect unless it's restarted

**Comment by jmprieur** [comment]
@ferronsw : did you see that you can subscribe to the OnL2CacheFailure delegate in the MsalDistributedTokenCacheAdapterOptions, and do a retry?

https://github.com/AzureAD/microsoft-identity-web/blob/704cd3f8a8db8833888a55623c7d8e686ef6b424/src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapterOptions.cs#L25-L34

**Comment by ferronsw** [comment]
@jmprieur No I did not. Thx, I will look into it!

**Comment by ferronsw** [comment]
@jmprieur  I tried the default:

```
            services.Configure<MsalDistributedTokenCacheAdapterOptions>(options =>
            {

                options.OnL2CacheFailure = (ex) =>
                  {
                      if (ex is StackExchange.Redis.RedisConnectionException)
                      {
                          return true;
                      }
                      return false;
                  };
            });
```

The weird thing is that the application now throws many errors. 

```
Timeout performing HMGET (5000ms), next: HMGET 201edf17-fc3e-2fcb-c414-404d10772faa, inst: 32, qu: 0, qs: 27, aw: False, rs: ReadAsync, ws: Idle, in: 9106, serverEndpoint: <name>.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: ab2411fedb63, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=20,Free=32747,Min=1,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 
```

Before this only happened when there was maintanance or something. The app would'nt work, but the app keeps working now. Maybe because of the L1 cache failover?

**Comment by ferronsw** [comment]
Increasing the MinThreads resolved this issue. I did it trought the csproj file:

```
	<PropertyGroup>
		<ThreadPoolMinThreads>50</ThreadPoolMinThreads>
	</PropertyGroup>
```

**Comment by jmprieur** [comment]
Thanks for sharing your solution, @ferronsw
