### ISSUE TITLE
[Bug] Exception when cache deserialization fails

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#1643]
**Which version of Microsoft Identity Web are you using?**
1.23.0

**Actual behavior**
Related to MSAL issue [3162](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3162).
When distributed cache serialization and encryption is enabled, in certain cases (like when encryption keys are changed), MSAL will fail to deserialize an already serialized cache entry and throw an exception.

**Repro**
1. Use [WebAppCallsMicrosoftGraph](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/WebAppCallsMicrosoftGraph).
1. Add distributed token caches, data protection (with data protection discriminator), and encryption.
```csharp
...
.AddDistributedTokenCaches();
services.AddDataProtection(o =>
{
    o.ApplicationDiscriminator = "DataProtectionApplicationDiscriminator12";
});

services.Configure<MsalDistributedTokenCacheAdapterOptions>(options =>
{
    options.Encrypt = true;
});
```
3. Set up some distributed cache like SQL or Redis.
4. Login once, so that encrypted token is in the L2 cache. (Don't sign out, it will delete the cached token.)
5. Change the data protection discriminator to something else.
6. Login with the same account again.
7. Data protection will fail decrypting the cache entry, and pass the encrypted entry to MSAL which will fail at deserialization.

**Expected behavior**
Cache is cleared, code execution continues.

**Comment by jennyf19** [comment]
released in [1.23.1](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.23.1)
