### ISSUE TITLE
[Feature Request / Question]  Enable logging when multiple tokenencryption certs are used

### ISSUE THREAD

**Issue by thegalah** [AzureAD/microsoft-identity-web#1646]
**Is your feature request related to a problem? Please describe.**
Our team is in the process of rotating tokenencryption certs. We have decided to implement a "primary / secondary" cert rotation method where we will set two token decryption certs (outlined here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.tokendecryptionkeys?view=azure-dotnet#microsoft-identitymodel-tokens-tokenvalidationparameters-tokendecryptionkeys)
In this way, whilst a cert is being rotated one of the certs will be "successful" and one will be "unsuccessful"
It is not clear whether it is possible to log the successful cert thumbprint whilst the rotation is occuring.

The use case is that while we are rotating we will expect telemetry to show us 100% Primary, 0% Secondary -> 0% Primary, 100% Secondary.

In this way we can remove the primary from rotation after we reach the latter state.

**Describe the solution you'd like**
A way for us to be able to Log the thumbprint or access the thumprint perhaps from the request contect.

**Comment by jennyf19** [comment]
done in identity model. Please use the latest Id Web.
