### ISSUE TITLE
[Question] Why are my OpenIdConnectEvents not firing?

### ISSUE THREAD

**Issue by rob-king-volpara** [AzureAD/microsoft-identity-web#1647]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.23.0

**Where is the issue?**
* Web app
    * [X] Sign-in users

**Is this a new or an existing app?**
This is a new .Net 6 app which is a port of a .Net Framework 4.8 app

**Repro**

Program.cs:
```csharp
builder.Services
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                })
                .AddMicrosoftIdentityWebApp(MicrosoftIdentityAuthentication.Setup(serviceProvider), openIdConnectScheme: "MSID");
```
MicrosoftIdentityAuthentication.cs
```csharp
public static Action<MicrosoftIdentityOptions> Setup(ServiceProvider serviceProvider)
        {
            _configuration = serviceProvider.GetRequiredService<IConfiguration>();
            _tokenService = serviceProvider.GetRequiredService<ITokenService>();
            _keyVaultService = serviceProvider.GetRequiredService<IKeyVaultService>();

            tenantId = _configuration["sso:MSID:TenantId"];
            clientId = _configuration["sso:MSID:ClientId"];
            clientSecret = _configuration["sso:MSID:ClientSecret"];
            instance = _configuration["sso:MSID:Instance"];
            authority = instance;

            return (options) =>
            {
                options.TenantId = tenantId;
                options.ClientId = clientId;
                options.ClientSecret = clientSecret;
                options.Authority = authority;
                options.Instance = instance;
                options.CallbackPath = "/signin-oidc";
                options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
                options.UseTokenLifetime = true;

                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true
                };

                options.ProtocolValidator = new OpenIdConnectProtocolValidator
                {
                    NonceLifetime = new TimeSpan(0, 6, 0, 0),
                    RequireStateValidation = false
                };

                options.Events = new OpenIdConnectEvents
                {
                    OnRedirectToIdentityProvider = OnRedirectToIdentityProviderFunc,
                    OnTokenValidated = OnTokenValidatedFunc,
                    OnAuthorizationCodeReceived = OnAuthorizationCodeReceivedFunc,
                    OnAuthenticationFailed = OnAuthenticationFailedFunc
                };
            };
        }

private static Task OnAuthorizationCodeReceivedFunc(AuthorizationCodeReceivedContext context)
        {
            var code = context.ProtocolMessage.Code;
}
```

**Expected behavior**
When the user is redirected to their Azure idp they can sign in. I expect that on successful authentication to the idp, the OnAuthorizationCodeReceived event is fired and I can step into that event. We do this successfully in our .Net Framework app to enrich the identity with some extra claim information etc.

**Actual behavior**
After the user has successfully authenticated through the idp, the events don't fore and they are returned to the login screen. Looking at the network traffic in the browser, a code and id_token are returned successfully. The one even that does fire is the OnRedirectToIdentityProvider event so I know the event wiring is working.

**Additional context / logs / screenshots / link to code**
The suggestion has been made to me that the authentication flow that I am experiencing is one that doesn't trigger these events and that I need to specify something else to make these events fire.

**Comment by jmprieur** [comment]
@rob-king-volpara : a lot of the code you have is not necessary.
Please look at https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps on how to use Microsoft.Identity.Web.

**Comment by rob-king-volpara** [comment]
Hi @jmprieur thanks for the link. I stripped back my code and it worked fine. So I gradually reintroduced bits of our code that we needed and found the issue was coming from the **OnRedirectToIdentityProvider** event.

I was setting the redirect URIs and this was causing the app to return to the home page bypassing the other events. This is what I have now and you can see the commented out bits which were casuing the issue.

```
private static Task OnRedirectToIdentityProviderFunc(RedirectContext context)
        {
            //string appBaseUrl = $"{context.Request.Scheme}://{context.Request.Host}{context.Request.PathBase}/";
            //context.ProtocolMessage.RedirectUri = $"{appBaseUrl}";
            //context.ProtocolMessage.PostLogoutRedirectUri = appBaseUrl;

            string login_hint = context.Properties.GetParameter<string>("login_hint");
            context.ProtocolMessage.LoginHint = login_hint;

            return Task.CompletedTask;
        }
```

I don't know if this is the expected behaviour since this stuff is a bit new to me. However it is different to how it behaves with our older OpenIdConnect code hence me getting tripped up.

**Comment by jmprieur** [comment]
@rob-king-volpara : the redirect URIs is the URL where Azure AD will send back the token to your web app. It's fixed depending on the authentication handler (/signin-oidc here). If you change it, your app won't receive the token, I don't think that other OIDC frameworks do differently as the address needs to be registered in the identity provider (Azure AD)

**Comment by jennyf19** [comment]
closing as answered. feel free to re-open is necessary. Thanks!
