### ISSUE TITLE
Maybe just use throw and not throw exception ?

### ISSUE THREAD

**Issue by MauRiEEZZZ** [AzureAD/microsoft-identity-web#1651]
https://github.com/AzureAD/microsoft-identity-web/blob/bba91c4298411e780c9f082e8e3843eacd8e543c/src/Microsoft.Identity.Web/MicrosoftIdentityConsentAndConditionalAccessHandler.cs#L145

While debugging I stumbled upon this line as I was matching my stacktrace.
If this method just doesn't want to handle the exception it is better rethrown using only throw; and not throw ex; 
This first method resets the stacktrace.

**Comment by bgavrilMS** [comment]
If you are in a catch block, you can rethrow via `throw` instead of `throw ex` which preserves the stack trace. But I don't think you can rethrow in a like `HandleException(Exception e)`
