### ISSUE TITLE
[Bug] Fail to obtain access token for downstream API when app registered to use Personal Accounts

### ISSUE THREAD

**Issue by adamsosinski** [AzureAD/microsoft-identity-web#1666]
**Which version of Microsoft Identity Web are you using?**  11.16.0
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

Those are new apps for experiments

**Repro**

I have two apps registered within Azure AD that support both multitenant and personal accounts (**external** and **internal**)
For external, the API Permission is set for the internal app so it can downstream the user information within the token.

![image](https://user-images.githubusercontent.com/25317691/159719705-7c61c93d-edb2-4c1c-83ac-2073d50e28b8.png)

I'm using Postman for testing calling internal from external on behave of the identified user.
I'm retrieving access tokens using the Authorization tab

![image](https://user-images.githubusercontent.com/25317691/159723081-9bad7b86-ca81-42d8-b9c1-05c5f1550b53.png)

where for the scope I provide the one registered for external, as using '.default' returns invalid_scope from Postman.
When I try to call
```csharp
string accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(_scopesToAccessDownstreamApi);
```
with either '.default' scope or one registered for internal in `_scopesToAccessDownstreamApi` I receive the exception (I'm using the Application ID URI of internal for those scopes)

**Expected behavior**
Code should work despite supported account types for which the app is registered.

**Actual behavior**
![image](https://user-images.githubusercontent.com/25317691/159723933-c2fa327a-3b0e-4346-89bf-4dd407fbb014.png)

**Possible solution**

**Additional context / logs / screenshots / link to code**

The same code works when I use single-tenant registered apps. The only difference is in "TennantId" at appsettings.json where for this case it is set to 'common', also the URLs for authorize and token at Postman have TennantId instead of common.

The same issue is for apps registered to support only personal accounts so I'm assuming there is some issue related to provisioning the access to downstream API for tokens generated for personal accounts. 
Additionally, for those apps, I'm not able to change the status to granted, even though I'm logged in as Global Administrator.

**Comment by jmprieur** [comment]
For apps configured to support only MSA, did you try to set the tenant to `consumers` ?

**Comment by jennyf19** [comment]
closing as answered. feel free to re-open is necessary. Thanks!

**Comment by adamsosinski** [comment]
I would like to re-open that bug, as it is not resolved in my opinion.
To answer @jmprieur yes, I have done that as well with the same result.

**Comment by jmprieur** [comment]
Looking at it, there is no way for an admin of your tenant to consent on behalf of MSA users, @adamsosinski.
Do I understand that you get the error on your internal web API? If that's the case, you need to have something (a setup experience) that lets MSA users to consent to your internal API calling 

See also https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/3.-Web-api-call-Microsoft-graph-for-personal-accounts

**Comment by jmprieur** [comment]
proposing to close as answered, but feel free to reopen if you disagree, @adamsosinski
