### ISSUE TITLE
[Bug] (specific authentication scheme)

### ISSUE THREAD

**Issue by munkii** [AzureAD/microsoft-identity-web#1668]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Microsoft Identity Web 1.21.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [X] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
The app is in production, I have upgraded to a new version of Microsoft Identity Web in DEV environment and seen the issue.

**Repro**

```csharp
var accessToken = await this.tokenAcquisition.GetAccessTokenForAppAsync(this.auditApiScope);
```

**Expected behavior**
I would expect to get a token and I do ghet a token using versions 1.11.0 to 1.16.0

**Actual behavior**
On versions from 1.16.1 to 1.12.1 I get MsalClientException 

> IDW10104: Both client secret and client certificate cannot be null or whitespace, and only ONE must be included in the configuration of the web app when calling a web API. For instance, in the appsettings.json file.

**Possible solution**
My current workaround is to keep my version to 1.16.0

**Additional context / logs / screenshots / link to code**
I originally raised this as a Stackoverflow question, [MsalClientException IDW10104 from GetAccessTokenForAppAsync](https://stackoverflow.com/questions/71600292/msalclientexception-idw10104-from-getaccesstokenforappasync) I have since answered the question explaining that the issue only came in at 1.16.1. Note the use of `ForwardDefaultSelector ` to get rid of all the extraneous exceptions.

**Comment by jmprieur** [comment]
@[munkii](https://github.com/munkii)
I think that this is an authentication scheme issue.

you might want to:
- either define a default authentication scheme in your startup.cs
- Or use the override of GetAccessTokenForAppAsync with the authenticationScheme parameter, and use the authentication scheme for which you registrered the web API (B2CScheme).

See https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes

We are, btw adding a new exception to the next version of Microsoft.Identity.Web to help with the authentication schemes

**Comment by jennyf19** [comment]
closing as answered. feel free to re-open if necessary. thanks!

**Comment by jennyf19** [comment]
closing as answered. feel free to re-open if necessary. thanks!
