### ISSUE TITLE
What is the proper way to register an L2 cache?

### ISSUE THREAD

**Issue by plamber** [AzureAD/microsoft-identity-web#1670]
**Is your feature request related to a problem? Please describe.**
Hello,
we are using in our projects the latest version of Microsoft.Identity.Web. We came to an interesting challenge that I am not sure how to solve properly. Maybe you could point me in the right direction.

We are using Microsoft.Identity.Web and the IDistributedCache implementation for L2 cache targeting environment X. 
In the same project, we are using a different library that also requires an implementation of the IDistributedCache interface but with the requirement to target a different L2 cache environment Y.

Is there a way for me to pass an instance of L2 cache to Microsoft.Identity.Web without using the IDistributedCache interface? Maybe there might be a way to do it directly in the constructor AddDistributedTokenCaches() by passing some singletons? Are there other ways to register a custom L2 cache in Microsoft.Identity.Web?

And the last question related to caching. Is there a way to specify a custom implementation of L1 cache?

Thank you for your feedback,
Patrick

**Comment by jmprieur** [comment]
@[plamber](https://github.com/plamber). Microsoft.Identity.Web just uses directly IDistributedCache. So you cannot really have different implementations unless you inherit from IDistributedCache for your other environment, or for the distributed token cache.

You can, if you wish you can provide your own token cache adapter by doing something like: https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs

but use a different interface here:
https://github.com/AzureAD/microsoft-identity-web/blob/855f6d4d9ffa52286fe432efeb5f25e625e0de5b/src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs#L25

**Comment by plamber** [comment]
Hi @jmprieur,
thank you for your feedback. This looks good to me.

And with this line I am going to register it.

https://github.com/AzureAD/microsoft-identity-web/blob/855f6d4d9ffa52286fe432efeb5f25e625e0de5b/src/Microsoft.Identity.Web.TokenCache/Distributed/DistributedTokenCacheAdapterExtension.cs#L27

Thank you,
Patrick

**Comment by jmprieur** [comment]
right Patrick!
