### ISSUE TITLE
.NET Core 6 MVC app that signs in users

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-identity-web#1671]
Do we have a sample for web app that signs in users using .NET Core 6?

**Comment by jmprieur** [comment]
@[jrmcdona](https://github.com/jrmcdona)

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/1-WebApp-OIDC/README.md

In fact just replace netcoreapp3.1 or net50 by net60 in the TargetFramework / TargetFrameworks element of your csproj and you are good.

**Comment by jrmcdona** [comment]
@jmprieur great thanks. Out of curiousity how come the samples do not have AccountController in them yet the loginPartial.cshmtl  says to use the AccountController?

Is there magic happening?

**asp-controller="Account"**

**Comment by jrmcdona** [comment]
Nevermind I see this:
In ASP.NET, selecting the Sign-in button in the web app triggers the SignIn action on the AccountController controller. In previous versions of the ASP.NET core templates, the Account controller was embedded with the web app. That's no longer the case because the controller is now part of the Microsoft.Identity.Web.UI NuGet package. See [AccountController.cs](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs) for details.

**Comment by jrmcdona** [comment]
If you want to use the out of the box Program.cs that comes with a new .NET Core 6 project it can be like this for example:

```
using Experimental.AspNetCore.Migrations;
using Microsoft.Identity.Web;
using Microsoft.Identity.Web.UI;

builder.Services.Configure<CookiePolicyOptions>(options =>
{
    // This lambda determines whether user consent for non-essential cookies is needed for a given request.
   // options.CheckConsentNeeded = context => true;
    options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
    // Handling SameSite cookie according to https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1
    options.HandleSameSiteCookieCompatibility();
});

// Sign-in users with the Microsoft identity platform
builder.Services.AddMicrosoftIdentityWebAppAuthentication(builder.Configuration, "AzureAD", "OpenIdConnect" , "Cookies");

builder.Services.AddControllersWithViews(options =>
{
var policy = new AuthorizationPolicyBuilder()
 .RequireAuthenticatedUser()
    .Build();
options.Filters.Add(new AuthorizeFilter(policy));
}).AddMicrosoftIdentityUI();

builder.Services.AddRazorPages();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.UseEndpoints(endpoints =>
{

    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");

    endpoints.MapControllerRoute(name: "signin-oidc",
            pattern: "signin-oidc",
            defaults: new { controller = "Home", action = "signin-oidc" });

    endpoints.MapControllerRoute(name: "signout-oidc",
               pattern: "signout-oidc",
               defaults: new { controller = "Home", action = "signout-oidc" });

    endpoints.MapRazorPages();
});


app.MapReverseProxy();

app.Run();
```
