### ISSUE TITLE
GraphQL API's

### ISSUE THREAD

**Issue by fiakkasa** [AzureAD/microsoft-identity-web#169]
**Describe the solution you'd like**
I would like to be able to interact with the API surface of identity web using GraphQL API's.

**Describe alternatives you've considered**
An alternative would be to provide gRPC API's where as a developer I would consume the contracts produced by the protobufs in my application.

**Comment by bgavrilMS** [comment]
Not sure there is enough detail here. AAD exposes OIDC compliant endpoints and MSAL / Microsoft.Identity.Web provide a higher level API to fetch tokens. 

Can you explain what scenarios you'd like to achieve with GraphQL, gRPC or protobuf?

**Comment by fiakkasa** [comment]
For GraphQL what changes is the shape of the request and the response.
In essence, GraphQL enables the possibility to request the data you need which practically reduces over-fetching / under-fetching scenarios.
For good example consider the a use case where only the username of a user is required for presentation purposes; in addition, let's assume that the data exchange will occur on a limited connectivity scenario, think Edge or 2G, doing so with REST based API's there would be way more data travelling on the wire.

**Comment by fiakkasa** [comment]
Regarding gRPC, we are looking at clearly more efficient and secure protocol thanks to HTTP 2.
Protobufs will enable us to work with strongly typed contracts in our client apps.
Such a scenario would be to provide a streaming gRPC endpoint that would notify me instead of polling it whenever my token is about to expire.

**Comment by bgavrilMS** [comment]
Got it. Authentication is governed by standards such as OAuth2 and OpenID Connect. So we don't have any leeway on the amount of data requested. You can configure the tokens to contain optional claims, which will make them larger. I think it is more important to understand and utilise token caching, which will eliminate a lot of requests to the server.

MSAL / Identity.Web are not low level libraries so it isn't in their remit to provide gRPC or protobuf descriptions. But AAD is OIDC compliant, so any gRPC description should work.

**Comment by fiakkasa** [comment]
Thanks!

**Comment by jmprieur** [comment]
@fiakkasa I'm confused by your request. Would you please provide repro steps of what you'd like to that. There is no API surface per se in Microsoft.Identity.Web. ? It inserts in ASP.NET Core?

**Comment by fiakkasa** [comment]
@jmprieur The idea is to be able to use GraphQL to perform requests related to identity instead of REST requests.
The API surface of Microsoft.Identity.Web that I know of does not provide GraphQL endpoints.
Yes, it does integrate with ASP.NET Core by using the related packages like HotChocolate or GraphQL.NET

**Comment by jmprieur** [comment]
what is the API surface of Microsoft.Identity.Web that you know, @fiakkasa ?
Can you give an example of what you have in mind. I don't understand at all.
(and I know what GraphQL is, BTW. It's just I cannot connect the dots ...)

**Comment by fiakkasa** [comment]
Please correct me if I missed something, but the Microsoft.Identity.Web enables the possibility to use auth in an app without having to add the scaffolding yourself.
I would presume that the oidc controller we typically had in an app would reside in the cloud, Azure in this case.
So instead of using REST and redirects to achieve this, would it be possible to have GraphQL endpoints that would do 
- sign in / out
- token refresh
- all the other goodies that come with Microsoft.Identity.Web 🙂

**Comment by jmprieur** [comment]
My understanding is that this would be for the service (Azure AD)
Closing as external. Will follow-up with service people

**Comment by fiakkasa** [comment]
Thanks for looking into it.
