### ISSUE TITLE
[Feature Request] Allow access to IServiceProvider in .AddMicrosoftGraph() factory method

### ISSUE THREAD

**Issue by marcinburak** [AzureAD/microsoft-identity-web#1695]
**Is your feature request related to a problem? Please describe.**
I'd like to add my own custom logging middleware to the underlying `GraphServiceClient` instance. I followed the [official Graph SDK documentation instructions](https://docs.microsoft.com/en-us/graph/sdks/customize-client?tabs=csharp) so I've created my own `DelegatingHandler` implementation, e.g.

```csharp
internal class MyCustomMicrosoftGraphLoggingMiddleware : DelegatingHandler
{
    private readonly ILogger<MyCustomMicrosoftGraphLoggingMiddleware> _logger;

    public MyCustomMicrosoftGraphLoggingMiddleware(ILogger<MyCustomMicrosoftGraphLoggingMiddleware> logger)
    {
        _logger = logger;
    }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
    {
        // logging logic
    }
}
```

then I'm trying to customize my `GraphServiceClient` by using the `.AddMicrosoftGraph()` factory method, but I can't resolve the `ILogger<>` dependency required by my custom middleware `MyCustomMicrosoftGraphLoggingMiddleware`

```csharp
services.AddMicrosoftIdentityWebApiAuthentication()
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddMicrosoftGraph(graphAuthenticationProvider => 
    {
          var middlewareHandlers = GraphClientFactory.CreateDefaultHandlers(graphAuthenticationProvider);
          var compressionMiddlewareHandler = middlewareHandlers.FirstOrDefault(handler => handler is CompressionHandler);
          if (compressionMiddlewareHandler is not null)
          {
              middlewareHandlers.Remove(compressionMiddlewareHandler);
          }
          middlewareHandlers.Add(new MicrosoftGraphLoggingMiddleware(/* HOW DO I PASS MY ILogger<> INSTANCE HERE FROM THE DI CONTAINER? */));

          var httpClient = GraphClientFactory.Create(middlewareHandlers);
                    
          return new GraphServiceClient(httpClient);
    })
    .AddInMemoryTokenCaches();
```

**Describe the solution you'd like**
I'd like to access `IServiceProvider` inside the `.AddMicrosoftGraph()` factory method in order to resolve my custom services from the DI container and pass them to my custom middleware instance.

**Describe alternatives you've considered**
Right now I'm considering some sort of an anti-pattern like accessing static reference to `IServiceProvider` located directly in my `Startup.cs`.

**Additional context**
-

**Comment by jennyf19** [comment]
done in 2.5.0.
