### ISSUE TITLE
[Documentation] how to increase debug output?

### ISSUE THREAD

**Issue by lknite** [AzureAD/microsoft-identity-web#1698]
I've implemented ```[Authorize]``` before using ADFS, so have some experience with what is happening.

Implemented according to this page:
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration

Added to Startup.cs
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd");
```

Added to appsettings.json
```json
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "c53<guid>c81",
    "ClientId": "96c<guid>e3f"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}
```

Got an invalid Audience error and so tried adding:
```json
"Audience": "api://96c<guid>e3f"
```
and this:
```json
"Audience": "//96c<guid>e3f"
```

Adding an audience and modifying the clientid both got rid of the error message.   But, I'm still getting 401 when calling method with an Authorization header and specifying a valid "Bearer <token>" value.

Adding this in the past helped to troubleshooting using ADFS, but didn't seem to do anything this time:
```c#
IdentityModelEventSource.ShowPII = true;
```
Without anything in the logs, tricky to troubleshoot.  Everything looks good as far as I know, so how to troubleshoot?

c# / .NET 5.0 / Microsoft.Identity.Web 1.23.1

**Comment by jennyf19** [comment]
@lknite You can set up logging specific to Id.Web and MSAL.NET - [see here](https://github.com/AzureAD/microsoft-identity-web/wiki/Logging#how-do-i-enable-the-msal-net-logs) for details. That should give you more information hopefully.

Also, Id.Web does not yet support ADFS, so here are some related issues: https://github.com/AzureAD/microsoft-identity-web/issues/1638, https://github.com/AzureAD/microsoft-identity-web/issues/852. Looks like we would need to do [this](https://github.com/AzureAD/microsoft-identity-web/issues/1638#issuecomment-1048134422), but I have not looked into it.

**Comment by lknite** [comment]
@jennyf19 Thanks for your quick response.  I'm not trying to setup ADFS, but rather use Azure as my Identity Server to perform authentication of users on a webapi.  I'm not currently trying to setup the client side of things.  For now it is alright to use a swagger page & manually provide a bearer token to test.  I just need to get the webapi side working.

From the link provided I have configured my app settings with:
```
"Logging": {
        "LogLevel": {
            "Default": "Information",
            "Microsoft": "Information",
            "Microsoft.Identity.Web":  "Information"
        }
```

Still not seeing anything in the logs to help me identify what might be going wrong.  Am I implementing the logging as you had in mind?  Any other ideas?

**Comment by jennyf19** [comment]
@lknite The audience should be your web API: 
`"Audience": "api://96c<guid>e3f"`
Is that the audience of the token you are sending to it? This is the `aud` claim in the token.

**Comment by lknite** [comment]
Via portal.azure.com -> App Registrations, I have an app registered there.  The values it uses are GUID values.  What I have for ClientId what is labled as "Application (client) ID" in the app registration.  I just added "api://".

I just generated a token and looked inside.  The 'aud' is the same guid value '96c<guid>e3f', there is no "api://' in front of it.

**Comment by lknite** [comment]
Located this url which seems to have some additional steps I need to configure the registered app.  Will pick this back up tomorrow.
```
https://docs.microsoft.com/en-us/azure/active-directory/develop/web-api-quickstart?pivots=devlang-aspnet
```

**Comment by lknite** [comment]
In Azure under Expose an API, I've enabled that and now have an ```api://<guid>```.  Also added an 'Admins and users' scope.

**Comment by jmprieur** [comment]
@lknite : is your issue solved?

**Comment by lknite** [comment]
@jmprieur not at all, ... waiting a bit before retrying, hoping some new documentation or an article will be written on the topic in the meantime
