### ISSUE TITLE
[Bug] appsetting.json and identity federation helper class should explain more what it's for, not the implementation detail 

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1699]
**Which version of Microsoft Identity Web are you using?**
not released yet

Why?
From the point of view of a developer, what matters is that they want to avoid having to provide client secrets and client certificates. but that's not what the following tells us. It talks about implementation details (using identity federation in MSAL).

```Json
"IdentityFederation": {
 "IsEnabled": true, 
 "SubjectIdentifier": "02c0b640-8e3d-405e-999d-4781f2f0438a"
}
```

Before we release Id.Web, I propose we change the name of these settings to something like:

```Json
"ClientCredentialsUsingManagedIdentity": {
   "IsEnabled": true,
    "ManagedIdentityObjectId": "02c0b640-8e3d-405e-999d-4781f2f0438a"
}
```

We would also want to rename [AzureFederatedTokenProvider](https://github.com/AzureAD/microsoft-identity-web/blob/9b159ba02f3b38d62777ed21b71704dfd84e538d/src/Microsoft.Identity.Web.IdentityFederation/AzureFederatedTokenProvider.cs#L20) to **MsiClientAssertion**

**Comment by jennyf19** [comment]
Released in [1.24.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.24.0).
