### ISSUE TITLE
Investigate if AuthorizeForScopes could use a Policy instead of an exception filter

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#17]
**Why?**
Policies work independently of ASP.NET, or even Http. They work with SignalR..
The recommendation of the ASP.NET Core team is to not embed rules in a filters
Policies can be parametrized. 

**What?**
AuthorizeForScopes might be be a Policy 
(or not, this might not work, in which case Barry wants to know)

**Resources**
=> GitHub.com/blowdart=>old workshop.

copied from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/292

**Comment by jmprieur** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.1

**Comment by DamianEdwards** [comment]
This is more important now with the advent of Minimal APIs in ASP.NET Core 6.0, i.e. a way to author web APIs without using MVC controllers. As the current attribute is implemented as an MVC action filter, it can't be used with APIs authored in this new way.

Ideally the attribute should be reimplemented as endpoint metadata that is read by a configured auth policy. Whether the policy is configured directly in the project using the existing authz APIs or there is a new helper added to MIW to enable doing this more elegantly, or perhaps even by default, is something that should be investigated.

**Comment by jmprieur** [comment]
@DamianEdwards AuthorizeForScopes is not used in web APIs, only in web apps.
But we got the point.

**Comment by DamianEdwards** [comment]
Ah sorry for confusion, I thought this was the issue that was pointed to when we were discussing tracking the work to move the filter attribute to a policy-based approach. Where is that issue? 😄

**Comment by jmprieur** [comment]
@DamianEdwards : this was my point yesterday when we asked Barry to create an issue for the Scopes filter ;-). We don't have such an issue yet.

**Comment by DamianEdwards** [comment]
It's not this one? #1434

**Comment by jmprieur** [comment]
My understanding is that #1434 is what Barry advises to apply to `[AuthorizeForScopes]`, not to `[RequiredScopes]` ?

**Comment by jennyf19** [comment]
closing as not possible. Needs to be filter
