### ISSUE TITLE
gRPC API's

### ISSUE THREAD

**Issue by fiakkasa** [AzureAD/microsoft-identity-web#170]
**Describe the solution you'd like**
I would like to be able to interact with the API surface of identity web using gRPC API's.

**Describe alternatives you've considered**
An alternative would be to provide GraphQL API's where as a developer I would consume the GraphQL schema in my application.

**Comment by jmprieur** [comment]
Which API surface @fiakkasa ?
Do you mean Azure AD ? Microsoft.Identity.Web improves the developer experience on top of ASP.NET Core. I'm not sure I understand what you mean

Can you please provide repro steps?

**Comment by fiakkasa** [comment]
This is similar to issue 169, but instead of GraphQL is referring to gRPC for web.

**Comment by jmprieur** [comment]
My understanding is that this would be for the service (Azure AD)
Closing as external. Will follow-up with service people

**Comment by fiakkasa** [comment]
Much appreciated.
