### ISSUE TITLE
[Documentation] msidentity-app-sync should support NET 6.0 or redirect to dotnet msidentity

### ISSUE THREAD

**Issue by dagrooms52** [AzureAD/microsoft-identity-web#1708]
### Documentation related to component

App Provisioning Tool
https://github.com/AzureAD/microsoft-identity-web/blob/master/tools/app-provisioning-tool/README.md

### Please check all that apply

- [x] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

I want to use the command `msidentity-app-sync` to provision MS Identity auth in a .NET Core webapi project generated with the command `dotnet new webapi -au SingleOrg`.
I have an existing AAD app registration with app ID `f9ff8c4f-2a57-44c8-bf37-c4df29f5b712`.
The output from the tool indicates a new app registration was created, instead of using the one with the provided ID:

```
msidentity-app-sync --tenant-id $tenantID --client-id f9ff8c4f-2a57-44c8-bf37-c4df29f5b712
Detected project type dotnet-webapi.
Authentication is not enabled yet in this project. An app registration will be created, but the tool does not add the code yet (work in progress).
Created app 9b767f36-0867-452d-b119-4440b97976a3. Summary
Writing the project AppId = 9b767f36-0867-452d-b119-4440b97976a3
```

I may not be forming the command correctly, as the `msidentity-app-sync --help` text suggests passing another argument in addition to `--client-id`, but omits the name:
>  You might want to also pass-in the ?? if you know it.

The document linked above indicates this argument is `--tenant-id`, although it did not succeed in updating my existing app registration. 

Am I missing an argument to this command? Why was a new app registration created?

**Comment by jmprieur** [comment]
Is it a .NET 6 project?

**Comment by jmprieur** [comment]
@dagrooms52. Which version of the .NET framework did you use?

**Comment by dagrooms52** [comment]
This was a .NET 3.1 project

**Comment by jmprieur** [comment]
@dagrooms52 : See https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template for .NET Core 3.1

Fixed for .NET 6.0
