### ISSUE TITLE
[Documentation] Explain how to sign-in users in a Web App with multiple IdPs (Azure AD, Azure ADB2C, and OAuth 2.0 providers)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#173]
### Documentation Related To Component:
Sign-in in Web app:
Explain how to sign-in users in a Web App with multiple IdPs (Azure AD, Azure ADB2C, and OAuth 2.0 providers)

### Please check those that apply

- [ ] typo
- [x ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

See ASP.NET Core issue https://github.com/dotnet/aspnetcore/issues/11972
@alexvy86 created a repo with a sample app that uses 3 different auth providers, based on the official Microsoft samples. It does require some setup with the app registrations in AzureAD and AzureAD B2C, but can serve as a starting point.

See the repo https://github.com/alexvy86/multi-auth-sample/

**Comment by jmprieur** [comment]
See also https://github.com/AzureAD/microsoft-identity-web/issues/549

**Comment by jmprieur** [comment]
Duplicate of https://github.com/AzureAD/microsoft-identity-web/issues/955

**Comment by jennyf19** [comment]
Included in [1.11.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.11.0) and [documentation here](https://github.com/AzureAD/microsoft-identity-web/wiki/Multiple-Authentication-Schemes).
