### ISSUE TITLE
[Feature Request] Integrate Id.Web with IIdentityLogger to write Wilson logs to AspNetCore's ILogger

### ISSUE THREAD

**Issue by sruke** [AzureAD/microsoft-identity-web#1730]

**Comment by jennyf19** [comment]
Included in [1.25.1 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.25.1)

**Comment by Marusyk** [comment]
where are the details of this Feature Request? After upgrade to 1.25.1 my app generates a lot of errors

> 
> [23-01-23 22:36:57.57Z ERR] Microsoft.IdentityModel Version: 6.25.1.0. Date 01/23/2023 22:36:57. PII logging is OFF. See https://aka.ms/IdentityModel/PII for details.
> IDX40001: Issuer: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', does not match any of the valid issuers provided for this application.  <s:Development:Twin Service/Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter>
> [23-01-23 22:36:57.57Z ERR] IDX10516: Signature validation failed. Unable to match key:
> kid: '-KI3Q9nNR7bRofxmeZoXqbHZGew'.
> Number of keys in TokenValidationParameters: '0'.
> Number of keys in Configuration: '1'.
> Exceptions caught:
>  '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
> token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Valid Lifetime: 'True'. Valid Issuer: 'False' <s:Development:Twin Service/Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter>
> [23-01-23 22:36:57.57Z ERR] IDX10205: Issuer validation failed. Issuer: 'https://sts.windows.net/XXXX-XXXX-403b-8a08-0c5f50471e64/'. Did not match: validationParameters.ValidIssuer: 'CARoot-test' or validationParameters.ValidIssuers: 'null' or validationParameters.ConfigurationManager.CurrentConfiguration.Issuer: 'Null'. For more details, see https://aka.ms/IdentityModel/issuer-validation.  <s:Development:Twin Service/Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter>
> [23-01-23 22:36:57.57Z ERR] IDX10516: Signature validation failed. Unable to match key:
> kid: '-KI3Q9nNR7bRofxmeZoXqbHZGew'.
> Number of keys in TokenValidationParameters: '0'.
> Number of keys in Configuration: '1'.
> Exceptions caught:
>  '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
> token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Valid Lifetime: 'True'. Valid Issuer: 'False' <s:Development:Twin Service/Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter>

**Comment by jmprieur** [comment]
@Marusyk 
this now integrates the detailed logs from Identity.Model, therefore surfacing real errors that you didn't see before (in other words your token is not valid)

Is the problem that you have too many logs error? I'd expect that apart from that, the web API still works?

cc: @jennyf19 @sruke: we might need a flag to disable the integration?

**Comment by Marusyk** [comment]
but if I rollback to 1.24.1 - no error about token is not valid,
because actually it is always valid and always I receive a result from API, but when 1.25.+ - it adds these logs
