### ISSUE TITLE
[Bug] In web api scenario, use the `tid` claim of the incoming assertion

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-identity-web#1738]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

In a multi-tenanted web api, IdWeb should acquire the OBO token using a tenanted authority, where the tenant is the `tid` claim of the incoming assertion (i.e. it should not use `common`)

**Comment by jmprieur** [comment]
Proposed design:

add an else condition taking the user.GetTenantId()

https://github.com/AzureAD/microsoft-identity-web/blob/bb2d213e11311f4b7c7b217a73d6d26346c34481/src/Microsoft.Identity.Web/TokenAcquisition.cs#L855-L859

**Comment by jennyf19** [comment]
Included in [1.25.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.25.0)
