### ISSUE TITLE
[Feature Request] Accept CancellationTokens in IDownstreamWebApi

### ISSUE THREAD

**Issue by h3rmanj** [AzureAD/microsoft-identity-web#1739]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to pass a CancellationToken to IDownstreamWebApi methods, allowing me to cancel requests and tasks. This is useful if you do multiple requests in your own API, but the request to your API was aborted (indicated by `HttpContext.RequestAborted`).

About every other interface by microsoft accepts a cancellation token, so I'd expect this one to do as well.

**Describe the solution you'd like**
I've made a proposal PR #1734 which adds an optional `CancellationToken cancellationToken = default` param to every IDownstreamWebApi methods and extension methods.

**Comment by jmprieur** [comment]
Fixed in IDownstreamRestApi in rel/v2
