### ISSUE TITLE
[Feature Request] Allow configuration of HttpClients for IDownstreamWebApi

### ISSUE THREAD

**Issue by h3rmanj** [AzureAD/microsoft-identity-web#1740]
**Is your feature request related to a problem? Please describe.**
I'd like to add Polly policies, described in [these docs](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) on how to implement resilient http requests.

However I can't really access the HttpClientBuilder when using the [recommended way to call downstream apis](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-call-api?tabs=aspnetcore).

There seems to be some incompatibility in whats recommended, and I'd like the gap to be closed.

**Describe the solution you'd like**
Some way to configure the HttpClients used by IDownstreamWebApi. I've proposed a solution in #1735 which allows the user to pass a `configureHttpClientBuilder` to `AddDownstreamWebApi()`.

**Additional context**
This was partly pointed out in #891 but wasn't really addressed when closed.

**Comment by luismanez** [comment]
Not sure if this helps, but this is what I´m doing to achieve what you need. Basically, I´m overwriting the HttpClient used by  ```AddDownstreamWebApi()``` and then adding my Polly stuff in the _HttpClientBuilder_ returned. In my case, it also helps to change some headers, as I´m calling SharePoint REST API, and returned XML by default

```csharp
services
                .AddHttpClient<IDownstreamWebApi, DownstreamWebApi>(client =>
                {
                    client.DefaultRequestHeaders.Add("Accept", "application/json");
                })
                .AddMyPollyStuff();
```

**Comment by bosteelsd** [comment]
We would really like this for our project too.

**Comment by jennyf19** [comment]
done in 2.5.0.

**Comment by EnricoMassone** [comment]
I recently ran into the same problem of registering a Polly-based HTTP message handler for the underlying `HttpClient `of `IDownstreamApi`. I have also asked [a question about this](https://github.com/AzureAD/microsoft-identity-web/discussions/3253#discussion-8004966) in the Discussions section. 

Just as a confirmation, the proposed solution is the one showed [here ](https://github.com/AzureAD/microsoft-identity-web/pull/1735#issuecomment-1152699911) by @h3rmanj ? If that is the case, it could be great to explain that in the available documentation. It seems it is not mentioned anywhere in the available documentation and examples for `IDownstreamApi`.

**Comment by h3rmanj** [comment]
Can confirm, currently using this extension when registering our downstream clients.

```csharp

/// <summary>
/// Extension methods to support downstream web API services.
/// </summary>
public static class DownstreamApiExtensions
{
    /// <summary>
    /// Adds a named downstream web API service related to a specific configuration section.
    /// </summary>
    /// <param name="services">Services.</param>
    /// <param name="serviceName">Name of the configuration for the service.
    /// This is the name used when calling the service from controller/pages.</param>
    /// <param name="configuration">Configuration.</param>
    /// <returns>The httpClientBuilder for the client to use.</returns>
    public static IHttpClientBuilder AddDownstreamApiClient(this IServiceCollection services,
        string serviceName,
        IConfiguration configuration)
    {
        services.AddDownstreamApi(serviceName, configuration);

        return services.AddHttpClient(serviceName);
    }
}
```

Agree docs should be added for this.

**Comment by EnricoMassone** [comment]
> Can confirm, currently using this extension when registering our downstream clients. Works with both on-behalf-of and client credential scenarios.
> 
> /// <summary>
> /// Extension methods to support downstream web API services.
> /// </summary>
> public static class DownstreamApiExtensions
> {
>     /// <summary>
>     /// Adds a named downstream web API service related to a specific configuration section.
>     /// </summary>
>     /// <param name="services">Services.</param>
>     /// <param name="serviceName">Name of the configuration for the service.
>     /// This is the name used when calling the service from controller/pages.</param>
>     /// <param name="configuration">Configuration.</param>
>     /// <returns>The httpClientBuilder for the client to use.</returns>
>     public static IHttpClientBuilder AddDownstreamApiClient(this IServiceCollection services,
>         string serviceName,
>         IConfiguration configuration)
>     {
>         services.AddDownstreamApi(serviceName, configuration);
> 
>         return services.AddHttpClient(serviceName);
>     }
> }
> Agree docs should be added for this.

@h3rmanj many thanks for the confirmation. I will do the same for my project. 

Still wondering if this is the intended way to use the abstraction. This is working because the underlying `HttpClient` is registered with the same name used to register the downstream api. Although this is reasonable, this solution relies on an implementation detail. Your [initially proposed solution](https://github.com/AzureAD/microsoft-identity-web/pull/1735#issue-1234098520) seems much better to me.

**Comment by EnricoMassone** [comment]
I finally filed a new issue (see #3258) for this topic @h3rmanj
