### ISSUE TITLE
[Blazor Server] TokenAcquisition and Claims modification conflict

### ISSUE THREAD

**Issue by boppercr** [AzureAD/microsoft-identity-web#1746]
Hi, I'm having an issue with the TokenAcquisition "mechanics" in an app. When accessing a page, the service (via DI) gets an access token and continually loops on the consent page (MsalUiRequiredException at all times) until it just stops and "crashes". 

We require to add claims to the user after signing in, so we added a OnTokenValidated event on the OpenId configuration.
 ``` C#
services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                var tokenService = new CRTokenTransformation(Configuration);
                // Use the groups claim for populating roles
                options.TokenValidationParameters.NameClaimType = "name";
                options.Events.OnTokenValidated = async context => await tokenService.OnTokenValidated(context);
            });
``` 
I won't go into details as to what the OnTokenValidated function does, but commenting it "solves" the problem. What it does is it adds and Identity to the ClaimsPrincipal.

The call to request the access token is straight forward enough, I think.
``` C#
public bool GetClient(ref ParametresClient client)
        {
            try
            {
                var accessToken = Task.Run(() => _tokenAcquisition.GetAccessTokenForUserAsync(_referencesScopes)).GetAwaiter().GetResult();
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                client = new ParametresClient(_httpClient);
                return true;
            }
            catch (Exception e)
            {
                ConsentHandler.HandleException(e);
            }
            return false;
        }
```

I've tried many ways to debug it, with no success. We really need for the new claims to exist since they are directly linked to the signed in user, but doing this seems to crash the AccessToken mechanics. 

Any ideas what might be wrong here?

**Comment by jmprieur** [comment]
@boppercr if you expect to call an API in the TokenValidated event, you need to do it after Microsoft.Identity.Web has processed the token. For this you need to chain the events.

See https://github.com/AzureAD/microsoft-identity-web/wiki/customization#how-to-query-microsoft-graph-on-token-validated
