### ISSUE TITLE
[Feature Request] ForceHttpsRedirectUris option to elegantly enable container deployments

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#175]
Initially raised by @krispenner in https://github.com/AzureAD/microsoft-identity-web/issues/115#issuecomment-627758989

**Is your feature request related to a problem? Please describe.**
For many people who only want to ensure https is used (instead of http) like myself as I'm running in a Docker container hosted in Azure App Service. I think a simpler option such as ForceHttpsRedirectUris = true in the configuration/options would be simpler. It would remove the need to specify the full absolute URI just to ensure https is used allowing the computed redirect URI to stay and just upgrade it to https. I'm concerned with managing the absolute URIs across configuration files and environments - relative paths as so much friendlier.

**Describe the solution you'd like**
Here is what I've currently done which solved my issue of http being used when in a Docker container:

services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme,
    options => {
        var redirectToIdpHandler = options.Events.OnRedirectToIdentityProvider;
        options.Events.OnRedirectToIdentityProvider = async context =>
        {
            // Call what Microsoft.Identity.Web is doing
            await redirectToIdpHandler(context);

            // Override the redirect URI to be what you want
            if (context.ProtocolMessage?.RedirectUri?.StartsWith("http://") ?? false)
            {
                context.ProtocolMessage.RedirectUri = context.ProtocolMessage.RedirectUri.Replace("http://", "https://");
            }
        };

        var redirectToIdpForSignOutHandler = options.Events.OnRedirectToIdentityProviderForSignOut;
        options.Events.OnRedirectToIdentityProviderForSignOut = async context =>
        {
            // Call what Microsoft.Identity.Web is doing
            await redirectToIdpForSignOutHandler(context);

            // Override the redirect URI to be what you want
            if (context.ProtocolMessage?.PostLogoutRedirectUri?.StartsWith("http://") ?? false)
            {
                context.ProtocolMessage.PostLogoutRedirectUri = context.ProtocolMessage.PostLogoutRedirectUri.Replace("http://", "https://");
            }
        };
    });

**Describe alternatives you've considered**
Customers are not blocked as they can set the `RedirectUri` and `PostLogoutRedirectUri`

**Additional context**
This is a nice to have that would avoid devs maitaining multiple appsettings.json, in particular when there are several deployment slots ...

**Comment by pmaytak** [comment]
Included in [Microsoft Identity Web 0.1.5-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.5-preview).

cc: @mochr @BurritoSmith @krispenner @AAGhotkar @goshmiller @graemeWT

**Comment by krispenner** [comment]
Thanks, works great!
