### ISSUE TITLE
[Bug] AddMicrosoftIdentityUserAuthenticationHandler cannot resolve ITokenAcquisition scoped service 1.25.0 (regression)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1757]
**Which version of Microsoft Identity Web are you using?**
1.25.0

**Where is the issue?**
See description and repro steps in https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/603

**Comment by jmprieur** [comment]
@jennyf19 FYI

**Comment by jennyf19** [comment]
@jmprieur ack.
