### ISSUE TITLE
[Feature Request] Managed Identity support in IDownstreamWebApi / IDownstreamApi

### ISSUE THREAD

**Issue by Rookian** [AzureAD/microsoft-identity-web#1775]
Can I also use Managed Identity (System or user-assigned) for `IDownstreamWebApi`? 
Shouldn't Managed Identity the first option that should be mentioned in the documentation for the users? My proposed order would be `Managed Identity`, `client certificate`, `client secret`.

Why do I first need to call `AddMicrosoftIdentityWebApiAuthentication(IConfiguration)` then `EnableTokenAcquisitionToCallDownstreamApi` and then `AddDownstreamWebApi`  in order to enable `IDownStreamWebApi` usage? In my case a web api (not protected) calls another web api (protected) and I would like to use Managed Identity, so there should be no further configuration needed. My expectation would be something like
```csharp
// For a system-assigned Managed Identity client id does not need to be passed
builder.Services.AddDownstreamWebApi(string managedIdentityClientId = null);
```

See also: https://github.com/MicrosoftDocs/azure-docs/issues/94620

**Comment by jmprieur** [comment]
@Rookian : if your daemon app is only hosted in Azure and you don't need to debug it locally (with the app permission), you can use Azure.Identity.
Id.Web enables you to be deployed anywhere, and debugged locally.

**Comment by Rookian** [comment]
@jmprieur The same is true for Azure.Identity, as you can use AzureCliCredential (for local usage) and ManagedIdentityCredential (for Azure environment) within a ChainedTokenCredential. 

The question from my site is, if I need to cache the retrieved bearer token?

**Comment by jmprieur** [comment]
@Rookian, yes. but the chained token credentials don't use the same credentials (once is a Client Cred, the other is you as a user, who was granted access to the resources).

For the moment, you need to cache the token. In the near future the Azure SDK will do it for you (leveraging MSAL)

**Comment by Rookian** [comment]
Coming back again to my scenario.

I would like to use Managed Identity to call a protected Web API.
For this I have created a small example solution where I have a client WebApp (deamon, unprotected) and a server Web App (protected). I always want to be able to run my code from my local machine and from Azure.
For now I have used Azure.Identity to acquire the token. Everything is working fine.

Now I would like to test Microsoft.Identity.Web and I already stumbled over `AddMicrosoftIdentityWebApiAuthentication` where I need to pass in `IConfiguration`. I guess this is used for the WebAPI itself where it acts as a server, but I have a daemon app.

```csharp
builder.Services.AddMicrosoftIdentityWebApiAuthentication(builder.Configuration)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddInMemoryTokenCaches()
    .AddDownstreamWebApi("ServerWebApp", x =>
    {
        x.Scopes = "api://{appId}/.default";
        x.BaseUrl = "https://localhost:7214/"
    });

...

var response = await api.CallWebApiForAppAsync("ServerWebApp", options =>
{
    options.HttpMethod = HttpMethod.Get;
    options.RelativePath = "/test";
});

```
`CallWebApiForAppAsync` throws an exception "IDW10106: The 'ClientId' option must be provided. "

**Comment by bgavrilMS** [comment]
@jmprieur - should we use this issue to track the Managed Identity integration?

**Comment by jmprieur** [comment]
In the case of Id.Web, the debuggability of the app is important, and therefore we shouldn't use MSAL.NET directly for this feature (but use AzureDefaultCredentials)

For the workload identity federation with Managed identity, we should use MSAL.NET directly, and move the code to MSAL as it doesn't depend on anything else than Ms.Id.Abstractions

**Comment by scottjohnstone** [comment]
Thank you for bringing this to light  @Rookian and @jmprieur 
As part of this effort, documentation around IDownstreamApi wrt/protected API & user+system managed id scenarios should be improved, especially the usage scenarios described at the top.  The following docs dance around the subject without providing E2E guidance/examples, creating confusion regarding capabilities and use cases reducing adoption:
•	[Tutorial - .NET Web app accesses Microsoft Graph as the app - Azure App Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-app?tabs=azure-powershell#grant-access-to-microsoft-graph) 
•	[List Azure role assignments using Azure PowerShell - Azure RBAC | Microsoft Learn](https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-list-powershell#list-role-assignments-for-a-managed-identity) 
•	[New-MgServicePrincipalAppRoleAssignment (Microsoft.Graph.Applications) | Microsoft Learn](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.applications/new-mgserviceprincipalapproleassignment?view=graph-powershell-1.0) 
•	[Tutorial - .NET Web app accesses Microsoft Graph as the app - Azure App Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-app?tabs=azure-powershell#grant-access-to-microsoft-graph) 
•	[Assign Azure roles using Azure PowerShell - Azure RBAC | Microsoft Learn](https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-powershell#next-steps) 
•	[Call Azure AD protected website using Managed Service Identity (MSI) | Microsoft Learn](https://learn.microsoft.com/en-us/archive/blogs/waws/call-azure-ad-protected-website-using-managed-service-identity-msi) 
•	[Protect API in API Management using OAuth 2.0 and Azure Active Directory - Azure API Management | Microsoft Learn](https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad) 
•	[Azure API Management policy reference - authentication-managed-identity | Microsoft Learn](https://learn.microsoft.com/en-us/azure/api-management/authentication-managed-identity-policy) 
•	[active-directory-aspnetcore-webapp-openidconnect-v2/5-WebApp-AuthZ/5-2-Groups/Startup.cs at master · Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 · GitHub](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/5-WebApp-AuthZ/5-2-Groups/Startup.cs) 
•	[v2.0 · AzureAD/microsoft-identity-web Wiki (github.com)](https://github.com/AzureAD/microsoft-identity-web/wiki/v2.0#credentials-are-generalizing-certificates)

**Comment by bgavrilMS** [comment]
@jmprieur @localden - how about this config for MI

## Client Creds Config
```json
"AzureAd": {
        "Instance": "https://login.microsoftonline.com/",
        "TenantId": "[Enter here the tenantID or domain name for your Azure AD tenant]",
        "ClientId": "[Enter here the ClientId for your application]",
        "ClientCredentials": [
            {
                "SourceType": "ClientSecret",
                "ClientSecret": "[Enter here a client secret for your application]"
            }
        ]
    }
```

## MSI Config

```json
"AzureAd": {
        "ManagedIdentity": {
                "SystemAssigned": true
        }
    }
```
```json
"AzureAd": {
        "ManagedIdentity": {
                "UserAssignedClientId": <GUID>
        }
    }
```

**Comment by jmprieur** [comment]
@bgavrilMS, I would use the same as what is done for the other usages of Managed identity in Microsoft.Identity.Web today (for instance for workload identity federation): When it's system assigned, don't even mention it. When it's user assigned, I would mention it. And I would use the same properties as today.
(this was agreed with Yordan ...)

Now, this is not enough. This is only some configuration that already exists in Microsoft.Identity.Web. We need to describe the whole end to end. For instance when using ITokenAcquirer, IDownstreamApi, or IAuthorizationHeaderProvided (for app) we need to tell it to use the managed identity instead of acquiring a token with the client credentials.

**Comment by jmprieur** [comment]
Proposed end to end:

## Option 1
- Have authentication scheme sections for the managed identities (similar to the "AzureAd" section), dropping what is not needed. Only required ClientCredentials of type "ManagedIdentity" (new source type), and optionally the user assigned managed identity clientID. See "MSI1" below
- in the downstream API / IAuthorizationProvider options / ITokenAcquirer options, use the "AuthenticationOptionsName" property (which represents the authentication scheme)

```diff
{
    "AzureAd": {
        "Instance": "https://login.microsoftonline.com/",
        "ClientId": "guid"
        "TenantId": "organizations":
        "ClientCredentials": [
            {
                "SourceType": "ClientSecret",
                "ClientSecret": ""
            }
        ],
       }
    },
+   "MSI1":
+   {
+       "ClientCredentials": [
+           {
+               "SourceType": "ManagedIdentity",
+
+                // Optional
+                "ManagedIdentityClientId": "user-assigned-msi"
+            }
+    },

    // Call graph on behalf of the managed identity (client creds only)
    "DownstreamApis": {
        "allUsers": {
            "BaseUrl": "https://graph.microsoft.com/v1.0",
            "RelativePath": "/users",
            "Scopes": [ "https://graph.microsoft.com/.default" ],
            "AcquireTokenOptions" : {
+               "AuthenticationOptionsName": "MSI1"
             }
         }
       }
}
```

## Option 2.
Like Option 1, but no new SourceType. Rather a value "System-Assigned" for "ManagedIdentityClientId" (which would be mandatory).


```diff
{
    "AzureAd": {
        "Instance": "https://login.microsoftonline.com/",
        "ClientId": "guid"
        "TenantId": "organizations":
        "ClientCredentials": [
            {
                "SourceType": "ClientSecret",
                "ClientSecret": ""
            }
        ],
       }
    },
+   "MSI1":
+   {
+       "ClientCredentials": [
+           {
-               "SourceType": "ManagedIdentity",
-                // Optional
+                "ManagedIdentityClientId": "System-Assigned"
+            }
+    },

    // Call graph on behalf of the managed identity (client creds only)
    "DownstreamApis": {
        "allUsers": {
            "BaseUrl": "https://graph.microsoft.com/v1.0",
            "RelativePath": "/users",
            "Scopes": [ "https://graph.microsoft.com/.default" ],
            "AcquireTokenOptions" : {
+               "AuthenticationOptionsName": "MSI1"
             }
         }
       }
}
```

# Option 3
Change the [AcquireTokenOptions](https://learn.microsoft.com/dotnet/api/microsoft.identity.abstractions.acquiretokenoptions?view=msal-model-dotnet-latest) to add the notion of Managed identity

```diff
    "DownstreamApis": {
        "allUsers": {
            "BaseUrl": "https://graph.microsoft.com/v1.0",
            "RelativePath": "/users",
            "Scopes": [ "https://graph.microsoft.com/.default" ],
            "AcquireTokenOptions" : {
+               "UseManagedIdentity": ""
             }
         }
       }
```

and 

```diff
    "DownstreamApis": {
        "allUsers": {
            "BaseUrl": "https://graph.microsoft.com/v1.0",
            "RelativePath": "/users",
            "Scopes": [ "https://graph.microsoft.com/.default" ],
            "AcquireTokenOptions" : {
+               "UseManagedIdentity": "system-assigned-managed-identity"
             }
         }
       }
```

**Comment by localden** [comment]
(3) looks like the most straightforward @jmprieur

**Comment by jmprieur** [comment]
@localden : and I think that this would be compatible with SLC.
Today, MSI knows the authority to get the token from. With SLC, will there be a need to specify it?

**Comment by jmprieur** [comment]
If we go to 3), the work is:

1. Add `UseManagedIdentity` as a property in [AcquireTokenOptions](https://github.com/AzureAD/microsoft-identity-abstractions-for-dotnet/blob/main/src/Microsoft.Identity.Abstractions/TokenAcquisition/AcquireTokenOptions.cs)
2. In [TokenAcquisition.GetAuthenticationResultForAppAsync](https://github.com/AzureAD/microsoft-identity-web/blob/f2474ba1806fb3f1ad84d8b7637ad7ee3ad74064/src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs#L362), based on `tokenAcquisitionOptions?.UseManagedIdentity`:
     - if null or empty -> do what we do today
     - if "SystemAssignedManagedIdentity": use MSAL to get a token with a system assigned managed identity: see https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/managed-identity#system-assigned-managed-identities
     - if a GUID or resource, to get a token with a user assigned managed identity: https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/managed-identity#user-assigned-managed-identities
 
the `resource` would be the scopes without the "./default".


The rest will work normally:
- MSGraph with app permissions
- IDownstreamApi when calling GetForApp
- IAuthorizationHeaderProvider when called on behalf of app

**Comment by jmprieur** [comment]
@bgavrilMS : i'm confused. I thought we had agreed on: https://github.com/AzureAD/microsoft-identity-web/issues/1775#issuecomment-1769864869 ?

no changes the client credentials, but adding parameters to TokenAcquirerOptions?

**Comment by bgavrilMS** [comment]
This is just a naming consistency. The design is agreed. I updated my comment. I would suggest using "ManagedIdentity" insteaed of "UseManagedIdentity".
