### ISSUE TITLE
How to setup DI for bypassing JWT authentication in Developer environment

### ISSUE THREAD

**Issue by bgandhisf** [AzureAD/microsoft-identity-web#178]
I'm using Microsoft.Identity.Web for securing my WebAPI (in ASP.Net core 3.1). In Startup.ConfigureServices, I have below code to use the capabilities provided by this library:

```
    services.AddProtectedWebApi(Configuration);
    services.Configure<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme, options =>
     {
           options.TokenValidationParameters.RoleClaimType = "roles";
     });
```
And then in Configure, I use app.UseAuthentication/app.UseAuthorization middlewares. 
I also have controllers marked with [Authorize] attribute.

This all works fine with my app registered in Azure AD etc.

However, what I want to do on my developer environment (local machine) is that I want to be able to invoke APIs without having to get a Bearer token. Do I need to do anything special in ConfigureServices to do this? What is your recommended way of doing this?

Thank you.

**Comment by jmprieur** [comment]
@bgandhisf 
If you don't want to invoke a bearer token, just remove the [Authorize] attribute.

**Comment by jmprieur** [comment]
Closing as I believe I've answered the question.
Feel free to reopen
