### ISSUE TITLE
[Feature Request] Consider using IHttpClientFactory in DownstreamWebApi

### ISSUE THREAD

**Issue by luismanez** [AzureAD/microsoft-identity-web#1791]
I´m moving some Azure Functions from v3 to v4, and the migration pre-check tool in the Azure portal is raising this warning:

![image](https://user-images.githubusercontent.com/9392197/176361751-b3ece632-028f-48db-8df7-6685ab111b61.png)

Following best practices [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0) I guess the ```DownstreamWebApi```should use the ```IHttpClientFactory```.

**Comment by jmprieur** [comment]
Fixed in rel/v2
the new IDownstreamRestApi injects a IHttpClientFactory

https://github.com/AzureAD/microsoft-identity-web/blob/6c1f5fda4a6bf1eeb14ae37ed6d7d1f58dd30d17/src/Microsoft.Identity.Web.DownstreamRestApi/DownstreamRestApi.cs#L36
