### ISSUE TITLE
[Feature Request] Use `HttpContent` instead of a `StringContent` for input parameters

### ISSUE THREAD

**Issue by Skulblaka** [AzureAD/microsoft-identity-web#1798]
Because `CallWebApiForAppAsync` only accepts an object of type `StringContent` instead of `HttpContent`, I can't use it with `JsonContent.Create`.

Not only is this an inconvenience, it also forces me to completely serialize my payload in-memory which may result in higher memory usage compared to the `Stream`-based implementation of `JsonContent`.

**Comment by jmprieur** [comment]
Thanks for the feedback @Skulblaka

**Comment by jmprieur** [comment]
Fixed in rel/v2
