### ISSUE TITLE
Call user_info endpoint for AAD guest scenarios

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#18]
### Why?

TokenAcquistion.cs has hacks to try to guess guest scenarios. In the case of guest scenarios the home tenant ID, home object id is different from the tenantID, object ID which are provided in the IDToken. But we don't have today the home tid/oid information, and therefore we don't know that this is a guest user. 
MSAL.NET uses the home tenant information, and therefore in the guest scenarios we don't find find the tokens in the cache today (I believe UniqueObjectIdentifier)

https://github.com/AzureAD/microsoft-identity-web/blob/72939218c85f65d42e7d5989e5dffcf0cdee6000/src/Microsoft.Identity.Web/TokenAcquisition.cs#L403-L412

and

https://github.com/AzureAD/microsoft-identity-web/blob/72939218c85f65d42e7d5989e5dffcf0cdee6000/src/Microsoft.Identity.Web/TokenAcquisition.cs#L297-L308

The hypothesis is that we'd want to call the User info endpoint not only for B2C, but also AAD, and get the home tenant ID, home iod, instead of the hack.

### What ?
- Like we do w/B2C, call the user_info endpoint for AAD guest scenarios. Today we test for B2C. We probably want to do the same or similar for AAD.

  https://github.com/AzureAD/microsoft-identity-web/blob/dbb91d6afe1fc8f770a3db2d700789d27ce149d8/src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs#L141-L148

- probably (to be checked) change the GetMsalId method to use the home tenant information?

https://github.com/AzureAD/microsoft-identity-web/blob/27391236c35d037ebcd2e48f5c9a909b6c0e1bbc/src/Microsoft.Identity.Web/ClaimsPrincipalExtensions.cs#L19

- if this is successful, remove the hacks?

### How to test?

- Guest scenarios are only available in single tenant applications (audience = MyOrg). therefore the tenant Id in the config file should be a guid (not common or organizations). This sample could be used https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph with the msidentitytesting tenant signing-in with corporate accounts (as it only requires user.read, which is allowed in the corp tenant).

Otherwise we could add an hotmail account in a test tenant. Alternatively the identity lab will have guest accounts.

**Comment by jmprieur** [comment]
@jennyf19 this would be a good one to take if other issues are not fully spec-ed

**Comment by jennyf19** [comment]
In [0.1.4-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.4-preview)
