### ISSUE TITLE
Add EnablePiiLogging and RedirectUri to MicrosoftAuthenticationOptions.cs

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#1818]
**Why?**
EnablePiiLogging and RedirectUri are not present in [AuthenticationOptions.cs](https://github.com/AzureAD/microsoft-identity-web/blob/rel/v2/src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/ApplicationOptions/AuthenticationOptions.cs) in Microsoft.Identity.Web.TokenAcquisitionAbstraction, wheres they were present in `MicrosoftIdentityOptions`.

We want to replace, in the new DevEx, the `MicrosoftIdentityOptions` by [MicrosoftAuthenticationOptions.cs](https://github.com/AzureAD/microsoft-identity-web/blob/rel/v2/src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/ApplicationOptions/MicrosoftAuthenticationOptions.cs)

**What?**
- [x] Add the 2 options
- [ ] Update [sample-configuration.json](https://github.com/AzureAD/microsoft-identity-web/blob/rel/v2/src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/ApplicationOptions/sample-configuration.json)

**Comment by jmprieur** [comment]
https://github.com/AzureAD/microsoft-identity-web/pull/1819
https://github.com/AzureAD/microsoft-identity-web/pull/1822

**Comment by jmprieur** [comment]
Fixed in rel/v2
