### ISSUE TITLE
[Bug] Manipulate JSON using System.Text instead of Newtonsoft

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-identity-web#182]
**Which Version of Microsoft Identity Web are you using ?**
Note that to get help, you need to run the latest version. 
0.1.3-preview

**Where is the issue?**

While Identity.Web does not reference Newtonsoft.Json directly, but via Wilson, it should rely on System.Text instead. This will make it easier to upgrade to latest Wilson. Also, System.Text is the preferred json serializer in the ASP.NET Core ecosystem.

**Comment by jmprieur** [comment]
We need to fix this before having the templates available in ASP.NET Core.

**Comment by jmprieur** [comment]
Fixed by https://github.com/AzureAD/microsoft-identity-web/pull/188
@pmaytak : in the future, please reference the issues in your PR for traceability

**Comment by pmaytak** [comment]
Fixed in [Microsoft Identity Web 0.1.5-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.5-preview).
