### ISSUE TITLE
DownstreamWebApiSupport infinite redirects on B2C

### ISSUE THREAD

**Issue by Megasware128** [AzureAD/microsoft-identity-web#1826]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.25.1

### Web app

Sign-in users and call web APIs

### Web API

Not Applicable

### Token cache serialization

In-memory caches

### Description

Both AddDownstreamWebApi and AddMicrosoftIdentityUserAuthenticationHandler don't work when building with AAD B2C. Once the api tries to be called, the webpage infinitely tries to challenge consent. I did do a bit of debugging and in both cases the issue seems to be [GetAccountAsync](https://github.com/AzureAD/microsoft-identity-web/blob/b4c2d7ca006f3bbead874863b2527570eb61c083/src/Microsoft.Identity.Web/TokenAcquisition.cs#L949) returning null. I also found workarounds for this, either entirely remove the B2C code path or just replace [this line](https://github.com/AzureAD/microsoft-identity-web/blob/b4c2d7ca006f3bbead874863b2527570eb61c083/src/Microsoft.Identity.Web/DownstreamWebApiSupport/MicrosoftIdentityUserAuthenticationMessageHandler.cs#L51) with just `var userflow = options.UserFlow;` to fix just the MessageHandler. It creates the same result by also ignoring the B2C code path I talked about earlier.

I am not sure but shouldn't the B2C code path just be removed? Because it seems to work correct without it. Why is it there? Is this case related to #1660?

### Reproduction steps

1. Setup B2C
2. Setup an API app with a custom scope
3. Setup a web app with permission for the API app scope
4. Create simple ASP.NET Core app which uses either AddDownstreamWebApi or AddMicrosoftIdentityUserAuthenticationHandler (API won't be necessary because it never gets called because of this bug)

### Error message

fail: Microsoft.Identity.Web.TokenAcquisition[0]
      False MSAL 4.45.0.0 MSAL.NetCore .NET 6.0.7 Microsoft Windows 10.0.22622 [2022-07-26 13:13:26Z] Exception type: Microsoft.Identity.Client.MsalUiRequiredException
      , ErrorCode: user_null
      HTTP StatusCode 0
      CorrelationId

         at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)

### Relevant code snippets

```csharp
builder.Services.AddHttpClient<swaggerClient, swaggerClient>(client =>
{
    client.BaseAddress = new Uri(builder.Configuration["DownstreamApi:BaseUrl"]);
    return new swaggerClient(client.BaseAddress.ToString(), client);
})
.AddMicrosoftIdentityUserAuthenticationHandler("DownstreamApi", builder.Configuration.GetSection("DownstreamApi"));
```

### Expected behavior

Consent should be challenged just ones.

**Comment by jmprieur** [comment]
Thanks @Megasware128 
@jennyf19: I wonder if we shouldn't use the user flow in this line:

https://github.com/AzureAD/microsoft-identity-web/blob/b4c2d7ca006f3bbead874863b2527570eb61c083/src/Microsoft.Identity.Web/TokenAcquisition.cs#L949

**Comment by jennyf19** [comment]
@Megasware128 does this repo in the 2.x version?

**Comment by Megasware128** [comment]
@jennyf19 I'll take a look later today or tomorrow. You'll hear my findings!

**Comment by jennyf19** [comment]
@Megasware128 any update? Please reopen if the issue still persists. Thanks!
