### ISSUE TITLE
[Bug] "GetAccessTokenForUser" fails when most recent token was not obtained through the signin policy

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#184]
Reported in [sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/357)

**Comment by jmprieur** [comment]
@jennyf19 would it be a duplicate of https://github.com/AzureAD/microsoft-identity-web/issues/27 ?

**Comment by jennyf19** [comment]
duplicate of this one: https://github.com/AzureAD/microsoft-identity-web/issues/138
