### ISSUE TITLE
[Feature Request] Support web app scenario for ASP.NET classic / OWIN 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-identity-web#1843]
Id.Web provides higher level APIs for ASP.NET Core. This is a request to add support for ASP.NET classic.

**Comment by bgavrilMS** [comment]
For website scenario, for using client_info, I have a PR in our ASP.NET sample https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect/pull/76/files

**Comment by jmprieur** [comment]
Thanks @bgavrilMS. yes, we had seen :-)

**Comment by jmprieur** [comment]
Fixed in rel/v2.
