### ISSUE TITLE
[Bug] Significant performance decrease after updating Microsoft.Identity.Web from 1.16.0 to 1.25.1

### ISSUE THREAD

**Issue by macchmie3** [AzureAD/microsoft-identity-web#1844]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.25.1

### Web app

Not Applicable

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

Not Applicable

### Description

Performance of our APIs got significantly decreased after changing nuget version of Microsoft.Identity.Web from 1.16.0 to 1.25.1. APIs are hosted in Azure. This was **the only single change between deployments**. We updated the package in 2 of our applications. They have different traffic, but both were affected. It's worth mentioning that both apps didnt see any noticible differences in CPU/Memory usage.  App service plans had pre/post deployment CPU usage below 50% and memory usage below 60%.

App with bigger traffic:
![Bigger traffic app](https://user-images.githubusercontent.com/12615493/185396153-46a78374-e0cb-43f6-b1ef-23056aedf57b.png)

App with lesser traffic:
![Lesser traffic app](https://user-images.githubusercontent.com/12615493/185396190-a601bd20-6e03-4f89-b111-f720e98e57d3.png)

As you can see on the graph the request count is quite stable over time.
**Reverting nuget package back to 1.16.0** fixed the problem immidiately.

### Reproduction steps

I have linked how we configure the app and the versions.

### Relevant code snippets

```csharp
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApi(options =>
            {
                options.Events = new JwtBearerEvents
                {
                    OnMessageReceived = (context) => {
                        StringValues values;

                        if (!context.Request.Query.TryGetValue("access_token", out values))
                        {
                            return Task.CompletedTask;
                        }

                        if (values.Count > 1)
                        {
                            context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                            context.Fail(
                                $"Only one 'access_token' query string parameter can be defined. " +
                                $"However, {values.Count:N0} were included in the request."
                            );

                            return Task.CompletedTask;
                        }

                        var token = values.Single();

                        if (String.IsNullOrWhiteSpace(token))
                        {
                            context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                            context.Fail(
                                $"The 'access_token' query string parameter was defined, " +
                                "but a value to represent the token was not included."
                            );

                            return Task.CompletedTask;
                        }

                        context.Token = token;

                        return Task.CompletedTask;
                    }
                };
                options.TokenValidationParameters.ValidAudiences = new List<string>{"RedactedValue"};
                options.TokenValidationParameters.ValidateIssuer = false;
                options.TokenValidationParameters.SaveSigninToken = true;
            }, options =>
            {
                options.TenantId = "RedactedValue";
                options.Instance = "RedactedValue";
                options.ClientId = "notUsed";
            }, "AzureADBearer");
```

### Regression

1.16.0

### Expected behavior

Performance of the app should not be significantly decreased after changing nuget version from 1.16.0 to 1.25.1

**Comment by jmprieur** [comment]
Thanks @macchmie3. We'll investigate.

**Comment by jmprieur** [comment]
@macchmie3 : I've a few questions about your code (un-related to the performance regression):
- why do you use Microsoft.Identity.Web if you are setting everything yourself? It seems AddJwtBearer would work better in your scenario if you handle the token yourself?
- did you see how to use Microsoft.Identity.Web for web APIS? : https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis

**Comment by macchmie3** [comment]
@jmprieur 

Thanks for the links. 99,99% of our traffic goes through tokens received in headers so not block for query parameters were required, but we also use signalR and some client libraries are not able to connect to signalR hub and send token in a header, so they need to do it through query parameter.  Before we started using signalR the setup was without  `OnMessageReceived` event subscription

**Comment by macchmie3** [comment]
Hi, do you have any information if this performance issue has been fixed in newer versions of the library?

**Comment by jmprieur** [comment]
Fixed in rel/v2.
