### ISSUE TITLE
RefreshToken not being cached from 1.20.1 version

### ISSUE THREAD

**Issue by luismanez** [AzureAD/microsoft-identity-web#1846]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.TokenCache

### Microsoft.Identity.Web version

1.20.1

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Distributed caches

### Description

I'm using Distributed Token cache from MS Identity Web. However, from 1.20.1 version, the refresh token is not being stored in the Cache anymore (tested with SQL SRV and Redis Cache). Exactly same code with MS Identity Web 1.20.0 version, works as expected, and I can see the refresh token stored in cache. I´ve realised about this here: https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/issues/11#issuecomment-1218063916 but the issue is in this library, or MSAL!

I´ve been having a look to the changes between 1.20.0 and 1.20.1, and the only relevant thing I can see is that the version of MSAL (Microsoft.Identity.Client) has been upgraded, so it might be an issue on MSAL side...

### Reproduction steps

Add MS identity web packages in any version higher than 1.20.0:

```
	<PackageReference Include="Microsoft.Identity.Web" Version="1.25.1" /> 
	<PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="1.25.1" />
```

Create a .net 6 web api secured like:

```c#
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
          .AddMicrosoftIdentityWebApi(builder.Configuration)
            .EnableTokenAcquisitionToCallDownstreamApi(options => { builder.Configuration.Bind("AzureAd", options); })
               .AddMicrosoftGraph(builder.Configuration.GetSection("MicrosoftGraph"))
            .AddDistributedTokenCaches();
```

I´m using SQL Server cache (but also tested using Redis cache with same result)

```c#
builder.Services.AddDistributedSqlServerCache(options =>
{
    options.ConnectionString = builder.Configuration.GetConnectionString(
        "BudgieContext");
    options.SchemaName = "dbo";
    options.TableName = "DistributedCache";
});
```
Then I have an API controller that gets the _GraphServiceClient_ and just calls the _Me_ endpoint:

```c#
[HttpGet("me")]
    public async Task<IActionResult> GetGraphMe()
    {
        var meData = await _graphServiceClient.Me.Request().GetAsync();
        
        return Ok(new
        {            
            meData.Id,
            meData.DisplayName,
            meData.UserPrincipalName
        });
    }
```

I´m using Postman to get a valid oAuth2 token and I´m able to call the API properly and get Graph Me information.

However, if I take a look to the SQL Cache table, I can see the user´s entry, but when I take a look to the data store, the RefreshToken is not cached:

![image](https://user-images.githubusercontent.com/9392197/185573003-88ba7a10-a140-4732-ae1f-332c57dd1508.png)

Now, if you downgrade MS Identity web packages to __1.20.0__, the refresh token is being cached as expected:

![image](https://user-images.githubusercontent.com/9392197/185573804-84927939-1872-4180-97fc-f467359bfa39.png)

### Relevant code snippets

```csharp
Already present in repro steps

#
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
          .AddMicrosoftIdentityWebApi(builder.Configuration)
            .EnableTokenAcquisitionToCallDownstreamApi(options => { builder.Configuration.Bind("AzureAd", options); })
               .AddMicrosoftGraph(builder.Configuration.GetSection("MicrosoftGraph"))
            .AddDistributedTokenCaches();
```

### Regression

1.20.0

### Expected behavior

The refresh token is present in the distributed cache store.

**Comment by luismanez** [comment]
Not sure if this helps, but I´ve created my custom __TokenCacheAdapter__ inheriting the one from MS Identity web __MsalDistributedTokenCacheAdapter__, and overwritting all its methods, just for debugging purposes. The method that writes into the cache sql table looks like:

```c#
protected override Task WriteCacheBytesAsync(string cacheKey, byte[] bytes, CacheSerializerHints cacheSerializerHints)
    {
        var str = System.Text.Encoding.Default.GetString(bytes);
        return base.WriteCacheBytesAsync(cacheKey, bytes, cacheSerializerHints);
    }
```

I set a breakpoint in that method to debug the byte array value, and the refresh token is not there, so, unless I´m missing something, I´d say this seems more an __MSAL__ bug...

/cc @bgavrilMS

**Comment by jennyf19** [comment]
@luismanez If you need the RT in the OBO scenario, then you would fall into the long running process category, which is [described here](https://github.com/AzureAD/microsoft-identity-web/wiki/get-token-in-event-handler#how-to-get-an-obo-token-in-an-event-handler-or-a-long-running-process). This is by design and the change was intended (security).

**Comment by luismanez** [comment]
Thanks @jennyf19 for coming to the rescue!! 
I see. If that´s the case, just a couple of question/comments:

- The sample here (https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache) then is not valid anymore, right? (at least the OBO sample). Maybe a note in the readme should be done.
- Is it documented that MSAL is not storing the Refresh token for OBO flow?
- The long running process approach, will work in an Azure Function (background process)? I´m asking cos my understanding is that the code in __Callback__ controller would go into the Az Function, but I don´t know if this call will work in a background process: ```tokenAcquisition.GetAuthenticationResultForUserAsync(...)``` Basically, my scenario is exactly the one in the previous sample that is not valid anymore...

Thanks again.

**Comment by luismanez** [comment]
Answering myself, in case anyone has the same questions:

- Previous sample is not valid anymore, at least if you´re using latest MSAL version (this is not actually related to MS Identity web, is more an MSAL thing improving security)
- I haven´t found any specific official doc saying Refresh token is not stored for OBO flow. I found some issues in MSAL repo where someone said something about it. Also, this official doc from MSAL explains the supported Long running scenario: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of#long-running-obo-processes
- I can confirm it works in an Azure Function (background process). In my scenario, an API endpoint fires the long running process using MS Identity Web and this code:

```c#
TokenAcquisitionOptions tokenAcquisitionOptions = new TokenAcquisitionOptions()
            {
                LongRunningWebApiSessionKey = keyHint ?? TokenAcquisitionOptions.LongRunningWebApiSessionKeyAuto
            };

            _= await _tokenAcquisition.GetAuthenticationResultForUserAsync(new string[] { "user.read" }, 
                    tokenAcquisitionOptions: tokenAcquisitionOptions);
```                    
and then in an Azure Function, using MSAL (MS Identity Web does not work well in background scenarios. I know the team is working to make it work, and likely will be available in next release), I´m able to get the delegated token with a snippet like:

```c#
var authResult = await ((ILongRunningWebApi)confidentialClientApp)
         .AcquireTokenInLongRunningProcess(
              scopes,
              provisioningQueueMessage.OperationId)
         .ExecuteAsync();
```
The important part here, is that when building the _ConfidentialClientApplication_, you have to use the same AAD App, that the one in the API that fired the long running process.

Hope it helps.
