### ISSUE TITLE
Get Access Token For App later than v1.16.1

### ISSUE THREAD

**Issue by Pmr-precure** [AzureAD/microsoft-identity-web#1857]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.16.1

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

Hi,

Im using TokenAcquisition.GetAccessTokenForApp to get my access token for the powerbi API, and everything is working perfectly. But when updating the packet to 1.6.1 + then i get hit with the same error message:
![image](https://user-images.githubusercontent.com/99671597/186996355-8409a065-1a64-42fd-9c35-a1c74e78f0c0.png)

If i downgrade to 1.6.0 then i have no problems.

### Reproduction steps

Upgrade to 1.6.1 or more.

### Error message

Microsoft.Identity.Client.MsalClientException: 'One client credential type required either: ClientSecret, Certificate, ClientAssertion or AppTokenProvider must be defined when creating a Confidential Client. Only specify one. See https://aka.ms/msal-net-client-credentials. '

### Relevant code snippets

```csharp
// In startup.cs   
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration, "ServicePrincipalApp")
                .EnableTokenAcquisitionToCallDownstreamApi().AddInMemoryTokenCaches();

//Trying to get token
await _tokenAcquisition.GetAccessTokenForAppAsync(_configuration["PowerBi:DefaultScope"]);
```

### Regression

1.16.0

### Expected behavior

Not throwing a error about not having a client secret.

**Comment by Pmr-precure** [comment]
Sorry i see i wrote 1.6.x, i ofc mean 1.16.x

**Comment by Mehdi-Panjwani** [comment]
Hi, any update on this? I am facing this same problem. Why is a client secret even needed in this scenario?

```
    public SomeController(GraphServiceClient graphServiceClient)
    {
        _graphServiceClient = graphServiceClient;
    }
    public async Task<IActionResult> SomeAction() {
        var me = await _graphServiceClient.Me.GetAsync();
    }
```

```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(configuration.GetSection("AzureAd"))
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddMicrosoftGraph(options =>
    {
        options.BaseUrl = "https://graph.microsoft.com/v1.0";
        options.Scopes = ["https://graph.microsoft.com/.default"];
    })
    .AddInMemoryTokenCaches();
```

```
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "xxxx.onmicrosoft.com",
    "TenantId": "xxxxxxxxxxxxxxxxxxxxxxx",
    "ClientId": "xxxxxxxxxxxxxxxxxxxxxxxxx",
    "Audience": "https://xxxxx.xxx.xx,
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc"
  }
```

**Comment by Pmr-precure** [comment]
> Hi, any update on this? I am facing this same problem. Why is a client secret even needed in this scenario?
> 
> ```
>     public SomeController(GraphServiceClient graphServiceClient)
>     {
>         _graphServiceClient = graphServiceClient;
>     }
>     public async Task<IActionResult> SomeAction() {
>         var me = await _graphServiceClient.Me.GetAsync();
>     }
> ```
> 
> ```
> services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
>     .AddMicrosoftIdentityWebApp(configuration.GetSection("AzureAd"))
>     .EnableTokenAcquisitionToCallDownstreamApi()
>     .AddMicrosoftGraph(options =>
>     {
>         options.BaseUrl = "https://graph.microsoft.com/v1.0";
>         options.Scopes = ["https://graph.microsoft.com/.default"];
>     })
>     .AddInMemoryTokenCaches();
> ```
> 
> ```
>   "AzureAd": {
>     "Instance": "https://login.microsoftonline.com/",
>     "Domain": "xxxx.onmicrosoft.com",
>     "TenantId": "xxxxxxxxxxxxxxxxxxxxxxx",
>     "ClientId": "xxxxxxxxxxxxxxxxxxxxxxxxx",
>     "Audience": "https://xxxxx.xxx.xx,
>     "CallbackPath": "/signin-oidc",
>     "SignedOutCallbackPath ": "/signout-callback-oidc"
>   }
> ```

Tbh i cant remember i did, i THINK i had to change the way i received the accessToken. Here is the code i used:

![image](https://github.com/user-attachments/assets/2ecdb213-f7f6-42a7-805a-6ed3a790d16f)

Maybe it helps. 

Br.
