### ISSUE TITLE
Measure performance of rel/v2

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#1869]
**On 1.25.2**
326 ms (cold)
335 ms (warm)

**On rel/v2**
231 ms (cold)
51 ms (warm)

**Comment by jmprieur** [comment]
On rel/v2
Starting test with 1000 users from 1 to 1000 using 2 parallel tasks.
Running for 5 minutes.
------------------------------------------------------------------------
Run time: 9/5/2022 8:36:50 PM - 9/5/2022 8:39:58 PM = 00:03:08.6848702.
Total number of users: 1000 users from 1 to 1000.
Loop: 0
Total requests: 500.
Average request time: 231.3799 ms.
Cache requests: 365.
Average cache time: 3.0436 ms.
AuthRequest failures: 0. Generic failures: 0.

------------------------------------------------------------------------
Run time: 9/5/2022 8:36:50 PM - 9/5/2022 8:40:12 PM = 00:03:22.6659385.
Total number of users: 1000 users from 1 to 1000.
Loop: 1
Total requests: 1000.
Average request time: 125.9079 ms.
Cache requests: 860.
Average cache time: 2.0845 ms.
AuthRequest failures: 0. Generic failures: 0.

------------------------------------------------------------------------
Run time: 9/5/2022 8:36:50 PM - 9/5/2022 8:40:28 PM = 00:03:38.5262218.
Total number of users: 1000 users from 1 to 1000.
Loop: 1
Total requests: 1500.
Average request time: 92.4610 ms.
Cache requests: 1359.
Average cache time: 1.8410 ms.
AuthRequest failures: 0. Generic failures: 0.

------------------------------------------------------------------------
Run time: 9/5/2022 8:36:50 PM - 9/5/2022 8:40:44 PM = 00:03:54.3114444.
Total number of users: 1000 users from 1 to 1000.
Loop: 2
Total requests: 2000.
Average request time: 75.5995 ms.
Cache requests: 1857.
Average cache time: 1.7211 ms.
AuthRequest failures: 0. Generic failures: 0.

------------------------------------------------------------------------
Run time: 9/5/2022 8:36:50 PM - 9/5/2022 8:40:59 PM = 00:04:09.7688918.
Total number of users: 1000 users from 1 to 1000.
Loop: 2
Total requests: 2500.
Average request time: 65.4247 ms.
Cache requests: 2355.
Average cache time: 1.6318 ms.
AuthRequest failures: 0. Generic failures: 0.

------------------------------------------------------------------------
Run time: 9/5/2022 8:36:50 PM - 9/5/2022 8:41:15 PM = 00:04:25.7341926.
Total number of users: 1000 users from 1 to 1000.
Loop: 3
Total requests: 3000.
Average request time: 58.8199 ms.
Cache requests: 2854.
Average cache time: 1.5951 ms.
AuthRequest failures: 0. Generic failures: 0.

------------------------------------------------------------------------
Run time: 9/5/2022 8:36:50 PM - 9/5/2022 8:41:33 PM = 00:04:43.8360707.
Total number of users: 1000 users from 1 to 1000.
Loop: 3
Total requests: 3500.
Average request time: 54.6212 ms.
Cache requests: 3352.
Average cache time: 1.5868 ms.
AuthRequest failures: 0. Generic failures: 0.

Processing stopped. Duration elapsed.
------------------------------------------------------------------------
Run time: 9/5/2022 8:36:50 PM - 9/5/2022 8:41:50 PM = 00:05:00.6049769.
Total number of users: 1000 users from 1 to 1000.
Loop: 3
Total requests: 3947.
Average request time: 51.9556 ms.
Cache requests: 3799.
Average cache time: 1.5862 ms.
AuthRequest failures: 0. Generic failures: 0.

------------------------------------------------------------------------
Run time: 9/5/2022 8:36:50 PM - 9/5/2022 8:41:55 PM = 00:05:05.5580280.
Total number of users: 1000 users from 1 to 1000.
Loop: 4
Total requests: 4445.
Average request time: 81.4003 ms.
Cache requests: 4110.
Average cache time: 1.6886 ms.
AuthRequest failures: 0. Generic failures: 0.

**Comment by jennyf19** [comment]
Exit criteria: Common scenario (daemon calls web API) and results are available in App Insights.

**Comment by jennyf19** [comment]
First step is to see how much of SAL perf & stress repo can be re-used for Id Web.

**Comment by jennyf19** [comment]
closing. we will leverage the crank tests we are doing in MIcrosoft.IdentityModel. will open a new issue later for tracking similar work here.
