### ISSUE TITLE
[Bug] : Handle missing roles from "ver":"1.0" tokens

### ISSUE THREAD

**Issue by zaker** [AzureAD/microsoft-identity-web#187]
**Which Version of Microsoft Identity Web are you using ?**
v0.1.0->v0.1.4

**Where is the issue?**
* Web App
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [x] Protected web APIs (Validating tokens)
    * [x] Protected web APIs (Validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In Memory caches
     * [ ] Session caches
     * [ ] Distributed caches

Other? - please describe;

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of Microsoft Identity Web

**Repro**
My App has a legacy client that uses v1.0 tokens, and A newer one that uses v2.0 tokens.
With an upgrade to v0.1.2,3,4 this has stopped accepting the tokens from the legacy app.

**Expected behavior**
Validate tokens from both clients

**Actual behavior**
Throws either Audience not valid(this can be corrected with setting The Audience in the app settings. But then it wants to have scope or roles, but this isnæt available in the jwt comming from the legacy client.

**Possible Solution**
Avoid throwing an error on missing roles/scopes on v1.0 type tokens in the on token validated event handler

**Comment by jmprieur** [comment]
@zaker : can you please provide a repro? or send me the audience of a token that is not accepted ?

**Comment by zaker** [comment]
v1.0 example token anonymized

{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "CtTuhMJmD5M7DLdzD2v2x3QKSRY",
  "kid": "CtTuhMJmD5M7DLdzD2v2x3QKSRY"
}.{
  "aud": "12341234-1234-1234-1234-123412341234", // This gets validated against api://<client_id>
  "iss": "https://sts.windows.net/12341234-1234-1234-1234-123412341234/",
  "iat": 1591084879,
  "nbf": 1591084879,
  "exp": 1591088779,
  "aio": "asdfasdfasdfasdfas==",
  "amr": [
    "pwd",
    "mfa"
  ],
  "family_name": "memememe",
  "given_name": "MeMe",
  "ipaddr": "10.0.0.1",
  "name": "MeMe memememe",
  "nonce": "12341234-1234-1234-1234-123412341234",
  "oid": "12341234-1234-1234-1234-123412341234",
  "onprem_sid": "S-1-5-21-....",
  "sub": "abcds",
  "tid": "12341234-1234-1234-1234-123412341234",
  "unique_name": "me@mail.com",
  "upn": "me@mail.com",
  "uti": "abcd",
  "ver": "1.0"
}

**Comment by jmprieur** [comment]
@zaker and you wrote the regression happened in 0.1.1? or 0.1.4?

**Comment by zaker** [comment]
I was using the 0.1.0 version, but the regression happened when i upgraded to 0.1.3, but I've tried the versions 0.1.2 0.1.3 and 0.1.4.. It validates the token if I in the appSettings set "AzureAD:Audience":"12341234-1234-1234-1234-123412341234", but then it fails after validation with a "Neither scope or roles claim was found in the bearer token." error since it is no roles or scope in the token. This causes the API to serve A 500 StatusCode.

**Comment by jmprieur** [comment]
@zaker 
It's odd that you don't have a scope. Doesn't your API accepting v1.0 token define an OAuth2.0 permission (for instance user_impersonation): that's the same as a scope in v2.0?

Or would it be an API accepting daemon applications? (https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-verification-scope-app-roles#verify-app-roles-in-apis-called-by-daemon-apps) but I don't see roles either.

Would it be an ID token? 
how did you acquire it? with which library/authority?

**Comment by zaker** [comment]
It looks as if the legacy app uses id_tokens. That would explain a lot, we've let that app live it's own life for a while. Thanks for pointing me in the right direction, this will now need to be handled by office politics.

**Comment by jmprieur** [comment]
@zaker

Yes. IDToken won't contain roles. 
You could always override OnTokenReceived but this is not a great practice to send IDTokens to the Web APIs.

Do we want to close this issue?

**Comment by zaker** [comment]
Yes. I'm satisfied.
