### ISSUE TITLE
[Feature Request] Log L1/L2 cache details to TokenCacheNotificationArgs

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-identity-web#1900]
Add L1/L2 cache details to TokenCacheNotificationArgs once the cache details parameter is available from MSAL. This will be available when we release MSAL 4.48.0.

This will involve adding which cache was used L1/L2 to fetch the token. 
MSAL already captures cache latency.

Ref: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3596
PR to add cache details in MSAL: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3737

**Comment by jmprieur** [comment]
In 2.13.4

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.13.4
