### ISSUE TITLE
Cannot acquire API access token for B2C Reset Password policy

### ISSUE THREAD

**Issue by grzegorzy** [AzureAD/microsoft-identity-web#191]
I don't know if this is really a bug or perhaps it's a result of my lack of knowledge about the library and B2C in general. Here are the details:

Microsoft Identity Web 0.1.4-preview

**Where is the issue?**
* Web App
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (Validating tokens)
    * [ ] Protected web APIs (Validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In Memory caches
     * [ ] Session caches
     * [ ] Distributed caches

**Is this a new or existing app?**
This is a new app or experiment.

**Repro**
1. Create a new web app based on the "IndividualB2C" template.
2. Create a new web api based on the "IndividualB2C" template.
3. Register both applications in the Azure AD B2C Tenant.
4. Expose API with some scope for the second app registration.
5. Apply delegated API permissions for the first app registration. Grant admin consent.
6. Call the protected API from the web application
7. Sign in via SUSI policy -> Access token acquired, call to the protected API succeeded
8. Sign in via Reset Password policy -> Access token not acquired, call to the protected API failed

**Expected behavior**
Web application should be able to access the protected API when the Reset Password policy is used.

**Actual behavior**
Web application is not able to access the protected API when the Reset Password policy is used.

**Possible Solution**
I see the following code in the `AzureADB2COpenIDConnectEventHandlers` class:

```csharp
public Task OnRedirectToIdentityProvider(RedirectContext context)
{
	var defaultUserFlow = Options.DefaultUserFlow;
	if (context.Properties.Items.TryGetValue(OidcConstants.PolicyKey, out var userFlow) &&
		!string.IsNullOrEmpty(userFlow) &&
		!string.Equals(userFlow, defaultUserFlow, StringComparison.OrdinalIgnoreCase))
	{
		context.ProtocolMessage.Scope = OpenIdConnectScope.OpenIdProfile;
		context.ProtocolMessage.ResponseType = OpenIdConnectResponseType.IdToken;
		context.ProtocolMessage.IssuerAddress = BuildIssuerAddress(context, defaultUserFlow, userFlow);
		context.Properties.Items.Remove(OidcConstants.PolicyKey);
	}

	return Task.CompletedTask;
}
```

If my understanding is correct, when user signs in into the app via a policy other than the default one (susi most probably) then the above code replaces scope and response type values. In my case response type "code id_token" is replaced with "id_token". The same thing happens with the scope. I assume that the code does it deliberately and there is a reason for that. But I guess that is why I cannot call API when I sign in via Reset Password policy.

**Comment by jmprieur** [comment]
@grzegorzy 
We are working on delivering support for certificates, and then the following release will be about improving the B2C scenarios. The issues we are looking at, related to B2C are the following: https://github.com/AzureAD/microsoft-identity-web/labels/b2c

I believe that when we have done the following enhancement, this should fix your issue: https://github.com/AzureAD/microsoft-identity-web/issues/27

Proposing to label this issue as a duplicate. Please tell me if you disagree.
cc: @jennyf19

**Comment by grzegorzy** [comment]
Thank you for the response. I agree that this will probably fix my issue. I am looking forward to the B2C related release! :+1:

**Comment by jmprieur** [comment]
Closing a duplicate.
