### ISSUE TITLE
[Feature Request] Add an ASP.NET Core 5.0 target

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#194]
**Is your feature request related to a problem? Please describe.**
In order for Microsoft.Identity.Web to be referenced by the ASP.NET Core template, we need to support .NET Core 5.0

**Describe the solution you'd like**
- Just add a target framework in the project.
- From that moment, developer environments and build will need to reference the SDK 5.0.x.
- Update the wiki to express the fact that MIcrosoft.Identity.Web supports .NET 5.0
- Update the project templates

See:
- https://dotnet.microsoft.com/download/dotnet/5.0
- possibly https://dotnet.microsoft.com/download/dotnet-core/scripts for the builds (might not be needed)

To be able to build in Visual Studio enable preview options (Tools | Options | Environment| Preview features | Use previews of the .NET Core SDK (requires restart)

![image](https://user-images.githubusercontent.com/13203188/84913685-140d2480-b0bb-11ea-836c-ef6c547e381e.png)

Jenny found this explaining more about .NET 5.0:
https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
