### ISSUE TITLE
Where can I find the URL of getting token from Azure AD?

### ISSUE THREAD

**Issue by DaemonWalker** [AzureAD/microsoft-identity-web#1950]
Hi guys,

Currently, we want to create a project with react web app and .net core web API. and we want to put call azure AD at backend because of safety.

I found SDK for web API, but it doesn't provide methods like calling an OpenId server, so we want to make it with IdentityClient, how can I find the URL for get code and token?

**Comment by jmprieur** [comment]
I don't understand your question, @DaemonWalker.
ASP.NET Core and Microsoft.Identity.Web do it for you.

Where would you use this URL? a web API is not a web app. But you can have a service which is both

**Comment by DaemonWalker** [comment]
Hi @jmprieur 
Sorry for the inconvenience, I have found the guide for Azure Active Directory Oauth2.0 flow.
By the way, the question was I have a react web app and a .net core web API, is there's any .Net WebAPI SDK for Oauth2.0 flow?
Forgive my poor English T_T

**Comment by jmprieur** [comment]
yes, @DaemonWalker: this would be Microsoft.Identity.Web (This library)
See https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis

**Comment by DaemonWalker** [comment]
Understood, great appreciate @jmprieur!
I'll close the issue
