### ISSUE TITLE
[Bug] Under CallWebApiForAppAsync hardcoded scope in ManagedIdentityClientAssertion

### ISSUE THREAD

**Issue by konradZi** [AzureAD/microsoft-identity-web#1953]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.CertificateLess

### Microsoft.Identity.Web version

1.25.5

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Not Applicable

### Description

In Certificateless approach, there is hardcoded scope in ManagedIdentityClientAssertion.  From my understanding, it should be configurable.

### Reproduction steps

Locally. Login through VS or AZ CLI to Azure.
Set  

  "ClientCredentialsUsingManagedIdentity": {
      "IsEnabled": true
    }

in app settings. 

Call protected API from a protected app with CallWebApiForAppAsync. You will get an error that you don't have credentials.

### Relevant code snippets

```csharp
var response = await _downstreamWebApi.CallWebApiForAppAsync("MyApi", config => { config.HttpMethod = HttpMethod.Post; }, content: new StringContent(val));

  "ClientCredentialsUsingManagedIdentity": {
      "IsEnabled": true
    }

in app settings.
```

### Expected behavior

I should be able access my protected API with signed user in CLI or VS.

**Comment by jmprieur** [comment]
@konradZi 
your requirement is a bit different. you'd like Id.Web to use the token acquired with Azure SDK to call your downstream web API. What the feature you attempted to use does is use the token acquired specifically from Managed identity (deployed in a compute environment supporting Managed Identity) as a signed assertion which is presented as client credentials (it's an alternative to certificates)
