### ISSUE TITLE
Protecting Web API with Azure B2C Throws a Bearer error="invalid_token" With Insufficient Log Information.

### ISSUE THREAD

**Issue by jenergm** [AzureAD/microsoft-identity-web#1959]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.25.0

### Web app

Not Applicable

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

Not Applicable

### Description

Dear all,

We had 2 applications registered in Azure B2C.
* Daemon Application (for ClientId and Client Secret)
* Web API Application

Application Daemon is just to get a Access Token that have grant access to the other Web API .NET 6.
We can get access_token properly using Postman for our tests with the following informations:
1. POST  >> https://login.microsoftonline.com/{{tenant}}/oauth2/v2.0/token
2. BODY >> x-www-form-urlencoded
> > client_id: {{guid-daemon-application}}
> > scope: https://b2c.company.com/{{web-api-application-id}}/.default
> > client_secret: {{guid-daemon-application-secret}}
> > grant_type: client_credentials

We had set our Web API with data provide from Azure B2C (Web API Application)
**Startup.cs**
-> ConfigureServices method
`services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd");
IdentityModelEventSource.ShowPII = true;`
-> Configure method
`app.UseAuthentication();
app.UseAuthorization();`

### Reproduction steps

1. Register a Daemon Application in Azure B2C to get client_secret.
2. Register a Web API Application in Azure B2C to your .NET Core 6 Web API.
3. Grant permission to the Daemon Application to access the Web API Application in Azure B2C.
4. Get access_token using Postman to your Daemon Application.
5. Try call your Web API using the access_token.

### Error message

We got from Postman just this error:

**WWW-Authenticate:** Bearer error="invalid_token"

### Id Web logs

We didn't see any problem in .NET Logs.
**Note:** For security issues, the log bellow we use {{variable}} but in fact is the values.

info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      Microsoft.IdentityModel Version: 6.25.0.0. Date 11/09/2022 17:30:50. PII logging is ON, do not use in production. See https://aka.ms/IdentityModel/PII for details.
      IDX10242: Security token: '{{access_token}}' has a valid signature.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10239: Lifetime of the token is valid.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10234: Audience Validated.Audience: 'https://b2c.company.com/{{guid-web-api}}'
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10245: Creating claims identity from the validated token: '{"typ":"JWT","alg":"RS256","x5t":"2ZQpJ3UpbjAYXYGaXEJl8lV0TOI","kid":"2ZQpJ3UpbjAYXYGaXEJl8lV0TOI"}.{"aud":"https://b2c.company.com/{{guid-web-api}}","iss":"https://sts.windows.net/{{tenant_id}}/","iat":1668014713,"nbf":1668014713,"exp":1668018613,"aio":"{{aio}}","appid":"{{guid-web-api}}","appidacr":"1","idp":"https://sts.windows.net/{{tenant_id}}/","oid":"{{oid}}","rh":"{{rh}}","sub":"{{sub}}","tid":"{{tenant_id}}","uti":"qzap3PZd0Uqk3mPqCpQSAg","ver":"1.0"}'.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10241: Security token validated. token: '{{access_token}}'.

### Relevant code snippets

```csharp
**Startup.cs**
-> ConfigureServices method
`services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd");
IdentityModelEventSource.ShowPII = true;`
-> Configure method
`app.UseAuthentication();
app.UseAuthorization();`

**appsettings.json**
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "company.com",
    "TenantId": "00000000-5ad2-4d22-9369-000000000000",
    "ClientId": "00000000-1655-4e8e-93c7-000000000000",
    "Scopes": "https://b2c.company.com/00000000-1655-4e8e-93c7-000000000000/.default",
    "Audience": "https://b2c.company.com/00000000-1655-4e8e-93c7-000000000000"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}
```

### Expected behavior

Results successfully.

**Comment by jmprieur** [comment]
@jenergm 
For a B2C application the authority should not be [https://login.microsoftonline.com/{{tenant}}/oauth2/v2.0/token]

but something like https://domain.b2clogin.com/domain/policy

**Comment by jmprieur** [comment]
@jenergm: do you have some documentation about B2C web APIs?
I don't understand why their authority would be an AAD authority.

What authority (instance/tenant) do you use in the configuration of your B2C web API?

**Comment by jenergm** [comment]
Hi @jmprieur,

Now my Web API B2C works properly.

Here is the correct code.

    \****************************************************** Startup.cs ******************************************************\
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.Audience = Configuration["AzureAD:ClientId"];
                    options.Authority = $"https://login.microsoftonline.com/{Configuration["AzureAD:TenantId"]}";
                    options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                    {
                        ValidAudience = $"https://b2c.company.com/{Configuration["AzureAD:ClientId"]}",
                        ValidIssuer = $"https://login.microsoftonline.com/{Configuration["AzureAD:TenantId"]}/v2.0"
                    };
                });

        services.AddAuthorization(options =>
                {
                    options.DefaultPolicy = new AuthorizationPolicyBuilder()
                        .RequireAuthenticatedUser()
                        .RequireClaim("appid", appid)
                        .Build();
                });
        // appid: is the Azure B2C Guid Daemon Application, that have granted access to call the API.
    ...

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseAuthentication();
        app.UseAuthorization();
    ...

    \*************************************************** appsettings.json ***************************************************\
    "AzureAd": {
        "Instance": "https://login.microsoftonline.com/",
        "Domain": "company.com",
        "TenantId": "00000000-5ad2-4d22-9369-000000000000",
        "ClientId": "00000000-1655-4e8e-93c7-000000000000",
        "Scopes": "https://b2c.company.com/00000000-1655-4e8e-93c7-000000000000/.default",
        "Audience": "https://b2c.company.com/00000000-1655-4e8e-93c7-000000000000"
    },

We keep getting access_token properly using Postman for our tests with the following informations:

    POST >> https://login.microsoftonline.com/{{tenant}}/oauth2/v2.0/token
    BODY >> x-www-form-urlencoded
    client_id: {{guid-daemon-application}}
    client_secret: {{guid-daemon-application-secret}}
    scope: https://b2c.company.com/{{web-api-application-id}}/.default
    grant_type: client_credentials

Thanks for your help!

Best regards,
Jener Garcia Menezes

**Comment by jmprieur** [comment]
Thanks for the update, [energm](https://github.com/jenergm)
Closing the issue
