### ISSUE TITLE
[Feature Request] Project templates should have an option to generate the "call an API" part

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#196]
**Is your feature request related to a problem? Please describe.**
The project templates show how to create a Web app, or a Web api, but they don't show how to introduce the second part: call a downstream API.

**Describe the solution you'd like**
Have 2 more mandator parameters and one optional parameter to the templates:
- calledApi: URL to the API (for instance http://graph.microsoft.com/v1.0/me)
- calledApiScopes: Scopes requested to call the web API
- tokenCacheImplementation: [optional] InMemory, Redis, Sql => to generate the right cache

If these parameters are present:
- the Startup.cs file adds the CallWebApis part and a token cache.

**Describe alternatives you've considered**
None

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
