### ISSUE TITLE
[Feature Request] Add a SendX5c option to help certificate rotation (1P)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#197]
**Is your feature request related to a problem? Please describe.**
MSAL.NET provides an option to send the x5c with the certificate to help certificate rotation (`.WithX5c(true)`), but Microsoft.Identity.Web does not expose it.

**Describe the solution you'd like**
- MicrosoftIdentityOptions has a new boolean property **sendX5c**
- When calling .WithCertificate on the confidential client application, TokenAcquisition also adds a call to .WithSendX5C(microsoftIdentityOptions.sendX5c)

**Describe alternatives you've considered**

**Additional context**

**Comment by pmaytak** [comment]
Included in [Microsoft Identity Web 0.1.5-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.5-preview).
