### ISSUE TITLE
How to silently renew Id Token using AddMicrosoftIdentityWebAppAuthentication to Call Downstream API

### ISSUE THREAD

**Issue by mschaefer-gresham** [AzureAD/microsoft-identity-web#1978]
I am trying to implement the BFF-Gateway pattern (no tokens in the browser) to be used with a React SPA. The BFF is using AddMicrosoftIdentityWebAppAuthentication to handle login and issue a cookie to the SPA. And it is using YARP to proxy api requests to a downstream api. I'm using Azure B2C. Everything works perfectly until the BFF id_token expires in 1 hour. At that point, fetching the downstream api access token via GetAccessTokenForUserAsync (which is called in a piece of middleware) fails:

```
var scope = _configuration["CallApi:ScopeForAccessToken"];
var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(new[] { scope });
ctx.Request.Headers.Add("Authorization", "Bearer " + accessToken);
```

Exception:
```
IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent. 

ResponseBody: {"error":"invalid_grant","error_description":"AADB2C90085: The service has encountered an internal error. Please reauthenticate and try again.\r\nCorrelation ID: 622d6bd6-d06e-4142-86f2-b30a7a17b3b5\r\nTimestamp: 2022-11-25 09:31:23Z\r\n"} 
```

This is effectively the same as [Call Downstream API Without The Helper Class](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-acquire-token?tabs=aspnetcore) example and this [sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C), except that I'm acquiring the access token in middleware, not a controller, so the downstream YARP requests contain the access token. *BTW I get the same error if I do this inside a controller per this example.* And I see no soluton to this in the sample. 

There is a similar question [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1008) which references the sample referenced above, but for the B2C sample I see no solution to this problem.

I also found this [sample](https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect) and this [explanation](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-with-authorization-codes-on-web-apps-MSAL-2.x). But this uses [Microsoft.Owin](https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect/blob/master/WebApp/App_Start/Startup.Auth.cs) to configure auth, not AddMicrosoftIdentityWebAppAuthentication. This looks promising, but is a departure from most examples I see that use Microsoft.Identity.Web.

Can you please point to the correct solution? I need call to be able to call _tokenAcquisition.GetAccessTokenForUserAsync after the id token expires  without asking the user to reauthenticate and/or the SPA to having to reload. 

Feels like this is a very common scenario that isn't documented very well. 

At the moment I am handling this issue in the SPA by catching the exception from MSAL and redirecting back to the login endpoint in the BFF which initiates the challenge. This gets me a new id_token and cookie,  but this is just a temp workaround as it's very disruptive to user to be redirected away from the SPA.

**Comment by jmprieur** [comment]
@mschaefer-gresham : did you see this article?
https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

It should provide you ideas on how to handle your scenario.

**Comment by mschaefer-gresham** [comment]
@jmprieur Thank you. I did read that article, but wasn't sure it was solving the same problem. Is it the [Handling incremental consent or conditional access in web APIs](https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#handling-incremental-consent-or-conditional-access-in-web-apis) section that I should focus on?

**Comment by jmprieur** [comment]
note quite. You are building an ASP.NET Core web app?. You'd want to use this section: https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#handling-incremental-consent-or-conditional-access-in-web-apps

**Comment by mschaefer-gresham** [comment]
Yes, I'm building a webapp, but the example seems to require/assume that you aquire the downstream token (_tokenAcquisition.GetAccessTokenForUserAsync(scopes)) from inside a controller decorated with [AuthorizeForScopes], which "processes the MSAL.NET MsalUiRequiredException to handle conditional access and incremental consent".  

I'm not calling GetAccessTokenForUserAsync(scopes) from inside a controller, but rather inside of middleware (for downstream api requests proxied by YARP). I thought the webAPI example, which handles the exceptions explicity, was more appropriate. Is this incorrect?

If the webApi example definitely won't work, how can I replicate what's happening in the controller with attribute [AuthorizeForScopes] inside of middleware?

**Comment by mschaefer-gresham** [comment]
@jmprieur I've followed the documentation (as best I could) and I am still being forced to re-authenticate when the id token expires in one hour. The call to GetAccessTokenForUserAsync in the controller still fails the same way and doesn't appear to be handled by the [AuthorizeForScopes] attribute. 

Here are the main parts of my setup (note ClientCapabilities):

Configuration:
```
"AzureB2C": {
    "EnablePiiLogging": true,
    "Instance": "my instance",
    "Domain": "my domain",
    "TenantId": "my tenant",
    "ClientId": "my client id",
    "ClientSecret": "my client secret",
    "ClientCapabilities": [ "cp1" ],
    "ClientCertificates": [
    ],
    "CallbackPath": "/signin-oidc",
    "SignUpSignInPolicyId": "my policy",
    "SignedOutCallbackPath": "/signout-callback-oidc"
  },
```

Services:
```
string[]? initialScopes = configuration.GetValue<string>("CallApi:ScopeForAccessToken")?.Split(' ');
var subscribeToEvents =
    configuration.GetValue<bool>("SubscribeToOpenIdConnectMiddlewareDiagnosticsEvents");
services.AddMicrosoftIdentityWebAppAuthentication(
        configuration,
        "AzureB2C",
        OpenIdConnectDefaults.AuthenticationScheme,
        CookieAuthenticationDefaults.AuthenticationScheme,
        subscribeToEvents
    )
    .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
    .AddDistributedTokenCaches();

services.AddDistributedSqlServerCache(options =>
{
    options.ConnectionString = configuration.GetConnectionString("Server");
    options.SchemaName = configuration["TokenCache:SchemaName"];
    options.TableName = configuration["TokenCache:TableName"];
    options.DefaultSlidingExpiration = TimeSpan.FromMinutes(90);
});

TimeSpan expiry = TimeSpan.FromMinutes(90);
services.Configure<MsalDistributedTokenCacheAdapterOptions>(options => { options.SlidingExpiration = expiry;});
```

Controller:
```
[Authorize]
[HttpGet("/test/app-user/me")]
[AuthorizeForScopes(Scopes = new[] { "https://myazureb2cdomain/538376c7-428c-42c5-9c8b-879b50a74a6e/api_access" })] public async Task<IActionResult> AppUserTest()
{
        // Acquire the access token (same as above CallApi:ScopeForAccessToken).
        string[] scopes = new string[]{"https://myazureb2cdomain/538376c7-428c-42c5-9c8b-879b50a74a6e/api_access"};
        
        // This fails when the id token expires
        string accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(scopes);

        // Use the access token to call a protected downstream API.
        HttpClient client = new HttpClient();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
        var response = await client.GetAsync("http://api-domain/api/app-user/me");

       // process response

        return Ok(result);
    }
```

What am I missing? Is something more required which isn't documented in the webapp section?

**Comment by mschaefer-gresham** [comment]
@jmprieur I've followed the webapp instructions, and as a test, tried to acquire the token in a controller decorated with the [AuthorizeForScopesAttribute]. Debugging the failed request I see that I end up in the attribute, which sets a Challenge on the result property of the Exception context, and then re-raises the exception:

```
context.Result = new ChallengeResult(properties);
...
base.OnException(context);
```

This exception is still coming back to my React SPA. I was under the impression that I was going to be re-authenticated within the server and that my request was going to be re-tried (perhaps wishful thinking).

How is my React SPA suppose to make use of this exception with the Challenge result? 

Before I was catching the Msal exception in the SPA and redirecting back to the login, which went to the Challenge. This get me reauthenticated, but I'm still redirected away from the SPA.

It still feels like I'm missing a piece of this.

**Comment by mschaefer-gresham** [comment]
@jmprieur my React SPA is calling an endpoint/controller in my server side "webapp", which is my BFF. This controller is decorated with [AuthorizeForScopes] and as described above, tries to acquire an access token for a downstream api. 

How is the webApp(BFF) suppose to handle the [AuthorizeForScopes] exception which is being thrown by it's own controller?

Just to recap, my webApp(BFF) handles the login process and acts as a gateway to a downstream api.  I want to renew the webApp(BFF) id token when it expires from within the webApp(BFF) without the SPA being involved.

**Comment by jmprieur** [comment]
I don't think that this is possible, @mschaefer-gresham. Re-signing it the user requires going to the authorization endpoint, so your SPA page would be replaced by a call to AAD (which can be quick and without requiring the user interaction), and then the SPA code would be again be available in the backend, end your frontend would redeem it to get an access token

@kalyankrishna1 what do you think?

**Comment by kalyankrishna1** [comment]
@mschaefer-gresham , you should look at this sample [Accessing the logged\-in user's token cache from background apps, APIs and services](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache) for your scenario

**Comment by mschaefer-gresham** [comment]
@kalyankrishna1 and @jmprieur, first I'd like to say thank you for your responses so far. I appreciate your support.

However, we are going in circles now. @kalyankrishna1 the sample you proposed requires having an access token in the browser. This is _precisely_ what I am trying to avoid. 

Can I assume that you are both familar with the [BFF](https://duendesoftware.com/products/bff) (no tokens in the browser) pattern? This is now considered the one-and-only way to secure a public SPA. The SPA should only have an httponly cookie issued from the BFF. The BFF handles the login and manages tokens for itself, and for downstream APIs. The SPA has no tokens, nor does it need any specialized msal related library, or otherwise.

Based on everything you are telling me, Microsoft.Identity.Web + Azure B2C does not support this pattern without requiring the user to re-authenticate (i.e. making the SPA redirect to the idp) every time the BFF id token expires.

This is a major shortcoming of this framework. In our application, it's not feasible to expect the user re-authenticate just because the BFF id token has expired. Moreover, it introduces the problem that the SPA can't anticipate which request is going to fail when the BFF id token expires. For example, the user clicks a button to do a POST/PUT action which subsequently fails causing the SPA to redirect to Azure AD. What happens to that request?

Incidentally, this [example](https://github.com/manfredsteyer/yarp-auth-proxy) does solve this problem by using Microsoft.AspNetCore.Authentication extensions (AddCookie, AddOpenIdConnect). It acquires access and refresh tokens for the BFF which can be renewed _before they expire,_ and uses the BFF access token to acquire the downstream api token using an "on_behalf_of" token exchange. The BFF access token expiry is checked _before_ the downstream api access token is fetched such that the downstream request will not fail because of an expired BFF token.

The problem is that on_behalf_of is not supported by Azure B2C. 

The only _possible_ solution I can see now is for the BFF to know the client id and secret of each downstream api and to request their access tokens this way. But I'm not sure even this works because I need to acquire them on behalf of the logged in user. Will the downstream api access token have the correct claims?

I would like to think I'm missing something here and/or that I have not explained myself well enough up to this point. 

At the very least, I would be extremely useful/time saving if you could at least confirm that Microsoft.Identity.Web + Azure B2C is not capabale of solving the BFF (no token in browser) pattern with silent BFF id token refresh. I think @jmprieur confirmed this, but I'd like to be sure.

I would also like to request that support for this be added.

**Comment by jmprieur** [comment]
@mschaefer-gresham yes, this flow: [Hybrid SPA](https://github.com/AzureAD/microsoft-identity-web/wiki/Hybrid-SPA) is supported by AAD, but not AAD B2C,

**Comment by jmprieur** [comment]
> @mschaefer-gresham yes, this flow: [Hybrid SPA](https://github.com/AzureAD/microsoft-identity-web/wiki/Hybrid-SPA) is supported by AAD, but not AAD B2C,

**Comment by mschaefer-gresham** [comment]
@jmprieur I was not referring to the [Hybrid SPA](https://github.com/AzureAD/microsoft-identity-web/wiki/Hybrid-SPA) flow. Once again, I am trying to implement the BFF no-tokens-in-the-browser solution for securing a public SPA. It feels like we keep having two different conversations. 

My SPA currently works by acquiring tokens in the browser. My objective is to stop doing this according to current [best practice](https://duendesoftware.com/products/bff) without relying on Duende.

I think it would be helpful to a lot of people if you could answer my original question.  For the sake of completeness, I am trying to achieve the following and the only piece I cannot solve is #3 together with #4:

### Goal:
1. The SPA should only rely on a httponly cookie issued by a "BFF" server app. The SPA should have zero dependencies on any auth type libraries (and obviously no tokens).

1. The BFF server should handle login, acquire and manage tokens for itself, and be able to acquire tokens for downstream apis on behalf of the logged in user.

1.  When the BFF server token (id or access) expires, the BFF should be able to renew this token silently such that the SPA is not involved at all (not redirected to the idp), allowing the BFF to continue acquiring tokens for downstream apis.

1.  This should work for Azure B2C.

### Problem:
If I use Microsoft.Identity.Web, acquiring the downstream api access token fails when BFF server id token expires. There is no way to silently renew the BFF id token server-side.

If I use Microsoft.AspNetCore.Authentication extensions (AddCookie, AddOpenIdConnect) together with Azure B2C, I cannot achieve the token exchange for the downstream api token because the on_behalf_of flow is not supported in B2C.

### Question:
Is there a solution for silently renewing the BFF server id token entirely on the server without the SPA needing to redirect to the idp using B2C? I've looked at the suggestions you and @kalyankrishna1 have sent me and I don't see how either can solve this problem.

If there is a solution, can you please be more specific on how to solve it.

**Comment by kalyankrishna1** [comment]
Silent token acquisition within the browser (SPA) is only possible using [MSAL.js](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki).

Tagging @derisen to see if he can help

**Comment by michiproep** [comment]
Hi @mschaefer-gresham,
I totally understand your frustration since nobody seems to understand your question.

Please correct me if I'm wrong but I don't think there is a need to renew IdTokens at all.
With BFF, you authenticate once to get an IdToken and then use cookies to maintain your own session. If, for whatever reason, you need updated claims from the IdToken you need to reauthenticate or call the graph api (e.g. in cookie sliding expiration event).

For calling downstream APIs, AccessTokens are used. MSAL requests AccessToken (also for different scopes than the initial once) by using the refresh token. Therefore, it always injects the offline_access scope to the authorize-request.

My finding is, that using the IDownstreamApi helper class does not work for AzureB2C since it trys to use the OBO flow. You can use the ITokenAquisition to get accesstokens, though.

Is this answer going in the right direction?

**Comment by mschaefer-gresham** [comment]
Hi @michiproep 

Thank you for responding. Based in this conversation and others I figured out that it is not possible to implement the [BFF Pattern](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#name-backend-for-frontend-bff-pr) using Microsoft.Identity.Web. 

Instead, I based my solution on this [example](https://github.com/manfredsteyer/yarp-auth-proxy) that was referrenced by Damien Bowden on his blog. It's working quite well after making a few changes.

**Comment by michiproep** [comment]
Hi @mschaefer-gresham,
may I ask if you managed to renew an IdToken with that solution?

**Comment by mschaefer-gresham** [comment]
Hi @michiproep, no you don't renew the id token using the approach I mention above, only the access token. Regarding this issue, I did not fully understand how this worked or what was possible when I started this project using Microsoft.Identity.Web so I was asking the wrong question.

**Comment by mschaefer-gresham** [comment]
Hi @michiproep, I might also mention that Azure B2C does not support renewing an access token by default using grant type "refresh_token". You have to create a [custom policy](https://github.com/azure-ad-b2c/samples/tree/master/policies/refresh-token-journey).

**Comment by michiproep** [comment]
Oh that's interesting. well, I never tryed the built-in user flows. I used custom policies from the beginning
