### ISSUE TITLE
[Documentation] 

### ISSUE THREAD

**Issue by dmbush** [AzureAD/microsoft-identity-web#1984]
### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ x] documentation needs clarification
- [ ] error(s) in the example
- [x ] needs an example

### Description of the issue

I have found your How to enable hybrid spa page and think it might be exactly what I am looking for.
I would like to use ASP.Net Core MVC/API to get and store my tokens and get a cookie to my react app to use it and call graph via asp and set that back to the app.  Keeping everything secure on the backend.
I have found the beginning of how you might set it up with [Microsoft Idenity](https://github.com/AzureAD/microsoft-identity-web/wiki/Hybrid-SPA) It would be really good to get Tutorial/Example or further clarification on getting this setup and working.  I followed more of the links on the initial page but could not find a solid example of how to do this.
please can you help?

**Comment by jmprieur** [comment]
@dmbush : this is described here: https://github.com/AzureAD/microsoft-identity-web/wiki/Hybrid-SPA
But only works for AAD (not B2c)
