### ISSUE TITLE
Wrong authority used to redeem authorization code of guest users

### ISSUE THREAD

**Issue by tjkb** [AzureAD/microsoft-identity-web#1996]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.25.10

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Distributed caches

### Description

We have a multi tenant SaaS Web App that logs in users. The backend validates if the tenantId of the user that logs in is a paying customer. If all is ok, the user can proceed and it calls MS Graph to show some data.  In our appsettings we use the `common` endpoint as tenantId. So it is setup like this:

```csharp
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApp(Configuration)
            .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
            .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
            .AddInMemoryTokenCaches();
```

When guest users with private Microsoft accounts log in, because we configured the `common` endpoint, the user claims contain the home tenant id and not the tenantId they are guests of. This is solved when during the login process the users choose "Log in options" and then "Log in to an organization". There, they can search for the desired tenant to log in.

This works and the user claims contain the correct tenantId. But when Identity Web redeems the authorization code for an access token, since we use `EnableTokenAcquisitionToCallDownstreamApi`, it fails with error message provided below. **It fails, because during the redemption of the authorization code the `common` endpoint is used instead of the tenant specific one that was used when obtaining the authorization code.**

By using the `OnAuthorizationCodeReceived` hook and not letting Identity.Web do the redemption of the authorization code it starts working. Right now we need to use some kind of home realm discovery, e.g. checking the query string for a value, to know where the user wants to log in.
```csharp
openIdConnectOptions.Events.OnAuthorizationCodeReceived = async context =>
            {
                var application = ConfidentialClientApplicationBuilder
                    .Create(openIdConnectOptions.ClientId)
                    .WithTenantId(GetTenantIdFromHomeRealmDiscovery(context.HttpContext))
                    .WithClientSecret("my-secret")
                    .WithCacheOptions(CacheOptions.EnableSharedCacheOptions)
                    .WithRedirectUri("https://localhost:44321/signin-oidc")
                    .Build();

                var result = await application
                    .AcquireTokenByAuthorizationCode(openIdConnectOptions.Scope, context!.ProtocolMessage!.Code)
                    .WithPkceCodeVerifier(GetCodeVerifier(context))
                    .ExecuteAsync();

                context.HandleCodeRedemption(result.AccessToken, result.IdToken);
            };
```

This is a bug and Identity Web should in this case use the correct tenant id.

### Reproduction steps

1. Login with a guest user that uses a Microsoft account via "find organization" to a SaaS web app using the `common` endpoint

### Error message

MsalUiRequiredException: AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint. Trace ID: fd7556a5-8ff6-4765-8b61-590022914d00 Correlation ID: b8286fb9-2fdf-4739-9f73-0f2c9a846ea7 Timestamp: 2022-12-08 14:45:11Z

    Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
    Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse<T>(HttpResponse response, RequestContext requestContext)
    Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync<T>(Uri endPoint, HttpMethod method, RequestContext requestContext, bool expectErrorsOn200OK, bool addCommonHeaders, Func<OnBeforeTokenRequestData, Task> onBeforePostRequestData)
    Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, bool addCommonHeaders, Func<OnBeforeTokenRequestData, Task> onBeforePostRequestHandler)
    Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(string tokenEndpoint, ILoggerAdapter logger)
    Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(string tokenEndpoint, ILoggerAdapter logger)
    Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary<string, string> additionalBodyParameters, string scopeOverride, string tokenEndpointOverride, CancellationToken cancellationToken)
    Microsoft.Identity.Client.Internal.Requests.ConfidentialAuthCodeRequest.ExecuteAsync(CancellationToken cancellationToken)
    Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
    Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByAuthorizationCodeParameters authorizationCodeParameters, CancellationToken cancellationToken)
    Microsoft.Identity.Web.TokenAcquisition.AddAccountToCacheFromAuthorizationCodeAsync(AuthorizationCodeReceivedContext context, IEnumerable<string> scopes, string authenticationScheme)
    Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder+<>c__DisplayClass11_1+<<WebAppCallsWebApiImplementation>b__1>d.MoveNext()
    Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RunAuthorizationCodeReceivedEventAsync(OpenIdConnectMessage authorizationResponse, ClaimsPrincipal user, AuthenticationProperties properties, JwtSecurityToken jwt)
    Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()

### Relevant code snippets

```csharp
as above
```

### Expected behavior

When using `EnableTokenAcquisitionToCallDownstreamApi` it should use the same authority/tenantId to redeem the authorization code as was used when obtaining the authorization code (logging in the user).

**Comment by tjkb** [comment]
It’s an existing .NET 6 app.Am 08.12.2022 um 18:11 schrieb Jean-Marc Prieur ***@***.***>:﻿
@tjkb : is it a new app or an existing app?
Which target framework? .NET 7?

**Comment by tjkb** [comment]
I've simplified the bug description/reproduction since guest users can login to a specific tenant via "log in options" - "find organization".

**Comment by jmprieur** [comment]
What does GetTenantIdFromHomeRealmDiscovery do?

**Comment by tjkb** [comment]
In our specific case it looks at the subdomain of the host url of the current request. Our customers access our app via custom urls like `customerA.app.com`. That way, we can know to which tenant a user tries to login to.

But generally, `GetTenantIdFromHomeRealmDiscovery` tries to get the destination tenant from the current request. It’s custom logic.

**Comment by JoshLozensky** [comment]
@tjkb does this repro on version 2.13.3? If so please re-open this issue.

**Comment by tjkb** [comment]
@JoshLozensky does the 2.13.3 release contain a PR that should influence this?
