### ISSUE TITLE
RemoveAccount should remove all the policies for a given account from the cache

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#20]
from: @TiagoBrenck :
For B2C, the remove account might have a bug. Since one user can have many IAccounts (because of the policies), we need to find a solution that gets all of the accounts of that user (regardless the policy) and remove from the cache. The current implementation is not doing it.

**Comment by jennyf19** [comment]
@jmprieur I checked the MSAL .NET code and they are removing all the accounts, regardless of policy. we do not enable removal of an account based on a policy. I will take a look at MS Identity Web's implementation next.

**Comment by jennyf19** [comment]
I don't see multiple b2c accounts, even when targeting multiple policies, so on the surface, this seems to be a non-issue, as we do remove all the b2c accounts, but we only have one, which is not right. will require further investigation.

**Comment by jmprieur** [comment]
@jennyf19 : this might be hard to do as we don't know how policies will have been used by a user (and the token caches are per policies).
If we do, we should have a cacheKey based only on the oid-without-policy and tid, and then all the policies for the same user would be in the same token cache.

I wonder if we really want to do that.

**Comment by jennyf19** [comment]
pending work here in [msal .net](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1940)
