### ISSUE TITLE
AspNetCore.OpenIdConnect is being set as samesite=none 

### ISSUE THREAD

**Issue by vikrantSinghOnGithub** [AzureAD/microsoft-identity-web#2012]
AspNetCore.OpenIdConnect is being set as samesite=none 

Is there any possiblity, we can set this cookies as Lax, if yes, Please share the snippet.

**Comment by jmprieur** [comment]
@vikrantSinghOnGithub : can you please provide repro steps?

**Comment by jmprieur** [comment]
@vikrantSinghOnGithub do you have an update?
