### ISSUE TITLE
[Feature Request] Support changing token endpoint (authority) in runtime for .NET

### ISSUE THREAD

**Issue by xubinzheng** [AzureAD/microsoft-identity-web#2035]
**Is your feature request related to a problem? Please describe.**
MASL always uses `/common/oauth2/v2.0/token` for code redemption. The `/common` endpoint works fine except for MSA guest users (B2B scenario). AAD tenant can invite MSA accounts into the tenant, and for those MSA accounts, we should use `/<tenantId/oauth2/v2.0/token` instead.

ESTS error message with `/common` for MSA guest user:
`AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.`

**Describe the solution you'd like**
I am looking for a way to inject the tenantId into the authority during runtime. So when the backend receives the auth code, it knows where to redeem the code per request per tenantId.

Maybe something in the `OpenIdConnectEvents`, create a new handler like `OnRedirectToCodeRedemption()`, where caller can update the authority per token request.

**Comment by jmprieur** [comment]
@xubinzheng 
I understand that this is a web app.
- Is it in a multi-tenant application? or a single-tenant application?
- Do you have repro steps? What Instance did you use in the configuration? What scope did you try to acquire during the auth code redemption?

**Comment by xubinzheng** [comment]
This is a first party app, so should be a multi-tenant application.
The repro steps should be: start MSAL.NET with `"Instance": "https://login.microsoftonline.com",` and `"TenantId": "common",`
Try to login with OIDC auth code flow from a MSA guest user, you will see the token request to ESTS is `/common/oauth2/v2.0/token`, and will see the exception of `MSA guest token redemption attempt on v2 common endpoint.`

**Comment by xubinzheng** [comment]
Problem is solved by using `common/oauth2/v2.0/authorize` and `/common/oauth2/v2.0/token` for OIDC login, then use tenanted endpoint for access token acquisition. i.e. `_tokenAcquisition.GetAuthenticationResultForUserAsync(new string[] { $"{ResourceId}/.default" }, tenantid, null, null, null)`

MSAL will use refresh token (from /common) to acquest corresponding tenanted token to downstream APIs.

**Comment by xubinzheng** [comment]
We have a user case that customers may request apps from different tenants.
Using the `<tenantId>/oauth2/v2.0/authorize` gives the user a chance to select a different account via ESTS account picker for different tenants. However, using `/common/v2.0/authorize` will always use the current account for all tenants. The access token request will fail with MSAL exception of "user doesn't exist in the tenant". 

We return ChallengeResult(OpenIdConnectDefaults.AuthenticationScheme) we when see a MSAL exception, but it ends up with an infinite login loop, because it redirects customers to the /common endpoint again which they have already logged in.


Xubin Zheng
So we would have to either 
1. continue to use <tenantId>/oauth2/v2.0/authorize and ask MSAL/MISE to support <tenantId>/oauth2/v2.0/tokens
2. ask ESTS to ignore current user when service returns `ChallengeResult(OpenIdConnectDefaults.AuthenticationScheme)`

**Comment by xubinzheng** [comment]
**Current implementation** (blocked MSA B2B guest users)
Token flow: 
/{tenant id}/oauth2/v2.0/authorize --> `/common/oauth2/v2.0/token` code redemption --> refresh token --> token exchange for access token
Blocker:
Ests blocks code redemption for MSA users. Because it cannot redeem a tenant specific auth code in /common endpoint for MSA users

**MSAL suggested** (blocked tenant switching)
Token flow: 
`/common/oauth2/v2.0/authorize` --> `/common/oauth2/v2.0/token` code redemption --> refresh token --> token exchange for access token
Blocker:
This wouldn’t work with when users have multiple accounts in multiple tenants. The request will always use current signin user as auth context, no way to switch to a different account in WebAPI.

Potential solution (feature ask)
Token flow: 
`/{tenant id}/oauth2/v2.0/authorize` --> `/**{tenant id}**/oauth2/v2.0/token` code redemption --> refresh token --> token exchange for access token

This would support MSA guest users and also support tenant switching.

**Comment by jmprieur** [comment]
@xubinzheng 
> I am looking for a way to inject the tenantId into the authority during runtime. So when the backend receives the auth code, it knows where to redeem the code per request per tenantId.

Where would this tenant Id come from?

**Comment by jmprieur** [comment]
Fixed
