### ISSUE TITLE
Typo in error message for missing scope or roles

### ISSUE THREAD

**Issue by frnk01** [AzureAD/microsoft-identity-web#2062]
There is a typo in the error message `Neither scope or roles claim was found in the bearer token`.
This should use `nor` instead of `or`.

Sincere regards,
The nitpicker

[IDWebErrorMessage.cs Line:25](https://github.com/AzureAD/microsoft-identity-web/blob/05acc378fe1642ccef4e86cfbaa067485889b7c5/src/Microsoft.Identity.Web.TokenAcquisition/IDWebErrorMessage.cs#L25****)

**Comment by jennyf19** [comment]
Thanks nitpicker 😂we will fix it.
