### ISSUE TITLE
GetAccessTokenForUserAsync - returned access token scope doesnt include the full unique identifier 

### ISSUE THREAD

**Issue by markharrison** [AzureAD/microsoft-identity-web#2084]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.26.0

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

im using this code - 

```csharp
string accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(
                                 new string[] { "api://e8b9cef4-b6e6-41de-828e-8f31ad0aa15d/Red.Read" });
```

The (decoded) returned access token includes:

```
 "scp": "Red.Read",
```

what happened to the api://e8b9cef4-b6e6-41de-828e-8f31ad0aa15d  ?

should the access include the  full unique identifier ?

-------

A snippet of code I found to do the API validation suggests it should be included ?  

```csharp
// Add Microsoft identity services
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"));

// Define a scope for accessing colors
const string ColorsScope = "api://<your-app-id>/Colors.Read";

// Add authorization policies based on scopes
builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("ColorsPolicy", policy =>
        policy.Requirements.Add(new ScopeAuthorizationRequirement(ColorsScope)));
});

```

### Reproduction steps

see code 

### Error message

n/a

### Id Web logs

n/a

### Relevant code snippets

```csharp
string accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(
                              new string[] { "api://e8b9cef4-b6e6-41de-828e-8f31ad0aa15d/Red.Read" });
```

### Expected behavior

scope in the access token to include the full unique identifier ?

**Comment by michiproep** [comment]
This is the expected behavior. besides that this would not be an issue of this library
