### ISSUE TITLE
Documentation issues about IDownstreamApi/IDownstreamRestApi migration

### ISSUE THREAD

**Issue by AndreErb** [AzureAD/microsoft-identity-web#2092]
### Documentation related to component
IDownstreamRestApi (called IDownstreamApi)

### Please check all that apply

- [x] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [x] error(s) in the example
- [x] needs an example

### Description of the issue
Wrong information in https://github.com/AzureAD/microsoft-identity-web/blame/master/docs/blog-posts/downstreamwebapi-to-downstreamapi.md

1. Wrong NuGet package name [here](https://github.com/AzureAD/microsoft-identity-web/blame/master/docs/blog-posts/downstreamwebapi-to-downstreamapi.md#L18)
Instead of "Microsoft.Identity.Web.AddDownstreamApi" it propably should be **Microsoft.Identity.Web.DownstreamApi**
2. [Here](https://github.com/AzureAD/microsoft-identity-web/blame/master/docs/blog-posts/downstreamwebapi-to-downstreamapi.md#L58) it is advised to inject a "IDownstreamApi" while [here](https://github.com/AzureAD/microsoft-identity-web/pull/2036/files#diff-0e00969aa402745aa7820a6bd10c669a446b653e56be62b54c447293e86a4e43R25) a "**IDownstreamRestApi**" is being injected
3. The whole blog post is talking about a "IDownstreamApi" while it seems like "**IDownstreamRestApi**" is the new thing
4. Maybe it's also better to link to examples, that use the NuGet packages instead of project references like being done [here ](https://github.com/AzureAD/microsoft-identity-web/pull/2036/files#diff-0e00969aa402745aa7820a6bd10c669a446b653e56be62b54c447293e86a4e43R25)

**Comment by dlgombert** [comment]
Absolutely this.  I upgraded my Microsoft.Identity package in what I thought was a nonbreaking change, and it took me an hour to reconcile the difference in documentation with my syntax errors.

**Comment by jmprieur** [comment]
@AndreErb @dlgombert 
Is this sufficient? https://github.com/AzureAD/microsoft-identity-web/blob/master/docs/blog-posts/downstreamwebapi-to-downstreamapi.md

Or do you need more?

**Comment by jmprieur** [comment]
Thanks for the heads up, @AndreErb and @dlgombert 

This is fixed. To provide more context, unfortunately we renamed IDownstreamRestApi to IDownstreamApi during the 2.x preview (based on feedback), and therefore the PR in the sample was partial (it was followed by [this PR](https://github.com/AzureAD/microsoft-identity-web/commit/bae8dbf9f1d2e9895b36d129be18c04b4fd22975)) which did not appear in the doc.

Thanks again
