### ISSUE TITLE
SignOut loop in v2.5.0

### ISSUE THREAD

**Issue by michiproep** [AzureAD/microsoft-identity-web#2095]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.UI

### Microsoft.Identity.Web version

2.5.0

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

Calling the SignOut endpoint in Web.UI controller preveously worked just fine.
With upgrade to 2.5.0 my app get's stuck in a logout-redirect-loop.
There are no overrides in the config to the signout-, etc. properties.

### Reproduction steps

Use
<a class="nav-link text-dark btn btn-sm btn-outline-secondary" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut">Sign out</a>

Ends up in loop.

### Relevant code snippets

```csharp
<a class="nav-link text-dark btn btn-sm btn-outline-secondary" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut">Sign out</a>
```

### Regression

1.26.0

### Expected behavior

User get's signed out. No loop.

**Comment by michiproep** [comment]
May-be, this is related? [#1558](https://github.com/AzureAD/microsoft-identity-web/pull/1558)

**Comment by tasha-rooney-ul** [comment]
I'm having the same issue with the [Azure B2C sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C) they recently upgraded to v2.5.0. It looks like it's setting the post logout redirect URI to the last page you tried to access, which was signout, causing the loop. Did you find a setting which allows us to set this value in the library manually?

**Comment by alexdulemba** [comment]
So far I've only seen that using version 1.26.0 solves the issue. Interestingly though, if you specify a custom `"SignedOutCallbackPath"` in appsettings.json, it will redirect from that back to Microsoft's Web.UI signed out page. Maybe this is a related issue?

**Comment by alexdulemba** [comment]
A workaround for now that seems to work: creating your own AccountController with SignIn and SignOut methods instead of using MicrosoftIdentity.AccountController SignIn and SignOut methods. Carlos Ortega's answer [here](https://stackoverflow.com/questions/56740143/how-to-specify-custom-logout-url-when-using-azure-ad-authentication-in-net-core) provides an example. You can then set a custom URI for a signout page to be redirected to without loops

**Comment by jennyf19** [comment]
We've applied a workaround in [2.9.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.9.0) which should address the issue. The root cause is a [breaking change in ASP.NET Core 6](https://github.com/dotnet/razor/issues/7577) with the Razor pages.
