### ISSUE TITLE
Microsoft.Identity.Web failing to validate audience with PublishTrimmed=true

### ISSUE THREAD

**Issue by celluj34** [AzureAD/microsoft-identity-web#2098]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.5.0

### Web app

Not Applicable

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

I have an application which we want to upgrade from `1.26.0` to `2.5.0`. Everything works locally, but when it's deployed to azure we are getting an error: `Bearer error="invalid_token", error_description="The audience 'api://<url>/<clientId>' is invalid"`. We are deploying using a docker container and using `PublishedTrimmed`, `PublishSingleFile`, and `PublishReadyToRun`. When I disable `PublishTrimmed` the authentication works, but when `PublishTrimmed` is enabled every protected endpoint returns HTTP 401.

- mcr.microsoft.com/dotnet/sdk:7.0.201-alpine3.17-amd64 AS build
- mcr.microsoft.com/dotnet/runtime-deps:7.0.3-alpine3.17-amd64 as publish

| Env   | Lib version | Works |
| ----- | ----------- | ----- |
| Local | 1.26.0      | ✅    |
| Local | 2.5.0       | ✅    |
| Prod  | 1.26.0      | ✅    |
| Prod  | 2.5.0       | ❌    |

### Reproduction steps

1. create web api protected by MS AAD with v2.5.0 and PublishedTrimmed=false
2. see that requiring auth works with bearer token
3. enable PublishedTrimmed and deploy
4. see "invalid audience" error on any protected endpoint

### Error message

HTTP Response Header
```text
www-authenticate: Bearer error="invalid_token", error_description="The audience 'api://<url>/<clientId>' is invalid"
```

### Relevant code snippets

```csharp
//Startup.cs -> ConfigureServices

services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
        .AddMicrosoftIdentityWebApi(_configuration.GetSection("AzureAd"));
```

### Regression

Microsoft.Identity.Web 1.26.0

### Expected behavior

I expect the auth to work even when trimmed.

**Comment by jmprieur** [comment]
@celluj34 what does it mean to be trimmed. Do you mean that there is a native compilation happening using the AoT compiler and that it proceeds with IL trimming?

**Comment by celluj34** [comment]
Trimmed meaning PublishTrimmed=true when running dotnet publish:

`dotnet publish --configuration Release --runtime win-x64 --output ./dist --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -p:PublishReadyToRun=true`.

I am going to try locally tomorrow. I wrote the issue just before I left work. I will report back with more detail if I have it.

**Comment by jmprieur** [comment]
Thanks @celluj34 
We need to do work to make our assemblies trimmable.

**Comment by westin-m** [comment]
The Json serialization used in DownstreamApi cannot be made trimmable using source generation. Because its base members and implementation leverages generic types, it is not feasible to create options for every type that will be used.
