### ISSUE TITLE
[Documentation] Typo in Web APIs

### ISSUE THREAD

**Issue by cpendery** [AzureAD/microsoft-identity-web#2099]
### Documentation related to component
[Web APIs](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#why-use-microsoftidentityweb-in-web-apis)

### Please check all that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
There shouldn't be a space in the word `dotnet` in the command `dot net new webapi -auth` in the first sentence of the section [Why use Microsoft.Identity.Web in web APIs?](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#why-use-microsoftidentityweb-in-web-apis). It also should have `--auth` instead of `-auth`. Resulting command: `dotnet new webapi --auth`

**Comment by jmprieur** [comment]
Thanks for the heads-up, @cpendery  (this was a bit embarrassing :-))
This is fixed!
