### ISSUE TITLE
Port code from ASP.NET Core Web app sample and have two dev samples

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#21]
What?
1. Port the code of Microsoft.Identity.Web, Microsoft.Identity.Web.UI and Microsoft.Identity.Web.Tests to this repo under the src folder

2. under dev-samples:
   1. Add the Web app calls Web API sample, and change it so that the Web API also calls Microsoft Graph (so that we experience the full end to end)
   2. Add the B2C Web app calls Web API sample

**Comment by jennyf19** [comment]
done.
