### ISSUE TITLE
AccessDenied page returns 404 when using MapControllerRoute

### ISSUE THREAD

**Issue by ElijahSink** [AzureAD/microsoft-identity-web#2111]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.UI

### Microsoft.Identity.Web version

2.5.0

### Web app

Sign-in users

### Web API

Not Applicable

### Token cache serialization

In-memory caches

### Description

In versions `2.0.2-preview` and following, the AccessDenied page is not returned when requested. Instead, the app returns a 404 response.

### Reproduction steps

1. Clone [the samples repo](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2) and open the project `1-WebApp-OIDC/1-1-MyOrg`. 
2. Update versions of `Microsoft.Identity.Web` and `Microsoft.Identity.Web.UI` to `2.5.0` (first version which displays the bug is `2.0.2-preview`)
3. Configure `appsettings.json` with the required values

The following steps are just the easiest way to reproduce the error; This bug does not depend on the exact method of producing an AccessDenied redirect.

4. Add an authorization policy which requires a role that your user doesn't have:
    _Startup.cs_
    ```diff
    --- a/1-WebApp-OIDC/1-1-MyOrg/Startup.cs
    +++ b/1-WebApp-OIDC/1-1-MyOrg/Startup.cs
    @@ -37,6 +37,10 @@ namespace WebApp_OpenIDConnect_DotNet
                 services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                 .AddMicrosoftIdentityWebApp(options => Configuration.Bind("AzureAd", options));
    
    +            services.AddAuthorization(
    +                policies => { policies.AddPolicy("p-Test", p => p.RequireClaim("roles", "TestRole")); }
    +            );
    +
                 services.AddControllersWithViews(options =>
                 {
                     var policy = new AuthorizationPolicyBuilder()
    ```
5. Add authorization using that policy to the `HomeController`:
    ```diff
    --- a/1-WebApp-OIDC/1-1-MyOrg/Controllers/HomeController.cs
    +++ b/1-WebApp-OIDC/1-1-MyOrg/Controllers/HomeController.cs
    @@ -6,7 +6,7 @@ using WebApp_OpenIDConnect_DotNet.Models;
    
     namespace WebApp_OpenIDConnect_DotNet.Controllers
     {
    -    [Authorize]
    +    [Authorize(Policy = "p-Test")]
         public class HomeController : Controller
         {
             private readonly ILogger<HomeController> _logger;
    ```
6. Start the app and open in your browser

### Error message

You will be redirected to `https://localhost:44321/MicrosoftIdentity/Account/AccessDenied?ReturnUrl=%2F` but the page will not be found.

### Id Web logs

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:44321
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:3110
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/ejsink/src/active-directory-aspnetcore-webapp-openidconnect-v2/1-WebApp-OIDC/1-1-MyOrg
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:44321/ - -
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      ClaimsAuthorizationRequirement:Claim.Type=roles and Claim.Value is one of the following values: (TestRole)
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[13]
      AuthenticationScheme: Cookies was forbidden.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[13]
      AuthenticationScheme: OpenIdConnect was forbidden.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:44321/ - - - 302 0 - 76.8571ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:44321/MicrosoftIdentity/Account/AccessDenied?ReturnUrl=%2F - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:44321/MicrosoftIdentity/Account/AccessDenied?ReturnUrl=%2F - - - 404 0 - 2.0688ms
```

### Relevant code snippets

```csharp
See reproduction steps.
```

### Regression

2.0.0-preview

### Expected behavior

The AccessDenied page should be returned properly.

**Comment by creativebrother** [comment]
It seems we have the issue too. 404 for /MicrosoftIdentity/Account/AccessDenied.

**Comment by creativebrother** [comment]
It seems this time the razor page routing is not working even though the page is there in the right path. In the host app razor page works no problem, just those pages provided by this lib in the UI project.

**Comment by jmprieur** [comment]
I didn't have the issue. I got
![image](https://user-images.githubusercontent.com/13203188/225798945-44f80493-486c-4f84-abdc-738431f09f1c.png)

The code I used is:

````csharp
           services.AddAuthorization(
                policies => { policies.AddPolicy("p-Test", p => p.RequireClaim("roles", "TestRole")); }
                        );

            services.AddRazorPages().AddMvcOptions(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();
```

**Comment by creativebrother** [comment]
I got this.
![image](https://user-images.githubusercontent.com/65241136/225900272-bd6764e6-3e00-4f54-b4b7-983e3d892b1a.png)

**Comment by creativebrother** [comment]
`            // Sign-in users with the Microsoft identity platform
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApp(options => Configuration.Bind("AzureAd", options));
            services.AddAuthorization(policies =>
            {
                policies.AddPolicy("p-Test", p => p.RequireClaim("roles", "TestRole"));
            });

            services.AddControllersWithViews(options =>
            {
                //var policy = new AuthorizationPolicyBuilder()
                //    .RequireAuthenticatedUser()
                //    .Build();
                //options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();

            services.AddRazorPages();`

`            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });`

**Comment by creativebrother** [comment]
I removed the default authorization RequireAuthenticatedUser() part because I do not need it.
If I change to use endpoints.MapControllers() in the routing,  I got 
![image](https://user-images.githubusercontent.com/65241136/225901881-06e14ba9-22d1-440d-b510-859160512e9c.png)

**Comment by creativebrother** [comment]
I used the code as the following: and I get 404
`            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
                // Handling SameSite cookie according to https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1
                options.HandleSameSiteCookieCompatibility();
            });

            // Sign-in users with the Microsoft identity platform
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApp(options => Configuration.Bind("AzureAd", options));
            services.AddAuthorization(policies =>
            {
                policies.AddPolicy("p-Test", p => p.RequireClaim("roles", "TestRole"));
            });

            services.AddControllersWithViews(options =>
            {
            }).AddMicrosoftIdentityUI();

            services.AddRazorPages().AddMvcOptions(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();`

`            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");

                endpoints.MapRazorPages();
            });`

**Comment by creativebrother** [comment]
![image](https://user-images.githubusercontent.com/65241136/225904346-85149faf-53db-43f1-9a5d-bde7d289e580.png)

**Comment by creativebrother** [comment]
If I downgrade the Microsoft.Identity.Web and Microsoft.Identity.Web.UI to **1.26.0**, everything seems working. I was using the test project webapp-openidconnect-dotnet with solution 1-1-MyOrg by Cloning [the samples repo](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2)

**Comment by creativebrother** [comment]
![image](https://user-images.githubusercontent.com/65241136/226331220-b99f4ed8-c5ca-4d7e-938c-8b1340312939.png)

**Comment by creativebrother** [comment]
If I use 2.5.0 Microsoft.Identity.Web and 1.26.0 for Mircosoft.Identity.Web.UI, it seems also working. So looks like the **Microsoft.Identity.Web.UI 2.5.0** is causing the issue.
![image](https://user-images.githubusercontent.com/65241136/226332683-23ffa635-307c-4b8f-bdcf-9b95cf56df0c.png)

**Comment by jmprieur** [comment]
Thanks for the repro steps, @creativebrother

**Comment by andyb749** [comment]
I created a page that would discover EndPoints in my page.  It found SignIn, SignOut, and others, but not AccessPage.   To get around this I created an area "MicrosoftIdentity", then added a folder "Account", then a subfolder "Pages" then created a Razor page within with the Razor page markup and .cs code in it.   I'm guessing that Error might need to be created in the same way.

Andy

**Comment by yankarinRG** [comment]
Having the same exact issue and patched by copying "src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity
/Pages/" into my project

**Comment by jmprieur** [comment]
This is due to a breaking change between net5 and net6.
For now the workaround is to release a net5.0 target for Id.Web.UI, while we are working with the ASP.NET Core team to understand a possible fix

**Comment by jennyf19** [comment]
We've applied a workaround in [2.9.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.9.0) which should address the issue. The root cause is a [breaking change in ASP.NET Core 6](https://github.com/dotnet/razor/issues/7577) with the Razor pages.

**Comment by LapinskasL** [comment]
@jennyf19, so does this version 2.9.0 fix this issue for .NET Core 6? I updated the packages to that version but I'm still getting the same issue.

**Comment by jmprieur** [comment]
@LapinskasL yes, this is fixed. I tested it with @ElijahSink's repro steps above before we released, and just re-cheched

<img width="568" alt="image" src="https://user-images.githubusercontent.com/13203188/234975317-4581d83a-04ed-422f-afe7-e620d4c89ddb.png">

**Comment by Saddiki881** [comment]
<img width="946" alt="image" src="https://github.com/AzureAD/microsoft-identity-web/assets/52981222/cb4ae537-bf9a-4923-b763-4abb4a45419d">
