### ISSUE TITLE
SAML questions

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#2130]
When my web application was written a few years ago, it was secured with Azure AD using Microsoft.Identity.Web. The application later was able to onboard users managed by external OIDC IDPs via Azure AD B2C. Since Microsoft.Identity.Web supports both Azure AD and Azure AD B2C, there was not much change to the application.

I have some questions since the application now needs to support users managed by an external IDP that for some reason has to use SAML.

1. Does Microsoft.Identity.Web support SAML by any chance?
2. Does Azure AD B2C support speaking SAML with the external IDP but using OIDC in the communication with the application? (I am trying to avoid the application having to handle SAML but based on my reading of the B2C doc it probably uses SAML on both sides)
3. If the application has to handle SAML, what is the NuGet packages you'd recommend?
4. If the application handles SAML, is there any value going through B2C vs. directly connecting to the external IDP?

**Comment by jmprieur** [comment]
@WenningQiu : is your application a web app? or a web API?

**Comment by WenningQiu** [comment]
@jmprieur It is in fact a Web API.

**Comment by jmprieur** [comment]
@brentschmaltz FYI

**Comment by jmprieur** [comment]
@WenningQiu : I don't think that we have a ready made solution for SAML tokens yet but we have plan to have one in the future (in the next year or so)
Which protocol is it? (what goes in the authorization header?)

**Comment by WenningQiu** [comment]
@jmprieur Thanks. I have yet to find out what goes in the header.

**Comment by WenningQiu** [comment]
I think I can answer my own questions after some exploration.

**Does Azure AD B2C support speaking SAML with the external IDP but using OIDC in the communication with the application? (I am trying to avoid the application having to handle SAML but based on my reading of the B2C doc it probably uses SAML on both sides)**
Yes that can be done with a custom policy - create a ClaimsProvider that handles SAML protocol with the external IDP while using OpenIdConnect protocol on the RelyingParty. With that approach my application can continue to use Microsoft.Identity.Web package.

**If the application handles SAML, is there any value going through B2C vs. directly connecting to the external IDP?**
My application is multi-tenanted, it must support OpenIdConnect; having to support SAML in the same application might create interference between the two authentication protocols. With B2C handling SAML, my application can just use Microsoft.Identity.Web package.

**Comment by jmprieur** [comment]
Thanks for sharing, @WenningQiu
