### ISSUE TITLE
Upgrading .net core app from v1 to v2 causes error in published azure app service

### ISSUE THREAD

**Issue by meyerovb** [AzureAD/microsoft-identity-web#2133]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.5.0

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

Upgrading from v1 that visual studio community wizard created breaks app in azure.  What are the required changes to the app to upgrade these to v2 from v1?

### Reproduction steps

Used vs2022 community .net 7 web app creation wizard, enabled microsoft identity authentication and graph, pointed it to a azure app service, published to azure, loaded and logged in fine.  went to nuget, saw 3 updates available (1.25 to 2.5), upgraded them, ran locally and could log in fine, published to azure and got

No service for type 'Microsoft.Identity.Abstractions.IAuthorizationHeaderProvider' has been registered

Downgraded to 1.26, published again, everything worked fine again.

### Error message

No service for type 'Microsoft.Identity.Abstractions.IAuthorizationHeaderProvider' has been registered

### Relevant code snippets

```csharp
nuget package manager, click upgrade...
```

### Expected behavior

not blow up

**Comment by bartdebever** [comment]
+1 on this issue, I currently have 2 apps running in production on an Azure App Service
A uses Microsoft.Identity.Web 1.26.0 and .NET 7 wtih no issues
B uses Microsoft.Identity.Web 2.6.1 with .NET 7 and throws the same exception as the author of this issue mentions.

Both work locally

**Comment by DrOverbuild** [comment]
I think this is the same issue as I reported in #2131. Newer versions, 2.6.1 and 2.7.0 don't seem to work either.
