### ISSUE TITLE
[Feature Request] Add method to compute the cache key  in MsalAbstractCacheAdapter

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#2135]
**Why?**
Even if the cache key suggested by MSAL.NET was carefully chosen based on data, some partners want to be able to express the key used to serialize and deserialize the cache (for instance Substrate)

**What?**
- In MsalAbstractTokenCacheProvider:
  - [x] add a virtual method `GetSuggestedCacheKey` taking the `TokenCacheNotificationArgs`. By default this method will return the SuggestedCacheKey member of the token cache notification arg
  - [x] replace all the arg.SuggestedCacheKey by the result to a call to the new method.
- [x] add a unit test (override the method in MsalTestTokenCacheProvider?)
- [x] document what partners will need to extend this class, or the `MsalDistributedTokenCacheAdapter` class, and override the singleton implementing `IMsalTokenCacheProvider` (see DistributedTokenCacheAdapterExtension)

**Comment by jennyf19** [comment]
Documentation should be in the xml comments.
