### ISSUE TITLE
[Feature Request] Support generic OIDC authority

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#2136]
Ask for STI, to be done when MSAL.NET itself supports OIDC authorities

**Comment by jmprieur** [comment]
See also MSAL.NET's issue: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4060
as well as the extensibility proposed for Id.Web in that issue

**Comment by jennyf19** [comment]
done.
