### ISSUE TITLE
OnRedirectToIdentityProvider event doesn't get called

### ISSUE THREAD

**Issue by bchakarov** [AzureAD/microsoft-identity-web#2142]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.6.1

### Web app

Sign-in users

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

The `OnRedirectToIdentityProvider` event doesn't get called. This starts happening after updating `Microsoft.Identity.Web` and `Microsoft.Identity.Web.UI` to version `2.6.1`. It does work on version `1.26.0`.

### Reproduction steps

1. Create a new ASP.NET Core Web App and select Microsoft identity platform for authentication.
2. Update both `Microsoft.Identity.Web` and `Microsoft.Identity.Web.UI` to version `2.6.1`.
3. Add the code from the `Relevant code snippets`.
4. Place a breakpoint inside the `OnRedirectToIdentityProvider` event and start the app. It will redirect you to the identity provider but the breakpoint won't get hit.

### Relevant code snippets

```csharp
builder.Services.Configure<MicrosoftIdentityOptions>(options =>
 {
     var onRedirectToIdentityProvider = options.Events.OnRedirectToIdentityProvider;
     options.Events.OnRedirectToIdentityProvider = async context =>
     {
         await onRedirectToIdentityProvider(context);
     };
 });
```

### Regression

1.26.0

### Expected behavior

I do expect the `OnRedirectToIdentityProvider` event to work and the code inside it to execute whenever there's a redirect to the identity provider. This used to work but updating the mentioned packages ended up breaking our entire multitenant identity solution.

**Comment by jmprieur** [comment]
@bchakarov, did you try the following?

```diff
+builder.Services.Configure<MicrosoftIdentityOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
-builder.Services.Configure<MicrosoftIdentityOptions>(options =>
 {
     var onRedirectToIdentityProvider = options.Events.OnRedirectToIdentityProvider;
     options.Events.OnRedirectToIdentityProvider = async context =>
     {
         await onRedirectToIdentityProvider(context);
     };
 });
```

 as explained [here](https://github.com/AzureAD/microsoft-identity-web/wiki/v2.0#breaking-changes-1), there is a breaking change in Microsoft.Identify.Web 2.x: you now need to provide the authentication scheme  (Id.Web 1.x was trying to guess the right authentication scheme, but could get it wrong)

**Comment by jmprieur** [comment]
@jennyf19 @westin-m 
I think we need to provide a bit of help here for our customers to detect (ideally at design time, but for sure at run time, that they configure the options without providing the authentication scheme)

**Comment by bivanovv** [comment]
> @bchakarov, did you try the following?
> 
> ```diff
> +builder.Services.Configure<MicrosoftIdentityOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
> -builder.Services.Configure<MicrosoftIdentityOptions>(options =>
>  {
>      var onRedirectToIdentityProvider = options.Events.OnRedirectToIdentityProvider;
>      options.Events.OnRedirectToIdentityProvider = async context =>
>      {
>          await onRedirectToIdentityProvider(context);
>      };
>  });
> ```
> 
> as explained [here](https://github.com/AzureAD/microsoft-identity-web/wiki/v2.0#breaking-changes-1), there is a breaking change in Microsoft.Identify.Web 2.x: you now need to provide the authentication scheme (Id.Web 1.x was trying to guess the right authentication scheme, but could get it wrong)

Confirming that this works, thanks! Also, I fully agree with your above comment.

**Comment by bchakarov** [comment]
> @bchakarov, did you try the following?
> 
> ```diff
> +builder.Services.Configure<MicrosoftIdentityOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
> -builder.Services.Configure<MicrosoftIdentityOptions>(options =>
>  {
>      var onRedirectToIdentityProvider = options.Events.OnRedirectToIdentityProvider;
>      options.Events.OnRedirectToIdentityProvider = async context =>
>      {
>          await onRedirectToIdentityProvider(context);
>      };
>  });
> ```
> 
> as explained [here](https://github.com/AzureAD/microsoft-identity-web/wiki/v2.0#breaking-changes-1), there is a breaking change in Microsoft.Identify.Web 2.x: you now need to provide the authentication scheme (Id.Web 1.x was trying to guess the right authentication scheme, but could get it wrong)

Confirming that this works, thanks! Also, I fully agree with your above comment.

**Comment by jmprieur** [comment]
Thanks for the update, @bchakarov.
Closing this question as answered,. See https://github.com/AzureAD/microsoft-identity-web/issues/2153
