### ISSUE TITLE
[Feature Request] Make MicrosoftIdentityAppCallsWebApiAuthenticationBuilder available on netstandard2.0

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/microsoft-identity-web#2143]
**Describe the solution you'd like**
Can MicrosoftIdentityAppCallsWebApiAuthenticationBuilder be made available on netstandard2.0 targets? This will help libraries that ship a netstandard 2.0 target.

**Comment by jmprieur** [comment]
@jennyf19, @westin-m : let's move the file from the AspNetCore folder to the project itself.
This will probably require conditional compilation for `Services.AddHttpContextAccessor()` (which is only available on netcoreapp3.1, net6, net7)
