### ISSUE TITLE
Simple transition from DownstreamWebApi to DownstreamApi results in 'Unauthorized'

### ISSUE THREAD

**Issue by johndhunter** [AzureAD/microsoft-identity-web#2146]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.6.1

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

Replacing DownstreamWebApi with DownstreamApi results in Unauthorised
{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Sun, 26 Mar 2023 16:56:57 GMT
  Server: Kestrel
  WWW-Authenticate: Bearer
  Content-Length: 0
}}

### Reproduction steps

1. Create a Asp.NET Core Web Api in Visual Studio 2022 using the template (C#)
2. Use ,Net7.0.  
3. Use Microsoft Identity platform ,Net7.0.  
4. Check Use Controllers....
5. Check Enable OpenApi Support
6. Add required components (Next)
7. Select Create new to add Azure configuration
8. Provide name and close
9. Add new Blazor Server app using same steps but add the above Api as a downstream Api
10. Inspect code and and see that DownstreamWebApi is being used by the template.
11. Run and check working OK. (I.e. login and call the Web Api)
12. Replace Calls to DownstreamWebApi in program.cs and CallWebApi.razor (adding reference to Microsoft.Identity.Web.DownstreamApi (2.6.1) - and update packages in Api and App
13. Run, login and call Web Api (via CallWebApi.razor) - result is Unauthorized
14. Comment out [RequiredScope(RequiredScopesConfigurationKey = "AzureAd:Scopes")] in Controller
15. Result is still Unauthorized

### Error message

Unauthorised
{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Sun, 26 Mar 2023 16:56:57 GMT
  Server: Kestrel
  WWW-Authenticate: Bearer
  Content-Length: 0
}}

### Id Web logs

info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7177
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5039
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\User\source\repos\BlazorApi5\BlazorApp6
info: System.Net.Http.HttpClient.DownstreamApi.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:7198/WeatherForecast/
info: System.Net.Http.HttpClient.DownstreamApi.ClientHandler[100]
      Sending HTTP request GET https://localhost:7198/WeatherForecast/
info: System.Net.Http.HttpClient.DownstreamApi.ClientHandler[101]
      Received HTTP response headers after 234.3103ms - 401
info: System.Net.Http.HttpClient.DownstreamApi.LogicalHandler[101]
      End processing HTTP request after 249.3649ms - 401

### Relevant code snippets

```csharp
from the code generated by the template and changed to use DownstreamApi:
            response = await downstreamAPI.CallApiForUserAsync(
                    "DownstreamApi",
                    options => options.RelativePath = "");

            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                apiResult = await response.Content.ReadAsStringAsync();
            }
            else
            {
                apiResult = "Failed to call the web API";
            }
```

### Expected behavior

Call should be authorized.

**Comment by johndhunter** [comment]
Problem solved - should have read all the docs - especially about scopes:
Replacing Scopes with Scopes[] solves this issue.

**Comment by jmprieur** [comment]
Thanks for updating the issue, @johndhunter.
What could have we done to make this more discoverable?

**Comment by johndhunter** [comment]
...and while I'm thinking about it....
this page 9https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-call-api?tabs=aspnetcore) could use an update

**Comment by jmprieur** [comment]
yes, thanks @johndhunter 
It's on the backlog ...

**Comment by johndhunter** [comment]
and this page: https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-7.0
