### ISSUE TITLE
[Feature Request] Enable Id.Web to work specifying Authority, if not Instance (for CIAM)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#2147]
**Is your feature request related to a problem? Please describe.**
**Why?**
Today, Microsoft.Identity.Web demands that the instance and the tenant are provided.
There are use cases where it will better to provide the authority.

**What?**
If you take the WebAppCallsMicrosoftGraph dev app

Instead of providing Instance and TenantId

https://github.com/AzureAD/microsoft-identity-web/blob/3a48a6dce9a43618aceb20525f1169fdf73eef7a/tests/DevApps/WebAppCallsMicrosoftGraph/appsettings.json#L1-L6

use

```json
{
    "AzureAd": {
        "Authority": "https://login.microsoftonline.com/7f58f645-c190-4ce5-9de4-e2b7acd2a6ab/v2.0",
        "ClientId": "56c9a633-236e-45ee-9af1-a53d9811fbd6",
```

Today this fails. 
After the fix, we'd want it to pass.

**How?**
In [MergedOptionsValidation.cs](https://github.com/AzureAD/microsoft-identity-web/pull/2101/files#diff-a5729432ee1cb615107c0912c12bf7aa7ee0704423dd05a6687ef31b78dc997b), change the condition on the instance to be instance and authority null or empty

**Additional context**
CIAM

**Comment by jennyf19** [comment]
Try to provide just the authority in the appsettings.json, not the instance and tenant and see what happens.
add unit tests
