### ISSUE TITLE
[Logging] Add logging to DownstreamApi

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#2148]
Add more logging to [DownstreamAPI](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs), as currently it's difficult to debug issues.

After updating this [sample](https://github.com/Azure-Samples/ms-identity-blazor-server/issues/17), find places to add more logging in DownstreamAPI, especially in the case of misconfiguration and failures...for example not having the scopes in a collection.

**Comment by westin-m** [comment]
leave the test app for an e2e
provoke different errors (ex. add a space in BaseUrl, use wrong scopes, spelling errors for the API, etc...)
See what errors you get, add logging for that area and move to the next error.
Push up the additional logging and do a PR but remove the sample from the project first

**Comment by jennyf19** [comment]
@westin-m Let's make sure we have a log message [here](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs#L295) maybe as part of an else, to say that the call is unauthenticated. This will help us/partners with debugging. Could be an info/debug level log message.
