### ISSUE TITLE
[Question] question about auth code flow 

### ISSUE THREAD

**Issue by worldspawn** [AzureAD/microsoft-identity-web#215]
**Which Version of Microsoft Identity Web are you using ?**
Note that to get help, you need to run the latest version. 
Microsoft Identity Web 0.1.5-preview

**Where is the issue?**
* Web API
    * Authorization code flow callback

Other? - please describe;

This is a new app or experiment

**Repro**

```json
{
  "AzureAd": {
    "Instance": "...",
    "ClientId": "...",
    "Domain": "...",
    "TenantId": "...",
    "SignedOutCallbackPath": "...",
    "SignUpSignInPolicyId": "...",
    "ResetPasswordPolicyId": "...",
    "CallbackPath": "/signin-oidc"
  }
}
```

```csharp
public void ConfigureServices(IServiceCollection services)
{
//..
                services.AddProtectedWebApi(options =>
                {
                    Configuration.Bind("AzureAd", options);
                },
                options =>
                {
                    Configuration.Bind("AzureAd", options);
                });
//..
}
```

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
//...
            app.UseAuthentication();
            app.UseAuthorization();
//...
}
```

I make request to my locally running application:
`GET https://localhost:10001/signin-oidc?code=eyJraWQiOiJjcGltY29yZV...`

**Expected behavior**
I'm expecting some other result. Not a 404.

**Actual behavior**
The result is 404 not found.

**Possible Solution**
No idea. I have confirmed the CallbackPath is actually being _bound_ to the options.

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@worldspawn Web APIs don't have reply URLs? I'm confused.

you should just use:

`GET https://localhost:10001`

And you should have `bearer eyJraWQiOiJjcGltY29yZV...` in the Authorize header of your HTTP request.

**Comment by worldspawn** [comment]
I'm trying to make this happen: https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow

My scenario is a spa that will authenticate with a aspnet core web api. The signing is facilitated with azure b2c. I've completed the credential entry of the signing in and end up with a code. I understand this code to be called a "authorization code". The spa should then submit this code to my web api which then exchanges it for a bearer token and optionally a refresh token (by submitting it back to azureb2c with the client secret). These are then returned to the client and used for future requests to my api.

Is that all wrong? :) I'm able to go through these steps using postman.

I'm trying to test this out by taking that initial authorization code and submitting it my api `GET https://localhost:10001/signin-oidc?code=xxx`. I'm expecting the middleware to be listening on that path.

I cannot seem to find a sample that matches my scenario. This example here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/1-WebApp-OIDC/1-5-B2C/Startup.cs

Seems to be hosting its own sign in ui. I want to use the azure b2c hosted flows.

**Comment by jmprieur** [comment]
@worldspawn you should really get a token for your Web API from the SPA (using MSAL.js for instance). 
If your SPA and the Web API have a difference client ID passing the code won't work. If they have the sample client ID, the code could be intercepted. this is not secure.

I'd advise you take a B2C MSAL.Js sample for your SPA and a Web API sample for your Web API. See for instance the Web API of this sample: https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/B2CWebAppCallsWebApi

**Comment by worldspawn** [comment]
@jmprieur thanks I see that I'm barking up the wrong tree with this approach. I wanted my api in the middle of this exchange so I could be notified of new user signups.

**Comment by jmprieur** [comment]
Closing as it was answered
