### ISSUE TITLE
User consent page is missing if custom scope of the app registration is used 

### ISSUE THREAD

**Issue by AlexPykavy** [AzureAD/microsoft-identity-web#2152]
I followed the https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration article. Then I extended the app a bit to integrate authorization with Swagger. The result can be found in the https://github.com/AlexPykavy/playground/tree/main/dotnet/Azure.ADAuth.

When I select only custom scope during authorization, the app redirects me to Azure AD (if I'm not already signed-in) and silently redirects me back to the Swagger page after the authorization succeeded.

However, when I select `openid` scope, the app shows user consent page after the authorization succeeded.

Do you know why this happens? Are they different because of a feature or a bug?)

Similar issue:
- https://github.com/MicrosoftDocs/azure-docs/issues/52167

**Comment by michiproep** [comment]
I don't think this would be an issue of this library but rather of the identity provider
