### ISSUE TITLE
[Documentation] Add dependabot to samples + documentation

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#2177]
- [x] Update our wiki with guidance on how to add [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) for automatic updates on Id Web releases
- [ ] Update the Id Web samples to use dependabot for automatic updates, in case we do not test all of them during a release. See [Id Web example](https://github.com/AzureAD/microsoft-identity-web/blob/master/.github/dependabot.yml) for idea.

**Comment by kellyyangsong** [comment]
Added to the wiki here: https://github.com/AzureAD/microsoft-identity-web/wiki/Add-Dependabot-for-Automatic-Updates

**Comment by kellyyangsong** [comment]
pull request adding dependabot to a samples repo (the other samples have dependabot already) https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/pull/253
