### ISSUE TITLE
Razor Pages are entirely missing from DLLs since 2.0.2-preview

### ISSUE THREAD

**Issue by ascott18** [AzureAD/microsoft-identity-web#2183]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.UI

### Microsoft.Identity.Web version

2.7.0

### Web app

Sign-in users

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

Since version 2.0.2-preview of this library, the compiled Razor Pages are entirely missing from the nuget package for .net6.0+ targets.

This also obviously prevents these pages from being routed to, since the endpoints for the razor pages also doesn't exist, the URL generated [here](https://github.com/AzureAD/microsoft-identity-web/blob/13c77c31d46af7d6b19ac28279a2137d2c0e348f/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs#L129) does not know of a page identified by `/Account/SignedOut`.

### Reproduction steps

1. Download Microsoft.Identity.Web.UI from nuget.org, any version from 2.0.2-preview onward
2. Open the nuget package with your tool of choice
3. Observe that Microsoft.Identity.Web.UI.Views.dll is not present in the nuget packages for net6.0 and net7.0 (but it is present for netcoreapp3.1)

![image](https://user-images.githubusercontent.com/5017521/230213200-fc864deb-7f79-4ba8-a5dd-b672f223a319.png)

### Relevant code snippets

```csharp
No code needed - issue is readily apparently from the nuget package contents.

Instantiate the ASP.NET Web App template from Visual Studio and select Microsoft Identity Platform as the authentication type. Then upgrade the Microsoft.Identity packages to the latest, remove the FallbackPolicy from Program.cs, and observe that https://localhost:7112/MicrosoftIdentity/Account/SignedOut returns a 404, while previous versions show a page with a message.
```

### Regression

2.0.0-beta, all 1.x versions

### Expected behavior

The razor pages exist

**Comment by jennyf19** [comment]
We need to look into this:
[View components in ASP.NET Core | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-7.0)
[Razor file compilation in ASP.NET Core | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-7.0&tabs=visual-studio) 

Looks like there was a breaking change in the ASP.NET Core views between NET5 and 6. Thanks for opening the issue.

**Comment by yankarinRG** [comment]
> Looks like there was a breaking change in the ASP.NET Core views between NET5 and 6. Thanks for opening the issue.
[This](https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#changes-to-the-aspnet-core-razor-sdk) should be it.

**Comment by jmprieur** [comment]
This is due to a breaking change between net5 and net6.
For now the workaround is to release a net5.0 target for Id.Web.UI, while we are working with the ASP.NET Core team to understand a possible fix

**Comment by jennyf19** [comment]
We've applied a workaround in [2.9.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.9.0) which should address the issue. The root cause is a [breaking change in ASP.NET Core 6](https://github.com/dotnet/razor/issues/7577) with the Razor pages.
