### ISSUE TITLE
Need support to set REDIRECT URL and not only CallbackPath

### ISSUE THREAD

**Issue by jagarzone6** [AzureAD/microsoft-identity-web#2215]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.UI

### Microsoft.Identity.Web version

2.9.0

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

I am deploying my web app to azure app service, 

but the library is automatically getting the host name for the redirect URL from the server HOST NAME
 e.g. dev-xxxxxx.azurewebsites.net/signin-oidc , 

I need to set different redirect url host like https://myown.domain.net/signin-oidc, and looks like is not supported in appsettings file.

### Reproduction steps

1. Create web app with <TargetFramework>net7.0</TargetFramework>
2. Use
PackageReference Include="Microsoft.Identity.Web.Diagnostics" Version="2.9.0"
 PackageReference Include="Microsoft.Identity.Web.UI" Version="2.9.0" />
    
3. deploy web app to azure app service.
4. There is no way to change the redirect host.

### Error message

Cant login cause the redirect hostname is incorrect in the redirect URL

### Id Web logs

n/a

### Relevant code snippets

```csharp
appsettings:

    "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "xxxxx",
    "ClientId": "xxxxxx",
    "ClientCertificates": [
      {
        "SourceType": "StoreWithThumbprint",
        "CertificateStorePath": "CurrentUser/My",
        "CertificateThumbprint": "xxxxxxx"
      }
    ],
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath": "/signout-oidc"
  },
```

### Regression

n/a

### Expected behavior

I should be able to specify the redirect URL or hostname env variable in azure app service

**Comment by jmprieur** [comment]
@jagarzone6  what is your scenario,
I think it's not supported by ASP.NET core even, because it would require cross site (would be vulnerable to cross site scripting).
Are you using a proxy?

**Comment by jagarzone6** [comment]
Ok I understand, I guess we have to change the infra, it is also available through app gateway listening internal sub domain so thats why it has 2 entry points, public azure website domain and the internal sub domain.

**Comment by jmprieur** [comment]
Did you try to have the gateway set X-Forwarded-to headers?
See https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers

**Comment by jagarzone6** [comment]
Not yet, let me try it, thank you
