### ISSUE TITLE
Question: How to read the Client Secret from the System Environment Variable instead of the appsettings.json

### ISSUE THREAD

**Issue by TejendraPrasad** [AzureAD/microsoft-identity-web#2216]
I have below config in appsettings.json

` {
  `"AzureAd": {
  `  "Instance": "https://login.microsoftonline.com/",`
  `  "Domain": "your-tenant.onmicrosoft.com",`
  `  "ClientId": "your-client-id",`
  `  "ClientSecret": "your-client-secret",`
  `  "CallbackPath": "/signin-oidc"`
 ` }`
`}`

And in .net core 6 code

` services.AddMicrosoftIdentityWebAppAuthentication(Configuration)`
                   `.EnableTokenAcquisitionToCallDownstreamApi() //Injects ITokenAcquisition`
                 `  .AddInMemoryTokenCaches();`

I'd like to copy ClientSecret to the Windows Server Environment and read from it to pass to services.AddMicrosoftIdentityWebAppAuthentication(Configuration)

Please advise on how to accomplish this.

Is there something similar to AppServicesAuthenticationInformation.cs in Microsoft.Identity.Web that I can use?

**Comment by jmprieur** [comment]
@TejendraPrasad : did you try the following?

```shell
set AZUREAD__CLIENTSECRET="your-client-secret"
```

For reference: https://learn.microsoft.com/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#non-prefixed-environment-variables

**Comment by TejendraPrasad** [comment]
@jmprieur , thank you for the guidance.

I just need to set AZUREAD__CLIENTSECRET="your-client-secret" in the Production Window Server's System Environment Variable?

I don't need to change anything in the code?

`{"AzureAd": {`
  `"Instance": "https://login.microsoftonline.com/",`
 ` "Domain": "your-tenant.onmicrosoft.com",`
  `"ClientId": "your-client-id",`
 ` "**ClientSecret": "your-client-secret"**, `-- **NOT REQUIRED Remove it as Env variable will be added in Configuration using AddEnvironmentVariables()**
 ` "CallbackPath": "/signin-oidc"`
` }`
`}`

And in .net core 6 code

 services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
.EnableTokenAcquisitionToCallDownstreamApi() //Injects ITokenAcquisition
  .AddInMemoryTokenCaches();

**Note**: We do not currently using CI/CD; instead, we manually publish locally using Visual Studio and copy it to the server... 

If my understanding is incorrect, please correct me.

Thank you!

**Comment by TejendraPrasad** [comment]
@jmprieur , thank you for the guidance.

I just need to set AZUREAD__CLIENTSECRET="your-client-secret" in the Production Window Server's System Environment Variable?

I don't need to change anything in the code?

`{"AzureAd": {`
  `"Instance": "https://login.microsoftonline.com/",`
 ` "Domain": "your-tenant.onmicrosoft.com",`
  `"ClientId": "your-client-id",`
 ` "**ClientSecret": "your-client-secret"**, `-- **NOT REQUIRED Remove it as Env variable will be added in Configuration using AddEnvironmentVariables()**
 ` "CallbackPath": "/signin-oidc"`
` }`
`}`

And in .net core 6 code

 services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
.EnableTokenAcquisitionToCallDownstreamApi() //Injects ITokenAcquisition
  .AddInMemoryTokenCaches();

**Note**: We do not currently using CI/CD; instead, we manually publish locally using Visual Studio and copy it to the server... 

If my understanding is incorrect, please correct me.

Thank you!

**Comment by TejendraPrasad** [comment]
@jmprieur , thank you for the guidance.

I just need to set AZUREAD__CLIENTSECRET="your-client-secret" in the Production Window Server's System Environment Variable?

I don't need to change anything in the code?

`{"AzureAd": {`
  `"Instance": "https://login.microsoftonline.com/",`
 ` "Domain": "your-tenant.onmicrosoft.com",`
  `"ClientId": "your-client-id",`
 ` "**ClientSecret": "your-client-secret"**, `-- **NOT REQUIRED Remove it as Env variable will be added in Configuration using AddEnvironmentVariables()**
 ` "CallbackPath": "/signin-oidc"`
` }`
`}`

And in .net core 6 code

 services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
.EnableTokenAcquisitionToCallDownstreamApi() //Injects ITokenAcquisition
  .AddInMemoryTokenCaches();

**Note**: We do not currently using CI/CD; instead, we manually publish locally using Visual Studio and copy it to the server... 

If my understanding is incorrect, please correct me.

Thank you!

**Comment by TejendraPrasad** [comment]
@jmprieur , thank you for the guidance.

It worked for me :-) 👍  sorry for multiple for close and open..

I just need to set AZUREAD__CLIENTSECRET="your-client-secret" in the Production Window Server's System Environment Variable.

`{"AzureAd": {`
  `"Instance": "https://login.microsoftonline.com/",`
 ` "Domain": "your-tenant.onmicrosoft.com",`
  `"ClientId": "your-client-id",`
 ` "**ClientSecret": "your-client-secret"**, `-- **NOT REQUIRED Remove it as Env variable will be added in Configuration using AddEnvironmentVariables()**
 ` "CallbackPath": "/signin-oidc"`
` }`
`}`

And in .net core 6 code

 services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
.EnableTokenAcquisitionToCallDownstreamApi() //Injects ITokenAcquisition
  .AddInMemoryTokenCaches();

Just to confirm, I can use the prefix **AZUREAD__** for any AzureAd configuration for example: Client Id or Callback?

Thank you!

**Comment by jmprieur** [comment]
Yes, @TejendraPrasad you can!
Thanks for updating this thread

**Comment by TejendraPrasad** [comment]
@jmprieur, I was also curious in alternative scenarios, such as how to manage two client secrets on the same server. For example, one for web and one for console.

I cannot have same key AZUREAD__CLIENTSECRET for both scenario right?

Thank you!
