### ISSUE TITLE
[Documentation] Typo in Wiki dotnet new webapi2 example 

### ISSUE THREAD

**Issue by geologyrocks** [AzureAD/microsoft-identity-web#2224]
### Documentation related to component
This repo's [Wiki](https://github.com/AzureAD/microsoft-identity-web/wiki#getting-started-with-microsoft-identity-web).

### Please check all that apply

- [X] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [X] error(s) in the example
- [ ] needs an example

### Description of the issue
In this repo's Wiki, in the [Getting started with Microsoft Identity Web](https://github.com/AzureAD/microsoft-identity-web/wiki#getting-started-with-microsoft-identity-web) section's example commands table,  
`dotnet new webapi2 --auth SingleAuth`
should instead be  
`dotnet new webapi2 --auth SingleOrg`.

**Comment by JoshLozensky** [comment]
@geologyrocks Thank you for pointing this out, I have made the suggested edit. We appreciate your assistance!
