### ISSUE TITLE
[Bug] Remove ForceHttpsRedirectUris 

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/microsoft-identity-web#223]
https://github.com/AzureAD/microsoft-identity-web/pull/202/files#diff-f39916663b976a444b0a47747df21822R62 Added ForceHttpsRedirectUris to work around scenarios where the app is behind a reverse proxy. This is an incomplete workaround for the scenario and should be removed. E.g. other components that depend on the request scheme still do not get the correct value like cookies.

The AspNetCore guidance for working with proxies is here:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1
- Address the issue centrally by using UseForwardedHeaders to fix up the request fields like scheme.
- Do not add workarounds to individual components.

The container scenario should have been addressed by default in .NET Core 3.0.
https://devblogs.microsoft.com/aspnet/forwarded-headers-middleware-updates-in-net-core-3-0-preview-6/

**Comment by Tratcher** [comment]
MicrosoftIdentityOptions.RedirectUri seems like it's trying to address the same problem and should also be removed.
https://github.com/AzureAD/microsoft-identity-web/blob/0e68799fc095c0611ccb3cec3a6758568b0f3f7c/src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs#L31-L42

If this isn't kept in sync with CallbackPath it's likely to break the flow.

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
