### ISSUE TITLE
Cannot resolve scoped service 'Microsoft.Identity.Web.ITokenAcquisition' from root provider

### ISSUE THREAD

**Issue by Gauravpitroda** [AzureAD/microsoft-identity-web#2242]
When I try to instantiate a class within middleware which has one of the parameters/dependecy as ITokenAcquisition, I get the following exception.

**System.InvalidOperationException: 'Cannot resolve scoped service 'Microsoft.Identity.Web.ITokenAcquisition' from root provider.'**

My code is as follows 

startup.cs file

```CSharp
public void ConfigureServices(IServiceCollection services)
{
  ...
  services.AddHttpClient<IClaimsApiHelper, ClaimsApiHelper>();
  ...
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
  app.UseMiddleware<ClaimsExpander>();
}
```

and the ClaimsExpander.cs middleware code 

```CSharp
public class ClaimsExpander
{
    private readonly RequestDelegate next;
    private readonly IClaimsApiHelper claimsApiHelper;
    
    public ClaimsExpander(RequestDelegate next,
	    ISecurityRolesService securityRolesService,
	    IUserService userService,
	    IUserGroupService userGroupService,
	    IClaimsApiHelper claimsApiHelper
	    )
    {
	    this.next = next;	   
	    this.claimsApiHelper = claimsApiHelper;
    }
    
    public async Task InvokeAsync(HttpContext context)
     {
           // code to use claimsApiHelper to call an external web api using the same authentication via ADB2C
     }
```

And the ClaimsApiHelper.cs file is

```CSharp
public class ClaimsApiHelper : IClaimsApiHelper
{
  private readonly HttpClient httpClient;
  private readonly IConfiguration configuration;
  private readonly ILogger logger;
  //private readonly ITokenAcquisition tokenAcquisition;
  
  /// <summary>
  /// Constructor
  /// </summary>
  /// <param name="httpClient">HttpClient</param>
  /// <param name="tokenAcquisition">ITokenAcquisition</param>
  /// <param name="configuration">Configuration</param>
  /// <param name="logger">Logger</param>
  public ClaimsApiHelper(
	  HttpClient httpClient,
	  IConfiguration configuration,
	  ITokenAcquisition tokenAcquisition,
	  ILogger<ClaimsApiHelper> logger)
  {
   // Constructor assignment of objects
   }
}
```

The ClaimsApiHelper constructor instantiation fails to inject a valid ITokenAcquisition object here.

Can you please let me know if
1. Is it possible to get ITokenAcquisition object or logged in user access_token in asp.net core middleware, so that I can call the downstream API from middleware using the same token?
2. Is there any other way to get access_token of logged in user and call a downstream API before pipeline ends or authorization happens using app.UseAuthorization();, so that I can fetch and add additional custom claims object to the existing identity?

Any help would be appreciated.

**Comment by jmprieur** [comment]
@Gauravpitroda, did you try:
```csharp
services.AddTokenAcquisition();
```

Is it a web API? If that's the case, see the docs here: https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration?tabs=aspnetcore
