### ISSUE TITLE
[Feature Request] Add a method to read a section with Downstream apis (.AddDownstreamApis(IConfigurationSection))

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#2255]
## Why?
As developers use more IDownstreamApi, standardize the description of a collection of Downstream APIs, and register them all at once.

In the appsettings.json, customers could describe their APIs in a particular section, and Microsoft.Identity.Web should be able to add them all.

```json
"AzureAd" : {
},

"DownstreamApi":
{
 "MyApi1": {
    "BaseUrl" : "https://myservice.com",
    "Scopes" : [ "access_as_admin" ],
    "RequestAppToken" : true
 },
 "MyApi2": {
    "BaseUrl" : "https://myOtherService.com",
    "Scopes" : [ "access_as_user" ],
 }
}
```

## What?

Have an API, in [DownstreamApiExtensions](https://github.com/AzureAD/microsoft-identity-web/blob/13f4022148bb1d19a16ab887cd3671d5f80ece0a/src/Microsoft.Identity.Web.DownstreamApi/DownstreamApiExtensions.cs#L15) that takes a `IConfigurationSection`

```csharp
services.AddDownstreamApis(Configuration.GetSection("DownstreamApis")
```

This would deserialize the section as a Dictionary<string, DownstreamApiOptions>, register the DownstreamApi service, and keep the Options in named options.

P2: Also add a method:
```csharp
AddDownstrsamApis(IConfiguration, Action<Dictionary<string, DownstreamApiOptions>> configureOptions)
```

## How
Dictionary<string, DownstreamApiOptions> dictionaryOfDownstreamApiOptionsByServiceName;

```csharp
foreach(var optionsForService in dictionaryOfDownstreamApiOptionsByServiceName)
{
  services.Configure(optionsForService.Key, optionsForService.Value);
}
RegisterDownstreamApi(services)
```

**Comment by jennyf19** [comment]
#2782
