### ISSUE TITLE
Missing API for WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions

### ISSUE THREAD

**Issue by guardrex** [AzureAD/microsoft-identity-web#2265]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

N/A

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

The API for ...

https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs

... is no longer appearing in the API browser (and thus not available for XREF cross-links) ...

https://learn.microsoft.com/en-us/dotnet/api/?term=MicrosoftIdentityWebApiAuthenticationBuilderExtensions

This is a recent phenomenon that broke some links in the official ASP.NET Core docs ...

https://buildapi.docs.microsoft.com/Output/PullRequest/332f35cd-658d-4914-0f85-907e40ee89f0/202305311313422280-29384/BuildReport?accessString=7be6219eb47c4399bce7dc56d3eff978643983827832ab92e544bdae90fa3be7

I'm code-fencing the API for now until it's fixed.

### Reproduction steps

N/A

### Relevant code snippets

```csharp
N/A
```

### Expected behavior

N/A

**Comment by jmprieur** [comment]
@guardrex : this should be [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.web.appbuilderextension.addmicrosoftidentitywebapp?view=msal-model-dotnet-latest), but I cannot find it.

@localden : would you see a reason why some API would not appear in the API browser?

**Comment by guardrex** [comment]
> [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.web.appbuilderextension.addmicrosoftidentitywebapp?view=msal-model-dotnet-latest)

That looks like different API, which is located at ...

https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.OWIN/AppBuilderExtension.cs

**Comment by jmprieur** [comment]
This one is for Asp.net own, not asp.net core

**Comment by guardrex** [comment]
Yes, I was just mentioning it because you cross-linked "*here*" to that API after I opened the issue.

This is a relatively recent problem. The API disappeared about the middle of last week AFAICT. I'll leave it code-fenced in the articles for now until it returns.

**Comment by jmprieur** [comment]
Thanks @localden 

@guardrex : it's there: https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.web.microsoftidentityappcallswebapiauthenticationbuilder?view=msal-model-dotnet-latest
