### ISSUE TITLE
[Documentation] Typo in attribute name RequiredScopesOrAppPermission in stead of RequiredScopeOrAppPermission

### ISSUE THREAD

**Issue by LockTar** [AzureAD/microsoft-identity-web#2277]
### Documentation related to component
Attribute name is incorrect (typo) in sample code. See the section [Verification of app roles](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#verification-of-app-roles).

### Please check all that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in the example
- [ ] needs an example

### Description of the issue
`RequiredScopesOrAppPermission` must be `RequiredScopeOrAppPermission`.

**Comment by jmprieur** [comment]
Thanks @LockTar 
This is fixed.
