### ISSUE TITLE
[Documentation] - Multiple Authentication Schemes has broken link

### ISSUE THREAD

**Issue by kickertw** [AzureAD/microsoft-identity-web#2284]
### Documentation related to component
Example

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [x] needs an example

### Description of the issue
On https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes, under the "Example" section, it states

See [this developer test app](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/MultipleAuthSchemes), which shows how to have both an Azure AD B2C and Azure AD sign-in in the same app.

This link shows "404 - page not found. The master branch of microsoft-identity-web does not contain the path tests/MultipleAuthSchemes."

Can someone provide the correct URL to the example code?

**Comment by jmprieur** [comment]
Thanks for the heads-up @kickertw 
the links are fixed.
