### ISSUE TITLE
Seeing authority_tenant_specified_twice error during token acquisition from v2.0 authority

### ISSUE THREAD

**Issue by RojaEnnam** [AzureAD/microsoft-identity-web#2288]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.11.1

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

Seeing authority_tenant_specified_twice error during token acquisition from v2.0 authority using TokenAcquirer, This is in PPE. 

### Reproduction steps

Acquire token through TokenAcquirer.GetTokenForAppAsync and provide v2.0 authority in IdentityApplicationOptions while creating TokenAcquirer as below.

```
                    var microsoftIdentityApplicationOptions = new MicrosoftIdentityApplicationOptions();
                    microsoftIdentityApplicationOptions.Authority = <V2Authority>;

                    tokenAcquirer = TokenAcquirerFactory.GetTokenAcquirer(microsoftIdentityApplicationOptions);
```

### Relevant code snippets

```csharp
Provided in reproduction steps
```

### Expected behavior

Should return a app token.

**Comment by jennyf19** [comment]
will be fixed in SAL
@sruke FYI
