### ISSUE TITLE
Microsoft.Identity.Web.OWIN issue with the redirect URI

### ISSUE THREAD

**Issue by obarbour** [AzureAD/microsoft-identity-web#2313]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.OWIN

### Microsoft.Identity.Web version

2.12.4.0

### Web app

Sign-in users

### Web API

Not Applicable

### Token cache serialization

In-memory caches

### Description

Using the Microsoft.Identity.Web.OWIN library, I'm not able to get the Redirect URI to work. I've tried using the appsettings.json file and setting the "RedirectUri" and I've also tried using only the web.config and setting "ida:RedirectUri". Neither option results in the "redirect_uri" URL parameter being added to the login redirect to "https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/authorize...". This is causing the redirect to go to a different (the first) redirect URI that is specified in the Azure AD App Registration.

Upon looking at the library implementation, it seems that [AddMicrosoftIdentityWebApp](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.OWIN/AppBuilderExtension.cs) is not setting the RedirectUri in the OpenIdConnectAuthenticationOptions. I have not tested to see if this is the culprit.

### Reproduction steps

In the Startup.Auth.cs file:
```
public void ConfigureAuth(IAppBuilder app)
{
    app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

    app.UseCookieAuthentication(new CookieAuthenticationOptions());

    OwinTokenAcquirerFactory factory = TokenAcquirerFactory.GetDefaultInstance<OwinTokenAcquirerFactory>();
    
    app.AddMicrosoftIdentityWebApp(factory);
    factory.Services
        .Configure<ConfidentialClientApplicationOptions>(options =>
        {
            options.RedirectUri = "https://localhost:44329/";
        })
        .AddInMemoryTokenCaches();
    factory.Build();
}
```

In the web.config file attempt
```
<appSettings>
    <add key="ida:ClientId" value="<CLIENT_ID>" />
    <add key="ida:AADInstance" value="https://login.microsoftonline.com/" />
    <add key="ida:ClientSecret" value="<CLIENT_SECRET>" />
    <add key="ida:Domain" value="<DOMAIN_NAME>.onmicrosoft.com" />
    <add key="ida:TenantId" value="<TENANT_ID>" />
    <add key="ida:PostLogoutRedirectUri" value="https://localhost:44329/" />
    <add key="ida:RedirectUri" value="https://localhost:44329/" />
    ...
</appSettings>
```

In the appsettings.json attempt
```
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "<DOMAIN_NAME>.onmicrosoft.com",
    "TenantId": "<TENANT_ID>",
    "ClientId": "<CLIENT_ID>",
    "RedirectUri": "https://localhost:44329/",
    "ClientSecret": "<CLIENT_SECRET>"
  }
}
```

### Error message

No error message. Login redirects to incorrect redirect URI. When looking at the login redirect request URL, the redirect_uri is not present as expected.

### Relevant code snippets

```csharp
Included above
```

### Expected behavior

Login redirects to correct redirect URI as specified in configuration.

**Comment by jvrooyen** [comment]
I lost the link to where I got this idea from, but this worked for me:

```
app.AddMicrosoftIdentityWebApp(factory, updateOptions: options =>
{
     options.RedirectUri = MyRedirectUri;
});
```

Microsoft.Identity.Web.OWIN v2.12.4

**Comment by obarbour** [comment]
Thanks - that solution worked. The documentation should be updated.
