### ISSUE TITLE
[Bug] Code Cleanup in Microsoft.Identity.Web.UI AccountController 

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#232]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.5-preview

**Where is the issue?**
* Web App
    * [x ] Sign-in users
    * [ ] Sign-in users and call web APIs

**Suggestions**
- AccountController [uses `IOptionsMonitor`](https://github.com/AzureAD/microsoft-identity-web/blob/17f48c62410e08ea0d4c1fdb4f15a0713ed7f00c/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs#L30) whereas the rest of Microsoft.Identity.Web.UI uses `IOptions`. The recommendation is to use IOptions
- AccountController sets explicitly a [scheme value](https://github.com/AzureAD/microsoft-identity-web/blob/17f48c62410e08ea0d4c1fdb4f15a0713ed7f00c/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs#L43) whereas Chris recommends to just use null (which challenges the default provider)

Note 
The AzureAD.UI [counterpart](https://github.com/dotnet/aspnetcore/blob/master/src/Azure/AzureAD/Authentication.AzureAD.UI/src/Areas/AzureAD/Controllers/AccountController.cs#L16) does the same as Microsoft.Identity.Web.UI's account controller.

**Comment by jmprieur** [comment]
@Tratcher FYI

**Comment by Tratcher** [comment]
> * AccountController sets explicitly a [scheme value](https://github.com/AzureAD/microsoft-identity-web/blob/17f48c62410e08ea0d4c1fdb4f15a0713ed7f00c/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs#L43) whereas Chris recommends to just use null (which challenges the default provider)

I checked on this and found that the auth scheme is only required to be non-null for SignIn. I've filed https://github.com/dotnet/aspnetcore/issues/23325 to fix that. You can remove the fallback for all of the others.

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
