### ISSUE TITLE
[Feature Request] Use the new AzureAD key issuer validator in AddMicrosoftIdentityWebApi

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#2323]
**Is your feature request related to a problem? Please describe.**
IdentityModel now exposes a new AAD specific implementation for a delegate validating keys issuer. AddMicrosoftIdentityWebApi could benefit from it.
For details, see https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2134

**Describe the solution you'd like**
Add the validation of the keys issuer, by calling `mergedOptions.TokenValidationParameters.EnableAadSigningKeyIssuerValidation()` for instance [here](https://github.com/AzureAD/microsoft-identity-web/blob/bd99dcd83e2fac586064a69b377fbe550ab5484f/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs#L218)

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.13.0

**Comment by jennyf19** [comment]
Included in [2.13.2 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.13.2)
