### ISSUE TITLE
Invoke password reset policy for local users 

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#2324]
I am using Microsoft.Identity.Web and Microsoft.Identity.Web.UI (2.11.1) on Azure AD B2C but run into some issue when testing password reset on local accounts. I am not able to reset the password when clicking "Forgot your password":

![image](https://github.com/AzureAD/microsoft-identity-web/assets/4291622/b82c1203-77b1-452d-8968-8f9b3ff6828c)

![image](https://github.com/AzureAD/microsoft-identity-web/assets/4291622/4ba862e2-348b-402d-8ff8-da7b1d48af79)

This is the HTTP message trace for the interaction above: [ResetPassword.har.zip](https://github.com/AzureAD/microsoft-identity-web/files/12029074/ResetPassword.har.zip)

The custom policies are based on LocalAccounts policies in the starter pack with just the tenant name and policy names adjusted:
[LocalAccountPolicies.zip](https://github.com/AzureAD/microsoft-identity-web/files/12029038/LocalAccountPolicies.zip)

Below is the appsettings.json section:
```
  "LocalAccount": {
    "Instance": "https://csgb2cdev.b2clogin.com",
    "TenantId": "2d3c6047-afa5-441b-8282-314f6dfe18d4",
    "Domain": "csgb2cdev.onmicrosoft.com",
    "ClientId": "57bb9b2e-d770-4fa7-9323-89d4c0642663",
    "ClientSecret": "xxxxTuSPcYp",
    "EditProfilePolicyId": "B2C_1A_LOCALACCOUNT_PROFILEEDIT",
    "ResetPasswordPolicyId": "B2C_1A_LOCALACCOUNT_PASSWORDRESET",
    "SignUpSignInPolicyId": "B2C_1A_LOCALACCOUNT_SIGNUP_SIGNIN",
    "CallbackPath": "/local-signin-oidc",
    "SignedOutCallbackPath": "/local-signout-callback-oidc"
  },
```

I appreciate suggestions on how to get around the issue.

**Comment by michiproep** [comment]
@WenningQiu 
You are using a policy without **embedded** password reset flow. In this case you either want to switch to an embedded pwrFlow or handle the specific "authentication failed" exception and send the user to your password reset policy yourself.

**Comment by WenningQiu** [comment]
@michiproep Thanks for the suggestions. User flow is much easier to use for local accounts.

**Comment by jennyf19** [comment]
Is the issue resolved @WenningQiu ? Going to close, but please re-open if that's not the case.
