### ISSUE TITLE
[Feature Request] When ASP.NET 5.0 supports Wilson 6.6, prioritize the small claims

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#233]
## Why?
.NET 5.0   is moving to using Wilson 6.6 which  has   a breaking change: using the small claims (ex: scp instead of the long   claims – the URIs)

## What?
-	Microsoft.Identity.Web already support both types of claims. But we need to test that all the scenarios still work.
-	We could also process the small claims before the long ones (optimization) as they will be the normal case by default, as we already did in https://github.com/AzureAD/microsoft-identity-web/blob/97ea390dacea2cdda94ec6143f37a844255353f3/src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs#L49-L54

**Comment by pmaytak** [comment]
According [this issue](https://github.com/dotnet/aspnetcore/issues/23441) Wilson 6.7 will be in Preview 7.

**Comment by pmaytak** [comment]
Tested Wilson 6.6 and Preview 7 with Identity Web test samples and web app samples. I didn't find any differences in claims behavior between Wilson 5.5 and 6.6.

>... has a breaking change: using the small claims (ex: scp instead of the long claims – the URIs)

@jmprieur What do you mean by that?

As far as I saw, in both 5.5 and 6.6 `SecurityToken` instances (as in our audience and issuer validator classes) always have small claims. But then by default they are transformed into long claims in `ClaimsPrincipal` instance.

**Comment by jmprieur** [comment]
This is what Barry told me (ASP.NET Core).
Would the transformation have been de-activated by default in 6.6 ?

**Comment by pmaytak** [comment]
Mapping is still active by default. The flag was added in 5.3.0 ([PR](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/924), [issue](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/923)).

Haven't found anything related in recent release notes.

**Comment by jmprieur** [comment]
@blowdart what did you have in mind when you told me that there would be a breaking change in Wilson 6.6 ?
cc: @pmaytak @jennyf19 @henrik-me

**Comment by pmaytak** [comment]
@jmprieur Suggestion on what to do with this? Keep it open?

**Comment by blowdart** [comment]
I understood you were turning mapping off by default, due to issues, well, like [this one](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/982#issuecomment-665405447)

If it was off by default that would obviously be a breaking change in Wilson, but if we can do it with a simple switch in aspnet we probably should cc @tratcher

**Comment by henrik-me** [comment]
@brentschmaltz @GeoK @mafurman

**Comment by brentschmaltz** [comment]
@blowdart @jmprieur @pmaytak turning off claim mapping is potentially breaking for users that look for specific claim types. 
IsInRole may not work as expected.

As a note, whenever a claim is mapped a property is added to the claim with the key value (JwtSecurityTokenHandler.ShortClaimTypeProperty, claimType),

This mapping issue was one of the driving forces behind the JsonWebTokenHandler which produces a JsonWebToken without any mapping.

**Comment by pmaytak** [comment]
Closing this issue, since testing was done on Identity Web side.

@blowdart If you decide to change this behavior ASP.NET side, please let us know then.

**Comment by jennyf19** [comment]
Included in [0.2.2-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.2-preview)
