### ISSUE TITLE
Singleton token acquisition with token cache serialization results in duplicate data in cache entries

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#2349]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.TokenCache

### Microsoft.Identity.Web version

2.13.1

### Web app

Sign-in users

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Distributed caches

### Description

This issue affects singleton token acquisition / MSAL instance with token serialization cache enabled and cache synchronization enabled.

In MSAL, when [new token is saved](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/9b9fb8d1089b3c838aba1d4340b14fd8e33ddda5/src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs#L162-L283) into the internal cache collection, cache serialization event handler for read is called first. This should clear the internal cache collection and load data relevant to the request cache key. If read doesn't find any data in serialized cache, internal cache should just be just cleared. The new tokens are then added to the internal collection and the whole collection is serialized into the external cache via write event handler.

The issue is that if the the read handler doesn't find any data in the external cache, `MsalAbstractTokenCacheProvider.OnBeforeAccessAsync`  doesn't call Msal.Deserialize, so any data from previous requests in the internal cache is not cleared.

The change in the Id.Web.TokenCache was made [here](https://github.com/AzureAD/microsoft-identity-web/pull/1904/files#diff-bfaf7cf903d49b640a7ef5682f24fdc00f9a28bd4e33a85aaa0d5abdb1f5a9dd).

### Reproduction steps
1. Create a web app/API.
2. Enable singleton token acquisition.
3. Enable token cache serialization using Id.Web.TokenCache.
4. Enable CacheSynchronization.
5. Do some operation that will end up writing to the serialized cache.
6. Do some other operation that will write to the cache (make sure the cache key is different, so for ex. different user).

To repro I modified [this test runner](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client) to hit [this web API](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/DevApps/WebAppCallsWebApiCallsGraph/TodoListService) with multiple users in parallel.

### Relevant code snippets

```csharp
-
```

### Regression

2.0.2-preview

### Expected behavior

The serialized cache entries should only have relevant tokens. `MsalAbstractTokenCacheProvider.OnBeforeAccessAsync` should always call Msal.Deseralize even if the read operation returned nothing.

**Comment by jennyf19** [comment]
Included in [2.13.2 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.13.2)

**Comment by jennyf19** [comment]
Included in [2.13.2 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.13.2)
