### ISSUE TITLE
[Feature Request] Update project templates to use the renamed APIs

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#236]
**Is your feature request related to a problem? Please describe.**
- Update templates to use the renamed APIs
-  Update the wiki pages describing the templates to explain how to use the web-app-calls-web-api and web-api-calls-web-api 
scenarios

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
