### ISSUE TITLE
Unable to auth openid via postman despite valid access token.

### ISSUE THREAD

**Issue by wrharper-AASP** [AzureAD/microsoft-identity-web#2367]
appsettings:
```
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "aasp.com",
    "TenantId": "REMOVED",
    "ClientId": "REMOVED",
    "CallbackPath": "/signin-oidc",
    "ClientSecret": "REMOVED",
    "ClientCertificates": []
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "MicrosoftGraph": {
    "BaseUrl": "https://graph.microsoft.com/v1.0",
    "Scopes": "User.ReadWrite"
  },
  "ServerKeyVault": {
    "VaultUri": "https://YOURVAULT.vault.azure.net/"
  }
}
```

program.cs:
```
var builder = WebApplication.CreateBuilder(args);
var initialScopes = builder.Configuration["DownstreamApi:Scopes"]?.Split(' ') ?? builder.Configuration["MicrosoftGraph:Scopes"]?.Split(' ');
var serverKeyVaultOptions = builder.Configuration.GetSection("ServerKeyVault").Get<ServerKeyVaultOptions>();

builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"))
    .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
    .AddMicrosoftGraph(builder.Configuration.GetSection("MicrosoftGraph"))
    .AddInMemoryTokenCaches(options => { options.AbsoluteExpirationRelativeToNow = new TimeSpan(90, 0, 0, 0); });

builder.Services.AddSingleton(x =>
{
    //switch when deploying
    return new SecretClient(new Uri(serverKeyVaultOptions.VaultUri), new InteractiveBrowserCredential());
    //return new SecretClient(new Uri(serverKeyVaultOptions.VaultUri), new ManagedIdentityCredential());
});

builder.Services.Configure<CookiePolicyOptions>(options =>
{
    options.CheckConsentNeeded = context => true;
    options.MinimumSameSitePolicy = SameSiteMode.None;
    options.Secure = CookieSecurePolicy.Always;
    options.HandleSameSiteCookieCompatibility();
});

builder.Services.AddControllersWithViews(options =>
{
    var policy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
    options.Filters.Add(new AuthorizeFilter(policy));
}).AddMicrosoftIdentityUI();

builder.Services.AddRazorPages();

builder.Services.AddServerSideBlazor()
    .AddMicrosoftIdentityConsentHandler();

builder.Services.AddSingleton<ConnectedUsers>();
builder.Services.AddSingleton<JavascriptWindowResizeHandler>();
builder.Services.AddSingleton<ServerSideValues>();
builder.Services.AddScoped<SemanticMemory>();

//builder.Services.AddControllers();

var app = builder.Build();

var secretClient = app.Services.GetService<SecretClient>();
ServerSideValues.PassthroughTest = (await secretClient.GetSecretAsync("AISite")).Value.Value;

app.UseExceptionHandler(new ExceptionHandlerOptions
{
    ExceptionHandler = async ctx => await Task.Run(() =>
    {
        var feature = ctx.Features.Get<IExceptionHandlerFeature>();
        if (feature?.Error is MsalUiRequiredException
            or { InnerException: MsalUiRequiredException }
            or { InnerException.InnerException: MsalUiRequiredException })
        {
            ctx.Response.Cookies.Delete($"{CookieAuthenticationDefaults.CookiePrefix}{CookieAuthenticationDefaults.AuthenticationScheme}");
            ctx.Response.Redirect(ctx.Request.GetEncodedPathAndQuery());
        }
    }),
    ExceptionHandlingPath = "/Error",
    AllowStatusCode404Response = true
});
if (!app.Environment.IsDevelopment())
{
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseCookiePolicy();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
    endpoints.MapBlazorHub();
    endpoints.MapFallbackToPage("/_Host");
});

app.Run();
```

Method 1: Manual entry

1st layer manually go to:
`https://login.microsoftonline.com/TENANTID/oauth2/v2.0/authorize?client_id=CLIENTID&response_type=code&redirect_uri=https://localhost:PORT/signin-oidc&response_mode=query&scope=openid profile offline_access User.ReadWrite`
to sign in

2nd layer: post x-www-form-urlencoded (used postman for this part)
```
URL: https://login.microsoftonline.com/TENANTID/oauth2/v2.0/token
client_id = same as 1st layer client_id
scope = .default
code = (get from 1st layer)
session_state = same as 1st layer client_id
redirect_uri = https://localhost:PORT/signin-oidc
grant_type = client_credentials
client_secret = what generated in app registration
```

(get access token here)

Method 2: tried Auth Code with PKCE Postman and without

```
callback: https://localhost:PORT/signin-oidc
auth url: https://login.microsoftonline.com/TENANTID/oauth2/v2.0/authorize
token url: https://login.microsoftonline.com/TENANTID/oauth2/v2.0/token
client id: same as 1st layer
client secret: what generated in app registration
Code Challenge Method: SHA-256 (when using PKCE)
Scope: openid profile offline_access User.ReadWrite
State: same as 1st layer client_id
Client Authentication: Tried both basic auth header and send client credentials in body
```

(get access token successfully with every combo here)

when doing curl to get 302 response:
curl -X GET https://localhost:PORT/api/webhook -i -H "Bearer TOKENGOESHERE" gives:
```
HTTP/1.1 302 Found
Content-Length: 0
Date: Fri, 04 Aug 2023 13:04:57 GMT
Server: Kestrel
Location: https://login.microsoftonline.com/TENANTID/oauth2/v2.0/authorize?client_id=CLIENTID&redirect_uri=https%3A%2F%2Flocalhost%3APORTGOESHERE%2Fsignin-oidc&response_type=code&scope=openid%20profile%20offline_access%20User.ReadWrite&code_challenge=HIDDEN&code_challenge_method=S256&response_mode=form_post&nonce=HIDDEN&state=HIDDEN&x-client-SKU=ID_NET6_0&x-client-ver=6.30.0.0
Set-Cookie: (gives cookie info here);  path=/signin-oidc; secure; samesite=none; httponly
```

When trying to Get with postman either with PKCE or not PKCE from method 2, or Bearer token from method 1 directly the body starts with. I have also tried defining and not defining cookies. Every combination still asks for another sign in:
```
<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->
<!DOCTYPE html>
<html dir="ltr" class="" lang="en">

<head>
	<title>Sign in to your account</title>
```

What am I missing?
I tried both methods via: https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-call-a-web-api-with-postman?tabs=dotnet6&pivots=api & curl version and with stack exchange information.

There appears to be a middleware that is causing this issue despite getting a valid token I cannot make calls to the site. I'd like to know the root cause and a solution if possible.

**Comment by jmprieur** [comment]
@wrharper-AASP 
Are you trying to build a web API?
If that's the case you need to use AddMicrosoftWebApi not AddMicrosoftWebApp

**Comment by wrharper-AASP** [comment]
it is both

**Comment by wrharper-AASP** [comment]
oh, i should clarify that if i use the browser directly, the GET works on the controller. so I know it's working in browsers.

**Comment by jmprieur** [comment]
If this is also a web API, you need to add:

```csharp
builder.Services.AddAuthentication()
    .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"));
```

**Comment by wrharper-AASP** [comment]
> 

i'll add it when i can but i'm not seeing how this would have anything to do with it since the same GET url works in the browser.

**Comment by wrharper-AASP** [comment]
since i couldn't just add it to the one already used that is required. I just added it on it's own.
Same issue...

```
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"))
    .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
    .AddMicrosoftGraph(builder.Configuration.GetSection("MicrosoftGraph"))
    .AddInMemoryTokenCaches(options => { options.AbsoluteExpirationRelativeToNow = new TimeSpan(90, 0, 0, 0); });

builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"));
```

**Comment by wrharper-AASP** [comment]
i also tried without OpenID Scheme for the 2nd part:
```
builder.Services.AddAuthentication()
    .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"));
```

**Comment by jmprieur** [comment]
Which controller action do you call? did you set the AuthenticationScheme to JwtBearer on your controller ?

**Comment by wrharper-AASP** [comment]
```
using Microsoft.AspNetCore.Mvc;

namespace AASPAIServerSide.Controllers
{
    //[AllowAnonymous]
    [Route("api/[controller]")]
    [ApiController]
    //[Produces("application/json")]
    //[ValidateAntiForgeryToken]
    //[Authorize]
    //[Authorize(Roles = "Admin, User")]
    public class WebhookController : Controller
    {
        [HttpGet(Name = "webhook")]
        public ActionResult<string> GetJson()
        {
            return "";
        }
    }
}
```

**Comment by wrharper-AASP** [comment]
> Which controller action do you call? did you set the AuthenticationScheme to JwtBearer on your controller ?

The fact that it works in the browser tells me this isn't the issue. That is the key here.... if it works in the browser. why won't it work in postman and why is postman asking me to sign in again with a valid token?

**Comment by wrharper-AASP** [comment]
Personally, I strongly think this has to do with MSAL. It has caused a nightmare of issues over time. I wouldn't be surprised if this is a deeper issue.

**Comment by jmprieur** [comment]
@wrharper-AASP : you need to:
- un-comment the `[Authorize]` attribute and tell ASP.NET Core it that you want to use the JwtBearer authentication scheme.

```csharp
[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
```

At this stage in your controller, MSAL is not used because you don't call web APIs. It's a more fundamental question that web Apps sign in users and return HTML displayed in the browser, whereas web APIs are protected and require an access token and return json, XML, or whatever content you want (And act as a function)

For more information see [Multiple authentication schemes](https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes)

But we would definitively want to understand the nightmare of issues you had, when you have time. + @localden

**Comment by wrharper-AASP** [comment]
> 

IDX10511: Signature validation failed. Keys tried: '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Number of keys in TokenValidationParameters: '8'.
Number of keys in Configuration: '0'.
Matched key was in 'TokenValidationParameters'.
kid: '-KI3Q9nNR7bRofxmeZoXqbHZGew'.
Exceptions caught:
 '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. See https://aka.ms/IDX10511 for details.

**Comment by wrharper-AASP** [comment]
It was a few months ago when MSAL was an issue, and I don't remember what all it was since it is fixed now. I think it had to do with TeamsFx.

**Comment by wrharper-AASP** [comment]
ok this is working now. It looks like the scope needed an api:// instead of what I was doing.
