### ISSUE TITLE
[Feature Request] Cookie options should be settable in `AddMicrosoftWebApp` 

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#237]
**Is your feature request related to a problem? Please describe.**
Cookie options should be settable. For this, `AddMicrosoftWebApp` should have a overload with an action to configure the `CookieAuthenticationOptions`

**Describe the solution you'd like**

The most complex override could be something like the following (note `configureCookieAuthenticationOptions` which is an `Action<CookieAuthenticationOptions>`)

```CSharp
 public static AuthenticationBuilder AddMicrosoftWebApp(
            this AuthenticationBuilder builder,
            Action<OpenIdConnectOptions> configureOpenIdConnectOptions,
            Action<MicrosoftIdentityOptions> configureMicrosoftIdentityOptions,
            Action<CookieAuthenticationOptions> configureCookieAuthenticationOptions,
            string openIdConnectScheme = OpenIdConnectDefaults.AuthenticationScheme,
            string cookieScheme = CookieAuthenticationDefaults.AuthenticationScheme,
            bool subscribeToOpenIdConnectMiddlewareDiagnosticsEvents = false)
        {
```

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
