### ISSUE TITLE
[Bug] Same site compat check needs updating.

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#238]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.5-preview

**Where is the issue?**
* Web App
    * [x ] Sign-in users

Other? - please describe;

**Repro**

[Same site compat check](https://github.com/AzureAD/microsoft-identity-web/blob/0b628e2a56e6525bbca682c50a7528da4d09cc22/src/Microsoft.Identity.Web/CookiePolicyOptionsExtensions.cs#L61) needs updating.

**Expected behavior**
See https://www.chromium.org/updates/same-site/incompatible-clients

**Actual behavior**
https://github.com/AzureAD/microsoft-identity-web/blob/0b628e2a56e6525bbca682c50a7528da4d09cc22/src/Microsoft.Identity.Web/CookiePolicyOptionsExtensions.cs#L61

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
