### ISSUE TITLE
Owin Identity Construction crash if "preferred_username" claim is not present

### ISSUE THREAD

**Issue by guillaumejay** [AzureAD/microsoft-identity-web#2388]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.11.1

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

Current Owin code looks for a very specific claims preferred_username and crash if not present

### Reproduction steps

Use Owin ( test/devapps/asp.net MVC/OwinWebApp application ) on Azure AD B2C without this claims.

### Error message

System.NullReferenceException

### Relevant code snippets

```csharp
This is the problematic webcode :
 string name = context.AuthenticationTicket.Identity.FindFirst("preferred_username").Value;
Microsoft.identy.web.Owin/AppBuilderExtension.Cs
https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.OWIN/AppBuilderExtension.cs#L180
```

### Expected behavior

Read the the claim name from the ClaimNameType name ?

**Comment by guillaumejay** [comment]
This can be fixed in an application by using the UpdateOptions parameters of  AddMicrosoftIdentityWebApp and replace Notifications.SecurityTokenValidated.

It's a bit tedious because you have to copy  the UniqueTenantIdentifier and UniqueObectIdentifier claims filling from the original source code, and it uses internals classes, but it can be done.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.13.4
