### ISSUE TITLE
[Bug] Remove the weird pattern for newing up redundant copies of MicrosoftIdentityOptions

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#239]
**Which Version of Microsoft Identity Web are you using ?
Microsoft Identity Web 0.1.5-preview

**Where is the issue?**
* Web App
    * [x ] Sign-in users
    * [ x] Sign-in users and call web APIs
* Web API
    * [x ] Protected web APIs
    * [x ] Protected web APIs call downstream web APIs

Other? - please describe;

**Repro**

Remove the weird pattern for newing up redundant copies of MicrosoftIdentityOptions
[WebApiAuthenticationBuilderExtensions.cs#L85-L88](https://github.com/AzureAD/microsoft-identity-web/blob/0e68799fc095c0611ccb3cec3a6758568b0f3f7c/src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs#L85-L88)
[WebAppAuthenticationBuilderExtensions.cs#L74-L75](https://github.com/AzureAD/microsoft-identity-web/blob/0e68799fc095c0611ccb3cec3a6758568b0f3f7c/src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs#L74-L75)
[WebApiCallsWebApiAuthenticationBuilderExtensions.cs#L63-L66](https://github.com/AzureAD/microsoft-identity-web/blob/0e68799fc095c0611ccb3cec3a6758568b0f3f7c/src/Microsoft.Identity.Web/WebApiCallsWebApiAuthenticationBuilderExtensions.cs#L63-L66)
[WebAppCallsWebApiAuthenticationBuilderExtensions.cs#L101-L102](https://github.com/AzureAD/microsoft-identity-web/blob/0e68799fc095c0611ccb3cec3a6758568b0f3f7c/src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs#L101-L102)

**Expected behavior**
-	Injecting something IOptions<MicrosoftIdentityOptions> from the container (in 5.0)
-	In 3.1. @Chris will provide an ugly work around.

See also https://github.com/AzureAD/microsoft-identity-web/issues/234 which leverages the same mechanism

**Proposed design**
- in https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs#L83, we already have a service provider. 
 1. Use it to get a required service of IOptions<MicrosoftIdentityOptions>. 
  ```CSharp
  MicrosoftIdentityOptions microsoftIdentityOptions = serviceProvider.GetRequiredService<IOptions<MicrosoftIdentityOptions>>().Value;
  ```
 2. Note that it's not needed to call `configureMicrosoftIdentityOptions(microsoftIdentityOptions);` because it's called automatically as registered by : https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs#L72

- same thing for https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs#L110, but the lines involving the MicrosoftIdentityOptions should be moved inside the `builder.AddOpenIdConnect` callback. The code could be something like:
  ```CSharp
    builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<IValidateOptions<MicrosoftIdentityOptions>, MicrosoftIdentityOptionsValidation>());

  #if DOTNET_CORE_31
            builder.AddOpenIdConnect(openIdConnectScheme, options =>
            {
                // TODO: replace by the work around that @Tratcher will provider
                IServiceProvider serviceProvider = builder.Services.BuildServiceProvider();
  #else
            builder.AddOpenIdConnect<IServiceProvider>(openIdConnectScheme, (options, serviceProvider) =>
            {
  #endif
                MicrosoftIdentityOptions microsoftIdentityOptions = serviceProvider.GetRequiredService<IOptions<MicrosoftIdentityOptions>>().Value;
  ```

- in https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/WebApiCallsWebApiAuthenticationBuilderExtensions.cs#L78 and https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs#L124, do something similar as in the previous 2 files.

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
