### ISSUE TITLE
Updating to 2.13.3 from 2.11.0 causes unexpected runtime error - no build failure.

### ISSUE THREAD

**Issue by erik-at-myopyn** [AzureAD/microsoft-identity-web#2392]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.13.3

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

My company has an in-house core library that includes this package as part of its user authentication processing. Yesterday a peer that manages that package updated to the latest version of this package `2.13.3` from `2.11.0`. There was no warnings or errors indicating any breaking changes with our integrations.

Today I was doing an update to our API service that uses this library and loading our UI to test the API I found our Sign-in and Session processes were failing, throwing this exception on sign-in:
`IDX10720: Unable to create KeyedHashAlgorithm for algorithm 'HS256', the key size must be greater than: '256' bits, key has '208' bits. (Parameter 'keyBytes')`

After a few hours of researching and trial-and-error reverting packages that were changed we were able to confirm it was this package update that broke our auth service.

### Reproduction steps

1. Have a working Blazor Client application that talks to an API service that uses this package with version `2.11.0`.
2. Update package to version `2.13.3`.
3. Try signing in to Blazor Client, API throws noted exception.

### Error message

IDX10720: Unable to create KeyedHashAlgorithm for algorithm 'HS256', the key size must be greater than: '256' bits, key has '208' bits. (Parameter 'keyBytes')

### Relevant code snippets

```csharp
<PackageReference Include="Microsoft.Identity.Web" Version="2.13.3" />
```
```


### Regression

2.11.0

### Expected behavior

Either existing functionality continues working the same, or introduce at least warnings if not errors to indicate breaking changes in behavior, and hopefully additional instructions to fix broken processes after migrating to new versions.

**Comment by jennyf19** [comment]
@erik-at-myopyn 
For security reasons, you need to use a larger key, of 256 bits. That will resolve the issue. 

It's actually coming from Microsoft.IdentityModel which addressed this issue [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1743
