### ISSUE TITLE
msidentity-app-sync Connection coming from a different IP address?

### ISSUE THREAD

**Issue by A9G-Data-Droid** [AzureAD/microsoft-identity-web#2393]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

msidentity-app-sync version 1.0.1

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

When running `msidentity-app-sync` I get a failure due to my conditional access policy geo-location. Reviewing the Azure Portal Sign-In log I can see that the failed request is not coming from my own IP address, as one might expect.

The location is listed as:

> Location	Gavle, Gavleborgs Lan, SE
> IP address	4.225.168.9
> Autonomous system number	8075
> 
> Named location type    Location name
> No network details

This begs the question: **Why would this tool be routing calls through a server in Sweden?**

Is this expected? Can it be changed?

### Reproduction steps

1. `dotnet tool install --global msidentity-app-sync`
2. `msidentity-app-sync --username <username/upn> --tenant-id <tenantID>`

### Error message

> http request failed with errorcode: BadRequest, Content:{"error":"invalid_grant","error_description":"AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.

### Relevant code snippets

```csharp
Simply attempt to use the `msidentity-app-sync`. Requests come from Sweden...
```

### Expected behavior

I would expect the connection to come directly from my development PC and go directly to my tenant.

**Comment by jmprieur** [comment]
@A9G-Data-Droid the tool itself is not routing anything. It just uses the MS Graph SDK.
Would you have something on your machine or your network that does re-route the IP addresses? 
For example the Global Secure Access Client?

**Comment by A9G-Data-Droid** [comment]
No. Due to the conditional access policy, if this were the case then nothing would work. I wouldn't be able to get my email or use any other Azure service. I use AzureAD authentication for a large number of things, including many Application Registrations. This is the only time I've ever seen this happen. I manually configured the Application Registration just now and it works fine. It's just this tool.

**Comment by jennyf19** [comment]
@A9G-Data-Droid The source code is [here](https://github.com/AzureAD/microsoft-identity-web/tree/master/tools/app-provisioning-tool).
