### ISSUE TITLE
[Fundamentals] Automate webAppCallsWebApiCallGraph using playwright

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#2395]
Two tasks
[ ] automate [web app calls web API calls graph](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/DevApps/WebAppCallsWebApiCallsGraph) using playwright
[ ] automate [B2C web app calls web API](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/DevApps/B2CWebAppCallsWebApi) with playwright

**Comment by JoshLozensky** [comment]
Completed with this PR https://github.com/AzureAD/microsoft-identity-web/pull/2475
