### ISSUE TITLE
Bearer error="invalid_token"

### ISSUE THREAD

**Issue by derodevil** [AzureAD/microsoft-identity-web#2396]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.13.3

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

I got this error when updating from 2.13.1 to 2.13.2 or 2.13.3

### Reproduction steps

1. Install via nuget version 2.13.1 and it runs well.
2. Update to version 1.13.3 and the error message appears

### Error message

The error message is from response header: Bearer error="invalid_token"

### Relevant code snippets

```csharp
services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(options =>
{
    options.Events = new JwtBearerEvents();
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateAudience = false,
        ValidateSignatureLast = false,
        SignatureValidator = delegate (string token, TokenValidationParameters parameters)
        {
            var jwt = new JwtSecurityToken(token);
            return jwt;
        }
    };
}, options =>
{
    options.TenantId = configuration["AD:TenantId"];
    options.ClientId = configuration["AD:ClientId"];
    options.Instance = "https://login.microsoftonline.com/";
    options.ClientSecret = configuration["AD:ClientSecret"];
}).EnableTokenAcquisitionToCallDownstreamApi(options =>
{
    options.TenantId = configuration["AD:TenantId"];
    options.ClientId = configuration["AD:ClientId"];
    options.Instance = "https://login.microsoftonline.com/";
    options.ClientSecret = configuration["AD:ClientSecret"];
}).AddInMemoryTokenCaches();
```

### Regression

2.13.1

### Expected behavior

The token should be well validated without 401 response.

**Comment by jmprieur** [comment]
Hello @derodevil 
What are you trying to do by newing-up a JwtSecurityToken? It's not using the token validation parameters and is duplicating wha the JwtBearer authentication handlers is already doing.

What is your scenario? so that we can help you.

**Comment by derodevil** [comment]
I have a backend web API where the code above is written. I also have a frontend written in Reactjs and it calls the web API where every single request has an authorization header token. The web API needs to validate the incoming that Azure AD JWT token header request. So, it would look like this:
Frontend (user login to AAD) -> Frontend accesses this API <--> If the token is valid it will be authorized otherwise rejected.
The code above runs well when I use version 2.13.1. Unfortunately, it produces invalid_token when I upgrate to latest version 2.13.3. Please advise me if the code is wrong.

**Comment by jmprieur** [comment]
The following should be enough.

```csharp
services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(options => Configuration.Bind("AD", options))
.EnableTokenAcquisitionToCallDownstreamApi()
.AddInMemoryTokenCaches();
```

**Comment by derodevil** [comment]
@jmprieur Unfortunately, it still produces the same error

**Comment by jmprieur** [comment]
Where do you get the token from?
Did you set the "Audience" to the App ID URI of your app?

**Comment by derodevil** [comment]
From the frontend where it logins and gets the token then sends the token to the backend API.
I didn't validate it because it's error.

This is the code to acquire the token
![935866cc-59e9-461c-b1f0-07270f135e19](https://github.com/AzureAD/microsoft-identity-web/assets/4223012/32ec4438-6f8a-4eee-9895-76aada7f9d70)

**Comment by jmprieur** [comment]
@derodevil : Isn't the token signed?
Is it for Azure AD?

**Comment by jmprieur** [comment]
@derodevil closing this issue since you didn't reply
We really don't advise your service to accept un-signed tokens,
