### ISSUE TITLE
[Bug] Fix the weird DI anti-pattern: Resolving ITokenAcquisition but then cast it to ITokenAcquisitionInternal.

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#240]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.5-preview

**Is this a new or existing app?**

**Repro**

Look at:
[WebAppCallsWebApiAuthenticationBuilderExtensions.cs#L129](https://github.com/AzureAD/microsoft-identity-web/blob/57184a32eb4dc97db0309d7e78002f5bb080f68a/src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs#L129)
[WebAppCallsWebApiAuthenticationBuilderExtensions.cs#L163](https://github.com/AzureAD/microsoft-identity-web/blob/57184a32eb4dc97db0309d7e78002f5bb080f68a/src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs#L163)

**Expected behavior**

We'd want to write code requesting only the `ITokenAcquisitionInternal`

```CSharp
                options.Events.OnAuthorizationCodeReceived = async context =>
                {
                    var tokenAcquisition = context.HttpContext.RequestServices.GetRequiredService<ITokenAcquisitionInternal>();
                    await tokenAcquisition.AddAccountToCacheFromAuthorizationCodeAsync(context, options.Scope).ConfigureAwait(false);
                    await codeReceivedHandler(context).ConfigureAwait(false);
                };
```

```CSharp
                options.Events.OnRedirectToIdentityProviderForSignOut = async context =>
                {
                    // Remove the account from MSAL.NET token cache
                    var tokenAcquisition = context.HttpContext.RequestServices.GetRequiredService<ITokenAcquisitionInternal>();
                    await tokenAcquisition.RemoveAccountAsync(context).ConfigureAwait(false);
                    await signOutHandler(context).ConfigureAwait(false);
                };
```

**How to achieve this?**

- Make one interface inherit from the other
- In the DI container, we can do a registration that delegates to another registration. See an example in the .NET runtime code: [https://github.com/dotnet/runtime/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L214](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L214). So there is one normal registration and the other references the first one. Makes sense when one interface inherits from the other. Have to register it twice.
Needs to use the delegate form so that we get the same copy within the scope.

** Possible design**
1. Have `ITokenAcquisitionInternal` inherit from `ITokenAcquisition`
2.  In **ServiceCollectionExtensions.cs** update the `AddTokenAcquisition` method to register the ITokenAcquisition service and the ITokenAcquistionInternal service, but turning out to be the same instance.

   ```CSharp
                services.AddScoped<ITokenAcquisition, TokenAcquisition>();
                services.AddScoped<ITokenAcquisitionInternal>(s => (ITokenAcquisitionInternal)s.GetService<ITokenAcquisition>());
   ```

(and same for the singleton)

3. Change WebAppCallsWebApiAuthenticationBuilderExtensions.cs and WebAppCallsWebApiAuthenticationBuilderExtensions.cs to use only `ITokenAcquisitionInternal`

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
