### ISSUE TITLE
User.Identity.Name is null in ASP.NET Core Web API

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#2406]
My Web API is secured by access token: 

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMicrosoftIdentityWebApiAuthentication(Configuration);
            services.AddControllers();
        }
```

However in the controller actions, ```User.Identity.Name``` is null even though ```User.Identity.IsAuthenticated``` is true and ```User.Identity.Claims``` contains the claims from the access token. 

I understand that this is just a matter of mapping the correct claim
 to ```User.Identity.Name```, but found no way to customize the mapping with ```AddMicrosoftIdentityWebApiAuthentication()```. Do I have to switch to using ```AddJwtBearer()``` which allows configuring claim mapping? (https://stackoverflow.com/questions/68682161/asp-net-core-3-1-user-identity-name-is-empty-in-api-controller-but-claim-name)

Thanks in advance for suggestions.

**Comment by jmprieur** [comment]
@WenningQiu 

Did you try:

```csharp
            services.Configure<OpenIdConnectOptions>(JwtBearerDefaults.AuthenticationScheme, options =>
            {
                // The claim in the Jwt token where Name is available.
                options.TokenValidationParameters.NameClaimType = "preferred_username";
            });
```

Assuming you are using Azure AD (not B2C). you can also adjust to another claim that contains the name.

**Comment by WenningQiu** [comment]
@jmprieur I am still getting null ```User.Identity.Name``` with Bearer configuration as below: 

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<OpenIdConnectOptions>(JwtBearerDefaults.AuthenticationScheme, options =>
            {
                options.TokenValidationParameters.NameClaimType = "preferred_username";
            });

            services.AddMicrosoftIdentityWebApiAuthentication(Configuration);
            
            services.AddControllers();
        }
```
I do have ```preferred_username``` claim:
![image](https://github.com/AzureAD/microsoft-identity-web/assets/4291622/1656dc63-d599-4f49-8744-ef76ab3bda6d)

**Comment by WenningQiu** [comment]
@jmprieur  No I did not try that. I had moved on by retrieving claims directly.

**Comment by jmprieur** [comment]
Thanks for the update, @WenningQiu
Closing the question

**Comment by jtrotman10** [comment]
I was able to get this working by adding this to my configuration in the "AzureAd" section (along with ClientId, etc.)

"TokenValidationParameters": {
  "NameClaimType": "preferred_username"
}

**Comment by WenningQiu** [comment]
@jtrotman10 Thanks!
