### ISSUE TITLE
Is this package supposed to work with WebForms ?

### ISSUE THREAD

**Issue by guillaumejay** [AzureAD/microsoft-identity-web#2408]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.13.3

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

I'm trying to make this packaged work in WebForms, using OWin, Azure ADB2C (redirect mode).

I can't make it work.
Main issue is that when :
        HttpContextBase httpContext =
            context.OwinContext.Get<HttpContextBase>(typeof(HttpContextBase).FullName);
httpContext.Session is null, which is problematic for some treatment in Microsft.Identity.Web.Owin

I f I use the Asp.Net Web Application (.net Framework), select MVC application and then add Webforms and web API, it works.
I f I use the Asp.Net Web Application (.net Framework), select WebForms application and then add MVCand web API, it does not work.

### Reproduction steps

Create a WebForms application, add this pacakge and configuration.

### Relevant code snippets

```csharp
app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

app.UseCookieAuthentication(new CookieAuthenticationOptions());

OwinTokenAcquirerFactory factory = TokenAcquirerFactory.GetDefaultInstance<OwinTokenAcquirerFactory>();

app.AddMicrosoftIdentityWebApp(factory,null,UpdateOptions);
factory.Services
    .Configure<ConfidentialClientApplicationOptions>(options =>
    {
        options.RedirectUri = "https://localhost:44386/";
        
    })

    .AddInMemoryTokenCaches();
factory.Build();
```

### Expected behavior

Working on a legacy webforms application

**Comment by jmprieur** [comment]
@guillaumejay 
We definitively didn't think Id.Web could be use with Web forms but we're glad you made it work. Adding a controller and the authorize attribute is the way it's meant to be used, so I would say this makes sense.

**Comment by rastrup** [comment]
> I was able to make it work by :
> 
> 1. removing all authentication and authorization tags in web.config (I was using them to start the redirect user flow, so I needed another            app.UseStageMarker(PipelineStage.Authenticate) in authConfig which was the problem
> 2. using a mvc controller (in my web forms application) with the Authorize annotation  (to start the redirect userflow)
> 3. after returning to my mvc controller, going back to my regular aspx pages.
> 
> I'm not sure there's not a better way for step 2

I do not fully get your step 1.
Was  app.UseStageMarker(PipelineStage.Authenticate) the problem and needed removal or was it the solution that you needed to add?

**Comment by guillaumejay** [comment]
I had to remove from web.config
`	<authentication mode="Forms">
		<forms name=".AUTH" loginUrl="Account/LoginDRW.aspx" timeout="10000" />
	</authentication>
`

so that the UseStageMarker could register correctly (I suppose)

For adding MVC controller to webforms, I just add to use a Controller derived class, and add routing. (I already add a webapi in the project, but there's lot of documentatin about adding some MVC to a webforms application)
