### ISSUE TITLE
[Feature Request] EnableCacheSynchronization should be false by default

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#2413]
**Is your feature request related to a problem? Please describe.**
In the next version MSAL will set `EnableCacheSynchronization` flag to true by default. (This will help to make singleton cache consistent.) This flag should be false by default in Identity Web to not affect the users. This is similar to the `LegacyCacheCompatibilityEnabled` (#1268).

**Comment by jmprieur** [comment]
Would it be ok to set it to true only for singletons?

**Comment by jmprieur** [comment]
IDWeb is fine with the MSAL default
