### ISSUE TITLE
[Feature Request] Introduce a lock while loading credentials from Credential Source

### ISSUE THREAD

**Issue by sruke** [AzureAD/microsoft-identity-web#2439]
**Is your feature request related to a problem? Please describe.**
Today it is possible for multiple requests to attempt to load the same CredentialDescription from the same source when DefaultCredentialsLoader.LoadCredentialsIfNeededAsync API is invoked. This can be expensive when the HTTP request needs to be sent to access a certificate from KeyVault. 

**Describe the solution you'd like**
Introduce a lock such that only a single request is attempting to load the same CredentialDescription. Allow concurrent loading of different credentialDescriptions. A request should be able to access and read the value of the credentialDescription.CachedValue property to recognize that a given credential has already been loaded and cached, thereby preventing unnecessary thread blocking.

Microsoft recommends using the SemaphoreSlim class for synchronization within a single app

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.13.4
