### ISSUE TITLE
[Bug] TokenAcquisition. Dictionary remove+add. Call Indexer Set instead

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#244]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 1.0.0-preview

Look at https://github.com/AzureAD/microsoft-identity-web/blob/57184a32eb4dc97db0309d7e78002f5bb080f68a/src/Microsoft.Identity.Web/TokenAcquisition.cs#L537-L542

We can replace it with one call to Set instead of remove and add.

that is replace these 5 lines of code by

```CSharp
            headers[HeaderNames.WWWAuthenticate] = v;
```

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
