### ISSUE TITLE
[Bug] Read the userinfo endpoint values from the protocol message rather than the form

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#245]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.5-preview 

Today, we read the returned values from the user info endpoint [from the form](https://github.com/AzureAD/microsoft-identity-web/blob/57184a32eb4dc97db0309d7e78002f5bb080f68a/src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs#L136-L139) whereas we could read them from the protocol message directly (as the whole content of the Form was [already copied](https://github.com/dotnet/aspnetcore/blob/724c2e75a7415e67f9f5ad33fc72bf55507b8d59/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L92) in the protocol message)

This is not broken. Just weird

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
