### ISSUE TITLE
[Bug] Unable to retrieve certificate from key vault when using ITokenAcquisition

### ISSUE THREAD

**Issue by rajravat** [AzureAD/microsoft-identity-web#2457]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.13.3

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

In my startup code i have the following configured:

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/3820ab5a-b858-4bdb-8b72-3ec2a7a5b119)

my environment variables are setup as below:
![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/5211ed10-19d3-4172-bdf9-836ddb68c660)

i'm using the token acquisition service as below:
![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/ea374dbe-907e-40d0-a74c-f6588c32f570)

My app is hosted inside a container app, with a user managed identity, which has the relevant RBAC access to key vault.

For local dev inside visual studio, the code works fine (using my visual studio credentials), however when it is deployed to a container app, it doesn't seem to pick up the user managed identity, the error i get is below:

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/56b9294e-d400-4ee4-b797-712c4110f658)

The odd thing is, if i use DefaultAzureCredential programmatically and try to access key vault, it works correctly using the managed user identity configured in my container app, for example, the following code below works fine:

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/1ae036af-04b3-4011-9bb6-37e26d74ffcf)

It also works as expected doing a similar thing to access azure service bus, so it seems to be something specific to the microsoft.identity.web token acquisition call.

On the official documentation (https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates#getting-certificates-from-key-vault) it states to set AZURE_CLIENT_ID to the clientId of the managed user identity, i have tried this but it gives me the same error - with or without the environment variable set in my container.

If i switch on System managed identity on my container app, and give it the correct keyvault permissions, it works successfully without any code changes.

Any ideas what could be preventing user managed identity working? 
 

### Reproduction steps

1. Setup a certificate in key vault
2. Setup an app inside a container app
3. Setup a user managed identity for the container app
4. Assign relevant permissions to the managed identity to access key vault
5. Setup a webapi project using the snippets of code in the post.

### Error message

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/6f36e4c3-7b5b-402c-8c6f-511cec1c7cf7)

### Relevant code snippets

As shown above

### Expected behavior

After setting AZURE_CLIENT_ID to be the clientid of my user assigned managed identity, i would expect it would use this identity to fetch the certificate from keyvault to enable me to make a downstream api call.

snippets from my bicep file setting the environment variable:

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/b142d103-a17e-4cc7-8447-61a8c8ab5a93)

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/c209a844-c14d-4f52-91dc-6e07934df444)

**Comment by rajravat** [comment]
I did some additional debugging and have got some more insight into why its not working

In the call that works e.g. this one below:
![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/0d0a63e6-00c3-421b-949e-b991b7e2f2c8)

the trace logs show it is passing resource and client_id to get a token: 
![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/f3b4479c-5236-4fca-b931-0615f5d1c460)

however, in the code that doesnt work:
![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/78145905-5417-4b7a-9935-230a123f934a)

the trace logs show it doesnt pass the client_id:
![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/b96b316f-535b-493e-810f-4842359785e1)

I dont understand why there are differences for the same app, i tried to have a look at the source code for KeyVaultCertificateLoader , but it looks like that eventually just uses DefaultAzureCredential and sets the managed user identity:
![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/1bc5b435-72b2-4ec1-98b4-dc2b571c5109)
i can only think it is somehow setting it to null or an invalid value. I have even tried to set DefaultCertificateLoader.UserAssignedManagedIdentityClientId just before the token call, but that doesnt seem to work either.

**Comment by rajravat** [comment]
After spending more time trawling through the code, I have found a way to make it work for my use case. Inside KeyVaultCertificateLoader there is the following code:

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/f48cafe4-e651-4c8c-a273-e07fdb8eeab0)
So if i set my user managed identity to be part of the certificate description, it will pick that over the static property on the class, when i do this it works as expected, although it does mean i have to end up setting two environment variables to the same property.

e.g. 'Azure_Client_Id' (for places that use DefaultAzureCredential without explicitly setting the managed identity) and then 'AzureAd__ClientCredentials__0__ManagedIdentityClientId' for the specific use case of fetching the cert from keyvault.

This wouldnt be necessary if the ManagedIdentityClientId wasnt set explicitly inside the file:

![image](https://github.com/AzureAD/microsoft-identity-web/assets/25839791/5d6cc9c5-807f-4c86-8a40-d4e0a01ae3aa)

**Comment by jmprieur** [comment]
Thanks @rajravat.
yes, setting the managed identity client Id was the way in Id.Web v1.0, and we kept it for backwards compatibility reasons.
We'll see what we can do to improve, but it seems you have a work around now with the 2 variables?

Not sure if you really need AZURE_CLIENT_ID?

**Comment by rajravat** [comment]
Thanks for responding, is there a risk the managed identity client id will be removed in future versions? Is there an alternative recommended way to set a user managed identity for key vault?

In my use case I require azure_client_id too because I have other code paths that use DefaultAzureCredentials (azure service bus) that requires this to be set for a user managed identity.

**Comment by jmprieur** [comment]
>  is there a risk the managed identity client id will be removed in future versions? 

which one, @rajravat ? the global one?

**Comment by rajravat** [comment]
sorry i was referring to this one: AzureAd__ClientCredentials__0__ManagedIdentityClientId

**Comment by jmprieur** [comment]
no. This one will remain.
Thanks for sharing your findings.
