### ISSUE TITLE
[Bug] Don't call HandleCodeRedemption twice in TokenAcquisition.cs#L125-L128

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#246]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.5-preview

**Where is the issue?

*In https://github.com/AzureAD/microsoft-identity-web/blob/0b628e2a56e6525bbca682c50a7528da4d09cc22/src/Microsoft.Identity.Web/TokenAcquisition.cs#L125-L128, verify that we still need to handle the code redemption twice. This should not be needed and is the sign smell like someone is using async void. 

**Why is it so?**
We had many cases, in the past, where the code was redeemed twice (once by Microsoft.Identity.Web and once by ASP.NET Core), which is not allowed by Azure AD.
However, async should ensure that this works fine.

**What to do?**
If this bugs, then the bug needs to be fixed.

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
