### ISSUE TITLE
[Bug] Avoid IHttpContextAccessor as much as possible.

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#248]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.5-preview

**Repro**
Avoid IHttpContextAccessor as much as possible:
- It gives a false sense of security. Everywhere where we can access the HttpContext directly we should do so. It’s not obvious in the multi-threaded methods that they use the HttpContext (which is not thread safe). Hiding that we use it leads to unsafe use.
- A lot of time, the HttpContext is passed to access one field. There is a balance between the simple developer experience and 
  the safety. Secretly accessing the HttpContext is not on the right side of the balance. For   instance:   
  ReplyForbiddenWithWwwAuthenticateHeader should pass in the HttpContext rather than relying on the accessor, it's called directly from a controller anyways   (See [TokenAcquisition.cs#L506](https://github.com/AzureAD/microsoft-identity-web/blob/0b628e2a56e6525bbca682c50a7528da4d09cc22/src/Microsoft.Identity.Web/TokenAcquisition.cs#L506))

requires more spec.

**Comment by jmprieur** [comment]
@jennyf19 : the work you've been doing on adding suggested cache key in the TokenSerializationArgs will remove a lot of this work

**Comment by jmprieur** [comment]
Blocked until we have the cacheKey for the token cache providers.

**Comment by jmprieur** [comment]
Verified we've removed all what we could.

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
