### ISSUE TITLE
[Documentation] - Clarify Azure Functions Support

### ISSUE THREAD

**Issue by dirthsj** [AzureAD/microsoft-identity-web#2482]
### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

Currently, the azure functions documentation makes no mention of the issues surrounding Azure Functions support, e.g. #1548 which has been open for nearly two years.

Please update documentation to specify which version(s) of Azure Functions are supported and link to relevant issues users may encounter when attempting to use this library with Azure Functions.

**Comment by jennyf19** [comment]
Azure functions is supported, but please use .NET 8+ Isolated model, as there were issues with the previous .NET versions, hence the open issues for an extended period of time. 
closing, but please re-open if needed.
