### ISSUE TITLE
Problem trying to support two domains for Azure Ad B2C (Protected Web API)

### ISSUE THREAD

**Issue by munkii** [AzureAD/microsoft-identity-web#2486]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.13.4

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

We have an exisiting Protected Web API that supports calls from Azure Ad accounts and Azure B2C.

We want to use Azure Front Door to create a custom name so that in our app the user logs into a domain such as https://account.dev.ourproduct.com rather than https://ourproductdevb2c.b2clogin.com.  We will need to support existing clients as well as new ones that are logging in from the custom domain. 

I have successfuly converted over our Azure Function away from "EasyAuth" to use System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler and Microsoft.IdentityModel.Protocols.ConfigurationManager.
Using a TokenValidationParameters I set multiple ValidIssuers covering the old and new domains, I retrieve the OpenIdConnectConfiguration explicity using a url build with the custom domain  and a ConfigurationManager<OpenIdConnectConfiguration>.GetConfigurationAsync call. This all works and supports both domains.

In the examples I have replaced our tenant name with "OurTenantName" and our tenant id with "OurTenantId"  obviously this is normally a GUID.

The  "Protected Web API"  does not work. It is an ASPNET Core Web API. I have included our startup code in "Relevant code snippets"

### Reproduction steps

If i set the jwtBearerOptions.Authority to be the cusom domain that will work for clients that signed in and got their tokewn against that custom domain. However it will fail agsinst clients that signed in against  the domain "https://OurTenantName.b2clogin.com"

If i switch the Authority the opposite happens, old clients work, new ones do not.

### Error message

Whether it works or not I can see one IDX40001 for every call in the VS2022 output window running on my desktop

> IDX40001: Issuer: 'https://Our.CustomDomain/TenantId/v2.0/', does not match any of the valid issuers provided for this application. 

or

> IDX40001: Issuer: 'https://OurTenantName/TenantId/v2.0/', does not match any of the valid issuers provided for this application. 

In Application Insights I get much more information

> 
> IDX10264: Reading issuer signing keys from validation parameters and configuration.
> IDX10265: Reading issuer signing keys from configuration.
> IDX10243: Reading issuer signing keys from validation parameters.
> IDX10243: Reading issuer signing keys from validation parameters.
> IDX10265: Reading issuer signing keys from configuration.
> IDX10239: Lifetime of the token is valid.
> IDX40001: Issuer: 'https://OurTenantName.b2clogin.com/OurTenantId/v2.0/', does not match any of the valid issuers provided for this application.
> Bearer was not authenticated. Failure message: IDX40001: Issuer: 'https://OurTenantName.b2clogin.com/OurTenantId/v2.0/', does not match any of the valid issuers provided for this application.
> 

### Relevant code snippets

```csharp
services.AddAuthentication()
        .AddMicrosoftIdentityWebApi(
            jwtBearerOptions =>
                                {
                    jwtBearerOptions.Audience = "https://OurAzureAppName.BreatheRMDevB2C.onmicrosoft.com/user_impersonation";
                    ////jwtBearerOptions.Authority = "https://OurB2cTenantName.b2clogin.com/tfp/OurTendantId/B2C_1A_signin_only";
                    jwtBearerOptions.Authority = "https://Our.CustomDomain/tfp/OurTendantId/B2C_1A_signin_only";
                    jwtBearerOptions.TokenValidationParameters.ValidAudiences = new string[2]
                                                                                            {
                                                                                                    "OurAppClientId",
                                                                                                    "https://OurAzureAppName.OurB2cTenantName.onmicrosoft.com/user_impersonation",
                                                                                            };
                                },
            microsoftIdentityOptions =>
                                    {
                    microsoftIdentityOptions.ClientId = "OurAppClientId";
                    microsoftIdentityOptions.Instance = "https://account.dev.breatherm.com";
                    microsoftIdentityOptions.TenantId = "OurTendantId";
                                    },
            "B2CScheme",
            true);

```
```


### Regression

_No response_

### Expected behavior

The calls would be valid from either domain

**Comment by jennyf19** [comment]
@munkii are you using multiple authentication schemes, see this [doc](https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes) for details.

**Comment by munkii** [comment]
We do already use multiple authentication schemes as we are securing some of the APIs against Azure AD as well Azure AD B2C. So we have two.

Are you saying that to support the custom domain even though it is to the same B2C tenant we would have a third authentication scheme, same TenantId, TernantName and Client Id but a different Instance?

**Comment by jmprieur** [comment]
Custom domaine?
What is the share of the authority ?

**Comment by munkii** [comment]
> Custom domaine?
Yes, using Azure FrontDoor we are presenting users with a custom domain when they log in on the app.

Currently users login with this URL
https://{ourtenantname}.b2clogin.com/tfp/{ourtenantname}.onmicrosoft.com/b2c_1a_signin_only/oauth2/v2.0/authorize

We want to be able use this url in future
https://account.{ourproduct.com}/tfp/{OurTenantGuid}/b2c_1a_signin_only//oauth2/v2.0/authorize

We need to be able to support both going forward because of exisitng clients using the original url

> What is the share of the authority ?
Sorry but I don't know what you mean by "share of"

**Comment by jmprieur** [comment]
Yes, I would use a 3rd authentication scheme.

**Comment by munkii** [comment]
FWIW I tried using a 3rd authentication scheme last week when I assumed that's what you were suggesting. However I could not get it to work.

 I am heartened by your closing of the issue as I'll take that as confidence that this scenario is supported and will work. I will try again today and report back, here

**Comment by munkii** [comment]
**UPDATE**
Whilst the App Service is allowing and denying requests as expected it is also generating 30 failures a minute in Application Insights and that is with only two clienys in a development environment. The failure is 

> IDX40001: Issuer: 'https://account.dev.OurCustomDomain.com/{OurTenantId}/v2.0/', does not match any of the valid issuers provided for this application.

We obviously cannot go ahead with code that does that. Therefore I have looked into overriding the `JwtOptions TokenValidationParameters.IssuerValidator`. I can find no documentationon how to implement an IssuerValidator and to be honest the fact that returns a string rather than a bool (Valid/NotValid) is confusing. However this is how I have implemented it and this does indeed stop all the IDX40001s

```
private string IssuerValidator(string issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
{
    string matchedIssuer = null;

    foreach (var iss in validationParameters.ValidIssuers)
    {
        if (iss.Equals(issuer))
        {
            matchedIssuer = iss;
        }
    }

    return matchedIssuer;
}

```

Does that look OK? Should I be paying more attention to `securityToken`?

**Comment by munkii** [comment]
I have tried implmenting `jwtBearerOptions.TokenValidationParameters.IssuerValidator` and `jwtBearerOptions.TokenValidationParameters.IssuerValidatorUsingConfiguration` seperately and at the same time and still I end up with 

> IDX40001: Issuer: 'https://account.dev.breatherm.com/6b10e302-689c-4093-bc9f-310c0fa8457a/v2.0/', does not match any of the valid issuers provided for this application.
> 
> Severity Level 3
> 

In App Insights TRACES table but they are not logged as "Failures" in AppInsights. Do i just give up trying to prevent this and just ignore it. My implmenetations of the validator are being called and it is not me throwing the Exceptions but looking at the src in Github I cannot see where else thoise 40001 entries are being logged

**Comment by munkii** [comment]
@jmprieur any more thoughts on this?

**Comment by wouterSeyen** [comment]
I have the exact same issue: 2 custom domains on an Azure B2C tenant and the IDX40001 error because the issuer validation fails for one of the 2 domains, but successful API calls because it succeeds for the other.
So I'm wondering if you ever found a solution for this issue?

**Comment by munkii** [comment]
I am no longer seeing IDX40001 warnings although it do get 

- IDX10241
- IDX10245
- IDX10234
- IDX10239
- IDX10242

At first these were disconcerting and i misread them as issues but they are in fact just severityLevel 1 (Information) and they are all positive such as `IDX10234: Audience Validated.Audience: 'https://ourdomain.co.uk/product.service'`

Note I am implementing an IssuerValidatorUsingConfiguration and filling TokenValidationParameters.ValidIssuers.

The last issue I have and one I want to remove is the following warning

> Issuer https://sts.windows.net/c57a8fd4-92eb-430b-b902-8dedd228fbea/ not valid

That warning is being thrown by me in my implementation of IssuerValidatorUsingConfiguration

```
public static string IssuerValidatorUsingConfiguration(string issuer, SecurityToken securityToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
{
    _ = issuer ?? throw LogHelper.LogArgumentNullException(nameof(issuer));
    _ = securityToken ?? throw LogHelper.LogArgumentNullException(nameof(securityToken));
    _ = validationParameters ?? throw LogHelper.LogArgumentNullException(nameof(validationParameters));

    string tenantId = IssueValidationHelper.GetTenantIdFromToken(securityToken);

    if (string.IsNullOrWhiteSpace(tenantId))
    {
        // Used to pass LogMessages.IDX40003 to Exception
        throw LogHelper.LogExceptionMessage(new SecurityTokenInvalidIssuerException("Pseudo IDX40003"));
    }

    if (validationParameters.ValidIssuers != null)
    {
        foreach (var validIssuerTemplate in validationParameters.ValidIssuers)
        {
            if (IssueValidationHelper.IsValidIssuer(validIssuerTemplate, tenantId, issuer))
            {
                return issuer;
            }
        }
    }

    if (validationParameters.ValidIssuer != null)
    {
        if (IssueValidationHelper.IsValidIssuer(validationParameters.ValidIssuer, tenantId, issuer))
        {
            return issuer;
        }
    }

    // If a valid issuer is not found, throw
    throw LogHelper.LogExceptionMessage(
        new SecurityTokenInvalidIssuerException(
            LogHelper.FormatInvariant(
                "Issuer {0} not valid",
                LogHelper.MarkAsNonPII(issuer))));
}
```

Should I add a check against the well known issuer "template" of https://sts.windows.net/{tenantid}?

**Comment by johnwc** [comment]
BTW, here's a way to use bearer scheme for all. Essentially what it does is register three different schemes using unique names, then it creates a policy scheme for bearer that takes the received token and reads the tfp claim, which contains the B2C policy name. Based on the value of the tfp claim, it forwards the authentication operation on to one of the three other schemes. We had to implement this in order to be able to accept using UserFlow policies along with custom policies, while we transition to all custom policies. Even though they are within the same B2C, they use different signing keys.

```c#
// Record name of secondary B2C policies
var custom1Policy = builder.Configuration.GetSection("AzureAd2").GetValue<string>("SignUpSignInPolicyId");
var custom2Policy = builder.Configuration.GetSection("AzureAd3").GetValue<string>("SignUpSignInPolicyId");

var jwtHandler = new JwtSecurityTokenHandler();
var authBuilder = builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddPolicyScheme(JwtBearerDefaults.AuthenticationScheme, "SchemeSelection",
    options =>
    {
        options.ForwardDefaultSelector = context =>
        {
            if (context.Request.Headers.TryGetValue(HeaderNames.Authorization, out var authorization)
                && authorization.Count == 1
                && authorization[0]?.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase) == true)
            {
                var token = authorization[0]!["Bearer ".Length..].Trim();
                if (jwtHandler.CanReadToken(token))
                {
                    var jwt = jwtHandler.ReadJwtToken(token);
                    var policy = jwt?.Claims.Where(c => c.Type == "tfp").Select(c => c.Value).FirstOrDefault();
                    if (policy?.Equals(custom1Policy, StringComparison.OrdinalIgnoreCase) == true)
                        return "CustomPolicy1";
                    if (policy?.Equals(custom2Policy, StringComparison.OrdinalIgnoreCase) == true)
                        return "CustomPolicy2";
                }
            }
            return "UserFlowPolicy";
        };
    });

// Register the three B2C policies
authBuilder.AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"), "UserFlowPolicy");
authBuilder.AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd2"), "CustomPolicy1");
authBuilder.AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd3"), "CustomPolicy2");
```
