### ISSUE TITLE
[Bug] SingletonTokenAcquisition can be removed

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#249]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.5-preview

AddTokenAcquisition isTokenAcquisitionSingleton parameter (never used)
https://github.com/AzureAD/microsoft-identity-web/blob/0b628e2a56e6525bbca682c50a7528da4d09cc22/src/Microsoft.Identity.Web/ServiceCollectionExtensions.cs#L32-L34 is a request from the Microsoft Graph SDK which want a singleton (whereas in general that’s not such a good idea)

See https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsMicrosoftGraph/appsettings.json#L9

There is an alternative which is that the GraphService registers the ITokenAcquisition as a singleton (the last which does the registration)

**Decision:**
- We keep AddTokenAcquisition as is
- We remove the [SingletonTokenAcquisition](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs#L35) property from the Microsoft.Identity.Options
- AddTokenAcquision is called with the default value (false) from the extension methods
- Remove the tests that were testing this.

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)

**Comment by SviatoslavVilkovych** [comment]
So, there is no more posibility to have **TokenAcquisition** registered as a Singleton service, right?

**Comment by pmaytak** [comment]
You still can. Call `services.AddTokenAcquisition(true)` at the end of `ConfigureServices` method. (The related PRs just removed `SingletonTokenAcquisition` property from `MicrosoftIdentityOptions`.)

https://github.com/AzureAD/microsoft-identity-web/blob/7df36791eb5314387c9aad3e084a94940ba24024/src/Microsoft.Identity.Web/ServiceCollectionExtensions.cs#L33-L35
