### ISSUE TITLE
DownstreamApi methods throw exception in 2.14.0

### ISSUE THREAD

**Issue by mevans-medpace** [AzureAD/microsoft-identity-web#2494]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.DownstreamApi

### Microsoft.Identity.Web version

2.14.0

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Not Applicable

### Description

When upgrading to version 2.14.0, calling a downstream API throws an exception indicating it is trying to call a version of the constructor that does not exist. This seems to be true for all the verb-related methods i.e. `GetForUserAsync` as well as the generic one where you specific the verb (`CallApiForUserAsync`)

It looks like this version upgraded to Microsoft.Identity.Abstractions v5.0.0 which changed the http method option to be a string instead of `HttpMethod`, but the code in `DownstramApi.HttpMethods.cs` is still trying to pass the `HttpMethod`.

### Reproduction steps

```csharp
            var response = await downstreamApi.GetForUserAsync<IEnumerable<MyObject>>(
                serviceName: DownstreamApiNames.MyApiName,
                options =>
                {
                    options.RelativePath = $"MyObject/all";
                });
```

### Error message

```
System.MissingMethodException: Method not found: 'Void Microsoft.Identity.Abstractions.DownstreamApiOptionsReadOnlyHttpMethod..ctor(Microsoft.Identity.Abstractions.DownstreamApiOptions, System.Net.Http.HttpMethod)'.
   at Microsoft.Identity.Web.DownstreamApi.MergeOptions(String optionsInstanceName, Action`1 calledApiOptionsOverride, HttpMethod httpMethod)
   at Microsoft.Identity.Web.DownstreamApi.GetForUserAsync[TOutput](String serviceName, Action`1 downstreamApiOptionsOverride, ClaimsPrincipal user, CancellationToken cancellationToken)
```

### Id Web logs

n/a

### Relevant code snippets

```csharp
var response = await downstreamApi.GetForUserAsync<IEnumerable<MyObject>>(
                serviceName: DownstreamApiNames.MyApiName,
                options =>
                {
                    options.RelativePath = $"MyObject/all";
                });
```

### Regression

Id Web 2.13.4

### Expected behavior

I expect that calling the downstream API will not throw an exception.

**Comment by jmprieur** [comment]
@westin-m could you please have a look?

**Comment by westin-m** [comment]
@mevans-medpace Can you add more detail to your reproduction steps, including versions of any other dependencies that you're using?

**Comment by mevans-medpace** [comment]
@westin-m Our web application uses a BFF, the controller calls a service which then executes the code I listed, calling an injected IDownstreamApi:

```
    private readonly IDownstreamApi downstreamApi;

    public MyService(
        IDownstreamApi downstreamApi)
    {
        this.downstreamApi = downstreamApi;
    }
```

The call to `GetForUserAsync` is where the error occurs.

As for dependencies, everything should be up-to-date. The relevant ones are:
- Azure.Identity (1.10.1)
- Microsoft.AspNet.WebApi.Client (5.2.9)
- Microsoft.Extensions.Caching.Memory (7.0.0)
- Microsoft.Extensions.Configuration.Abstractions (7.0.0)
- Microsoft.Extensions.Configuration.Binder (7.0.4)
- Microsoft.Extensions.Http (7.0.0)
- Microsoft.Graph (5.28.0)

I couldn't find any references to Microsoft.Identity.Abstractions outside of the one from Microsoft.Identity.Web via Microsoft.Identity.Web.TokenAcquistion.

I did try explicitly setting the version of Microsoft.Identity.Abstractions to 5.0.0 in NuGet Package Manager, thinking that somewhere in the chain a package was trying to use version 4.1.0, but that didn't resolve anything.

Let me know if you need any more information.

**Comment by jmprieur** [comment]
Did you try to output your recursive dependencies? I suppose that one of the IdWeb assemblies would not be 2.14.0?

```text
dotnet list yourproject.csproj package --include-transitive
```

See https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package

**Comment by mevans-medpace** [comment]
Thanks, I ran that command. All the IdWeb assemblies are 2.14.0:

```
   [net7.0]:
   Top-level Package                                      Requested        Resolved
   > AutoMapper                                           12.0.1           12.0.1
   > Azure.Identity                                       1.10.1           1.10.1
   > Microsoft.AspNet.WebApi.Client                       5.2.9            5.2.9
   > Microsoft.Extensions.Caching.Memory                  7.0.0            7.0.0
   > Microsoft.Extensions.Configuration.Abstractions      7.0.0            7.0.0
   > Microsoft.Extensions.Configuration.Binder            7.0.4            7.0.4
   > Microsoft.Extensions.Http                            7.0.0            7.0.0
   > Microsoft.Graph                                      5.28.0           5.28.0
   > Microsoft.Identity.Web                               2.14.0           2.14.0
   > StyleCop.Analyzers                                   1.2.0-beta.507   1.2.0-beta.507

   Transitive Package                                           Resolved
   > Microsoft.Graph.Core                                       3.0.11
   > Microsoft.Identity.Abstractions                            5.0.0
   > Microsoft.Identity.Client                                  4.56.0
   > Microsoft.Identity.Client.Extensions.Msal                  2.31.0
   > Microsoft.Identity.Web.Certificate                         2.14.0
   > Microsoft.Identity.Web.Certificateless                     2.14.0
   > Microsoft.Identity.Web.Diagnostics                         2.14.0
   > Microsoft.Identity.Web.TokenAcquisition                    2.14.0
   > Microsoft.Identity.Web.TokenCache                          2.14.0
   > Microsoft.IdentityModel.Abstractions                       6.32.3
   > Microsoft.IdentityModel.JsonWebTokens                      6.32.3
   > Microsoft.IdentityModel.Logging                            6.32.3
   > Microsoft.IdentityModel.LoggingExtensions                  6.32.3
   > Microsoft.IdentityModel.Protocols                          6.32.3
   > Microsoft.IdentityModel.Protocols.OpenIdConnect            6.32.3
   > Microsoft.IdentityModel.Tokens                             6.32.3
   > Microsoft.IdentityModel.Validators                         6.32.3

```

I pared down the list to just those that seem relevant. Could the `Microsoft.Identity.Client` or `Microsoft.IdentityModel` libraries be causing this?

**Comment by mevans-medpace** [comment]
We have some other packages used by the BFF project that are using an older version of Microsoft.Identity.Web - I think this may be causing the issue, even though the project with the service is fully up-to-date.

**Comment by mevans-medpace** [comment]
Definitely a problem with older versions of specific DLLs (i.e. Microsoft.Identity.Web.DownstreamApi.dll) in dependent packages - I'll close this issue.
