### ISSUE TITLE
With TokenAcquirerFactory, `IDownstreamApi.GetFromAppAsync` fails to resolve "AzureAd" config unless it's explicitly listed in the appsettings.json file

### ISSUE THREAD

**Issue by vitale232** [AzureAD/microsoft-identity-web#2495]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.14.0

### Web app

Not Applicable

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

I'm developing a Console app that will run as a "daemon application". The daemon app will make authenticated HTTP calls to a WebApi, which is protected using Azure AD (via a call to `builder.Services.AddMicrosoftIdentityWebApiAuthentication(builder.Configuration)` in the WebApi `Program.cs`).

I'd like for the daemon app to read its configuration object from user secrets during development. As such, I configure the host to include the User Secrets. Then, when it's time to make an authenticated request in my program, I inject the `IDownstreamApi` interface and invoke its `GetForAppAsync` method. However, the `GetForAppAsync` method is throwing a `NullReferenceException`. It appears that the library is unable to discover my `AzureAd` configuration.

The part that really surprised me, though, is that if I cut and paste my user secrets directly into the `appsettings.json`, the app will successfully make the authenticated HTTP request and return with a 200.

I'd much prefer to be able to work with the User Secrets feature for the added security in source control.

As a note, the secrets do appear to be getting read in correctly. I'm able to view and confirm the config values for `AzureAd` are present using the debugger. They're present regardless of whether I use apsettings.json or secrets.json to my program, but it appears they're only available to the library if they're in the appsettings.

### Reproduction steps

1. Create a WebAPI with authenitication/authorization provided by `Microsoft.Identity.Web.AddMicrosoftIdentityWebApiAuthentication`
2. Create an App and give it an app role in Azure AD for daemon app to authorize against the WebAPI 
3. Create the Daemon App in Azure AD and assign it the role to the WebApi
4. Connect to the WebApi via a console app using `Microsoft.Identity.Web`'s downstream APIs, with all config in `appsettings.json`. Verify.
5. Move the AzureAd config to user settings. Verify.

### Error message

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Identity.Web.MergedOptions.PrepareAuthorityInstanceForMsal()
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.DefaultAuthorizationHeaderProvider.CreateAuthorizationHeaderForAppAsync(String scopes, AuthorizationHeaderProviderOptions downstreamApiOptions, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.CallApiInternalAsync(String serviceName, DownstreamApiOptions effectiveOptions, Boolean appToken, HttpContent content, ClaimsPrincipal user, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.GetForAppAsync[TOutput](String serviceName, Action`1 downstreamApiOptionsOverride, CancellationToken cancellationToken)
   at NysdotScoringToolWebScraper.Http.ScoringToolFirmClient.GetFirm(DesignProjectInventoryPage dto) in C:\dev\prj\NysdotScoringTool\src\NysdotScoringToolWebScraper\Http\ScoringToolFirmClient.cs:line 58
   at NysdotScoringToolWebScraper.Http.ScoringToolFirmClient.ReconcileFirm(DesignProjectInventoryPage dto) in C:\dev\prj\NysdotScoringTool\src\NysdotScoringToolWebScraper\Http\ScoringToolFirmClient.cs:line 34
   at Program.<Main>$(String[] args) in C:\dev\prj\NysdotScoringTool\src\NysdotScoringToolWebScraper\Program.cs:line 224   at Program.<Main>(String[] args)
```

### Relevant code snippets

```csharp
// Setup code to configure the app to use VS User Secrets

using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Identity.Abstractions;
using Microsoft.Identity.Web;
//using Microsoft.Identity.Client;
using System.Net;

var host = Host.CreateDefaultBuilder()
    .ConfigureAppConfiguration(
        (hostingContext, config) =>
        {
            config
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddUserSecrets<Program>()
                .AddJsonFile("appsettings.json");
        }
    )
    .ConfigureServices(
        (hostingContext, services) =>
        {
            
            var config = hostingContext.Configuration; // Debugging the config object reveals that the User Secrets are present in the object
            
            services.AddAuthentication();

            var tokenAcquirerFactory = TokenAcquirerFactory.GetDefaultInstance("AzureAd");
            tokenAcquirerFactory.Services.AddLogging();
            tokenAcquirerFactory.Services.AddDownstreamApi(
                "GetFirmByName",
                config.GetSection("GetFirmByName")
            );

            var apiInstance = tokenAcquirerFactory.Build().GetRequiredService<IDownstreamApi>();
            services.AddSingleton(apiInstance);
        }
    )
    .Build();
```

```csharp
// Class that initiates the authenticated HTTP request.
public class ScoringToolFirmClient
{
    private readonly HttpClient _httpClient;

    private readonly IDownstreamApi _api;
    private readonly ILogger<ScoringToolFirmClient> _logger;

    public ScoringToolFirmClient(
        ILogger<ScoringToolFirmClient> logger,
        IDownstreamApi api,
        HttpClient httpClient
    )
    {
        _logger = logger;
        _api = api;
        _httpClient = httpClient;
    }

    public async Task<FirmDto?> GetFirm(DesignProjectInventoryPage dto)
    {
        var path = $"/GetFirmByName?firmName={WebUtility.UrlEncode(dto.FirmName)}";
        _logger.LogInformation("GET Firm path: {url}", path);

        var response = await _api.GetForAppAsync<GetFirmByNameResponse>(
            "GetFirmByName",
            options =>
            {
                options.RelativePath = path;
            }
        );
        return response?.Firm;
    }
}
```

### Expected behavior

I would expect that the library would authenticate succesfully as long as the `AzureAd` key is available in the configuration. I do not believe the source of the configuration, whether it be from User Secrets, `appsettings.json`, or some other file, should affect the underlying behavior of the library.

**Comment by jmprieur** [comment]
@vitale232 : 

In your case you already have a service collection. Don't use 
```csharp
var tokenAcquirerFactory = TokenAcquirerFactory.GetDefaultInstance("AzureAd");
```

but 

```csharp
services.Configure<MicrosoftIdentityApplicationOptions>(options => configuration.GetSection("AzureAd").Bind(options));
services.AddTokenAcquisition();
```

and use `services` instead of tokenAcquirerFactory.services elsewhere.

**Comment by vitale232** [comment]
That got me sorted. I had a feeling this was some variation of, "You're holding it wrong."

Thanks so much for the answer and the library! I'll leave the ticket open, as I see you've added some labels.

**Comment by jmprieur** [comment]
Thanks for the update, @vitale232

**Comment by borangecpn** [comment]
> @vitale232 :
> 
> This is a really good question, and we need to update our documentation.
> 
> In your case you already have a service collection (services). Don't use
> 
> ```cs
> var tokenAcquirerFactory = TokenAcquirerFactory.GetDefaultInstance("AzureAd");
> ```
> 
> which creates its own, independent, service collection. but instead use _services_:
> 
> ```cs
> services.Configure<MicrosoftIdentityApplicationOptions>(options => config .GetSection("AzureAd").Bind(options));
> services.AddTokenAcquisition();
> ```
> 
> and use `services` instead of tokenAcquirerFactory.Services elsewhere.

**Comment by borangecpn** [comment]
Could someone please show me what the rest of this code looks like?
I am trying to set this up in a .NET 8 Azure Function App as a service, and I cannot get it to work correctly. 
If I run the code: 
            var tokenAcquirerFactory = TokenAcquirerFactory.GetDefaultInstance();
            tokenAcquirerFactory.Services.AddDownstreamApi(ServiceName,
                tokenAcquirerFactory.Configuration.GetSection(ServiceName));
            var serviceProvider = tokenAcquirerFactory.Build();
            _alertApiClient = serviceProvider.GetRequiredService<IDownstreamApi>();
in the function app it works the first time, but the second time it generates an error that says you should not call build twice. 
I've tried to do this several ways and have failed and I cannot find any articles or code samples that show how to do properly accomplish this task.
