### ISSUE TITLE
AZURE_CLIENT_ID for User assigned Managed Identity (UAMI) is not honored

### ISSUE THREAD

**Issue by jc4gh** [AzureAD/microsoft-identity-web#2497]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.14.0

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

When AZURE_CLIENT_ID is set for User Assigned Managed Identity, it is getting used by DefaultAzureCredential() but not for Microsoft.Identity.Web. Workaround I found was to use ManagedIdentityClientId.

https://github.com/AzureAD/microsoft-identity-web/wiki/Using-certificates#microsoftidentityweb-leverages-managed-identity
According to this, it should.

### Reproduction steps

1. Set AZURE_CLIENT_ID as environmental variable
2. launch

### Error message

ArgumentException: IDW10109: All client certificates passed to the configuration have expired or can't be loaded. (Parameter 'clientCredentials')

Microsoft.Identity.Web.ConfidentialClientApplicationBuilderExtension.WithClientCredentials(ConfidentialClientApplicationBuilder builder, IEnumerable<CredentialDescription> clientCredentials, ILogger logger, ICredentialsLoader credentialsLoader, CredentialSourceLoaderParameters credentialSourceLoaderParameters)

### Relevant code snippets

```csharp
"AzureAD": {
    "ClientId": "ClientId",
    "ClientCredentials": [
      {
        "SourceType": "KeyVault",
        "KeyVaultCertificateName": "KeyVaultCertificateName",
        "KeyVaultUrl": "KeyVaultUrl",
        "ManagedIdentityClientId": "UAMI-ID" // workaround
      }
    ]
  },
```

### Expected behavior

use AZURE_CLIENT_ID value if present

**Comment by jmprieur** [comment]
@jc4gh : how is your startup? do you use the TokenAcquirerFactory? or AddMicrosoftIdentityWebXX?

**Comment by jc4gh** [comment]
```
MicrosoftIdentityWebAppAuthenticationBuilder authBuilder = null;
authBuilder = services.AddMicrosoftIdentityWebAppAuthentication(this.Configuration);

authBuilder
   .EnableTokenAcquisitionToCallDownstreamApi()
   .AddDownstreamApi(nameof(A), this.Configuration.GetSection("A"))
   .AddDownstreamApi(nameof(B), this.Configuration.GetSection("B"))
   .AddDownstreamApi(nameof(C), this.Configuration.GetSection("C"))
   .AddDownstreamApi(nameof(D), this.Configuration.GetSection("D"))
   .AddDownstreamApi(nameof(E), this.Configuration.GetSection("E"))
   .AddInMemoryTokenCaches();
```

**Comment by jc4gh** [comment]
public void ConfigureServices(IServiceCollection services)

**Comment by rajravat** [comment]
this is the same issue i came across, have a look at this post for a work around:

https://github.com/AzureAD/microsoft-identity-web/issues/2457

**Comment by JoshLozensky** [comment]
This was addressed in the commit linked above
