### ISSUE TITLE
[Bug] Rename MsalMemoryTokenCacheOptions.SlidingExpiration to AbsoluteExpirationRelativeToNow

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#250]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.5-preview

**Where is the issue?**
* Web App
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (Validating tokens)
    * [ ] Protected web APIs (Validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [x ] In Memory caches
     * [ ] Session caches
     * [ ] Distributed caches

**Repro**
MsalMemoryTokenCacheOptions.SlidingExpiration should be named  AbsoluteExpirationRelativeToNow

[MsalMemoryTokenCacheProvider.cs#L80](https://github.com/AzureAD/microsoft-identity-web/blob/17f48c62410e08ea0d4c1fdb4f15a0713ed7f00c/src/Microsoft.Identity.Web/TokenCacheProviders/InMemory/MsalMemoryTokenCacheProvider.cs#L80) 

whereas the In memory cache uses absoluteExpirationRelativeToNow

**Comment by jmprieur** [comment]
Adding P1 as there is an API breaking change (do it sooner rather than later)

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
