### ISSUE TITLE
AADSTS9000512: A Hybrid SPA code can only be requested while redeeming a confidential client authorization code

### ISSUE THREAD

**Issue by krsnaraja** [AzureAD/microsoft-identity-web#2510]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.15.1

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

Microsoft account types cannot login when requesting a "spa auth code". There are no issues with Azure AD account types, but an exception is raised when an MSA account, such as @hotmail, is used.

`AADSTS9000512: A Hybrid SPA code can only be requested while redeeming a confidential client authorization code (a code issued to a web-type redirect URI). Do not request a hybrid code otherwise.`

### Reproduction steps

Enable Hybrid SPA and login with a (MSA) Microsoft account, e.g., @hotmail.com, @outlook.com, etc. accounts.

### Error message

Error: invalid_request
Error description: AADSTS9000512: A Hybrid SPA code can only be requested while redeeming a confidential client authorization code (a code issued to a web-type redirect URI). Do not request a hybrid code otherwise.
Error codes: [9000512]
Error URI: https://login.microsoftonline.com/error?code=9000512

### Relevant code snippets

```csharp
Followed the Hybrid SPA code from https://github.com/AzureAD/microsoft-identity-web/wiki/Hybrid-SPA#how-to-enable-hybrid-spa-in-microsoftidentityweb.

Enabled Session and in our appsettings.json in the AzureAd section, added:
"WithSpaAuthCode": true
```

### Expected behavior

Ability to acquire the spa authorization code for both AAD and MSA account types.

**Comment by jmprieur** [comment]
@krsnaraja : this is not implemented on the IdP side.
