### ISSUE TITLE
2.15.1 must wait all OnTokenValidated delegates to completion

### ISSUE THREAD

**Issue by recumbented** [AzureAD/microsoft-identity-web#2513]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.15.1

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

Related to https://github.com/AzureAD/microsoft-identity-web/issues/2508

Since 2.15.1, OnTokenValidated is used as MulticastDelegate.
So `await _onTokenValidated(context);` will not wait it's invocations.
This causes unexpected behavior in users's OnTokenValidated invocation.

It's desired to wait all invocations like
```
await Task.WhenAll(((MulticastDelegate)_onTokenValidated)
	.GetInvocationList()
	.Cast<Func<TokenValidatedContext, Task>>()
	.Select(t=>t(context)));
```

### Reproduction steps

If you use scoped services from DI in OnTokenValidated, 
async method invocation may throw ObjectDisposedException.

### Relevant code snippets

```csharp
options.Events.OnTokenValidated = async context =>
{
    var dep = context.HttpContext.RequestServices.GetRequiredService<Service>();
    await Task.Delay(1000);
    await dep.UseResourceAsync(); //Out of DI scope at the time. ObjectDisposedException may be thrown.
}
```
```


### Regression

_No response_

### Expected behavior

All OpenIdConnectEvents delegates must be awaited to completion.

**Comment by westin-m** [comment]
@recumbented A fix for this is proposed in #2524. If you can, please try it for yourself and let us know the results.

**Comment by recumbented** [comment]
@westin-m Thanks. I tested and confirmed it works as expected.

**Comment by sruke** [comment]
Microsoft.Identity.Web v2.15.2 contains a fix for this issue.
