### ISSUE TITLE
[Bug] Fixes in  MsalSessionTokenCacheProvider.cs

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#252]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 0.1.5-preview

** Things to fix:
-	The lock object does not need to be static: [MsalSessionTokenCacheProvider.cs#L125](https://github.com/AzureAD/microsoft-identity-web/blob/17f48c62410e08ea0d4c1fdb4f15a0713ed7f00c/src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs#L125)
-	The session should not be committed (for instance [MsalSessionTokenCacheProvider.cs#L96](https://github.com/AzureAD/microsoft-identity-web/blob/17f48c62410e08ea0d4c1fdb4f15a0713ed7f00c/src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs#L96), but there are other lines). Commit is automatically called at the end of the request. If we do it prematurely, nobody can modify it any longer.

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
