### ISSUE TITLE
TokenAcquisition.BuildConfidentialClientApplication should not use exact error message for call graph logic.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/microsoft-identity-web#2549]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.TokenAcquisition

### Microsoft.Identity.Web version

2.x

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

catch (ArgumentException ex) when (ex.Message == IDWebErrorMessage.ClientCertificatesHaveExpiredOrCannotBeLoaded)

This logic in the code is fragile and can easily break.

### Reproduction steps

Review this code here: https://github.com/AzureAD/microsoft-identity-web/blob/4bec32ea244cb88b982d84261925f3926a9d2cdb/src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs#L643

### Relevant code snippets

```csharp
catch (ArgumentException ex) when (ex.Message == IDWebErrorMessage.ClientCertificatesHaveExpiredOrCannotBeLoaded)
```

### Expected behavior

Do not depend on error message for logic decisions.

**Comment by jmprieur** [comment]
that's what partners asked for.
How do you suggest we proceed? how can we know that a certificate was revoked?
It's not only about expiry

**Comment by brentschmaltz** [comment]
My comment is the logic is controlled by checking the exact string match.
This is a fragile model.
Better to have a specific exception.

Also, the error message lists two possibilities: Expired OR cannot be loaded.
Separate errors would be better.
