### ISSUE TITLE
[Feature Request] Use Microsoft.Identity.Web.OWIN in Visual Studio templates

### ISSUE THREAD

**Issue by rastrup** [AzureAD/microsoft-identity-web#2554]
**Describe the solution you'd like**
When I create a new ASP.NET MVC .Net Framework project with Microsoft Identity Authorization in Visual Studio it is created on the based of the Microsoft.Identity.Web.OWIN package.

**Comment by jennyf19** [comment]
ASP.NET Owin is no longer maintained, we are focusing our efforts on ASP.NET Core, and would recommend you move to .NET 8, which has perf improvements.

closing...feel free to reach out to aspnetcore team instead.
