### ISSUE TITLE
Not able to override ICredentialsLoader

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/microsoft-identity-web#2564]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.TokenAcquisition

### Microsoft.Identity.Web version

2.15.3

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

TokenAcquisition ServiceCollectionExtensions is checking for ICredentialsLoader against ImplementationType. It either needs to check ICredentialsLoader against ServiceType or ImplemenationType against DefaultCredentialLoader

See:

https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs#L48

### Reproduction steps

1. Register a custom ICredentialsLoader
2. Try to use an API that uses the credentials loader

### Relevant code snippets

```csharp
NA
```

### Expected behavior

The provided ICredentialsLoader is used.

**Comment by jmprieur** [comment]
Totally agree, @keegan-caruso
Feel free to propose a PR if you wish/need it
