### ISSUE TITLE
configureConfidentialClientApplicationOptions in EnableTokenAcquisitionToCallDownstreamApi only applies to first downstreamAPI

### ISSUE THREAD

**Issue by simonschlegel** [AzureAD/microsoft-identity-web#2568]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.13.3

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

Since incoming auth and downstream api components both rely on AzureAd configuration section, I need to override the tenantId. My incoming auth needs tenantId =  "common" however this will not work for downstream api calls, since it will throw System.ArgumentException: IDW10405: 'tenant' parameter should be a tenant ID or domain name, not 'common', or 'organizations'. See https://aka.ms/ms-id-web/daemon-scenarios.  (Parameter 'tenant')

The problem is overriding options in EnableTokenAcquisitionToCallDownstreamApi() seem to only apply to the first downstreamAPI added in the builder.

### Reproduction steps

1. Configure options action in EnableTokenAcquisitionToCallDownstreamApi()
2. Override a setting, such as tenantId
3. Add more than one downstream API using AddDownstreamApi
4. Make a request (downstreamApi.GetForAppAsync) to any of the downstream APIs that is not the first added in the builder

### Error message

Since I am specifically trying to override tenantId so it is not "common" for downstream APIs, my error is below. However, this error is not specific to the bug described above.

```
System.ArgumentException: IDW10405: 'tenant' parameter should be a tenant ID or domain name, not 'common', or 'organizations'. See https://aka.ms/ms-id-web/daemon-scenarios.  (Parameter 'tenant')
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.DefaultAuthorizationHeaderProvider.CreateAuthorizationHeaderForAppAsync(String scopes, AuthorizationHeaderProviderOptions downstreamApiOptions, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.CallApiInternalAsync(String serviceName, DownstreamApiOptions effectiveOptions, Boolean appToken, HttpContent content, ClaimsPrincipal user, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.GetForAppAsync[TOutput](String serviceName, Action`1 downstreamApiOptionsOverride, CancellationToken cancellationToken)
   at ContentManagement.Providers.Cms.CmsDataProvider.GetSapLegacyMapping() in C:\repos\AzureSupport-ContentManagement\src\Providers.Cms\CmsDataProvider.cs:line 48
```

### Relevant code snippets

```csharp
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApi(this.Configuration.GetSection("AzureAd"))
            .EnableTokenAcquisitionToCallDownstreamApi(x =>
            {
                // Override manually due to builder configuration limitation on both using AzureAd section
                this.Configuration.GetSection("AzureAd").Bind(x);
                x.TenantId = this.Configuration["AadTenantId"];
            })
            .AddDownstreamApi("MyApi1", this.Configuration.GetSection("MyApi1"))
            .AddDownstreamApi("MyApi2", this.Configuration.GetSection("MyApi2"))
            .AddDownstreamApi("MyApi3", this.Configuration.GetSection("MyApi3"))
            .AddDownstreamApi("MyApi4", this.Configuration.GetSection("MyApi4"))
            .AddInMemoryTokenCaches();
```

### Expected behavior

Configure callback should apply to all downstream APIs added in the builder, not just the first one.

**Comment by jmprieur** [comment]
First, by default Microsoft.Identity.Web uses the tenant of the user
You can always override the tenant in your downstream API options using the `AcquireTokenOptions.Tenant` (See https://github.com/AzureAD/microsoft-identity-abstractions-for-dotnet/blob/1427fdee21c2b5078c33ab1ee7feb78d80f57999/src/Microsoft.Identity.Abstractions/TokenAcquisition/AcquireTokenOptions.cs#L145)
