### ISSUE TITLE
ITokenAcquisition needs to have a member AcquireTokenForApp

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#26]
ITokenAcquisition needs to support the daemon scenario.
proposing to add a new method:

```CSharp
string AcquireTokenForApp(IEnumerable<string> scopes)
```

we might want to see if we want to leverate Managed identity, in the case of web apps/apis hosted in Azure or on the dev box

**Comment by jennyf19** [comment]
Included in [release]https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.0-preview)
