### ISSUE TITLE
IDX40001: Issuer 'https://[Instance]/[TenantId]/v2.0' does not match any of the valid issuers provided for this application.

### ISSUE THREAD

**Issue by christophedemey** [AzureAD/microsoft-identity-web#2618]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.16.0

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

Not Applicable

### Description

Hi, I am trying to get swagger docs working with azure ad (entra) in .NET 8.

I have setup my swagger

`builder.Services.AddSwaggerGen(c =>
{
    var scopes = new Dictionary<string, string>
    {
        { "api://7a179af8-0d99-496c-9d46-9480777b8e8a/Api.Access", "Api.Access" }
    };

    c.AddSecurityRequirement(new OpenApiSecurityRequirement()
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "oauth2"
                },
                Scheme = "oauth2",
                Name = "oauth2",
                In = ParameterLocation.Header
            },
            new List <string> ()
        }
    });
    c.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.OAuth2,
        Flows = new OpenApiOAuthFlows
        {
            Implicit = new OpenApiOAuthFlow()
            {
                AuthorizationUrl = new Uri("https://login.microsoftonline.com/common/oauth2/v2.0/authorize"),
                TokenUrl = new Uri("https://login.microsoftonline.com/common/common/v2.0/token"),
                Scopes = scopes
            }
        }
    });
});`

Then I created a secret on the api app registration and used it as following.

`    app.UseSwaggerUI(options =>
    {
        options.OAuthAppName("SwaggerClient");
        options.OAuthClientId("client-id");
        options.OAuthClientSecret("client-secret");
        options.OAuthUseBasicAuthenticationWithAccessCodeGrant();
    });`

My application configuration is looking like this : 
`  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "9c26678d-90ad-4288-b428-1b838fdd09c7",
    "ClientId": "7a179af8-0d99-496c-9d46-9480777b8e8a",
    "Domain": "dhoogherealestateoutlook.onmicrosoft.com",
    "Scopes": {
      "Authorized": [ "Api.Access" ]
    }
  },`

When I launch my app and authorize the swagger docs I am returned a token containing the Api.Access scope and my info.
But when I try to use this token I get an unauthorized, the output is : 

`Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10264: Reading issuer signing keys from validation parameters and configuration.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10265: Reading issuer signing keys from configuration.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10243: Reading issuer signing keys from validation parameters.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10243: Reading issuer signing keys from validation parameters.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10265: Reading issuer signing keys from configuration.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10239: Lifetime of the token is valid.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Error: IDX40001: Issuer: 'https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0', does not match any of the valid issuers provided for this application. `

I also note that in this output the tenantId "9188040d-6c67-4c5b-b112-36a304b66dad" is not known to me, but maybe this is normal ? 

I have been trying different instances/domains/configurations without any luck.

Thanks for any tip you can give me.

### Reproduction steps

1. Setup new web API .NET 8 (with swagger template)
2. Add configuration for azureAD
``  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "9c26678d-90ad-4288-b428-1b838fdd09c7",
    "ClientId": "7a179af8-0d99-496c-9d46-9480777b8e8a",
    "Domain": "dhoogherealestateoutlook.onmicrosoft.com",
    "Scopes": {
      "Authorized": [ "Api.Access" ]
    }
  },``
4. Configure Swagger to use authorization.
`    app.UseSwaggerUI(options =>
    {
        options.OAuthAppName("SwaggerClient");
        options.OAuthClientId("client-id");
        options.OAuthClientSecret("client-secret");
        options.OAuthUseBasicAuthenticationWithAccessCodeGrant();
    });`

`builder.Services.AddSwaggerGen(c =>
{
    var scopes = new Dictionary<string, string>
    {
        { "api://7a179af8-0d99-496c-9d46-9480777b8e8a/Api.Access", "Api.Access" }
    };

    c.AddSecurityRequirement(new OpenApiSecurityRequirement()
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "oauth2"
                },
                Scheme = "oauth2",
                Name = "oauth2",
                In = ParameterLocation.Header
            },
            new List <string> ()
        }
    });
    c.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.OAuth2,
        Flows = new OpenApiOAuthFlows
        {
            Implicit = new OpenApiOAuthFlow()
            {
                AuthorizationUrl = new Uri("https://login.microsoftonline.com/common/oauth2/v2.0/authorize"),
                TokenUrl = new Uri("https://login.microsoftonline.com/common/common/v2.0/token"),
                Scopes = scopes
            }
        }
    });
});`
6. Start web api, click on the authorize button, token is returned from azure ad, make a web api call.

### Error message

Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10264: Reading issuer signing keys from validation parameters and configuration.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10265: Reading issuer signing keys from configuration.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10243: Reading issuer signing keys from validation parameters.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10243: Reading issuer signing keys from validation parameters.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10265: Reading issuer signing keys from configuration.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10239: Lifetime of the token is valid.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Error: IDX40001: Issuer: 'https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0', does not match any of the valid issuers provided for this application. 

### Relevant code snippets

```csharp
`builder.Services.AddSwaggerGen(c =>
{
    var scopes = new Dictionary<string, string>
    {
        { "api://7a179af8-0d99-496c-9d46-9480777b8e8a/Api.Access", "Api.Access" }
    };

    c.AddSecurityRequirement(new OpenApiSecurityRequirement()
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "oauth2"
                },
                Scheme = "oauth2",
                Name = "oauth2",
                In = ParameterLocation.Header
            },
            new List <string> ()
        }
    });
    c.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.OAuth2,
        Flows = new OpenApiOAuthFlows
        {
            Implicit = new OpenApiOAuthFlow()
            {
                AuthorizationUrl = new Uri("https://login.microsoftonline.com/common/oauth2/v2.0/authorize"),
                TokenUrl = new Uri("https://login.microsoftonline.com/common/common/v2.0/token"),
                Scopes = scopes
            }
        }
    });
});`

`    app.UseSwaggerUI(options =>
    {
        options.OAuthAppName("SwaggerClient");
        options.OAuthClientId("client-id");
        options.OAuthClientSecret("client-secret");
        options.OAuthUseBasicAuthenticationWithAccessCodeGrant();
    });`

`  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "9c26678d-90ad-4288-b428-1b838fdd09c7",
    "ClientId": "7a179af8-0d99-496c-9d46-9480777b8e8a",
    "Domain": "dhoogherealestateoutlook.onmicrosoft.com",
    "Scopes": {
      "Authorized": [ "Api.Access" ]
    }
  },`
```

### Expected behavior

The call to the web api should be authenticated.

**Comment by jmprieur** [comment]
@christophedemey : you have common twice in:

  TokenUrl = new Uri("https://login.microsoftonline.com/common/common/v2.0/token"),
