### ISSUE TITLE
Adding explicit support for AKS Workload Identity in `ManagedIdentityClientAssertion`

### ISSUE THREAD

**Issue by sebader** [AzureAD/microsoft-identity-web#2643]
# Summary

Adding explicit support for AKS Workload Identity in `ManagedIdentityClientAssertion`

## Motivation and goals

`ManagedIdentityClientAssertion` right now does not work when you have multiple identities federated with one service account on an AKS pod using workload identity. 

## In scope

The fix should be fairly trivial; change this
https://github.com/AzureAD/microsoft-identity-web/blob/02b0b81b9f22150f952226ecf2968fd21a871060/src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs#L34

to be
```csharp
var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions()
            { ManagedIdentityClientId = _managedIdentityClientId, WorkloadIdentityClientId = _managedIdentityClientId});
```
## Out of scope

-

## Risks / unknowns

-

## Examples

see above. You might also extend the constructor to add an explicit parameter for the workload identity clientId, but I believe this should already help most people

**Comment by jmprieur** [comment]
Thanks @sebader 
Do you want to propose a PR?

cc: @jennyf19 @bgavrilMS

**Comment by sebader** [comment]
sure, see https://github.com/AzureAD/microsoft-identity-web/pull/2646
