### ISSUE TITLE
InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. 

### ISSUE THREAD

**Issue by ashokswain27** [AzureAD/microsoft-identity-web#267]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web  0.1.5-preview

**Where is the issue?**

* Web API
    * [x] Protected web APIs (Validating tokens)
  

**Is this a new or existing app?**
This is a new App.

**Repro**
API is protected with Azure AD.
Followed the below wiki to configure the authentication code.
Authentication is working fine if I am not specifying the [Authorize] in the "Controller".
After adding the [Authorize] attribute, the below error is occurred.
InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. 

```csharp
In Startup.cs code:
 services.AddAuthentication(AzureADDefaults.AuthenticationScheme).AddProtectedWebApi(Configuration);
in Appsetting.json:
"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": ".onmicrosoft.com",
    "TenantId": "",
    "ClientId": ""
  }

In the Controller method: Added  [Authorize] above the class
```

**Expected behavior**
Authentication should work by providing the "Authorize" attribute in the controller.

**Actual behavior**
Below error is occurred when call the protected api with accesstoken

**Possible Solution**
Is it by design?

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by pmaytak** [comment]
Hello. In your above code try replacing `AzureADDefaults.AuthenticationScheme` with `JwtBearerDefaults.AuthenticationScheme`.

**Comment by ashokswain27** [comment]
Replaced with JwtBearerDefaults.AuthenticationScheme. 
Got the 401 unauthorized error.

**Comment by jmprieur** [comment]
@ashokswain27, I'm assuming that you have values for the domain, tenantID and Client ID ?

**Comment by ashokswain27** [comment]
Yes,  domain, tenantID and Client ID have the correct values.

**Comment by ashokswain27** [comment]
Here is the code(not my project code), but the authentication code is same.
 Created a new asp.net core api template project.
https://github.com/ashokswain27/aspnetcoreapiauth

**Comment by udlose** [comment]
@ashokswain27  I see that you don't have `UseAuthentication()` specified in your `Configure` method.  You'll certainly need to add that as it sets up the middleware for authentication.

**Comment by jmprieur** [comment]
@ashokswain27. this is probably an app registration issue, then?
Do you see the logs?

**Comment by jmprieur** [comment]
@ashokswain27. I believe I've answered.
Closing this issue for now, feel free to reopen if you disagree.
