### ISSUE TITLE
New version that is compatible to other new Microsoft packages.

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#2674]
Our application use Microsoft.Identity.Web.GraphServiceClient, but even the latest version imposes dependency package version restriction that makes it hard to use with other new Microsoft packages.

1) Is it safe to just ignore the restriction and force MSBuild to use System.Text.Json 8.0.0?
2) Would it be possible to have a new release that is friendly with the latest Microsoft packages?

![image](https://github.com/AzureAD/microsoft-identity-web/assets/4291622/fc23298e-7f9f-4bf6-a40d-4f36acbce271)

**Comment by jennyf19** [comment]
@WenningQiu We try to use the lowest version possible so that end users are not forced to update. You can specify a specific version if you would rather do that.
Closing as won't fix, but feel free to re-open if you disagree.
