### ISSUE TITLE
Microsoft.Identity.Web doesn't respect the use of NullIdentityModelLogger.

### ISSUE THREAD

**Issue by nlz242** [AzureAD/microsoft-identity-web#2675]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.16.0

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

Not Applicable

### Description

A little bit of background before the issue itself...
Since 1.25.1 we'be been having some pretty serious performance issues. Our app has multiple authentication scheme defined and we switching to 1.25.1, we've noticed that under some load, we start loosing >2 seconds on some calls. After profiling the code, we've found that this time is spent failing IssuerValidation and logging failures, most of the wall-clock time is spent in logging failures. This wasn't an issue in 1.25.0. This has been reported in a couple of issues already. 

We've found two solution to our problem. The first one was suggested by @jmprieur, was basically to setup our authentication scheme and the defaut auth scheme logically. Doing that did bring the time loss down a bit, but we would still, under load, see >1 second degradation. 
So second solution was to create a logger that would do nothing and assign it to LogHelper.Logger. This worked great, performance was back where it should.

During a review of that code, we noticed we didn't have to create that logger, one already exists in Microsoft.IdentityModel.Abstraction, its called the NullIdentityModelLogger. So instead of re-inventing the wheel, we replaced our NullLogger with Microsoft's... and performance problems came back. I couldn't understand for the life of me WHY Microsoft's NullIdentityModelLogger would be slow, as it does NOTHING...

That is until I found this : 
https://github.com/AzureAD/microsoft-identity-web/blob/397fce764ad436a68934baa545f2b8884e70ae8c/src/Microsoft.Identity.Web.TokenAcquisition/MicrosoftIdentityBaseAuthenticationBuilder.cs#L41-L66

So if we explicitly set the logger to be the NullIdentityModelLogger, Microsoft.Identity.Web decides that it needs to it's own logger back in the game without any respect for our choice... Clearly a design shortcut to avoid having a configuration somewhere or something similar.

### Reproduction steps

1. Set LogHelper.Logger to NullIdentityModelLogger.Instance
2. Notice Wilson still logs
3. Create a duplicate of NullIdentityModelLogger, name it something else
4. Set LogHelper.Logger to this new instance
5. Notice Wilson doesn't log, like it should

### Relevant code snippets

```csharp
None
```

### Regression

Id Web 1.25.1

### Expected behavior

Microsoft.Identity.Web should provide means to disable logging that is WAY too verbose and causes performance issues, or at least respect the user's decision to use the NullIdentityModelLogger

**Comment by jennyf19** [comment]
Thanks @nlz242 Thanks for all the content and background. 2.16 is leveraging the more performant IdentityModel 7x and if used on .NET 8, you should see more perf improvements. Happy to learn more about the issues here and if you have benchmarks to share, happy to see those as well (if they can be shared).

**Comment by westin-m** [comment]
@nlz242 A fix for this will be in the next release. Please see #2816 for more information
