### ISSUE TITLE
[Question] Calling API from web app without authenticated users, using app permissions

### ISSUE THREAD

**Issue by AlbertoPa** [AzureAD/microsoft-identity-web#2678]
**Is your feature request related to a problem? Please describe.**

I have an asp.net core web app which calls a downstream API. Both are protected using Entra ID for Customers (preview).
Most of the API endpoints are called when users are authenticated, and work properly. 

However, a few endpoints need to be called on behalf of the application, without user authentication. 

I exposed the app permissions in the API configuration in Entra, granted them to the web app in its Entra registration. 

The web app is configured as follows:

```
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("EntraIdForCustomers"))
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddDownstreamApi("MyAPI", builder.Configuration.GetSection("MyAPIConfig"))
    .AddInMemoryTokenCaches();
```

The API as follows:

```
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("EntraIDForCustomers"));
```

and the controllers that should be authorized based on app permissions are protected with 

```
[Authorize]
[RequiredScopeOrAppPermission(
            RequiredAppPermissionsConfigurationKey = "EntraIdForCustomers:AppPermissions:Read",
            RequiredScopesConfigurationKey = "EntraIdForCustomers:AppPermissions:Read")]
```

I am using `CallApiForAppAsync` from `IDownStreamApi` to call the API. 

However, when the call is executed, Entra returns an error saying the request is invalid (400 - Bad request).

Is this scenario (web app calling an api on behalf of itself) supported by Microsoft Identity Web? I only found examples involving web apps calling an api on behalf of users, or daemon apps. If supported, could you please point to an example, if available?

Thank you.

**Comment by ThomasPe** [comment]
I have the same question. Only way I found is using MSAL.NET

**Comment by jmprieur** [comment]
It is supported, but you need to specify the authentication scheme on the authorize attribute.
See [Multiple Authentication Schemes](https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes)

**Comment by jmprieur** [comment]
Closing as answered
