### ISSUE TITLE
Error on OpenIdConnectAuthenticationHandler

### ISSUE THREAD

**Issue by juanan** [AzureAD/microsoft-identity-web#268]
I have an SPA starting an oidc login that calls to an .Net core project that offers 2 login possibilities: local login with Identity server or external login with Microsoft Identity Web.

If the user clicks on external login, the Microsoft login form is successfully shown but after login in with my office account I get this error on my redirect callback:

 ---> System.Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

This is the info that Azure sends to my callback

![image](https://user-images.githubusercontent.com/17723190/85109540-c7882d00-b211-11ea-9296-edce7407d62a.png)

Am I missing anything in the configuration?This is my Startup.cs class

![image](https://user-images.githubusercontent.com/17723190/85992602-67ee0680-b9f5-11ea-88f1-e15f133275c7.png)

And this is my controller to challengue the external login

![image](https://user-images.githubusercontent.com/17723190/85993578-d2ec0d00-b9f6-11ea-8858-245929ed4dd7.png)

In my case, I don't have deployed my .Net Core project on Azure so the solution to disable App Service Authentication is not valid for me, I just created an app under App registrations to have a client id, redirect url...

I would apprecciate any help, I can not figure out why its failing.

Many thanks.

Using .Net Core 3.1
Microsoft Identity Web 0.1.5-preview

**Comment by jennyf19** [comment]
believe this is fixed. please reopen if you need further assistance @juanan
