### ISSUE TITLE
How to update clientSecrects value with azure key vault fetched value

### ISSUE THREAD

**Issue by ajmaly** [AzureAD/microsoft-identity-web#269]
"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "123456ee-da8c-4b4d-92d6-6bbed315ec1e",
    "ClientId": "12345678-cb1a-447c-8388-6f146b8989be",
    "ClientSecret": ""
  },

I am sending `configuration` whatever I have default,

            services.AddWebAppCallsProtectedWebApi(Configuration).AddInMemoryTokenCaches();

How to update ClientSecret value which I fetched from azure key vault before calling `AddWebAppCallsProtectedWebApi` ?

**Comment by jmprieur** [comment]
Hello @ajmaly 
In this scenario, do you really want to use a client secret from keyvault, and not a certificate? 
Microsoft.Identity.Web supports using client certificate from KeyVault: https://github.com/AzureAD/microsoft-identity-web/wiki/Using-certificates#getting-certificates-from-key-vault.

**Comment by ajmaly** [comment]
Thanks @jmprieur for you reply. I know that library is supporting client certificate, same way I thought client secret support also there, but not found.  I guess it's not there.

One more question I have, while fetching certificate from keyValut, Is managed Identity supports inbuilt there? I want to access KeyValut through Managed Identity,

**Comment by jmprieur** [comment]
yes, Managed identity is built-in, @ajmaly

**Comment by jmprieur** [comment]
@ajmaly : can we close this issue? or is it something you'd like Microsoft.Identity.Web to do?

**Comment by jennyf19** [comment]
closing. @ajmaly please reopen if needed.

**Comment by ajmaly** [comment]
Thanks all. I am using certificate rather than client secrets as discussed.

**Comment by jmprieur** [comment]
Thanks for the update, @ajmaly
