### ISSUE TITLE
Process the query part of the authority when present

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#2697]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.17.0

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

When the authority is provided with a query part, it would be great to keep it and propagate to the MetadataUrl and the MSAL authority

```json
"Authority" : "https://customdomain.com/tenant/v2.0?dc=dcxyw
```

### Reproduction steps

```json
"Authority" : "https://customdomain.com/tenant/v2.0?dc=dcxyw
```

### Relevant code snippets

```csharp
"Authority" : "https://customdomain.com/tenant/v2.0?dc=dcxyw
```

### Expected behavior

?dc=dcxyw is taken into account

**Comment by pmaytak** [comment]
@jmprieur In what scenarios are the query params expected for an authority? When passed to MSAL, would these params be added to the /authorize or /token endpoints?
