### ISSUE TITLE
GraphAuthenticationProvider should check the requestinformation URI before appending the header

### ISSUE THREAD

**Issue by andrueastman** [AzureAD/microsoft-identity-web#2710]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.Graph

### Microsoft.Identity.Web version

2.17.0

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

GraphAuthenticationProvider from Microsoft.Identity.Web.GraphServiceClient should validate that the request uri is a valid graph URI before setting the Authorization header. Otherwise, requests made with the graph client in scenarios such as large file upload will cause undesired behaviour. See https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2379

This can also be done by using the [AllowedHostValidator](https://github.com/microsoft/kiota-abstractions-dotnet/blob/00a8f957808246c3b2bebba474655dd8b16a5d4d/src/authentication/AllowedHostsValidator.cs#L51) using the config at https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/5915858fccbb0ff0f7829c27c722bd2dcabc2e48/src/Microsoft.Graph.Core/Authentication/AzureIdentityAccessTokenProvider.cs#L19

### Reproduction steps

See code sample at https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2379

### Error message

```shell
Unhandled exception. Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException: IDW10502: 
An MsalUiRequiredException was thrown due to a challenge for the user.
See https://aka.ms/ms-id-web/ca_incremental-consent.
```

### Relevant code snippets

```csharp
static async Task UploadDriveItem(GraphServiceClient graphServiceClient, Drive drive, string filePath, string itemPath)
{
	Console.WriteLine($"Uploading {filePath} to {itemPath}");
	using var fileStream = File.OpenRead(filePath);


	var uploadSessionRequestBody = new DriveUpload.CreateUploadSessionPostRequestBody
	{
		Item = new DriveItemUploadableProperties
		{
			AdditionalData = new System.Collections.Generic.Dictionary<string, object>
			{
				{ "@microsoft.graph.conflictBehavior", "replace" },
			},
		},
	};

	// Create the upload session
	// itemPath does not need to be a path to an existing item
	// var myDrive = await graphServiceClient.Me.Drive.GetAsync(r => r.Options.WithAppOnly());
	var uploadSession = await graphServiceClient.Drives[drive.Id]
		.Items["root"]
		.ItemWithPath(itemPath)
		.CreateUploadSession
		.PostAsync(uploadSessionRequestBody, r => r.Options.WithAppOnly());

	// Max slice size must be a multiple of 320 KiB
	int maxSliceSize = 320 * 1024;
	var fileUploadTask = new LargeFileUploadTask<DriveItem>(
		uploadSession, fileStream, maxSliceSize, graphServiceClient.RequestAdapter);

	var totalLength = fileStream.Length;
	// Create a callback that is invoked after each slice is uploaded
	IProgress<long> progress = new Progress<long>(prog =>
	{
		Console.WriteLine($"Uploaded {prog} bytes of {totalLength} bytes");
	});

	try
	{
		// Upload the file
		var uploadResult = await fileUploadTask.UploadAsync(progress);

		Console.WriteLine(uploadResult.UploadSucceeded ?
			$"Upload complete, item ID: {uploadResult.ItemResponse.Id}" :
			"Upload failed");
	}
	catch (Microsoft.Graph.Models.ODataErrors.ODataError ex)
	{
		Console.WriteLine($"Error uploading: {ex.Error?.Message}");
	}
}
```

### Expected behavior

Requests made to non-graph urls should not attempt to acquire the token.

**Comment by kellyyangsong** [comment]
@andrueastman thanks for opening this issue - double checking with you on whether you know where the code is for creating the `UploadSession` in the example code snippet - and how did you deduce that the `UploadUrl` was not a graph URL and therefore should not be authenticated?

**Comment by andrueastman** [comment]
@kellyyangsong 
You can checkout the remarks on the resumable file upload for onedrive. The `UploadUrl` returned from the `UploadSession` is not usually a graph host uri. This is also covered in the remarks on how the Auth header should not be set.

https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0&preserve-view=true#remarks

The Messages API also returns an outlook URI and has a similar guidance. 

https://learn.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-1.0&tabs=http#examples

**Comment by kellyyangsong** [comment]
Thank you @andrueastman!
