### ISSUE TITLE
'Mixing web app and web API in the same ASP.NET core app' not working

### ISSUE THREAD

**Issue by David-Renz** [AzureAD/microsoft-identity-web#2742]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.17.4

### Web app

Sign-in users

### Web API

Protected web APIs (validating scopes/roles)

### Token cache serialization

In-memory caches

### Description

My Blazor Server offers anm API and a Web App. The API is used by desktop clients and the web app is like a admin tool to configure and setup things on the server.

Now I want to use my AzureAD to authenticate and authorize my Users. Therefore I use @attribute [Authorize(Roles = "MyRole")] for my razor pages and [Authorize(Roles = "MyRole")] attribute for my controllers.

This in mentioned here: [Mixing web app and web API in the same ASP.NET core app](https://github.com/AzureAD/microsoft-identity-web/wiki/Mixing-web-app-and-web-api-in-the-same-ASP.NET-core-app)

My AzureAd configuration looks like this:

```
"AzureAd": {
  "Instance": "https://login.microsoftonline.com/",
  "Domain": "[mydomain.com]",
  "TenantId": "[myTenantId]",
  "ClientId": "[myClientId]",
  "CallbackPath": "/signin-oidc",
  "SignedOutCallbackPath ": "/signout-callback-oidc"
}
```

Authentication and Authorization with the web app OR the web API is working as soon I remove the other from my code. So my AzureAD should setup and configured correctly.

For my current attempt just one of them is working at the same time:
1. The authentication for my clients via AddMicrosoftIdentityWebApiAuthentication is working but if I try to authenticate in my web app the AzureAd login kind of succeeds, but after the redirect to my app there is no user logged in.
OR
2. The web app authentication works and if I try to user my desktop client to authenticate the client gets and HttpResponseMessage with a http page with cookies disabled warning which it can't handle.

Current attempt:
```
services.AddMicrosoftIdentityWebApiAuthentication(Configuration);
services.AddMicrosoftIdentityWebAppAuthentication(Configuration);
services.AddControllersWithViews().AddMicrosoftIdentityUI();
services.AddRazorPages();
services.AddServerSideBlazor().AddMicrosoftIdentityConsentHandler();
```

### Reproduction steps

1. Setup your ASP.NET Core app like described here: [Mixing web app and web API in the same ASP.NET core app](https://github.com/AzureAD/microsoft-identity-web/wiki/Mixing-web-app-and-web-api-in-the-same-ASP.NET-core-app)
2. Try to use web app **and** API authentication
3. API authentication suceeds
4. web app auth fails

### Relevant code snippets

```csharp
public void ConfigureServices(IServiceCollection services)
{
   ...

   services.AddMicrosoftIdentityWebApiAuthentication(Configuration);
   services.AddMicrosoftIdentityWebAppAuthentication(Configuration);
   services.AddControllersWithViews().AddMicrosoftIdentityUI();
   services.AddRazorPages();
   services.AddServerSideBlazor().AddMicrosoftIdentityConsentHandler();

   ...
}
```

### Expected behavior

Both worlds, user authentication via web app and via API, are working like they do if the over one is "disabled".

**Comment by jmprieur** [comment]
@David-Renz you need to use different authentication schemes for the web app and the web API
See https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes

**Comment by jmprieur** [comment]
Moving to engineering from 12/8
