### ISSUE TITLE
Add threading analyzers and resolve issues

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#2766]
- Add `<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.9.28" PrivateAssets="all" />`
- Resolve the issues - fix or suppress.
   - Rules: https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/index.md
- This project **doesn't** treat warnings as errors. So any default rule severety of warning should be changed to error to match other libraries (IdentityModel). `VSTHRD111` (UseConfigureAwait()) rule needs to be set to warning.

**Comment by westin-m** [comment]
Leaving this in review until PublicApiAnalyzers is enabled in IdWeb to make sure no changes affect the public Api
