### ISSUE TITLE
Update of Microsoft.IdentityModel.* to 7.5.0 only for .NET not .NET Framework

### ISSUE THREAD

**Issue by rastrup** [AzureAD/microsoft-identity-web#2785]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.17.5

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

In releases 2.17.1 and 2.17.3 the packages Microsoft.IdentityModel.* were updated.
But this update was only for .NET, not .NET Framework.
Directory.build.props control the dependency versions and Microsoft.IdentityModel.* is controlled with the <IdentityModelVersion> tag on line 80 but also for .NET Framework on line 153 and 173. These 2 seems to have been forgotten.
Also a general alignment of versions in Directory.build.props seems to be needed as for several dependencies the version referenced is newer for net462 than for net472.

### Reproduction steps

Compare different target frameworks in the Directory.build.props file.

### Relevant code snippets

```csharp
NuGet\Install-Package Microsoft.Identity.Web.TokenAcquisition -Version 2.17.5
```

### Expected behavior

Some alignment of versions referenced when targeting different frameworks.

**Comment by jennyf19** [comment]
This was by-design previously as OWIN samples were not working on the 7x of M.IM. Will re-test and see if we can move to 7.x latest.
