### ISSUE TITLE
Allow OAuth 2.0 Client Credentials Grant without Scope or Roles Claim checking.

### ISSUE THREAD

**Issue by tbrophy** [AzureAD/microsoft-identity-web#281]
**Is your feature request related to a problem? Please describe.**
The only production client of our service passes an Azure AD token without any scopes or claims using this flow; https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-oauth2-client-creds-grant-flow

Because there does not seem to be a way to omit Scope and Roles claim checking that is happening here https://github.com/AzureAD/microsoft-identity-web/blob/0c9b125b6c3beb531e127cecf79a4cee25cf5668/src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs#L129, an exception is thrown with the message "Neither scope or roles claim was found in the bearer token.".

**Describe the solution you'd like**
Allow for an "AzureAd" aspsettings.json declaration of "ClaimsDisabled" (or something like that—see line 2 of snippet below) to turn of Scope and Roles claim checking.

```
"AzureAd": {
    "ClaimsDisabled": [ "Role", "Scope" ],
    "Audience": "our client does pass this"
    "Instance": "https://login.microsoftonline.com/",
    "ClientId": "[Enter_client_ID_Of_TodoListService-v2_from_Azure_Portal, _e.g._2ec40e65-ba09-4853-bcde-bcb60029e596]",
    /*
      You need specify the TenantId only if you want to accept access tokens from a single tenant (line of business app)
      Otherwise you can leave them set to common
    */
    "Domain": "qualified.domain.name", // for instance contoso.onmicrosoft.com. Not used in the ASP.NET core template
    "TenantId": "common" // The tenant's Directory ID (a guid) or 'common' or 'organizations' or 'consumers'

  }
```

**Describe alternatives you've considered**
We have tried to programmatically skip over claims checking (see below altered Startup.cs snippet replacing the commented-out "services.AddProtectedWebApi(Configuration);" line) but there does not seem to be a point where this is possible.

```
        public void ConfigureServices(IServiceCollection services)
        {
            // Adds Microsoft Identity platform (AAD v2.0) support to protect this Api
            // services.AddProtectedWebApi(Configuration);
            services.AddProtectedWebApi(options =>
            {
                Configuration.Bind("AzureAd", options);
                options.Events = new JwtBearerEvents();
                options.Events.OnTokenValidated = context =>
                {
                    return Task.CompletedTask;
                };
            }, options =>
            {
                Configuration.Bind("AzureAd", options);
            });

            services.AddControllers();
        }
```

**Additional context**
A similar request for advice has been documented here; https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/374

**Comment by snebjorn** [comment]
I just encountered this. I'm using a organization specific tenant and we're not passing any roles or scopes. It's simply enough to have a valid token.

So my ASP.NET Core 3.1 API simply returns ERROR 500
> System.UnauthorizedAccessException: IDW10201: Neither scope or roles claim was found in the bearer token.

Also shouldn't that be 401?

**Comment by jennyf19** [comment]
closing as [duplicate](https://github.com/AzureAD/microsoft-identity-web/issues/707) and already fixed.
