### ISSUE TITLE
How do you turn off redirection for the identity framework

### ISSUE THREAD

**Issue by 1957993455** [AzureAD/microsoft-identity-web#2820]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.11.1

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

Not Applicable

### Description

我在是identity来创建后端应用时，我使用了jwt，当我去访问 (When I created the backend application using identity, I used jwt. When I went to access)
```
[Authorize]
[ApiController]
[Route("api/[controller]/[action]")]
public class WeatherForecastController : ControllerBase
{
    private readonly IJwtHelp _jwtHelp;

    public WeatherForecastController(IJwtHelp jwtHelp)
    {
        _jwtHelp = jwtHelp;
    }

    [HttpGet]
    public IActionResult Get()
    {
        return Ok("hello");
    }
}
```
时，它总是给重定向到找不到此`localhost 页面找不到 Web 地址对应的网页: https://localhost:7171/Account/Login?ReturnUrl=%2Fapi%2FWeatherForecast%2FGet`
我改如何把他关闭这是我程序入口的主要代码//Identity配置 (When, it always redirects to Cannot find this. localhost 页面找不到 Web 地址对应的网页: https://localhost:7171/Account/Login?ReturnUrl=%2Fapi%2FWeatherForecast%2FGet
How do I change it to close it? This is the main code of my program entrance //Identity configuration)
```
builder.Services.Configure<IdentityOptions>(options =>
{
    // 密码默认设置
    options.Password.RequireDigit = false;
    options.Password.RequireUppercase = false;
    options.Password.RequiredLength = 6;
    options.Password.RequireNonAlphanumeric = false;
    options.Lockout.AllowedForNewUsers = true;
});

//跨域
builder.Services.AddCors(options =>
{
    options.AddPolicy("default", o =>
    {
        // o.WithHeaders(config.GetSection("Cors:Default").Value);
        o.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin();
    });
});

builder.Services.AddAuthentication(opts =>
{
    opts.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    opts.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    opts.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(opt =>
{
    opt.SaveToken = true;
    opt.RequireHttpsMetadata = false;
    opt.TokenValidationParameters = new TokenValidationParameters()
    {
        ValidateIssuer = true,
        ValidIssuer = config["jwt:Issuer"],
        ValidateAudience = true,
        ValidAudience = config["jwt:Audience"],
        //ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["jwt:SecurityKey"])),
        // ValidateLifetime = true,
    };
});
//激活 Identity API
builder.Services.AddIdentity<User, Role>()
    .AddEntityFrameworkStores<BlogDbContext>()
    .AddDefaultTokenProviders();

//AutoMapper配置
builder.Services.AddAutoMapper(typeof(AutoMapperModule));

var app = builder.Build();
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();`
```

### Reproduction steps

using Autofac;
using Autofac.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using New.Blog.Entity;
using New.Blog.EntityFrameWorkCore;
using New.Blog.Tool.AutoMappers;
using New.Blog.Web.Autofac;
using System.Text;
using System.Text.Json.Serialization;
using Yitter.IdGenerator;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
}); ;
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

//id注入
var idGen = new IdGeneratorOptions(3) { WorkerIdBitLength = 10 };
YitIdHelper.SetIdGenerator(idGen);

var config = builder.Configuration;

//autofac
builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());
builder.Host.ConfigureContainer<ContainerBuilder>(options =>
{
    options.RegisterModule(new AutofacModule(builder.Configuration));
});

//数据库
builder.Services.AddDbContextPool<BlogDbContext>(options =>
{
    options.UseMySql(config.GetConnectionString("Mysql"),
            new MySqlServerVersion(new Version(8, 0, 31)))
        .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
});

//Identity配置
builder.Services.Configure<IdentityOptions>(options =>
{
    // 密码默认设置
    options.Password.RequireDigit = false;
    options.Password.RequireUppercase = false;
    options.Password.RequiredLength = 6;
    options.Password.RequireNonAlphanumeric = false;
    options.Lockout.AllowedForNewUsers = true;
});

//跨域
builder.Services.AddCors(options =>
{
    options.AddPolicy("default", o =>
    {
        // o.WithHeaders(config.GetSection("Cors:Default").Value);
        o.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin();
    });
});

builder.Services.AddAuthentication(opts =>
{
    opts.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    opts.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    opts.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(opt =>
{
    opt.SaveToken = true;
    opt.RequireHttpsMetadata = false;
    opt.TokenValidationParameters = new TokenValidationParameters()
    {
        ValidateIssuer = true,
        ValidIssuer = config["jwt:Issuer"],
        ValidateAudience = true,
        ValidAudience = config["jwt:Audience"],
        //ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["jwt:SecurityKey"])),
        // ValidateLifetime = true,
    };
});
//激活 Identity API
builder.Services.AddIdentity<User, Role>()
    .AddEntityFrameworkStores<BlogDbContext>()
    .AddDefaultTokenProviders();

//AutoMapper配置
builder.Services.AddAutoMapper(typeof(AutoMapperModule));

var app = builder.Build();
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();

### Id Web logs

11

### Relevant code snippets

```csharp
using Autofac;
using Autofac.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using New.Blog.Entity;
using New.Blog.EntityFrameWorkCore;
using New.Blog.Tool.AutoMappers;
using New.Blog.Web.Autofac;
using System.Text;
using System.Text.Json.Serialization;
using Yitter.IdGenerator;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
}); ;
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

//id注入
var idGen = new IdGeneratorOptions(3) { WorkerIdBitLength = 10 };
YitIdHelper.SetIdGenerator(idGen);

var config = builder.Configuration;

//autofac
builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());
builder.Host.ConfigureContainer<ContainerBuilder>(options =>
{
    options.RegisterModule(new AutofacModule(builder.Configuration));
});

//数据库
builder.Services.AddDbContextPool<BlogDbContext>(options =>
{
    options.UseMySql(config.GetConnectionString("Mysql"),
            new MySqlServerVersion(new Version(8, 0, 31)))
        .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
});

//Identity配置
builder.Services.Configure<IdentityOptions>(options =>
{
    // 密码默认设置
    options.Password.RequireDigit = false;
    options.Password.RequireUppercase = false;
    options.Password.RequiredLength = 6;
    options.Password.RequireNonAlphanumeric = false;
    options.Lockout.AllowedForNewUsers = true;
});

//跨域
builder.Services.AddCors(options =>
{
    options.AddPolicy("default", o =>
    {
        // o.WithHeaders(config.GetSection("Cors:Default").Value);
        o.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin();
    });
});

builder.Services.AddAuthentication(opts =>
{
    opts.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    opts.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    opts.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(opt =>
{
    opt.SaveToken = true;
    opt.RequireHttpsMetadata = false;
    opt.TokenValidationParameters = new TokenValidationParameters()
    {
        ValidateIssuer = true,
        ValidIssuer = config["jwt:Issuer"],
        ValidateAudience = true,
        ValidAudience = config["jwt:Audience"],
        //ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["jwt:SecurityKey"])),
        // ValidateLifetime = true,
    };
});
//激活 Identity API
builder.Services.AddIdentity<User, Role>()
    .AddEntityFrameworkStores<BlogDbContext>()
    .AddDefaultTokenProviders();

//AutoMapper配置
builder.Services.AddAutoMapper(typeof(AutoMapperModule));

var app = builder.Build();
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();
```

### Regression

2.11.1

### Expected behavior

关闭身份认证重定向，我不需要重定向到登录地址，当没有身份验证时只需要显示401状态码，因为我使用的是前后端分离

(Turn off authentication redirection. I don't need to redirect to the login address. I only need to display the 401 status code when there is no authentication because I am using front-end and back-end separation.)

**Comment by jmprieur** [comment]
@1957993455 this is a question for ASP.NET Core, not Entra SDKs
https://github.com/dotnet/aspnetcore/issues/new/choose

**Comment by jennyf19** [comment]
closing, please open an issue with asp.net core.
