### ISSUE TITLE
Unable to signin with Microsoft Account (social Azure B2C)

### ISSUE THREAD

**Issue by UM001** [AzureAD/microsoft-identity-web#283]
We're unable to complete your request
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

Core 3.1 and this example:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2.git

With Local Account (own email+pwd) this works, however for Microsoft Account not.

**Comment by jennyf19** [comment]
@UM001 Did you correctly set up the [Microsoft Account(https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-microsoft-account) in the B2C tenant?

**Comment by UM001** [comment]
I was thinking of that as well. Setup seems to have changed. I will verify later. It turned out that this version breaks if the custom page is not properly showing. So I switched it off. I will post my findings later.

**Comment by jmprieur** [comment]
@UM001 closing for now.
Feel free to reopen if that's not a configuration problem.
