### ISSUE TITLE
 Getting Error: IDX10503: Signature validation failed. The token's kid is: 'XXXXXX', but did not match any keys in TokenValidationParameters or Configuration

### ISSUE THREAD

**Issue by ShaneHoffman** [AzureAD/microsoft-identity-web#2917]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.19.1

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

Not Applicable

### Description

I am using the react MSAL library on a SPA and the backend is having difficulty validating the access token.

The KID that the SPA assigns the access token is coming from these keys: https://login.microsoftonline.com/[tenant-id]/discovery/v2.0/keys?appid=[client-id] and the backend is trying to validate the access token with KIDS from these keys: https://login.microsoftonline.com/[tenant-id]/discovery/v2.0/keys

I have double checked that the appSettings.json match the app registration in Azure and what is being used in the React SPA.

### Reproduction steps

1. Create an app registration
2. Login to a React SPA with the react MSAL library to retrieve an access token
3. Request the .NET API with the access token and .AddMicrosoftIdentityWebApi configured

### Error message

Bearer error="invalid_token", error_description="The signature key was not found"

Error: IDX10503: Signature validation failed. The token's kid is: 'XXXXXX', but did not match any keys in TokenValidationParameters or Configuration
Number of keys in TokenValidationParameters: '0'. 
Number of keys in Configuration: '20'.

### Relevant code snippets

```csharp
{
  "AppSettings": {
    "AzureAd": {
      "TenantId": "",
      "ClientId": "",
      "ClientSecret": "",
      "Domain": "",
      "Instance": "https://login.microsoftonline.com/",
      "CallbackPath": "/signin-oidc"
    },
  }
}

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AppSettings:AzureAd"));
```

### Expected behavior

Token to be validated properly

**Comment by JoshLozensky** [comment]
Hi @ShaneHoffman is this issue still occurring for you? If not, what was the fix?

**Comment by JoshLozensky** [comment]
Closing due to no response, please reopen if the issue is reproducible in the latest Id Web version.

**Comment by JoshLozensky** [comment]
Closing due to no response, please reopen if the issue is reproducible in the latest Id Web version.
