### ISSUE TITLE
Getting IDX20803: Unable to obtain configuration from: 'https://login.micorosftonline.com/{tenantId}/v2.0/.well-known/openid-configuration' even though I can access configuration file through browser.

### ISSUE THREAD

**Issue by brainpow3r** [AzureAD/microsoft-identity-web#2918]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.20.0

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating scopes/roles)

### Token cache serialization

Not Applicable

### Description

Stack and relevant packages:

- .NET8 Minimal API
- Microsoft.Identity.Web

I am trying to set up authorization and authentication in my minimal API. I've done everything as described in [these](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis) examples. I am trying to test authenctication and authorization on a single endpoint with Postman. I've generated a valid OAuth2.0 Token and am passing it to the API in `Authorization` HTTP Header. In response, I get `HTTP401 Unauthorized`.

From the error message that I got I noticed that the library is trying to fetch some document, but fails to do so. Here I thought I'll try opening the URL on the browser. To my surprise it fetches the JSON document that's there. I tried sneding a `GET https://login.micorosftonline.com/{myTenantId}/v2.0/.well-known/openid-configuration` on Postman and I also received a `HTTP200 Success` response with the JSON in the body.

![response](https://github.com/AzureAD/microsoft-identity-web/assets/8397671/1b34929d-ef88-4977-b888-458cf512b759)

As I understand, the library is trying to fetch file from the URL in the error message, but it receives `HTTP302 Found` response.

I also wrote a simple console app, which basically just sends a request to the same URL and I can see that it also receives an `HTTP302 Found` response.
![client](https://github.com/AzureAD/microsoft-identity-web/assets/8397671/785fa74a-54cc-47db-9771-97b74d885e96)
![response2](https://github.com/AzureAD/microsoft-identity-web/assets/8397671/3eef18fd-448b-49ac-9455-c0dcbf5022c5)
 

### Reproduction steps

1. Create a .NET8 Minimal API
2. Install latest version (2.20.0 at the time of writing) Microsoft.Identity.Web nuget package.
3. Add `.AddMicrosoftIdentityWebApi(...)` authentication to the API.
4. Create a simple endpoint and add authorization to it.
5. Register the application in Microsoft Azure and make needed configurations so that App can authorize with OAuth2.0 through Microsoft Entra ID.
6. Generate a valid OAuth2.0 token for your API.
7. Call the secured endpoint with the token generated in previous step.

### Error message

_(To obfuscate sensitive data in following snippets I'll use `{myXXX}` format or asterisks)_

Upon executing the request I see the following message in the logs:
```
fail: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      Message: IDX20803: Unable to obtain configuration from: 'https://login.micorosftonline.com/{myTenantId}/v2.0/.well-known/openid-configuration'. Will retry at '03/07/2024 11:02:15 +00:00'. Exception: 'System.IO.IOException: IDX20807: Unable to retrieve document from: 'https://login.micorosftonline.com/{myTenantId}/v2.0/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 302, ReasonPhrase: 'Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        Date: Wed, 03 Jul 2024 11:02:14 GMT
        Server: Apache
        Set-Cookie: __tad=1720004534.7551307; expires=Sat, 01-Jul-2034 11:02:14 GMT; Max-Age=315360000
        Location: http://ww25.login.micorosftonline.com/{myTenantId}/v2.0/.well-known/openid-configuration?subid1=20240703-2102-1447-98b3-f492c72c94de
        Connection: close
        Content-Length: 2
        Content-Type: text/html; charset=UTF-8
      }', HttpResponseMessage.Content: '

'.
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)'., InnerException: IDX20807: Unable to retrieve document from: 'https://login.micorosftonline.com/{myTenantId}/v2.0/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 302, ReasonPhrase: 'Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        Date: Wed, 03 Jul 2024 11:02:14 GMT
        Server: Apache
        Set-Cookie: __tad=1720004534.7551307; expires=Sat, 01-Jul-2034 11:02:14 GMT; Max-Age=315360000
        Location: http://ww25.login.micorosftonline.com/{myTenantId}/v2.0/.well-known/openid-configuration?subid1=20240703-2102-1447-98b3-f492c72c94de
        Connection: close
        Content-Length: 2
        Content-Type: text/html; charset=UTF-8
      }', HttpResponseMessage.Content: '

'
```

### Relevant code snippets

_(To obfuscate sensitive data in following snippets I'll use `{myXXX}` format or asterisks)_

```csharp
To dig deeper where the problem might be I've set 

IdentityModelEventSource.ShowPII = true;
IdentityModelEventSource.LogCompleteSecurityArtifact = true;
```
in my `Program.cs`.

Relevant sections in my Program.cs:
```
...
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration);
...
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();
...
app.MapGet("/user/all", UserActions.GetAll)
    .RequireAuthorization()
    .RequireScope("{myScopes}");
...
```

Relevant configuration section in my appsettings.json looks like this:
```
"AzureAd": {
  "Instance": "https://login.micorosftonline.com/",
  "Domain": "********.onmicrosoft.com",
  "ClientId": "********-****-****-****-************",
  "TenantId": "********-****-****-****-************",
  "Scopes": "{myScopes}"
}
```
```


### Regression

_No response_

### Expected behavior

For library to handle `HTTP302 Found` response correctly. Request is expected to be authorized and callee to get back a `HTTP200 Success` response.

**Comment by jmprieur** [comment]
@brainpow3r 
you seem to have a typo in the instance:

  "Instance": "https://login.**micorosftonline**.com/",  =>   "Instance": "https://login.**microsoftonline**.com/",

**Comment by brainpow3r** [comment]
@jmprieur Thanks! I don't know how me and my colleagues missed it...

I fixed the typo and sadly ran into some other issues too, but with a little experimenting managed to resolve those too. For anyone who might stumble upon this:

When generating the OAuth2.0 token make sure you use 
`https://login.microsoftonline.com/{yourTenantId}/oauth2/v2.0/authorize` as `Auth URL` 
and
`https://login.microsoftonline.com/{yourTenantId}/oauth2/v2.0/token` as `Access Token URL`

I was using `https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize` and `https://login.microsoftonline.com/organizations/oauth2/v2.0/token` respectively and was running into some issues.

My problem is solved, closing the issue.
