### ISSUE TITLE
Cannot use msidentity-app-sync on mac arm - Says i need to install .net 5 which doesn't support arm

### ISSUE THREAD

**Issue by sethreidnz** [AzureAD/microsoft-identity-web#2919]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

msidentity-app-sync 1.0.1

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

I have followed the instructions here for syncing my new app with my AAD app

https://github.com/AzureAD/microsoft-identity-web/blob/master/tools/app-provisioning-tool/vs2019-16.9-how-to-use.md

However when I try to run the command `msidentity-app-sync -h` I get:

```
You must install or update .NET to run this application.

App: /Users/[redacted]/.dotnet/tools/msidentity-app-sync
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (arm64)
.NET location: /usr/local/share/dotnet

The following frameworks were found:
  6.0.28 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  6.0.30 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  8.0.3 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=arm64&rid=osx-arm64&os=osx.14
```

### Reproduction steps

1. Install .net 8 on mac arm silicoln
2. Install the tool `dotnet tool install -g msidentity-app-sync`
3. Run the command `msidentity-app-sync -h`

### Error message

You must install or update .NET to run this application.

App: /Users/[redacted]/.dotnet/tools/msidentity-app-sync
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (arm64)
.NET location: /usr/local/share/dotnet

The following frameworks were found:
  6.0.28 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  6.0.30 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  8.0.3 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=arm64&rid=osx-arm64&os=osx.14

### Relevant code snippets

```csharp
No code required.
```

### Expected behavior

I would expect to be able to use this tool with latest LTS .NET version on mac arm.

**Comment by jennyf19** [comment]
I think we just need to republish it with the .NET 8 target. Can you try with the one in the master branch: https://github.com/AzureAD/microsoft-identity-web/tree/master/tools/app-provisioning-tool and see if that works for you? I don't have a mac, so will not be able to easily test it. If that works, we will republish w/the latest version.

**Comment by JoshLozensky** [comment]
Synced with Seth offline. No longer an issue

**Comment by JoshLozensky** [comment]
Synced with Seth offline. No longer an issue
