### ISSUE TITLE
[Feature Request] Templates have a -callsMicrosoftGraph options that generate calling Microsoft Graph

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#292]
**Is your feature request related to a problem? Please describe.**
Templates have a -callsMicrosoftGraph options that generate calling Microsoft Graph

**Comment by jmprieur** [comment]
@navyasric FYI

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
