### ISSUE TITLE
[Bug] Microsoft.Identity.Web should not call GetAccountsAsync()

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#295]
**Which Version of Microsoft Identity Web are you using ?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
B2C scenario

Other? - please describe;

**Repro**
TokenAcquisition calls GetAccountsAsync in the case of B2C to remove the accounts. However, this will call the token cache serialiation with no suggested cache key.

https://github.com/AzureAD/microsoft-identity-web/search?q=GetAccountsAsync&unscoped_q=GetAccountsAsync

**Expected behavior**
When signing out, the token for a user are removed from the cache

**Actual behavior**
The cache is not cleared as no account is found

**Possible Solution**
- We should probably think of adding all the tokens for all the policies of a given account in the same token cache, which we could clear at once.
 - then we should not call GetAccountsAsync(), but GetAccountAsync(account-without-policy)

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jennyf19** [comment]
Part of this [pr](https://github.com/AzureAD/microsoft-identity-web/pull/331/)

**Comment by pmaytak** [comment]
Included in [Microsoft Identity Web 0.2.1-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.1-preview).
