### ISSUE TITLE
[Documentation] release notes are behind

### ISSUE THREAD

**Issue by mslucasMMID** [AzureAD/microsoft-identity-web#2951]
https://github.com/AzureAD/microsoft-identity-web/wiki/#roadmap

The latest version is from 14 march 2024 2.17.2 but we are now at 3.0.1.
Could this page be updated.

Thanks

**Comment by jmprieur** [comment]
Thanks for the feedback on the roadmap.

The changelog, and the releases are up to date: https://github.com/AzureAD/microsoft-identity-web/blob/master/changelog.md

**Comment by jennyf19** [comment]
What is the status on this @JoshLozensky ? I think you did the work, so closing, as done.
