### ISSUE TITLE
System.TypeLoadException: Method 'CallApiForUserAsync' in type 'Microsoft.Identity.Web.DownstreamApi' from assembly 'Microsoft.Identity.Web.DownstreamApi, Version=3.0.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' does not have an implementation.

### ISSUE THREAD

**Issue by jagdish-kumawat** [AzureAD/microsoft-identity-web#2960]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

3.0.1

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

I upgraded my package from 2.20.0 to 3.0.1. I started getting the titled exception. Below is the code from Program.cs:
`builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
.AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"))
.EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
.AddDownstreamApi("DownstreamApi", builder.Configuration.GetSection("DownstreamApi"))
.AddInMemoryTokenCaches();`

Below is how I call a downstream API. It was working fine on 2.20.0. 
`var response = await _downstreamApi.CallApiForUserAsync(apiName, options =>
{
    options.RelativePath = relativePath;
    options.HttpMethod = httpMethod.Method;

    if (requestData != null)
    {
        options.CustomizeHttpRequestMessage = (message) =>
        {
            // Add any custom headers or other properties to the HttpRequestMessage
            message.Content = new StringContent(JsonConvert.SerializeObject(requestData), Encoding.UTF8, "application/json");
        };
    }
}).ConfigureAwait(false);`

Also, when I reverted back the package upgrade, I kept getting same error but with 2.20.0 version in the error message. I cleaned the solution and rebuilt as well.

### Reproduction steps

1. Package upgrade from 2.20.0 to 3.0.1

### Relevant code snippets

```csharp
Mentioned in description.
```

### Expected behavior

Call downstream api must work.

**Comment by jmprieur** [comment]
Make sure that:
- all the versions of Microsoft.Identity.Web packages are the same
- you don't get Microsoft.IdentityModel package downgrades (if you do, just remove their reference)
- all versions of Microsoft.IdentityModel packages are the same.

To know the versions of packages with transitive dependencies, you can run:

```shell
dotnet list yourProject.csproj package --include-transtive
```

**Comment by jagdish-kumawat** [comment]
Yes, all the versions of Microsoft.Identity.Web are on the same version.
<img width="843" alt="Screenshot 2024-08-01 at 8 56 45 PM" src="https://github.com/user-attachments/assets/8b1fafb4-721e-47ff-9668-394b77e01609">

**Comment by jmprieur** [comment]
What about Microsoft.IdentityModel dependencies?

You don't need to add Microsoft.AspNetCore.Authentication.JwtBearer, and Microsoft.AspNetCore.Authentication.OpenIdConnect, btw, they are transitive dependencies of Microsoft.Identity.Web.

**Comment by jagdish-kumawat** [comment]
Not using Microsoft.IdentityModel dependencies. I created the project from the FluentUI Blazor template in .NET 8. And added Azure Entra ID authentication (Multi Tenant).

**Comment by jmprieur** [comment]
Do you mind creating repro steps? 
I'm not familiar with the FluentUI Blazor apps

**Comment by jagdish-kumawat** [comment]
Thanks for your reply on the issue, it seems, somehow it started working. I reverted my git changes to version 2.20.0. Then, I upgraded each package one by one just to see what caused an issue. Then it started working. Previously, I upgraded all the packages in a bulk.

**Comment by jmprieur** [comment]
Thanks for confirming!
