### ISSUE TITLE
Call WebApi from WebApp returns 401 Unauthorized

### ISSUE THREAD

**Issue by VladislavAntonyuk** [AzureAD/microsoft-identity-web#2965]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

3.0.1

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

I have a default .NET Aspire app with frontend and API service.
User should be able to sign in on UI and make calls to API service.
Unfortunately API request from frontend to Api Service returns 401. (However the desktop client can authenticate and returns response from API service, so Api service configuration is correct)

### Reproduction steps

1. Pull repo: https://github.com/VladislavAntonyuk/BlazorAuth
2. Update appsettings in frontend and apiservice projects
3. Run Aspire AppHost.
4. on Counter Page click Sign In button. You should be redirected and authenticated.
5. Navigate to Weather Page. The API call should be successful. Currently both Downstream Api and HttpClient returns 401.

### Relevant code snippets

```csharp
https://github.com/VladislavAntonyuk/BlazorAuth
```

### Expected behavior

Frontend should receive 200 OK from Api Service

**Comment by jmprieur** [comment]
From a quick look at the code, I think it's because the scopes should be a collection between square brackets on this line (not a single scope)
https://github.com/VladislavAntonyuk/BlazorAuth/blob/70b30b9d5e98b0b298ce1e48141e5f41af33c253/BlazorAuth.Web/appsettings.json#L22

**Comment by VladislavAntonyuk** [comment]
@jmprieur thank you for the quick response, I updated it to array, but the result is the same:
![image](https://github.com/user-attachments/assets/1980086b-4ea7-43a9-929f-a90ff1e03c18)

**Comment by DOMZE** [comment]
@VladislavAntonyuk you may have the same problem I have. See https://github.com/AzureAD/microsoft-identity-web/issues/2968

**Comment by VladislavAntonyuk** [comment]
Well, I was able to make it work using Downstream API, but HttpClient remains unauthorized. Closing it.
For anyone looking for a solution I wrote an article: https://vladislavantonyuk.github.io/articles/Azure-Active-Directory-authentication-in-.NET-Aspire-Distributed-Application/

**Comment by lockhartsoftware** [comment]
@VladislavAntonyuk thank you for doing this.
