### ISSUE TITLE
Reenable ChallengeUser_MicrosoftIdFlow_LocalApp_ValidEmailWithCiamPassword

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/microsoft-identity-web#2982]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

latest

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

Reenable `ChallengeUser_MicrosoftIdFlow_LocalApp_ValidEmailWithCiamPassword`
and `ChallengeUser_MicrosoftIdFlow_LocalApp_ValidEmailPasswordCreds_CallsDownStreamApiWithCiam`

### Reproduction steps

NA

### Relevant code snippets

```csharp
NA
```

### Expected behavior

ChallengeUser_MicrosoftIdFlow_LocalApp_ValidEmailWithCiamPassword passes

**Comment by jennyf19** [comment]
fixed
