### ISSUE TITLE
Using nuget update gives errors

### ISSUE THREAD

**Issue by ehtick** [AzureAD/microsoft-identity-web#2997]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

3.1.0

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

Nuget update gives error

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		Unable to resolve dependencies. 'Microsoft.Identity.Abstractions 7.0.0' is not compatible with 'Microsoft.Identity.Web.Certificate 3.1.0 constraint: Microsoft.Identity.Abstractions (>= 6.0.0 && < 7.0.0)', 'Microsoft.Identity.Web.TokenAcquisition 3.1.0 constraint: Microsoft.Identity.Abstractions (>= 6.0.0 && < 7.0.0)'.		

the abstractions lib is 7.0.0.0.
			

### Reproduction steps

install abstractions 7.0.0.0 and then try to add the 3.1.0 Microsoft.Identities.Web

### Error message

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		Unable to resolve dependencies. 'Microsoft.Identity.Abstractions 7.0.0' is not compatible with 'Microsoft.Identity.Web.Certificate 3.1.0 constraint: Microsoft.Identity.Abstractions (>= 6.0.0 && < 7.0.0)', 'Microsoft.Identity.Web.TokenAcquisition 3.1.0 constraint: Microsoft.Identity.Abstractions (>= 6.0.0 && < 7.0.0)'.					

### Id Web logs

none

### Relevant code snippets

```csharp
nuget
```

### Expected behavior

update the package

**Comment by jmprieur** [comment]
Please update to Microsoft.Identity.Web 3.2.2 where this is fixed.

**Comment by jmprieur** [comment]
Closing as answered.
