### ISSUE TITLE
Update reference to  Microsoft.Identity.Abstrations 7.0

### ISSUE THREAD

**Issue by ehtick** [AzureAD/microsoft-identity-web#2999]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

3.1.0

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

Nuget does not work updating when using the latest Microsoft.Identity.Abstrations 7.0

### Reproduction steps

Add reference to Microsoft.Identity.Abstrations 7.0 and then try to add nuget 

### Error message

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		Unable to resolve dependencies. 'Microsoft.Identity.Abstractions 7.0.0' is not compatible with 'Microsoft.Identity.Web.Certificate 3.1.0 constraint: Microsoft.Identity.Abstractions (>= 6.0.0 && < 7.0.0)', 'Microsoft.Identity.Web.TokenAcquisition 3.1.0 constraint: Microsoft.Identity.Abstractions (>= 6.0.0 && < 7.0.0)'.					

### Id Web logs

none

### Relevant code snippets

```csharp
Nope
```

### Regression

old abstractions

### Expected behavior

Nuget works

**Comment by pmaytak** [comment]
This has been updated. The latest Microsoft.Identity.Web 3.2.0 now references Microsoft.Identity.Abstactions 7.1.0.

**Comment by ehtick** [comment]
Thanxx, updated and it works.
