### ISSUE TITLE
[Feature Request] Allow multi-tenant applications to specify the AppHomeTenantId to be used for client credentials.

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#3121]
**Is your feature request related to a problem? Please describe.**
When a multi-tenant application (TenantId: "common" or "organizations") wants to acquire a token on behalf of itself, Microsoft.Identity.Web can't use the "TenantId" as this is not accepted by ESTS.

Today we require all developers to specify the tenant ID to use by code, or by configuration in the case of IDownstreamApi:

**Describe the solution you'd like**
- [x] Add in the MicrosoftIdentityApplicationOptions (in Microsoft.Identity.Abstractions), a new string property `AppHomeTenantId`, which developers of multi-tenant apps could set in order to define the home tenant of the app (the tenant for which the app can get a token to call a downstream API on behalf of itself). This will usually be the app registration tenant. For instance, add it [here](https://github.com/AzureAD/microsoft-identity-abstractions-for-dotnet/blob/b92053d41909a73742e8241a29ffd5baab73f472/src/Microsoft.Identity.Abstractions/ApplicationOptions/MicrosoftIdentityApplicationOptions.cs#L76)
- [x] In Microsoft.Identity.Web,
   - [x] Add the same property to MergeOptions, and update the method that populates MergedOptions from MicrosoftIdentityApplicationOptions.
   - [x]  when the token acquisition happens "for App", and if the TenantId is "common" or "organization" and the developer has not overriden the "TenantId" in the AcquireTokenOptions, use the `AppHomeTenantId` value. For this we would need to change this expression [here](https://github.com/AzureAD/microsoft-identity-web/blob/011bd155ce3ddedeb43daa7348e09584cfa20552/src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs#L437) to use `mergedOptions.AppHomeTenantId` if it's not null, and throw otherwise, like today
- [ ] For Auto-decrypt (SAL) use the `AppHomeTenantId` if the CredentialDescription.DownstreamApi.AcquireTokenOptions.Tenant is not specified. Might not be necessary as IdWeb does the token acquisition, but needs to be verified
- [ ] For MISE modules data providers, remove the configuration property that was using this tenant and let IdWeb do (or use the new property, instead of exposing it in each module configuration).
 
**Describe alternatives you've considered**
Multiply the same tenant value in all cases of auto-decrypt and MISE modules like today

**Comment by msbw2** [comment]
@jmprieur

> if the TenantId is "common" or "organization" and the developer has not overriden the "TenantId" in the AcquireTokenOptions, use the AppHomeTenantId value.

What does this mean? This seems conflicting (`TenantId` is both one of `common` or `organizations` but also `null`).

**Comment by jmprieur** [comment]
You are right @msbw2, I was not very clear.
in [this](https://github.com/AzureAD/microsoft-identity-web/blob/011bd155ce3ddedeb43daa7348e09584cfa20552/src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs#L418) method, there are 3 tenants involved:
- `tenant` the parameter of the method. This comes from the AcquireTokenOptions.Tenant.
- `mergedOptions.TenantId` which comes from the configuration (AzureAd section, TenantId property)
- `mergedOptions.AppHomeTenantId` which is the new property.

- the `tenant` parameter always has precedence if it's not `null`
- if it's null, we use  `mergedOptions.TenantId` unless it contains `common` or `organizations` in which case we use  `mergedOptions.AppHomeTenantId`, unless it's null in which case we throw the existing exception.
-

**Comment by msbw2** [comment]
> You are right @msbw2, I was not very clear. in [this](https://github.com/AzureAD/microsoft-identity-web/blob/011bd155ce3ddedeb43daa7348e09584cfa20552/src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs#L418) method, there are 3 tenants involved:
> 
> * `tenant` the parameter of the method. This comes from the AcquireTokenOptions.Tenant.
> * `mergedOptions.TenantId` which comes from the configuration (AzureAd section, TenantId property)
> * `mergedOptions.AppHomeTenantId` which is the new property.
> 
> the `tenant` parameter always has precedence if it's not `null`. if it's null, we use `mergedOptions.TenantId` unless it contains `common` or `organizations` in which case we use `mergedOptions.AppHomeTenantId`, unless it's null in which case we throw the existing exception.

@jmprieur Can you help me finish this table?
|`tenant`|`TenantId`|`AppHomeTenantId`|`tenant`|
|-|-|-|-|
|set|*|*|`tenant`|
|not set|set and GUID|*|`TenantId`|
|not set|set and common/org|set|`AppHomeTenantId`|
|not set|set and common/org|not set|exception|
|not set|not set|set|? (maybe `AppHomeTenantId`, but is this case possible)|
|not set|not set|not set|? (is this possible; if so, probably exception)|

**Comment by jmprieur** [comment]
Sure, @msbw2. Thanks for formalizing this. I think I updated your table

**Comment by msbw2** [comment]
@jmprieur https://github.com/AzureAD/microsoft-identity-abstractions-for-dotnet/pull/142

**Comment by msbw2** [comment]
@jmprieur https://github.com/AzureAD/microsoft-identity-web/pull/3132

**Comment by msbw2** [comment]
> * [ ]  For Auto-decrypt (SAL) use the `AppHomeTenantId` if the CredentialDescription.DownstreamApi.AcquireTokenOptions.Tenant is not specified. Might not be necessary as IdWeb does the token acquisition, but needs to be verified
> * [ ]  For MISE modules data providers, remove the configuration property that was using this tenant and let IdWeb do (or use the new property, instead of exposing it in each module configuration).

@jmprieur Do you have pointers to these? In SAL I only found two references to the property, but I'm not sure where `AppHomeTenantId` would be surfaced. In MISE none of the data providers appear to reference it or use a tenant from config whatsoever.

**Comment by jmprieur** [comment]
I'll check @msbw2. Thank you

**Comment by jennyf19** [comment]
released in 3.4.0
