### ISSUE TITLE
Authz Code redemption fails when using certificate for the confidential client

### ISSUE THREAD

**Issue by mrochon** [AzureAD/microsoft-identity-web#3154]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

3.4.0

### Web app

Sign-in users

### Web API

Not Applicable

### Token cache serialization

In-memory caches

### Description

Confidential application should be able to use a certificate to create a client_assertion and use it to authenticate to Entra to exchange authz code. It appears not to do that and so Entra responds with error stating that neither symmetric nor asymmetric credential is included in the code exchange.

### Reproduction steps

1. Create self-signed certificate:
2. Export its public key and upload to the app registration in Entra.
3. Configure app in appsettings.json:
4. Configure MIW:
5. 5. Execute, sign in

### Error message

OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: b78091ff-61a9-407d-9e05-ed0e98418000 Correlation ID: 921a5178-d39a-4dc5-84fa-2e2e97108d96 Timestamp: 2024-11-27 16:40:42Z', error_uri: 'https://login.microsoftonline.com/error?code=7000218'.

### Id Web logs

Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: Microsoft.IdentityModel Version: 8.2.1.0. Date 11/27/2024 16:40:35. PII logging is OFF. See https://aka.ms/IdentityModel/PII for details. 
IDX20805: Obtaining information from metadata endpoint: 'https://login.microsoftonline.com/1165490c-89b5-463b-b203-8b77e01597d2/v2.0/.well-known/openid-configuration'.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21811: Deserializing the string: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' obtained from metadata endpoint into openIdConnectConfiguration object.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21812: Retrieving json web keys from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX20805: Obtaining information from metadata endpoint: 'https://login.microsoftonline.com/1165490c-89b5-463b-b203-8b77e01597d2/discovery/v2.0/keys'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21813: Deserializing json web keys: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX10806: Deserializing json: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' into 'Microsoft.IdentityModel.Tokens.JsonWebKeySet'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21328: Generating nonce for openIdConnect message.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21342: 'RequireStateValidation' = false, not validating the state.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Error: Message contains error: 'invalid_client', error_description: 'AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: b78091ff-61a9-407d-9e05-ed0e98418000 Correlation ID: 921a5178-d39a-4dc5-84fa-2e2e97108d96 Timestamp: 2024-11-27 16:40:42Z', error_uri: 'https://login.microsoftonline.com/error?code=7000218', status code '401'.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Error: Exception occurred while processing message.

Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: b78091ff-61a9-407d-9e05-ed0e98418000 Correlation ID: 921a5178-d39a-4dc5-84fa-2e2e97108d96 Timestamp: 2024-11-27 16:40:42Z', error_uri: 'https://login.microsoftonline.com/error?code=7000218'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
 ---> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: b78091ff-61a9-407d-9e05-ed0e98418000 Correlation ID: 921a5178-d39a-4dc5-84fa-2e2e97108d96 Timestamp: 2024-11-27 16:40:42Z', error_uri: 'https://login.microsoftonline.com/error?code=7000218'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
The thread '.NET TP Worker' (33692) has exited with code 0 (0x0).

### Relevant code snippets

```csharp
$certname = "ups-app4"
$cert = New-SelfSignedCertificate -Subject "CN=$certname" -CertStoreLocation "Cert:\CurrentUser\My" -KeyExportPolicy Exportable -KeySpec Signature -KeyLength 2048 -KeyAlgorithm RSA -HashAlgorithm SHA256 -NotAfter (Get-Date).AddYears(1)
```

```json
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "meraridom2.com",
    "TenantId": "1165490c-89b5-463b-b203-8b77e01597d2",
    "ClientId": "8cb9ed19-ffe3-4fdc-95bb-a3d4f126b6fa",
    "CallbackPath": "/signin-oidc",
    "ResponseType": "code",
    "ClientCertificates": [
      {
        "SourceType": "StoreWithThumbprint",
        "CertificateStorePath": "CurrentUser/My",
        "CertificateThumbprint": "34bff633b846301b48b1f8fcd48b7e8c18a5f446"
      }
    ]
  }
```

```csharp
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(options =>
    {
        builder.Configuration.Bind("AzureAd", options)
});
```

### Expected behavior

Token request completes successfully.

**Comment by jmprieur** [comment]
You should use `ClientCredentials` not `ClientCertificates`.
To help you authoring the configuration, we provide a Json schema: https://[raw.githubusercontent.com/AzureAD/microsoft-identity-web/refs/heads/master/JsonSchemas/microsoft-identity-web.json](https://raw.githubusercontent.com/AzureAD/microsoft-identity-web/refs/heads/master/JsonSchemas/microsoft-identity-web.json)

**Comment by jmprieur** [comment]
Closing as answered.
Fell free to reopen if you still have the issue

**Comment by mrochon** [comment]
I had tried that syntax as well. Gives AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.... 

    "ResponseType": "code",
    "ClientCredentials": [
      {
        "SourceType": "StoreWithThumbprint",
        "CertificateStorePath": "CurrentUser/My",
        "CertificateThumbprint": "70286FFCC0E13648831E2D193A88C1BB12B0C1DC"
      }
    ]
  },

**Comment by jmprieur** [comment]
your certificate description is probably wrong.
Enable logging and see what is wrong (using a recent version of IdWeb. We've added logs for certificates)

**Comment by mrochon** [comment]
Running with IdWeb 3.5.0 get same error. No messages re invalid certs.

```
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: Microsoft.IdentityModel Version: 8.3.0.0. Date 12/08/2024 07:31:22. PII logging is OFF. See https://aka.ms/IdentityModel/PII for details. 
IDX20805: Obtaining information from metadata endpoint: 'https://login.microsoftonline.com/1165490c-89b5-463b-b203-8b77e01597d2/v2.0/.well-known/openid-configuration'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21811: Deserializing the string: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' obtained from metadata endpoint into openIdConnectConfiguration object.
'AuthzCodeWithX509.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21812: Retrieving json web keys from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX20805: Obtaining information from metadata endpoint: 'https://login.microsoftonline.com/1165490c-89b5-463b-b203-8b77e01597d2/discovery/v2.0/keys'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21813: Deserializing json web keys: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX10806: Deserializing json: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' into 'Microsoft.IdentityModel.Tokens.JsonWebKeySet'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21328: Generating nonce for openIdConnect message.
'AuthzCodeWithX509.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Debug: IDX21342: 'RequireStateValidation' = false, not validating the state.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Error: Message contains error: 'invalid_client', error_description: 'AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: e71ef17a-d3fb-4d92-a2c5-e6edeb631400 Correlation ID: 6ea3d76a-41ba-42cd-8ee7-c56a76d43bfa Timestamp: 2024-12-08 07:32:11Z', error_uri: 'https://login.microsoftonline.com/error?code=7000218', status code '401'.
'AuthzCodeWithX509.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AuthzCodeWithX509.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Error: Exception occurred while processing message.

Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: e71ef17a-d3fb-4d92-a2c5-e6edeb631400 Correlation ID: 6ea3d76a-41ba-42cd-8ee7-c56a76d43bfa Timestamp: 2024-12-08 07:32:11Z', error_uri: 'https://login.microsoftonline.com/error?code=7000218'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
 ---> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: e71ef17a-d3fb-4d92-a2c5-e6edeb631400 Correlation ID: 6ea3d76a-41ba-42cd-8ee7-c56a76d43bfa Timestamp: 2024-12-08 07:32:11Z', error_uri: 'https://login.microsoftonline.com/error?code=7000218'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by mrochon** [comment]
Also, if I *ClientCertificates* rather than *ClientCredentials* in appSettings.json, MicrosoftIdentityOptions instance loaded has the correct values for the certificates that my custom code can use to workaround the issue. [Here is my own sample](https://github.com/mrochon/AuthzCodeWithX509) that works correctly, using my own work-around.

**Comment by morymoto** [comment]
@mrochon I was having the same issue as you where I was trying to provide a certificate but kept getting `The request body must contain the following parameter: 'client_assertion' or 'client_secret'.` errors. Based on a hunch while reading [this Reddit post](https://www.reddit.com/r/Blazor/comments/1h6pj52/issues_deploying_blazor_server_app_with_azure/) and the template project generated by `dotnet new webapp --auth SingleOrg --calls-graph`, I tried adding Graph as a downstream API and everything started working.

Here's my `appsettings.json`:

```
   "AzureAd": {
    "CallbackPath": "/signin-oidc",
    "ClientCertificates": [
      {
        "SourceType": "StoreWithDistinguishedName",
        "CertificateStorePath": "LocalMachine/My",
        "CertificateDistinguishedName": "CN=placeholder.foo.com"
      }
    ],
    "ClientId": "redacted",
    "Domain": "redacted",
    "Instance": "https://login.microsoftonline.com/",
    "MapInboundClaims": false,
    "ResponseType": "code",
    "SignedOutRedirectUri": "redacted",
    "TenantId": "redacted"
  },
  // *** Add this section ***
  "DownstreamApi": {
    "BaseUrl": "https://graph.microsoft.com/v1.0",
    "Scopes": [
      "user.read"
    ]
  }
```

And this is in my `Program.cs`:

```
var initialScopes = builder.Configuration["DownstreamApi:Scopes"]?.Split(' ');
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(options =>
    {
        builder.Configuration.GetSection("AzureAd").Bind(options);
        // Override the default OIDC "name" and "role" attribute names with the Entra ID attribute names
        options.TokenValidationParameters.NameClaimType = "name";
        options.TokenValidationParameters.RoleClaimType = "roles";
    })
    // *** Add this section ***
    .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
        .AddMicrosoftGraph(builder.Configuration.GetSection("DownstreamApi"))
        .AddInMemoryTokenCaches();
```

I also needed to add the Microsoft.Identity.Web.GraphServiceClient package:
```
dotnet add package Microsoft.Identity.Web.GraphServiceClient
```

This works with certificates in the `CurrentUser/My` and `LocalMachine/My` certificate stores, but I did need to grant my user the Read permission on the private key in the `LocalMachine/My` store. Without that, I would get permission errors trying to read the certificate.

I don't know why adding the read permission on Graph is required, but after 3 days of trying to figure this out, that is what seems to let you specify a certificate instead of a secret when using Microsoft.Identity.Web to connect to Entra.

Hope this helps.
