### ISSUE TITLE
[Feature Request] Support the BlazorServerWeb-CSharp project template

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#319]
https://github.com/dotnet/aspnetcore/tree/master/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp

**Comment by jmprieur** [comment]
Fixed by PRs:
- https://github.com/AzureAD/microsoft-identity-web/pull/329
- https://github.com/AzureAD/microsoft-identity-web/pull/342

**Comment by pmaytak** [comment]
Included in [Microsoft Identity Web 0.2.1-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.1-preview).
