### ISSUE TITLE
[Feature Request] support the ComponentsWebAssembly-CSharp project template

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#320]
https://github.com/dotnet/aspnetcore/tree/master/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp

**Comment by jennyf19** [comment]
[branch](https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/componentsWebAssembly) started.

**Comment by pmaytak** [comment]
Included in [Microsoft Identity Web 0.2.1-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.1-preview).
