### ISSUE TITLE
[Feature Request] Send minimal server side telemetry

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#327]
**Is your feature request related to a problem? Please describe.**
Being able to send the sku (MsIdWeb) and version in requests to EVO so that we can measure the usage of Microsoft.Identity.Web and proactively contact 1P.

cc: @henrik-me 

We want to know:
- when MSAL makes a call is it initiated by Microsoft.Identity.Web ?
- when Wilson makes a call, is it initiated by Microsoft.Identity.Web?

Today:
- MSAL.NET will send x-client-sku: MSAL.NetCore (and x-client-ver the version)
- ASP.NET Core will send x-client-sku: ID_NETSTANDARD2.0 (and x-client-ver the version) 

We don't want to lose this information.

Therefore, given that Microsoft.Identity.Web acts as an orchestrator, the best is, as @jennyf19 suggested a few weeks ago, to add other properties in addition to the ones we have already. 
x-client-orch: ID_WEB
x-client-orch-ver: (Microsoft.Identity.Web version from the assembly).

**Comment by jmprieur** [comment]
Warning: MSAL sku should not be changed (features are available based on SKU and version)

**Comment by jennyf19** [comment]
@jmprieur to clarify expectations here.

**Comment by jmprieur** [comment]
Experiments done in the following branch: https://github.com/AzureAD/microsoft-identity-web/tree/jmprieur/experimentationsForSpecs

Marking this as blocked as:
- we can change `ID_NETSTANDARD_2` into `ID_NETSTANDARD_2_IDWEB`
- but we cannot add-up `IDWEB` to the `MSAL.NET` sku.
Henrik suggested using the telemetry blob, but they are for APIs, not for SKUs, and they would require surfacing something in the MSAL.NET API anyway, which I don't want to do
- another possibility is to do pattern matching in Kusto, or even better, propagate the correlation ID. See https://github.com/AzureAD/microsoft-identity-web/issues/494
