### ISSUE TITLE
[Feature Request] Class `AadIssuerValidator` public usable

### ISSUE THREAD

**Issue by Fabian-Schmidt** [AzureAD/microsoft-identity-web#332]
**Is your feature request related to a problem? Please describe.**
I want to use this library to validate custom created / received AAD token as part of an Azure Function app.
To reuse code I would like to use the, currently internal, class `AadIssuerValidator`.

**Describe the solution you'd like**
Change class `AadIssuerValidator` from internal to public.
https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs

**Describe alternatives you've considered**
I have to copy and paste the code out of this project and manually update it.

**Additional context**
I got an Azure Function app receiving AAD tokens. In the past I have copied this library into my project. Now that a NuGet feed is available I would like to switch and use it. This prevents me from doing it.

**Comment by jennyf19** [comment]
Included in [0.2.2-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.2-preview)
