### ISSUE TITLE
[Bug] NullReferenceException when providing a certificate store path is missing

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#334]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 0.2.0-preview+

**Where is the issue?**
Certificate retrieval.

**Repro**
Try to load a certificate either from distinguished name or thumbprint. Do not specify store location path.

**Expected behavior**
Default store location path value is applied.

**Actual behavior**
`certificateDescription.Container` ends up being null. Null is passed into `LoadFromStoreWithThumbprint` and `LoadFromStoreWithDistinguishedName`. The default parameter value is not applied.
https://github.com/AzureAD/microsoft-identity-web/blob/b484eebb2044d5da73500bbc7692d58fe9d3a650/src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs#L38-L42

Results in NullReferenceException in `ParseStoreLocationAndName` in `DefaultCertificateLoader`.
https://github.com/AzureAD/microsoft-identity-web/blob/b484eebb2044d5da73500bbc7692d58fe9d3a650/src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs#L163

**Possible solution**
Add a null check; apply default value here:
https://github.com/AzureAD/microsoft-identity-web/blob/b484eebb2044d5da73500bbc7692d58fe9d3a650/src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs#L161-L163

OR

Check if `Container` is null, then call a different overload without passing the null value here:
https://github.com/AzureAD/microsoft-identity-web/blob/b484eebb2044d5da73500bbc7692d58fe9d3a650/src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs#L38-L42

**Comment by jennyf19** [comment]
I was going to fix this, but when going through the code, i don't see how we will ever have a null value here, as there is a default.
![image](https://user-images.githubusercontent.com/19942418/91640215-afcae300-e9d0-11ea-948c-1eb692b90789.png)
I'm not sure how to repro this part from the above issue: "The default parameter value is not applied.", as in our tests, we do not use the default parameter value and even the compiler says this value is not null, and if not passed, the default parameter value is applied. 

Closing as no repro, but feel free to reopen if this is not the case, but will need repro steps and config to do further investigation.
cc: @jmprieur @pmaytak @henrik-me
