### ISSUE TITLE
[Bug] protect the project templates against the usage of --call-graph and --called-webapi-url in case of noAuth

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#337]
**Which version of Microsoft Identity Web are you using?**

For details see https://github.com/dotnet/aspnetcore/pull/24065#discussion_r456584631

cc: @henrik-me @jennyf19 @pmaytak 
I'm going to prioritize this one as well (discovered by @JunTaoLuo who is preparing the insertion in ASP.NET Core)

Also look at comments in https://github.com/dotnet/aspnetcore/pull/24065 and address the feedback

**Comment by pmaytak** [comment]
Included in [Microsoft Identity Web 0.2.1-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.1-preview).
