### ISSUE TITLE
[Documentation] 

### ISSUE THREAD

**Issue by rbrayb** [AzureAD/microsoft-identity-web#341]
### Please check all that apply

- [x ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

"the project is cloned into into a local folder."

"into" is duplicated.

**Comment by jmprieur** [comment]
Thanks for the heads-up @rbrayb 
I fixed it.
