### ISSUE TITLE
[Documentation] Please add a migration guide

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/microsoft-identity-web#346]
Please add a migration guide for people using ASP.NET Core 3.1's AzureAd.UI packages.
- What should they remove from their existing application?
- What should they add?

**Comment by jmprieur** [comment]
@Tratcher : does the following work  for you: 
- https://github.com/AzureAD/microsoft-identity-web/wiki/Web-Apps#with-azure-ad
- https://github.com/AzureAD/microsoft-identity-web/wiki/Web-APIs#why-to-use-microsoftidentityweb-in-web-apis
?
