### ISSUE TITLE
Add "Configuration" examples in README.md  [Documentation] 

### ISSUE THREAD

**Issue by saddlebear** [AzureAD/microsoft-identity-web#35]
### Documentation Related To Component:
services.AddSignIn(Configuration) and services.AddProtectedWebApi(Configuration)

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
Please include examples of "Configuration" in AddSignIn and AddProtectedWebApi in the README.md.

**Comment by jmprieur** [comment]
@saddlebear : which kind of configuration would you want to see? the explanation of the section name? Also did you see that  we are missing overrides for the moment: https://github.com/AzureAD/microsoft-identity-web/issues/2

**Comment by saddlebear** [comment]
The configuration parameters for Azure AD and B2C, possibly in (appsettings.) json format, such as TenantId, ClientId, ClientSecret, RedirectUri's, Policies (sign-in-up, reset-password, etc) and whatever else is required in the config to hook up AD or B2C to the sample web application (and api) that's depicted in the README.   Please don't forget B2C examples, B2C feels like an orphan child sometimes in the docs but it's a really nice, cost-effective service for those of us doing consumer-based web sites.

**Comment by jennyf19** [comment]
Added this to the wiki. will do b2c next.
example here: https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps#web-apps-that-sign-in-users---startupcs
