### ISSUE TITLE
[Bug] Don't use ].DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken) in samples/templates

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#350]
In the templates and dev samples, don't use

`[httpClient].DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);`

but rather create a `HttpRequestMessage` and add the header tot he request.

https://github.com/AzureAD/microsoft-identity-web/search?q=DefaultRequestHeaders.Authorization&unscoped_q=DefaultRequestHeaders.Authorization

**Comment by pmaytak** [comment]
Included in [Microsoft Identity Web 0.2.1-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.1-preview).
