### ISSUE TITLE
[Feature Request] Consider aligning the test projects with the outcome of the templates (if that makes sense)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#355]
**Is your feature request related to a problem? Please describe.**
- Today the dev apps (under test) are coming out of the ASP.NET Core web app and web api incremental tutorial
- As Microsoft.Identity.Web evolved, we introduced project templates

**Describe the solution you'd like**
It would be good, as an exercise to recreate the test apps using the templates (and, if needed, modifying them to get the same level of feature like the todo list)

**Describe alternatives you've considered**
keep things are they are.

**Additional context**
The tutorial might have to be updated too.

**Comment by jennyf19** [comment]
i don't think this is needed now that we have the tool.
