### ISSUE TITLE
[Bug] In templates, Services\DownstreamWebApi.cs, CallWebApi should be named CalledWebApiAsync

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#357]
**Which version of Microsoft Identity Web are you using?**
- Look at the DownstreamWebApi.cs files
- allWebApi is async and should be named CalledWebApiAsync

also change where it's called:
- .razor pages
- controllers.
- .cshtm.cs

**Comment by pmaytak** [comment]
Included in [Microsoft Identity Web 0.2.1-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.1-preview).
