### ISSUE TITLE
General availability date

### ISSUE THREAD

**Issue by utkarsh24** [AzureAD/microsoft-identity-web#364]
I am using this library and it is simply awesome, currently i am using 0.2 preview version.

Next month we are going to production, so please let me know General Availability of this library.

**Comment by jennyf19** [comment]
@utkarsh24 thanks for the feedback. we are aiming for oct - nov 2020 time period. You can follow our [project boards](https://github.com/AzureAD/microsoft-identity-web/projects) for details on the progress towards GA.

**Comment by jennyf19** [comment]
going to close, as answered, but feel free to engage more or open issues as needed.
