### ISSUE TITLE
[Fundamentals] Revisit release build

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#370]
The release build has issues often, especially w/package names and duplicates. There is always at least one issue during a release.

**Comment by jmprieur** [comment]
Fixed:
https://identitydivision.visualstudio.com/IDDP/_releaseDefinition?definitionId=34&_a=definition-history

@jennyf19

**Comment by jennyf19** [comment]
Included in [0.2.2-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.2-preview)
