### ISSUE TITLE
question: is it possible to use this library for using a client_credentials flow?

### ISSUE THREAD

**Issue by StefH** [AzureAD/microsoft-identity-web#372]
## Configure Azure App Registrations
I've this **API** app-registration in Azure:
| setting | value |
|-|-|
| Application ID URI | api://821eb724-edb8-4dba-b425-3f953250c0ae
| scope | API.Access (api://821eb724-edb8-4dba-b425-3f953250c0ae/API.Access)

And a **Client** app-registration in Azure like:
| setting | value |
|-|-|
| ClientId | c64feb8e-4545-4f2c-a0dd-6b72a8d1a8bb
| API Delegated Access Permission | api://821eb724-edb8-4dba-b425-3f953250c0ae/API.Access

## Get Access Token
Getting an access token using postman:
https://login.microsoftonline.com/020b0cf3-d6b2-464e-9b2d-45e124244428/oauth2/token
![image](https://user-images.githubusercontent.com/249938/88452921-f887fd00-ce62-11ea-8dc0-7b9918757c32.png)
![image](https://user-images.githubusercontent.com/249938/88452928-09387300-ce63-11ea-9b34-f4ce37116b4d.png)

## API Controller
The api-controller is defined like this:
``` c#
[Authorize]
[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
    private static readonly string[] Summaries = new[]
    {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

    private readonly ILogger<WeatherForecastController> _logger;

    public WeatherForecastController(ILogger<WeatherForecastController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    [AuthorizeForScopes(Scopes = new[] { "API.Access" })]
    public IEnumerable<WeatherForecast> Get()
    {
        _logger.LogInformation("GET : ");
        var rng = new Random();
        return Enumerable.Range(1, 5).Select(index => new WeatherForecast
        {
            Date = DateTime.Now.AddDays(index),
            TemperatureC = rng.Next(-20, 55),
            Summary = Summaries[rng.Next(Summaries.Length)]
        })
        .ToArray();
    }
```

## Accessing the API using Bearer token (also via postman)
This returns the default login page from Microsoft.
![image](https://user-images.githubusercontent.com/249938/88452993-7815cc00-ce63-11ea-8ff0-99eadb782045.png)

## Question
- Is this scenario supported?
- Or is something wrongly configured?

**Comment by jmprieur** [comment]
@StefH 
Yes, this scenario is supported. 
See https://github.com/AzureAD/microsoft-identity-web/wiki/Web-APIs#web-apis-that-acquire-tokens-on-their-own-behalf-daemon-scenarios-client-credential-flow

**Comment by StefH** [comment]
@jmprieur 
Thanks for your answer, however this does not apply in my scenario. I don't need to delegate the token.

I just want to only allow a **client app registration** which has access to the **API app registration** (via the scope) to call the API controller GET method. 

See my example project : https://github.com/StefH/CallAzureFunctionWithOAuth2-AAD/tree/master/WebApplication2

**Comment by jmprieur** [comment]
@StefH : Do I understand that you would need to do an "on behalf of flow for service principals" ?
If that's the case, this is not supported by Azure AD.

Could you elaborate on your scenario? do you want to send me an email directly (jean-marc.prieur at microsoft dot com)

**Comment by jmprieur** [comment]
@StefH : are you happy with the answers? shall I close this question?
