### ISSUE TITLE
[Documentation] fix doc images w/active-directory-dotnet-native-aspnetcore-v2

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#376]
This article has broken images as well as link. https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-dotnet-native-aspnetcore-v2/calling-an-aspnet-core-web-api-from-a-wpf-application-using-azure-ad-v2/

**Comment by jmprieur** [comment]
To be surfaced correctly in docs.microsoft.com/samples, the links should be absolute (not relative in the repo)

**Comment by pmaytak** [comment]
Verified, we have everything set up correctly. The issue is that VSC-Service-Account doesn't create a release package, which is what gets pushed to the MS Docs server via webhook, which is why the sample on their end was not updated. Docs team created a work item for tracking this on their end.

**Comment by jennyf19** [comment]
Included in [0.2.2-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.2-preview)
