### ISSUE TITLE
[Question] Using JwtAuthentication with Microsoft Identity Platform (Blazor Server App)

### ISSUE THREAD

**Issue by smriti-dahal** [AzureAD/microsoft-identity-web#377]
Hello,

We have a Blazor server app that needs to call multiple webApis (primarily Graph Apis and ARM Apis). We have followed the [template ](https://github.com/AzureAD/microsoft-identity-web/wiki/Web-App-Template#use-the-web-app-blazor-server-template) for this and our code snippet looks like below:
![image](https://user-images.githubusercontent.com/64666806/88866452-99f2b400-d1bf-11ea-962b-0e52a3cd4f51.png)

We're having some difficulty configuring our application using the identity platform with jwt authentication. Can you provide guidance on how to move forward with this?

Thanks.

**Comment by jmprieur** [comment]
@smriti-dahal. I'm not clear what you are trying to do, so guessing here.

However, something clear is you have a Web app, and try to configure the JwtBearerOptions (which are for Web apis). You need to use the OpenIdConnect events in a Web app.

You can configure them directly with Microsoft.Identity.Web, or after the fact (with a call to `Configure<OpenIdConnectOptions>` similarly to what you did) need to use a different override of `AddMicrosoftWebApp`. See [advanced scenarios | using delegates](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps#using-delegate-events), and [Customization](https://github.com/AzureAD/microsoft-identity-web/wiki/customization)

```CSharp
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
   .AddMicrosoftWebApp(options =>
                {
                    Configuration.Bind("AzureAD", options);
                    options.Events ??= new OpenIdConnectEvents();
                    var existingHandlers = options.Events.OnTokenValidated;
                    options.Events.OnTokenValidated = YourOwnHandler;
                    options.Events.OnTokenValidated += existingHandlers;
                })
                .AddMicrosoftWebAppCallsWebApi(Configuration, 
                                                                          scopes,
                                                                         "AzureAd")
                .AddInMemoryTokenCaches()
;
```

**Comment by jmprieur** [comment]
Closing as this was taken offline
