### ISSUE TITLE
[Bug] Daemon applications do not require a redirectUri but it's required in TokenAcquisition

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#38]
In `TokenAcquisition`, the redirect uri is calculated if the cc application is created there. However, when creating a Daemon application and using the ConfidentialClientApplicationOptions, the redirectUri is not required, so `TokenAcquisition` calculates a redirecturi which is not registered or needed, and MS Identity Web currently throws a null ref here.

**Comment by pmaytak** [comment]
This is included in [Microsoft Identity Web 0.2.1-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.1-preview).
