### ISSUE TITLE
[Bug] Unable to retrieve document from: 'https://{instance}/{TenantId}/v2.0/.well-known/openid-configuration' using Azure AD B2C

### ISSUE THREAD

**Issue by efonsecab** [AzureAD/microsoft-identity-web#384]
**Which version of Microsoft Identity Web are you using?**
**0.2.1 Preview**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [**X**] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?** 
**C**

**Repro**
Following these steps which used to work in the past: https://youtu.be/wNf7gYcA1eg
now the system is expecting having a TenantId in the configuration

**Expected behavior**
A clear and concise description of what you expected to happen (or code).
Auth building the authentication string correctly without having to trick the configuration
**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.
The error message in the title

**Possible solution**

I had to trick the TenantId in order for the flow to work as expected
"TenantId": "{domain}/{policy}"

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jennyf19** [comment]
@efonsecab It's not completely clear what you are doing. If you were using the templates from Visual Studio, and now using Microsoft Identity Web, there are differences. 
Are you using `login.microsoftonline.com`, or `*.b2clogin.com` or a custom domain? 
Can you share the appsettings.json w/us? 
Have you see this [B2C sample which uses Microsoft Identity Web](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C) or tried the [templates](https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template)?
Thanks.

**Comment by efonsecab** [comment]
I found the issue already, it turned out to be a typo in configuration tha end up showing this error.

**Comment by jennyf19** [comment]
Thanks for getting back to us @efonsecab
