### ISSUE TITLE
Should RoleClaimType be mapped to roles by default?

### ISSUE THREAD

**Issue by molntamas** [AzureAD/microsoft-identity-web#391]
I noticed that in the latest version I cannot add validation for a role as a C# attribute to an MVC controller anymore.
Instead I have to add a line in the controller action.

I would still like to be able to use this syntax

```
[Authorize("role")]
MyController
{
...
```

instead of 

`HttpContext.ValidateAppRole("role")`

Would this be possible in the future?
Or do I have to implement an attribute myself?

**Comment by pmaytak** [comment]
Hello.
Web app [sample 5-1](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/5-WebApp-AuthZ/5-1-Roles/Startup.cs) shows how to use roles. Have you made sure that the role claim type is set to the one that's in claims?

```csharp
            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                // The claim in the Jwt token where App roles are available.
                options.TokenValidationParameters.RoleClaimType = "roles";
            });
```

**Comment by jmprieur** [comment]
@molntamas @pmaytak @brentschmaltz @jennyf19 should Microsoft.identity.web set this by default?

**Comment by jmprieur** [comment]
This is now documented in https://github.com/AzureAD/microsoft-identity-web/wiki/Web-APIs#verification-of-scopes-or-app-roles-in-the-controller-actions

**Comment by brentschmaltz** [comment]
@jmprieur sorry for the late response, i think you are better off NOT setting by default.
So it looks like you did the right thing.

A strong solution would have the IdentityProvider specify what claim type should be used for 'roles'.
We do know what AAD uses and could have a switch that maps to the AAD behavior.

**Comment by molntamas** [comment]
Thanks for the feedback.
With version 2.3 Preview it actually worked for me without adding this:

```
services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                // The claim in the Jwt token where App roles are available.
                options.TokenValidationParameters.RoleClaimType = "roles";
            });
```

And adding 
`Authorize(Roles = "myRoleName")`

But I guess it is safer to specify the role claim type explicitly. Or what is recommended?

**Comment by jennyf19** [comment]
@molntamas yes, please specify the roles explicitly.

Closing, but please reopen if needed.
