### ISSUE TITLE
[Bug] Exception thrown for non-default user flows when a B2C app issues user flow in a 'tfp' claim

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#394]
**Which version of Microsoft Identity Web are you using?**
0.2.1-preview

**Repro**
- Set up a B2C app registration issuing a user flow claim in a 'tfp' token instead of 'acr'.
- Login into [B2CWebAppCallsWebApi](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/B2CWebAppCallsWebApi) Client app.
- Click **Edit Profile**, then click **Continue**.

**Actual behavior**
`Microsoft.Identity.Client.MsalUiRequiredException: AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1_susi and Expected Value : B2C_1_edit_profile` exception is thrown.

**Possible solution**
In `AddAccountToCacheFromAuthorizationCodeAsync`
replace
`string? userFlow = context.Principal?.Claims?.FirstOrDefault(c => c.Type == ClaimConstants.UserFlow)?.Value;`
with
`string? userFlow = context.Principal?.GetUserFlowId();`

**Comment by jennyf19** [comment]
@pmaytak i see you assigned this to me, is there an action item for me?

**Comment by pmaytak** [comment]
@jennyf19 Just created this for tracking. Assigned to you, to give you credit for the fix.

**Comment by jennyf19** [comment]
Included in [0.2.2-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.2-preview)
