### ISSUE TITLE
Identity.Web.UI should use Razor pages, not MVC

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#4]
Why?

Microsoft.Identity.Web.UI (in removeUI branch) currently uses MVC. The advise of the ASP.NET Core team is to change it to use Razor pages because Razor pages have an extensibility model can be overridden by copy / paste in the user project, therefore replacing the pages which are provided by the library

What?
The advise of the ASP.NET Core team is to change MVC pages to Razor pages

Copied from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/290

**Comment by jmprieur** [comment]
@jennyf19 @pmaytak : closing this issue because Microsoft.Identity.Web.UI already uses Razor pages (not MVC Views)
It's done!
