### ISSUE TITLE
In AadIssuerValidator, make the config manager an injectable singleton

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#402]
Currently in AadIssuerValidator, `ConfigurationManager` is a private static variable.
https://github.com/AzureAD/microsoft-identity-web/blob/d33ab13b7ef11f33fa4b8a4eca7949a79c95a144/src/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs#L25

Investigate to possibly make it an injectable singleton, so it's easier to fake/replace.

**Comment by Tratcher** [comment]
Compare to the options pattern AspNet uses that allows you to provide a backchannel and/or a configuration manager:
https://github.com/dotnet/aspnetcore/blob/3fdbc2e90d9762324ef3809098c9ca25b0cb3284/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectPostConfigureOptions.cs#L67-L105

**Comment by jennyf19** [comment]
Included in [1.2.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.2.0).
