### ISSUE TITLE
[Bug] Remove the Microsoft.AspNetCore.DataProtection.Abstractions dependency

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/microsoft-identity-web#410]
https://github.com/AzureAD/microsoft-identity-web/blob/d23ca81bd6c7511b5bfeccf63d490f79dbbd63bd/src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj#L84

You shouldn't need this dependency, it should be pulled in transitively.

If you really do need it, it should be moved to the TFM specific dependency section so you get the correct 3.x or 5.x version.
https://github.com/AzureAD/microsoft-identity-web/blob/d23ca81bd6c7511b5bfeccf63d490f79dbbd63bd/src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj#L72-L80

**Comment by jennyf19** [comment]
thanks @Tratcher this will be in our next release, later this week (0.2.2-preview)

**Comment by jennyf19** [comment]
Included in [0.2.2-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.2-preview)
