### ISSUE TITLE
[Feature Request] Support for non-AAD token authorize filter to protect API endpoints

### ISSUE THREAD

**Issue by ankitk20** [AzureAD/microsoft-identity-web#416]
**Is your feature request related to a problem? Please describe.**
Custom JWT based authorization instead of AAD

**Describe the solution you'd like**
Global authorization filter for custom JWT token instead of AAD token. The below codes secures the API with AAD token.

services.AddMicrosoftWebApiAuthentication(Configuration) // this statement adds AAD token authorization to all APIs
					.AddMicrosoftWebApiCallsWebApi(Action<ConfidentialOptions>, Action<MicrosoftIdentityOptions>);

The above code expects AAD token while invoking the APIs

**Describe alternatives you've considered**
Revert back to using MSAL.NET

**Additional context**
1. A JWT token is returned to the calling client after successful basic authentication
2. This JWT token is then used for every other API requests

**Comment by jmprieur** [comment]
@ankitk20 
I don't understand your scenario. What are you trying to achieve? how can we help you (given that our library is to help using AAD and Azure AD B2C ?)

If you don't want to use Azure AD, you can also just use:
`services.AddAuthentication(OpenIdConnectDefault.AuthenticationScheme)`, and start from there?

If you want to customize what Microsoft.Identity.Web does (for AAD), you can read https://github.com/AzureAD/microsoft-identity-web/wiki/customization

Then if you don't use Azure AD why would you use MSAL.NET ?

Again, we are happy to help, but I'm confused about what you want to achieve. Maybe an idea of your architecture would help?

**Comment by ankitk20** [comment]
I hav Basic Auth in the app which returns a custom JWT token to the client. The client uses this token to access the controllers. The controllers use Service Principal auth using MSAL to invoke Microsoft REST endpoints.

Now, with the given code on [Wiki](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis) it adds AAD authorization to all the controllers in the service. My question is how can I keep the custom authorization intact and just leverage the Service Principal flow of this new library?

**Comment by ankitk20** [comment]
@jmprieur any update on this?

**Comment by jmprieur** [comment]
@ankitk20. What is basic auth?  do you mean username/password?
and what is service principal auth? do you mean client credentials (AcquireTokenForClient?)

Do you want to draw an architectural diagram of your solution? showing where you want to use MIcrosoft.Identity.Web. 
Do you want to share some repro of the issue you've been experiencing?

**Comment by ankitk20** [comment]
Yes, basic auth is username/password and service principal is using _GetAccessTokenForAppAsync()_

This is issue I face when I try to use _AddMicrosoftWebApiCallsWebApi()_ as below

`services.AddAuthentication("OAuth").AddJwtBearer("OAuth", options => ....)
                                .AddMicrosoftWebApiCallWebApi(...)
                                .AddInMemoryTokenCaches()`

<img width="681" alt="error" src="https://user-images.githubusercontent.com/13991339/89987076-0af39a80-dc9b-11ea-9f3a-a7c1657d363c.png">

**Comment by jmprieur** [comment]
@ankitk20 
you should not call .AddMicrosoftWebApiCallWebApi without having called .AddMicrosoftWebApi(), at least that's not a scenario we have tested.
If you really want to do that, in relation to what I see in your screenshot, you'd need .AddHttpClient at least

https://github.com/AzureAD/microsoft-identity-web/blob/18fe4cef0f65ac76c42da87b097c009c9eebba1e/src/Microsoft.Identity.Web/WebApiExtensions/WebApiAuthenticationBuilderExtensions.cs#L83-L85

Something you could always do is:
 
```CSharp
services.AddAuthentication("OAuth")
    .AddMicrosoftWebApi(options => ..., "OAuth".) 
   .AddMicrosoftWebApiCallWebApi(...)
```
and then use the customization to avoid

**Comment by ankitk20** [comment]
Thanks @jmprieur ! Adding `services.AddHttpClient()` to the middleware worked. I've just one question before I close this Issue.
Is the below code (from your reply) used to override default AAD authorization by a custom JWT based authorization or is it just used to customize the default AAD authorization?

services.AddAuthentication("OAuth")
    .AddMicrosoftWebApi(options => ..., "OAuth".) 
   .AddMicrosoftWebApiCallWebApi(...)
  .AddInMemoryTokenCaches();


services.Configure<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme, options =>
{
  options.Events.OnTokenValidated = async context =>
  {
  }
});

**Comment by jmprieur** [comment]
The following code avoids testing for scopes and roles when the token is validated.

```CSharp
services.Configure(JwtBearerDefaults.AuthenticationScheme, options =>
{
options.Events.OnTokenValidated = async context =>
{
}
});
```

**Comment by ankitk20** [comment]
Thanks!
