### ISSUE TITLE
Update Templates and Dev Apps w/new API for 0.3.0-preview

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#418]
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2
https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2

- [ ] Web app MVC
- [ ] Web app Razor
- [ ] Web app Blazor server
- [ ] Blazor web assembly
- [ ] Web API

Can MS identity web be referenced w/ *? so the templates will use whichever is latest version.

**Comment by pmaytak** [comment]
Side note: `Version="*"` gets the latest stable version. `Version="*-*"` gets the latest version including pre-release.
[Reference](https://github.com/NuGet/Home/wiki/Support-pre-release-packages-with-floating-versions#common-scenarios)

**Comment by jmprieur** [comment]
The samples are, for the moment, using .NET Core 3.1, and I would not recommend moving them to 5.0 until it's RC or GA as this would add a tax to customers.

**Comment by jmprieur** [comment]
Proposal for templates update in https://github.com/AzureAD/microsoft-identity-web/pull/397, part of https://github.com/AzureAD/microsoft-identity-web/pull/397/commits/83a292186b9e231067f7bc4128c74e77c255e52a

**Comment by jennyf19** [comment]
Included in [0.3.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.3.0-preview).
