### ISSUE TITLE
Running locally vs deployed on Azure

### ISSUE THREAD

**Issue by tymtam2** [AzureAD/microsoft-identity-web#433]
### Documentation related to component
Web Api

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [x] needs an example

### Description of the issue

# TL;DR

In a asp.net core 3.1 setup, a console app using `ConfidentialClientApplicationBuilder` and `AcquireTokenForClient` calls a web api set up with `AddMicrosoftWebApiAuthentication` setup. 
The api runs locally the web api serves the content, but when the web api is deployed to Azure it returns HTTP 401 Unauthorized, with and without the *Authentication / Authorization* section configured.

Question: How to debug what is wrong with the setup?

Maybe separately, what is the relationship between the "AzureAd" section of `appsettings.json` and the *Authentication / Authorization* blade of the azure portal? 

# Details 
I am working on Scenario 2-Call-OwnApi' from [A .NET Core daemon console application using Microsoft identity platform (formerly Azure AD v2.0)](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2)

[![enter image description here][1]][1]

The web api and the console client app are asp.net core 3.1.

Web Api `appsettings.json`:
```
 "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "ClientId": "client-guid",
    "Domain": "XXX.onmicrosoft.com",
    "TenantId": "ad-tenant-guid"
  },
```
*(in real files the real guids are set)*

Client conf:
```
{
	"Instance": "https://login.microsoftonline.com/{0}",
	"Tenant": "ad-tenant-guid",
	"ClientId": "clientclientid",
	"ClientSecret": "secret",
	"CertificateName": "[Or instead of client secret: Enter here the name of a certificate (from the user cert store) as registered with your application]",
	"TodoListBaseAddress": "http://localhost:12345",
	"TodoListScope": "api://guid/.default"
}
```

A dedicated AD tenant is used for this that has 2 app registrations. One exposes the api, one is granted access to it.

**It works when both apps are run locally**

The API exposes multiple roles and in the web api code I can see expected claims.

After publishing the app to Azure (`https://~myapp.azurewebsites.net`) and changing the base address the client app can obtain the token but the response to api call is HTTP 403 (empty body). 

I have experimented with the *Authentication / Authorization* section in the Azure portal being

 * off 
 

    [![enter image description here][3]][3]
 * configured

    [![enter image description here][4]][4]

  [1]: https://i.stack.imgur.com/DO5hD.png
  [2]: https://i.stack.imgur.com/pPlXM.png
  [3]: https://i.stack.imgur.com/ldhAz.png
  [4]: https://i.stack.imgur.com/zWw1H.png

**Comment by jmprieur** [comment]
What error do you get, @tymtam2 ?
You definitively want to have App Service authentication off. 

Did you see this article? 
https://github.com/AzureAD/microsoft-identity-web/wiki/deploying-to-app-services

**Comment by tymtam2** [comment]
@jmprieur It seems the problem was between the seat and the keyboard. It works.

**Comment by jmprieur** [comment]
Thanks for the update, @tymtam2
