### ISSUE TITLE
The collection type 'Microsoft.Graph.IUserAppRoleAssignmentsCollectionPage' on 'Microsoft.Graph.User.AppRoleAssignments' is not supported.

### ISSUE THREAD

**Issue by Cholo981** [AzureAD/microsoft-identity-web#435]
I got this error trying to call Graph from an API. 
What does it means?

**Comment by jmprieur** [comment]
@Cholo981 
This is a question for the Microsoft Graph team.

@dkershaw10 @darrelmiller can you please help?

**Comment by jennyf19** [comment]
closing as not relevant to MS identity web.

**Comment by darrelmiller** [comment]
@Cholo981 This repo https://github.com/microsoftgraph/msgraph-sdk-dotnet is the right one to open this issue.  It could be that you are trying to use the latest preview of Microsoft.Graph.Core with the Microsoft.Graph library.  That won't work unfortunately.  You need to use the latest non-preview version of Microsoft.Graph.Core.

**Comment by poundingCode** [comment]
the error means that your project is complaining about the TodoTask.ITodoTaskExtensionsCollectionPage  property.
Create a new class that matches the TodoTask class, but doesn't have ITodoTaskExtensionsCollectionPage  property
Map your variables to that class.  And away you go...
