### ISSUE TITLE
[Bug] Blazor server apps require scoped services  -> error `Cannot resolve scoped service 'Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider'`

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#438]
Due to the nature of Blazor server, with multiple user contexts on the same app, all the services must be scoped, not singleton. Now, in order to support the Microsoft Graph SDK, we have to implement a Singleton for token acquisition. This does not work with Blazor, as the token acquisition will be registered as a singleton.

This is the error that is surfaced:
`System.InvalidOperationException: 'Cannot resolve scoped service 'Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider' from root provider.'
`

@jmprieur to have conversation w/Microsoft Graph SDK.

**Comment by jennyf19** [comment]
FYI: putting this on your radar: @DanielMannInCycle @schmid37 @gwgrubbs @jaimunday @josheinstein

**Comment by jmprieur** [comment]
@jennyf19 @henrik-me @pmaytak 
this does not seem to repro;
Moving it to a later milestone (won't cause API breaking changes anyway)

**Comment by jmprieur** [comment]
Closing for now
Will reopen if this error really happens.

**Comment by JannyM85** [comment]
Hello I have the same problem. When I use DbContextFactory. When I use DbContext its working ok. 
You can simulate this bug on page counterfail a correct behavior on counter page. [Download demo project here.](https://drive.google.com/file/d/1MoPHHpRtG2m74rZHR5ft2yVJW7sF6dh2/view?usp=sharing)
![image](https://user-images.githubusercontent.com/13817757/111752340-de89a780-8895-11eb-9358-f244f9592b3f.png)

I'm solving this bug on [docs.micrososft.com](https://docs.microsoft.com/en-us/answers/questions/318230/blazor-server-it-is-possible-get-current-loged-use.html)
