### ISSUE TITLE
[Bug] JWT validations fails with ClientId: client-guid and no Audience.

### ISSUE THREAD

**Issue by ramiglez30** [AzureAD/microsoft-identity-web#446]
**Which version of Microsoft Identity Web are you using?**
Microsoft.AspNetCore.Authentication.AzureAD.UI **v3.1.7**

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ x] Sign-in users and call web APIs
* Web API
    * [ x] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app.

**Repro**

```csharp
services.AddAuthentication(AzureADDefaults.JwtBearerAuthenticationScheme)
              .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));
```
```json
"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "mytenant.onmicrosoft.com",
    "TenantId": "tenant-gui",
    "ClientId": "client-id-guid"
  }
```

**Expected behavior**
API should authenticate without issues with basic configuration as documented.

**Actual behavior**
Here is what I have found. Scenario: SPA using JWT token to authenticate an API. The spa gets the token successfully, inside we have all information required, the audience (aud) is: "api://clientid-guid". But then with the basic configuration, JWT validations fails and the error said "invalid audience 'api://clientid-guid' ". Adding Audience parameter to appsettings.json did not help. The only thing that worked for me was to change in appsettings.json ClientId to: "api://clientid-guid". For me, it looks like it took ClientId as a valid Audience. I'm not sure this behavior is expected or not. 

**Possible solution**
If taking ClientId to create the valid Audience, the valid audience string should be formatted insight your code as to keep ClientId being a guid in appsettings.json. And/Or successfully load valid Audience from appsettings.json. (it did not work for me)

**Additional context / logs / screenshots**
I manage to make it work using: 
```json
"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "mytenant.onmicrosoft.com",
    "TenantId": "tenant-gui",
    "ClientId": "api://client-id-guid"
  }
```

**Comment by jmprieur** [comment]
@ramiglez30 if you want to use Microsoft.AspNetCore.Authentication.AzureAD.UI, then is an issue for aspnetcore, not Microsoft.Identity.Web

If, on the other hand, you are happy to use Microsoft.Identity.Web you'd do the following and that would just work:

```CSharp
   services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
           .AddMicrosoftWebApi(Configuration, "AzureAd");
```

BTW, Microsoft.AspNetCore.Authentication.AzureAD.UI is going to be deprecated in .NET 5.0.

cc: @Tratcher @blowdart

**Comment by blowdart** [comment]
You should definately switch now @ramiglez30 if you can, it will be easier in the long run.

**Comment by jennyf19** [comment]
closing as answered. Thanks @ramiglez30
