### ISSUE TITLE
How to make Azure AD access_token compliant for its signature validation outside Microsoft Graph APIs?

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [AzureAD/microsoft-identity-web#452]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
0

I have created a Azure AD Mobile and desktop applications. Now I am getting my access_token using following API,

POST https://login.microsoftonline.com/{Directory (tenant) ID }/oauth2/token password:pass client_id:id resource:https://graph.microsoft.com grant_type:password client_secret:secret username:userName scope: openid

The response looks like, "access_token": "acessToken", "refresh_token": "refereshToken", "id_token": "id_token".

Now I am passing the access_token to a third party application which is configured with same Azure AD client. When that third party application tries to validate the signature, the operation fails. Then got to know its because of nonce which is available for only microsoft graph APIs. Now how to remove the same or make my access_token signature verification compliant?**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@PSHREYASHOLLA : 
You should not validate a token in a mobile/desktop application. you acquire a token which is for a web API which is the only to be able to validate it (you don't have the keys)

You might want to look at the following documentation? https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-overview

Finally, how is this question related to MIcrosoft.Identity.Web ? from what you describe you're not using it, are you?

**Comment by jennyf19** [comment]
closing as answered, please reopen if needed. @PSHREYASHOLLA
