### ISSUE TITLE
[Feature Request] Update the project templates to use the new public API 

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#453]
**Is your feature request related to a problem? Please describe.**
0.3.0-preview

**Describe the solution you'd like**
- Have the template generate projects using the new public API and the MicrosoftGraph and DownstreamApi services
- Refresh the templates from the ASP.NET core ones in RC1

**Comment by jennyf19** [comment]
Included in [0.3.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.3.0-preview).
