### ISSUE TITLE
How can I call ITokenAcquisition.GetAccessTokenForUserAsync from startup.cs

### ISSUE THREAD

**Issue by mia01** [AzureAD/microsoft-identity-web#460]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 0.2.3-preview

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [x] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of Microsoft Identity Web.

**Repro**

I'm trying to upgrade one of the projects I'm working on to use the Microsoft.Identity.Web nuget package. So far really working well but I'm having trouble figuring out how to add additional claims which I was previously doing by the following: 

            services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
            {
                options.Events.OnAuthorizationCodeReceived = async ctx =>
                {
                    var serviceProvider = services.BuildServiceProvider();
                    var distributedCache = serviceProvider.GetRequiredService<IDistributedCache>();

                    var identifier = ctx.Principal.FindFirst(ObjectIdentifierType)?.Value;

                    var cca = ConfidentialClientApplicationBuilder.CreateWithApplicationOptions(new ConfidentialClientApplicationOptions()
                    {
                        ClientId = "ClientId",
                        RedirectUri = "RedirectUri",
                        ClientSecret = "ClientSecret"
                    })
                    .WithAuthority(ctx.Options.Authority)
                    .Build();

                    var tokenCache = new SessionTokenCache(identifier, distributedCache);
                    tokenCache.Initialize(cca.UserTokenCache);
                    var token = await cca.AcquireTokenByAuthorizationCode(scopes, ctx.TokenEndpointRequest.Code).ExecuteAsync();

                    ctx.HandleCodeRedemption(token.AccessToken, token.IdToken);

                    // get the claims
                    var claimService = serviceProvider.GetRequiredService<ClaimService>();
                    var response = await apiClient.GetUserAdditionalClaimsAsync(token.AccessToken);
                    
                    // add the claims
                };

Now when I try to use the ITokenAcquisition.GetAccessTokenForUserAsync() method instead of using the `ConfidentialClientApplicationBuilder` 

```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftWebApp(options =>
    {
        Configuration.Bind("AzureAD", options);
        options.Events.OnAuthorizationCodeReceived = async ctx =>
        {
            var serviceProvider = services.BuildServiceProvider();
            var tokenAcquisition = serviceProvider.GetRequiredService<ITokenAcquisition>();

            var token = await tokenAcquisition.GetAccessTokenForUserAsync("scopes");

            // get the claims
            var claimService = serviceProvider.GetRequiredService<ClaimService>();
            var response = await apiClient.GetUserAdditionalClaimsAsync(token);

            // add the claims
        };
    })
    .AddMicrosoftWebAppCallsWebApi(Configuration, new[] { "scopes" })
    .AddDistributedTokenCaches();

```

I get the following error:
[![enter image description here][1]][1]

Any help would be so much appreciated on how best to handle this. 
Thanks!

  [1]: https://i.stack.imgur.com/NPObh.png

**Comment by jmprieur** [comment]
@mia01 : did you see this article? https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

**Comment by jmprieur** [comment]
@mia01 

you'd need something like the following:
```CSharp

       services.AddMicrosoftWebApp(Configuration)
                    .AddMicrosoftWebAppCallsWebApi(Configuration)
                    .AddMemoryTokenCaches();

        services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
        {
            var previousEventHandler = options.Events.OnAuthorizationCodeReceived;
            options.Events.OnAuthorizationCodeReceived = async ctx =>
            {
             // Ensure the Auth code is processed and the cache populated
             await previousEventHandler(ctx);

            // Get the token acquisition service here
           var tokenAcquistion = serviceProvider.GetRequiredService<ITokenAcquisition>();
           var token = await tokenAcquisition.GetAccessTokenForUserAsync("scopes");
         }
       }
```

**Comment by mia01** [comment]
@jmprieur  thanks for that snippet. Looks like it could work IIUC!
I'll give it a go...

**Comment by mia01** [comment]
@jmprieur I've tried this yet still getting the exact same error, unfortunately :(

**Comment by jmprieur** [comment]
@mia01 : I'm trying to understand your scenario. Why do you want to acquire a token from the Startup.cs, and not from the controller actions / Razor/Blazor pages ?

**Comment by sameer-kumar** [comment]
I'm also having the same issue/error and have similar use case. I want to make a call to Graph service to retrieve user membership so that I can add Group names as claims.

**Comment by pmaytak** [comment]
@sameer-kumar I see from [this issue](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/421#issuecomment-702431176) that you issue was resolved related to this?

**Comment by mia01** [comment]
> @mia01 : I'm trying to understand your scenario. Why do you want to acquire a token from the Startup.cs, and not from the controller actions / Razor/Blazor pages ?

@jmprieur we are trying to add a bunch of custom claims to the user. We want to add this once when user is authenticated. We determine what claims the user by calling Graph Api which means we need the token at that point.

**Comment by mia01** [comment]
@sameer-kumar I'm interested what was the code that worked for you?

**Comment by sameer-kumar** [comment]
@pmaytak yes, my use case is solved. 
@mia01 I just followed along [this](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/5-WebApp-AuthZ/5-2-Groups/Startup.cs) with my custom modifications specific to my use case and it works for me.

**Comment by jmprieur** [comment]
Closing as it's answered.
See also this code (and the called method) which does it: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/b07a9e06206f7274fdcadc34a50b8bebf9666fcf/5-WebApp-AuthZ/5-2-Groups/Startup.cs#L51

**Comment by munkii** [comment]
We'd like to be able to centralise the configuration of our HttpClient in Startup.cs. So instead of 

`services.AddHttpClient<IMyService, MyService>();`

We are moving to something like this,

```
services.AddHttpClient(nameof(MyService), (hc) =>
            {
                string apiBaseAddress = this.configuration["MyApi:BaseAddress"];
                hc.BaseAddress = new Uri(apiBaseAddress);
                hc.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            });
```

That works fine but if we wanted to move the following in there too 

```
var accessToken = await tokenAcquisition.GetAccessTokenForUserAsync(new[] { this.configuration["ClinicianApi:Scopes"] });
hc.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
```

We'd need access to ITokenAcquisition in Startup. There are a few references that suggest calling 

```
var serviceProvider = services.BuildServiceProvider();
var tokenAcquisition = serviceProvider.GetRequiredService<ITokenAcquisition>()
```
However if you do that you get a warning when you build, ["Avoid calls to BuildServiceProvider in ConfigureServices"](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#ASP0000 )

Therefore we would still like to know "How can I call ITokenAcquisition.GetAccessTokenForUserAsync from startup.cs"

**Comment by jmprieur** [comment]
Updating the proposed solution: @mia01 @munkii 

```CSharp

       services.AddMicrosoftWebApp(Configuration)
                    .AddMicrosoftWebAppCallsWebApi(Configuration, new string[] { "scopes", "you", "need" ))
                    .AddMemoryTokenCaches();
       services.AddMicrosoftIdentityConsentHandler();

        services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
        {
            var previousEventHandler = options.Events.OnAuthorizationCodeReceived;
            options.Events.OnAuthorizationCodeReceived = async ctx =>
            {
             // Ensure the Auth code is processed and the cache populated
             await previousEventHandler(ctx);

            // Get the token acquisition service here
           var tokenAcquistion = serviceProvider.GetRequiredService<ITokenAcquisition>();
           var consentHandler = serviceProvider.GetRequiredService<MicrosoftIdentityConsentAndConditionalAccessHandler>(); 

           try
           { 
            var token = await tokenAcquisition.GetAccessTokenForUserAsync("scopes");
           }
          catch (Exception ex)
          {
            consentHandler .HandleException(ex);
          }
         }
       }
```
