### ISSUE TITLE
[Bug] ADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials

### ISSUE THREAD

**Issue by sprakash10** [AzureAD/microsoft-identity-web#462]
version : 0.2.3-preview
How do I call downstream api. I am trying to call "GetAccessTokenForAppAsync" but I get the above-mentioned error. I am using multi tenant setup. Tenant is "common" in appsettings. It's .net core web app.

below appsettings
"Instance": "https://login.microsoftonline.com/",
    "Domain": "xxxx.com",
    "TenantId": "common",
    "ClientId": "ac2b0838-xxxxxxxxxxxxx",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-oidc",
    "ClientSecret": "boBTm_xxxxxxxx",
    "AadAuthorityAudience": "AzureAdMultipleOrgs"

I will be calling the downstream api, and user is not signed in yet.

Thanks

**Comment by jmprieur** [comment]
@sprakash10 
If you want to use GetAccessTokenForAppAsync you need:
- either to configure your tenantId to a tenanted authority
- or to pass-in the tenantId to GetAccessTokenForAppAsync (which is a feature coming in 0.3.0-preview)

**Comment by sprakash10** [comment]
Thanks, jmprieur
I don't understand what do you mean by the first bullet. However glad to know that the next release will have a way to pass the tenant id. I have done some workaround to accomplish the task.

**Comment by sprakash10** [comment]
Thanks. This works well in this release.
