### ISSUE TITLE
[Bug] AddAccountToCacheFromAuthorizationCodeAsync isn't accessible

### ISSUE THREAD

**Issue by sprakash10** [AzureAD/microsoft-identity-web#465]
version 0.2.3

below code
/// <code>
        /// private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context)
        /// {
        ///   var tokenAcquisition = context.HttpContext.RequestServices.GetRequiredService&lt;ITokenAcquisition&gt;();
        ///    await _tokenAcquisition.AddAccountToCacheFromAuthorizationCode(context, new string[] { "user.read" });
        /// }
        /// </code>

ITokenAcquisition doesn't expose the above-mentioned method.

**Comment by jmprieur** [comment]
@sprakash10 
It's now implemented by another interface: [`ITokenAcquisitionInternal`](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/ITokenAcquisitionInternal.cs)

Why do you need it? can you please explain your scenario?

Isn't using `WebAppCallsWebApi` (or `EnableTokenAcquisitionToCallDownstreamApi` in 0.3.0-preview) enough ?

**Comment by pmaytak** [comment]
@sprakash10 0.3.0-preview was released today. [Wiki](https://github.com/AzureAD/microsoft-identity-web/wiki/0.3.0-preview#calling-microsoft-graph-and-downstream-apis) has info and examples on how you can call downstream APIs.

**Comment by jmprieur** [comment]
@sprakash10: If you [build the .NET core project templates for Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template) from the repo (we have not released them yet), you can create a project doing exactly what you want:

```Shell
dotnet new blazorserver2 --auth  SingleOrg --called-api-url "https://localhost:12345" --called-api-scopes "api://{someguid}/access_as_user"
```

Then look in the CallWebApi page.
I confirm you don't need at all to use AddAccountToCacheFromAuthorizationCodeAsync

Closing this issue for now
feel free to reopen if you need.

**Comment by sprakash10** [comment]
Thanks. Correct I don't need to use above method at all.
