### ISSUE TITLE
[Investigate] how to handle exceptions in MS identity web

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#47]
@bgavrilMS brought up a good point about exceptions [here](https://github.com/AzureAD/microsoft-identity-web/pull/39#discussion_r386016125)...just something we need to explore

**Comment by jmprieur** [comment]
Fixed in 0.2.1-preview.
Documentation in https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access
