### ISSUE TITLE
[Feature Request] During auth code redemption, send `code_verifier` to /token endpoint as part of auth code + pkce

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#470]
**Background**
For details, see the spec for auth code + pkce for [public clients](https://tools.ietf.org/html/rfc7636).

Auth code + pkce was originally implemented for public clients as they are susceptible to having the auth code intercepted. However, more and more confidential clients are wanting to implement pkce:
![image](https://user-images.githubusercontent.com/19942418/90693264-5d98fd80-e22b-11ea-9bba-368a736cbbf5.png)

ASP NET Core surfaces the `code_verifier` in the AuthenticationProperties [collection on the event context](https://github.com/dotnet/aspnetcore/blob/524c8cda631206ded37f7f57ac7a6e5d0bd7d3b9/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L1118-L1124).

Part of this work is adding a client secret for the web app, in the templates, now as the secret will be used to verify the client.

**Next Steps**
MSAL .NET needs to support auth code + pkce for confidential clients first, so that we can use it during auth code redemption. See [issue here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1473).

ASP NET starts the first leg of the auth code flow, and includes code_challenge and code_challenge_method to the /authorize endpoint.

Then, the second part, MS Identity Web, using MSAL, will need to send the code + code_verifier (which we will get in the AuthenticationProperties) so that the server can verify the original code_challenge. 

We need to complete the work in MSAL .NET first. 
We can use the MSAL Java implementation for this. 

Here is where the developer provides the code_challenge and code_challenge_method:
https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/AuthorizationRequestUrlParameters.java#L84

And where the developer passes in the code_verifier.
https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/AuthorizationCodeParameters.java#L47

**Comment by jmprieur** [comment]
See also https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1323064

**Comment by jennyf19** [comment]
What I'd like to see for this:
A new override of AcquireTokenByAuthorizationCode that takes the code_verifier. The changes to Id Web should be minimal, 1-2 lines. Just getting the code_verifier from the event context on the AuthenticationProperties in ASP.NET and giving to the AcquireTokenByAuthorizationCode method.
Like this for example:

```csharp
public async Task AddAccountToCacheFromAuthorizationCodeAsync(
    AuthorizationCodeReceivedContext context,
    IEnumerable<string> scopes)
{
    if (context == null)
    {
        throw new ArgumentNullException(nameof(context));
    }

    if (scopes == null)
    {
        throw new ArgumentNullException(nameof(scopes));
    }

    try
    {
        _application = await GetOrBuildConfidentialClientApplicationAsync().ConfigureAwait(false);

        string codeVerifier = context.Properties.Items.TryGetValue(OAuthConstants.CodeVerifierKey, out codeVerifier);
        var builder = _application
            .AcquireTokenByAuthorizationCode(
                       scopes.Except(_scopesRequestedByMsal),
                       context.ProtocolMessage.Code,
                       codeVerifier)
            .WithSendX5C(_microsoftIdentityOptions.SendX5C);
....
//more here

```

**Comment by jmprieur** [comment]
Bloked until MSAL.NET 4.30 releases

**Comment by jennyf19** [comment]
Included in [1.9.2 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.9.2)

**Comment by tedvanderveen** [comment]
Hi @jennyf19 I'm a bit stuck. I try to use PKCE auth against B2C from our ASP.Net web application.
I have setup our B2C app in Azure so it accepts PKCE. But I have a hard time getting this to work. I get this error:
`IDX21336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.`

I must be missing a config setting. Can you spot the issue here?

I do see the `code_verifier` going through the wire:
![image](https://user-images.githubusercontent.com/1763519/117322923-baf2de80-ae8e-11eb-9fe3-20571b43dc0d.png)

Azure B2C setup:
![image](https://user-images.githubusercontent.com/1763519/117322407-4750d180-ae8e-11eb-8ba2-0f43240eb66f.png)

**Comment by jmprieur** [comment]
@tedvanderveen you should use a Web platform, not a Single Page application (which is only for MSAL.js 2.x+)

**Comment by tedvanderveen** [comment]
@jmprieur @jennyf19 for PKCE flows in B2C, you need a "Single Page application" platform, although the name is a bit confusing here. As stated in the initial post of this Issue, PKCE can/should now also be used by confidential web applications. So I assume selecting "Single Page application" is what we need to get Auth code + PKCE in B2C play nice with the new bits introduced with latest version (1.9.2) of this library?

**Comment by jmprieur** [comment]
@tedvanderveen, I think that this is because you don't need to do anything in the B2C app registration, in order to enable PKCE in a B2C web app.

So, no. don't add "Single Page application". It would only work with blazorwasm applications or MSAL.js applications.

**Comment by jennyf19** [comment]
@jmprieur is correct, you shouldn't have to do anything as app developer using Microsoft Identity Web to enable PCKE, it's on by default and your app should just work as it did before, with no code or registration changes.

**Comment by tedvanderveen** [comment]
@Ponant yes it just works!

**Comment by Ponant** [comment]
Razor pages? It does not work locally, but I just implemented so I will check further.

**Comment by Ponant** [comment]
If I do this (with razor pages .net 5 b2c, upgraded to latest nuget 1.9.2), then I do not get the code_challenge sent out

**Comment by Ponant** [comment]
I can confirm anew. I tested several options (even knowingly that it won't work).

In the portal, with a web option:

If I disable implicit grant (Access and idtokens checkboxes) I get the error (before login flow). And Url has no code_challenge

**AADB2C90057: The provided application is not configured to allow the 'OAuth' Implicit flow.**

If I enable only ID tokens (used for implicit and hybrid flows), the same error.

If I add to the startup.cs 
` options.ResponseType = OpenIdConnectResponseType.Code;
                    options.Scope.Add(options.ClientId);`
Then I see a code_challenge in the url 
Then I can go through the login flow but then it throws
**'AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.**

If I remove the code above, which is essentially the base template, then the app works but no code_challenge
