### ISSUE TITLE
Test generated projects from 0.3.0-preview templates

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#480]
## Test the generated templates 

1. Build the Microsoft.Identity.Web.sln solution: from the root of the repository:
   ```Shell
   dotnet pack /p:ClientSemVer=0.3.0-preview Microsoft.Identity.Web.sln
   ```  
1. Delete Microsoft.Identity.Web and MIcrosoft.Identity.Web.UI from the .nuget cache.
1. Delete the `ProjectTemplates\bin\Debug\tests` folder.
1. Run the `ProjectTemplates\test-templates.bat` file (in a developer command prompt)
1. Open the `ProjectTemplates\bin\Debug\tests\tests.sln` solution
1. Test the following projects
   - [x] blazorserver2/blazorserver2-b2c
   - [x] blazorserver2/blazorserver2-b2c-callswebapi
   - [x] blazorserver2/blazorserver2-singleorg
   - [x] blazorserver2/blazorserver2-singleorg-callsgraph
   - [x] blazorserver2/blazorserver2-singleorg-callswebapi
   - [ ] blazorwasm2/blazorwasm2-b2c
   - [ ] blazorwasm2/blazorwasm2-singleorg
   - [ ] blazorwasm2/blazorwasm2-singleorg-callsgraph
   - [ ] blazorwasm2/blazorwasm2-singleorg-callswebapi
   - [ ] blazorwasm2/blazorwasm2-b2c-hosted
   - [ ] blazorwasm2/blazorwasm2-singleorg-hosted
   - [ ] blazorwasm2/blazorwasm2-singleorg-callsgraph-hosted
   - [ ] blazorwasm2/blazorwasm2-singleorg-callswebapi-hosted
   - [x] mvc2/mvc2-b2c
   - [x] mvc2/mvc2-b2c-callswebapi
   - [x] mvc2/mvc2-singleorg
   - [x] mvc2/mvc2-singleorg-callsgraph
   - [x] mvc2/mvc2-singleorg-callswebapi
   - [x] webapp2/webapp2-b2c
   - [x] webapp2/webapp2-b2c-callswebapi
   - [x] webapp2/webapp2-singleorg
   - [x] webapp2/webapp2-singleorg-callsgraph
   - [x] webapp2/webapp2-singleorg-callswebapi
   - [ ] webapi2/webapi2-b2c
   - [ ] webapi2/webapi2-singleorg
   - [ ] webapi2/webapi2-singleorg-callsgraph
   - [ ] webapi2/webapi2-singleorg-callswebapi

**Comment by jennyf19** [comment]
Included in [0.3.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.3.0-preview).
