### ISSUE TITLE
Incremental consent throwing exception in blazor app.

### ISSUE THREAD

**Issue by sprakash10** [AzureAD/microsoft-identity-web#483]
Version user: 0.2.3-preview

Followed configuration explained in https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access for blazor app. However, it throws below exception:
![image](https://user-images.githubusercontent.com/53528930/90968770-3b6ade00-e4be-11ea-8a51-3b9676b025c8.png)

Below is my code
protected override async Task OnInitializedAsync()
        {
            Products = new List<ProductDto>();
            try {
                Products = await ProductSvc.GetProductsAsync().ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                ConsentHandler.HandleException(ex);
            }

        }

        [Inject]
        public IProductService ProductSvc { get; set; }

        public IEnumerable<ProductDto> Products { get; set; }

        [Inject]
        public MicrosoftIdentityConsentAndConditionalAccessHandler ConsentHandler { get; set; }

Any help appreciated.

Thanks

**Comment by jennyf19** [comment]
@sprakash10 did you add this to startup.cs:
```csharp
services.AddServerSideBlazor()
         .AddMicrosoftIdentityConsentHandler();
```
and this as well:
```@csharp
app.UseEndpoints(endpoints =>
{
   endpoints.MapControllers();
   // More here
});
```

**Comment by sprakash10** [comment]
@jennyf19, Yes.

**Comment by jennyf19** [comment]
@sprakash10 do you have a repro you can share?

**Comment by jennyf19** [comment]
@sprakash10 actually, you might want to wait until we release 0.3.0-preview, which contains a [fix for blazor](https://github.com/AzureAD/microsoft-identity-web/issues/437) (i thought we had already released this one), you can also try removing the pre-rendering.

**Comment by jennyf19** [comment]
@sprakash10 we've released 0.3.0-preview, there are API breaking changes in this one. see https://aka.ms/ms-id-web/0.3.0-preview for details.

**Comment by jennyf19** [comment]
closing as i believe this is fixed in 0.3.0-preview. please reopen if needed. thanks. @sprakash10

**Comment by sprakash10** [comment]
I am getting different issue now. Flow is getting stuck in infinite loop. I have verified all the code, it is the same as explained in the wiki. Browser keep in redirecting between given two URLs. I don't know what's wrong.

https://login.microsoftonline.com/common/reprocess?ctx=rQIIAY2TO4vjVgCF7fGMd3ZCyORB2CYwkC1C4I6vrKcHUkiWZEuy5Jc8lhyC0NtX1suWxg-lDymnDGkC2W5JmkAgbJV6YMkWYYu06bZKtkqRIrP_IM0HB86B03xnD8hL8hJewk8b7Ut49dh22w5kcAb4nQ4FCBhggKGDAGC-5-C43fYDF27eOzt_-e-Xr73Pn6vfvXr05Pf0t7-f1j9elmVeXLVaceba8TIryiuCwCm6VaAwRSnIkOf-Uq-_qNefHhUUTuME3sYJeE8Cdgj8chF5K40PK7NiS62nEtoUQrMS44EeHlTeLdVI2C_mKm7qAlSrMbnQJ7GaCPgiMkszkQ4muu_rZjWYi_GwJ5Warlamzh7M-SIe8gL2x9E7Q_amXLbfINugyn999DDINomV33_9tvHVcTfgZUYyNB8H4nRbatsJUqb-ULVZeZe7-0xkg5FjZSGaY9Us8BkCwGjFFeJeYuQtDxVOQiopWOzG2XDCtUla7LJ9E-6ExC2V-4UkxWvPFwyfw9fUWE5LCdsCfuoyirJIqO7EX2cTBAUAEwC6TBAPq9Uop5Uo62tsJWnCSJhHG07aGHZITQIb7DEoUXju2ga7olfGImUiLVd3xAxDq07ioNE85aby1gqdea6Nh7qxsnvWWInlfrqkPXN3SHKNXGqmWwlLMVgK3rzPuihJVsoU0QfAGjGkRAhC44ZRyYLD9wNxEHV3iO_ueijzunycbdPSWGIUfhBJsr0mFzxFdq_FHZcgNx4WBxNW1JQEa0fGhvtKHygYNuvpoAhvvHgip30MD_3ezgG7FV12CHhth6EyS6JEj1SB77MJd903tswEWKMVwoh1wbgyJngLah4YprXmJk7M95xq6tJIFg_0WrPd3Y2lxV3Ozpx2ZK490QAempJ8lHVX87jHg5npFInomVTaC8ephSpOsvKK1OWhS8-oZAq3458aTTdLkix91nhMY6TTwZ0AdDCCBEQAO8B2HRu4LkG4GN1xSDK4a3yU5X6KvIt8kwUo9i-yIIhR6lu26_pF8eK4_ur4w9OT85NHtYvaJx_AxtXp6dl57U3657j-_cm9TX--5RDPv-hyT2ovfyh__rF2d9LK2lILb6kKpmbwGivlWElEsT22MTNnenvSV_frohjYpbGFn2FX2G2zftts3jbfv2u-K_GWJuhTndV4dsK3LfhXs_71g9qzh_9H0W_O6r--XfsP0&sessionid=715b93bf-9145-4f09-acba-cc44c179b55f

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=ac2b0838-e996-40f1-87ff-1edb33a2efc0&
redirect_uri=https%3A%2F%2Flocalhost%3A44367%2Fsignin-oidc&
response_type=code%20id_token&scope=openid%20profile%20offline_access&
response_mode=form_post&
nonce=637343235748506940.M2M0ZDljNTItODMyOC00NTlhLWIyMTctYWZhMWFmN2NlOGQ4NmYwODZkNGQtZGMyMC00MDI0LWI0ZWEtMWE2ZjA4OTcxNTI0&client_info=1&state=CfDJ8IXNe3-FSvtNvRiKSeOMaALGKoZ_JZExuzKvV40_28bAOSdaVOrQq82q4my1nYQ5gXd7pKSi7OJ9ZGXqAcQEi4DVi4HGN3PzFGHt1_a0yDtTeFSeru27ww-R54dvnYlLqWVMJ1i6akOD-Pa4m5iYFQWRhyFglmzwtmsbS0bjUfsgUZpHVV86pZDQLeHYLRTGdak3Z_mQ-b3wqplDqA09UmvXvWfFkwHCK18O3jSNmxpwEam10O3w2ENhiPDQjnrKdk-DOALPCoaimeNgpQpqPSKDq2_IuvmBos_mdLqFY41OCF0iX5XBhNEe9cBUWgqWF2MtvCJQ7FCRrlN-REfKE84dcm5rie13Rvbg7Qfg1UpxVGQbFJtpa-Dm233qt06DxHhtFMXaNmx21eEXQwBYLUzjrkffpUirHPArgKYNYWofeACuFJ1HN_armNO-3wVVyGL0pWjosZa0Wn5a-H_CyOPRU55Su0PEuXZIxRz3_uYuPS5DnGlVi1-xtKJ7zZ5b8g&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0

**Comment by jennyf19** [comment]
@sprakash10 do you have a repro you can share?

**Comment by hbulens** [comment]
@sprakash10 Did you find a solution?
