### ISSUE TITLE
[Bug] Infinite loop in B2C when acquiring a token with a different policy/user-flow

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#484]
**Which version of Microsoft Identity Web are you using?**
0.3.0-preview

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

B2C

**Repro**
- Run the test app (**B2CWebAppCallsWebApi\TodoListClient** and **B2CWebAppCallsWebApi\TodoListService**)
- Click the **TodoList** button, the user is signed-in with the SUSI policy (works)
- Click the **Claims (susi)**, the claims are displayed (works)
- Click the **Claims (edit-profile)** button: 

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
there is an infinite loop because  `AuthorizeForScopesAttributes.cs` line 101, the properties does not contain the user flow (edi-profile) as `IncrementalConsentAndConditionalAccessHelper.BuildAuthenticationProperties()` does not consider the user flow (which sis a member of AuthorizeForScopesAttribute)

**Possible solution**
Pass-in the user flow to `IncrementalConsentAndConditionalAccessHelper.BuildAuthenticationProperties()` and add it as a property

**Comment by jennyf19** [comment]
Included in [0.3.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.3.0-preview).
