### ISSUE TITLE
[Feature Request] Need for a blazor server B2C test app

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#488]
**Is your feature request related to a problem? Please describe.**
In order to test b2C specificities like policies and conditional access with B2C, we'd want to have a blazor server B2C test app.

**How to get it**
My recommendation would be to clone the **BlazorServerCallsGraph** sample (blazor.csproj), to for instance creating a new folder blazor-server-b2c and then change a few files in the cloned project to accommodate the B2C registration. I would think that the following changes would do the work (starting both the blazor-server-b2C (this new project) and the b2C web API part of the B2CWeppAppCallsWebApi folder. the following values were actually copied from the **TodoListClient** in the **B2CWeppAppCallsWebApi** folder

### lauchsettings.json
```Json
"sslPort" : 44365
```

### appsettings.json
1. Change the instance, domain, tenantID, clientID:
  ```Json
  "Instance": "https://fabrikamb2c.b2clogin.com",
  "Domain": "fabrikamb2c.onmicrosoft.com",
  "TenantId": "fabrikamb2c.onmicrosoft.com",
  "ClientId": "fdb91ff5-5ce6-41f3-bdbd-8267c817015d",
  ```
 2. Add policies:
  ```Json
  "SignUpSignInPolicyId": "b2c_1_susi",
  "ResetPasswordPolicyId": "b2c_1_reset",
  "EditProfilePolicyId": "b2c_1_edit_profile", // Optional profile editing policy
  ```

2. Remove the `GraphBeta` section (as B2C does not call graph)

3. Change the `CalledApi` section to call the b2C TodoList service?
  ```Json
    "CalledApi": {
        "Scopes": "https://fabrikamb2c.onmicrosoft.com/tasks/read",
        "BaseUrl": "https://localhost:44332/api/todolist"
    },

  ```

### CalledWebApi.razor
the `options.RelativePath` should be set to `""` (empty string) instead of me as we now longer call graph and the full API URL is provided in the config file.

### ShowProfile.razor
I would just do a copy paste of the `CalledWebApi.razor` page, except the first line (which needs to remain `@page "/showprofile"`)

Then, in order to test what happens when we call Web API with a different user flow, I would override the user flow:

```CSharp
            response = await downstreamAPI.CallWebApiForUserAsync(
                    "CalledApi",
                    options => { options.RelativePath = "";
                                         options.UserFlow = "b2c_1_edit_profile"; 
                                       });
```

### Optional
In `Shared\NavMenu.razor`, we could change "Show profile" into "Edit profile"

**Comment by jennyf19** [comment]
Included in [0.3.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.3.0-preview).
