### ISSUE TITLE
[Bug] Fix .NET Core 3.1 blazorwasm2 and blazorserver project template

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#490]
**Which version of Microsoft Identity Web are you using?**
0.3.0-preview

**Where is the issue?**
blazorwasm project template

**Repro**
Create a blasorwasm project from the template

**Expected behavior**
The expected UI appears with the menu bar on the left side

**Actual behavior**
The UI is not great. There is an error in the browser that `_framework/scoped.styles.css` cannot be found

**Investigation**
The templates only work for .NET Core 5.0 Preview 8+

**Proposed fix**
See example in https://github.com/AzureAD/microsoft-identity-web/pull/487/files, detailed as follows

#### ComponentsWebAssembly-CSharp/Client/Program.cs
- line 25 replace `"#app"` by `"app"`

#### ComponentsWebAssembly-CSharp/Client/MainLayout-Auth.razor
- line 3 and line 18 remove the <div class="page"> and the corresponding </div>

#### ComponentsWebAssembly-CSharp/Client/MainLayout-NoAuth.razor
- line 3 and line 18 remove the <div class="page"> and the corresponding </div>
(same changes as previous file)

#### delete the following files
- ComponentsWebAssembly-CSharp/Client/Shared/MainLayout.razor.css
- ComponentsWebAssembly-CSharp/Client/Shared/NavMenu.razor.css 

####   ComponentsWebAssemblyCSharp/Client/wwwroot/css/app.css
Replace the content by the one from **tests/blazorwasm2-b2c-hosted/Client/wwwroot/css/app.css**

#### ComponentsWebAssembly-CSharp/Client/wwwroot/index.html 
- remove line 11: https://github.com/AzureAD/microsoft-identity-web/blob/1bb75bd2a0ec532ba35f07360b53ed294e915cea/ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Client/wwwroot/index.html#L11
- line 15: replace `<div id="app">Loading...</div>` by `<app>Loading...</app>`

**Comment by jennyf19** [comment]
Included in [0.3.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.3.0-preview).
