### ISSUE TITLE
[Feature Request] Expose requestID or correlation ID for requests made to AAD

### ISSUE THREAD

**Issue by pranavgk** [AzureAD/microsoft-identity-web#494]
**Is your feature request related to a problem? Please describe.**
Currently, we want to investigate an issue with the token received as part of the OBO flow. Since we don't have a request id or correlation id, we are having trouble in identifying the logs of the calls made for obtaining the token when we call `await tokenAcquisition.GetAccessTokenForUserAsync(scopes);`

**Describe the solution you'd like**
A request ID or correlation ID that we could trace back the requests for AAD in Kusto would go a long way in achieving traceability.

**Describe alternatives you've considered**
Any other solution that lets us trace the AAD calls would work too.

**Additional context**
N/A

**Comment by jmprieur** [comment]
Blocked as ASP.NET Core seems to not provide the x-ms-* headers which contain the correlation ID.

**Comment by jmprieur** [comment]
@jennyf19 assigning this to you.
I think that for our partners it's important to have it for GA, along with the extra query parameters

**Comment by jennyf19** [comment]
included in 1.0.0 release
