### ISSUE TITLE
[Bug] Cannot resolve IHttpContextAccessor scoped service in blazorserver web apps that sign-in users

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#496]
**Which version of Microsoft Identity Web are you using?**
0.3.0-preview
With the fixed Blazorserver UI changes

**Where is the issue?**
Blazor server B2C or single org

**Repro**
dotnet new blasorserver2 --auth SingleOrg
configure the app coordinates.

**Expected behavior**
This works

**Actual behavior**
System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHandler Lifetime: Scoped ImplementationType: Microsoft.Identity.Web.MicrosoftIdentityServiceHandler': Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Microsoft.Identity.Web.MicrosoftIdentityConsentAndConditionalAccessHandler'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Identity.Web.MicrosoftIdentityConsentAndConditionalAccessHandler Lifetime: Scoped ImplementationType: Microsoft.Identity.Web.MicrosoftIdentityConsentAndConditionalAccessHandler': Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Microsoft.Identity.Web.MicrosoftIdentityConsentAndConditionalAccessHandler'.)'

**Root cause**
This is because when the initialization of the `MicrosoftIdentityConsentAndConditionalAccessHandler` happens, we are in pre-rendering, and the IHttpContextAccessor is not available.

Note that our test apps call web apis ... which is why we did not catch this

**Possible solution**
Just inject an `IServiceProvider`, and attempt to get the `IHttpContextAccess` as a service. If this returns null, that's ok as the CircuitHandler will provide all the necessary information (there are tests for `IsBlazorServer` everywhere in `MicrosoftIdentityConsentAndConditionalAccessHandler`)

**Comment by jennyf19** [comment]
Included in [0.3.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.3.0-preview).
