### ISSUE TITLE
SameSite browser sniffing code should be extensible

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#5]
Why?
The number of browsers hit by SameSite keeps growing

What?

Provide a way to let app developers add their favorite browser. Add some extensibility here.
Possibly have a community project to propose the last known good browsers?
recommendation from the ASP.NET Core team.

Copied from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/291

**Comment by jennyf19** [comment]
I think this is already complete, based on what is written in the linked issue. thoughts @jmprieur ?

**Comment by jmprieur** [comment]
@jennyf19 : yes I agree. Thanks for checking!
We just need to add a Wiki page, then we can close this issue.
