### ISSUE TITLE
Some thoughts on CallWebApiForUserAsync2<TInput, TOutput>

### ISSUE THREAD

**Issue by NikolaosWakem** [AzureAD/microsoft-identity-web#503]
I have switched some existing code to use IDownstreamWebApi which is great..

In the end I i knocked together the following so the app could access an existing API

```
public static async Task<TOutput> CallWebApiForUserAsync2<TInput, TOutput>(this IDownstreamWebApi downstreamWebApi, string optionsInstanceName, TInput input, Action<DownstreamWebApiOptions> downstreamWebApiOptionsOverride = null, ClaimsPrincipal user = null)
        {
            HttpResponseMessage response = await downstreamWebApi.CallWebApiForUserAsync(
                optionsInstanceName,
                downstreamWebApiOptionsOverride,
                user,
                new StringContent(JsonSerializer.Serialize(input), Encoding.UTF8, "application/json")
                ).ConfigureAwait(false);

            try
            {
                response.EnsureSuccessStatusCode();
            }
            catch
            {
                string error = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

                throw new HttpRequestException($"{(int)response.StatusCode} {response.StatusCode} {error}");
            }

            string content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            if (string.IsNullOrWhiteSpace(content))
                return default;

            return JsonSerializer.Deserialize<TOutput>(content, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        }
```
1) Current CallWebApiForUserAsync only accepts OK status code
2) Current CallWebApiForUserAsync seems to not be able to accept Ok() returned from webapi i.e. blank string
3) Current CallWebApiForUserAsync only accepts TOutput as class so no OK(332)

I imagine IDownstreamWebApi might be still a work in progress?.. be great to hear how best to utilize it.

**Comment by pmaytak** [comment]
@NikolaosWakem thanks for your feedback. The idea behind `DownstreamWebApi` classes was to encapsulate some common code (that accesses protected APIs) for reuse. [Wiki](https://github.com/AzureAD/microsoft-identity-web/wiki/0.3.0-preview#calling-microsoft-graph-and-downstream-apis) has more info. Also [this](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/WebAppCallsWebApiCallsGraph) sample uses these classes like [here](https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsWebApiCallsGraph/Client/Controllers/TodoListController.cs#L22) and [here](https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs#L47).

**Comment by NikolaosWakem** [comment]
All the example code seems to always returns the Todo item e.g. OK(Todo) which isn't how most apis work :-(

**Comment by jennyf19** [comment]
@NikolaosWakem going to reopen, as, based on your analysis, looks like we a bug, and/or overlooked an important scenario.

**Comment by jennyf19** [comment]
@NikolaosWakem I have a [PR](https://github.com/AzureAD/microsoft-identity-web/pull/518) w/your code suggestions, if you want to take a look.

**Comment by NikolaosWakem** [comment]
> Thanks for your suggestion, @NikolaosWakem, and for being an early adopter.
> Would you see value in having other generic methods (for instance CallWebApiForUserAsync?)

Thanks for getting back to me... I just use the following... 

`public static class MicrosoftIdentityWebExtensions
    {
        public static bool IsMsalUiRequiredException(this Exception exception)
        {
            if (exception is Microsoft.Identity.Client.MsalUiRequiredException)
                return true;
            else if (exception.InnerException != null)
                return IsMsalUiRequiredException(exception.InnerException);
            else
                return false;
        }

        public static async Task<TOutput> GetAsync<TOutput>(this IDownstreamWebApi downstreamWebApi, string serviceName, string relativeUri)
        {
            return await downstreamWebApi.CallWebApiForUserAsync2<object, TOutput>(serviceName, null, options =>
            {
                options.RelativePath = relativeUri;
            });
        }

        public static async Task PostAsync(this IDownstreamWebApi downstreamWebApi, string serviceName, string relativeUri)
        {
            await downstreamWebApi.CallWebApiForUserAsync(serviceName, options =>
            {
                options.HttpMethod = HttpMethod.Post;
                options.RelativePath = relativeUri;
            });
        }

        public static async Task<TOutput> PostAsync<TOutput, TInput>(this IDownstreamWebApi downstreamWebApi, string serviceName, string relativeUri, TInput data)
        {
            return await downstreamWebApi.CallWebApiForUserAsync2<TInput, TOutput>(serviceName, data, options =>
            {
                options.HttpMethod = HttpMethod.Post;
                options.RelativePath = relativeUri;
            });
        }

        public static async Task PutAsync<TInput>(this IDownstreamWebApi downstreamWebApi, string serviceName, string relativeUri, TInput data)
        {
            await downstreamWebApi.CallWebApiForUserAsync2<TInput, object>(serviceName, data, options =>
            {
                options.HttpMethod = HttpMethod.Put;
                options.RelativePath = relativeUri;
            });
        }

        public static async Task<TOutput> PutAsync<TOutput, TInput>(this IDownstreamWebApi downstreamWebApi, string serviceName, string relativeUri, TInput data)
        {
            return await downstreamWebApi.CallWebApiForUserAsync2<TInput, TOutput>(serviceName, data, options =>
            {
                options.HttpMethod = HttpMethod.Put;
                options.RelativePath = relativeUri;
            });
        }

        public static async Task<TOutput> CallWebApiForUserAsync2<TInput, TOutput>(this IDownstreamWebApi downstreamWebApi, string optionsInstanceName, TInput input, Action<DownstreamWebApiOptions> downstreamWebApiOptionsOverride = null, ClaimsPrincipal user = null)
        {
            HttpResponseMessage response = await downstreamWebApi.CallWebApiForUserAsync(
                optionsInstanceName,
                downstreamWebApiOptionsOverride,
                user,
                new StringContent(JsonSerializer.Serialize(input), Encoding.UTF8, "application/json")
                ).ConfigureAwait(false);

            string content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
                throw new HttpRequestException($"{(int)response.StatusCode} {response.StatusCode} {content}");

            return !string.IsNullOrWhiteSpace(content) ? JsonSerializer.Deserialize<TOutput>(content, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) : default;
        }
    }`

**Comment by rollandjb** [comment]
It would also be helpful to be able to set up `DefaultRequestHeaders` on the HttpClient, for example, to add an `api key` to every call to the `api`.

**Comment by jmprieur** [comment]
@rollandjb : we were advised against doing it by the ASP.NET Core team (HttpClient is pooled).
Do you think it would be harmless to do it?

**Comment by rollandjb** [comment]
@jmprieur : I am no expert, but according to [.NET microservices - Architecture e-book](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) `HttpMessageHandlers` are pooled, not `HttpClient`. The document encourages the use of `IHttpClientFactory` as provided by Typed Clients, described as

> ... just an HttpClient that's pre-configured ...[with some] ... specific values such as the base server, HTTP headers or time outs.

Of course, `DownstreamWebApi` is just such a typed client.

The document also encourages the use of `DelegatingHandler`s for fine tuning requests on the way out and in. It also has a reference to [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#consumption-patterns) describing the pattern in more detail.

To be able to do this, though, one needs access to the `IHttpClientBuilder` returned from `AddHttpClient`.

In a production app, one would most likely write a dedicated typed client in any respect. However, providing a way to configure and add handlers to `DownstreamWebApi` would, together with the suggestions above, make it more flexible.

Maybe an overload of `AddDownstreamApi` that accepts `Action< IHttpClientBuilder>` would do the trick?

What do you think?

**Comment by jennyf19** [comment]
Included in [0.4.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.4.0-preview). we have another issue, above, tracking more improvements here.

**Comment by parwejp** [comment]
> @jmprieur : I am no expert, but according to [.NET microservices - Architecture e-book](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) `HttpMessageHandlers` are pooled, not `HttpClient`. The document encourages the use of `IHttpClientFactory` as provided by Typed Clients, described as
> 
> > ... just an HttpClient that's pre-configured ...[with some] ... specific values such as the base server, HTTP headers or time outs.
> 
> Of course, `DownstreamWebApi` is just such a typed client.
> 
> The document also encourages the use of `DelegatingHandler`s for fine tuning requests on the way out and in. It also has a reference to [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#consumption-patterns) describing the pattern in more detail.
> 
> To be able to do this, though, one needs access to the `IHttpClientBuilder` returned from `AddHttpClient`.
> 
> In a production app, one would most likely write a dedicated typed client in any respect. However, providing a way to configure and add handlers to `DownstreamWebApi` would, together with the suggestions above, make it more flexible.
> 
> Maybe an overload of `AddDownstreamApi` that accepts `Action<IHttpClientBuilder>` would do the trick?
> 
> What do you think?

@jennyf19 : I am not able to find out how to send request headers while using get requests on iDownStreamWebAPI. I recently got an error while calling MS graph api to add "ConsistencyLevel = eventual" header. 
[Microsoft Graph advanced queries Header](https://developer.microsoft.com/en-us/identity/blogs/microsoft-graph-advanced-queries-for-directory-objects-are-now-generally-available/ ) 
Have switched to ITokenAquisition implementation for now but would be nice to use IDownStreamWebAPI for it. As @rollandjb mentioned it would be possible to set request headers with pooled HttpClient with proper isolation. I am no expert but creating HttpRequestMessage could be quick fix. 
If it is implemented already, could you please be kind enough to point me out to documentation?

Many Thanks

**Comment by jmprieur** [comment]
Thanks @parwejp these are fair points.
Would you mind opening a new issue with this?
