### ISSUE TITLE
[Documentation] change changelog extension to .md

### ISSUE THREAD

**Issue by johnayoub** [AzureAD/microsoft-identity-web#508]
### Documentation related to component
changelog

### Please check all that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
changelog is a markdown document but with a .txt extension and therefore doesn't render properly on github

**Comment by jennyf19** [comment]
thanks @johnayoub. most of our teams use the same format, so we'll check and get back to you.

**Comment by jennyf19** [comment]
Included in [0.4.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.4.0-preview)
