### ISSUE TITLE
[Feature Request] In the Blazorwasm templates hosted, show how to call graph and a downstream api

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#509]
**Is your feature request related to a problem? Please describe.**
The Blasorwasm template has all the initialization to call a downstream API, or Graph, but we did not expose pages that actually call them

**Comment by jmprieur** [comment]
Work to be done (in the Client):
- in the Pages sub folder, add the CallWebApi.razor and ShowProfile.razor pages from https://github.com/AzureAD/microsoft-identity-web/tree/master/ProjectTemplates/templates/BlazorServerWeb-CSharp/Pages
- in the Shared sub folder, add the NavMenu.* pages from https://github.com/AzureAD/microsoft-identity-web/tree/master/ProjectTemplates/templates/BlazorServerWeb-CSharp/Shared
- in the template.json file, add the conditional inclusion of the pages: https://github.com/AzureAD/microsoft-identity-web/blob/5d3c277ed53e060b91f0c1c36d041e09e6055388/ProjectTemplates/templates/BlazorServerWeb-CSharp/.template.config/template.json#L131-L173

**Comment by jennyf19** [comment]
Included in [1.1.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.1.0).
