### ISSUE TITLE
[Bug] Adding reference to Blazor WebAssembly .net 5.0 template project causes build error

### ISSUE THREAD

**Issue by dakahler** [AzureAD/microsoft-identity-web#513]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 0.3.1-preview

**Where is the issue?**

Build error: error NETSDK1073: The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized

**Is this a new or an existing app?**
New app

**Repro**

- Create new Blazor WebAssembly hosted project with the project template in Visual Studio 16.8 Preview 2. Select .net 5.0 target.
- Add a reference to the Client project: <PackageReference Include="Microsoft.Identity.Web" Version="0.3.1-preview" />
- Build

**Expected behavior**
Build succeeds

**Actual behavior**
Compile error: C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(318,5): error NETSDK1073: The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized

**Comment by jmprieur** [comment]
@dakahler : did you self-resolve your issue?
Do you want to share what the problem was? is there anything we could have done to avoid your issue in the first place?

**Comment by dakahler** [comment]
I initially thought I had mistakenly attributed this issue to the Identity package, which is why I closed it. More investigation seemed to indicate it was actually the fault of the Radzen.Blazor package.

However, even further investigation indicates that the issue only appears when both of these packages are included. Whether this is a problem with Identity, Radzen, or the .net 5 toolchain. I'm really not sure.

**Comment by jmprieur** [comment]
@dakahler : how is it related to MIcrosoft.Identity.Web? I'm not familiar with Radzen.Blazor.

**Comment by dakahler** [comment]
It appears to be an interaction between Microsoft.Identity.Web and Radzen.Blazor. I can't say what the root cause is without a deeper investigation.

**Comment by jmprieur** [comment]
This should now be solved.
Please reopen if you disagree @dakahler
