### ISSUE TITLE
[Checklist] GA Criteria - Quick start - ASP.NET Core Web App that signs-in users (from template)

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#520]
Running sample should not be more than few steps.

The quickstart is https://docs.microsoft.com/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp
Also tacked as https://identitydivision.visualstudio.com/Technical%20Content/_workitems/edit/1128821

**Comment by jmprieur** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/128358

**Comment by jmprieur** [comment]
@mmacy : in progress.

**Comment by jmprieur** [comment]
blocked waiting for review

**Comment by mmacy** [comment]
@jmprieur Thanks Jean-Marc, will tackle this tomorrow first thing in the morning.

**Comment by mmacy** [comment]
@jmprieur The updated PR I created from your PR is now ready for your review:

https://github.com/MicrosoftDocs/azure-docs-pr/pull/129127

**Comment by jmprieur** [comment]
Reviewed by Marsh.

**Comment by mmacy** [comment]
@jmprieur The updated doc is now live:

https://docs.microsoft.com/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp

**Comment by jmprieur** [comment]
Live: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp
