### ISSUE TITLE
[Checklist] GA Criteria - Quick start - ASP.NET Core Protected Web API (from template)

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#522]
Running sample should not be more than few steps.

**Comment by jmprieur** [comment]
blocked waiting for review

**Comment by mmacy** [comment]
I've signed off on the PR:

https://github.com/MicrosoftDocs/azure-docs-pr/pull/130150

**Comment by jmprieur** [comment]
Live: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-web-api
