### ISSUE TITLE
[Checklist] GA Criteria - Quick start - Web app signs-in user and calls web APIs scenario landing page (using GraphService and/or IDownstream API)

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#523]
Running sample should not be more than few steps.

**Comment by jmprieur** [comment]
Live:https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-configuration?tabs=aspnetcore#summary
