### ISSUE TITLE
[Checklist] GA Criteria - Protected web APIs that calls downstream APIs scenario articles (using GraphService and/or IDownstream API)

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#524]
Running sample should not be more than few steps.

**Comment by jmprieur** [comment]
PR is https://github.com/MicrosoftDocs/azure-docs-pr/pull/130706
@mmacy @jennyf19

**Comment by jmprieur** [comment]
Live: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-app-configuration?tabs=aspnetcore#option-1-call-microsoft-graph
