### ISSUE TITLE
[Feature Request] Allow multiple scopes from configuration for AuthorizeForScopesAttribute

### ISSUE THREAD

**Issue by jamiemccrindle** [AzureAD/microsoft-identity-web#54]
**Is your feature request related to a problem? Please describe.**

AuthorizeForScopesAttribute does not support multiple scopes from configuration e.g. it's pretty common to want some custom app scope as well as Group.Member.Read

**Describe the solution you'd like**

Have a way to pull multiple scopes from configuration e.g. this could be done by checking if ScopeKeySection has children or introducing a new property called ScopesKeySection.

**Describe alternatives you've considered**

I've had to copy AuthorizeForScopesAttribute into my own code and make the change.

**Additional context**

Thanks for this library, it's awesome.

**Comment by jmprieur** [comment]
This is now fixed. The scopes are space delimited.
Documented in This is by design, and handling the exception is documented in https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access
