### ISSUE TITLE
Update nuget release notes to point to changelog.md instead of changelog.txt.

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-identity-web#541]
See under release notes for details: https://www.nuget.org/packages/Microsoft.Identity.Web/0.3.1-preview

**Comment by jmprieur** [comment]
Thanks for raising, @henrik-me 
this was fixed already in 0.4.1, (point to releases), but not yet published (hence the trick of having changelog.txt 'redirecting' the developer to changelog.md

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/92080977-abcd0580-edc2-11ea-99fe-730e8a8550e5.png)

**Comment by jmprieur** [comment]
Assigning to @jennyf19  as it was done when fixing #508 
part of https://github.com/AzureAD/microsoft-identity-web/pull/519/files

**Comment by jennyf19** [comment]
Is there more work to be done here?

**Comment by jennyf19** [comment]
Included in [0.4.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.4.0-preview)
