### ISSUE TITLE
[Feature Request] Support token acquisition for multiple applications 

### ISSUE THREAD

**Issue by stvonolf** [AzureAD/microsoft-identity-web#545]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to configure a single application - example:

`"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "7f58f645-c190-4ce5-9de4-e2b7acd2a6ab",
    "ClientId": "a4c2469b-cf84-4145-8f5f-cb7bacf814bc",
  }`

**Describe the solution you'd like**
We would like to use multiple applications to acquire tokens for different services (e.g., CDS, Flow):
`"CDSApp": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "7f58f645-c190-4ce5-9de4-e2b7acd2a6ab",
    "ClientId": "a4c2469b-cf84-4145-8f5f-cb7bacf814bc",
  },`

`"FlowApp": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "7f58f645-c190-4ce5-9de4-e2b7acd2a6ab",
    "ClientId": "52494365-4ef7-4789-8d38-84075585653a",
  }`

An `ITokenAcquisitionFactory` could be used to obtain the correct `ITokenAcquisition` service: `tokenAcquisitionFactory.GetTokenAcquisition("CDSApp");`

**Describe alternatives you've considered**
Use a single application registration for all dependencies (e.g., CDS, Flow).

**Additional context**
n/a

**Comment by stvonolf** [comment]
Does that make sense or would the recommendation be to create a single app registration per WebApp?

**Comment by jmprieur** [comment]
@stvonolf : what is your scenario? why would you want to have several AppId for the same Web app / Web API? that's not the model that we recommend. 
You can have several web apps (code) that uses the same client ID, but the contrary (have several AppId in the same web app code), although possible if you use MSAL.NET directly, is not something we've plan to support with MIcrosoft.Identity.Web.

Proposing to see if many people are interested in this feature, but for the moment, I would not recommend taking it.

**Comment by jmprieur** [comment]
@stvonolf : I'm however curious about your scenario. and would like to understand it better (in case we miss something)
