### ISSUE TITLE
[Bug] Signing Out redirects to 404 -- https://<host>/Account/SignOut?page=%2FAccount%2FSignedOut

### ISSUE THREAD

**Issue by mjnorman** [AzureAD/microsoft-identity-web#546]
**Which version of Microsoft Identity Web are you using?**
0.3.1-preview

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)
Signing Out Users

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of Microsoft Identity Web.

**Repro**

Relevant section of Startup.cs:
```csharp
            services.AddMicrosoftIdentityWebAppAuthentication(Configuration);
...

            ).AddMicrosoftIdentityUI()
```
_LoginPartial
```csharp
<a class="nav-link text-dark" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut">Sign out</a>
```

**Expected behavior**
I would have expected a redirect to the SignedOut page within Microsoft.Identity.Web.UI package.

**Actual behavior**
Redirects to a 404 page `https://<host>/Account/SignOut?page=%2FAccount%2FSignedOut`

With this present in the console--
`[11:50:11 DBG] No candidates found for the request path '/Account/SignOut'`

**Comment by mjnorman** [comment]
Comparing my code to the sample, I was missing the `MapRazorPages()` command in the `UseEndpoints` block.  This is mentioned in the migration from 2.2 to 3.0 guide, and I apparently missed it.  Adding this, code now works as expected. Thanks for your work on this library!

```csharp
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });
```

Closing issue.

**Comment by HunteRoi** [comment]
Good afternoon @mjnorman ! I see you closed this issue on your own. Does it mean you found why you fell on a 404? If so, could you explain? I'm facing the same issue and I'm hitting my head on a rock at the moment..

Thanks for your time!

**Comment by mjnorman** [comment]
@HunteRoi yes, take a look at my closure comment, was just missing the MapRazorPages.
