### ISSUE TITLE
How to configure Microsoft.Identity.Web when Web App and Web API exist in the same project.

### ISSUE THREAD

**Issue by levi106** [AzureAD/microsoft-identity-web#547]
I looked at the [document](https://github.com/AzureAD/microsoft-identity-web/wiki/0.3.0-preview) but couldn't figure out how to configure the following project.

- The project is an ASP.NET Core MVC project with API controller.
- Both Web App and Web API call backend API (e.g. Microsoft Graph)

Do I need to call AddMicrosoftIdentityWebAppAuthentication and also AddMicrosoftIdentityWebApiAuthentication?

**Comment by jmprieur** [comment]
yes @levi106 : you need to call both.

**Comment by levi106** [comment]
Does the call order matter? Calling AddMicrosoftIdentityWebApiAuthentication after AddMicrosoftIdentityWebAppAuthentication resulted in a 401 error.

```
services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
           .EnableTokenAcquisitionToCallDownstreamApi()
           .AddInMemoryTokenCaches();
services.AddMicrosoftIdentityWebApiAuthentication(Configuration)
           .EnableTokenAcquisitionToCallDownstreamApi()
           .AddInMemoryTokenCaches();
```

![image](https://user-images.githubusercontent.com/16788901/92246414-ac6bb600-ef00-11ea-91cd-f42122297c5b.png)

**Comment by jmprieur** [comment]
I does not but I think that you probably need to use the non-contracted from and decide of which scheme (OpenIdConnect or JWT has the priority), and specify which scheme to use for which page / controller action.

See details in https://github.com/AzureAD/microsoft-identity-web/wiki/adding-call-api-to-web-app

**Comment by levi106** [comment]
I tried to specify the scheme name for the Web API, but I got the same result.

```
            services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
                    .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddInMemoryTokenCaches();

            services.AddMicrosoftIdentityWebApiAuthentication(Configuration, jwtBearerScheme:"Bearer2")
                    .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddInMemoryTokenCaches();
```

**Comment by jmprieur** [comment]
@levi106 did you decorate the [Authorize] attribute for your HTML pages (Web app) and your api pages (web api) with the scheme ? did you read this article? [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/aspnet/core/security/authorization/limitingidentitybyscheme)

**Comment by jmprieur** [comment]
See also https://github.com/AzureAD/microsoft-identity-web/wiki/Mixing-web-app-and-web-api-in-the-same-ASP.NET-core-app
Closing as answered
