### ISSUE TITLE
'NonController' and //.AddMicrosoftIdentityUI() should be commented out for custom AccountController

### ISSUE THREAD

**Issue by UM001** [AzureAD/microsoft-identity-web#550]
### Documentation related to component
I do not like the markup of the SignedOut.html page. So I want to customize the controller.
It took me some time to understand that I needed to comment out the 'noncontroller' on the accountcontroller code and the 'AddMicrosoftIdentityUI' as well.

'NonController' and //.AddMicrosoftIdentityUI() should be commented out for custom AccountController

 /// <summary>
    /// Controller used in web apps to manage accounts.
    /// </summary>
    //[NonController]
    [AllowAnonymous]
    [Area("MicrosoftIdentity")]
    [Route("[area]/[controller]/[action]")]

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x ] documentation needs clarification
- [ ] error(s) in the example
- [ x] needs an example

### Description of the issue
Please contact me if not clear.

**Comment by jmprieur** [comment]
@UM001 : Wouldn't it be an option to use this technics: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#override-views-partial-views-and-pages
(without removing the controller, just overriding the pages?

**Comment by jennyf19** [comment]
updated wiki [here](https://github.com/AzureAD/microsoft-identity-web/wiki/customization#ui-customization)
