### ISSUE TITLE
[Bug] Blazor server multi-tenant authentication to Azure AD for use with Graph API

### ISSUE THREAD

**Issue by EdAlexander** [AzureAD/microsoft-identity-web#557]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 0.3.1-preview

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
Testing multi-tenant server side blazor in order to validate configuration before applying pattern to new server side blazor app already working in single tenant.. Adding graph integration, therefore need ability to get token for bearer in order to do that.. (send email, etc).

**Repro**

1) run BlazoreGraphApi sample, confirm function as single tenant.
2) mark registration as multi-tenant in azure ad applications
3) login is "primary/original" tenant user, works fine
4) login with user from some other tenant, (note login.microsoftonline background shown and example account align with original tenant... not generic multi-tenant background graphis)
    a) credentials are authenticated
    b) user then presented with request for more information with only option being "Mobile app".  user not prompted to accept scopes

**Expected behavior** (Desired behavior)
The external user being tested has no multi-factor requirements configured in AzureAD... Would like for user to be prompted for scopes, accept and be done...

**Actual behavior**
All third part users are blocked from app with mobile app requirement.... 

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

![image](https://user-images.githubusercontent.com/13755026/92491854-b91e3180-f1c0-11ea-8f2e-601d25c075d8.png)

**Comment by jennyf19** [comment]
@EdAlexander do you have a link to the blazor server sample you refer to above?

**Comment by jmprieur** [comment]
@EdAlexander 
I just tried creating a multi-tenant blazor app:

1. ```shell
   dotnet new blazorserver2 --auth MultiOrg --calls-graph
   ```

2. add the clientID and ClientSecret in the appsettings.json

3. dotnet run --framework netcoreapp31

4. Navigate to https://localhost:5001

This worked very well, and I was able to sign-in and see the profile picture for any tenant.


So I think that you are trying to:
1. either add an app in a tenant where the tenant admin has set conditional access policies to force 2FA
2. or you are trying to sign-in a user from a tenant where the tenant admin has set conditional access policies to force 2FA

It could be 1. applying to only guest users. you'd have to see with your tenant admin.

In any case this is not an issue with Microsoft.Identity.Web
Proposing to close this issue as external. Feel free to reopen if you disagree.

**Comment by jmprieur** [comment]
cc: @jennyf19

**Comment by EdAlexander** [comment]
https://github.com/wmgdev/BlazorGraphApi is the sample i am running.  

I am not using a tenant with multi-factor or conditional access enabled.  

The template mentioned by @jmprieur does run and work fine, but does not use microsoft.identity.web and i don't see that it returns the bearer token for use with graph (I had tried that sample before and was not able to access the graph using the graph api).

**Comment by jmprieur** [comment]
What do you mean @EdAlexander it does not use Microsoft.Identity.Web ? it's a Microsoft.Identity.Web template: 
See https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template#use-the-web-app-blazor-server-template

**Comment by EdAlexander** [comment]
I built the sample from the visual studio blazor server template, choosing multi-tenant and graph and found no package (nuget) for microsoft.identity.web installed.  To be honest i don't know where that template is came from, but it doesn't seem to do the trick.

I see the templates in the identity.web project now and will try blazorserver2 from there (and compare to what i was using in my application)... 

Appreciate the help in locating a good pattern for my needs.  I am trasitioning from UWP for custom business apps to blazor and security is key.

Thanks!!!

**Comment by EdAlexander** [comment]
having trouble picking up blazorserver2 template...
PS C:\Users\ed.alexander\source\repos> **dotnet new --install "Microsoft.Identity.Web.ProjectTemplates"**
  Determining projects to restore...
  Restored C:\Users\ed.alexander\.templateengine\dotnetcli\v3.1.402\scratch\restore.csproj (in 1.39 sec).


Templates                                                                      Short Name               Language          Tags
---------------------------------------------------------------------------------------------------------------------------------------------------------------

Blazor Server App                                                              blazorserver             [C#]              Web/Blazor
Blazor WebAssembly App                                                         blazorwasm               [C#]              Web/Blazor/WebAssembly


PS C:\Users\ed.alexander\source\repos> dotnet new blazorserver2 --auth MultiOrg --calls-graph
**Couldn't find an installed template that matches the input, searching online for one that does...**

![image](https://user-images.githubusercontent.com/13755026/92598911-7ff4c880-f277-11ea-9779-2378543a78d3.png)

**Comment by jmprieur** [comment]
@EdAlexander 
Just download the https://www.nuget.org/packages/Microsoft.Identity.Web.ProjectTemplates/0.3.1-preview NuGet package and save it somewhere on your disk (let's say the folder path is `yourSavedlocation`)

then run the following command to install the templates:

```Shell
dotnet new -i yourSavedlocation\Microsoft.Identity.Web.ProjectTemplates.0.3.1-preview.nupkg
```

and you'll be set. This is explained in https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template, btw

**Comment by EdAlexander** [comment]
Thanks for the link to documentation...  looking forward to v1.0 :)

**Comment by EdAlexander** [comment]
found my original issue (now resolved)... sometimes the simple things are the hardest.  I changed appsettings.json TenantId to "common" and all is well....
