### ISSUE TITLE
[Documentation] Ensure API reference documentation is published

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#56]
### Documentation Related To Component:
Ensure the NuGet package is picked-up by docs.ms and the reference documentation is generated

### Please check those that apply

- [ ] typo
- [ x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Comment by jmprieur** [comment]
@mmacy : the NuGet packages are now published: 
- https://www.nuget.org/packages/Microsoft.Identity.Web/0.1.0-preview
- https://www.nuget.org/packages/Microsoft.Identity.Web.UI/0.1.0-preview

When can we schedule the request to generate the reference documentation for these?

cc: @jennyf19

**Comment by mmacy** [comment]
@jmprieur Anytime, though I believe we had planned to do an XML doc pass prior to doing so. I guess by this message, you're ready for that now? ;)

**Comment by jennyf19** [comment]
@mmacy yes, we are ready.

**Comment by jmprieur** [comment]
The XML comments were not in the NuGet pacakge. This should be fixed by #137

**Comment by jmprieur** [comment]
@mmacy : we should release a new version of the NuGet package soon (Friday?) which would contain the XML comments file.
