### ISSUE TITLE
[Documentation] - Question about wiki page statement

### ISSUE THREAD

**Issue by mderriey** [AzureAD/microsoft-identity-web#560]
### Documentation related to component

Wiki page "Why use Microsoft.Identity.Web?"

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

In the [Why use Microsoft.Identity.Web?](https://github.com/AzureAD/microsoft-identity-web/wiki/Microsoft-Identity-Web-basics) wiki page, it states (emphasis mine):

> Today, without Microsoft Identity Web, when doing `dotnet new --auth` and creating a Web App from an ASP.NET core template, the application is targeting the Azure AD v1.0 endpoint, which means sign-in with a work or school account is the only option for customers. **There is also no issuer validation happening when the token is returned.**
> The Web Apps and Web APIs that are created do not call downstream Web APIs, if a developer wanted to call a downstream Web API, they would need to leverage MSAL.

My understanding is that both the OpenID Connect and JWT Bearer authentication providers in ASP.NET Core do perform issuer validation, most of the time based on the value that is retrieved from the OpenID Connect metadata document.

Could you please elaborate on that statement?

**Comment by jmprieur** [comment]
Thanks for the heads-up @mderriey. This sentence was obviously wrong. I fixed it by "There is also no issuer validation happening in multi-tenant applications."
