### ISSUE TITLE
[Feature Request] To Pass extraQueryParameters using Microsoft.Identity.Web

### ISSUE THREAD

**Issue by Shama-K** [AzureAD/microsoft-identity-web#561]
We can not pass extra query parameters in query string, as **WithExtraQueryParameters** of [AcquireTokenSilentParameterBuilder Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.acquiretokensilentparameterbuilder?view=azure-dotnet) is not supported by Microsoft.Identity.Web.

**Comment by jmprieur** [comment]
See also https://github.com/AzureAD/microsoft-identity-web/issues/532

**Comment by jennyf19** [comment]
Making a note to self here that this may not work as we expect. We might have to do some fixes in MSAL .NET first
cc: @jmprieur

**Comment by jmprieur** [comment]
@Shama-K, the fix is available in Microsoft.Identity.Web 1.0.0
