### ISSUE TITLE
wiki web-app-template 0.4.0-preview

### ISSUE THREAD

**Issue by damienbod** [AzureAD/microsoft-identity-web#575]
### Documentation related to component

https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template

### Description of the issue

Some links need to be updated to 0.4.0

Also maybe a Note about how to update a template would be useful. First uninstall then install (-u)

**Comment by jmprieur** [comment]
Thanks for the heads-up @damienbod 
This is fixed.
