### ISSUE TITLE
Needs help on Securing a web app

### ISSUE THREAD

**Issue by dsjijo** [AzureAD/microsoft-identity-web#58]
Hi ,

This is not bug , but needs a help on how to do this feature.
I have a web app (Flask ) A created by following this tutorial. [Link](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python?tabs=bash) 
And I have another website B hosted in another host provider and trying to access above api from B.
I added CORS in A but want to impliment an oAuth2 in azure . how to do that? 
I am looking a scenario where credentials prompt is not shown . like a deamon app it should be able to get the token.
I am new to all these. Hope you got what am i looking into.

**Comment by jmprieur** [comment]
@dsjijo : this repo is for .NET
we have a request for Python here: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/147

**Comment by dsjijo** [comment]
Hi @jmprieur
Thanks for the reply . I have checked the same and found that it would be in the enhancement plan. BTW I have found another repository doing the same [Link](https://github.com/Azure-Samples/ms-identity-python-webapi-azurefunctions/tree/master/Function/secureFlaskApp) . 

The token I was able to get through following this [link](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret) and restructed my app (API_AUDIENCE  was changed to Application ID URI ) from the   [secureFlaskApp](https://github.com/Azure-Samples/ms-identity-python-webapi-azurefunctions/tree/master/Function/secureFlaskApp). 

Thanks for the help.
