### ISSUE TITLE
CORS error Azure B2C

### ISSUE THREAD

**Issue by MellVgaEcu** [AzureAD/microsoft-identity-web#581]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
**Microsoft.AspNetCore.Authentication.AzureADB2C.U**

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hi everyone!
I developed an application that works with Azure B2C and I have my work flow available for profile editing, when I want to edit a data , this redirect to index but with a cors error.
I'wll attach the issue description. Please, can anyone help me with this?

**Request at 'https://xxxxx.b2clogin.com/xxxxxx.onmicrosoft.com/b2c_1_signup…kveCtN0Bnp1GpsilHJRtFb&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0' (redirected from 'https://xxxxx.azurewebsites.net/xxxxxx/xxxxxxx') from origin 'https://xxxxxxx.azurewebsites.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

![error (1)](https://user-images.githubusercontent.com/71160286/92984280-b9435900-f46e-11ea-91e4-fbd390704b19.PNG)

My app is already registrated in the azure portal

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by MellVgaEcu** [comment]
@jmckennon I got it XD
![image](https://user-images.githubusercontent.com/71160286/93271319-92d83300-f778-11ea-9535-370fe08297a3.png)
I updated the packages you told me and then I re-write this code in **Startup.cs**
![image](https://user-images.githubusercontent.com/71160286/93271515-12660200-f779-11ea-8eb1-764a616271f7.png)

thank you very much ...

**Comment by jennyf19** [comment]
@MellVgaEcu are you getting the same error with the updated package?

**Comment by MellVgaEcu** [comment]
@jennyf19  No, After updating the packages,my issue was resolved.

**Comment by jennyf19** [comment]
@MellVgaEcu awesome! Thanks for letting us know so quickly.
