### ISSUE TITLE
[Feature Request] Add a ASP.NET middleware that ensures user has an access token in the cache before calling controller actions.

### ISSUE THREAD

**Issue by tigertop** [AzureAD/microsoft-identity-web#59]
The current approach for refreshing an access token is using the AuthorizeForScopes attribute on controller actions. We faced some issues while using this approach. Consider following controller action. ``DoSomethingAndSendNotification`` method updates the state in the database and then sends a notification via a call to Microsoft Graph API in the ``SendNotification`` function.
```
[AuthorizeForScopes(Scopes = new[] {Constants.ScopeUserRead})]
        public async Task<IActionResult> DoSomethingAndSendNotification(string username)
        {
            var orderId = _orderService.RegisterOrder(username);

            var accessToken =
                await tokenAcquisition.GetAccessTokenForUserAsync(new[] {Constants.ScopeUserRead});

            _notificationService.SendNotification(username, accessToken);
            return View();
        }
```
The first issue we faced was with token caching and app restarts. We used in memory token caching. So users authenticated normally with app and got their token added to the cache. Then when we did an app restart (due to updates) we come to the situation when user's browser has a valid authentication cookie but the backed cache doesn't have an access token in the cache. So when the user presses a button and calls the ``DoSomethingAndSendNotification`` method again an exception will be raised from ``GetAccessTokenForUserAsync`` method. ``AuthorizeForScopes`` attribute handles the exception and redirects the user to AAD for authentication flow. When the user authenticates she is redirected back and the ``DoSomethingAndSendNotification`` method is re-executed. Problem in this case is that is this sample ``_orderService.RegisterOrder(username);`` method is called again and double order will be registered for the user. 

To solve this we either needed to design orderService with a re-entrancy logic or we need to ensure that before the controller's action is called we somehow ensure that user has an access token in the cache. For that we implemented this ASP.NET middleware:
```
public class TokenSetterMiddleware
    {
        private readonly RequestDelegate _next;
        private ConfidentialClientApplicationOptions _applicationOptions;
        private readonly AzureADOptions _azureAdOptions;
        private readonly TokenSetterMiddlewareOptions _options;
        private readonly IMsalTokenCacheProvider _tokenCacheProvider;

        public TokenSetterMiddleware(RequestDelegate next, IConfiguration configuration, IOptions<TokenSetterMiddlewareOptions> options,
            IMsalTokenCacheProvider tokenCacheProvider)
        {
            _next = next;
            _options = options.Value;
            _tokenCacheProvider = tokenCacheProvider;
            _azureAdOptions = new AzureADOptions();
            configuration.Bind("AzureAD", _azureAdOptions);
            _applicationOptions = new ConfidentialClientApplicationOptions();
            configuration.Bind("AzureAD", _applicationOptions);
        }

        public async Task InvokeAsync(HttpContext context)
        {
            if (context.User.Identity.IsAuthenticated &&
                (context.Request.Path != _azureAdOptions.CallbackPath
                || context.Response.StatusCode != 302))
            { 
                var app = BuildConfidentialClientApplication(context, context.User);
                var user = await app.GetAccountAsync(context.User.GetMsalAccountId());

                if (user == null)
                {
                    //Workaround for Guest Users
                    var loginHint = context.User.GetLoginHint();
                    var accounts = await app.GetAccountsAsync();
                    user = accounts.FirstOrDefault(a => a.Username == loginHint);

                    if (user == null)
                    {
                        var properties = BuildAuthenticationPropertiesForIncrementalConsent(_options.Scopes, context);
                        await context.ChallengeAsync(properties);
                        return;
                    }
                    
                }
            }
            await _next(context);
        }

        private IConfidentialClientApplication BuildConfidentialClientApplication(HttpContext httpContext, ClaimsPrincipal claimsPrincipal)
        {
            var request = httpContext.Request;
            var azureAdOptions = _azureAdOptions;
            var applicationOptions = _applicationOptions;
            string currentUri = UriHelper.BuildAbsolute(
                request.Scheme,
                request.Host,
                request.PathBase,
                azureAdOptions.CallbackPath ?? string.Empty);

            string authority = $"{applicationOptions.Instance}{applicationOptions.TenantId}/";

            var app = ConfidentialClientApplicationBuilder
                .CreateWithApplicationOptions(applicationOptions)
                .WithRedirectUri(currentUri)
                .WithAuthority(authority)
                .Build();

            // Initialize token cache providers
            _tokenCacheProvider?.InitializeAsync(app.AppTokenCache);
            _tokenCacheProvider?.InitializeAsync(app.UserTokenCache);

            return app;
        }

        private AuthenticationProperties BuildAuthenticationPropertiesForIncrementalConsent(
            string[] scopes, HttpContext context)
        {
            var properties = new AuthenticationProperties();

            // Set the scopes, including the scopes that ADAL.NET / MASL.NET need for the Token cache
            string[] additionalBuildInScopes =
                {OidcConstants.ScopeOpenId, OidcConstants.ScopeOfflineAccess, OidcConstants.ScopeProfile};
            properties.SetParameter<ICollection<string>>(OpenIdConnectParameterNames.Scope,
                                                         scopes.Union(additionalBuildInScopes).ToList());

            // Attempts to set the login_hint to avoid the logged-in user to be presented with an account selection dialog
            var loginHint = context.User.GetLoginHint();
            if (!string.IsNullOrWhiteSpace(loginHint))
            {
                properties.SetParameter(OpenIdConnectParameterNames.LoginHint, loginHint);

                var domainHint = context.User.GetDomainHint();
                properties.SetParameter(OpenIdConnectParameterNames.DomainHint, domainHint);
            }

            return properties;
        }
    }
```
(Sorry for the code quality. Didn't have time for refactoring.) 
I am curious what you think about this approach? Is this an acceptable solutions for product? Are that alternatives to the AuthorizeForScopes attribute?
Thanks.

**Comment by jmprieur** [comment]
@tigertop : this is an interesting approach
how do you set the TokenSetterMiddlewareOptions  ? do you have an example of code?

How would you do if several controller actions require different scopes, like in the following sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/3-WebApp-multi-APIs/Controllers/HomeController.cs ?

**Comment by tigertop** [comment]
Here is the gist with the codes. This currently works quite well for us.
https://gist.github.com/tigertop/fc1dd9ac77a15e80ef6b1a97d398c8ca

Now the implementation uses only scopes read from the configuration. I was thinking that I can fetch the scopes right from the attribute if present on the action method. This can be achieved in two ways. First one is to place the TokenSetterMiddleware after the MVC so I can fetch the routing data and then using a little bit of reflection I would be able to get the AuthorizeForScopes attribute and get scopes from that.
Other option is to build an ASP.NET authorization or action filter that checks for the token in cache and in case or re-authentication need fetches the scopes from the AuthorizeForScopes attribute (if placed on the action) or the configuration.

Not sure in which direction is right. Could use an advice.

**Comment by tigertop** [comment]
@jmprieur do you have ideas on a better way if implementing this approach?

**Comment by jennyf19** [comment]
@tigertop If you provide all the scopes upfront in `EnableTokenAcquisition`, then you will have the same effect.

Closing as won't fix.
