### ISSUE TITLE
[Feature Request] Leverage the ASP.NET Core IHttpClientFactory

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#6]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Why?

Architectural guidance recommand to [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests).

ASP.NET Core [IHttpClientFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests) manages the pooling and lifetime of underlying HttpClientMessageHandler instances, which avoids port exhaustion and common DNS (Domain Name System) problems that occur when manually managing HttpClient lifetimes.
It also allows for configurable logging experience (via ILogger) for all requests sent through clients created by the factory.

Today, when instanciating a IConfidentialClientApplication in https://github.com/AzureAD/microsoft-identity-web/blob/72939218c85f65d42e7d5989e5dffcf0cdee6000/src/Microsoft.Identity.Web/TokenAcquisition.cs#L348-L366
we leave it to MSAL.NET to manage the HttpClient

### Possible design

For the moment, we could have the following design

1. Add a new parameter `httpClientFactory` of type `IHttpClientFactory` in the constructor of `TokenAcquisition`: https://github.com/AzureAD/microsoft-identity-web/blob/72939218c85f65d42e7d5989e5dffcf0cdee6000/src/Microsoft.Identity.Web/TokenAcquisition.cs#L46-L51 so that an HttpClientFactor can be injected by dependency injection. Also add a corresponding property to `TokenAcquisition`
2. Add a new internal class (for instance `MsalAspNetCoreHttpClientFactory`) implementing [IMsalHttpClientFactory](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/HttpClient) and having a constructor with an ASP.NET Core `IHttpClientFactory`, and which `CreateClient()` method would just delegate to `IHttpClientFactory`
3. When building MSAL.NET confidential client application, use the `.WithHttpClientFactory(httpClientFactory)`  modifyer and instanciate a `MsalAspNetCoreHttpClientFactory` from the  `httpClientFactory` property
4. In `AddWebAppCallsWebApi` and  `AddProtectedWebApiCallsWebApi`, add a service: `services.AddHttpClient();`

### Possible future improvement

I don't think we need to use [Named clients](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#named-clients) ?

Copied from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/267

**Comment by jmprieur** [comment]
@jennyf19 : this one would be useful. We might want to discuss with @henrik-me and @bgavrilMS first if that's what we want to do (knowing it was recommended by Chris and Barry)

**Comment by jmprieur** [comment]
@bgavrilMS @pmaytak you might want to review the design discussed with @jennyf19 yesterday ?

**Comment by bgavrilMS** [comment]
The proposal looks fine to me. 

I don't have enough context to understand the lifetime of these objects, so please ensure that only 1 factory is ever used.

**Comment by jmprieur** [comment]
I think that's the principle in ASP.NET Core. Thanks @bgavrilMS

**Comment by pmaytak** [comment]
Strategy makes sense to me so far and seems useful. I'd have to look closer through the docs to give a more informed opinion.

**Comment by jmprieur** [comment]
Fixed in Microsoft.Identity.Web 0.1.2-preview
