### ISSUE TITLE
[Question] How to handle the MsalUiRequiredException for incremental consent with AJAX calls

### ISSUE THREAD

**Issue by creativebrother** [AzureAD/microsoft-identity-web#603]
**Which version of Microsoft Identity Web are you using?**
 v0.4.0-preview
**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**

```csharp
in startup.cs configureservices:
string[] initialScopes = Configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' ');
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                .AddDistributedTokenCaches();

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();
in appsettings.json:
  "DownstreamApi": {
    /*
     'Scopes' contains space separated scopes of the Web API you want to call. This can be:
      - a scope for a V2 application (for instance api:b3682cc7-8b30-4bd2-aaba-080c6bf0fd31/access_as_user)
      - a scope corresponding to a V1 application (for instance <App ID URI>/.default, where  <App ID URI> is the
        App ID URI of a legacy v1 Web application
      Applications are registered in the https:portal.azure.com portal.
    */
    "BaseUrl": "https://graph.microsoft.com/v1.0",
    "Scopes": "user.read"
in controller:
       [Authorize]
        [HttpGet]
        [Route("RecognitionTile")]
        [AuthorizeForScopes(Scopes = new[] { "https://ccbcc.sharepoint.com/AllSites.Read" })]
        public ViewComponentResult RecognitionTile()
        {
            return ViewComponent("RecognitionTile");
        }
for token acquistion;
        /// <summary>
        /// Private: Gets and returns an access token for the provided resource.
        /// </summary>
        /// <param name="resource">Resource to obtain access token for</param>
        /// <returns></returns>
        private async Task<string> GetAccessTokenforResource(string resource)
        {
            // Get the access token for the resource.
            string accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(new[] { resource });
           //resource is actually same as controller scope -- "https://ccbcc.sharepoint.com/AllSites.Read"
```

**Expected behavior**
Expect the incremental consent prompt to come up when call the controller.
**Actual behavior**
When call the tokenAcquisition.GetAccessTokenForUserAsync(new[] { resource }) they exception is thrown: IDW10502
An MsalUiRequiredException was thrown due to a challenge for the user.
Inner Exeption:
AADSTS65001: The user or administrator has not consented to use the application with ID 'xxx' named 'xxxx'. Send an interactive authorization request for this user and resource.

**Possible solution**

**Additional context / logs / screenshots**
This code is trying to access sharepoint api with incremental scope.
The initial scope cause the initial consent prompt during authentication:
![image](https://user-images.githubusercontent.com/65241136/93934037-8ad84000-fcf0-11ea-80f5-4415e199eb02.png)
Cleared all the Permissions prior:
![image](https://user-images.githubusercontent.com/65241136/93934180-c115bf80-fcf0-11ea-85c0-ca31c2315be6.png)
After initial consent:
![image](https://user-images.githubusercontent.com/65241136/93934440-2a95ce00-fcf1-11ea-81d7-c87931f8aac1.png)

**Comment by creativebrother** [comment]
Is the [AuthorizeForScopes(Scopes = new[] { "https://ccbcc.sharepoint.com/AllSites.Read" })]
works like [Authorize] Attribute by checking the header about the token scope to verify the scope exist, otherwise prompt user to a consent page?

**Comment by jmprieur** [comment]
@creativebrother : the AuthorizeForScopes attribute is explained here: https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

It's an exception handling attribute (it handles the MsalUiRequiredException)
which means that the method by which you acquire the token should be called by your controller action.

You can also place this attribute on the controller/page if all the actions require consent for the same scopes

**Comment by creativebrother** [comment]
Hi, jmprieur
Thanks for point out that I should acquire the token in the controller action. Now it seems it is redirecting to the authorization endpoint when my jquery.ajax call to the controller action decorated with the AuthorizeForScopes attribute. But I have the following cors errors from chrome before and after I removed the custom header. (I tried to remove the custom header from xhr in jquery ajax call to avoid this preflight check) but it still did not work. Could you kindly point out what I am missing?

Chrome error before remove  X-Requested-With header :
Access to XMLHttpRequest at 'https://login.microsoftonline.com/xxx/oauth2/v2.0/authorize?client_id=xxx&redirect_uri=https%3A%2F%2Flocalhost%3A44354%2Fsignin-oidc&response_type=code%20id_token&scope=https%3A%2F%2Fccbcc.sharepoint.com%2FAllSites.Read%20openid%20offline_access%20profile&response_mode=form_post&nonce=xxx&login_hint=xxx&domain_hint=organizations&client_info=1&state=xxx&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0' (redirected from 'https://localhost:44354/Home/RecognitionTile?_=1600837060526') from origin 'https://localhost:44354' has been blocked by CORS policy: 
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Chrome error after remove  X-Requested-With header :
Access to XMLHttpRequest at 'https://login.microsoftonline.com/xxx/oauth2/v2.0/authorize?client_id=xxx&redirect_uri=https%3A%2F%2Flocalhost%3A44354%2Fsignin-oidc&response_type=code%20id_token&scope=https%3A%2F%2Fccbcc.sharepoint.com%2FAllSites.Read%20openid%20offline_access%20profile&response_mode=form_post&nonce=xxx&login_hint=xxx&domain_hint=organizations&client_info=1&state=xxx&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0' (redirected from 'https://localhost:44354/Home/RecognitionTile?_=1600837060526') from origin 'https://localhost:44354' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by jmprieur** [comment]
@creativebrother did you have a look at this article: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors)

**Comment by creativebrother** [comment]
Yes I did.  I tried and actually it did not work. Then I realized that I am solving a different problem.
In short:
[AuthorizeForScope(Scope="xxx")] is good for redirect to the prompt page for user consent when user click on the action link.
but when an ajax call situation to the same action, the page does not redirect in browser hence ajax is calling into difference origin.

So change my code of any CORS thing won't help.  https://login.microsoftonline.com/xxx/oauth2/v2.0/authorize?xxx side is not emitting cors header. Please let me know if I misunderstood anything.

Thanks,

**Comment by creativebrother** [comment]
In the mean time, I have to create another controller action without the [AuthorizeForScope(Scope="xxx")] for the ajax call and return the a 200 with custom data containg redirect url by using ConfidentialClientApplicationBuilder.CreateWithApplicationOptions to construct the authorization endpoint url so the ajax can use the window.location to bring up the consent prompt...

**Comment by creativebrother** [comment]
I did the following and now my ajax call is working.
        [Authorize]
        [HttpGet]
        [Route("RecognitionTile")]
        //[AuthorizeForScopes(Scopes = new[] { "https://ccbcc.sharepoint.com/AllSites.Read" })]
        public async Task<IActionResult> RecognitionTile()
        {
            try
            {
                var aToken = await GetAccessTokenforResource("https://ccbcc.sharepoint.com/AllSites.Read");
            }
            catch(MicrosoftIdentityWebChallengeUserException ex)
            {
                var callbackpath = new PathString("/signin-oidc");
                var request = Request;
                var currentUri = UriHelper.BuildAbsolute(request.Scheme, request.Host, request.PathBase, callbackpath);
                var app = ConfidentialClientApplicationBuilder.CreateWithApplicationOptions(_applicationOptions).WithRedirectUri(currentUri).Build();
                var appp = app.GetAuthorizationRequestUrl(new string[] { "https://ccbcc.sharepoint.com/AllSites.Read" }).WithLoginHint(User.Identity.Name);
                var authuri = await appp.ExecuteAsync();
                return Unauthorized(new { authurl = authuri.AbsoluteUri });
            }
            return ViewComponent("RecognitionTile");
        }

**Comment by creativebrother** [comment]
Hi, @jmprieur After looked at [authorize] source code and [authorizeforscopes] source code
if it possible to do the following
        /// <summary>
        /// A delegate assigned to this property will be invoked when the related method is called.
        /// </summary>
        public Func<RedirectContext<CookieAuthenticationOptions>, Task> OnRedirectToReturnUrl { get; set; } = context =>
        {
            if (IsAjaxRequest(context.Request))
            {
                context.Response.Headers["Location"] = context.RedirectUri;
            }
            else
            {
                context.Response.Redirect(context.RedirectUri);
            }
            return Task.CompletedTask;
        };

        private static bool IsAjaxRequest(HttpRequest request)
        {
            return string.Equals(request.Query["X-Requested-With"], "XMLHttpRequest", StringComparison.Ordinal) ||
                string.Equals(request.Headers["X-Requested-With"], "XMLHttpRequest", StringComparison.Ordinal);
        }	

in AuthorizeForScopeAttribute:

                    AuthenticationProperties properties = IncrementalConsentAndConditionalAccessHelper.BuildAuthenticationProperties(
                        incrementalConsentScopes,
                        msalUiRequiredException,
                        context.HttpContext.User,
                        UserFlow);

                    var httprequest = context.HttpContext.Request;
                    if(IsAjaxRequest(httprequest))
                    {
                        context.Result = ?
                    }
                    else
                    {
                        context.Result = new ChallengeResult(properties);
                    }

**Comment by creativebrother** [comment]
Or is it possible to do it in the Startup.cs

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddCookie(options =>
                {
                    options.Events = new CookieAuthenticationEvents
                    {
                        OnRedirectToLogin = context =>
                        {
                            if (IsAjaxRequest(context.HttpContext.Request))
                            {
                                context.Response.Headers["Location"] = context.RedirectUri;
                                context.Response.StatusCode = StatusCodes.Status401Unauthorized;
                            }
                            else
                            {
                                context.Response.Redirect(context.RedirectUri);
                            }

                            return Task.FromResult(0);
                        }
                    };
                })
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                .AddDistributedTokenCaches();

**Comment by jmprieur** [comment]
@creativebrother if this works for you, this looks good for me, but I'm not an expert
Adding @tratcher for his input

**Comment by Tratcher** [comment]
Cookie auth already does that by default, not sure why you needed to modify it.
https://github.com/dotnet/aspnetcore/blob/c39ecb9f9b387ec39112c3eace5ae38db06df160/src/Security/Authentication/Cookies/src/CookieAuthenticationEvents.cs#L41-L53

**Comment by creativebrother** [comment]
@Tratcher Hi, When my ajax call the action method decorated with  [AuthorizeForScopes(Scopes = new[] { "https://ccbcc.sharepoint.com/AllSites.Read" })], its response is not 401 but is a 302 redirect(ChallengeResult) that caused the CORS issue because ajax is silently redirect to Azure Authorization EndPoint.

Is it possible in the AuthorizeForScopesAttribute to return ChallengeResult(302) or UnauthorizedObjectResult(/*Here goes with the redirectUrl for Authorization URL*/)?
I did try this, but can not get a redirect url like from login redirect is creating.

I tried modify the attribute this way at the end
                    AuthenticationProperties properties = IncrementalConsentAndConditionalAccessHelper.BuildAuthenticationProperties(
                        incrementalConsentScopes,
                        msalUiRequiredException,
                        context.HttpContext.User,
                        UserFlow);

                    var request = context.HttpContext.Request;
                    if (IsAjaxRequest(request))
                    {
                        IConfiguration configuration = context.HttpContext.RequestServices.GetRequiredService<IConfiguration>();
                        var applicationOptions = configuration.GetSection("AzureAd").Get<ConfidentialClientApplicationOptions>();
                        var callbackpath = new PathString("/signin-oidc");
                        var loginhint = properties.Parameters["login_hint"].ToString();
                        var currentUri = UriHelper.BuildAbsolute(request.Scheme, request.Host, request.PathBase, callbackpath);
                        var app = ConfidentialClientApplicationBuilder.CreateWithApplicationOptions(applicationOptions).WithRedirectUri(currentUri).Build();
                        var appp = app.GetAuthorizationRequestUrl(incrementalConsentScopes).WithLoginHint(loginhint);
                        var authuri = appp.ExecuteAsync().Result;
                        context.Result = new UnauthorizedObjectResult(new { authurl = authuri.AbsoluteUri });
                    }
                    else
                        context.Result = new ChallengeResult(properties);        

it does redirect to the authorization endpoint, can scope prompt and everything, but on the call back, I got this error:
Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty.
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

**Comment by creativebrother** [comment]
@Tratche Actually the problem I am facing is as simple as on web app page using Microsoft.Identity.Web 0.4.0-preview, an ajax call the action method decorated with AuthorizeForScopesAttribute will cause CORS issue with Azure Authorization endpoint because AuthorizeForScopesAttribute is not producing 401 but 302 result.

**Comment by creativebrother** [comment]
I have altered the AuthorizeForScopesAttribute a bit to let it return a cookie based ChallengeResult within the OnException override
                    var request = context.HttpContext.Request;
                    if (IsAjaxRequest(request))
                        context.Result = new ChallengeResult(CookieAuthenticationDefaults.AuthenticationScheme, properties);
                    else
                        context.Result = new ChallengeResult(properties);   

Now the ajax call will get 401 instead of 302 from OpenIdConnectDefaults.AuthenticationScheme as @Tratcher have suggested.
However, there are two problems now:

1  The response header gives 
     location: https://localhost:44354/Account/Login?ReturnUrl=%2FHome%2FRecognitionTile%3F_%3D1601010828886
     which is not what I want, we want to challenge the OpenId, not local Cookie Authentication here, this is not useful for 
     incremental consent since it cannot carry scopes at all, we just go back to the initial login again...
2  And there is a problem here even for cookie authentication though if you examine the Account controller Route, it is missing 
    Area "MicrosoftIdentity" here and will 404.  I reported similar issue before. It was access is denied 403, and it was missing Area 
   "MicrosoftIdentity". I had to do the following to workaround:
            services.Configure<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme, options =>
            {
                options.AccessDeniedPath = new PathString("/MicrosoftIdentity/Account/AccessDenied");
                .....
            }

**Comment by jmprieur** [comment]
@creativebrother : to enable the MicrosoftIdentity area, you need to add the 'Microsoft.Identity.Web.UI' NuGet package, and enable controllers in the startup.cs: 

For instance if you are using Razor pages:

```CSharp
       services.AddRazorPages().AddMvcOptions(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();
```

**Comment by OnAzureCloud9** [comment]
@creativebrother any luck with your AJAX calls after steps taken in this thread? I am facing the same issues.

**Comment by creativebrother** [comment]
> @creativebrother any luck with your AJAX calls after steps taken in this thread? I am facing the same issues.

@OnAzureCloud9 I tried to do the following in startup.cs and it solved the AJAX issue similar as Cookie Authentication scheme mentioned earlier by @Tratcher. Basically it detect AJAX request and return 401 in Response and in Header Location parameter pass the incremental consent page to get Auth Code. The AJAX has a chance to redirect the browser window by window.location = authcode url and avoid CORS errors.

            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                options.Events = new OpenIdConnectEvents()
                {
                    OnRedirectToIdentityProvider = context =>
                    {
                        if (IsAjaxRequest(context.Request))
                        {
                            string HeaderValueEpocDate = "Thu, 01 Jan 1970 00:00:00 GMT";
                            var message = context.ProtocolMessage;
                            var properties = context.Properties;
                            if (!string.IsNullOrEmpty(message.State))
                            {
                                properties.Items[OpenIdConnectDefaults.UserstatePropertiesKey] = message.State;
                            }
                            // When redeeming a 'code' for an AccessToken, this value is needed
                            properties.Items.Add(OpenIdConnectDefaults.RedirectUriForCodePropertiesKey, message.RedirectUri);

                            message.State = options.StateDataFormat.Protect(properties);
                            if (string.IsNullOrEmpty(message.IssuerAddress))
                            {
                                throw new InvalidOperationException(
                                    "Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.");
                            }

                            if (options.AuthenticationMethod == OpenIdConnectRedirectBehavior.RedirectGet)
                            {
                                var redirectUri = message.CreateAuthenticationRequestUrl();
                                context.Response.Headers["Location"] = redirectUri;
                                context.Response.StatusCode = 401;

                            }
                            else if (options.AuthenticationMethod == OpenIdConnectRedirectBehavior.FormPost)
                            {
                               // similar just let AJAX bring up a form post to avoid the CORS here too...
                            }
                            context.HandleResponse();
                        }
                        return Task.FromResult(0);
                    }
                };
            });

But I have another problem after I introduced this OnRedirectToIdentityProvider  OpenIdConnectEvent, which is now causing an infinite loop on this authcode pagesimilar to #573, #531. It seems that the it is interfering with the following method
protected override async Task HandleChallengeAsync(AuthenticationProperties properties)
within 
public class OpenIdConnectHandler : RemoteAuthenticationHandler<OpenIdConnectOptions>, IAuthenticationSignOutHandler.
The method is requesing auth code and then within same method redeming access token.
Trying reading all kind of document about auth code flow which is up to date with the code is a challenging task alone, 

I just upgraded the Microsoft.Identity.Web to the 1.0.0, will look if there is any luck.

For my project to move ahead, I just admin consent them all and removed the incremental consent, sadly.

**Comment by creativebrother** [comment]
@OnAzureCloud9 @Tratcher @jmprieur 
Finally had sometime to look into the related source code and find a way to correctly handle AJAX call to Action Method deocrated with  AuthorizeForScopesAttribute for dynamic consent.
            services.AddOptions<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme).Configure(options =>
            {
                var redirecthandler = options.Events.OnRedirectToIdentityProvider;
                options.Events.OnRedirectToIdentityProvider = async context =>
                {
                    await redirecthandler(context).ConfigureAwait(false); //Need to call this first !!! unlike the original ones in library
                    if (IsAjaxRequest(context.Request))
                    {                        
                        var message = context.ProtocolMessage;
                        var properties = context.Properties;
                        properties.RedirectUri = "/";
                        properties.Items[".redirect"] = "/";
                        if (!string.IsNullOrEmpty(message.State))
                        {
                            properties.Items[OpenIdConnectDefaults.UserstatePropertiesKey] = message.State;
                        }
                        // When redeeming a 'code' for an AccessToken, this value is needed
                        properties.Items.Add(OpenIdConnectDefaults.RedirectUriForCodePropertiesKey, message.RedirectUri);

                        message.State = options.StateDataFormat.Protect(properties);
                        if (string.IsNullOrEmpty(message.IssuerAddress))
                        {
                            throw new InvalidOperationException(
                                "Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.");
                        }

                        if (options.AuthenticationMethod == OpenIdConnectRedirectBehavior.RedirectGet)
                        {
                            var redirectUri = message.CreateAuthenticationRequestUrl();
                            context.Response.Headers["Location"] = redirectUri;
                            context.Response.StatusCode = 401;

                        }
                        else if (options.AuthenticationMethod == OpenIdConnectRedirectBehavior.FormPost)
                        {
                           // similar just let AJAX bring up a form post to avoid the CORS here too...
                        }     
                        context.HandleResponse();                  
                    }
                };
            });

**Comment by creativebrother** [comment]
@Tratcher After looking at the source code in OpenIdConnectHandler -> HandleChallengeAsync-> HandleChallengeAsyncInternal
I need to duplicated the part of the code there in my options.Events.OnRedirectToIdentityProvider handler to short-circuit it to conditionally return and 401 for AJAX type request. Not sure if it is possible to add this logic in the HandleChallengeAsyncInternal or 
@jmprieur add this redirect logic in options.Events.OnRedirectToIdentityProvider within AddMicrosoftIdentityWebApp extention method?
It will greatly help developers on successfully AJAX calling the incremental consent controller actions because it took me quite some time to sort this out after going through lots of scouting in both OpenIdConnect and Microsoft.Identity.Web and MSAL stuff.
Thanks,

**Comment by OnAzureCloud9** [comment]
@creativebrother how are you handling the AJAX call client side after getting a 401? I setup a similar custom solution but instead I'm returning a 403 (not sure if 401 or 403 is more appropriate here, but really we're doing the same thing). On client side in the AJAX callback function, I check if I get an error and a 403. Then, I'm changing the window location direction to "/MicrosoftIdentity/Account/SignIn" (from the `Microsoft.Identity.Web.UI` package). This re-signs in the user which refreshes the tokens and then AJAX calls succeed. However, after navigating to the login page, it returns the user back to the homepage after successfully logging in. I tried replacing the redirect URL in a custom call to the login endpoint but that does not work since it's not in the reply URLs for the Azure app registration. So, my best solution is notify the user via alert that they're session has expired and they'll be redirected to login. Then it logs them back in and they land back at the home page. 

Can you explain how you are handling this client side? Are you able to redirect back to the original page the user was viewing before an MSAL exception occurred from an AJAX call? Are you able to save any state (such as if the user was filling out a form) on the page as well? I'm not content with forcing the user back to the login screen every time the token needs to be refreshed, but at least I'm able to get my AJAX calls working now.

**Comment by jmprieur** [comment]
See also https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/264#issuecomment-703351600

**Comment by jmprieur** [comment]
@creativebrother. Thanks for sharing your learnings.
Do you want to provide a PR (with a test solution?)

**Comment by creativebrother** [comment]
@jmprieur Sure! Will do that.

**Comment by creativebrother** [comment]
@OnAzureCloud9 For the state info like form data I would think Tempdata, but it perhaps won't work since there are two redirects here. But you can embed your custom data in the state OpenIdMessage's state property as exiting auth properties like redirect url etc, since it will be protected when sending to authorize endpoint and on the way back. Specifically  I just add a new dictionary item on the AuthenticationProperties.Items and you get it back after authentication.
As for redirect to previous user window location, this should be provided by the challenge itself, if not, an default of "/" is provided to the framework in the RemoteAuthenticationHandler's HandleRequestAsync().  Currently it is providing the "AJAXed URL" which is not fit for my situtation, I just manually set it in the above mentioned state to whatever URL which contains the AJAX call.
In a separate thread you mentioned you issue, I commented about refresh token feature existed in the authentication flow, just wondering why that did not kick in? My understanding is you should not need to manually refresh the token, the MSAL will do it for you.

**Comment by jennyf19** [comment]
@creativebrother thanks for your contribution on this!
Included in [1.2.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.2.0).

**Comment by jmprieur** [comment]
cc: @OnAzureCloud9

**Comment by OnAzureCloud9** [comment]
Thanks for the tag @jmprieur. I will try out the 1.2.0 release this weekend with AJAX calls. Do you know if the 1.2.0 release still requires some custom implementation of OpenIdConnect? @creativebrother described that in [this post](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/264#issuecomment-707361318).

**Comment by jmprieur** [comment]
No, it shouldn't @OnAzureCloud9 : the startup.cs is pretty standard now. https://github.com/AzureAD/microsoft-identity-web/blob/77d2b6a1958f6bd7e9d514bd04e46d374773097b/tests/AjaxCallActionsWithDynamicConsent/Startup.cs#L31

**Comment by OnAzureCloud9** [comment]
@jmprieur great to hear. I will try this out this weekend and report back some results.

**Comment by OnAzureCloud9** [comment]
@jmprieur looks like we still need to add some custom options like @creativebrother showed here? https://github.com/AzureAD/microsoft-identity-web/issues/603#issuecomment-703316365

I updated my started based on the format linked above with Open ID Connection defaults. When `MicrosoftIdentityWebChallengeUserException` is thrown it's a very similar issue to before where I receive a CORS error in the browser and no headers or status code information available in the error callback function for the AJAX call.

**Comment by OnAzureCloud9** [comment]
Looks like I'm having better luck after adding the `OnRedirectToIdentityProvider` into my app. Is there a reason this isn't in the example linked for Ajax calls? That is what is throwing me off a bit and what made me think I'm doing something wrong. 

After adding the `OnRedirectToIdentityProvider` in Startup file I am getting a 401 now. Still having an issue with it redirecting back to the appropriate page. Looks like in @creativebrother example above he is setting the redirect URI in the `OnRedirectToIdentityProvider`. Isn't this always going to redirect back to the home page? I had to update this to use the HTTP context request and fetch the `X-ReturnUrl` that I'm now passing with my AJAX requests. Then I re-assign that value instead of using "/". I feel like I'm missing something from the 1.2.0 update for Ms.Id.Web:

- Shouldn't the authorize for scopes attribute now determining that it's an AJAX call and add the appropriate redirect URL to the challenge properties?
- Do I still need the `OnRedirectToIdentityProvider` which are missing from the sample or am I missing something there?
