### ISSUE TITLE
Missing Strong Name

### ISSUE THREAD

**Issue by stevebuckco** [AzureAD/microsoft-identity-web#607]
Can you release an update with the assemblies signed?  We're unable to use the package because of the missing strong names

**Comment by jmprieur** [comment]
@stevebuckco: which version of which NuGet package? Can you please provide us with a link to the NuGet packages ?
The signing happens in our release build and I personally check that each NuGet package is signed, so I'm a bit surprized

**Comment by jmprieur** [comment]
I checked 0.4.0-preview, and it's signed.

![image](https://user-images.githubusercontent.com/13203188/94059426-acb1ef80-fde2-11ea-8a94-baa25868e55f.png)

**Comment by jmprieur** [comment]
@stevebuckco 
Closing this issue. feel free to reopen if you disagree
