### ISSUE TITLE
[Bug] add tid long-claim check in AadIssuerValidator.GetTenantIdFromToken

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#617]
**Which version of Microsoft Identity Web are you using?**
1.0.0

**Where is the issue?**
* Web app
    * [x ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ x] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
Not a regression. Found by @GeoK when reviewing the code. No customer impact known

**Repro**
See https://github.com/AzureAD/microsoft-identity-web/blob/5d3c277ed53e060b91f0c1c36d041e09e6055388/src/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs#L177

There is no long-claim check

**Expected behavior**
Have a long-claim tid check in addition to the short tid claim check

**Actual behavior**
long tid claims not checked from the token. No know customer impact (hence P2)

**Comment by jennyf19** [comment]
Included in [1.1.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.1.0).
