### ISSUE TITLE
[Bug] `requestContent` is not used in the method `DownstreamApi.CallWebApiForAppAsync`

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#618]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
Not a regression

**Repro**

Look at  https://github.com/AzureAD/microsoft-identity-web/blob/5d3c277ed53e060b91f0c1c36d041e09e6055388/src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs#L169

**Expected behavior**
`requestContent` should be used in the method, or the parameter removed

**Actual behavior**
`requestContent` is not used in the method `DownstreamApi.CallWebApiForAppAsync`

**Comment by jennyf19** [comment]
Included in [1.1.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.1.0).
