### ISSUE TITLE
[Bug] Token is not always returned after user has logged in

### ISSUE THREAD

**Issue by anant-k-singh** [AzureAD/microsoft-identity-web#619]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 0.4.0-preview

**Where is the issue?**
* Web app
    - [ ] Sign-in users
    - [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app

**Repro**
StartUp.cs
```csharp
public void ConfigureServices(IServiceCollection services)
{
    string[] initialScopes = Configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' ');

    services
        .AddMicrosoftIdentityWebAppAuthentication(Configuration)
        .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
        .AddInMemoryTokenCaches();

    services.AddControllersWithViews(options =>
    {
        var policy = new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .Build();
        options.Filters.Add(new AuthorizeFilter(policy));
    });

    services.AddRazorPages()
        .AddMicrosoftIdentityUI();
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
 
    app.UseHttpsRedirection();
    app.UseStaticFiles();

    app.UseRouting();

    app.UseAuthentication();
    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=Home}/{action=Index}/{id?}");
        endpoints.MapRazorPages();
    });
}
```
Controller.cs
```csharp
[AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
public class EmbedInfoController : Controller
{
    private string token;
    private ITokenAcquisition tokenAcquisition;
    public EmbedInfoController(ITokenAcquisition tokenAcquisition){
        this.tokenAcquisition = tokenAcquisition;
    }

    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    [HttpGet]
    [Route("/embedinfo/generateToken")]
    public async Task<string> GenerateToken()
    {
        // This does not get the token when user is already logged in the browser
        this.token = await tokenAcquisition.GetAccessTokenForUserAsync(requiredScope);  // requiredScope = https://analysis.windows.net/powerbi/api/.default
        return this.token;
    }
    ...
}
```
appsettings.json
```json
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "",
    "TenantId": "common",
    "ClientId": "",
    "ClientSecret": "",
    "ClientCertificates": [
    ],
    "CallbackPath": "/signin-oidc"
  },
  "DownstreamApi": {
    "BaseUrl": "https://analysis.windows.net/powerbi/api",
    "Scopes": ".default"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}

```
Or, add the above to the HomeController of [2-1 Azure Sample for MIW WebApp](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph)

**Expected behavior**
If the user is logged in the browser (i.e. User was logged in automatically on login redirect), `GetAccessTokenForUserAsync` should return the accessToken or if the token is not found in cache, redirect to login page. 

**Actual behavior**
There are two scenarios
1. The user is **not** logged in the browser: (Works as expected)
User is redirected to Microsoft's login page. Once the user successfully signs in, user is redirected back to our app.
`await tokenAcquisition.GetAccessTokenForUserAsync(requiredScope);` returns the accessToken as expected.

1. The user is **already** logged in the browser: **(Unexpected)**
User is redirected to Microsoft's login page. User is immediately redirected back to our app.
`await tokenAcquisition.GetAccessTokenForUserAsync(requiredScope);` does **not** return the accessToken.
__MicrosoftIdentityWebChallengeUserException__ is thrown.

**Exception message:**
```
Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException: IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent.
---> MSAL.NetCore.4.18.0.0.MsalUiRequiredException:
ErrorCode: user_null
Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.
```

**Exception screenshot:**
![image](https://user-images.githubusercontent.com/22440924/94541133-d779c900-0264-11eb-9468-2104a4f50467.png)

**Comment by jmprieur** [comment]
@anant-k-singh 
this is the expected behavior for the moment: if there is a session cookie, and no token in the cache, then the user should be challenged. 
Is the value of `requiredScope` the same as what you have in the **Scopes** property of the **DownstreamApi** section in your appsettings.json?

Did you read this article? https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

**Comment by jmprieur** [comment]
Also relates to https://github.com/AzureAD/microsoft-identity-web/issues/13 (which proposes another behavior)

**Comment by anant-k-singh** [comment]
I understand that when the user is already logged in the browser, we would not have token in the cache and sign in via UI would be required.
How do we redirect to the sign in page when MicrosoftIdentityWebChallengeUserException is thrown?

**Comment by jmprieur** [comment]
Do you mean the AuthorizeForScope attribute did not redirect you?
Did you add MicrosoftIdentityUI: https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#startupcs ?

**Comment by anant-k-singh** [comment]
Exactly, AuthorizeForScope attribute does not redirect the user.
Yes, we have added `services.AddRazorPages().AddMicrosoftIdentityUI();` in the _startup.cs_ using Microsoft.Identity.Web.UI.

@jmprieur Is it possible that because I am returning string and not a View() from the controller, the user is not redirected to login page in case of MicrosoftIdentityWebChallengeUserException?

**Comment by anant-k-singh** [comment]
Actually [AuthorizeForScope] attribute does redirect to login page.
The issue was that I was calling the controller with an ajax/fetch call and it returned redirect response with 302 when token is not available and the redirect request in the 302 response was blocked due to CORS policy

This issue was resolved when I returned view (razor page).
The `MicrosoftIdentityWebChallengeUserException` was thrown in this case as well, but it is handled automatically by Microsoft.Id.Web
