### ISSUE TITLE
[Question]: How to programmatically redirect to Microsoft's login page

### ISSUE THREAD

**Issue by anant-k-singh** [AzureAD/microsoft-identity-web#623]
Context:
I have a .NET Core web app and I am using the Microsoft.Identity.Web & Microsoft.Identity.Web.UI NuGet packages for redirecting to Microsoft's login page on click of a custom sign in button, but currently it redirects to Microsoft's login page first at the start of the application and then after login shows the custom sign in button.

Question:
How to programmatically control when to redirect to Microsoft's login page?

**Comment by jmprieur** [comment]
@anant-k-singh

You're redirected to the Microsoft login page because your page or controller has the `[Authorize]` attribute
If your default controller action / Page does not have the `[Authorize]` attribute, the user won't need to sign-in. This would only happen on protected pages.
