### ISSUE TITLE
[Documentation] (migration)

### ISSUE THREAD

**Issue by grounzero** [AzureAD/microsoft-identity-web#627]
### Please check all that apply

- [ ] typo
- [ x] documentation doesn't exist
- [x ] documentation needs clarification
- [x ] error(s) in the example
- [ x] needs an example

### Description of the issue
Have upgraded to 1.0.0 and ```AuthenticationBuilder AddMicrosoftWebApiAuthentication(this IServiceCollection services ... )``` is missing.  

Do I change it to ```MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration AddMicrosoftIdentityWebApiAuthentication(this IServiceCollection services ... )```

**Comment by jmprieur** [comment]
@grounzero : the change happened in 0.3.0: See https://github.com/AzureAD/microsoft-identity-web/wiki/0.3.0-preview. The wiki is up to date.
Indeed, you can use AddMicrosoftIdentityWebApiAuthentication
See https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#protected-web-apis---startupcs

**Comment by grounzero** [comment]
@jmprieur thanks for confirming :)
