### ISSUE TITLE
Request to Support Mutliple Authorization Servers 

### ISSUE THREAD

**Issue by rsrinivasanhome** [AzureAD/microsoft-identity-web#637]
I have exposed an api which needs to validate AD Token, Azure Ad B2C token and able to configure the library to work with microsoft identity web library.  Now I need to also validate Auth 0 token.  I need to give a different metadata end point .

A clear sample on how to configure the metadata endpoint of the third party oauth provider along with setting the issuer.

Any pointer to a sample or guidance on how to achieve this would be great .

**Comment by jmprieur** [comment]
@rsrinivasanhome : in that case you should just add the OpenIdConnect provider for Auth0

```CSharp
services.AddAuthentication()
              .AddXXXXX()
```

See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/other-logins?view=aspnetcore-3.1

cc:@tratcher

**Comment by jmprieur** [comment]
@rsrinivasanhome 
Closing as this is answered
