### ISSUE TITLE
[Documentation] AJAX requests when authorization is needed

### ISSUE THREAD

**Issue by OnAzureCloud9** [AzureAD/microsoft-identity-web#642]
### Documentation related to component
None, yet.

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [x] needs an example

### Description of the issue
When calling a .NET Core controller action with the [AuthorizeForScopes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.authorizeforscopesattribute?view=azure-dotnet-preview) attribute client side from an AJAX call a CORS issue occurs:

`Access to XMLHttpRequest at 'https://login.microsoftonline.com/..........' (redirected from 'https://localhost:44352/test/testPartialView) from origin 'https://localhost:44352' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

This does not always occur but presumably does when the user's authorization is expired. Then, I assume in the controller action a [MsalUiRequiredException](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.msaluirequiredexception?view=azure-dotnet) is thrown which creates a request of type "xhr / Redirect" and returns a 302 which results in the CORS issue due to the redirect. This is similar to an issue [described here](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/264).

Using AJAX to make calls to a .NET Core application using _Microsoft.Identity.Web_ is a common scenario and I anticipate many will face this issue. Can documentation be created to provide guidance when using _Microsoft.Identity.Web_ and making AJAX calls to a controller action for a protected web app?

Other details:
Microsoft.Identity.Web version: 1.0.0
Microsoft.Identity.Web.UI version: 1.0.0

**Comment by jennyf19** [comment]
Included in [1.2.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.2.0).
