### ISSUE TITLE
[Fundamentals] Add additional metrics/counters to the PerformanceTestService

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#643]
Add metrics:
- Cache item size
- Id.Web Cache size in MB, and in number of items, 
- Id.Web Cache hits/misses, 
- Id.Web Cache load/save timing numbers, 
- Id.Web Errors (by error code)
- MSAL cache hits/misses,  
- MSAL cache load/save timing numbers
- MSAL Errors (by error code)

Note: Might need to update MSAL to send the telemetry.

Also add metrics for System.Runtime ([here](https://github.com/AzureAD/microsoft-identity-web/blob/6bbc143b33a07ec6fb34562ace6b8d0afbe244af/tests/PerformanceTests/PerformanceTestService/Startup.cs#L42-L53)) and verify if they are needed/more accurate than the default ones in the App Insights:
- cpu-usage
- working-set

Additionally should think if it's better to use EventCounters or TelemetryClient to send metrics.

**Comment by bgavrilMS** [comment]
No work is needed on MSAL to get these metrics. For cache hit / miss, there exists `AuthenticationResult.ResultMetadata.TokenSource` which will be set to Cache in case of a hit. 

What is missing here is the time spent in network calls, which can be calculated by injecting an HTTPClient that monitors the network, similar to  [this one](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/5000f4a5624c1acd4cf1c07b25c6abb5eedf746c/tests/Microsoft.Identity.Test.Common/Core/Helpers/HttpSnifferClientFactory.cs#L11))

Overall, we care more about time spent in MSAL / M.I.W than on the network and in the cache, although total time using a well-known cache implementation (e.g. Redis, as you propose) is what customers want to see.

**Comment by pmaytak** [comment]
I added some related thoughts on this in [Feature Request High-Level perf assement scenario #2146](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2146).
`AuthenticationResult.ResultMetadata.TokenSource` could be checked in the test runner that directly calls MSAL (as opposed to in the service). We do that in MIW perf client.

**Comment by pmaytak** [comment]
Closing as the cache related metrics were added. Postponing adding error metrics (created #735 for tracking that).
