### ISSUE TITLE
[Fundamentals] Add performance tests that use Redis distributed cache

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#646]
Goal: Collect metrics for the Redis cache operations.

Approach:
Set up Redis cache and hook up the performance test service to it. Existing cache related metrics should already work.

Considerations:
- Choose between local hosted Redis or Azure Redis.

Effort: .5 days

**Comment by bgavrilMS** [comment]
Propose not to do this, profiling MSAL is more important to get some wins here.
