### ISSUE TITLE
[Fundamentals] Add more e2e performance test cases

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#647]
Goal: Add test cases that cover all end-to-end scenarios in Identity Web.

Approach: Create a controller action for each scenario below, which only performs that operation. Have test runner send requests to that action.

Currently used test endpoint:
- TokenAcquisition.GetAccessTokenForUserAsync (OBO)

Other existing test endpoints include:
- TokenAcquisition.GetAccessTokenForAppAsync
- Empty Action (Controller has GraphServiceClient, TokenAcqusition injected)

Possible other endpoints include for testing:
- TokenAcquisition.AddAccountToCacheFromAuthorizationCodeAsync
- TokenAcquisition.RemoveAccountAsync
- HttpContext.VerifyUserHasAnyAcceptedScope
- HttpContext.ValidateAppRole
- CallDownstreamWebApi
- CallMicrosoftGraph
- Empty Action in Controller with different injected classes

Additionally:
- Add additional metrics (ex. measure time with stopwatch) in the action to measure operation execution time.

Effort: 2 days

**Comment by bgavrilMS** [comment]
We should get more value from existing test cases before investing in more. Propose to postpone this.
