### ISSUE TITLE
[Fundamentals] Host the perf test runner in a scalable location

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#649]
Goal: Host test runner in a location where it is able to be run continously.

Previously the test runner ran from a VM (which seems to be the simpler solution). Other possibilities: Azure Functions, WebJobs.

Additionally:
- Should also be able to run multiple instances of runner with different configuration (possibly via command line arguments).

Considerations:
- Previously had issues remoting into a Lab DevTest VM; however, setting up a non-Lab VM was quick and straightforward.

Effort: .5 days

**Comment by bgavrilMS** [comment]
The typical mechanism for running perf test is to run them over and over on the same machine. I believe this is also the approach of the Middleware team. We can get a dedicated VM for this if needed. 

For now, I propose we just rely on Azure Hosted VMs having the same specs.
