### ISSUE TITLE
[Feature Request] VerifyUserHasAnyAcceptedScope should appear as an ASP.NET Core policy and have a better name

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#65]
**Is your feature request related to a problem? Please describe.**
Today, the scopes are checked in the contoller actions by

```csharp
[Authorize]
ControllerAction()
{
 HttpContext(VerifyUserHasAnyAcceptedScope(scopes);

 // .. do the work
}
```

**Describe the solution you'd like**
```csharp
[Authorize(Policy="CheckScopes", Scopes= scopes)]
ControllerAction()
{
 // .. do the work
}
```

**Comment by jmprieur** [comment]
cc: @jennyf19

**Comment by jmprieur** [comment]
@jennyf19 @pmaytak @henrik-me 
It's not possible, in the Authorize attribute to use Scopes=
See https://github.com/dotnet/aspnetcore/blob/f3b370c1ac986312db5824b1735c9bb3ee3117c4/src/Security/Authorization/Core/src/AuthorizeAttribute.cs

Proposing to punt this one.
Please tell me if you disagree

**Comment by pmaytak** [comment]
@jmprieur Instead of `Authorize` attribute could we perhaps create our own like `VerifyUserScopes` or something? I'm thinking a method or controller class attribute is a bit simpler and more intuitive to use.

**Comment by jmprieur** [comment]
Yes,  @pmaytak : we have an issue to investigate that: https://github.com/AzureAD/microsoft-identity-web/issues/17

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)

**Comment by plamber** [comment]
Hi @jmprieur,
I wanted to use a custom attribute and apply it to my controller or methods like this.

![image](https://user-images.githubusercontent.com/18241305/102627365-64d40780-4148-11eb-9ed6-3020860cd2e6.png)

I ended up using your code under VerifyUserHasAnyAcceptedScope and wrote [this Gist](https://gist.github.com/plamber/3122487154a7503216c7ad48f1252deb.js). 

Is this something that could become useful for you?

Cheers,

**Comment by jmprieur** [comment]
thanks @plamber 
Yes, I think that would be useful. @jennyf19 what do you think?

@plamber : Do you want to propose a PR?

**Comment by plamber** [comment]
@jmprieur I created an enhancement issue first #849. 

If you want, I can create a pull request. I am just wondering how you want to return the custom error message. This has not been implemented in this solution yet. The only technique I am aware of is (this one)[https://ignas.me/tech/custom-unauthorized-response-body/]

If you are interested we can continue with the specification here #849 (names, namespaces, etc.). Then I can make the PR
