### ISSUE TITLE
[Bug] ARM does not work for MSA accounts

### ISSUE THREAD

**Issue by rcladmin** [AzureAD/microsoft-identity-web#651]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.0.0

**Where is the issue?**
* Web API
    * [ ] Protected web APIs (validating scopes)

For **Microsoft Accounts (MSA)** , when scopes for Azure Services Management are requested, the following error is received:

"error":"invalid_scope","error_description":"AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'https://management.azure.com/user_impersonation offline_access openid profile' does not exist.

The consent screen is not provided and the access token is not provided for MSA accounts for Azure Services Management.

For AAD Work and School accounts, the consent screen is provided (if consent was not provided before) and the token is issued. It works as expected.

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of Microsoft Identity Web.
-->

**Repro**

Sign in with a Microsoft Account (MSA). 

```csharp
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;

namespace RCL.CloudApps.Portal.Controllers
{
    [Authorize]
    public class ARMConsentController : Controller
    {
        private readonly ITokenAcquisition _tokenAcquisition;

        public ARMConsentController(ITokenAcquisition tokenAcquisition)
        {
            _tokenAcquisition = tokenAcquisition;
        }

        [AuthorizeForScopes(Scopes = new[] { "https://management.azure.com/user_impersonation" })]
        public async Task<IActionResult> Index()
        {
            string[] scopes = new string[] { "https://management.azure.com/user_impersonation" };
            string accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(scopes);

            return RedirectToPage("/Dashboard", new { area = "" });
        }
    }
}
```

**Expected behavior**
Display the Consent screen to provide permissions to Azure Services Management API (if consent was not provided before). Subsequently, the issuance of the access token.

**Actual behavior**
An exception thrown : "error":"invalid_scope","error_description":"AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'https://management.azure.com/user_impersonation offline_access openid profile' does not exist.

**Possible solution**
None that I know of.

**Additional context / logs / screenshots**

**Expected behavior** -- (AAD Work and School Accounts works)

![arm_permissions](https://user-images.githubusercontent.com/4339259/94981625-80445480-0501-11eb-8c99-14f684b9d1b1.PNG)

**Actual behavior** -- (Microsoft Accounts Fails)

![arm_permissions_msa_error](https://user-images.githubusercontent.com/4339259/94981631-9a7e3280-0501-11eb-8a3d-d39ee2d390e0.PNG)

**Comment by jmprieur** [comment]
@rcladmin : To my knowledge, Azure Resource Manager does not support MSA accounts yet. Are you saying that this was working before? In that case which client Id did you use to have?

**Comment by rcladmin** [comment]
I have never gotten MSA accounts to work with Azure Resource Manager (ARM) before. Are there any plans for ARM to support MSA accounts?

**Comment by jmprieur** [comment]
@hpsin would you know?

**Comment by hpsin** [comment]
That team is looking at it with Stuart. It's a known gap.
@rcladmin what is the scenario for supporting ARM with MSA for your app? Tenant lookup, or managing resources?

**Comment by jmprieur** [comment]
Thanks @rcladmin for the update. Proposing to close this issue (we'll answer if we get the information about ARM support for MSA)

**Comment by rcladmin** [comment]
@hpsin MSA support for ARM for managing resources is required.

**Comment by hpsin** [comment]
Got it - thanks @rcladmin .  This isn't actually the case though - you can only manage resources in the context of an AAD tenant.  Thus, you need to sign the user into the AAD tenant that owns the resource, at which point you're no longer signing in an MSA, just an AAD guest. Do if you use a tenant-specific authority, on v1 or v2, you can sign the user in and get a token for ARM no matter where they're from, since they're acting as an AAD user.

**Comment by rcladmin** [comment]
@hpsin based on your recommendation, I have signed in the user to a specific tenant that contains their resources, changing my configuration as follows : 

```
// "AzureAd:TenantId": "common", // Multi-tenant scenario
  "AzureAd:TenantId": "b3edd15f-xx-xxxx-xxxxxx", // Single tenant scenario
```

It works. The access token and consent is now issued for ARM to manage resources for a MSA account.

However, my problem now is how to get this to work with a Multi-tenant scenario? I am creating a SaaS application in a multi-tenant scenario. I don't know my customers teantid when they are initially signing in to my SaaS application. And if I do get their tenatid somehow, how do I dynamically change my configuration to change the tenantid for each customer when they sign in.

Is there some way to get this to work in a multi-tenant scenario? I am stumped here, can you point me in the right direction? Your assistance will be greatly appreciated.

**Comment by hpsin** [comment]
@jmprieur would be the best to help you with updating your app to support multi-tenant handling.  You would need some UX that asks for their tenant ID if they're an MSA, and then initialize your app object with that tenant ID as the authority.

**Comment by rcladmin** [comment]
'Initialize your app object with that tenant ID as the authority' - how do you do this? Will need to resarch into this. 

If your are you are aware of any samples or resources where someone actually accomplished , feel free to share.

**Comment by jmprieur** [comment]
@rcladmin : This sample should help you doing that: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

(I know there is a lot to read, but I think you'd want to read the README.md carefully)

**Comment by jcharnley** [comment]
what about if you need to keep the /common endpoint but then you want to call ARM to find out the list of tenant and ask the user to select it, thus accessing the correct tenant the guest user has been invited into. There is a serious technolgy gap in this area. Multi Tenant apps are not fully multi tenant when guest users are involved. It would be great to hear any updates on this topic
