### ISSUE TITLE
[Bug] Unable to install the latest 1.0.0 .NET templates

### ISSUE THREAD

**Issue by cmatskas** [AzureAD/microsoft-identity-web#668]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Microsoft Identity Web 1.0.0

**Where is the issue?**
The blob for the NuGet package for the templates is missing/broken
* Other (please describe)
When attempting to download and install the latest NuGet package for the CLI templates, the installation fails because the blob is missing

**Is this a new or an existing app?**
No

**Repro**
Open the CLI
Type `dotnet new -i Microsoft.Identity.Web.ProjectTemplates.1.0.0.nupkg`

**Expected behavior**
Installation completes successfully

**Actual behavior**
The installation receives the following error message
```
PS C:\Users\cmatskas> dotnet new -i Microsoft.Identity.Web.ProjectTemplates.1.0.0.nupkg
  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp1.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\cmatskas\.templateengine\dotnetcli\v5.0.100-rc.1.20452.10\scratch\restore.csproj]
C:\Users\cmatskas\.templateengine\dotnetcli\v5.0.100-rc.1.20452.10\scratch\restore.csproj : error NU1101: Unable to find package Microsoft.Identity.Web.ProjectTemplates.1.0.0.nupkg. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
  Failed to restore C:\Users\cmatskas\.templateengine\dotnetcli\v5.0.100-rc.1.20452.10\scratch\restore.csproj (in 589 ms).
```
Attempting to access the NuGet package from the URL, I also get this error:

![image](https://user-images.githubusercontent.com/4126750/95402512-c95f2480-08c4-11eb-97c4-71517c5505bc.png)

**Possible solution**
Restore the blob or fix

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by cmatskas** [comment]
@jennyf19 @jmprieur FYI, the template download is broken :(

**Comment by jennyf19** [comment]
Yes, @cmatskas, we had issues pushing that nuget package. we are working to sort it out, should be up oct.8. you can run the templates from the repo directly, by doing dotnet pack.

**Comment by jmprieur** [comment]
@cmatskas 
Microsoft.Identity.Web.ProjectTemplates.1.1.0 was uploaded to NuGet a few hours ago. The wiki is up to date.
