### ISSUE TITLE
[Feature Request] TokenAcquisitionOptions should have a Claims property

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#677]
**Is your feature request related to a problem? Please describe.**
Some apps want to trigger a conditional access policy and therefore specify claims.

**Describe the solution you'd like**
a `Claims` property in `TokenAcquisitionOptions`

**Describe alternatives you've considered**
ExtraQueryParameters, but this does not do it all

**Comment by jmprieur** [comment]
@jennyf19 do we still want to do this one? it seems we'll do differently?

**Comment by jennyf19** [comment]
Included in [1.2.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.2.0).
