### ISSUE TITLE
Additional roles managed within application - do I use OpenIdConnectEvents or Microsoft Graph API?

### ISSUE THREAD

**Issue by superman-lopez** [AzureAD/microsoft-identity-web#680]
I am using `Microsoft.Identity.Web` version 1.1 with Azure AD.  I want to manage my users application roles within my application, and plan to use `RoleManager` as suggested [here in Microsoft documentation](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#roles-using-an-application-role-manager)

How do I call `RoleManager` such that the roles can be added by my application?  Do I use `OpenIdConnectEvents` and if so which is the appropriate event that should call `RoleManager`?

(I am not using ASP.Net Core Identity: I only plan to store the roles basis Azure AD users' id and rely on Azure AD for the identity).

**Comment by jmprieur** [comment]
@superman-lopez : did you have a look at this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-1-Roles ?

**Comment by superman-lopez** [comment]
No, I will review this now.  Thanks!

**Comment by superman-lopez** [comment]
@jmprieur I had a look at the Readme, and also searched the repository for use of `RoleManager` but it's not immediately obvious to me that this is related.  The Readme states:
>These application roles are defined in the Azure portal in the application's registration manifest. When a user signs into the application, Azure AD emits a roles claim for each role that the user has been granted individually to the user in the from of role membership. Assignment of users and groups to roles can be done through the portal's UI, or programmatically using the Microsoft Graph and Azure AD PowerShell.

So this means to me the application roles are managed on the Azure AD, rather than in application.

**Comment by jmprieur** [comment]
@superman-lopez : our recommendation is to use the Azure AD way.
Could you please share your scenario, and why you'd prefer to have an in-app management? (you could always manage the roles from the app using the Microsoft Graph API:  https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties see app roles

**Comment by superman-lopez** [comment]
It's an enterprise SaaS application where the roles need to be able to be assigned in-app, as it's not guaranteed that our client's security officer (or application owner) responsible for our application has access to the Azure AD portal.  

We did review using Graph API, but that was in context of extension properties to store permissions.  That was not deemed secure as the extension properties could potentially also be read/written to by other applications that were consented to do so.  I will review `appRoleAssignment` now and see if it meets our goals. 

Can I conclude from your reply that I should not or cannot use `OpenIdConnectEvents` to manage roles?

**Comment by jmprieur** [comment]
@superman-lopez : no I don't think  you should conclude anything. It will take us a bit of time to understand your scenario and the RoleManager (unknown to me yet)

@kalyankrishna1 : would you have any insights?

**Comment by superman-lopez** [comment]
Thanks @jmprieur 

In fact I was also considering to use `OpenIdConnectEvents` to include other claims, such as licenses specific to paid-for features. So my concern is actually related to a broader context, it's just that Application Roles was the first part I decided to implement.

**Comment by superman-lopez** [comment]
Hi @jmprieur,
Thanks again for your thoughts on managing the Application Roles.  We are reviewing how we can implement the management of Application Roles through the Graph API as you recommended.  Unfortunately I am running into a practical issue with the tokens.

The application is ASP.Net Web API, and the configuration for it was done by following this sample using `Microsoft.Identity.Web`: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API

The authentication with Azure AD is done with `msal-browser` in our SPA, and the application was configured basis this sample: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample .  (I have combined the two projects for [my own reference](https://github.com/superman-lopez/AzureAd_AspNet_Angular))

So the tokens are issued to our SPA and through the HTTP interceptor the relevant token is included in the HTTP request to our ASP.Net Web API.  The issue I run into is that I have three relevant tokens that are needed on the ASP.Net Web API, yet I can't include all three in my HTTP request. 

I have an `AccessToken` to make the Web API call with the `api://~guid~/scope` scope, an `AccessToken` for the Graph API scopes and an `IdToken` that holds my Application Roles.  I will always need the first `AccessToken` so that I can access my Web API, and then secondly I need either the `IdToken` for all transactional calls on my Web API so the API knows the user's roles, or I need the second `AccessToken` such that my Web API can call Graph API to make changes in the Application Roles.

What would be the correct strategy for my Web API to access these tokens and can use and manage the Application Roles?

**Comment by jmprieur** [comment]
@superman-lopez : do I understand that we answered your question? or you unblocked yourself?

**Comment by superman-lopez** [comment]
@jmprieur I am implementing your suggestion of calling Graph API to manage the application roles, so I am no longer looking to implement Role Manager as a result.  As to my last blocking, I was supported on Stackoverflow and through Azure support to solve that part.  

Thanks for your help on this!

**Comment by jmprieur** [comment]
Thanks for the update, @superman-lopez. I'm glad you're unblocked.
