### ISSUE TITLE
[Bug] Reference Assembly does not have a strong name 

### ISSUE THREAD

**Issue by cloudsere** [AzureAD/microsoft-identity-web#682]
**Which version of Microsoft Identity Web are you using?**
1.1.0

**Where is the issue?**
Referenced assembly 'Microsoft.Identity.Web.UI, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
![image](https://user-images.githubusercontent.com/9955832/96113777-8212fe00-0e99-11eb-9638-44cea404cce7.png)

* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app

**Repro**
Choose signing in solution properties
![image](https://user-images.githubusercontent.com/9955832/96113985-d1592e80-0e99-11eb-8d58-29da30a096c3.png)

**Comment by jmprieur** [comment]
@cloudsere where did you get the assembly from?

**Comment by jmprieur** [comment]
Oh I see, sorry the strong name. I get it
Thanks for the heads-up @cloudsere

**Comment by cloudsere** [comment]
Very happy to see this is fixed, you guys are great! Just wondering when the 1.2.0 version will be released, will there be any preview version~? @jmprieur

**Comment by jmprieur** [comment]
@cloudsere : we intend to release at the end of this week.
Do you have an urgent need?

**Comment by cloudsere** [comment]
I'm now working on the authentication part of my Web App, it is the basic of the whole app, so if there could be a preview version would be very helpful :) @jmprieur

**Comment by bgavrilMS** [comment]
@cloudsere - as a workaround you could disable strong name validation on your dev box: 

`sn.exe -Vr *`
from a Developer Command Prompt for VS201* (probably with Admin rights). 

Note that strong naming is not a security feature, doesn't protect against code tampering, and many .NET projects don't even bother anymore. Code signing is the security feature.

**Comment by jmprieur** [comment]
Or just sn.exe -Vr for the DLL?

**Comment by bgavrilMS** [comment]
Another workaround is to add a refrence to https://www.nuget.org/packages/StrongNamer/. We do this in unit tests, to overcome the fact that many .NET DLLs are not strong named.

**Comment by cloudsere** [comment]
Will try both methods, thanks you guys @bgavrilMS @jmprieur ! Looking forward to 1.2.0 this week :)

**Comment by jennyf19** [comment]
@cloudsere Included in [1.2.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.2.0).
