### ISSUE TITLE
[Feature Request] IDownstreamApi should process www-Authenticate headers automatically (CAE)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#685]
**Is your feature request related to a problem? Please describe.**
Web APIs can reply to clients with a Www-Authenticate header (by calling [ReplyForbiddenWithWwwAuthenticateHeaderAsync](https://github.com/AzureAD/microsoft-identity-web/blob/60fe9f7d99ff3296a15eebf835d264ac501d2118/src/Microsoft.Identity.Web/TokenAcquisition.cs#L350)

Web apps (or web APIs calling that web API) should check it, and relay (in the case of a web api), or request incremental consent / conditional access (in the case of a web app) before retrying.

**Comment by jmprieur** [comment]
## Why? / What?
When a web API tries to acquire a token it can get a UiRequiredException this could be:
- the need for more claims (for example perform 2FA), in that case this can be forwarded back to the client so that the user provides more claims
- the need for the user and an admin to consent for the web API to call a downstream API. In the case of multi-tenant web APIs, the recommendation to ISVs is:
  - either to have the tenant admins install the web API (really create a service principle) and admin consent for the web API to call downstream APIs
  - or have the ISV provide a sign-up mechanism in the web API as a static page which really means having the tenant admin to admin consent to the web API being installed in their tenant (the service principal created), and this web API to call downstream web APIs. This is illustrated in the Web API incremental tutorial, where the web API generates a wwwAuthenticate header in [TodoListController ](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListService/Controllers/TodoListController.cs#L60) and the wwwAuthenticate header is processed in the TodoList client  [here](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/157f26bfb70c4171a8afc232eaeb23b102b5dd9a/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListClient/MainWindow.xaml.cs#L143-L145)

The idea of this feature is that given Microsoft.Identity.Web provides the IDownstreamApi which could receive a wwwAuthenticate header, it would process it by
- challenging the user if more claims are needed
- in the other cases provides the information (for instance as an exception) so that the application can display information to the user telling them that they need to consent to the web API, with the link.

ADAL.NET also used to have a class named [AuthenticationParameters](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/e85e0bbe2443d8caffb50b92f8b68fe94c4527df/src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationParameters.cs) which could retrieve from an wwwAuthenticate header the authorization uri (which will build-up the authority), and the resource_id (which would build-up the scopes as {resource_id}/.default.

We should also try to surface this.

and needs to propagate it back to its client so that the user can provide more claims or consent for more scopes  

The same requests comes to MSAL.NET to surface something like this.

**Comment by jmprieur** [comment]
Note that the claims challenges could URL encode or not the claims.
Azure AD only understand the non-encoded (plain JSon) format.

**Comment by jennyf19** [comment]
Needs to be re-tested, as CAE might be working now.

**Comment by jennyf19** [comment]
fixed in latest version v.3.4+
