### ISSUE TITLE
Is it posible to add additional QueryParameters when using Authentication.Challenge [Question] 

### ISSUE THREAD

**Issue by gavinbarron** [AzureAD/microsoft-identity-web#687]
When using MSAL.js I am able to send additional query string parameters to the identity provider using `extraQueryParameters` when calling loginRedirect.
I now need to do this in the context of an ASP.NET MVC application and cannot work out how to add extra query string parameters to the url used when creating the challenge.

If I cannot add the extra param the AzureB2C tenant that I am required to use will not accept the request and fails. Likely the provider here could/should fix this but we've been able to make this work for our SPA applications and it's frustrating me not to find a solution for a webApp

Current code:
```
var extraParams = new Dictionary<string, string>{{"customParam", "value"}};
var authProps = new AuthenticationProperties(extraParams) { RedirectUri = "/" };
HttpContext.GetOwinContext().Authentication.Challenge(authProps);
```

It looks like the extraParams are getting encoded up in the state rather than adding extra parameters to the query string

**Comment by bgavrilMS** [comment]
Microsoft.Identity.Web might have a better idea.. transferring issue

**Comment by jmprieur** [comment]
@gavinbarron : are you interested in ASP.NET ? or ASP.NET Core?
If this is a new app, I strongly recommend ASP.NET Core (with Microsoft.Identity.Web)

**Comment by gavinbarron** [comment]
Unfortunately it's porting an existing ASP.NET MVC application to a modern identity provider and upgrading it to netcore is not on the cards at this point in time.
So .NET Framework 4.7 ASP.NET MVC is the code stack.

**Comment by jmprieur** [comment]
It's not a Microsoft.Identity.Web question, however, let me try to help here. I'm taking this sample as a basis:
https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect/blob/master/WebApp/App_Start/Startup.Auth.c

In the `app.UseOpenIdConnectAuthentication()` method, add a notication for the `RedirectToIdentityProvider` event:
https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect/blob/3b518e3ab80cc3c002fd260eca4b8e82e0cd1365/WebApp/App_Start/Startup.Auth.cs#L58

```CSharp
              Notifications = new OpenIdConnectAuthenticationNotifications()
                    {
                        AuthorizationCodeReceived = OnAuthorizationCodeReceived,
                        AuthenticationFailed = OnAuthenticationFailed,
                        RedirectToIdentityProvider = OnRedirectToIdentityProvider,
                    },
```

with 

```CSharp
        private  Task OnRedirectToIdentityProvider(RedirectToIdentityProviderNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> arg)
        {
            arg.ProtocolMessage.SetParameter("myNewParameter", "its Value");
            return Task.CompletedTask;
        }
```

You probably want to do it condionnally.

HTH

**Comment by jmprieur** [comment]
Closing as I believe this is answered. Feel free to reopen if you disagree, @gavinbarron

**Comment by gavinbarron** [comment]
Thanks so much for this, it was exactly what we needed to unblock us :)
