### ISSUE TITLE
[Documentation] about token cache serialization

### ISSUE THREAD

**Issue by dawid1** [AzureAD/microsoft-identity-web#688]
### Please check those that apply
MSAL.NET
- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
Could you provide more clarifications to the text on page https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization:
`"A very important thing to remember is that for Web Apps and Web APIs, there should be one token cache per user (per account). You need to serialize the token cache for each account."`

I'm using Cosmos DB and asp.net core 3.1 api and i have several entries for a user. Don't have any customization just have AddDistributedTokenCaches() and later on AddComosCache in my startup.cs.
Could you provide a sample for asp .net web api core which subscribes to the cache serialization events please.

Thank you

**Comment by jmprieur** [comment]
@dawid1 : do you think you need more than : https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization#distributed-token-cache ?

**Comment by jmprieur** [comment]
@dawid1 @jennyf19 @bgavrilMS @trwalke @neha-bhargava @henrik-me I've also updated  https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization:

I need to plan to do a refresh wave of docs.ms from the wiki

**Comment by jmprieur** [comment]
@dawid1 proposing to close. Feel free to reopen if you disagree
