### ISSUE TITLE
TokenDecryptionCertificates info

### ISSUE THREAD

**Issue by damienbod** [AzureAD/microsoft-identity-web#692]
### Documentation related to component

I was exploring the Micosoft.Identity.Web code.

How is the **TokenDecryptionCertificates** used in the Micosoft.Identity.Web lib and what does it change in my tokens, flows?

Maybe a note or an example might be useful in the docs

Greetings Damien

**Comment by jmprieur** [comment]
@damienbod 
I need to write a full page, but the principle is:
- in the Web API registration you add a Decrypt certificate, (you share the public key with Azure AD), and only you app has the private. This is in the web API registration as of course access tokens are for the web API which decides of its format.
- still in the app registration you direct Azure AD to encrypt the tokens with that decrypt certificate
- when the client receives the access token it's encrypted (so it cannot crack open it)
- when the web API receives the access token from the client, it uses the decrypt certificate, and the rest is the same as usual

**Comment by jennyf19** [comment]
@damienbod Here is the documentation with how to set this up and more information -> https://github.com/AzureAD/microsoft-identity-web/wiki/Token-Decryption

there are code snippets on the page. 
going to close this issue, but feel free to reopen or tag me w/questions.

**Comment by damienbod** [comment]
@jennyf19 Docs are really good, thanks

I also made a blog about this.

https://damienbod.com/2020/10/22/using-encrypted-access-tokens-in-azure-with-microsoft-identity-web-and-azure-app-registrations/

One small improvement suggestion to the docs:

## Generate the certificate

I would add **Generate Certificate in Azure Key Vault** before this section as I think this is the standard way.

Then download the public cer file to add to the App registration. 

Greetings Damien

**Comment by jmprieur** [comment]
@jennyf19:
Do you want to please update the wiki to add a section on how to generate certificate in KeyVault?

**Comment by jennyf19** [comment]
Thanks @damienbod

**Comment by shobhitvaish** [comment]
@jmprieur Does this library supports token encryption while using client credentials flow?

**Comment by jmprieur** [comment]
Yes, the library supports decrypting tokens for every flow.
It doesn't require any special SKU of Azure AD. But if you want to use KeyVault, you'll need an Azure subscription.
See https://github.com/AzureAD/microsoft-identity-web/wiki/Token-Decryption

**Comment by shobhitvaish** [comment]
@jmprieur Thank you for your response!

1. I have registered an application in Azure AD and exposed it as an API. I added a self-signed certificate by following these steps: https://github.com/AzureAD/microsoft-identity-web/wiki/Token-Decryption#in-the-azure-ad-portal
![image](https://user-images.githubusercontent.com/24998910/166297391-2329c1a6-9057-4db6-aa0f-d3a2eb1da4ec.png)

2. Clients(registered Azure AD apps) of the API are in the same tenant and will access the API using the client credentials flow. I have added the API in the API permissions. 
![image](https://user-images.githubusercontent.com/24998910/166298120-c5e008d8-01c2-451b-bc07-debe11ed4223.png)

**I am requesting API token using the client id and client secret of the client apps. However, I am not getting an encrypted token. Please guide what I am missing?**
