### ISSUE TITLE
[Fundamentals] Add SonarCloud analysis to a Microsoft.Identity.Web CI build

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#693]
**Is your feature request related to a problem? Please describe.**
Be able to understand the security issues, the coverage etc ... on new or changed code

**Describe the solution you'd like**
Add SonarCloud analysis to a CI build (to be determined)

**Additional context**
See also https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/pull/104, for MSAL.NET

**Comment by jennyf19** [comment]
Related PRs:
https://github.com/AzureAD/microsoft-identity-web/pull/740
https://github.com/AzureAD/microsoft-identity-web/pull/739

**Comment by jennyf19** [comment]
still working on this.
