### ISSUE TITLE
Stop using Animated Images in documentation

### ISSUE THREAD

**Issue by mikerains** [AzureAD/microsoft-identity-web#694]
Please just put the images in sequence in the document and let users scroll.  The animated images collections of screen images forces the user to try to remember, and the arbitrary paces of flipping through the images denies the reader the ability to analyze and understand the source code.  If there is some other tool needed to work with the images, please indicate that in a caption below each animated image, as this is not a widely-adopted approach.

**Comment by jmprieur** [comment]
@jennyf19, let's discuss about this.
cc: @SaeedAkhter-MSFT FYI

**Comment by jmprieur** [comment]
Commented out the image and it's comment.
