### ISSUE TITLE
[Feature Request] When EasyAuth is activated, but not the AAD provider, throw a meaningful exception

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#702]
**Is your feature request related to a problem? Please describe.**
The EasyAuth integration works only if EasyAuth is activated, and for AAD

![image](https://user-images.githubusercontent.com/13203188/96644404-4e1c5a80-1329-11eb-88c3-dc4d5d753e59.png)

**Describe the solution you'd like**
When it's activated, but not for AAD, we could throw a meaningful exception.

@jennyf19's idea.

**Comment by jennyf19** [comment]
proposing to close. let's revisit if we have customers hitting this.
