### ISSUE TITLE
[Feature Request] Enable web APIs called by daemon apps to control tokens without roles claim

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#707]
## Why?
**Is your feature request related to a problem? Please describe.**
Microsoft.Identity.Web enforces that a token has scopes (for delegated permissions) or roles (when called by daemon apps), however there is another mechanism: the ACL-based authorization pattern to [control tokens without roles claim](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#controlling-tokens-without-the-roles-claim). 

**Describe the solution you'd like**
Have a way to specify that the application can bypass the following test, to support the ACL-based authorization for the web API called by daemons:

https://github.com/AzureAD/microsoft-identity-web/blob/158636e31b9b438c631659736ec32627c7b76e90/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs#L222-L229

**Describe alternatives you've considered**
None. See the discussion here: https://github.com/AzureAD/microsoft-identity-web/issues/691

## Proposed design:
- Add a new `bool` property named `AllowWebApiToBeAuthorizedByACL` in the `MicrosoftIdentityOptions`, which would be false by default.
- If this property is true, then avoid throwing in https://github.com/AzureAD/microsoft-identity-web/blob/158636e31b9b438c631659736ec32627c7b76e90/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs#L222-L229

**Comment by jmprieur** [comment]
@jennyf19 @TaranbirBhullar

**Comment by jmprieur** [comment]
Thanks @TaranbirBhullar for confirming that this works for you.

**Comment by jennyf19** [comment]
Included in [1.2.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.2.0).
