### ISSUE TITLE
[Feature Request] When EasyAuth returns a non-usable token, throw an exception with an aka.ms to the new tutorial

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#712]
**Is your feature request related to a problem? Please describe.**
When you deploy your app to App Services and enable App Services Authentication, and then want to call the graph, you first need to configure App Service to return a usable access token.
Ryan has been writing a new tutorial. See https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=command-line#configure-app-service-to-return-a-usable-access-token

If this is not done MicrosoftGraph will return an exception, when calling the web API, saying that the compact token's format is wrong. l.

**Describe the solution you'd like**
We could detect this exception in:
- IDownstreamApi
- GraphServiceClient (work with @darrelmiller to understand how to add a Graph SDK middleware for this)

And then throw a more meaningful exception pointing to the tutoria

**Describe alternatives you've considered**
Just document it.

cc: @henrik-me @mmacy @navyasric FYI

**Comment by jmprieur** [comment]
@jennyf19 : nobody complains. Moving it away of 1.3.1.

**Comment by jennyf19** [comment]
closing
