### ISSUE TITLE
[Bug] .Net 5 RC2 - no runtime package error

### ISSUE THREAD

**Issue by Satukan** [AzureAD/microsoft-identity-web#717]
Hello,

I would like to try out the package on .Net 5 RC2 (latest SDK) with a Blazor Wasm application, but I can see the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.	....	C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	387	

Without the package the app is running well.

Following the nuget description it should support .Net 5.
I think one of the dependency causes the error, but I am just guessing.

Can you please check it and give me feedback?

**Comment by jmprieur** [comment]
@Satukan 
How did you create your project?

The reason I ask is that Microsoft.Identity.Web templates are released with .NET 5 (from Preview 7), and there are subtle differences in Blazor. 
If you want to use Microsoft.Identity.Web with .NET 5.0, just use the normal **dotnet new** commands (for instance `dotnet new blazorwasm`, instead of `dotnet new blazorwasm2` if you were using netcoreapp3.1)

**Comment by Satukan** [comment]
Hi  jmprieur,

The project wasn't created by me, I just continue to working with.
Initially it was a Blazor Wasm .Net Core hosted web app. Based on .Net Core 3.1.
I am trying out the .Net 5 RC2 because the app uses AAD B2C and I need to set the ProviderOptions.LoginMode="redirect" in the AAD options to avoid popups.
This is the main reason that the framework is switch to .Net 5 RC2 and I am trying to use the Microsoft.Identity.Web on top of it.

Do you know, that this package supports the option: ProviderOptions.LoginMode="redirect"?
In this case I  could remove and replace with the Microsoft.Authentication.WebAssembly.Msal package completely and go back to .Net Core 3.1 / .Net Standard 2.1.
What do you think?

**Comment by jmprieur** [comment]
@javiercn: what would you recommend? (we know Microsoft.Identity.Web works with RC2, but the app has changed a bit)

**Comment by javiercn** [comment]
@Satukan I would recommend you scaffold a new project based on 5.0 and compare the differences with your own project and follow the migration instructions to migrate to Microsoft.Identity.Web (I'm not sure where they are if they exist).

Note that `Microsoft.Identity.Web` is for your ASP.NET Core applications, for the client part of the Blazor Webassembly you need to use `Microsoft.Authentication.WebAssembly.Msal`

@jmprieur maybe we need to clarify on the docs when `Microsoft.Identity.Web` and `Microsoft.Authentication.WebAssembly.Msal` apply

**Comment by Satukan** [comment]
Alright, thank you.
I try to review the migration steps again, maybe I missed anything.
