### ISSUE TITLE
[Documentation]  Create a document describing how microsoft-identity-web fits into the existing landscape

### ISSUE THREAD

**Issue by JoeMarkov** [AzureAD/microsoft-identity-web#724]
### Documentation related to component

As a developer familar with IdentityServer, OAuth, ASP.NET core, I am a bit confused where microsoft-identity-web fit into the big picure architecture wise.

I would like to see an a addition to the documentation that explains on a high-level where microsoft-identity-web fits into the big picture for ASP.NET Core developers.

That anwers questions like:

* Is microsoft-identity-web a replacement for these method calls? 
  .AddJwtBearer(...)
  .AddCookie(...)
. AddOpenIdConnect(...)

* What is the pros and cons compared to the above methods? 
* Is microsoft-identity-web a replacement for the above methods?

* What about ASP.NET Identity? How does microsoft-identity-web relate here?

* What about IdentityServer? How does microsoft-identity-web relate here? Does it work with non-Azure AD providers? 

* What is the relationship with the MSAL library?

### Please check all that apply

- [ ] typo
- [X] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

**Comment by jmprieur** [comment]
@JoeMarkov. Thanks for your feedback. 
Don't the following articles answer some of your questions? 
- https://github.com/AzureAD/microsoft-identity-web/wiki/Microsoft-Identity-Web-basics
- https://github.com/AzureAD/microsoft-identity-web/wiki/1.0.0

Would you suggest we do more? (maybe add ASP.NET Identity). Where would you want to find this document?

**Comment by JoeMarkov** [comment]
Somewhat, but honestly not really. I think I do get what it is aiming at, is that I would like 
to see it in a more explicit an concreate way, so I don’t spend time on a dead-end.

So, perhaps what I am looking for is a FAQ that brings up the questions that I have, as a way to confirm my assumptions about the library.


Questions, then become:

* Is microsoft-identity-web a replacement for these method calls? .AddJwtBearer(...) .AddCookie(...) . AddOpenIdConnect(...)

* What is the pros and cons compared to the above methods?

* What about ASP.NET Identity? How does microsoft-identity-web relate here?

* What about IdentityServer? How does microsoft-identity-web relate here? 

* Does it work with non-Azure AD providers? Auth0, Octa, Ping...

* What is the relationship with the MSAL library?

**Comment by JoeMarkov** [comment]
Also, perhaps a good topic to talk about in the 425show  :-)

**Comment by jmprieur** [comment]
@JoeMarkov 

Microsoft.Identity.Web is a simpler way to use Azure AD in ASP.NET Core web apps and web APIs. It doesn't replace ASP.NET Identity in any way, it doesn't replace AddJwtBearer or AddCookie or any of the lower level primitives, but it does use and configure them correctly for Azure AD. It doesn't work with non-Azure identity providers.
It replaces AzureAD.UI and AzureADB2C.UI which are obsolete in .NET 5.0
