### ISSUE TITLE
[Bug] Consent is required when requesting explicit Graph scopes

### ISSUE THREAD

**Issue by plamber** [AzureAD/microsoft-identity-web#726]
Hello,
I am not sure if this is a bug at all or just working like this by design. I haven't noticed this behavior before.

I am using the Microsoft.Identity.Web package in an ASP.NET Core API that is using the ITokenAcquisition interface and method GetAccessTokenForUserAsync to retrieve the token for a Microsoft Graph call. 

I have an admin consented app with following scopes:
![image](https://user-images.githubusercontent.com/18241305/97302641-a25b9900-1859-11eb-8027-fdf0b40c6946.png)

If I am calling the GetAccessTokenForUserAsync with the delegated scope "https://graph.microsoft.com/.default", I am getting back an access token without issues. If I am calling the same method by narrowing down the scopes to https://graph.microsoft.com/Groups.ReadWrite.All and https://graph.microsoft.com/User.Read.All I am getting an error message like this:
{"AADSTS65001: The user or administrator has not consented to use the application with ID '788a060f-1bfb-4ea0-a2a2-ec234dc984b0' named '....'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 0ca4b4dc-cbe8-4c6a-a1e4-850c36f2c800\r\nCorrelation ID: fafd55b0-177b-4738-9a85-09e52fef0f84\r\nTimestamp: 2020-10-27 12:31:26Z"}

My understanding is that the specific scopes Groups.ReadWrite.All and User.Read.All are both already consented. I would assume that if I am getting a token with the scope https://graph.microsoft.com/.default (which includes both scopes), calling the individual scopes shouldn't ask for a consent. Is my assumption correct?

As a sidenote. Groups.ReadWrite.All and User.Read.All are both called the same in the delegated scope and in the application scopes. Not sure if this might be the cause of the issue.

**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.2.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

c. This is a new app or an experiment.

**Repro**
- Create a SPA app with following permissions:
![image](https://user-images.githubusercontent.com/18241305/97303358-958b7500-185a-11eb-9335-d51b23b1e2e4.png)
- Grant admin consent to that app
- Authenticate the user and call the downstream api. Request the token for https://graph.microsoft.com/User.Read.All. The error will be thrown.
- Authenticate the user and call the downstream api. Request the token for https://graph.microsoft.com/.default and no error is thrown.

```csharp
var scopes = request.Scopes.Split(",");
var token = await _tokenAquisition.GetAccessTokenForUserAsync(scopes)
```

**Expected behavior**
Calling the individual scopes returns the token

**Actual behavior**
Calling the individual scopes returns "AADSTS65001"

Thank you,
Patrick

**Comment by jmprieur** [comment]
@plamber
1. it could be that this is a multi-tenant application and that the tenant admin of your home account requires you to consent? 
2. Or that AAD wants you to perform some kind of conditional access which requires you to sign-in?
3. Do you observe the same thing if you use "User.Read.All" instead of "https://graph.microsoft.com/User.Read.All"

In any case:
- Microsoft.Identity.Web itself will just return what Azure AD returns. There is nothing we can do here.
- You can let Microsoft.Identity.Web challenge the user automatically by using the AuthorizeForScopes attribute or the MicrosoftIdentityConsentAndConditionalAccessHandler class. 

For details, see: See https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

**Comment by plamber** [comment]
Hi @jmprieur,
thank you very much for your fast response.

1 and 2 can be excluded because we are talking of the same tenant in a multi-tenant application. We were just addressing the scope differently.

Your suggestion 3 finally fixed the issue. I was able to retrieve the token without exception using User.Read.All without the https://graph.microsoft.com/ domain beforehand. 

Thank you again for your feedback. 

br,
Patrick
