### ISSUE TITLE
GetAccessTokenForUserAsync - Is not working to obtain JWT Token to access Common Data Service Global Discovery Service

### ISSUE THREAD

**Issue by LKShankarKarthik** [AzureAD/microsoft-identity-web#727]
Currently Im using Version 1.2.0 in my ASP .Net Core 3.1 Web API Project which is secured with Azure AD.

**Where is the issue?**
I tried to use ITokenAcquisition.GetAccessTokenForUserAsync in order to obtain JWT Token for the current User context which can be used to access the Common Data Service(CDS) Global Discovery Web API. I used the below scope and the Tenant.

                string[] _scopes = new string[] { "https://disco.crm.dynamics.com/api/discovery" };
                accessToken = _tokenAcquisition.GetAccessTokenForUserAsync(scopes: _scopes, tenantId: "common").Result;

But whenever its executed, it returns with exception saying the specified resource (https://disco.crm.dynamics.com/api/discovery) is not found in your tenant. Same is working with "AcquireTokenAysnc" method exposed viz Microsoft.IdentityModel.Clients.ActiveDirectory. 

Note: I tried changing the appsettings.json to have TenantId as "common" still the same problem. 

Would help if you can suggest what Im doing wrong.

Source Code:

![image](https://user-images.githubusercontent.com/36524787/97388774-a660e700-193d-11eb-86e4-94ee285548cd.png)

**Expected behavior**

Expect a valid JWT Token, with which I can invoke the Global Discovery Web API (https://globaldisco.crm.dynamics.com/).

**Actual behavior**
Currently it throws the below exception as in the image below.
![image](https://user-images.githubusercontent.com/36524787/97389069-69492480-193e-11eb-85fd-0d74dc5fa5c5.png)

**Comment by jmprieur** [comment]
@LKShankarKarthik
If seems that you used as scopes, the URL to call? Are you sure of the scopes? What AppID URI did you use with ADAL?

**Comment by LKShankarKarthik** [comment]
Hi

Yes, I used it as scope based on the Microsoft documentation. For ADAL, I referred the sample to access Global Discovery Service from Microsoft link which is working perfectly fine with that Uri.

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/samples/global-discovery-service-csharp

**Comment by jmprieur** [comment]
@LKShankarKarthik : can you please try to use scope = "https://disco.crm.dynamics.com/api/discovery/.default" and the authority "organizations" instead of "common"?
See https://docs.microsoft.com/azure/active-directory/develop/msal-net-migration

**Comment by LKShankarKarthik** [comment]
@jmprieur - Sure, I tried and I still get the same error as in the image.
![image](https://user-images.githubusercontent.com/36524787/97654928-d688c100-1ac8-11eb-9ab1-2800bf8e5ef4.png)

**Comment by jmprieur** [comment]
Did the tenant admin of the tenant 7a** install the resource? (create a service principal) ?

**Comment by LKShankarKarthik** [comment]
For the below Score/resource, no its not in our AD Tenant & I dotn think its expected. ADAL API is working without it pointing to the same Tenant. 

https://disco.crm.dynamics.com/api/discovery

**Comment by jmprieur** [comment]
Why do you at all override the tenantId in the call to GetAccessTokenForUserAsync? this is not necessary: Microsoft.Identity.Web will use the tenant which is in your appsettings.json, and the effective tenant will be the one in your app registration.
Did you use the same ClientId as you used with ADAL? For instance were you using the ClientId provided in the PowerApp sample? If yes did you change the audience for your application in the app registration?

**Comment by jmprieur** [comment]
If you use common, the Microsoft.Identity.Platform endpoint will use the home tenant Id of the user. Use a tenanted authority. Are you sure that the same behavior does not happen with the same user with ADAL?

**Comment by LKShankarKarthik** [comment]
Yes the same behavior doesn't happen for ADAL methods. 
I have managed to get it work by changing the scope as below. Would have  been easier if Microsoft documentation had these details.
![image](https://user-images.githubusercontent.com/36524787/97916519-f1ed1800-1db7-11eb-9755-8918e360f323.png)

We can close this case now. Thanks for your suggestions and support on this case.

**Comment by jmprieur** [comment]
@LKShankarKarthik : 
I'm glad you self-troublehooted.

Which MIcrosoft documentation would you want to update? a dynamics one? or a Microsoft identity platform one? 

BTW, the scope (which did not seem right to me) is the first question I asked you: https://github.com/AzureAD/microsoft-identity-web/issues/727#issuecomment-717936275. I should have insisted more :)

**Comment by LKShankarKarthik** [comment]
I would see it as more logical to get this updated in the Dynamics one.

Yep I was also mislead by the Microsoft Global discovery sample, which I downloaded from official site.
