### ISSUE TITLE
AddMicrosoftIdentityUI() not working in Razor Pages

### ISSUE THREAD

**Issue by jaoord** [AzureAD/microsoft-identity-web#730]
**Which version of Microsoft Identity Web are you using?**
1.2.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)
  AddMicrosoftIdentityUI() will return 404 for https://localhost:5001/MicrosoftIdentity/Account/SignOut

**Is this a new or an existing app?**
new

**Repro**
https://github.com/jaoord/RazorPagesAzureADTest

```csharp

            services.AddRazorPages()
                .AddRazorPagesOptions(opt =>
                {
                    opt.Conventions.AuthorizeFolder("/");
                    opt.Conventions.AuthorizeAreaFolder("Admin", "/", "adminPolicy");
                })
                .AddMicrosoftIdentityUI();
```

**Expected behavior**
Navigating to /MicrosoftIdentity/Account/SignOut should sign out the user

**Actual behavior**
A 404 error is returned

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@jaoord : Microsoft.Identity.Web.UI brings a controller. I think that you are missing mapping the controller:

```CSharp
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
     // More code

     app.UseAuthentication();
     app.UseAuthorization();

     app.UseEndpoints(endpoints =>
     {
      endpoints.MapRazorPages(); // If Razor pages
      endpoints.MapControllers();
     });
    }
```

See https://github.com/AzureAD/microsoft-identity-web/wiki/Web-Apps#using-the-sign-insign-out-ui for details

**Comment by jaoord** [comment]
Thanks, that fixed it. (Didn't know there was a wiki)
