### ISSUE TITLE
[Bug] Feature for allowing a pre-configured httpClient does not appear to work in 1.2.0

### ISSUE THREAD

**Issue by mjnorman** [AzureAD/microsoft-identity-web#732]
**Which version of Microsoft Identity Web are you using?**
1.2.0

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [x] Protected web APIs (validating tokens)
    * [x] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [x] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
Production app moved to Microsoft.Identity.Web

**Repro**
According to the release notes, the below code should allow for enabling of proxy for backchannel use.  This does not appear to work, although I am not sure why.  Locally, I confirmed I can use the proxy to access content, however when the app attempts to pull in the login.microsoft.com web content, it returns a 407 as if it is not passing credentials to the proxy.

I have tried several variations of the below including configuring the uri with `username:password@host:port` but nothing seems to pass the correct proxy auth.

```csharp
                services.Configure<AadIssuerValidatorOptions>(options => { options.HttpClientName = "proxyedClient"; });

                services.AddHttpClient("proxyedClient")
                    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
                    {
                        UseProxy = true,
                        Proxy = new WebProxy()
                        {
                            Address = new Uri($"host:port"),
                            UseDefaultCredentials = false,
                            Credentials = new NetworkCredential()
                            {
                                UserName = username,
                                Password = password
                            }
                        },
                        PreAuthenticate = true //have tried with and without this
                    });
```

**Expected behavior**
backchannel should pull in the discovery json.

**Actual behavior**
407 from proxy

Reverting to the previous work around of globally enabling proxy at startup with the same proxy information works correctly.
```csharp
            System.Environment.SetEnvironmentVariable(HTTP_PROXY, proxy);
            System.Environment.SetEnvironmentVariable(HTTPS_PROXY, proxy);
```

**Comment by jennyf19** [comment]
@mjnorman What value are you using here? Is it a valid URI?
```
Address = new Uri($"host:port"),
```

**Comment by mjnorman** [comment]
That is correct.  Also confirmed it by using it to curl outside of this environment and app.

**Comment by mjnorman** [comment]
To clarify, I redacted the url for privacy, but did confirm it resolves to a known good url at runtime, and as mentioned above, used it outside of the app to confirm.

**Comment by jennyf19** [comment]
@mjnorman Is this repro'ing only with the HttpClient?

**Comment by mjnorman** [comment]
I'm not sure I follow the question, can you elaborate?

**Comment by jennyf19** [comment]
Can you repro it with a console app with your custom proxy settings and a new HttpClient? We are thinking of sending this to the HttpClient owners to take a look.

**Comment by mjnorman** [comment]
I can do that just keep in mind that I won't be able to provide any proxy information as it is only usable from inside our company footprint.

**Comment by jennyf19** [comment]
yes, understood...thanks so much.

**Comment by mjnorman** [comment]
Repro located here just plug in your proxy uri and credentials into appsettings.json.  I used the mvc2 template instead of a console app.  If this is not sufficient let me know.  Thanks.

https://github.com/mjnorman/identity-web-proxy-repro

**Comment by jennyf19** [comment]
Thanks @mjnorman you could repro it w/your proxy settings and this repro?

**Comment by mjnorman** [comment]
Yes.

**Comment by jennyf19** [comment]
Thanks @mjnorman - I opened an issue w/dotnet, so we'll keep an eye on it. Will mark this one as "external" for now.

cc: @jmprieur

**Comment by jennyf19** [comment]
closing, seems to answered in the linked issue. if not, please reopen.
