### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by amirtezgalinew** [AzureAD/microsoft-identity-web#736]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [x] Protected web APIs (validating tokens)
    * [x] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [x] In-memory caches
     * [x] Session caches
     * [x] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by amirtezgalinew** [comment]
![SharedScreenshot1](https://user-images.githubusercontent.com/48028630/97793660-36a46380-1bac-11eb-9ed7-8369227b5bf5.jpg)

**Comment by jennyf19** [comment]
closing until we have more information. Feel free to reopen @amirtezgalinew
