### ISSUE TITLE
[Feature Request] ASP.NET MVC users can leverage Microsoft.Identity.Web's Token cache serializers

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#741]
**Is your feature request related to a problem? Please describe.**
As developer move from ADAL to MSAL it's important to help them with token caching.
In ASP.NET Core, Microsoft.Identity.Web provides [token cache adapters/serializers]() but ASP.NET MVC developers are on their own. 

**Describe the solution you'd like**
- P1: Expose the token cache adapters for Memory and IDistributedCache to a new target framework (.NET 4.7.2, at least 4.6.1)
- P2: Expose other classes that could be interesting, such as the certificate management, the ClaimsPrincipalExtension, and possibly the issuer validation.

**Describe alternatives you've considered**
Have the token cache in MSAL.NET, but currently the required target framework are not supported

**Additional context**

-	The classes in red depend on ASP.NET Core and therefore we cannot take them as is in .NET Framework. They are the classes that will require efforts if we wanted to bring them to ASP.NET developers
-	The classes in blue don’t have a (direct) dependency on ASP.NET Core. Unless they depend on a red class (follow the arrows), we can expose them, therefore producing value to customers, in particular:
o	Support for certificates
o	Possibly the issuer validation.

![image](https://user-images.githubusercontent.com/13203188/97989211-81a5bd00-1dde-11eb-919f-9ea174be9311.png)

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-identity-web/pull/737

**Comment by jennyf19** [comment]
In [1.3.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.3.0)
