### ISSUE TITLE
The sample "dotnet new webapi2 --auth SingleAuth" is not working. [Bug] 

### ISSUE THREAD

**Issue by xavierjohn** [AzureAD/microsoft-identity-web#748]
"Microsoft.Identity.Web" Version="1.2.0"

**The sample  code generation is not working. dotnet new webapi2 --auth SingleAuth **
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

**Repro**
dotnet new webapi2 --auth SingleAuth
give error:
C:\Temp>dotnet new webapi2 --auth SingleAuth
Couldn't find an installed template that matches the input, searching online for one that does...
No templates found matching: 'webapi2'.

```csharp
var your = (code) => here;
```

**Expected behavior**
Sample code to be generated with Unit tests.

**Actual behavior**
Error:
"Couldn't find an installed template that matches the input, searching online for one that does...
No templates found matching: 'webapi2'."

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jennyf19** [comment]
@xavierjohn did you see this? https://github.com/AzureAD/microsoft-identity-web/wiki/web-api-template

**Comment by xavierjohn** [comment]
That worked. Thanks.
