### ISSUE TITLE
[Bug] ClaimActions not being invoked

### ISSUE THREAD

**Issue by tonytilbo** [AzureAD/microsoft-identity-web#749]
**Which version of Microsoft Identity Web are you using?**
E.g. Microsoft Identity Web 1.2.0

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)
This is a new app or an experiment.

**Repro**
We are attempting to use a custom ClaimAction that will do some additional mapping of JWT claims to custom claims on the identity.

```csharp
public class CustomClaimAction : ClaimAction
{
	public CustomClaimAction(string claimType, string valueType): base (claimType, valueType) { }
        public override void Run(JsonElement userData, ClaimsIdentity identity, string issuer) 
                                  => throw new System.NotImplementedException();
}

services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
  .AddMicrosoftIdentityWebApi(jwt => { }, options =>
  {
      options.TenantId = Configuration["AzureAd:TenantId"];
      options.ClientId = Configuration["AzureAd:ClientId"];
      options.Domain = Configuration["AzureAd:Domain"];
      options.Instance = Configuration["AzureAd:Instance"];

       options.ClaimActions.Add(new CustomClaimAction (ClaimTypes.Role, ClaimValueTypes.String));
 });
```

**Expected behavior**
I expect the Run method of the CustomClaimAction to be invoked.

**Actual behavior**
Method is not called.

**Comment by jmprieur** [comment]
@tonytilbo thanks for the heads-up.

This property is normally an OpenIdConnect property (for a web app, and acting on the IDToken claims), whereas here you have a web API, but indeed, given it's surfaced in MicrosoftIdentityOptions, we should probably make it work for the Access token claims as well.

Out of curiosity, what is your scenario? what are you trying to achieve?

**Comment by tonytilbo** [comment]
We are looking to check for "groups" claims in the incoming access token and maps these based on some external configuration to a set of roles which would be added to the ClaimsIdentity so we can manage access to the API used role based authorization.

**Comment by jmprieur** [comment]
@tonytilbo. Thanks for the update.
Alternatively, until we get this working, you could have a look at this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/7cfdb74dc595a04d95e351c8037a9433fccee0c7/5-WebApp-AuthZ/5-2-Groups/Startup.cs#L51.

**Comment by tonytilbo** [comment]
Thanks, will take a look.

**Comment by gunnim** [comment]
@jmprieur afaics MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions is not mapping the configured claims here

https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L299

**Comment by warrenbuckley** [comment]
Any update on this @jmprieur or @jennyf19 please ?

**Comment by jmprieur** [comment]
Fixed
