### ISSUE TITLE
B2C Error AADB2C99059 when attempting to edit profile or change password

### ISSUE THREAD

**Issue by xavier-90** [AzureAD/microsoft-identity-web#751]
I have started to consistently get an error when attempting to either edit my profile or change my password:

`AADB2C99059: The supplied request must present a code_challenge`

This issue (I guess) relates to this one https://github.com/MicrosoftDocs/azure-docs/issues/64073 

Is there a solution / workaround when using the Microsoft.Identity.Web library?

#### B2C Configuration
- Single-page application
- `https://myserver/signin-oidc`
- Access tokens `enabled`
- ID tokens `disabled`
- Allow public client flows `No`
#### User flows
- `Profile editing (Recommended), Conditional Mfa`
- `Password reset (Recommended), Conditional Mfa`
- `Sign up and sign in (Recommended), Conditional Mfa`
#### Conditional Access Policy
- Sign-In Policy (_All Users, 1 App, Sign-in risk = High, Medium, Low, Any device, Any location, Grant access_)
#### using...
- `Microsoft.Identity.Web 1.2.0`
- `Microsoft.Identity.Web.UI 1.2.0`
- `Microsoft.Graph 3.19.0`
#### Startup:
```
services.Configure<CookiePolicyOptions>(options =>
{
    // This lambda determines whether user consent for non-essential cookies is needed for a given request.
    options.CheckConsentNeeded = context => true;
    options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
    // Handling SameSite cookie according to https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1
    options.HandleSameSiteCookieCompatibility();
});
services.AddOptions();
// Configuration to sign-in users with Azure AD B2C
services.AddMicrosoftIdentityWebAppAuthentication(configuration, "AzureAdB2C");
services.AddControllersWithViews()
    .AddMicrosoftIdentityUI();
services
    .AddRazorPages();
// Add MVC / API services
services
    .AddMvc()
    // Make sure the property name cases are not changed by setting a new ContractResolver with a NamingStrategy to null
    .AddNewtonsoftJson(options =>
    {
        //options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
        options.SerializerSettings.ContractResolver = new DefaultContractResolver { NamingStrategy = null };
    });
```
#### appsettings.json:
```
"AzureAdB2C": {
  "Instance": "https://myinstance.b2clogin.com",
  "TenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "ClientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "ClientSecret": "xxxxxxxxxxxxxxxxxxx",
  "Domain": "myinstance.onmicrosoft.com",
  "SignUpSignInPolicyId": "b2c_1_susi",
  "ResetPasswordPolicyId": "b2c_1_pr",
  "EditProfilePolicyId": "b2c_1_pe"
},
```

**Comment by jennyf19** [comment]
@xavier-90 in the B2C app registration, you should use a web redirect URL and not a SPA redirect URL.

**Comment by xavier-90** [comment]
Thank you for your advice. It now works but...

I am getting an error when returning to my server:

`AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1_SUSI and Expected Value : B2C_1_PE
`

My guess is that this relates to the following issue?
https://github.com/AzureAD/microsoft-identity-web/issues/729

PS: Thank you for this library!

**Comment by jmprieur** [comment]
Thanks for the update, @xavier-90. Yes it's certainly related to that error.
