### ISSUE TITLE
[Bug] Signout doesn't clear the session

### ISSUE THREAD

**Issue by JiwanMS** [AzureAD/microsoft-identity-web#755]
**Which version of Microsoft Identity Web are you using?**
1.2.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users and call web APIs
The session is not cleared on signout. Old browser cookies never expire and can be used to access application even after signout. The cookie basically never expires.

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft Identity Web.

**Repro**

```csharp
var azureServiceTokenProvider = new AzureServiceTokenProvider();
            var keyVaultClient = new KeyVaultClient(
                new KeyVaultClient.AuthenticationCallback(
                    azureServiceTokenProvider.KeyVaultTokenCallback));

            var storageAccount = CloudStorageAccount.Parse(configuration["Settings:StorageConnectionString"]);
            var keyVaultName = configuration["Settings:VaultName"];

            services.AddDataProtection()
                .SetApplicationName("My_WebApp")
                .ProtectKeysWithAzureKeyVault(keyVaultClient, $"https://{keyVaultName}.vault.azure.net/keys/dataprotection")
                .PersistKeysToAzureBlobStorage(storageAccount, "/dataprotectionkeys/keys.xml");

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                       .AddMicrosoftIdentityWebApp(configuration)
                       .EnableTokenAcquisitionToCallDownstreamApi(new[] { configuration[MyApiScope], configuration[GraphApiScope] })
                       .AddMicrosoftGraph(configuration.GetSection("GraphApi"))
                       .AddDownstreamWebApi("MyApi", configuration.GetSection("MyApi"))
                       .AddDistributedTokenCaches();

            services.AddRedisTokenCaches(redisConnectionString, "Token"); // We have overridden IMsalTokenCacheProvider to use with data protection.
```

**Expected behavior**
On SignOut, the session should be cleared. The user should not be able to use old cookies to get access.

**Actual behavior**
The cookie never expires and we are able to access the application with an old cookie.

**Possible solution**

**Additional context / logs / screenshots**
I have tried by setting options to expire sessions but that doesn't work either.

**Comment by jmprieur** [comment]
@JiwanMS : is this a regression?
Do you see this as well in an in-private / icognito browser? or only on your corporate network?

**Comment by JiwanMS** [comment]
@jmprieur Yes, this is happening in incognito browser also. We saw the below issue and implemented a server-side Ticket store. The cookies are now invalidated on sign-out after this change. However, I was under the impression that global sign-out will handle this case. Let me know if I am missing something.

https://github.com/dotnet/aspnetcore/issues/7737

**Comment by jmprieur** [comment]
@JiwanMS : I would have thought the same.
@hpsin, what would you think?

**Comment by hpsin** [comment]
I am not familiar with how Identity Web handles front channel logout. The sign out in AAD uses the OIDC standard front channel logout to send a request to your logout url, at which point your code must erase the cookies. I assume Identity Web does that for you, but don't see a reference to that being handled in the code above.

**Comment by jmprieur** [comment]
Microsoft.Identity.Web just lets ASP.NET Core trigger the global signout, and subscribes to the global signout event to remove the token from the cache

**Comment by JiwanMS** [comment]
The problem is not with erasing cookies. If the cookie was stolen before sign out, then it should not work after the user has signed out. Even though the cache is cleared on sign-out, you can still use an old cookie and the call goes through. The ITokenAcquization.GetAccessTokenForUserAsync() returns a token for API call even if the distributed cache(Redis in our case) is empty. Below are the steps I have tried.

1. Scenario is Web App calls protected Web API
2. Log in redirects to AD and after successful login Web app calls Web API
3. Go to the browser and copy the details for a call, copy all headers including cookies
4. Make a call using Fiddler/Postman using the above info. This call is successful since the user is logged in.
5. Signout from Web App, The token cache is cleared in this case.
6. Make a call using fiddler with the information captured in step 3, this call still goes through and the ITokenAcquization returns a token for the backend API call. I am not sure how this token is obtained.

Ideally, after logging out the ITokenAcquization should throw a MsalUiRequired exception since there is no token in the cache.

**Comment by hpsin** [comment]
Yes, if you restore the cookie set on login.mso.com, then the login page thinks you still have a session and issues tokens appropriately.  This is not an attack that applications can prevent, and it implies a significant level of control over the network or device. We are investing in cookie binding and some server side state to protect against this attack. 

This is a valid, well-known attack against login systems like AAD that are stateless - if you save the state and replay it against AAD, we issue a token. The requirements to pull off the attack are significant though, and beyond the scope of this SDK.  

I'd recommend closing this out unless you have additional questions.

**Comment by JiwanMS** [comment]
Thanks, @hpsin, I'll close the issue. Is there any documentation that shows this is a known issue with AAD?
