### ISSUE TITLE
[Documentation]  Custom SignedOut page

### ISSUE THREAD

**Issue by shanemikel** [AzureAD/microsoft-identity-web#758]
### Documentation related to component

Microsoft.Identity.Web.UI

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [x] needs an example

### Description of the issue

I'm working on a Blazor Server app using AzureAD and Microsoft.Identity.Web.UI for AuthN & AuthZ.  The Identity UI is implemented with MVC, which doesn't play nicely with Blazor.  In particular, it doesn't work with my site layout page and navigation components (`_Host.cshtml` and `MainLayout.razor`).

I'm looking for an example of how to implement a custom SignedOut page to replace `/MicrosoftIdentity/Account/SignedOut`.

**Comment by jmprieur** [comment]
@shanemikel : did you read this article: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#override-views-partial-views-and-pages ?

**Comment by shanemikel** [comment]
I just looked through it.  Could you help me out here?  I'm not familiar with MVC, so I'd rather make a Razor Page if possible.  I added an `Areas/MicrosoftIdentity/Account/Pages/SignedOut.cshtml` file, but it doesn't work.  I also tried making a page in my app `Pages` folder with `@page '/MicrosoftIdentity/Account/SignedOut`.  Also no luck.

**Comment by ThatMouse** [comment]
@shanemikel I just tried the same thing and cannot override it. I've yet to find any examples of creating a logout page. I happen to be using Blazor server. The old AspNetCore.Authentication library required doing something similar though.

**Comment by shanemikel** [comment]
Ahh, thanks @ThatMouse, indeed it is /Areas/MicrosoftIdentity/Pages/Account/SignedOut.cshtml ... Thank you!

**Comment by jennyf19** [comment]
added to our [documentation](https://github.com/AzureAD/microsoft-identity-web/wiki/Customization#ui-customization)

**Comment by sven5** [comment]
Could you elaborate how to do this in a Blazor Server app?

**Comment by jmprieur** [comment]
@javiercn, would you please know?

**Comment by munkii** [comment]
@jennyf19 @shanemikel I've tried overriding SignedOut.cshtml but I get a build error saying there is a conflict with the imported type Areas_MicrosoftIdentity_Pages_Account_SignedOut and my page obj\Debug\netcoreapp3.1\Razor\Areas\MicrosoftIdentity\Pages\Account\SignedOut.cshtml.g.cs

Any thoughts?

**Comment by javiercn** [comment]
@munkii are you doing this in a class library instead of on your main app?

**Comment by munkii** [comment]
@jmprieur just read this SO Q&A https://stackoverflow.com/questions/59370588/the-type-some-view-conflicts-with-the-imported-type-default-view-cs0436 He pointed out that he ignored the "WARNING" so then it dawned on me that quite reasonably we have a project set to Treat ALL warnings as Errors.

If I turn that it off the overridding works. However that is not a great place position to be in.

I am not doing it in a Class Library simply in a .NET Core Web Site

**Comment by abhisheksiddhu** [comment]
@munkii That's an expected warning telling that you're overriding the provided view from the library with your view. You can safely ignore this warning in this particular scenario.

It's similar to when we try to override a non-virtual method in a derived class, it warns us that it's hiding the method from the base class and we should use the `new` keyword if the method hiding was intended. Unfortunately, we don't yet have a solution, or maybe I am not aware of a way to similarly tell the razor compiler that this override was intended.

**Comment by witheej** [comment]
I was also getting the build error, but it worked for me to just change the namespace (make sure you change it in the cshtml file AND cshtml.cs file)

**Comment by munkii** [comment]
@witheej thanks! I guess I had assumed that namespace must match too. Chnaging the namespace in the Razor file (we have no code behind) worked perfectly

**Comment by kculpepperhpc** [comment]
I added the Razor Page (that wasn't specified might I add) and it makes me log back in before displaying the page because the page doesn't allow anonymous access.  How is that done?

**Comment by jmprieur** [comment]
@kculpepperhpc : If you have an [Authorize] attribute, you'll be ask to log-in

**Comment by shangec** [comment]
Hi @witheej ,

Can you show me how to modify the namespance?

And mine is 'RPA.SOX.Web.Areas.MicrosoftIdentity.Pages.Account'.

![image](https://user-images.githubusercontent.com/52879952/118254331-8fe73b00-b4dd-11eb-873b-360ec09b5ed4.png)

**Comment by witheej** [comment]
@shangec You got it. And in `SignedOut.cshtml` you should have:

```
@page
@model RPA.SOX.Web.Areas.MicrosoftIdentity.Pages.Account.SignedOutModel
```

**Comment by shangec** [comment]
Hi @witheej ,

I followed your advice and the project also used the custom page.

But there has a strange thing, when I sign out the account, it redirect to a sign in page, the steps as follow.

1.
![image](https://user-images.githubusercontent.com/52879952/118431509-1d5aa300-b709-11eb-8366-53f6458febaf.png)

2.
![image](https://user-images.githubusercontent.com/52879952/118431521-22b7ed80-b709-11eb-8bc4-14791e3f2416.png)

3.
![image](https://user-images.githubusercontent.com/52879952/118431531-2a779200-b709-11eb-8051-c7eafb615cf3.png)

4.
![image](https://user-images.githubusercontent.com/52879952/118431549-2fd4dc80-b709-11eb-873c-45eab5fee250.png)

I'm not sure where I got it wrong in my code.  Have you ever encountered such problems?

**Comment by shangec** [comment]
Problem resolved, thanks.

**Comment by byrnesr1975** [comment]
Hi @shangec 

I'm also having the same problem as yourself, how did you resolve your problem?

**Comment by shangec** [comment]
Have you followed the steps above, and which step are you now? @byrnesr1975

**Comment by byrnesr1975** [comment]
Apologies @shangec  for not being clearer, I am experiencing the issue where when signed out, it directs you back to the sign in page, as per the 4 screen grabs you have provided. My issue is exactly the same at that point.

**Comment by shangec** [comment]
Hi @byrnesr1975 ,

![image](https://user-images.githubusercontent.com/52879952/120300312-63fdef00-c2fe-11eb-9abc-16a6ee320225.png)

This is my SignOut method, I commented out the downloaded code and customized my own logic, after signout, it redirect to another page.
![image](https://user-images.githubusercontent.com/52879952/120300832-dff83700-c2fe-11eb-87a7-9b0b788ce5f7.png)

**Comment by byrnesr1975** [comment]
Hi @shangec,

Thank you for your quick response and your help, this has set me on the right track.

I've managed to resolve my issue by adding options into the "AddRazorPage" call using the following code and placing it at the bottom of ConfigureServices in startup.cs (just in case it helps others)

services.AddRazorPages(options =>
                options.Conventions.AllowAnonymousToAreaPage("MicrosoftIdentity", "/Account/SignedOut")
);

Thanks again for your assistance and patience!

**Comment by shangec** [comment]
Ok, sounds good




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月1日(星期二) 下午5:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AzureAD/microsoft-identity-web] [Documentation]  Custom SignedOut page (#758)





 
Hi @shangec,
 
Thank you for your quick response and your help, this has set me on the right track.
 
I've managed to resolve my issue by adding options into the "AddRazorPage" call using the following code and placing it at the bottom of ConfigureServices in startup.cs (just in case it helps others)
 
services.AddRazorPages(options =&gt;
 options.Conventions.AllowAnonymousToAreaPage("MicrosoftIdentity", "/Account/SignedOut")
 );
 
Thanks again for your assistance and patience!

**Comment by jmprieur** [comment]
@byrnesr1975 : I don't understand ... this page is already anonymous?
