### ISSUE TITLE
[Bug] Switching from AzureAD.UI to Identity.Web.UI causes IDX20803 and IDX20807.

### ISSUE THREAD

**Issue by tottes200** [AzureAD/microsoft-identity-web#766]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [X] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

The app is in production and I have upgraded to a new version of Microsoft Identity Web.

**Repro**
Following the instructions on moving from AzureAD.UI to Indetity.Web.UI causes this break. I was working fine last night, this morning when I ran the code it broke. 

Code that was running last night was not altered in any way and failed to work this morning. 
```csharp
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"));
            services.AddControllersWithViews()
                .AddMicrosoftIdentityUI();

            services.AddAuthorization(options =>
            {
                options.AddPolicy(Policies.IsAdmin, Policies.IsAdminPolicy());
                options.AddPolicy(Policies.IsPm, Policies.IsPmPolicy());
                options.AddPolicy(Policies.IsUser, Policies.IsUserPolicy());
                options.AddPolicy(Policies.IsTest, Policies.IsTestPolicy());
                options.AddPolicy(Policies.IsMinimumElevated, Policies.IsMinimumElevatedPolicy());
                // By default, all incoming requests will be authorized according to the default policy
                options.FallbackPolicy = options.DefaultPolicy;
            });
```

switching to this code works just fine still, but is marked as obsolete.

```csharp
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
	.AddAzureAD(options => Configuration.Bind("AzureAd", options));

services.AddControllersWithViews(options =>
{
	var policy = new AuthorizationPolicyBuilder()
		.RequireAuthenticatedUser()
		.Build();
	options.Filters.Add(new AuthorizeFilter(policy));
});
```

**Expected behavior**
To allow me to log in.

**Actual behavior**
This is the error that I am receiving now.

![image](https://user-images.githubusercontent.com/44611315/99192480-1db9b780-2741-11eb-8f58-5b8f04eef683.png)

**Comment by jmprieur** [comment]
@tottes200, what do you have in your appsettings.json. In particular for the Instance?

**Comment by tottes200** [comment]
@jmprieur This is what I currently have in there. This as well hasn't changed. 

![image](https://user-images.githubusercontent.com/44611315/99194395-16001000-274d-11eb-96a1-29efc7c5fcb3.png)

**Comment by jmprieur** [comment]
@tottes200 : I'd suggest you remove the `Authority` line in the AzureAD section

Authority = `Instance` + tenant (for Azure AD). Here it's not right.

Also you don't need `ResponseType`, `Prompt`, `Scope`

**Comment by tottes200** [comment]
I will test that out and see if that solves the problem. Thank you.

**Comment by jmprieur** [comment]
@tottes200 proposing to close this issue, as I believe we have answered.
Of course if this still reproes for you once you've made the changes we proposed, feel free to reopen.

**Comment by tottes200** [comment]
That seems to have fixed it. Thank you for your help!!

**Comment by jmprieur** [comment]
Thanks for the update, @tottes200. I'm glad you self troubleshooted
