### ISSUE TITLE
microsoft-identity-web issue in Blazor Server side

### ISSUE THREAD

**Issue by saddamhossain** [AzureAD/microsoft-identity-web#768]
Hi, 
I am facing an issue. I am using Blazor server-side application with Azure ADB2C. Suppose I keep my B2C user flows with the domain, client id etc, and use the default template of visual studio for Blazor server-side application. When I run the project for the first time, it redirects to the Azure B2C login page but it should show the index, I mean the home page. Then if I click the login link/button then only it should go to the login page. Can anyone help me to find out the solution, please? Thanks in advance. 
![1](https://user-images.githubusercontent.com/8841098/99377005-df162f80-28ef-11eb-8b13-0ffd094a8216.PNG)

**Comment by jmprieur** [comment]
@javiercn would you know ?

**Comment by javiercn** [comment]
@jmprieur no idea, we have manual test coverage for this, so I believe this must be a configuration issue on the user tenant. I don't think we have active reports of this not working.

**Comment by jennyf19** [comment]
closing, please reopen if needed @saddamhossain
