### ISSUE TITLE
[Bug] ITokenAcquisition.GetAcquireTokenForApp should be named GetAccessTokenForAppAsync

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#77]
[Bug] ITokenAcquisition.GetAcquireTokenForApp should be named GetAccessTokenForAppAsync

**Comment by jennyf19** [comment]
Included in [release]https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.0-preview)
