### ISSUE TITLE
Policy Constants not available in the microsoft-identity-web

### ISSUE THREAD

**Issue by saddamhossain** [AzureAD/microsoft-identity-web#770]
Hi, 
When I integrate Microsoft.Identity.Web.UI from NuGet, I also try to use the Account controller but the **Policy** constant, not available there. 
Here is the link:
[link](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.UI/Constants.cs)

**Comment by jmprieur** [comment]
@jennyf19 : proposing to take this one.

**Comment by saddamhossain** [comment]
@jmprieur and @jennyf19 Thank you so much. Stay safe, Stay care!

**Comment by jennyf19** [comment]
Included in [1.4 Release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.4.0).
