### ISSUE TITLE
No authentication handler is registered for the scheme 'OpenIdConnect'. When application is deployed to Azure App Service Deployment (non- slot).

### ISSUE THREAD

**Issue by madshaun1984** [AzureAD/microsoft-identity-web#772]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

Microsoft Identity Web 1.3.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ X] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [X ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
The app is an existing app in production and I have upgraded to a new version of Microsoft Identity Web whilst introducing distributed token caching. When testing in our staging slot (development environment, which was also previously functioning as expected), the site fails to login.

**Repro**
- Host in an azure deployment (non-production) slot and link with an existing app registration (in our case, this was previously working with Microsoft.Identity.Web 1.1.0). 
- Start the site
- Attempt to login.

**Failing Code Example**
```csharp
public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.Configure<CustomSettings>(Configuration);

            services.AddOptions();

            JwtSecurityTokenHandler.DefaultMapInboundClaims = false;

            // Sign-in users with the Microsoft identity platform
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                    .EnableTokenAcquisitionToCallDownstreamApi(new string[] { Constants.ScopeUserRead, Constants.ScopeDirectoryReadAll })
                    /*.AddInMemoryTokenCaches();*/
                    .AddDistributedTokenCaches();

            services.AddDistributedSqlServerCache(options =>
            {
                options.ConnectionString =
                    Configuration["SqlConnectionString"];
                options.SchemaName = "dbo";
                options.TableName = "TokenCache";
            });

            //services.AddMSGraphService(Configuration);
            services.AddGraphService(Configuration);


            //Adding authorization policies that enforce authorization using Azure AD roles.
            services.AddAuthorization(options =>
            {
                options.AddPolicy(AuthorizationPolicies.AssignmentToUserReaderRoleRequired, policy => policy.RequireRole(AppRole.UserReaders));
                options.AddPolicy(AuthorizationPolicies.AssignmentToDirectoryViewerRoleRequired, policy => policy.RequireRole(AppRole.DirectoryViewers));
            });

            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                // Use the groups claim for populating roles
                options.TokenValidationParameters.RoleClaimType = "roles";
                //options.AccessDeniedPath = new PathString("/Account/AccessDenied");
            });

            // We need to override the access denied path, so we can add some custom formating to the view.
            // Cookie auth options is set due to https://github.com/AzureAD/microsoft-identity-web/issues/117
            services.Configure<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme, options => {
                options.AccessDeniedPath = new PathString("/Account/AccessDenied");
            });

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser() /* Comment this line to remove Authorization site wide */
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });

            services.AddRazorPages()
                .AddMicrosoftIdentityUI();

        }
```

**Expected behavior**
Once published to Azure it is expected that upon clicking sign in, the website will transition through the login flow.

**Actual behavior**
When running locally via VS debug session, the login flow works as expected. However, when hosted the server immediately returns an error view, and logs the following error in AppInsights.

_"No authentication handler is registered for the scheme 'OpenIdConnect'. The registered schemes are: Cookies, AppServicesAuthentication. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OpenIdConnect",...)? "_

**Additional context / logs / screenshots**
The previously working code is as follows, but was using the Microsoft.Identity.Web v1.1.0 nuget package.

````csharp
public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.Configure<CustomSettings>(Configuration);

            services.AddOptions();

            JwtSecurityTokenHandler.DefaultMapInboundClaims = false;

            // Sign-in users with the Microsoft identity platform
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                    .EnableTokenAcquisitionToCallDownstreamApi(new string[] { Constants.ScopeUserRead, Constants.ScopeDirectoryReadAll })
                    .AddInMemoryTokenCaches();
                   /*.AddDistributedTokenCaches();*/

            //services.AddMSGraphService(Configuration);
            services.AddGraphService(Configuration);


            //Adding authorization policies that enforce authorization using Azure AD roles.
            services.AddAuthorization(options =>
            {
                options.AddPolicy(AuthorizationPolicies.AssignmentToUserReaderRoleRequired, policy => policy.RequireRole(AppRole.UserReaders));
                options.AddPolicy(AuthorizationPolicies.AssignmentToDirectoryViewerRoleRequired, policy => policy.RequireRole(AppRole.DirectoryViewers));
            });

            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                // Use the groups claim for populating roles
                options.TokenValidationParameters.RoleClaimType = "roles";
                //options.AccessDeniedPath = new PathString("/Account/AccessDenied");
            });

            // We need to override the access denied path, so we can add some custom formating to the view.
            // Cookie auth options is set due to https://github.com/AzureAD/microsoft-identity-web/issues/117
            services.Configure<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme, options => {
                options.AccessDeniedPath = new PathString("/Account/AccessDenied");
            });

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser() /* Comment this line to remove Authorization site wide */
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });

            services.AddRazorPages()
                .AddMicrosoftIdentityUI();

        }
````

**Comment by jennyf19** [comment]
@madshaun1984 Did you enable easy auth (App Services Authentication)? In that case the line about `services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme...` should be removed. MS Identity Web is using the [App Services scheme](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationHandler.cs).

**Comment by madshaun1984** [comment]
> @madshaun1984 Did you enable easy auth (App Services Authentication)? In that case the line about `services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme...` should be removed. MS Identity Web is using the [App Services handler](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationHandler.cs) and [scheme](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationDefaults.cs#L14).

This is seems to resolve the issue, however, to test I have turned off easy auth then successfully managed to login..

Is this documented anywhere? I wasn't able to surface it if it is.

Thanks!

**Comment by jennyf19** [comment]
We have this [documentation](https://github.com/AzureAD/microsoft-identity-web/wiki/1.2.0#integration-with-azure-app-services-authentication-of-web-apps-running-with-microsoftidentityweb) and [this](https://github.com/AzureAD/microsoft-identity-web/wiki/deploying-to-app-services), but we will improve the wiki so it's more discoverable.
cc: @jmprieur i'll update the wiki, fyi.

closing, but feel free to reopen or open another if needed.

**Comment by jmprieur** [comment]
Thanks for the feedback, @madshaun1984.
We've updated a bit the doc
