### ISSUE TITLE
[Documentation] Improve App Services Auth wiki documentation

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#774]
https://github.com/AzureAD/microsoft-identity-web/issues/772

**Comment by jmprieur** [comment]
Thanks for raising this @jennyf19 
I've updated the wiki docs:

https://github.com/AzureAD/microsoft-identity-web/wiki/deploying-to-app-services

**Comment by jennyf19** [comment]
thanks. i was going to do it, but thank you. i'll go ahead and close this.

**Comment by jennyf19** [comment]
Included in [1.4 Release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.4.0).
