### ISSUE TITLE
[Documentation] AuthorizeForScopesAttribute handles MSAL exceptions

### ISSUE THREAD

**Issue by DigitalSa1nt** [AzureAD/microsoft-identity-web#776]
### Documentation related to component

Microsoft.Identity.Web.AuthorizeForScopesAttribute

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

Hitting a controller endpoint adorned with the `AuthorizeForScopesAttribute` must allow MSAL exceptions to be propagated upwards otherwise the automatic challenge doesn't occur. I think this may need to be better documented, or documented at all somewhere. 

If a developer catches general exceptions and doesn't realise that they need to throw any of `MsalUiRequiredException` types then the only thing that states this is required by the `AuthorizeForScopesAttribute ` is the class commentary found [here](https://github.com/AzureAD/microsoft-identity-web/blob/9b86f44cdc2747e350eb3e83a6a732b2b89132c6/src/Microsoft.Identity.Web/AuthorizeForScopesAttribute.cs#L130)

**Comment by jmprieur** [comment]
@DigitalSa1nt : do we need more than this article: https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access ?

**Comment by DigitalSa1nt** [comment]
> @DigitalSa1nt : do we need more than this article: https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access ?

I did see that documentation and your reply [here](https://github.com/AzureAD/microsoft-identity-web/issues/603#issuecomment-696973021) 

But I don't think the behavior is quite as clearly indicated as we think; nothing suggests that you should re-throw the caught MSAL exceptions so that the attribute can handle it. The only place that suggests that is the actually in-line commentary in the class itself. I may have missed this in the documentation though so please correct me if I'm wrong but even calling the attribute an exception handling attribute would be good as that's not explicitly mentioned either. 

But again the class shows that it inherits from `ExceptionFilterAttribute` which again isn't mentioned as far as I can tell in the docs.

**Comment by jmprieur** [comment]
@DigitalSa1nt 
This is now fixed. 

https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#the-authorizeforscopes-attribute---how-does-it-work

**Comment by DigitalSa1nt** [comment]
> @DigitalSa1nt
> This is now fixed.
> 
> https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#the-authorizeforscopes-attribute---how-does-it-work

Thank you, I think that's an excellent additional snippet to the docs.
