### ISSUE TITLE
[Bug] Missing method: AddProtectedWebApi

### ISSUE THREAD

**Issue by SaqibS** [AzureAD/microsoft-identity-web#78]
**Which Version of Microsoft Identity Web are you using ?**
Note that to get help, you need to run the latest version. 
Latest from master branch

**Where is the issue?**
Web API

**Is this a new or existing app?**
<!-- Ex:
This is a new app or experiment

**Repro**

```csharp
  public void ConfigureServices(IServiceCollection services)
  {
   services.AddProtectedWebApi(Configuration);
  }
```

**Expected behavior**
The `AddProtectedWebApi` method should be there.

**Actual behavior**
There is a method called `AddProtectedWebApi` on `AuthenticationBuilder`, which suggests that this may need to go in `Configure`', but that returns `IApplicationBuilder` not `ApplicationBuilder`.

**Possible Solution**
Updated the readme.

**Additional context/ Logs / Screenshots**
None.

**Comment by SaqibS** [comment]
Very strange - I filled in the bug template but not all content shows up here.

Basically, in `ConfigureServices`, I can't find the `AddProtectedWebApi` method in latest master. There is a method with that name on `AuthenticationBuilder`, but how to create one of those?

**Comment by jmprieur** [comment]
Hello @SaqibS : you need to call .AddAuthentication first.
Would you want to AddProtectedWebApi on the services collection?
 
 ...
  public void ConfigureServices(IServiceCollection services)
  {
   ...
   services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
           .AddProtectedWebApi(Configuration);
   ...
  }
  ...

**Comment by jmprieur** [comment]
BTW, we discsussed this bug and we've decided to bring back the `services.AddProtectedWebApi()`.  
See https://github.com/AzureAD/microsoft-identity-web/pull/81

**Comment by jennyf19** [comment]
Included in [release]https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.0-preview)
