### ISSUE TITLE
Use IHttpClientFactory to create the GraphServiceClient

### ISSUE THREAD

**Issue by damienbod** [AzureAD/microsoft-identity-web#780]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
1.3.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

performance improvement

**Comment by jmprieur** [comment]
@damienbod : closing this issue as the PR is closed.
Feel free to reopen if you have a better idea.

**Comment by tjkb** [comment]
@damienbod @jmprieur Is this issue still fixed? When I'm looking into `Microsoft.Identity.Web.GraphServiceCollectionExtensions.AddMicrosoftGraph` of version 2.19.0 then I don't see anymore that `IHttpClientFactory` is being used. Was it removed?
