### ISSUE TITLE
HttpActionContext not getting set with claims post AzureAD authentication

### ISSUE THREAD

**Issue by santoshpatro** [AzureAD/microsoft-identity-web#782]
Hi Team,

Any help on this issue : https://stackoverflow.com/questions/64971978/httpactioncontext-not-getting-set-with-claims-post-azuread-authentication is much appreciated.

Thanks,
Santosh

**Comment by jmprieur** [comment]
@santoshpatro : how is this related to Microsoft.Identity.Web ?

**Comment by jennyf19** [comment]
closing, but reopen if necessary @santoshpatro
