### ISSUE TITLE
[Feature Request] Allow configuration from container

### ISSUE THREAD

**Issue by wasabii** [AzureAD/microsoft-identity-web#787]
The `AddMicrosoftIdentityWebApi` and `AddMicrosoftIdentityWebApp` methods have no overload which can be used to specify the options while having access to the `IServiceProvider`. They should. I use the container to deliver my configuration options.

**Comment by jmprieur** [comment]
@wasabii : I'm not familiar with your scenario. Can you please elaborate? provide links to documentation ? or other APIs that do that?
At the moment you call .AddMicrosoftIdentityWebApi, I believe that the service provider does not exist yet. I'd think the way to do it by using the overrides with the delegates, which will be called when the service provider exists? Or am I missing something?

**Comment by VivekPaiM** [comment]
I think he's referring to something like this
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#ASP0000

Currently, if the configuration is part of the container, you'd have to build the container to get access to the values. Ideally, we'd want to use the `AddOptions<T>`/`Configure `syntax.

E.g.
``` c#
services.AddOptions<MicrosoftIdentityOptions>()
        .Configure<IMyConfiguration>((options, config) =>
        {
            options.Instance = config.Instance;
        });
```

**Comment by pmaytak** [comment]
@VivekPaiM Thanks for the suggestion. I tested it with [WebAppCallsMicrosoftGraph](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/WebAppCallsMicrosoftGraph) sample and it worked.

Code snippet:
```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IMyConfig>(new MyConfig() { Secret = "custom secret from MyConfig" });

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                        .EnableTokenAcquisitionToCallDownstreamApi()
                           .AddMicrosoftGraph(Configuration.GetSection("GraphBeta"))
                           .AddInMemoryTokenCaches();
            
            services.AddOptions<MicrosoftIdentityOptions>()
                .Configure<IMyConfig>((options, config) =>
                {
                    options.ClientSecret = config.Secret;
                });
```

By the time we get to these lines in `AddMicrosoftIdentityWebApp`, the `MicrosoftIdentityOptions.Secret` is set to the one from `MyConfig`.
https://github.com/AzureAD/microsoft-identity-web/blob/7f5c422bffaf6e6b74addb767e211f78746a2fe4/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L259-L263

@wasabii Would this help in your scenario?
