### ISSUE TITLE
 [Documentation] CertificateDescription.FromStoreWithThumprint(String, StoreLocation, StoreName) Method

### ISSUE THREAD

**Issue by llx9** [AzureAD/microsoft-identity-web#791]
### Documentation related to component

CertificateDescription.FromStoreWithThumprint(String, StoreLocation, StoreName) Method
### Please check all that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

Should be CertificateDescription.FromStoreWith**Thumbprint** ,not **Thumprint**

The SDK Method name is aslo misspelled

**Comment by jmprieur** [comment]
Thanks for the heads-up, @llx9 
Assigning to the next major version (as fixing this would be a breaking change)

**Comment by jmprieur** [comment]
@llx9 this is fixed in 1.12.0
