### ISSUE TITLE
[Feature Request] Change the templates to use b2clogin.com instead of https://login.microsoftonline.com/tfp/

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#792]
The project templates use `https://login.microsoftonline.com/tfp/`.
We want them to use `https://domain.b2clogin.com/`.

We also need to create a PR for ASP.NET Core.

cc: @jennyf19

**Comment by jennyf19** [comment]
included in [1.5.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.5.0)
