### ISSUE TITLE
[Bug] Constants.LoginHint should value login_hint, not loginHint (and domain_hint for DomainHint)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#798]
**Which version of Microsoft Identity Web are you using?**
1.3.0

**Where is the issue?**
* Web app
    * [ x ] Sign-in users
    * [ x ] Sign-in users and call web APIs

**Repro**

Call `AccountController.Challenge` with a loginHint.

```csharp
var your = (code) => here;
```

**Expected behavior**
The call to AAD should show login_hint

**Actual behavior**
It's not

**Possible solution**
Change the value of the LoginHint to `login_hint`
https://github.com/AzureAD/microsoft-identity-web/blob/a4bde02483a792bc0f3af68f2da702be88175e88/src/Microsoft.Identity.Web/Constants/Constants.cs#L15

Same for DomainHint which should value `domain_hint`

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@jennyf19 do you agree?

**Comment by jennyf19** [comment]
Included in [1.4 Release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.4.0).
