### ISSUE TITLE
[Documentation] Authentication fails with no login prompt

### ISSUE THREAD

**Issue by aaronjones1** [AzureAD/microsoft-identity-web#799]
### Documentation related to component
Protected Web API

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
I cannot get authentication to work for a "hello world" protected web API.  I must have missed something but I don't know what.

* Microsoft.Identity.Web version: **1.3.0**
* Target framework: **.NET 5.0**

## appsettings.json
```JSON
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "cycomdev.onmicrosoft.com",
    "TenantId": "<tenant_guid>",
    "ClientId": "<app_registration_Client_ID_guid>"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}
```

## Startup.cs
```C#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Identity.Web;
using Microsoft.OpenApi.Models;

namespace WebApplication5
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            //services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            //    .AddMicrosoftIdentityWebApi(Configuration.GetSection("AzureAd"));
            services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd", "Bearer", true);

            services.AddControllers();
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "WebApplication5", Version = "v1" });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "WebApplication5 v1"));
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
```

## App Registration
* Redirect URI: **`https://localhost:44359`**
* Application ID URI: **`api://<app_registration_Client_ID_guid>`**
* Scope:  **`api://<app_registration_Client_ID_guid>/user_impersonation`**
* Implicit Grant:  **ID tokens**
* Supported account types:  **Accounts in this organizational directory only (cycomdev only - Single tenant)**

## Expected behavior
Browser window opens and prompts for login.

## Actual behavior
The browser window opens and shows HTTP Error 401.

**Comment by jennyf19** [comment]
@aaronjones1 I'm a little confused, as you can't sign-in to a web api, but you can sign-in to a web app, which will then call a web api (or not, just sign-in a user). 

have you seen our web [app templates](https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template)? and 
web [api templates](https://github.com/AzureAD/microsoft-identity-web/wiki/web-api-template)? That should get you up and running. Then you'll register a web app in the azure portal, and if you want, a web api, which would include a client secret.
This [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview?tabs=aspnetcore) might help as well. 
let us know if this helps.

**Comment by aaronjones1** [comment]
Thank you for your reply :)

I guess it was my assumption that if I tried to navigate to the API Controller endpoint in a browser, I would be redirected to the Office 365 sign-in page, authenticate, and then the JSON data would be returned by the API.  But you're saying the only way I can get data from my protected API is by signing in to a client application first?

**Comment by jennyf19** [comment]
Yes, that's what I'm saying. You don't sign-in to a web API, you send a token there, which the web API validates and denies or gives you access based on the scopes the user consented to during the sign-in. 
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration#bearer-token
Going to close this issue, but feel free to ask more questions or open another.
