### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#80]
![image](https://user-images.githubusercontent.com/19942418/78518063-162a3d00-7774-11ea-9866-9bf94f4435de.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/78518090-407bfa80-7774-11ea-8969-e8b9305efabb.png)

![image](https://user-images.githubusercontent.com/19942418/78518130-6d301200-7774-11ea-93a5-0184e097c2cf.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/78593166-0b66bb00-77fb-11ea-8e97-411651142627.png)

![image](https://user-images.githubusercontent.com/19942418/78593183-128dc900-77fb-11ea-9c39-0d23c3d8399e.png)

![image](https://user-images.githubusercontent.com/19942418/78593281-3c46f000-77fb-11ea-81d2-17dff33f721e.png)

![image](https://user-images.githubusercontent.com/19942418/78593320-4b2da280-77fb-11ea-9c65-7a7714cc6514.png)

**Comment by jmprieur** [comment]
![Microsoft Identity Web-2](https://user-images.githubusercontent.com/13203188/81092446-e4d29780-8f00-11ea-993d-b4cea18c8b2e.gif)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/87329890-058a1f80-c538-11ea-9a2a-2726d722c27a.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/89042701-a6097d80-d347-11ea-88e7-b2c12ec767c8.png)

**Comment by pmaytak** [comment]
![image](https://user-images.githubusercontent.com/34331512/89093258-88e7a580-d36d-11ea-8e57-1472c096e834.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/89124954-2f9d8480-d4db-11ea-9a3a-010668c45f1c.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/93343934-5a486000-f831-11ea-9a09-a6a231d198f7.png)

![image](https://user-images.githubusercontent.com/13203188/93343955-603e4100-f831-11ea-9cd8-7025f6361453.png)

**Comment by pmaytak** [comment]
![Avg cache ops](https://user-images.githubusercontent.com/34331512/94507416-8b774780-01c4-11eb-9ec7-ebcd7154cb6f.png)
![Avg Response Time](https://user-images.githubusercontent.com/34331512/94507419-8c0fde00-01c4-11eb-8078-e1aff878a903.png)
![Avg CPU](https://user-images.githubusercontent.com/34331512/94507420-8ca87480-01c4-11eb-8143-30ab3a4f7d51.png)
![Avg Memory](https://user-images.githubusercontent.com/34331512/94507421-8ca87480-01c4-11eb-92aa-e20d8e044ea9.png)
![Request time distribution](https://user-images.githubusercontent.com/34331512/94507422-8ca87480-01c4-11eb-83e8-db6851f44999.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/95238182-6e1c2c00-0809-11eb-884d-234075856eb9.png)

![image](https://user-images.githubusercontent.com/13203188/95238444-d408b380-0809-11eb-98a5-51bbeac89ee2.png)

![image](https://user-images.githubusercontent.com/13203188/95239023-ae2fde80-080a-11eb-8cb7-b14d9356cd19.png)

![image](https://user-images.githubusercontent.com/13203188/95239121-cbfd4380-080a-11eb-9003-493677d5b385.png)

![image](https://user-images.githubusercontent.com/13203188/95239185-e3d4c780-080a-11eb-96a5-3a7eef3c03b8.png)

![image](https://user-images.githubusercontent.com/13203188/95239261-fa7b1e80-080a-11eb-84d9-3519cac4f26a.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/95241144-aaea2200-080d-11eb-8633-51e7796750ce.png)

![image](https://user-images.githubusercontent.com/13203188/95241423-03212400-080e-11eb-99a3-6fbb7a38cd0c.png)

![image](https://user-images.githubusercontent.com/13203188/95241601-47142900-080e-11eb-9c0c-6ebf2febb9db.png)

![image](https://user-images.githubusercontent.com/13203188/95241777-8e9ab500-080e-11eb-92d7-dca52d37ec8b.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/107696478-4acf2500-6cb2-11eb-9e78-2f211cd3f6ab.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/110395300-c195de80-8022-11eb-92ba-115a34267ae1.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/110962124-e3f46880-8350-11eb-8023-330646c6c16b.png)

**Comment by mmacy** [comment]
Ooh, I like this. Would love a little one-liner in the first commit message at the top explaining what this is intended for, though. Are these current, or is this just a way to host images for transient references, such as for other issues/etc.?

**Comment by jmprieur** [comment]
it's to store pictures for the wiki pages. See https://github.com/AzureAD/microsoft-identity-web/wiki/Microsoft-Identity-Web-basics#high-level-architecture

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/111669541-247e3700-87d4-11eb-8cb2-fbdc36773a41.png)
![image](https://user-images.githubusercontent.com/19942418/111669601-3364e980-87d4-11eb-9c94-18f3ee83c067.png)
![image](https://user-images.githubusercontent.com/19942418/111669678-45df2300-87d4-11eb-8217-becc641ff10a.png)
![image](https://user-images.githubusercontent.com/19942418/111669723-51cae500-87d4-11eb-8d04-688db7af836e.png)
![image](https://user-images.githubusercontent.com/19942418/111669787-614a2e00-87d4-11eb-9ebb-882187d239d8.png)
![image](https://user-images.githubusercontent.com/19942418/111669835-6c9d5980-87d4-11eb-8195-60e9e2f1d136.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/113718913-67ee0600-96ed-11eb-9bbb-99c028c4501b.png)

**Comment by jmprieur** [comment]
![image](https://user-images.githubusercontent.com/13203188/114165522-dff63f00-992c-11eb-8485-c7a94a6b1a7b.png)

![image](https://user-images.githubusercontent.com/13203188/114165665-0f0cb080-992d-11eb-9c3c-d244fc7a6dee.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/125811549-88eedf0f-81ab-456e-9503-3393a5ba0306.png)

**Comment by jennyf19** [comment]
![image](https://user-images.githubusercontent.com/19942418/134209423-dc560d9d-618a-417b-95c2-8681634905f9.png)
![image](https://user-images.githubusercontent.com/19942418/134209549-2aea8441-d39e-43bc-9b06-968ab25ce942.png)
