### ISSUE TITLE
Add a method to IServiceCollection, for Razor, to add a consent handler

### ISSUE THREAD

**Issue by bakerCaleb** [AzureAD/microsoft-identity-web#805]
**Is your feature request related to a problem? Please describe.**
When writing a Razor web app, I'd like to add a consent handler. There is no available method. I'm using the one for Blazor, which I think will work, but it is confusing and I'm not confident it is the correct approach.

Example from ConfigureServices() in Startup.cs:

services.AddServerSideBlazor()
               .AddMicrosoftIdentityConsentHandler();

**Describe the solution you'd like**
I'd like something like:
services.AddServerSide**Razor**()
               .AddMicrosoftIdentityConsentHandler();

**Describe alternatives you've considered**
If it's the same code for Razor and Blazor, maybe just make it neutral, like:

services.AddServerSide()
               .AddMicrosoftIdentityConsentHandler();

**Additional context**

**Comment by jmprieur** [comment]
The AddMicrosoftIdentityConsentHandler does not use the [IServerSideBlazorBuilder](https://github.com/dotnet/aspnetcore/blob/b3836954ed895c62e5bc0e188e3ef06704b1d20b/src/Components/Server/src/DependencyInjection/IServerSideBlazorBuilder.cs)

https://github.com/AzureAD/microsoft-identity-web/blob/1a073ed8c0f1e6edf7ac929729c4f76251f1fff7/src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs#L31-L43

**Comment by jennyf19** [comment]
Included in [1.4 Release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.4.0).
