### ISSUE TITLE
[Feature Request] Microsoft.Identity.Client.ConfidentialClientApplicationOptions does not take in ClientCertificate

### ISSUE THREAD

**Issue by llx9** [AzureAD/microsoft-identity-web#806]
How could I share the IEnumerable<CertificateDescription> MicrosoftIdentity.Options.ClientCertificates to the ConfidenticalClientapp?

Microsoft.Identity.Client.ConfidentialClientApplicationOptions only takes in ClientSecret.

e.g.

            services.AddAuthentication()
                .AddMicrosoftIdentityWebApp(options =>
                {
                    this.Configuration.Bind("AzureAd", options);
                    options.ClientCertificates = new CertificateDescription[]
                    {
                         CertificateDescription.FromStoreWithThumprint("xxx")
                    };
                })
                .EnableTokenAcquisitionToCallDownstreamApi(options =>
                {
                    this.Configuration.Bind("AzureAd", options);
                    options.ClientCertificates = ??; // it only takes in ClientSecret.
                },
                new string[] { "User.Read" })
                .AddInMemoryTokenCaches();

**Comment by jmprieur** [comment]
You need to use the MicrosoftIdentityOptions as you've done. The certs will be picked-up by the confidential client app.

**Comment by llx9** [comment]
@jmprieur  Thanks for the reply, but how could I just use MicrosoftIdentityOptions? EnableTokenAcquisitionToCallDownstreamApi method only takes in the Action<ConfidentialClientApplicationOptions> as parameter

**Comment by jennyf19** [comment]
@llx9 in either the appsettings.json or you can do it [programmatically](https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates#describing-client-certificates-to-use-programmatically).
closing as answered, but feel free to reopen or ask more questions.

**Comment by llx9** [comment]
Hi @jennyf19, thanks for your reply. 

It looks to me that _AddMicrosoftIdentityWebApp(Action<MicrosoftIdentityOptions>, ...)_ returns _MicrosoftIdentityWebAppAuthenticationBuilder_, 

The builder only has one method: 
_EnableTokenAcquisitionToCallDownstreamApi(Action<ConfidentialClientApplicationOptions>, IEnumerable<string>)_  
it takes an Action configure delegate, 

My question here:
we already specified all the propriety of the MSAL confidential client app in the configure delegate _Action<MicrosoftIdentityOptions> for AddMicrosoftIdentityWebApp()_ method, 
But we are still required to fill in the configure delegate _Action<ConfidentialClientApplicationOptions>_ for _EnableTokenAcquisitionToCallDownstreamApi(Action<ConfidentialClientApplicationOptions>, IEnumerable<string>)_
and why couldn't we just have _EnableTokenAcquisitionToCallDownstreamApi(IEnumerable<string>)_ method for the builder, or have the first Action parameter as optional?
the duplicate configuration here seems little misleading.
