### ISSUE TITLE
Propagate .WithForceRefresh through to obo call

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#811]
staring w/MSAL .NET 4.24, MSAL .NET supports passing .WithForceRefresh to acquire token by obo. Include this w/the obo builder in identity web.

**Comment by PetrPospisil** [comment]
Good job. Thx.

**Comment by jennyf19** [comment]
Included in [1.4 Release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.4.0).
