### ISSUE TITLE
EnableTokenAcquisitionToCallDownstreamApi throws exception AADB2C90146:  The scope '' provided in request specifies more than one resource for an access token, which is not supported

### ISSUE THREAD

**Issue by jkears** [AzureAD/microsoft-identity-web#814]
I have a Blazor Server-Side application that uses Microsoft.Identity.Web 1.1.0 and  Microsoft.Identity.Web.UI 1.1.0 with an Azure AD B2C as the STS.

Within Azure B2C I created an App registration for the Blazor Server App as well as 2 separate WebAPI microservices as follows;

1. **Blazor Application** - has a B2C App (named Project Portal) that has API Permissions on **coreservices_readwriteaccess**, **sharedservices_readwriteaccess** 
2. **CoreServices** microservice - has a B2C App (named coreservices) that exposes API **coreservices_readwriteaccess**
3. **SharedServices** microservice - has a B2C App (named sharedservices) that exposes API **sharedservices_readwriteaccess**

The following is the Product Portals API Permissions in B2C..
![image](https://user-images.githubusercontent.com/1290937/101268861-3b71af80-3736-11eb-92bf-a451e042d9ec.png)

The following is the CoreServices Exposed API
![image](https://user-images.githubusercontent.com/1290937/101268866-462c4480-3736-11eb-85fe-31ea705edbeb.png)

The following is the ShareServices Exposed API
![image](https://user-images.githubusercontent.com/1290937/101268867-4debe900-3736-11eb-81a4-a4d3be33907c.png)

The following is the startup code within the Blazor application ...
![image](https://user-images.githubusercontent.com/1290937/101268875-6a882100-3736-11eb-902a-f94aae2f8c5e.png)

 
The following is the app config for the Blazor app...
![image](https://user-images.githubusercontent.com/1290937/101268877-6f4cd500-3736-11eb-9bc3-7f70b442db07.png)
 
Shortly after running the Blazor App I receive the following exception ...

> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Error: Message contains error: 'invalid_request', error_description: 'AADB2C90146: The scope 'openid profile offline_access https://nextwaregroupdev.onmicrosoft.com/nextware.productportal.coreservices.api/coreservices_readwriteaccess https://nextwaregroupdev.onmicrosoft.com/nextware.productportal.sharedservices.api/sharedservices_readwriteaccess' provided in request **specifies more than one resource for an access token, which is not supported**.
> Correlation ID: f009ecab-1b42-4230-88ef-e84775e480e2
> Timestamp: 2020-12-06 01:16:08Z
> ', error_uri: 'error_uri is null'.

If I remove one or the other of the scopes I do not get an exception and I am able to acquire an Access Token for the authenticated user with the scope requested.  

I do not understand this..  The two services are not the same resource at all, they are completely separate.

**Comment by jmprieur** [comment]
@jkears 
In `EnableTokenAcquisitionToCallDownstreamApi`, please use only one scope, as Azure AD and Azure AD B2C don't accept that we request scopes for several resources (and these are different resources as you called out).

This won't prevent you from having things work later when you use the downstreamWebApi, as the refresh token will be used to get scopes for the other resource.

**Comment by jkears** [comment]
Thank you @jmprieur  for this guidance however I must be doing something wrong for when I only request a single scope (in startup), then when I request an access token via tokenservice.GetAccessTokenForUserAsync passing in the scope that is not the one I set in startup the method returns a null value token (not exception) but a null value.   When using the same request for an access token that matches the scope I set in startup it does return a valid access token.  It was this behavior that led me in my attempt to set the two scopes within startup.

Here is a test method that I use in an attempt to acquire an access token prior to invoking a secured API.

![image](https://user-images.githubusercontent.com/1290937/101370189-2fd9d200-3877-11eb-97b9-da7c61d541c7.png)

Note:  We have developed an internal suite of tools that use Rosalyn to code generate our ASP.Net Web API microservices from a DSL derived domain model based upon the principals of Domain Driven Design.  Within the model we are able to model and shape the API as well as define gRPC integration between services as well as subscription of domain event integration.  

As such, our future product offerings could potentially consist of 100's of  domain microservices, each with multiple APIs (per domain aggregate).   

We have further automated the B2C  App registration flow to configure the AD Apps for each domain service.  

I am really struggling with the MS Docs on how to make this work.  I have looked high-and-low for real-world examples that invoke more than one API from an App but all there seems to be is examples of with a single scope.  

Can you point me to any documentation with examples on how to properly set this up?

Thank you in advance.

**Comment by jkears** [comment]
For example and as per your (@jmprieur)  guidance.... I include the scope for CoreService only as per this example .. 

![image](https://user-images.githubusercontent.com/1290937/101383340-0032c600-3887-11eb-902a-ffef3ebdb7a9.png)


And when I attempt to get an access token per each resource (CoreService and SharedService) I only get a valid access token for the scope specified above, the other is null...

![image](https://user-images.githubusercontent.com/1290937/101383607-57389b00-3887-11eb-8a53-b8e95636c7dd.png)

And... if I switch the scope at startup to SharedService ...

![image](https://user-images.githubusercontent.com/1290937/101383939-cb733e80-3887-11eb-80c4-f2958b7c8fd1.png)

And run that same code the CoreService scope requested Access token is null while the SharedService scope request Access token is valid...

![image](https://user-images.githubusercontent.com/1290937/101384094-fa89b000-3887-11eb-8b9d-8f406da4192d.png)

How do I get the Access Token to call both of these downstream APIs?

**Comment by jmprieur** [comment]
@jennyf19 : apparently the refresh token does not work (any longer?) to access several B2C web APIs. Are you aware of it?

**Comment by jennyf19** [comment]
@ktsakas can you provide any insight here? thank you.

**Comment by jkears** [comment]
A key point that I made earlier is how it returns a null access token and does not throw an exception for a valid scope list. 

For example, if you attempt to pass a totally bogus scope you will receive an exception (as expected).   

Thus the call into **GetAccessTokenForUserAsync** that returns a null access token must be resolving to the requested scope list  and then downstream of that validation it fails to acquire the token for whatever reason (tbd).

**Comment by jmprieur** [comment]
@jkears this is really Azure AD B2C (the service) which does this validation. It knows that the resource/scope exists. 
Would you have a different user flow / policy associated with both APIs?

**Comment by jkears** [comment]
@jmprieur no I do not implement a different user flow / policy associated with my APIs.  

Were you able to reproduce my issues?    

Do you have an example that acquires access tokens for multiple APIs?  

If so, please share that with me so I can compare for differences with my very simple solution.

**Comment by jmprieur** [comment]
@nickgmicrosoft
What would be the recommendation for a B2C web app to call different web APIs (different resources)? The refresh token does not allow this. Can the initial scopes contain several resources?

cc: @jennyf19

**Comment by relakhani** [comment]
B2C does not allow multiple resources (web apis) as scope parameter value in a single authorize request. You need to send separate auth requests for each resource

**Comment by jmprieur** [comment]
Closing as this is external

**Comment by jpda** [comment]
@jmprieur & @jennyf19 - external where? B2C side or separate? We have this problem too; `AuthorizeForScopes` sends the user to the correct B2C authorization URL (with the correct, requested scope), however on the return trip, when the code is redeemed, it is redeemed with the other API scope, not the requested one.

API1 (`https://jaydoubleutee.info/jt/WebApi1Access`)
API2 (`https://jpdab2c.onmicrosoft.com/jt2/WebApi2Access`)

Startup config has API1, I can also get access tokens for API1.

```csharp
 services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
  .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAdB2C"))
  .EnableTokenAcquisitionToCallDownstreamApi(
      new[] { "https://jaydoubleutee.info/jt/WebApi1Access" }
  )
  .AddInMemoryTokenCaches()
```

But in a page, when I need to call API2, I use AuthorizeForScopes with the 2nd API scope - when I try to `GetAccessTokenForUserAsync(api2 scope)` I get in a redirect loop. 

Desired scope: `https://jpdab2c.onmicrosoft.com/jt2/WebApi2Access` - this is requested when the user is sent to /authorize

![image](https://user-images.githubusercontent.com/5932293/106336061-1c862a00-625c-11eb-8e45-ebd98e814ae9.png)

But on return, when the code redemption call is made to `/token`, it is for the incorrect scope, which leads to a redirect loop as MSAL bombs

![image](https://user-images.githubusercontent.com/5932293/106336143-463f5100-625c-11eb-97d1-590805f82980.png)

**Comment by cmatskas** [comment]
To pile on on @jpda's comment above, I was able to replicate this issue using B2C while trying to acquire tokens for two different APIs using the `AddDownstreamWebApi()` approach. The error manifests in a different way:

Exception details.
![image](https://user-images.githubusercontent.com/4126750/106337341-c7d7b480-6245-11eb-84ed-7b58a2a19f87.png)

![image](https://user-images.githubusercontent.com/4126750/106337366-d625d080-6245-11eb-9521-171dcdcda158.png)

You can find the code to repro this [here](https://github.com/cmatskas/webapp-calling-multiple-apis-b2c)

**Comment by jennyf19** [comment]
@jmprieur reopening. we need a sample or doc on this scenario, so reopening to track, but i might open a separate issue later (fyi).

**Comment by jt-pt-dev** [comment]
Hi @jmprieur 

I appreciate if you are unable to comment, but I was wondering what the block is and whether it is the "_will be fixed in the next release_" type block or is it "_uh oh... we need to rethink this_" type of block.

We are considering whether to back out of B2C and revert back to plain AD and some timelines would be helpful.

Thank you.

**Comment by jmprieur** [comment]
@jt-pt-dev : the B2C people will answer.

**Comment by jmprieur** [comment]
Closing as this is a service limitation (documented)

**Comment by flipch** [comment]
@jmprieur Can  you provide guidance on whether or not this applies  to just B2C or also normal Azure AD?

I'm trying to setup my server side  blazor app with the conditional access handler for both GRAPH and Azure ARM API's and eithe struggling with not being able to request two resources with same token or not getting the consent handler for the azure arm scopes.

Would  you prefer if I opened a new issue?

**Comment by nickgmicrosoft** [comment]
I believe this applies to both AAD and B2C. You can only get an AT one at a time. I think the recommended approach is to get a refresh token and then redeem it multiple times for the different resources needed, one at a time.

**Comment by flipch** [comment]
@nickgmicrosoft Maybe I'm confusing this issue with  mine. I'm not trying to get an access token that can access both Graph and ARM.

My struggle is that the consent  handler isn't retrying to get the correct scopes or at  least doesn't succeed to. I've also struggled to find an example that sets up blazor server with more than just a call to Grap API

**Comment by nickgmicrosoft** [comment]
Not sure what you mean by consent handler. To things to note that may be relevant to your scenario:
- user tokens generated by Azure AD B2C user flows/policies cannot be used against Microsoft Graph (or ARM).
- user authentications using Azure AD B2C user flows/policies do not support user consent. That is, permissions must have admin consent.

Not sure if that's relevant to your scenario but just stating it in case.

Your scenario sounds a little different than this original Github issue, probably preferable if you open a new ticket.

**Comment by flipch** [comment]
Thank you @nickgmicrosoft. Your edit pointed me in the right direction.

>  Azure AD B2C does now support redeeming a refresh token for a resource different than the initial request. This was a recent addition.

This made me look at which version Identity.Web I was using and it was 1.1.0
I believe this is the default for people using the `dotnet new blazorserver --auth stuff` command. Perhaps that oughta be updated, albeit not under your scope :)

**Comment by cmatskas** [comment]
@flipch check out some of the streams we have on the [#425Show](https://aka.ms/425Show).

https://www.youtube.com/watch?v=smlqDVpDuq0
https://www.youtube.com/watch?v=naK0RZhvNAs

**Comment by jennyf19** [comment]
@jkears @jpda @flipch @cmatskas this has been addressed on the B2C side, so should be working now. 
cc: @nickgmicrosoft

**Comment by deathblade89** [comment]
@flipch Hey man.

So this ended abruptly.

I have ran into the same issues and there are no documented solutions.

Did you manage to come right with this using Azure B2C?

I am currently stuck on the newer versions of Identity.Web 2.11.1 and using the IAuthorizationHeaderProvider.CreateAuthorizationHeaderForUserAsync(scopes);

This still has the same result as defined in this forum.

If I add the scope for the one API resource in the setup EnableTokenAcquisitionToCallDownstreamApi(scope)
Then downstream works fine for that one resource scope.

Sigh.... You just can't get good help these days.

**Comment by SilverioMiranda** [comment]
What worked for me was not specifying any scopes when registering the services:

```
builder.Services
    .AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAdB2C"))
    .EnableTokenAcquisitionToCallDownstreamApi([])
    .AddInMemoryTokenCaches();
```
Then, I obtained the tokens by passing the scope and the user parameter as a ClaimsPrincipal object:


```
var token = await tokenAcquisition.GetAccessTokenForUserAsync(
    ["your_scope_here"], user: user);
```
