### ISSUE TITLE
[Feature Request] Simplify the builds and projects, now that .NET released

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#824]
**Is your feature request related to a problem? Please describe.**
Now that .NET 5 is released, it's recognized part of Visual Studio, and therefore we should be able to simplify our build:

**Describe the solution you'd like**
- Update the Microsoft.Extension.* package reference in the net472 section of Microsoft.Identity.Web to be 5.0.0
- remove these package reference from Microsoft.Identity.Web.Test and Microsoft.Identity.Web.Test.Common as they'll be available by transitivity.
- (to be tested): Remove the Microsoft.Identity.Web-without-blasorwasm2-sample.sln solution? and update the build to VSBuild the Microsoft.Identity.Web solution directly

https://github.com/AzureAD/microsoft-identity-web/blob/f829b9b4198f70166ed1224995458f0ccfe0fa5f/build/template-restore-build-MSIdentityWeb.yaml#L23

I would then think that the following build task would not be necessary

https://github.com/AzureAD/microsoft-identity-web/blob/f829b9b4198f70166ed1224995458f0ccfe0fa5f/build/template-restore-build-MSIdentityWeb.yaml#L10-L15

**Comment by jennyf19** [comment]
Included in [1.4 Release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.4.0).
