### ISSUE TITLE
[Investigate] Remove AddAuthentication with auth default calls as they might be unnecessary

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#83]
Currently in samples and in `ServiceCollection` extensions we set the default authentication scheme by calling: `AddAuthentication(JwtBearerDefaults.AuthenticationScheme)` or `AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)`. Later in the configuration process we call `builder.AddJwtBearer(jwtBearerScheme, options => ...)` or `builder.AddOpenIdConnect(openIdConnectScheme, options => ... )` with the same authentication scheme name. 

Need to investigate if calling the `AddAuthentication` methods is necessary or not because they have the same functionality as the following methods.

Ref: 
[AuthenticationBuilder](https://github.com/dotnet/aspnetcore/blob/1bbca1502b8f638f43d414d8ee2ccf9fa88bc4b7/src/Security/Authentication/Core/src/AuthenticationBuilder.cs#L14)
[AuthenticationServiceCollectionExtensions](https://github.com/dotnet/aspnetcore/blob/1bbca1502b8f638f43d414d8ee2ccf9fa88bc4b7/src/Security/Authentication/Core/src/AuthenticationServiceCollectionExtensions.cs#L14)

**Comment by TiagoBrenck** [comment]
@pmaytak during your investigation, make sure that users are still allowed to configure multiple authentication schemes, with different configurations each. For instance, there are scenarios where developers configure AAD and B2C in the same web application.

**Comment by pmaytak** [comment]
Thanks for the pointer, @TiagoBrenck. 👍

**Comment by pmaytak** [comment]
Closing. [AddAuthentication](https://github.com/dotnet/aspnetcore/blob/c9ce0664ea2d9ff842af8f6242d1609c93e8b683/src/Security/Authentication/Core/src/AuthenticationServiceCollectionExtensions.cs#L16) adds some required services.
