### ISSUE TITLE
[Documentation] How to use with Azure Functions?

### ISSUE THREAD

**Issue by chris5287** [AzureAD/microsoft-identity-web#830]
Is there any documentation explaining how to wire this up for an Azure Function (mainly to use Microsoft Graph API)?

**Comment by jmprieur** [comment]
@chris5287 Microsoft.Identity.Web is for ASP.NET Core web app and web APIs.
For Azure functions acting as web APIs, please see, https://github.com/Azure-Samples/ms-identity-dotnet-webapi-azurefunctions.

See https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#azure-functions-as-web-apis

**Comment by jennyf19** [comment]
@chris5287 Actually @hajekj got this to work. You should check out his [blog post](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhajekj.net%2F2020%2F12%2F12%2Fmicrosoft-identity-web-and-azure-functions%2F&data=04%7C01%7Cjeferrie%40microsoft.com%7Cbda7149dbc2f4b7ab8f508d89ee0a363%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637434034961268428%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dftZDUq1WQmLZjAdabmn9SrJJBfJ1AiauEE2KW4B3Gg%3D&reserved=0) and let us know how it goes or if you hit any issues.
