### ISSUE TITLE
[Feature Request] EnableTokenAcquisitionToCallDownstreamApi(IEnumerable) method for MicrosoftIdentityWebAppAuthenticationBuilder

### ISSUE THREAD

**Issue by llx9** [AzureAD/microsoft-identity-web#834]
**Is your feature request related to a problem? Please describe.**
It looks to me that AddMicrosoftIdentityWebApp(Action, ...) returns MicrosoftIdentityWebAppAuthenticationBuilder,

The builder only has one method:
EnableTokenAcquisitionToCallDownstreamApi(Action, IEnumerable)
it takes an Action configure delegate,

we already specified all the propriety of the MSAL confidential client app in the configure delegate Action for AddMicrosoftIdentityWebApp() method,
But we are still required to fill in the configure delegate Action for EnableTokenAcquisitionToCallDownstreamApi(Action, IEnumerable)
the duplicate configuration here seems little misleading.

**Describe the solution you'd like**
have EnableTokenAcquisitionToCallDownstreamApi(IEnumerable) method for the builder, or have the first Action parameter as optional in EnableTokenAcquisitionToCallDownstreamApi(Action, IEnumerable)

**Describe alternatives you've considered**

**Additional context**
#806 related issue.

**Comment by jmprieur** [comment]
@llx9. This is slightly more complex than that.
1. `AddMicrosoftIdentityWebApp` has several overrides. One takes a configuration, and then what you propose happens, but the second override takes a delegate to initialize (yourself) a `MicrosoftIdentityOption`.
2. When using the second override (with delegate), you have only one method on the build `EnableTokenAcquisitionToCallDownstreamApi`, indeed which takes an action and the scopes. However, the action is, this time, to initialize another option class: `ConfidentialClientApplicationOptions`. 

Even if there is a bit of overlap between the properties of `MicrosoftIdentityOption` and `ConfidentialClientApplicationOptions`, there are properties in `ConfidentialClientApplicationOptions` which are not in `MicrosoftIdentityOption`, and therefore you need to initialize it.

Something we could do a bit better is try to initialize the common properties, though.

**Comment by jmprieur** [comment]
@llx9  closing as we've answered.
Feel free to reopen
