### ISSUE TITLE
[Bug] Add overrides with delegates of AddSignIn, and AddProtectedWebAPI taking Service collection (in addition to AuthenticationBuilder)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#84]
**Where is the issue?**
* Web App
    * [ x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ x] Protected web APIs (Validating tokens)
    * [ ] Protected web APIs (Validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In Memory caches
     * [ ] Session caches
     * [ ] Distributed caches

**Repro**

Today, we need to write
```csharp
services.AddAuthentication(OpenIdConnectAuthentication.DefaultScheme)
             .AddSignIn(options => ..., options => ....);
```
but we cannot do directly :
services..AddSignIn(options => ..., options => ....);

whereas the overrides with a configuration section exist.

**Expected behavior**
Have the overrides with delegates for both AddSignIn and AddProtectedWebAPI, from a service collection in addition to from an AuthenticationBuilder

**Comment by jennyf19** [comment]
Included in [release]https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.0-preview)
