### ISSUE TITLE
[Bug] Blazor Server Incremental Consent Issue

### ISSUE THREAD

**Issue by Shama-K** [AzureAD/microsoft-identity-web#847]
**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Repro**

1. Select test project [blazorserver-calls-api](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/blazorserver-calls-api) in Microsoft.Identity.Web.
2. Remove scope from this code in Startup.cs, by updating as below:
services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
.EnableTokenAcquisitionToCallDownstreamApi()
.AddInMemoryTokenCaches();
3. Run the application and Sign-in. Select ToDoList.

**Expected behavior**
Consent screen should be displayed.

**Actual behavior**
Requests goes into infinite loop.

**Possible solution**
Resolved with [this Pull Request](https://github.com/AzureAD/microsoft-identity-web/pull/840).

**Comment by jennyf19** [comment]
included in [1.5.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.5.0)
