### ISSUE TITLE
Provide an IAuthorizationFilter to filter accepted scopes

### ISSUE THREAD

**Issue by plamber** [AzureAD/microsoft-identity-web#849]
**Is your feature request related to a problem? Please describe.**
The current version of microsoft-identity-web provides the [ScopesRequiredHttpContextExtensions.VerifyUserHasAnyAcceptedScope(HttpContext, String[]) Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.resource.scopesrequiredhttpcontextextensions.verifyuserhasanyacceptedscope?view=azure-dotnet-preview) to verify that the user authenticated in the web API has any of the accepted scopes.

This method must be called in the API methods you are implementing. In some situations this is a repeating activity with repeating code. 

**Describe the solution you'd like**
I wanted to improve the situation by providing an IAuthorizationFilter decorator for API classes and methods like this:
![image](https://user-images.githubusercontent.com/18241305/102627365-64d40780-4148-11eb-9ed6-3020860cd2e6.png)

I ended up using the existing code implemented for VerifyUserHasAnyAcceptedScope and came with [this Gist](https://gist.githubusercontent.com/plamber/3122487154a7503216c7ad48f1252deb/raw/a268f2aa96625aec57d52919d99d7b2d25d5cbed/gistfile1.txt). 

I am wondering if such a technique could become a part of the library. Personally, it feels more natural using the attributes  as suggested here.

**Describe alternatives you've considered**
Implement it by my own

**Additional context**
Reference issue #65

**Comment by jmprieur** [comment]
See in particular this comment (https://github.com/AzureAD/microsoft-identity-web/issues/65#issuecomment-748423937) on how to return a custom error message

**Comment by jennyf19** [comment]
Included in [1.6.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.6.0) release.
