### ISSUE TITLE
[Question] Functionality of AuthorizeForScopes in Resource Filter

### ISSUE THREAD

**Issue by PieterJanVdb** [AzureAD/microsoft-identity-web#857]
I'm currently implementing a Resource Filter in a Razor Page web application where `TokenAcquisition.GetAccessTokenForUserAsync` is called which might result in a `MsalUiRequiredException`. Now usually that's handled by using the `AuthorizeForScopes` attribute on the Page. However, any exceptions thrown in a Resource Filter will not be handled by any Exception Filters (like `AuthorizeForScopes`).

So I thought I'd just replicate the behaviour of the `AuthorizeForScopes` attribute in the Resource Filter, but I stumbled on `IncrementalConsentAndConditionalAccessHelper` being an internal class. When I then tried to see if I could replicate whatever is in the two necessary methods (`CanBeSolvedByReSignInOfUser` and `BuildAuthenticationProperties`) I once again stumbled on an internal class, this time `OidcConstants` for the additionalBuiltInScopes.

Now my question is, is there a way for me achieve the same functionality as the `AuthorizeForScopes` attribute but in a Resource Filter with the current version? All I really need are the previously mentioned two methods so I can challenge the user in the Filter.

(I could just copy the code inside BuildAuthenticationProperties and hardcode the constants, but that seems like a recipe for disaster if there is a breaking change in the library)

**Comment by jmprieur** [comment]
@PieterJanVdb : you could use the `MicrosoftIdentityConsentAndConditionalAccessHandler` class which is the solution for Blazor pages, but can also be used in MVC or Razor pages. 

https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-the-blazor-page-itself

Can you inject it by dependency injection in your resource filter?

**Comment by PieterJanVdb** [comment]
@jmprieur That seems to do the trick, thanks!

**Comment by jmprieur** [comment]
Thanks for the update, @PieterJanVdb. We're glad you're unblocked.
