### ISSUE TITLE
[Feature Request] IGraphServiceClient Injection

### ISSUE THREAD

**Issue by jayoungers** [AzureAD/microsoft-identity-web#860]
**Is your feature request related to a problem? Please describe.**
Currently, `AddMicrosoftGraph()` adds `GraphServiceClient` to the service collection as the type opposed to the interface.

**Describe the solution you'd like**
If this line was updated to reference the interface: https://github.com/AzureAD/microsoft-identity-web/blob/ee038c26145e7f42c0f44461c57cc39d55e5598f/src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphExtensions.cs#L72

It would resolve the problem.  I'm not sure if that would result in backwards compatibility issues (if someone was asking for `GraphServiceClient` specifically, I would hope the service provider would still use this descriptor), but if that's not the case, it could be added like the work around below to minimize the breaking change

**Describe alternatives you've considered**
Current work around is to manually add the interface after setup:

```
            services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd")
                    .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddMicrosoftGraph()
                    .AddDistributedTokenCaches();
            services.AddScoped<IGraphServiceClient, GraphServiceClient>();
```

**Additional context**
From a testing perspective it's difficult to mock the concrete class out as it currently is

**Comment by jennyf19** [comment]
@jayoungers please see the [comment here](https://github.com/AzureAD/microsoft-identity-web/issues/625#issuecomment-702765953), this is against the recommendation from the Graph SDK team. Closing as by-design.
cc: @darrelmiller

**Comment by jayoungers** [comment]
Thanks @jennyf19 !  I'll look into pulling out our references to the interfaces

@darrelmiller I fully agree with the stance on interface usage, but is the comment inferring that in order to test `GraphServiceClient` in isolation, the expectation is to mock it out at a lower level (i.e. http requests/responses)?

If my logic is injecting `GraphServiceClient`, I'm not 100% sure from a testing perspective what should be provided to that logic in a unit testing scenario.  As of now we're using the interfaces because they can be mocked, whereas the class cannot since nothing is marked as virtual
