### ISSUE TITLE
ITokenAcquisition injected into IClaimsTransformation implementation fails to return access token

### ISSUE THREAD

**Issue by bradtwurst** [AzureAD/microsoft-identity-web#861]
**Which version of Microsoft Identity Web are you using?**
1.4.1
**Where is the issue?**
* Web app
    * [x] Sign-in users - blazor server

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**

attempting to call GetAccessTokenForUserAsync inside an implementation of IClaimsTransformation so that additional application specific claims can be retrieved from a legacy application

the call fails and the access token is not provided.

how do I get the access token at this stage in the pipeline?

```csharp
public class HttpClaimsTransformation : IClaimsTransformation
    {
        private readonly UserProvider _userProvider;
        private readonly ITokenAcquisition _tokenAcquisition;

        public HttpClaimsTransformation(
            UserProvider userProvider, //http api to retrieve application-specific info stored within application
            ITokenAcquisition tokenAcquisition
            )
        {
            _userProvider = userProvider;
            _tokenAcquisition = tokenAcquisition;
        }

        public async Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
        {
//retrieval of accessToken is actually occuring in UserProvider but I put here for testing purposes - in
            try
            {
                var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(new[] { "<<my scope>>" });
            }
            catch (System.Exception ex)
            {
                //this fails with an MsalUiRequiredException inner exception of "No account or login hint was passed to the AcquireTokenSilent call."
                throw;
            }

            var newPrincipal = await _userProvider.ProvideUpdatedPrincipal(principal);
            return newPrincipal;
        }
    }
```

**Expected behavior**
would like to be able use an access token to call a specific web api call

**Actual behavior**
the access token is not provided

**Additional context / logs / screenshots**
this is for a blazor server application, but I think it would also happen with mvc web sites as well

my guess is that the token has not yet been cached at the point where the claims transformation occurs?

**Comment by jmprieur** [comment]
What is the failure? is there an exception?

I would think that IClaimsTransformation  is called before the HttpContext.User is even populated.
You might want to try to call the override of [GetAccessTokenForUserAsync](https://docs.microsoft.com/dotnet/api/microsoft.identity.web.itokenacquisition.getaccesstokenforuserasync?view=azure-dotnet-preview#Microsoft_Identity_Web_ITokenAcquisition_GetAccessTokenForUserAsync_System_Collections_Generic_IEnumerable_System_String__System_String_System_String_System_Security_Claims_ClaimsPrincipal_Microsoft_Identity_Web_TokenAcquisitionOptions_) taking a ClaimsPrincipal.

**Comment by bradtwurst** [comment]
Thanks for the response.

The exception reported is 

    MsalUiRequiredException inner exception of "No account or login hint was passed to the AcquireTokenSilent call."

I was not aware that the GetAccessToken method had an override for passing in the claims principal.

I used that override with the principal that is provided to the claims transformation method and it does resolve the situation.

Thanks,
James

**Comment by jmprieur** [comment]
Thanks for the update, @bradtwurst !
