### ISSUE TITLE
[Feature Request] Enabling to see relevant health data and usage metrics in Application Insights or similar telemetry system

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-identity-web#87]
All services needs to have telemetry to be able to monitor health as well as usage. Identity.Web should provide an easy integration into Application Insights as well as other telemetry systems to show both health and usage metrics.

This will mean that Telemetry from MSAL and IdentityModel should be exposed enabling Identity.Web to leverage that. Additionally Identity.Web should provide telemetry on usage patterns as well as service health metrics specifically for the glue.

Next step: Investigate in more detailed requirements

**Comment by jmprieur** [comment]
@henrik-me : which questions do we want to answer? who is the PM for this?

**Comment by bgavrilMS** [comment]
If I were an a website developer I would want to have a dahsboard that shows at least:

- duration of AcquireToken* calls
- duration of AcquireTokenSilent call when cache is hit
- duration of AcquireTokenSilent call when cache is not hit (i.e. refresh_token flow)
- cache hit ratio

**Comment by jmprieur** [comment]
Closing for now
@pmaytak FYI
