### ISSUE TITLE
[Bug] AuthorizeForScopesAttribute should specify an alternate AuthenticationScheme name

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#870]
**Which version of Microsoft Identity Web are you using?**
1.5.0

**Where is the issue?**
* Web app
    * [ x] Sign-in users and call web APIs

**Is this a new or an existing app?**
Apps that want to use several identity providers / authentication schemes. We have, for instance this request for documentation on how to sign-in with both AAD and B2C: https://github.com/AzureAD/microsoft-identity-web/issues/549. If there is CA or incremental consent, this would require this feature

**Expected behavior**
It's possible for the developer to have incremental consent and CA handled for several authentication schemes. 

**Actual behavior**
Today this is not possible.

**Possible solution**
The authorize for scopes attributes could take a new property with the Authentication scheme

**Additional context / logs / screenshots**
- @DrEsteban proposed a PR. See https://github.com/AzureAD/microsoft-identity-web/pull/868

**Comment by jennyf19** [comment]
Included in [1.6.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.6.0) release.
