### ISSUE TITLE
[Feature Request] Microsoft.Identity.Web helps authenticating Azure Functions with AAD and B2C

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#878]
**Is your feature request related to a problem? Please describe.**
Azure functions can be considered as Web APIs. It's possible to call with with a header containing a bearer token. 

**Describe the solution you'd like**
Microsoft.Identity.Web should provide a helper and documentation on how to do that.

**Describe alternatives you've considered**
-  See https://github.com/AzureAD/microsoft-identity-web/issues/830, where @hajekj proposed a blog post.
-  See also 
   - https://winsmarts.com/use-microsoft-identity-web-with-azure-functions-2a5c52824578 for another blog post
   - https://github.com/maliksahil/ms-identity-azurefunctions-microsoft-identity-web for a sample

**Comment by jmprieur** [comment]
Reopen until we release it (it's fixed)

**Comment by husseinkorly** [comment]
It will be really useful for us if it can decrypt and validate v2 tokens!

**Comment by husseinkorly** [comment]
@jmprieur when 1.5.0 expected to be released?

**Comment by jmprieur** [comment]
This week, @husseinkorly 
(today is a public holiday in the US)

**Comment by jennyf19** [comment]
included in [1.5.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.5.0)
