### ISSUE TITLE
[Feature Request] Performance and Load Testing

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-identity-web#88]
Build infrastructure to measure performance and load metrics on a continuous basis ensuring that releasing can be done so with high confidence that no performance sensitive scenarios are broken.

We should be able to answer questions such as:
* How many users are supported?
* Latency in various configurations
* How does using redis impact cache performance
* How many users can we handle using various combinations of cache?
* Cache failure rates (telemetry data point), e.g. Redis is know for failures.
* Cache misses (telemetry data point)
and many many more

Findings during the performance and load testing should be turned into new features/bugs and addressed. 

Next: More detailed requirements to be defined.

**Comment by bgavrilMS** [comment]
The questions around the cache are dependent on a small improvement in MSAL: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1728

**Comment by pmaytak** [comment]
@henrik-me Should I close this issue, since we completed GA criteria work? Afterwards we can create separate issues for each perf task that will be done?

**Comment by jmprieur** [comment]
Let's mark it as fixed. We'll close it with the milestone.

**Comment by jennyf19** [comment]
Included in [1.1.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.1.0).
