### ISSUE TITLE
[Bug] Set option "GetClaimsFromUserInfoEndpoint" should go to user info endpoint

### ISSUE THREAD

**Issue by m-hicks-OH** [AzureAD/microsoft-identity-web#880]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
1.4.1

**Where is the issue?**
* Web app
    * [x ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Other (please describe)

**Is this a new or an existing app?**

a. The app is in production and I have attempted to change from OpenIDConnect middleware to MicrosoftIdentityWebApp middleware.

**Repro**

```csharp
var initialScopes = new string[] { "openId", "profile", "User.ReadBasic.All" };
// Sign-in users with the Microsoft identity platform
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
     .AddMicrosoftIdentityWebApp(options =>                
     {   
          Configuration.Bind("AzureAd", options);
          options.GetClaimsFromUserInfoEndpoint = true;
      }, options => { Configuration.Bind("AzureAd", options); })
      .EnableTokenAcquisitionToCallDownstreamApi(options => Configuration.Bind("AzureAd", options), initialScopes)
      .AddMicrosoftGraph(Configuration.GetSection("GraphAPI"))
      .AddInMemoryTokenCaches();
```

**Expected behavior**
Setting option "GetClaimsFromUserInfoEndpoint" to true actually results in an HTTP request to that endpoint passing the access_token as a bearer, retrieving all additional claims, and adding them to the set of UserClaims.

**Actual behavior**
OpenIdConnetOption of "GetClaimsFromUserInfoEndpoint" is not resulting in actually sending an http request to the UserInfo Endpoint defined in the Discovery/Meta document.  For example, our tenant defines the v2.0 userinfo endpoint as "https://graph.microsoft.com/oidc/userinfo", but that request is never made despite the access_token to do so being received.
This works as intended in the standard OpenIdConnect middleware.

Specifically GraphAPI based (such as User.ReadBasic.All) claims are NOT included in the id_token (as expected), but since the call to the userinfo endpoint is not happening, those claims are never retrieved.  Once again, if I manually setup the same configuration directly in OpenIdConnect middleware, the correct behavior occurs, and all claims are available.

**Possible solution**
Make the setting option of "GetClaimsFromUserInfoEndpoint = true" on the function .AddMicrosoftIdentityWeb() actually result in calling the endpoint defined in the discovery document.

**Comment by m-hicks-OH** [comment]
As a side note, I downloaded the sample app for .net core web apps configured all the settings in the appsettings.json, and got the same effect.  The user signs-in, app gets the authcode, app sends the authcode to the token endpoint, app gets an access token, and does not call the userinfo endpoint.  I then tried to manually set that option (either in the appsettings or on the options delagate, and same effect.

**Comment by jmprieur** [comment]
@jennyf19 
Let's call the user info endpoint even in the case where we don't call a web api. This way, I believe the ID token might no longer be needed (we need to verify this claim)

**Comment by m-hicks-OH** [comment]
ID Token is still very much needed, especially if GetClaimsFromUserInfoEndpoint is set to false.

**Comment by jennyf19** [comment]
@blowdart and @tratcher I looked into this, and doesn't seem to be something we (id web) handle, but rather in the OpenIdConnectOptions...can you provide some insight here? thank you.

**Comment by blowdart** [comment]
I leave this to chris. Presumably there's an event somewhere where you'll get the results back and you need to wire that up if the option is set to true.

**Comment by Tratcher** [comment]
Hmm, that code path doesn't have many preconditions:
https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L875-L884

Which of those logs do you get?

**Comment by Tratcher** [comment]
@jennyf19 do you hook any of the events like OnTokenValidated and short circuit? That would cause GetClaimsFromUserInfoEndpoint not to run later.

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L631-L635

**Comment by jennyf19** [comment]
@Tratcher we hook in for the [auth code](https://github.com/AzureAD/microsoft-identity-web/blob/4da4d33812b33969c8d7469df1249f8a00d8c331/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs#L132) and [OnTokenValidated](https://github.com/AzureAD/microsoft-identity-web/blob/4da4d33812b33969c8d7469df1249f8a00d8c331/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs#L140), but I don't think we short circuiting things.

**Comment by ChristopherHaws** [comment]
After debugging through the ASP.NET Core code, it looks like `AccessToken` is null, so [this branch is being triggered](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L880) right before calling the UserInfoEndpoint. The access token is null because the `tokenEndpointResponse` is null [here](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L744). Looking back further in the code, it looks like this is because the `authorizationResponse.Code` property is null so the [`tokenEndpointResponse`](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L666) is never set.

In the end, it looks like the auth flow wasnt doing a hybrid flow (aka, `options.ResponseType` is set to `id_token` and not `code id_token` as described [here](https://medium.com/identity-beyond-borders/openid-connect-hybrid-flow-1123bc9461fe). To get around this, I added the following configuration:

```csharp
// Ensure that we are using hybrid flow so that we can get user info from the user info endpoint
if (!options.ResponseType.Split(' ').Contains("code"))
{
    options.ResponseType = $"code {options.ResponseType}";
}
```

Ultimately, it seems like if the `options.GetClaimsFromUserInfoEndpoint` option is set to true, then `Microsoft.Identity.Web` should do this for you.

Hope this helps!

**Comment by jmprieur** [comment]
Thanks for the investigation, @ChristopherHaws

**Comment by jennyf19** [comment]
Look into this and the answer is in this [doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo#userinfo-response), specifically that if the claims are the same values that the app would see in the Id token, use the id token, via `HttpContext.User`.

UserInfo can only return `sub` `name` `family_name` `given_name` `email`, and all those can be found in the id token as well.

Closing as by-design.

**Comment by ChristopherHaws** [comment]
@jennyf19 When using Azure Active Directory, the `family_name` and `given_name` are not returned as part of the id token. This is the reason I am using the user info endpoint.

**Comment by jmprieur** [comment]
@ChristopherHaws, you can configure the claims that appear in the IDToken:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#configuring-optional-claims

**Comment by m-hicks-OH** [comment]
@ChristopherHaws  well "Son-of-a-biscuit"... 
```
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                {
                    options.GetClaimsFromUserInfoEndpoint = true;
                    options.ClientId = Configuration.GetValue<string>("AzureAd:ClientId");
                    options.ClientSecret = Configuration.GetValue<string>("AzureAd:ClientSecret");
                    options.TenantId = Configuration.GetValue<string>("AzureAd:TenantId");
                    options.CallbackPath = Configuration.GetValue<string>("AzureAd:CallbackPath");
                    options.Instance = Configuration.GetValue<string>("AzureAd:Instance");
                    options.ClaimActions.MapAll();
                    options.SaveTokens = true;
                    **options.ResponseType = "code id_token"**;
                });
```
the explicit setting of the response type did the trick.

My apologies for ghosting this thread... I ended up going with an explicit implementation of .AddOpenIdConnect because I ran out of time to dig deeper into this issue.

I'm going to try to use this (Microsoft.Identity.Web) again, as it will make calling MSGraph as a downstream API a heck of alot easier.

**Comment by xperiandri** [comment]
@jennyf19 why do you throw access token away here?
https://github.com/AzureAD/microsoft-identity-web/blob/fdc81a924cf6e893102c33a6eebd3b7ebe5dbb41/src/Microsoft.Identity.Web/TokenAcquisition.cs#L229

**Comment by xperiandri** [comment]
And claim actions are duplicated
![image](https://user-images.githubusercontent.com/2365592/174454592-a168ed77-b9be-4a6f-8672-6b4c44acaec6.png)
