### ISSUE TITLE
Documentation: How to use EasyAuth with Azure AppService and Roles?

### ISSUE THREAD

**Issue by johnnyreilly** [AzureAD/microsoft-identity-web#881]
### Documentation related to component

How to use EasyAuth with Azure App Service with Roles.  I may be reporting a bug here also - but I'm not sure.

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

Hello!  I've been working on trying to make use of Easy Auth with a .NET 5 project running in an Azure App Service (Linux).  According to the [docs](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization#userapplication-claims): 

> At this time, ASP.NET Core does not currently support populating the current user with the Authentication/Authorization feature. However, some 3rd party, open source middleware components do exist to help fill this gap.

The 3rd party component is: https://github.com/MaximRouiller/MaximeRouiller.Azure.AppService.EasyAuth

I initially started using @MaximRouiller's shim but found an issue with the roles mapping which lead me to go with a slightly tweaked approach which I've blogged about: https://blog.johnnyreilly.com/2021/01/azure-easy-auth-and-roles-with-dotnet-and-core.html

@MaximRouiller gave me the great news that official support was being worked upon and was good enough to point me in the direction of @mattchenderson [who was good enough to point me here](https://twitter.com/mattchenderson/status/1350137204719321091) suggesting that this was now a solved problem.

I happened upon the [docs for the 1.2 release](https://github.com/AzureAD/microsoft-identity-web/wiki/1.2.0#integration-with-azure-app-services-authentication-of-web-apps-running-with-microsoftidentityweb):

> From version 1.2.0, the same code for your web app written with Microsoft.Identity.Web will work seamlessly with our without EasyAuth. Your web app can sign-in users and possibly call web APIs or Microsoft Graph. Indeed, Microsoft.Identity.Web now detects that the app is hosted in App Services, and uses that authentication.

This appears to be thanks to @jmprieur's work on this PR: https://github.com/AzureAD/microsoft-identity-web/pull/700

It might be good to update the docs to clarify that Easy Auth now *does* work with Azure App Service for authentication.  Now to the bug.

### Roles with Azure App Service Easy Auth != Roles when directly using Microsoft.Identity.Web

Whilst the authentication seems to work, authorisation does not.  So whilst my app knows who I am - the authorization is not working with relation to **roles**.

When directly using `Microsoft.Identity.Web` (as we do locally) we see these claims:

```json
[
    // ...
    {
        "type": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
        "value": "Administrator"
    },
    {
        "type": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
        "value": "Reader"
    },
    // ...

]
``` 

However, EasyAuth puts provides roles related claims with a **different type**:

```json
[
    // ...
    {
        "type": "roles",
        "value": "Administrator"
    },
    {
        "type": "roles",
        "value": "Reader"
    },
    // ...
]
```

This means that roles related authorization *does not work* with Easy Auth:

```cs
[Authorize(Roles = "Reader")]
[HttpGet("api/reader")]
public string GetWithReader() =>
    "this is a secure endpoint that users with the Reader role can access";
```

This is because .NET is looking for claims with a `type` of `"http://schemas.microsoft.com/ws/2008/06/identity/claims/role"` and not finding them with Easy Auth.

My feeling is that this *may* be a bug.  Running directly against `Microsoft.Identity.Web` has different behaviour to using Easy Auth.  Ideally these would be the same. 

### Is there a workaround?

Whilst ideally this would just work.... I wonder if there might be a workaround which we could use now.  [I'd submitted a PR](https://github.com/MaximRouiller/MaximeRouiller.Azure.AppService.EasyAuth/pull/13) to add a `OnClaimsReceived` event to `MaximeRouiller.Azure.AppService.EasyAuth`.  If merged it would faciliate usage like this:

```cs
services.AddAuthentication("EasyAuth").AddEasyAuthAuthentication(options =>
    options.Events.OnClaimsReceived = (claims) => {
        var mappedRolesClaims = claims
            .Where(claim => claim.Type == "roles")
            .Select(claim => new Claim(ClaimTypes.Role, claim.Value))
            .ToList();

        return Task.FromResult(claims.Concat(mappedRolesClaims));
    });
```

Is there a similar event available that we could hook into right now which would support this sort of mechanism?  This might be a good short term measure.  I've had a look at https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationHandler.cs but nothing has leaped out at me so far.

### Code

We're using a .NET 5 project, running in an Azure App Service (Linux). 

```xml
    <PackageReference Include="Microsoft.Identity.Web" Version="1.4.1" />
```

In my `Startup.cs` we're using:

```cs
      public void ConfigureServices(IServiceCollection services) {
            //...
            services.AddMicrosoftIdentityWebAppAuthentication(Configuration);
            //...
      }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {
            //...
            app.UseAuthentication();
            app.UseAuthorization();
            //...
      }
```

The relevant portion of the `azuredeploy.json` that enables EasyAuth looks like this:

```json
                "siteConfig": {
                    "siteAuthSettings": {
                        "enabled": true,
                        "unauthenticatedClientAction": "RedirectToLoginPage",
                        "tokenStoreEnabled": "true",
                        "defaultProvider": "AzureActiveDirectory",
                        "clientId": "[parameters('clientId')]",
                        "issuer": "[concat('https://sts.windows.net/', parameters('tenantId'), '/')]"
                    },
                    "linuxFxVersion": "[parameters('linuxFxVersion')]",
                    "alwaysOn": false,
                    "ftpsState": "Disabled",
                    "http20Enabled": true,
                    "minTlsVersion": "1.2",
                    "remoteDebuggingEnabled": false,
                    "appSettings": [
                      //...
                    ]
                },
```

**Comment by johnnyreilly** [comment]
I think I've come up with a workaround using `IClaimsTransformation`.  Inside our `Startup.cs` I've registered a claims transformer: 

```cs
            services.AddScoped<IClaimsTransformation, AddRolesClaimsTransformation>();
``` 

And that claims transformer looks like this:

```cs
    public class AddRolesClaimsTransformation : IClaimsTransformation {
        private readonly ILogger<AddRolesClaimsTransformation> _logger;

        public AddRolesClaimsTransformation(ILogger<AddRolesClaimsTransformation> logger) {
            _logger = logger;
        }

        public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal) {
            var mappedRolesClaims = principal.Claims
                .Where(claim => claim.Type == "roles")
                .Select(claim => new Claim(ClaimTypes.Role, claim.Value))
                .ToList();

            // Clone current identity
            var clone = principal.Clone();

            if (clone.Identity is not ClaimsIdentity newIdentity) return Task.FromResult(principal);

            // Add role claims to cloned identity
            foreach (var mappedRoleClaim in mappedRolesClaims) 
                newIdentity.AddClaim(mappedRoleClaim);

            if (mappedRolesClaims.Count > 0)
                _logger.LogInformation("Added roles claims {mappedRolesClaims}", mappedRolesClaims);
            else
                _logger.LogInformation("No roles claims added");

            return Task.FromResult(clone);
        }
    }
```

I've done some testing and it seems to work.  We'll be able to move forward with this for now.  I'll try and blog about this to share the knowledge.  It would be tremendous if this wasn't necessary though.

**Comment by johnnyreilly** [comment]
Hi @jennyf19,

Apologies for pinging you directly.  I was just wondering if there was anyone looking into the issue I raised here?  I appreciate you must be super busy - but it would be great to understand if this being looked at in any way?  Or if my understanding of the situation isn't quite right.  That's always possible!

**Comment by jmprieur** [comment]
@johnnyreilly. We can see if we can enhance Microsoft.Identity.Web to use "roles" by default in the case the app is hosted by EasyAuth. Would you be able to try out if we produced a preview build?

Meanwhile, instead of doing the claim transformation, did you try the following ?

```CSharp
services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                // The claim in the Jwt token where App roles are available.
                options.TokenValidationParameters.RoleClaimType = "roles";
            });
```

**Comment by johnnyreilly** [comment]
Thanks for responding @jmprieur!

> Would you be able to try out if we produced a preview build?

Absolutely!

> Meanwhile, instead of doing the claim transformation, did you try the following ?

No I haven't tried that - I will and will report back.

**Comment by kalyankrishna1** [comment]
The solution is provided [here](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/5-WebApp-AuthZ/5-1-Roles/Startup.cs)

The relevant code for reference
            ```
// This is required to be instantiated before the OpenIdConnectOptions starts getting configured.
            // By default, the claims mapping will map claim names in the old format to accommodate older SAML applications.
            // 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' instead of 'roles'
            // This flag ensures that the ClaimsIdentity claims collection will be built from the claims in the token
            JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
```

**Comment by johnnyreilly** [comment]
Hey @jmprieur! (and @kalyankrishna1),

We experimented with adding the following in, as suggested:

```
            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options => {
                // The claim in the Jwt token where App roles are available.
                options.TokenValidationParameters.RoleClaimType = "roles"; // see: https://github.com/AzureAD/microsoft-identity-web/issues/881#issuecomment-769118334
            });
```

However it doesn't appear to have worked.  Here's were our `roles` claims when deployed to Azure:

```json 
{
"type": "roles",
"value": "Administrator"
},
{
"type": "roles",
"value": "Reader"
},
```

However, when attempting to hit the following controller endpoint we experienced `403 Forbidden`.

```
        [Authorize(Roles = "Reader")]
        [HttpGet("api/reader")]
        public string GetWithReader() =>
            "this is a secure endpoint that users with the Reader role can access";
```

**Comment by jmprieur** [comment]
@johnnyreilly : did you do what @kalyankrishna1 suggested:

```CSharp
JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
```

before calling `AppMicrosoftIdentityWeb` ?

**Comment by johnnyreilly** [comment]
Sorry no - I missed that. Let me test again and report back.

**Comment by johnnyreilly** [comment]
No - it didn't work with @kalyankrishna1's suggestion either I'm afraid.

**Comment by dev-a11y** [comment]
Does anyone succeeded in using Microsoft.Identity.Web package as middleware for App Services Authentication?
I followed all? blogs and articles (discussion here is the most comprehensive one in this subject) and still no success.

**Background**

We have ASP.NET Core 3.1 web api that is hosted in App Service on Azure.
When we access it directly in browser we get:

> AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '[***client id of app registration***]'.

but it's as expected because this api is only accessed from SharePoint Online client side context.

Easy Auth is enabled on that App service - with Azure Active Directory provider.

**Problem**

Everything is fine when we use [https://www.nuget.org/packages/MaximeRouiller.Azure.AppService.EasyAuth/](https://www.nuget.org/packages/MaximeRouiller.Azure.AppService.EasyAuth/) package.
Meaning, whole thing behaves as in previous version based on .NET Framework - we can lookup authenticated user mail, AAD id and in general User property is available in controller. Here is the code we use:

in project file:
```csharp
<PackageReference Include="MaximeRouiller.Azure.AppService.EasyAuth" Version="1.0.154" />
```
in startup file:
```csharp
using MaximeRouiller.Azure.AppService.EasyAuth;

services.AddAuthentication().AddEasyAuthAuthentication((o) => { });

```
in controllers:
```csharp
[Authorize(AuthenticationSchemes = "EasyAuth")]
```

BUT when we switch to Microsoft.Identity.Web like this:

in project file:
```csharp
<PackageReference Include="Microsoft.Identity.Web" Version="1.8.2" />
```
in startup file:
```csharp
using Microsoft.Identity.Web;

services.AddMicrosoftIdentityWebAppAuthentication(Configuration);

```
in controllers:
```csharp
[Authorize]
```

We just get 401 and nothing more (with MaximeRouiller's package there is no such problem at all)...

We have tried probably all combinations of code in startup and settings files but no luck.

In docs we have: 

> From version 1.2.0, the same code for your web app written with Microsoft.Identity.Web will work seamlessly with our without EasyAuth. Your web app can sign-in users and possibly call web APIs or Microsoft Graph. Indeed, Microsoft.Identity.Web now detects that the app is hosted in App Services, and uses that authentication.

Does it mean it can be considered as a replacement for mentioned 3rd party library or not yet? 
Here [https://github.com/AzureAD/microsoft-identity-web/issues/8](https://github.com/AzureAD/microsoft-identity-web/issues/8) there is comment:

> See also Feature 964131: Microsoft.identity.web populates User object with claims received in Headers from EasyAuth

I compared the code between MaximRouiller's package and what we have in this repo here and it looks similar...

The only thing I could think of is that maybe app service does not providing those env variables:
```csharp
/// <summary>
/// Is App Services authentication enabled?.
/// </summary>
public static bool IsAppServicesAadAuthenticationEnabled
{
    get
    {
        return (Environment.GetEnvironmentVariable(AppServicesAuthEnabledEnvironmentVariable) == Constants.True)
            && Environment.GetEnvironmentVariable(AppServicesAuthIdentityProviderEnvironmentVariable) == AppServicesAuthAzureActiveDirectory;
    }
}
```
in MaximRouiller's package we don't have such check...

Anyway, below are the errors that appear in app service logs in azure when we try to call some endpoint:

> HTTP Error 401.71 - Unauthorized
Module EasyAuthModule_64bit
Error Code 0x80004005
Logon Method Not yet determined
Requested URL http://localhost:80/

> HTTP Error 401.71 - Unauthorized
Module EasyAuthModule_64bit
Error Code 0x80004005
Logon Method Not yet determined
Requested URL http://[***name of app service***]:80/

> HTTP Error 401.71 - Unauthorized
Module EasyAuthModule_64bit
Error Code 0x80004005
Logon Method Not yet determined
Requested URL https://[***name of app service***]:80/

> HTTP Error 401.0 - Unauthorized
Module AspNetCoreModuleV2
Error Code 0x00000000
Logon Method aad
Requested URL https://[***name of app service***]:80/api/mycontroller?param=value
Logon User [email of my aad account]

> [Debug] Microsoft.Identity.Web.AppServicesAuthenticationHandler: AuthenticationScheme: AppServicesAuthentication was not authenticated.
[Information] Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Authorization failed.
[Information] Microsoft.Identity.Web.AppServicesAuthenticationHandler: AuthenticationScheme: AppServicesAuthentication was challenged.

Do you have any clues, we lost almost a week fighting with this and gave up for now hoping someone will figure it out some day (more and more people will be migrating from .NET Framework so maybe this will get proper attention then OR maybe App Service authentication will be decommissioned? maybe we will be advised to use Azure Functions with http triggers instead custom app service hosted apps? hard to guess...

**Comment by jmprieur** [comment]
@dev-a11y @johnnyreilly 
Frankly, when you want elaborated scenario, just disable Easy auth (disable app services authentication). 
Use app services, but let Microsoft.Identity.Web do the authentication and authorization.

What benefit do you expect from Easy Auth, if your web app or web API is already protected with Microsoft.Identiyt.Web ?

**Comment by johnnyreilly** [comment]
> What benefit do you expect from Easy Auth, if your web app or web API is already protected with Microsoft.Identiyt.Web ?

Hey @jmprieur 

The benefit we've identified is around having a standard policy that can be applied. A little context may help here. Our organisation is of a reasonable size and is planning to migrate its estate from running on our own data centers into Azure. A large percentage of those applications being migrated are internal facing. We want to minimise the risk of applications being moved into Azure and potentially exposing customer data through endpoints that aren't correctly secured.

A way to achieve this is through enforcing EasyAuth with Azure AD by policy (and allowing exceptions for public facing apps).

cc @jamiemccrindle - please do add any detail / nuance that might better express the need here.

**Comment by jmprieur** [comment]
For the moment, Easyauth isn’t configurable beyond “let all authenticated users in” and limiting it to a single tenant.
To do more, you'd want to disable Easy auth and leverage groups and roles in conjunction with MIcrosoft.Identity.Web. See [Authorization with Roles and Groups in an ASP.NET core web app](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ)

**Comment by jmprieur** [comment]
See https://blog.johnnyreilly.com/2021/01/17/azure-easy-auth-and-roles-with-net-and-microsoft-identity-web/
