### ISSUE TITLE
Sample to use subscribeToJwtBearerMiddlewareDiagnosticsEvents: true

### ISSUE THREAD

**Issue by rsrinivasanhome** [AzureAD/microsoft-identity-web#889]
**Is your feature request related to a problem? Please describe.**
I want to see the jwt bearer events but not able to do even though I am setting subscribeToJwtBearerMiddlewareDiagnosticsEvents: true

Here is the sample I am using.

services.AddAuthentication()
                   .AddMicrosoftIdentityWebApi(Configuration, "AzureAd", "ADScheme", subscribeToJwtBearerMiddlewareDiagnosticsEvents: true)
                       .EnableTokenAcquisitionToCallDownstreamApi();

How do I see what is happening in the JWT bearer events ?  Can I get example ?

**Comment by jennyf19** [comment]
@rsrinivasanhome I see them in the logs using the same set-up you have. Is there something more specific you are looking for?

```csharp
Microsoft.Identity.Web.Resource.JwtBearerMiddlewareDiagnostics: Debug: Begin OnMessageReceivedAsync. 
Microsoft.Identity.Web.Resource.JwtBearerMiddlewareDiagnostics: Debug: End OnMessageReceivedAsync. 
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler: Information: Successfully validated the token.
Microsoft.Identity.Web.Resource.JwtBearerMiddlewareDiagnostics: Debug: Begin OnTokenValidatedAsync. 
Microsoft.Identity.Web.Resource.JwtBearerMiddlewareDiagnostics: Debug: End OnTokenValidatedAsync. 
```

**Comment by jennyf19** [comment]
@rsrinivasanhome I've updated the wiki with the information on [logging](https://github.com/AzureAD/microsoft-identity-web/wiki/Logging) and [web api troubleshooting](https://github.com/AzureAD/microsoft-identity-web/wiki/Web-API-Troubleshooting)
