### ISSUE TITLE
[Feature Request] Allow for configuring HttpClient in AddDownstreamWebApi

### ISSUE THREAD

**Issue by snebjorn** [AzureAD/microsoft-identity-web#891]
**Is your feature request related to a problem? Please describe.**
I want to be able to configure the HttpClient made inside the `AddDownstreamWebApi` call.

I'd like access to `HttpClient` to be able to set default headers etc. `client.DefaultRequestHeaders`.
I'd like access to `IHttpClientBuilder` to be able to call `ConfigurePrimaryHttpMessageHandler`.

**Describe the solution you'd like**
The default DownstreamWebApi implementation is nice. But a bit restrictive.
https://github.com/AzureAD/microsoft-identity-web/blob/1a073ed8c0f1e6edf7ac929729c4f76251f1fff7/src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs#L18

Can't we just get a named client with the token stuff sorted :)

Example: (probably not a good api, but should highlight the idea)
```cs
// config
services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddDownstreamHttpClient("MyDownstreamApi",
        client =>
        {
            client.DefaultRequestHeaders.Add(HeaderNames.Accept, MediaTypeNames.Application.Json);
        },
        builder => 
        {
            builder.ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
            {
                AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
            });
        })
    .AddInMemoryTokenCaches();

// usage
using var httpClient = _httpClientFactory.CreateClient("MyDownstreamApi");
// .. do stuff
```

You would then wrap the usage in a service and everyone would be happy 🌮 

This could probably also work for typed clients.

**Describe alternatives you've considered**
Alternatively we would have to use `ITokenAcquisition` and write our own http client and copy this
https://github.com/AzureAD/microsoft-identity-web/blob/1a073ed8c0f1e6edf7ac929729c4f76251f1fff7/src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs#L47

But that might change in future versions

**Comment by jennyf19** [comment]
Included in the [1.22.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.22.00

**Comment by jmprieur** [comment]
@snebjorn: you can now customize the HttpRequestMessage. The documentation is [Customizing the headers (or the HttpMessageRequest) when using IDownstreamWebApi](https://github.com/AzureAD/microsoft-identity-web/wiki/adding-call-api-to-web-app#customizing-the-headers-or-the-httpmessagerequest-when-using-idownstreamwebapi)

**Comment by snebjorn** [comment]
Excellent! Thank you ❤️
