### ISSUE TITLE
[Feature Request] Have a project template for protected Azure functions

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#899]
**Is your feature request related to a problem? Please describe.**
dotnet new func --auth SingleOrg [--calls-graph] 
dotnet new func --auth SingleOrg [--called-api-url xxx --called-api-scopes yyy]
dotnet new func --auth IndividualB2C 

**Describe the solution you'd like**
Have a project template for Azure functions that are protected with AAD or AAD B2C

**Additional context**
The Azure function templates are in https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/ProjectTemplate/CSharp

**Comment by jennyf19** [comment]
Included in [1.6.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.6.0) release.
