### ISSUE TITLE
Support netstandard 2.1 rather than netcoreapp3.0

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#9]
See request: [#242 (comment)](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/242#issuecomment-569228606)

Copied from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/248

**Comment by yohanb** [comment]
Any update on this? Thanks.

**Comment by jmprieur** [comment]
@yohanb : I don't think that would be possible. Microsoft.AspNetCore.Authentication.JwtBearer (which is one of our dependencies) for instance does not have a target platform for netstandard2.1 ...

**Comment by yohanb** [comment]
@jmprieur maybe it would be possible to extract most of the functionality into a separate package that is netstandard compatible.  For example, implementing `ITokenAcquisition` or using `MicrosoftIdentityOptions` in a library project would make sense as opposed to an aspnetcore project.

**Comment by jmprieur** [comment]
Thanks @yohanb :as we are making more features available in .NET framework, we'll think of your suggestion.
Which public API would you like to see in the netstandard project?

**Comment by jennyf19** [comment]
blocked as MSAL.NET does not support netstandard2.1

**Comment by stephenjust** [comment]
@jennyf19 Latest version of Microsoft.Identity.Client does target netstandard2.1
