### ISSUE TITLE
[Feature Request] worker2 project template should allow for calling graph and downstream APIs

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#900]
**Is your feature request related to a problem? Please describe.**
The `worker2` template protects gRPC services, but does not show how to call Microsoft Graph or a downstream API yet.

**Describe the solution you'd like**
```Shell
dotnet new worker2 --auth SingleOrg [--calls-graph]
dotnet new worker2 --auth SingleOrg [--called-api-url xxx --called-api-scopes yyy]
```

**Additional context**
See the WebAPI template

**Comment by jennyf19** [comment]
Included in [1.6.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.6.0) release.
