### ISSUE TITLE
Query how to configure multiple audience for Azure AD B2C

### ISSUE THREAD

**Issue by rsrinivasanhome** [AzureAD/microsoft-identity-web#904]
Hi,
I am using Azure AD B2C .  My token will have two different audiences based on conditions.  My api needs to work with both the audiences .  In the client id field I have been able to add one Audience if I need to add more than one say two. How  will add it the config file ?

{ 
  "AzureAdB2C": {
    "Instance": "https://mytenant.b2clogin.com",
    "Domain": "mytenant.onmicrosoft.com",
    **"ClientId": "<UUID>",**
    "SignUpSignInPolicyId": "B2C_1_SignIn"
  }
}

**Comment by jmprieur** [comment]
I suggest that, after services.AddMicrosoftIdentityWebApp, you add an instruction like the following:

```CSharp
services.Configure<OpenIdConnectOptions>("AzureADB2C", options =>
{
   options.TokenValidationParameters.ValidAudiences = your_audiences;
});
```

**Comment by RichardWhitfield** [comment]
@jmprieur thank you!!  I don't know why but I couldn't figure this out and your snippet pointed me in the right direction. 👍
