### ISSUE TITLE
[Bug] Enable token decryption certificates rotation

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#905]
**Which version of Microsoft Identity Web are you using?**
1.5.1

**Where is the issue?**
* Web API
    * [x ] Protected web APIs (validating tokens)

**Is this a new or an existing app?**
New or existing

**Repro**
Today, Microsoft.Identity.Web allows the developers to provide a collection of token decryption certificates (to be able to rotate certificates), but only the fist one is used. See [this code](https://github.com/AzureAD/microsoft-identity-web/blob/9bc1a37c2c52175aa514e577b2fb966f25469e6b/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs#L208-L209)

**Expected behavior**
Developers need to be able to rotate their certificates, and therefore all the certs provided in the TokenDecryptionCertificates property

**Actual behavior**
Only the first certificate is loaded and used for the token decryption

**Possible solution**
Use `TokenValidationParameters.TokenDecryptionKeys` instead of `TokenValidationParameters.TokenDecryptionKey`.  We'll also need to have a new method [DefaultCertificateLoader.LoadAllCertificates]() in addition to the existing method [DefaultCertificateLoader.LoadFirstCertificate](https://github.com/AzureAD/microsoft-identity-web/blob/9bc1a37c2c52175aa514e577b2fb966f25469e6b/src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs#L227), with the same signature, but returning a collection of `X509Certificate2`. 

Note we don't want to remove the existing method (LoadFirstCertificate) as it will still be used for client certificates, for which the rotation is helped by the use of sendX5c.

**Comment by brentschmaltz** [comment]
@jmprieur We need to be careful when using certificates.
Some users have seen issues when specifying the certificate. 
A more performant pattern would be to obtain the RSA object from the certificate once on startup and pass an RSASecurityKey (s) instantiated with the RSA object. Our libraries will not dispose of the RSA as they did not create it.

**Comment by jennyf19** [comment]
@jmprieur there was [fix](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1511) for the issue i hit w/this is in IdentityModel.* 6.8.0, however, Microsoft.AspNetCore.Authentication.* is currently on 6.7.1 of IdentityModel.*, and updating to 6.7.1 does not support net472 or netcoreapp3.1.

so, marking as blocked, we can discuss how to proceed.

**Comment by jmprieur** [comment]
Fixed by https://github.com/AzureAD/microsoft-identity-web/pull/909

**Comment by jennyf19** [comment]
Included in [1.6.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.6.0) release.
