### ISSUE TITLE
Question: How to change login and logout path

### ISSUE THREAD

**Issue by akshaybabloo** [AzureAD/microsoft-identity-web#906]
I wanted to change the login path from `/MicrosoftIdentity/Account/SignIn` to `/login` and this is what I have so far

```cs
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(msOptions =>
                    {
                        Configuration.Bind("AzureAdB2C", msOptions);
                    },
                    cookieOptions =>
                    {
                        cookieOptions.Cookie.Name = "RexAuth";
                        cookieOptions.LogoutPath = new PathString("/logout");
                        cookieOptions.LoginPath = new PathString("/login");
                    });
```

And it doesn't work. How should I change the login path?

**Comment by jmprieur** [comment]
@akshaybabloo 
What you are changing is the cookie logout path, not the AAD one.
The Microsoft Identity account controller is implemented with MVC. Adding a Areas/MicrosoftIdentity/Pages/Account/*.cshtml file will enable you to override the default /MicrosoftIdentity/Account/ pages.

Would that work for you?

**Comment by akshaybabloo** [comment]
@jmprieur Thanks for getting back. But doesn't this override the page instead of the path?

**Comment by jmprieur** [comment]
Yes, it does override the page, but you can provide your controller part of the app.

Alternatively, you might want to try to change the OpenIdConnectOptions.RemoteSignoutPath](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.builder.openidconnectoptions.remotesignoutpath?view=aspnetcore-1.1#Microsoft_AspNetCore_Builder_OpenIdConnectOptions_RemoteSignOutPath)
 ?

**Comment by akshaybabloo** [comment]
OK will have a look at this. Will reopen it if I still have an issue. Thanks.
