### ISSUE TITLE
[Bug] Phone sign up form problems

### ISSUE THREAD

**Issue by arqe** [AzureAD/microsoft-identity-web#907]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [x ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

Hi, 

I have no idea, where to report the B2C login issue for phone sign up, since there are no links to report anything inside Azure. 
This is probably not related to Identity.Web at all, but you may be able to forward the issue for those of concern to know. 

The issue: It is not possible to select Czech Republic by any means. After you click on it in the dropdown, another one gets selected. 

![image](https://user-images.githubusercontent.com/16734197/105631629-aba3d400-5e4f-11eb-807e-83b162b5bf04.png)

Chrome 87.0.4280.141

Many thanks.

**Comment by arqe** [comment]
I took a look at the page source and this is the root cause: 
![image](https://user-images.githubusercontent.com/16734197/105632637-86fe2b00-5e54-11eb-9acf-837f3f584280.png)

**Comment by jmprieur** [comment]
@arqe: we contacted the service people. We are waiting for them to reply

**Comment by jennyf19** [comment]
@arqe have you tried with the standard userflow? Based on the UI in the screen shot, it looks like you are using the recommended user flow...a work around might be to try w/the standard user flow until we hear back from the b2c team. just an idea.

**Comment by arqe** [comment]
Thanks a lot! It is not related to a production scenario at the moment, so I just wanted it to be reported for the benefit of everyone.

**Comment by jennyf19** [comment]
closing as b2c issue.
