### ISSUE TITLE
[Bug] What Distributed SQL value to use for DefaultSlidingExpiration ? 

### ISSUE THREAD

**Issue by rajeevchib** [AzureAD/microsoft-identity-web#908]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [X ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ X] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
New app.

**Repro**

```csharp
services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureAdB2C")
    .AddDistributedTokenCaches();
services.AddDistributedSqlServerCache(options =>
{
    options.ConnectionString = _config["DistCache_ConnectionString"];
    options.SchemaName = "dbo";
    options.TableName = "TestCache";
});
```
We are calling _tokenAcquisition.GetAccessTokenForUserAsync to get the access token. This works.
This method acquires new access token and refresh token automatically, if access token is expired.

But If token cache entry is expired, but still present in database. This method throws MSALUIRequiredException.
(Note: no matters, if access token is still valid or expired. This method generates exception if token cache entry is expired.)

**Expected behavior**
We were expecting this method will do silent login and return us an access token, when token cache entry is expired.
The validity of the token cache should not affect the validity of access token.

**Actual behavior**
GetAccessTokenForUserAsync method is throwing MSALUIRequiredException exception, when token cache entry is expired.

Default expiration of Sql Token Cache is 20 mins. Default Access token expiration is 1 hour.
If we leave everything with default settings and leave application inactive for 20 mins.
When we perform any action after 20 mins, token cache entry is expired, but access token is still valid.
Calling _tokenAcquisition.GetAccessTokenForUserAsync method at that time throws MSALUIRequiredException exception.

**Possible solution**
When we debugged Microsoft.Identity.Web OpenSource, The value of accountIdentifier looks okay.
But since account is null, we get an exception in GetAccessTokenForUserAsync at Line 219.

**Additional context / logs / screenshots**

@jmprieur 

I am creating this issue because I am not getting reply into a closed issue (https://github.com/AzureAD/microsoft-identity-web/issues/843). Not sure, if closed issues ever get entertained any further or not.

We are still getting MSALUIRequired Exception, when SQL Token Cache is expired, but access token is still valid.

I am attaching sample application to reproduce the issue with steps specified in the readme.txt file under project folder.
I have taken off client id and secret for security. If you would like to use our application, please provide an email address where I can send you these details and credentials.

Note: We are using Authorization Code Flow, so during registration of application we deselected both Access Token and ID Token Options used for implicit flow. Attached screenshot.
![image](https://user-images.githubusercontent.com/77790555/105700977-a322ca80-5f2f-11eb-9b09-8d9197b5fbc8.png)

[MSIdentitySample.zip](https://github.com/AzureAD/microsoft-identity-web/files/5866270/MSIdentitySample.zip)

Exception
Message - One or more errors occurred. (IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent. )
StackTrace - at GIXplore.Utility.RequestHandlingMiddleware.Invoke(HttpContext httpContext) in E:\GeoLogix\Proj\Microservices\GIXplore\Trunk\GIXplore\Utility\RequestHandlingMiddleware .cs:line 23
at CommonFiles.ErrorHandlingMiddleware.Invoke(HttpContext httpContext) in E:\GeoLogix\Proj\Common\Code\Trunk\CommonLibrary\Code\ErrorHandlingMiddleware.cs:line 20
InnerException
Message - IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent.
StackTrace - at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable1 scopes, String tenant, String userFlow, ClaimsPrincipal user) in E:\\GeoLogix\\Proj\\OpenSource\\MSAL\\0.4.0-preview-netcoreonly\\microsoft-identity-web-master\\src\\Microsoft.Identity.Web\\TokenAcquisition.cs:line 265 at CommonFiles.HttpHelper.GetClient(Boolean isTokenRequired) in E:\\GeoLogix\\Proj\\Common\\Code\\Trunk\\CommonLibrary\\Code\\HttpHelper.cs:line 38 Inner Exception Message - No account or login hint was passed to the AcquireTokenSilent call. Error code - user_null. StackTrace - at Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder.Validate() at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder1.ValidateAndCalculateApiId()
at Microsoft.Identity.Client.AbstractClientAppBaseAcquireTokenParameterBuilder1.ExecuteAsync(CancellationToken cancellationToken) at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder1.ExecuteAsync()
at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForWebAppWithAccountFromCacheAsync(IConfidentialClientApplication application, IAccount account, IEnumerable1 scopes, String authority, String userFlow) in E:\\GeoLogix\\Proj\\OpenSource\\MSAL\\0.4.0-preview-netcoreonly\\microsoft-identity-web-master\\src\\Microsoft.Identity.Web\\TokenAcquisition.cs:line 536 at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForWebAppWithAccountFromCacheAsync(IConfidentialClientApplication application, ClaimsPrincipal claimsPrincipal, IEnumerable1 scopes, String authority, String userFlow) in E:\GeoLogix\Proj\OpenSource\MSAL\0.4.0-preview-netcoreonly\microsoft-identity-web-master\src\Microsoft.Identity.Web\TokenAcquisition.cs:line 499
at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String tenant, String userFlow, ClaimsPrincipal user) in E:\GeoLogix\Proj\OpenSource\MSAL\0.4.0-preview-netcoreonly\microsoft-identity-web-master\src\Microsoft.Identity.Web\TokenAcquisition.cs:line 250

**Comment by jmprieur** [comment]
@rajeevchib : what do you mean by the cache entry expired? The cache entry will expire only if the token has expired or the session (in the case of a web app) expires, and in both cases the user needs to be challenged.

The recommendation is to have the serialization expiration (in this case the SQL database expiration delay) be bigger than the token expiry. If the database entry is deleted, then the token cache does no longer find the entry, whether or not the token had actually expired or not.

**Comment by rajeevchib** [comment]
Hi @jmprieur 

what do you mean by the cache entry expired? The cache entry will expire only if the token has expired or the session (in the case of a web app) expires, and in both cases the user needs to be challenged.
**The problem seems to occur when the token cache has expired, but the access token is still valid. Token cache is not automatically refreshed.
        Could you please elaborate on what you mean by session expiration? We don't use web session.**
        
The recommendation is to have the serialization expiration (in this case the SQL database expiration delay) be bigger than the token expiry. If the database entry is deleted, then the token cache does no longer find the entry, whether or not the token had actually expired or not.
        **If the access token expiration is 10 min and SQL Cache token expiration is 15 mins, the application works upto 15 mins and automatic renewal of the access token doesn't happen after 15 mins.**

**Comment by jmprieur** [comment]
Thanks for the update, @rajeevchib 
we've updated the wiki to

**Comment by rajeevchib** [comment]
Hi @jmprieur,

The solution you are recommending does not help us. May be We are missing something.

Actually we already tried setting DefaultSlidingExpiration more than Access Token Expiration.
In that case, we get MSALUIRequiredException in GetAccessTokenForUserAsync after DefaultSlidingExpiration.

e.g. Access Token Expiration is 1 hour and SQL Cache token expiration is 90 mins, the application works upto 90 mins and automatic renewal of the access token doesn't happen after 90 mins.

Please let me know if you need any clarification further.

**Comment by jmprieur** [comment]
Thanks for clarifying, @rajeevchib. I understand better now.

**Comment by rajeevchib** [comment]
Hi @jmprieur 

Thanks for the update. 

So, Are we going to re-open this issue OR need to create another issue?

**Comment by jmprieur** [comment]
@rajeevchib : I've created https://github.com/AzureAD/microsoft-identity-web/issues/919 for this
