### ISSUE TITLE
[Bug] Cannot acquire token to call API from another API

### ISSUE THREAD

**Issue by edkar-guber-issoft** [AzureAD/microsoft-identity-web#912]
**Which version of Microsoft Identity Web are you using?**
_**The latest one: Microsoft Identity Web 1.5.1**_

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] **Protected web APIs call downstream web APIs**
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
c. This is a new app

**Repro**

I have 3 apps: Web app -> API -> API
Web app sings in users and then make a request to the first API on behalf of the user (this part works). Then the first api should call the second API. For the sake of simplicity, the flow is **Web UI -> Middle API -> Data API**
Middle API & Data API have their own access_as_user scopes.
Web UI accepts access_as_user scope from Middle API, Middle API accepts access_as_user scope from Data API.
Middle API successfully authenticates requests from Web UI, but then I get the error when trying to acquire access token to call Data API from Middle API. 
The error: 
```
Microsoft.Identity.Client.MsalServiceException: 'AADB2C90086: The supplied grant_type [urn:ietf:params:oauth:grant-type:jwt-bearer] is not supported.
Correlation ID: c24294c9-2d0b-41cb-b889-fc57c44af0b6
Timestamp: 2021-01-29 17:57:53Z
```

Code from first "Middle" API:
Startup registration (I get this from https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis)
```csharp
services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAdB2C")
				.EnableTokenAcquisitionToCallDownstreamApi()
				.AddInMemoryTokenCaches();
```
Configuration for Azure B2C contains:
```
    "Instance": "https://-.b2clogin.com",
    "ClientId": "{my middle api client id}",
    "Domain": "-.onmicrosoft.com",
    "SignedOutCallbackPath": "/signout/B2C_1_local_signin",  //not sure if it's necessary for api, but I left it so far
    "SignUpSignInPolicyId": "B2C_1_local_signin", //not sure if it's necessary for api, but I left it so far
    "ClientSecret": "{middle api client secret}"
```
Token acquision:

var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(new List<string> 
	            { "https://{my tenant name}.onmicrosoft.com/{data API client id}/access_as_user" });

**Expected behavior**
Looks like I should easily obtain access token to call the next downstream api, but unfortunately, I've got the error described above.
Expectation: receiving access token by calling _tokenAcquisition.GetAccessTokenForUserAsync
Maybe the problem somewhere on Azure B2C side, maybe I have missed something in azure b2c app settings, idk.

**Actual behavior**
Microsoft.Identity.Client.MsalServiceException: 'AADB2C90086: The supplied grant_type [urn:ietf:params:oauth:grant-type:jwt-bearer] is not supported.

**Comment by jmprieur** [comment]
@edkar-guber-issoft 
the B2C service does not support the On behalf of flow which is required for a web api to call a downstream API.

See also https://github.com/AzureAD/microsoft-identity-web/wiki/1.0.0#case-of-an-azure-ad-b2c-app which shows this graphically.

**Comment by edkar-guber-issoft** [comment]
@jmprieur thank you for the quick response! could you point me what are workarounds might be in that case? is it possible to use service-to-service call (on behalf of the application) with Microsoft Identity Web in this scenario?

**Comment by jmprieur** [comment]
@edkar-guber-issoft: It's possible with Azure AD, but not with Azure AD B2C, sorry.
@nickgmicrosoft FYI and if you want to comment

**Comment by jmprieur** [comment]
@edkar-guber-issoft: This is now documented in https://github.com/AzureAD/microsoft-identity-web/wiki/b2c-limitations#azure-ad-b2c-protected-web-apis-cannot-call-downstream-apis

**Comment by edkar-guber-issoft** [comment]
@jmprieur thank you!
