### ISSUE TITLE
[Bug] custom host redirect uri is not working for ConfidentialClientApplicationBuilder

### ISSUE THREAD

**Issue by flytiny** [AzureAD/microsoft-identity-web#918]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Microsoft.Identity.Client 4.24.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [x] Distributed caches
* Other (please describe)

 We deploy our service to Azure app service, and we config an Azure Front Door with a custom cname.
 Currently we only want user to access our cname not Azure Front Door uri or ASE uri.

 So we config the ConfidentialClientApplicationBuilder reply uri with our cname uri not ASE uri, but the request to AAD login page will always be configed with the ASE redirect uri.

**Is this a new or an existing app?**

It's a new app and we just deploy it to Azure app service.

**Repro**

```csharp
string redirectUri = "https://****.microsoft.com/signin-oidc";

var builder = ConfidentialClientApplicationBuilder
  .Create(this.configuration[IWConstants.ClientId])
  .WithClientName(Service)
  .WithClientVersion(version)
  .WithAuthority(uri, true)
  .WithLogging(this.LogCallback)
  .WithTenantId(tenantId)
  .WithCertificate(appCert)
  .WithRedirectUri(redirectUri);
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).
The redirect uri shoule be "https://****.microsoft.com/signin-oidc" in my code.

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.
![image](https://user-images.githubusercontent.com/6790396/106559300-2eb7df00-6560-11eb-84bf-e50c922c4e26.png)
The redirect uri is still ASE uri, not the cname redirectUri in my code.

**Possible solution**

Currentlly I can only modify OpenIdConnectEvents RedirectToIdentityProvider function to change the redirect uri. But it's definitely a bad solution.
```csharp
string redirectUri = "https://****.microsoft.com/signin-oidc";
context.ProtocolMessage.RedirectUri = redirectUri;
```

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment]
@flytiny: I'm a bit confused by your question, and have a few questions for you to narrow down the issue and help you at best:
1. Are you using App Services **authentication** (Easy Auth), or just hosting your web app in App services?
   - if you are using App Services **authentication**, then the token is obtained by EasyAuth, and the redirect URI is managed by EasyAuth.
2. Are you using Microsoft.Identity.Web ? You mentioned that you *configured MSAL.NET redirect URI*, do you mean you don't use Microsoft.Identity.Web? or you do and forked the code? 
- If you use Microsoft.Identity.Web (this is the repo where you raised the issue)
  - you shouldn't need to configure MSAL.NET at all. Microsoft.Identity.Web is a higher level API on top of it. See the explanation below.
  - did your read: https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers?
- If you are not using Microsoft.Identity.Web, we'd need to understand more about what gets the auth code (see below)

### About the auth code grant, and the redirect URI
In ASP.NET Core web apps, the ASP.NET Core middleware requests the auth code when you sign-in users (first leg of the [Auth Code grant](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-auth-code-flow)), and this is the part that sets the redirect URI.  Then MSAL.NET is involved only for the second leg of the Auth Code Flow: the redemption of the code.
This means the redirect URI is never used by MSAL.NET in confidential client applications. ASP.NET Core does use it to decide where to get the auth code back.

**Comment by jmprieur** [comment]
Closing as it requires more info.
Feel free to reopen if you wish / need to
