### ISSUE TITLE
[Bug] Distributed SQL does not seem to respect the sliding window.

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#919]
**Which version of Microsoft Identity Web are you using?**
See https://github.com/AzureAD/microsoft-identity-web/issues/908

**Comment by rajeev16mca2k5** [comment]
> **Which version of Microsoft Identity Web are you using?**
> See #908

Hi @jmprieur 

Thanks for update.

We are using Microsoft.Identity.Web and Microsoft.Identity.Web.UI V1.4.1.

**Comment by jmprieur** [comment]
@rajeev16mca2k5 
Did you try with setting the MsalDistributedTokenCacheAdapterOptions as well?:

```CSharp
// or use a distributed Token Cache by adding
    services.AddMicrosoftIdentityWebAppAuthentication(Configuration);
            .EnableTokenAcquisitionToCallDownstreamApi(new string[] { scopesToRequest })
               .AddDistributedTokenCaches();

// For instance the distributed in memory cache (not cleared when you stop the app)
services.AddDistributedMemoryCache()

// Or even a SQL Server token cache
services.AddDistributedSqlServerCache(options =>
{
 options.ConnectionString = _config["DistCache_ConnectionString"];
 options.SchemaName = "dbo";
 options.TableName = "TestCache";

 // You don't want the SQL token cache to be purged before the access token has expired. Usually
 // access tokens expire after 1 hours (but this can be changed by token lifetime policies), whereas
 // the default sliding expiration for the distributed SQL database is 20 mins. 
 // Use a value which is above 60 mins (or the lifetime of a token in case of longer lived tokens)
 options.DefaultSlidingExpiration = expiry;
});

// Set the expiry of the MSAL distributed token cache to 90 mins
TimeSpan expiry = TimeSpan.FromMinutes(90);
services.Configure<MsalDistributedTokenCacheAdapterOptions>(options => { options.SlidingExpiration = expiry;});
```

**Comment by rajeevchib** [comment]
> 
> 
> @rajeev16mca2k5
> Did you try with setting the MsalDistributedTokenCacheAdapterOptions as well?:
> 
> ```cs
> // or use a distributed Token Cache by adding
>     services.AddMicrosoftIdentityWebAppAuthentication(Configuration);
>             .EnableTokenAcquisitionToCallDownstreamApi(new string[] { scopesToRequest })
>                .AddDistributedTokenCaches();
> 
> // For instance the distributed in memory cache (not cleared when you stop the app)
> services.AddDistributedMemoryCache()
> 
> // Or even a SQL Server token cache
> services.AddDistributedSqlServerCache(options =>
> {
>  options.ConnectionString = _config["DistCache_ConnectionString"];
>  options.SchemaName = "dbo";
>  options.TableName = "TestCache";
> 
>  // You don't want the SQL token cache to be purged before the access token has expired. Usually
>  // access tokens expire after 1 hours (but this can be changed by token lifetime policies), whereas
>  // the default sliding expiration for the distributed SQL database is 20 mins. 
>  // Use a value which is above 60 mins (or the lifetime of a token in case of longer lived tokens)
>  options.DefaultSlidingExpiration = expiry;
> });
> 
> // Set the expiry of the MSAL distributed token cache to 90 mins
> TimeSpan expiry = TimeSpan.FromMinutes(90);
> services.Configure<MsalDistributedTokenCacheAdapterOptions>(options => { options.SlidingExpiration = expiry;});
> ```

Hi @jmprieur 

I will try and let you know.

**Comment by rajeevchib** [comment]
> 
> 
> > @rajeev16mca2k5
> > Did you try with setting the MsalDistributedTokenCacheAdapterOptions as well?:
> > ```cs
> > // or use a distributed Token Cache by adding
> >     services.AddMicrosoftIdentityWebAppAuthentication(Configuration);
> >             .EnableTokenAcquisitionToCallDownstreamApi(new string[] { scopesToRequest })
> >                .AddDistributedTokenCaches();
> > 
**We have same block of code as above.**
> > // For instance the distributed in memory cache (not cleared when you stop the app)
> > services.AddDistributedMemoryCache()
> > 
**Since we are using SQL Server token cache, we are not using code above and using the code just below this comment.
We declared expiry variable just before this code to use it for AddDistributedSqlServerCache and MsalDistributedTokenCacheAdapterOptions.**
> > // Or even a SQL Server token cache
> > services.AddDistributedSqlServerCache(options =>
> > {
> >  options.ConnectionString = _config["DistCache_ConnectionString"];
> >  options.SchemaName = "dbo";
> >  options.TableName = "TestCache";
> > 
> >  // You don't want the SQL token cache to be purged before the access token has expired. Usually
> >  // access tokens expire after 1 hours (but this can be changed by token lifetime policies), whereas
> >  // the default sliding expiration for the distributed SQL database is 20 mins. 
> >  // Use a value which is above 60 mins (or the lifetime of a token in case of longer lived tokens)
> >  options.DefaultSlidingExpiration = expiry;
> > });
> > 
> > // Set the expiry of the MSAL distributed token cache to 90 mins
> > TimeSpan expiry = TimeSpan.FromMinutes(90);
> > services.Configure<MsalDistributedTokenCacheAdapterOptions>(options => { options.SlidingExpiration = expiry;});
> > ```
> 
> Hi @jmprieur
> 
> I will try and let you know.


Hi @jmprieur 

Please check my replies in bold.

**We tried the experiment with Access Token Expiry to 10 mins and SQL Token Cache Expiration to 15 mins and still we get MSALUIRequiredException after 15 mins of inactivity.**

**Comment by rajeevchib** [comment]
Hi @jmprieur 

Wound you have some time frame for delivery of this fix? We initially reported this to Microsoft in Oct 2020.

**Comment by rajeevchib** [comment]
Hi @jmprieur

Just a reminder that we have been waiting for this issue to be action-ed. 
Just curious to know, if its in the plan to get fixed sooner?

**Comment by jmprieur** [comment]
@rajeevchib. thanks for the heads-up
We'll have a deeper look at it in the release after next (next is imminent)

**Comment by rajeevchib** [comment]
@jmprieur 

Thanks for the update. 

Unfortunately this is holding up testing of our docker application with multiple instances accessing the same token cache store.

**Comment by jmprieur** [comment]
This seems to be fixed. See https://github.com/AzureAD/microsoft-identity-web/wiki/L1-Cache-in-Distributed-(L2)-Token-Cache

**Comment by rajeevchib** [comment]
Hi @jmprieur 

Great News, Thanks for the update. 
Unfortunately we are in middle of couple of projects. 
We will try this after finishing those activities and will update you.
