### ISSUE TITLE
[Feature Request] Server-side support for Continuous Access Evalutation

### ISSUE THREAD

**Issue by hajekj** [AzureAD/microsoft-identity-web#922]
**Is your feature request related to a problem? Please describe.**
It would be great if this library supported an attribute which could enforce the user to have used MFA for authentication or that their password has been explicitly entered in the past 30 minutes (basically forcing re-authentication).

**Describe the solution you'd like**
Have an attribute which can enforce re-authentication like:
```
[RequireReauthentication(int timeElapsedSinceLast]
```

Support for requiring a specific set of authentication methods ([currently supported methods](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#the-amr-claim)):
```
[RequireAuthenticationMethod(string[] authenticationMethods]
```

Additionally support for maximum token lifetime (crucial part of CAE):
```
[RequireMaximumTokenAge(int seconds)]
```

In client-facing application the response should be redirection to AAD with proper parameters to obtain the right token (this is probably going to be more complex since HttpContext.User.Identities get populated when the `id_token` arrives but not updated with token refresh, so we would need to obtain the token age information from MSAL's accounts info.

For API-based endpoints the response should be HTTP 401 with `WWW-Authenticate` header ([docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-resilience-continuous-access-evaluation)):
```
HTTP 401; Unauthorized
WWW-Authenticate=Bearer
  authorization_uri="https://login.windows.net/common/oauth2/authorize",
  error="insufficient_claims",
  claims="eyJhY2Nlc3NfdG9rZW4iOnsibmJmIjp7ImVzc2VudGlhbCI6dHJ1ZSwgInZhbHVlIjoiMTYwNDEwNjY1MSJ9fX0="
```

**Describe alternatives you've considered**
I have written some basic re-authentication code and published it on my [blog](https://hajekj.net/2017/03/06/forcing-reauthentication-with-azure-ad/), so it is something which could be used as a starting point.

**Additional context**
I am not really sure whether it is not a really big overkill set of features, but I think it could come in really handy for other developers and eventually help making CAE and some advanced secured authentication scenarios more accessible.

**Comment by cristianhosu** [comment]
Couldn't this be achieved by using a smaller token lifetime (access token & refresh token) and also by enforcing MFA in Azure AD?

**Comment by hajekj** [comment]
Yes, it can be achieved quite easily when you are building a single tenant application. When you are building a SaaS multi-tenant application (which I primarily focus on), as a developer, you don't have control over the token lifetimes etc. configured in the target tenant consuming your app.

**Comment by jmprieur** [comment]
Thanks @hajekj 
The team has been working on an alternative which does require pulling reauthenticating, but does the just in time evaluation. It might come public later.

**Comment by jmprieur** [comment]
Closing as external (MISE)
