### ISSUE TITLE
Microsoft.Identity.Web.MicrosoftGraph vs Microsoft.Graph?

### ISSUE THREAD

**Issue by felinepc** [AzureAD/microsoft-identity-web#936]
As a new ASP.NET Core developer I'm getting confused by all these different identity and graph related packages.

My user sign-ins are already handled via Identity Server integrated with Microsoft Identity Platform and ASP.NET Core Identity. So I do not need sign-in UIs any more.

Additionally, during user's sign-ins I also already saved their access and refresh tokens using ASP.NET Core Identity.

Now the only thing I really need is to access the Graph API on behalf of these users in the background.

Should I use ```Microsoft.Identity.Web.MicrosoftGraph``` or ```Microsoft.Graph``` for this purpose?

**Comment by jmprieur** [comment]
@felinepc
You're right, if you already have tokens from IdentityServer, you don't really need Microsoft.Identity.Web (although it abstract things nicely, on provides a load of additional features like incremental consent and conditional access management). You could use MicrosoftGraph directly by implementing a class inheriting from `IAuthenticationProvider`. Microsoft.Identity.Web provides one ([TokenAcquisitionAuthenticationProvider](https://github.com/AzureAD/microsoft-identity-web/blob/68a2cb3afda3c1a38d7d17c5db6e34e506ce901c/src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs)) which delegates the token acquisition to MSAL.NET.

What matters is that you set the Authentication header like in: https://github.com/AzureAD/microsoft-identity-web/blob/68a2cb3afda3c1a38d7d17c5db6e34e506ce901c/src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs#L60

But note that you'll need to refresh your token yourself. Maybe you'd want to use MSAL for that, calling AcquireTokenByRefreshToken the first time, and then AcquireTokenSilent (See [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration#adal-to-msal-migration))

How frequent do you think this scenario is? is the refresh token stored somewhere in ASP.NET Core? and in this case, how to you access it (what's the code to access it). Maybe we could make it easier for you (that is let you use Microsoft.Identity.Web by having it detect the presence of this refresh token and have MSAL store it and refresh it for you. What do you think @jennyf19 ?

**Comment by felinepc** [comment]
@jmprieur Thank you for taking your time to evaluation my use case. I feel that this is a valid one so I'll explain it in more details.

As you know, when we use IdentityServer integrated with ASP.NET Core's standard OIDC client middleware, we can specify ```SaveTokens = true```, and that gives us access to all the tokens returned by Microsoft at sign-in time via a temporary cookie. 

When we use ASP.NET Core Identity + EF Core as the integrated user store for IdentityServer, it offers this convenient one-liner method ```SignInManager.UpdateExternalAuthenticationTokensAsync``` that persists these tokens directly into the Identity database, in a table called ```AspNetUserTokens```. 

This table allows us to associate a user's tokens by the user ID, and the tokens persisted by Identity's helper method even includes an ```expires_at```  item, which shows when the access token would expire.

So now that we have the tokens nicely in database already, what I ideally need, is a convenient way to run ```GraphServiceClient``` that allows me to pass in a user ID as a parameter, and have the client retrieve the access token from the database – and if it already expired, refresh it, update the database and return the fresh access token.

I have managed to do so thus far using such a flow:

1. I created a simple ```GetAccessToken``` API controller on my IdentityServer instance, that takes in the user's ID, and returns its access token. It's this controller that manages the expiration/refreshing logic. It first looks at the ```expires_at`` value in the database, if not expired, returns existing token; if expiring/expired, get a new one from Microsoft's token endpoint, then update the database (with new refresh token, access token, and expires_at).

Thankfully the IdentityServer folks made this ```IdentityModel``` library that makes refreshing token against Microsoft's ```/common/v2.0/``` endpoint relatively easy.

Note that I opted to not give my application direct access to the ```AspNetUserTokens``` table/database, hence the API, for better separation of concerns. HOWEVER, if using a library can significantly streamline token management for me, I'm down to giving it access to the database.

2. Now to use ```Microsoft.Graph```, I initialize it with:

```
var graphClient = new GraphServiceClient(authenticationProvider: null);
```
Then I pass in the ```token``` (by calling my ```GetAccessToken``` API with a http client, which should always hand me a valid token):
```
var requestHeaders = new List<HeaderOption>() { new HeaderOption("Authorization", "Bearer " + token) };
var me = await graphClient.Me.Request(requestHeaders).GetAsync();
```
So this does seem to work. But I honestly have no clue if this setup of mine can scale well, because I'll need to make Graph API calls on behalf of potentially tens of thousands of users, many of them concurrently at set intervals.

And of course I see that MS's existing packages seem to automate/streamline this process, and their logic/process must be a lot more sophisticated than mine. I just can't find a way to take advantage of them using my current setup.

Your advice would be greatly appreciated!

**Comment by jennyf19** [comment]
closing, unless @felinepc needs more assistance.
