### ISSUE TITLE
Access Sign Up Directly From Web App

### ISSUE THREAD

**Issue by SwagStork** [AzureAD/microsoft-identity-web#938]
Currently, the web app documentation shows a "Sign In / Up" button, however there are many instances where it would be beneficial to send the user directly to the Sign Up page. However, I cannot seem to figure out how to do that.

Is this possible with Microsoft Identity Web?

 If so, I would be happy to add to the docs to help others learn as well.

**Comment by jmprieur** [comment]
@SwagStork : You are right. That's not what Microsoft identity web does today.
There is a PR, however, proposed by @dan-giddins to achieve the same, and which we still need to look at more deeply, 
https://github.com/AzureAD/microsoft-identity-web/pull/854

**Comment by MarcAnnous** [comment]
Would be helpful indeed. Thank you @dan-giddins and @jmprieur .

**Comment by TMUNYU** [comment]
How far with the PR @jmprieur. Do we have a potential ETA on this?

**Comment by dan-giddins** [comment]
I have updated my PR #968 off the current master branch, and managed to get it working again.

**Comment by jmprieur** [comment]
This is done service side (AAD/AAD B2C), by providing a sign-up UI.
Closing for now
