### ISSUE TITLE
[Bug] Microsoft.Identity.Web doesn't initialize a redis cache until an IDistributedCache is used elsewhere in the code

### ISSUE THREAD

**Issue by FourierTransformer** [AzureAD/microsoft-identity-web#944]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.5.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [x] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [x] Distributed caches
* Other (please describe)

a. This is an existing app that I am trying to add a distributed cache to.

**Repro**

```csharp
services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd")
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddMicrosoftGraphAppOnly(authProvider => new GraphServiceClient(authProvider))
    .AddDistributedTokenCaches();

services.AddStackExchangeRedisCache(options =>
    {
        options.ConfigurationOptions = ConfigurationOptions.Parse("localhost");
    });
```
1. Login to the site
2. Check redis to see if the `AppTokenCache` key have been created.

**Expected behavior**
I expect to see the token cache in the redis database right away after a user is logged in.

**Actual behavior**
I don't see the `AppTokenCache` in redis, until I hit a page that uses an `IDistributedCache`, at which point it initializes and then I see the `AppTokenCache` in redis.

**Additional context / logs / screenshots**
I'm thinking it's a bug, but it might just be I've initialized the DistributedTokenCache incorrectly. If that's the case, I was just following the docs, and they may require an update.

**Comment by jmprieur** [comment]
@FourierTransformer: Microsoft.Identity.Web will serialize to the distributed cache the first time there will be a token written to the cache. It's using a lazy principle.

Why would you want it to be initialized earlier? what is your specific scenario?

**Comment by FourierTransformer** [comment]
Ahh, I was confused, didn't realize it was lazy loading. Sorry about that.
