### ISSUE TITLE
Tests for TokenAcquisition (unit and/or integration)

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#95]
Add unit tests for
- TokenAcquisition

**Comment by jmprieur** [comment]
Closing duplicate https://github.com/AzureAD/microsoft-identity-web/issues/102

**Comment by jmprieur** [comment]
@jennyf19 to close if you feel that this is well covered.

**Comment by jennyf19** [comment]
i looked at this class, i think we are good.

**Comment by jennyf19** [comment]
Included in [0.4.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.4.0-preview)
