### ISSUE TITLE
[Feature Request] Productize the app provisionning prototype

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#954]
**Is your feature request related to a problem? Please describe.**
Visual Studio 16.9 will release in March without, by default, a way to create app and configure the appsettings.json files of applications. The plan is to have a pointer to a doc describing what to do, manually, or by running a command line app creation script as a dotnet global tool.

**Describe the solution you'd like**
A prototype exists of a tool that takes a project, infers its nature, creates an Azure AD or Azure AD B2C app, and updates the code. See https://github.com/jmprieur/app-provisonning-tool

**Work to do**
- [x] Fix all the warnings in the prototype (Jm)
- [x] Import the prototype (source and unit tests) into the Microsoft.Identity.Web Tools folder. Decide if we also want to import the integration tests, but they are costly.
- [ ] Improve the Unit tests
- [ x ] Update the release definition to be able to release a package with the tool. Do we want to brand the tool Microsoft.Identity.Web.something?
- [ ] Address the P0 and P1 issues in https://github.com/jmprieur/app-provisonning-tool/issues   
- [ ] Update the documentation

**Comment by jennyf19** [comment]
Included in [1.7.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.7.0)
