### ISSUE TITLE
[Feature Request] Support authentication scheme in all scenarios

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#955]
**Which version of Microsoft Identity Web are you using?**
4.16.0

**Repro**

Customers need to be able to implement apps which sign-in users with AAD and B2C, or which are web apps and web APIs. Today, the authentication scheme are supposed to help for this, but they are not taken into account everywhere.

See:
- https://github.com/AzureAD/microsoft-identity-web/issues/173
- https://github.com/AzureAD/microsoft-identity-web/issues/549
- https://github.com/AzureAD/microsoft-identity-web/issues/429
- https://github.com/AzureAD/microsoft-identity-web/issues/958
- https://github.com/AzureAD/microsoft-identity-web/issues/971
- https://github.com/AzureAD/microsoft-identity-web/issues/1126
- https://github.com/AzureAD/microsoft-identity-web/issues/1127
- https://developercommunity2.visualstudio.com/t/I-would-like-to-set-the-AddMicrosoftIden/1339302

This issue might be related: 
- https://github.com/AzureAD/microsoft-identity-web/issues/1164

**Expected behavior**
A fully functional sample of an AAD + B2C web app which also contains web APIS.

**Actual behavior**
See the referenced issues for repro steps

**Possible solution**
See investigation in branch https://github.com/AzureAD/microsoft-identity-web/tree/jmprieur/multipleSchemeInvestigation

**Comment by jennyf19** [comment]
@jmprieur we need to test the confidential client options, i had issues w/the unit tests and had to add `Instance` and `clientSecret`. just adding this as a reminder.

**Comment by jennyf19** [comment]
TODO:
- [ ] Create a wiki page
- [ ] We know PostConfigure() doesn't work - work in progress
- [ ] Check that the regular scenarios still work
- [ ] Run a -preview build

**Comment by jmprieur** [comment]
For Microsoft Graph, I wonder if we need to add a method so that controller actions which are called for a specific auth scheme can pass it, in to the Graph SDK:

`BaseRequestExtensions.WithAuthenticationScheme<T>(this T baseRequest, string authenticationScheme)`

This would have an impact in the Microsoft.Identity.Web.MicrosoftGraph assembly on:
- TokenAcquisitionAuthenticationProviderOption (new AuthenticationScheme property)
- TokenAcquisitionAuthenticationProvider adding an authenticationScheme member, and passing it through to the token acquisition methods (which now have it as a parameter)

**Comment by jennyf19** [comment]
Included in [1.11.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.11.0) and [documentation here](https://github.com/AzureAD/microsoft-identity-web/wiki/Multiple-Authentication-Schemes).
