### ISSUE TITLE
[Feature Request] Provide a more sophisticated token cache L1/L2 (L1 in InMemoryCache, L2 IDistributedCache, with encryption strategy)

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#957]
**Is your feature request related to a problem? Please describe.**
@henrik-me to update or @jennyf19 / @jmprieur  after discussing with @henrik-me and/or @GeoK

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**
See MISE

**Comment by damienbod** [comment]
It would be great that when the required access token has expired, or does not exist in the cache, the lib just tries to get a new access token. We do this with other OIDC, OAUTH clients. Would this be possible? 

Greetings Damien

**Comment by jmprieur** [comment]
@damienbod : in a web app? or in a web API?
in a web app, Microsoft.Identity.Web manages it already with the [AuthorizeForScopes] attribute. See https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

**Comment by damienbod** [comment]
Hi @jmprieur In both, I don't see this from the docs. But you say then that if I don't use a persistent cache, then I can use the  [AuthorizeForScopes] attribute on my API and it will get me a new token if the the cache has been reset?

Correct?

Thanks Damien

**Comment by jmprieur** [comment]
Thanks @damienbod 
this is on the backlog: https://github.com/AzureAD/microsoft-identity-web/issues/685
(today if you have a web API, you'd need handle the exception and pass it to ITokenAcquisition.ReplyForbiddenWithWwwAuthenticateHeaderAsync. See https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#handle-conditional-access

**Comment by jennyf19** [comment]
Included in [1.8.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.8.0)
