### ISSUE TITLE
[Documentation] provide client secrets by code

### ISSUE THREAD

**Issue by nevadawilliford** [AzureAD/microsoft-identity-web#960]
### Documentation related to component
Example / Question

### Please check all that apply

- [ ] typo
- [ X] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ X] needs an example

### Description of the issue
I'm looking for an official example of using Microsoft.Identity.Web where the client secret is not stored in the appsettings.json AzureAd section which is checked into source control. It's my understanding that it would not be best practice to check this client secret into source control given that's akin to a password. 

We have an application running using [this sample](https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo) which works great. The only thing we want to work different in this sample is we want to **NOT** store the ClientSecret in appsettings.json. 

I understand that I could use AzureKeyVault or use certificates as well. Those aren't options on the table for our team currently.  All I really want to do in this case is set the ClientSecret at runtime. We are running our app on prem in a Docker/Kubernetes environment using Rancher and can use the Secrets feature of Rancher to pull that secret at runtime. 

Can someone point me in the right direction? Is it just not possible to set the ClientSecret at runtime? Am I missing something?

**Comment by jmprieur** [comment]
@nevadawilliford : you might want to try (with Microsoft.Identity.Web 1.6.0 or later): 

```CSharp
     // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApi(Configuration)
                    .EnableTokenAcquisitionToCallDownstreamApi(options => {options.ClientSecret= "xxxxxxxx"})
                        .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                        .AddInMemoryTokenCaches();
```

**Comment by nevadawilliford** [comment]
@jmprieur Thanks so much for your prompt response. Your example with 1.6.0 worked perfectly. I was still running 1.5.1. 

I am using the user-secrets feature when running locally and that works well. No issues there. 

I'll talk to my team about using certificates again after reviewing the Wiki page you provided. 

Thanks again for the information. Very much appreciated.
