### ISSUE TITLE
[Bug] dotnet new blazorwasm --hosted generates broken code if --calls-graph is also used

### ISSUE THREAD

**Issue by sgesweinFusion** [AzureAD/microsoft-identity-web#962]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Latest blazorwasm project template, generated code uses Microsoft Identity Web 1.1.0

**Where is the issue?**
* Other (please describe)

On first Visual Studio build and run of a project generated with `dotnet new blazorwasm`, generated code fails to call the API in WeatherForecastController successfully when "Fetch data" is chosen in the hosted Blazor WASM client.

**Is this a new or an existing app?**
c. This is a new app or an experiment.
HOWEVER, having a newly-generated project work would be invaluable in refitting a production-track development app to use Microsoft Graph.

**Repro**
First, verify you can create a working sample using the steps at:
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0

Create app registrations as per "Register apps in AAD and create solution", and generate a Wasm5 project with a command line that looks like:
```
dotnet new blazorwasm -o Wasm5 --hosted -au SingleOrg ....
```
Verify the redirect URI appears as needed in the SPA platform configuration of the client app registration, and run from VS2019. Choosing "Fetch Data" in the sidebar successfully authenticates and shows results from WeatherForecastController call.

Next, generate a Wasm5Graph project by adding the --calls-graph switch to the command line used previously:
```
dotnet new blazorwasm -o Wasm5Graph --hosted --calls-graph -au SingleOrg ....
```
Start it up from VS2019, and verify the redirect URI as with the earlier example.

**Expected behavior**
Wasm5Graph should run as well as Wasm5 against the well-configured app registrations.

**Actual behavior**
Run fails at line of code generated (I believe)  by this line of the template:
https://github.com/AzureAD/microsoft-identity-web/blob/master/ProjectTemplates/templates/WebApi-CSharp/Controllers/WeatherForecastController.cs#L88

**Possible solution**
Generated code adds a `ClientSecret` with a bogus value to the server appsettings.json; I was able to add a real client secret from the server app registration to get past that. However, subsequent graph calls just return a 401 Unauthenticated error to the client... and now I turn to you.

The `dotnet new blazorwasm --help` documentation implies the --calls-graph switch works out-of-the-box to generate working code for  the hosted Blazor WASM on-behalf-of flow that I need. Maybe it shouldn't imply that.

**Additional context / logs / screenshots**
My immediate project-blocking need is for an example of working code for my scenario, preferably with steps that set up the app registrations appropriately for admin consent and admin-and-user consent scenarios. I discovered this issue by believing the dotnet new template would generate that working code for me...

Pointers to complete docs and samples for implementing the on-behalf-of flow, as of net5.0 and Microsoft.Identity.Web 1.5.1, from a Blazor WASM client to an API would be gratefully accepted as a first step toward a fix here.

**Comment by jmprieur** [comment]
@sgesweinFusion, did you try with the MIcrosoft.Identity.Web template (blazorwasm2 instead of blazorwasm)?

```CSharp
dotnet new blazorwasm2 -o Wasm5Graph --hosted --calls-graph -au SingleOrg ....
```

**Comment by sgesweinFusion** [comment]
There's a blazorwasm2?!? Didn't know that; I'll give it a spin later today.

Should I have that template installed with VS2019 16.8, or is there an installation I need to run first?

**Comment by jmprieur** [comment]
@sgesweinFusion : it will tell you to install Microsoft.Identity.Web.ProjectTemplates

**Comment by sgesweinFusion** [comment]
Just ran `dotnet new -i Microsoft.Identity.Web.ProjectTemplates` which did indeed make `dotnet new blazorwasm2 --help` respond as expected.

I think, at least, I'll now be working with the code we're best equipped to talk about here! Give me some hours to run through the new output, and I'll summarize my experience here.

**Comment by sgesweinFusion** [comment]
I appear to need to read some docs on the app registration setup expected by blazorwasm2 before I can verify if the code is broken or my setup.

As suggested, with the params I used to create a working hosted Blazor WASM app named Wasm5 (see above), I generated a new solution with the blazorwasm2 template:

 ```cs
dotnet new blazorwasm2 -o Wasm5Graph2 --hosted --calls-graph -au SingleOrg ....
```

In the Wasm5Graph2.Server project's, appsettings.Development.json, I added an AzureAd:ClientSecret override value from the server app registration's client secret.

Running the app and choosing Show Profile caused the login interaction (which includes two-factor on my tenant), but it completed with a failure dialog titled "Come back again later", with a message "You've hit our limit on text verification codes. Try to sign in again shortly." Any other auth interaction with my account works immediately upon completing two-factor, but I'm consistently hitting this message after entering the numeric code on any attempt to log into Wasm5Graph2. So I think I'm configured there for a viciously quick auth fail loop somehow.

I suspect I need a differently-configured client and/or server app registration, but am unsure what steps to follow to get to a known-good set of app registrations. What documentation am I missing?

**Comment by sgesweinFusion** [comment]
After some spelunking around the repo, it looks like the best approach for me to get working code for my use case is to start from scratch with new app registrations. I'm planning on trying this next to get to working code for a hosted Blazor WASM client that authenticates and calls the hosting Web API, which then uses claims appropriately to call Microsoft Graph on behalf of the Blazor-authenticated user.

The steps I'm planning:

- manually creating new app registrations for client and server by adapting Step 2 from here: https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-dotnet-native-aspnetcore-v2/2-web-api-now-calls-microsoft-graph/
- Making note of all the new app registration ids, etc. as the (old) blazorwasm template requires
- Running the (new) blazorwasm2 template to generate a new project.
- Verifying the generated appsettings.json files in both projects; I'm fairly sure there will be a tweak to make still on the server side to get ClientSecret properly configured.
- Launching the generated solution, clicking through to Show Profile, and rejoicing in the majesty of a successful Microsoft Graph call through the hosting API of a hosted Blazor WASM project.

Does that sound about right? Can anyone think of any tips/tricks/pitfalls I should be aware of before starting down this track?

**Comment by jennyf19** [comment]
Sorry we didn't get back to you @sgesweinFusion. I believe this is fixed in the .NET 6 templates. Please re-open if needed.
