### ISSUE TITLE
Integration tests for AuthorizeForScopesAttribute

### ISSUE THREAD

**Issue by pmaytak** [AzureAD/microsoft-identity-web#97]
Add unit tests for
- AuthorizeForScopesAttribute

**Comment by jennyf19** [comment]
Waiting on guidance from ASP NET

**Comment by jmprieur** [comment]
@jennyf19 : this is covered by you UI test. proposing to consider it as duplicate / fixed?

**Comment by jmprieur** [comment]
PR is: https://github.com/AzureAD/microsoft-identity-web/pull/556

**Comment by jennyf19** [comment]
Included in [0.4.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.4.0-preview)
