### ISSUE TITLE
[Bug] Typo (trailing comma) in Source for MicrosoftIdentityCircuitHandler.cs

### ISSUE THREAD

**Issue by sbitaxi** [AzureAD/microsoft-identity-web#970]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

Version 1.5.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

Typo in Source: MicrosoftIdentityCircuitHandler.cs
line 204
https://github.com/AzureAD/microsoft-identity-web/blob/bf8b06fa812521e99cd006edee8b50f100f0670c/src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs#L204

**Is this a new or an existing app?**
c. This is a new app or an experiment.

Building a Razor app using the webapp template with auth

**Repro**

```csharp
            string[] additionalBuiltInScopes =
            {
                 OidcConstants.ScopeOpenId,
                 OidcConstants.ScopeOfflineAccess,

                // Trailing comma here
                 OidcConstants.ScopeProfile,
            };
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.

**Possible solution**
Remove trailing comma

**Additional context / logs / screenshots**
I was trying to add the AddMicrosoftIdentityConsentHandler service to my app to address an authentication issue, but the app would not compile once I added this service. 

I reviewed the code to make sure I understood what it was doing and noticed the comma. I don't believe the issue is related as the error I receive is pertaining to AuthenticationStateProvider:

>  Innermost exception 	 System.InvalidOperationException : Unable to resolve service for type 'Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider' while attempting to activate 'Microsoft.Identity.Web.MicrosoftIdentityServiceHandler'.

**Comment by jmprieur** [comment]
Thanks for your feedback @sbitaxi 
This is valid syntax in C# (and we build Microsoft.Identity.Web every day :)). Your issue's cause is somewhere else.

**Comment by sbitaxi** [comment]
Noted. I'll stay out of it until I know what I'm doing.

Thank you for the constructive feedback!
