### ISSUE TITLE
[Bug] unsupported_grant_type error when AAD B2C web app signs in users & acquires tokens on behalf of web app call downstream APIs

### ISSUE THREAD

**Issue by jonschoning** [AzureAD/microsoft-identity-web#972]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Microsoft.Identity.Web 1.6.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)
  * [x] AAD B2C web app which signs in users, acquires tokens on behalf of web app call downstream APIs (client credential flow) 

**Is this a new or an existing app?**
This is a new app

**Repro**

```csharp
                services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApp(Configuration, "AzureAdB2C")
                        .EnableTokenAcquisitionToCallDownstreamApi()
                        .AddInMemoryTokenCaches();

```

`ClientSecret` is included in `AzureAdB2C` config.
AdB2C App is using custom policies
```
  "AzureAdB2C": {
    "Instance": ...,
    "ClientId": "...",
    "CallbackPath": ...,
    "Domain": ...,
    "SignUpSignInPolicyId": ...,
    "ResetPasswordPolicyId": ...,
    "ClientSecret": ...,
  },

```

**Expected behavior**
AAD B2C  users are signed in and downstream APIs are called on behalf of the application

**Actual behavior**
{"error":"unsupported_grant_type","error_description":"AADB2C90086: The supplied grant_type [client_credentials] is not supported.\r\nCorrelation ID: 407e5930-73ae-4807-84a9-d2d8d2c40313\r\nTimestamp: 2021-02-15 23:23:15Z\r\n"}

**Comment by jmprieur** [comment]
@jonschoning what did you use in your controller?
Did you call AcquireTokenForApp ? 

If you want to sign-in users and not call downstream APIs, you should remove the client secret.

If you call an API, this can only be done on behalf of the signed-in user. Indeed, Azure AD B2C does not support the client credentials: See https://github.com/AzureAD/microsoft-identity-web/wiki/b2c-limitations#you-cannot-use-itokenacquisitiongettokenforappasync-or-idownstreamapicallwebapiforappasync-in-azure-ad-b2c-web-apps
