### ISSUE TITLE
[Bug] CompactToken parsing failed with error code: 80049217

### ISSUE THREAD

**Issue by beckerben** [AzureAD/microsoft-identity-web#979]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.6.0

**Where is the issue?**
I was running the test "BlazorServerCallsGraph", i updated with my client id, app secret and tenant and it works great when run locally.  I then deployed the app to an Azure App and the "Profile" and "Call Web API" calls do not work when running up on Azure.  I see this error in the browser console:
```
Microsoft.Graph.ServiceException: Code: InvalidAuthenticationToken
Message: CompactToken parsing failed with error code: 80049217
```

* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x] Protected web APIs call downstream web APIs
* Token cache serialization
     * [x] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is literally your sample "BlazorServerCallsGraph" when deploying to Azure App.  Is there something special that needs to be setup in the App for this to be deployed to Azure?  I have the "additionalLoginParams": ["response_type=code id_token","resource=https://graph.microsoft.com"] set in the config\authsettings of the app on Azure, and the access_token looks valid when running it through jtw.ms, but something is still off. 

**Repro**

**Expected behavior**
I would expect the sample test you guys provided to work when published to an azure app, it does not!

**Actual behavior**
Error message received as indicated above, again, works great when running in localhost, but when I publish to Azure App, it does not work.  

**Possible solution**
N/A

**Additional context / logs / screenshots**
![image](https://user-images.githubusercontent.com/143489/108154429-d7128b00-70aa-11eb-864c-b591918a9890.png)

![image](https://user-images.githubusercontent.com/143489/108154411-cf52e680-70aa-11eb-959b-9328ea5859a1.png)

**Comment by beckerben** [comment]
As a follow up, I did refer to this article here: 

https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=command-line

I think it is very interesting it states this (which I have done):

>  Important
If you don't configure App Service to return a usable access token, you receive a CompactToken parsing failed with error code: 80049217 error when you call Microsoft Graph APIs in your code.

This is the error I am getting and my problem does exist when publishing to the App Service...I have re-setup the App Service twice following the instructions on the site there and same issue happens here.  Appreciate any advice since this is impacting me in another app I am trying to deploy to Azure with the same issue here.

**Comment by jmprieur** [comment]
@beckerben 
Yes, it seems that you don't get the right token from app service authentication (code name easy auth)

When you deploy to app service, given that you are using Microsoft.Identity.Web and have already configured you application with a client ID etc, you **shouldn't need** to configure app service authentication. Do you really need to enable it?

**Comment by beckerben** [comment]
@jmprieur That is a brilliant question.  After thinking about it more, I don't think I do need the app service authentication turned on in the app.  I disabled this and things work as they should.  

However, in theory, using both Microsoft.Identity.Web and the App Service Authorization should work, correct?  I conclude this from this snippet from the [prior mentioned documentation](https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=command-line):

> Using the Microsoft.Identity.Web library, the web app gets an access token for authentication with Microsoft Graph. In version 1.2.0 and later, the Microsoft.Identity.Web library integrates with and can run alongside the App Service authentication/authorization module. Microsoft.Identity.Web detects that the web app is hosted in App Service and gets the access token from the App Service authentication/authorization module. The access token is then passed along to authenticated requests with the Microsoft Graph API.

**Comment by jmprieur** [comment]
Yes, @beckerben : they should work together, but EasyAuth is for simple scenarios. you quickly get the limit (and the usable token thing is one of the issue). 
It seems, that, for some reason, the token that Easy Auth gets for you is wrong. I would actually like to repro your issue. Would you have repro steps?

**Comment by beckerben** [comment]
@jmprieur basically follow the steps [outlined here](https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service) to set the app registration up in Azure and then you publish the "BlazorServerCallsGraph" test project to it.  This will replicate the issue.

**Comment by jmprieur** [comment]
@navyasric, do you want to have a look? this is the Azure day 1 scenario.

**Comment by jennyf19** [comment]
@navyasric please see above. thank you.

**Comment by jmprieur** [comment]
After connecting with the App service team, it appears that this shouldn't happen
@beckerben does this still repro? 
If this still repro, could you still try so that App service have recent logs?

Closing as I'm assuming this doesn't happen any longer but fee free to reopen if this still reproes

**Comment by SquallHalle** [comment]
Hi,

i got an ASPNetCore 3.1 Application and inside i use a self-wirtten-libary to call some azure graph functions via Microsoft.Graph package.  I use ASPNetCore as Backende while i serve a SPA written in VUE and Auth is done via keycloak.
So maybe that's the wrong place to answer but the pattern of my problem is kind of the same. 
On my local Maschine everything runs alright but as soon as i publish it to an AzureWebApp i also get the same error
```
Microsoft.Graph.ServiceException: Code: InvalidAuthenticationToken
Message: CompactToken parsing failed with error code: 80049217
```
Let me know if i am wrong here or you need more information's.

**Comment by jmprieur** [comment]
@SquallHalle : I think you might be missing this step: https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=azure-resource-explorer%2Ccommand-line#configure-app-service-to-return-a-usable-access-token

**Comment by SquallHalle** [comment]
hey @jmprieur  thanks for you answer. 
No actually my config looks like this:
```
    "identityProviders": {
      "azureActiveDirectory": {
        "enabled": true,
        "registration": {},
        "login": {
          "loginParameters": [
            "response_type=code id_token",
            "resource=00000003-0000-0000-c000-000000000000"
          ],
          "disableWWWAuthenticate": false
        },
        "validation": {
          "jwtClaimChecks": {},
          "defaultAuthorizationPolicy": {
            "allowedPrincipals": {}
          }
        }
      }
```

so i guess that should be right. 
but also may i am wrong here, course i dont use azure to auth my webapp but just a lib i use inside the webapp-backend and to me this chnage looks like its needed if you use the  azure-auth directly in the webapp for userers or such.

Greetings

**Comment by kalimuthu-zluri** [comment]
thank @beckerben you saved m day today
