### ISSUE TITLE
Blazor MsalUiRequiredException & ConsentHandler loop trying to set up conditional consent

### ISSUE THREAD

**Issue by Robosanta** [AzureAD/microsoft-identity-web#985]
I'm relatively new to .NET core development and I've been trying to set up Incremental Consent and Conditional Access for my blazor application to be able to generate tokens using Token Acquisition and call Microsoft Graph down the line. I've read the issues posted here and the solutions and have tried the many attempts. Setting up a ConsentHandler in my razor pages seemed to be the fix for Blazor in many of these instances, but at this point the application enters a loop of trying to authenticate the user until it bounces the user out saying "We couldn't sign you in. Please try again.", or (with authentication configured to use my registered app in Azure) it refuses to auth me in and redirects me to the <unauthorized> component. If I remove the ConsentHandler it just throws an MsalUiRequiredException.
To add the expected behavior works as intended locally, but fails as a webApp on azure.

Expected Behavior: 
- Call GraphAPI.me & .user
- return an access token when requested

Current Behavior (from log stream in Azure):

With Authentication configured on azure (Or without ConsentHandler):
IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent.

With ConsentHandler and no Authentication Configured on Azure:
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.System.Exception: An error was encountered while handling the remote login.---> MSAL.NetCore.4.24.0.0.MsalServiceException:ErrorCode: invalid_clientMicrosoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS500112: The reply address 'https://replyUrlNotSet' does not match the reply address 'https://{url}/signin-oidc' provided when requesting Authorization code.Trace ID: d2d52785-d5b7-4be8-8cc9-e8e9e1772100Correlation ID: 113c1960-ea07-439d-bba7-30a428efa2c1Timestamp: 2021-02-18 02:19:47Zat Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)at Microsoft.Identity.Client.Internal.Requests.ConfidentialAuthCodeRequest.ExecuteAsync(CancellationToken cancellationToken)at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByAuthorizationCodeParameters authorizationCodeParameters, CancellationToken cancellationToken)at Microsoft.Identity.Web.TokenAcquisition.AddAccountToCacheFromAuthorizationCodeAsync(AuthorizationCodeReceivedContext context, IEnumerable`1 scopes)at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder.<>c__DisplayClass10_1.<<WebAppCallsWebApiImplementation>b__1>d.MoveNext()--- End of stack trace from previous location ---at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RunAuthorizationCodeReceivedEventAsync(OpenIdConnectMessage authorizationResponse, ClaimsPrincipal user, AuthenticationProperties properties, JwtSecurityToken jwt)at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()StatusCode: 400ResponseBody: {"error":"invalid_client","error_description":"AADSTS500112: The reply address 'https://replyUrlNotSet' does not match the reply address 'https://{url}/signin-oidc' provided when requesting Authorization code.\r\nTrace ID: d2d52785-d5b7-4be8-8cc9-e8e9e1772100\r\nCorrelation ID: 113c1960-ea07-439d-bba7-30a428efa2c1\r\nTimestamp: 2021-02-18 02:19:47Z","error_codes":[500112],"timestamp":"2021-02-18 02:19:47Z","trace_id":"d2d52785-d5b7-4be8-8cc9-e8e9e1772100","correlation_id":"113c1960-ea07-439d-bba7-30a428efa2c1"}Headers: Cache-Control: no-store, no-cachePragma: no-cacheStrict-Transport-Security: max-age=31536000; includeSubDomainsX-Content-Type-Options: nosniffP3P: CP="DSP CUR OTPi IND OTRi ONL FIN"client-request-id: 113c1960-ea07-439d-bba7-30a428efa2c1x-ms-request-id: d2d52785-d5b7-4be8-8cc9-e8e9e1772100x-ms-ests-server: 2.1.11496.5 - WUS2 ProdSlicesx-ms-clitelem: 1,500112,0,,Set-Cookie: fpc=AlpJ0fLON5RJnT_b2K4EVTkLIetDFAAAAKjFv9cOAAAA; expires=Sat, 20-Mar-2021 02:19:47 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=prod; path=/; secure; httponly, stsservicecookie=ests; path=/; secure; samesite=none; httponlyDate: Thu, 18 Feb 2021 02:19:47 GMT
--- End of inner exception stack trace ---at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

In ApiFunction.cs:

    [Authorize]
    [AuthorizeForScopes(Scopes = new string[] { "{clientid}/.default" })]
    public class ApiFunctions : Controller
    {
        private readonly ILogger<ApiFunctions> _logger;
        private readonly HttpClient _client;                
        private readonly string _url = "{url}";

        private ITokenAcquisition _tokenAcquisition;
        private readonly MicrosoftIdentityConsentAndConditionalAccessHandler _consentHandler;

        public ApiFunctions(HttpClient httpClient, ILogger<ApiFunctions> logger, ITokenAcquisition tokenAcquisition,
            MicrosoftIdentityConsentAndConditionalAccessHandler consentHandler)
        {
            _client = httpClient;
            _logger = logger;
            _tokenAcquisition = tokenAcquisition;
            _consentHandler = consentHandler;
        }

        //[AuthorizeForScopes(Scopes = new string[] { "{clientid}/.default" })]
        private async Task SetAccessToken()
        {
            try
            {
                string[] scopes = new string[] { "{clientid}/.default" };
                var accessToken = await _tokenAcquisition
                    .GetAccessTokenForUserAsync(scopes)
                    .ConfigureAwait(false);
                _client.DefaultRequestHeaders.Authorization =
                    new AuthenticationHeaderValue("Bearer", accessToken);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Token error: {ex.Message}");
            }            
        }
}

startup.cs

        public void ConfigureServices(IServiceCollection services)
        {
            string[] initialScopes = Configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' ');

            services.AddHttpClient();
            services.AddHttpClient<ApiFunctions>(c => c.BaseAddress = new Uri(Configuration["JupiterAPI"]));
            services.AddHttpClient<IUserService, UserService>(c => c.BaseAddress = new Uri(Configuration["JupiterAPI"]));

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                    .EnableTokenAcquisitionToCallDownstreamApi(new[] { "User.Read.All" })
                        .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                        .AddInMemoryTokenCaches();

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();

            services.AddAuthorization(options =>
            {
                options.FallbackPolicy = options.DefaultPolicy;
            });

            services.AddRazorPages();

            services.AddServerSideBlazor().AddMicrosoftIdentityConsentHandler();

            services.AddTokenAcquisition(true);

            services.AddTransient<ApiFunctions>();
        }

In Razor Page1:

        [Inject]
        GraphServiceClient GraphServiceClient { get; set; }
        [Inject]
        Microsoft.Identity.Web.ITokenAcquisition TokenAcquisitionService { get; set; }
        [Inject] 
        Microsoft.Identity.Web.MicrosoftIdentityConsentAndConditionalAccessHandler ConsentHandler { get; set; }
        [Inject]
        ApiFunctions _apiService { get; set; }
        [Inject]
        ILogger<ApiFunctions> Logger { get; set; }
        [Inject]
        IHttpClientFactory ClientFactory { get; set; }

        protected async Task GetGraphAPI()
        {
            HttpClient _httpClient = ClientFactory.CreateClient();
            string graphToken = "";

            try
            {
                graphToken = await TokenAcquisitionService.GetAccessTokenForUserAsync(new string[] { "User.Read" });
            }
            catch (Exception ex)
            {
                Logger.LogError($"Graph Consent: {ex.Message}");
                ConsentHandler.HandleException(ex);
            }

            try
            {
                // make API call
                _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", graphToken);
                var dataRequest = await _httpClient.GetAsync("https://graph.microsoft.com/beta/me");

                if (dataRequest.IsSuccessStatusCode)
                {
                    var userData = System.Text.Json.JsonDocument.Parse(await dataRequest.Content.ReadAsStreamAsync());
                    string userDepartment = userData.RootElement.GetProperty("department").GetString();
                    Logger.LogError(userDepartment);
                }
            }
            catch(Exception ex)
            {
                Logger.LogError($"graph http error: {ex.Message}");
            }
            
        }

In Razor Page 2 (Different method same result):

        [Inject]
        GraphServiceClient GraphServiceClient { get; set; }
        [Inject] 
        Microsoft.Identity.Web.MicrosoftIdentityConsentAndConditionalAccessHandler ConsentHandler { get; set; }
        private string BusinessUnit { get; set; }

        ...

        protected async Task GetGraphAPI()
        {
            User user = await GraphServiceClient.Me
                .Request()
                .Select(i => i.Department)
                .GetAsync();
            BusinessUnit = user.Department;
        }

**Comment by jmprieur** [comment]
@Robosanta 
Thanks for providing the detail logs. Your issue is explained in there:

```text
The reply address 'https://replyUrlNotSet' does not match the reply address 'https://{url}/signin-oidc' 
```

This means, that when you deploy your app, you need to add, to the app registration the redirect URI of your application as deployed (you need to have as many redirect URIs as deployment locations, including https://localhost:port:/signin-oidc if you want debug locally on your machine.

**Comment by Robosanta** [comment]
@jmprieur 
Thanks for the response, I think that log was due to miss-configuring the authentication to use Microsoft Accounts as the app registration does have all the required redirect urls. Removing this I continue to get a loop of MsalUiRequiredExceptions:

2021-02-18 20:00:40.525 +00:00 [Error] JupiterWebApp.Data.UserService: Token error: IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent.
2021-02-18 20:00:41.210 +00:00 [Error] JupiterWebApp.Data.ApiFunctions: Graph Consent: IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent.
2021-02-18 20:00:45.526 +00:00 [Error] JupiterWebApp.Data.UserService: Token error: IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent.
2021-02-18 20:00:46.043 +00:00 [Error] JupiterWebApp.Data.ApiFunctions: Graph Consent: IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent.

**Comment by Robosanta** [comment]
Solved

ApiFunction.cs:

    [Authorize]
    public class ApiFunctions
    {
        private readonly ILogger<ApiFunctions> _logger;
        private readonly HttpClient _client;
        private ITokenAcquisition _tokenAcquisition;
        private readonly MicrosoftIdentityConsentAndConditionalAccessHandler _consentHandler;

        public ApiFunctions(HttpClient httpClient, ILogger<ApiFunctions> logger, ITokenAcquisition tokenAcquisition,
            MicrosoftIdentityConsentAndConditionalAccessHandler consentHandler)
        {
            _client = httpClient;
            _logger = logger;
            _tokenAcquisition = tokenAcquisition;
            _consentHandler = consentHandler;
        }

        [AuthorizeForScopes(Scopes = new string[] { "{clientid}/.default" })]
        private async Task SetAccessToken()
        {
            try
            {
                string[] scopes = new string[] { "{clientid}/.default" };
                var accessToken = await _tokenAcquisition
                    .GetAccessTokenForUserAsync(scopes)
                    .ConfigureAwait(false);
                _client.DefaultRequestHeaders.Authorization =
                    new AuthenticationHeaderValue("Bearer", accessToken);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Token error: {ex.Message}");
            }            
        }

        ...

    }

Startup.cs:

     public void ConfigureServices(IServiceCollection services)
        {
            string[] initialScopes = Configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' ');

            services.AddHttpClient();
            services.AddHttpClient<ApiFunctions>(c => c.BaseAddress = new Uri(Configuration["MyApi"]));
            services.AddHttpClient<IUserService, UserService>(c => c.BaseAddress = new Uri(Configuration["MyApi"]));

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                    .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                        .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                        .AddInMemoryTokenCaches();

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();

            services.AddAuthorization(options =>
            {
                options.FallbackPolicy = options.DefaultPolicy;
            });

            services.AddRazorPages();

            services.AddServerSideBlazor()
                .AddMicrosoftIdentityConsentHandler();

            services.AddTransient<ApiFunctions>();
        }

On Azure:

App Registration required scopes:

* offline_access
* openid
* profile
* User.Read
* User.ReadBasic.All

* Under Authentication -> Implicity grant and hybrid flows: select both access tokens and ID tokens
