### ISSUE TITLE
Question about multiple daemon server-side applications using a jwt protected webapi with Azure B2C

### ISSUE THREAD

**Issue by V4A001** [AzureAD/microsoft-identity-web#998]
I want to connect a lot of external systems to a web SAAS service. I am thinking of making it secure with client/app secrets using ConfidentialClientApplicationBuilder so that tokens are used during the operations instead of a fixed secret. 

To setup every external system I create new app registrations in Azure B2C (which will be automated with a subscription service). The external system requests a token and then uses JWT to come across the [Authorize] attribute of my SAAS web service. 

The correct/ distinct external system is identified by adding a claim through third party integration or through app registrations if that is easier to start with. In this way I have authentication and authorization secured. If the customer/ user can subscribe and add its own app registration and unique claim (fixed format!) then I believe it is quite secure.

Now the implementation. I have the token acquisition ready with app roles and I am able to get a application token with app roles from Azure AD B2C.
`
var azureAdB2cConfig = new AzureAdB2cConfig();
            _configuration.GetSection(AzureAdB2cConfig.SectionName).Bind(azureAdB2cConfig);

            _scopes = new string[] { azureAdB2cConfig.Scopes };

            _clientApplication = ConfidentialClientApplicationBuilder
                .Create(azureAdB2cConfig.ClientId)
                .WithClientSecret(azureAdB2cConfig.ClientSecret)
                .WithAuthority(azureAdB2cConfig.Authority)
                .Build();
`
But I get these errors:
IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.
IDX20803: Unable to obtain configuration from: 'System.String'.

My web api uses the same parameters during my integration tests:

`
public static IServiceCollection AddCustomAuthentication(this IServiceCollection services, IConfiguration configuration)
        {
            services.Configure<AzureAdB2cConfig>(configuration.GetSection(AzureAdB2cConfig.SectionName));
            
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddMicrosoftIdentityWebApi(configuration, AzureAdB2cConfig.SectionName);

            return services;
        }
`
I see that for Azure B2C and Azure AD the config might be different. But I also found out that Azure B2C does not support daemons.

![image](https://user-images.githubusercontent.com/9630343/108594740-06135000-737c-11eb-80f6-0551441a4346.png)

So is it then better to use Azure AD to do all the app registrations? On the other hand that must then become a separate AD instance as otherwise Azure AD of internal users and Azure B2C get mixed? Or is this too strict?

https://docs.microsoft.com/en-us/azure/active-directory-b2c/application-types

**Which version of Microsoft Identity Web are you using?**

Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ x] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)
none.

**Is this a new or an existing app?**

**Repro**

```
see code above
```

**Expected behavior**
Authenticate daemon to my SAAS web api with JWT in a secure way.

**Actual behavior**
Solution direction a bit unclear or I am using the wrong config file

**Possible solution**
Azure AD or different config file.

**Additional context / logs / screenshots**
See above.

**Comment by V4A001** [comment]
Meanwhile I managed to get this running with a regular Azure AD. I found a lot of useful information here: https://github.com/AzureAD/microsoft-identity-web/wiki/Web-APIs#using-multiple-authentication-schemes
I think some of it is outdated. Like the RequiredScopesConfigurationKey. I am able to use Roles. I understand for daemon apps, only roles can be used?
`
        [Authorize(Roles= "access_as_application")]
        //[RequiredScope(RequiredScopesConfigurationKey = "AzureAd:Scopes")]
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        public async Task<IActionResult> Test()
        {
            _logger.LogInformation($"Test() OK");
            return Ok();
        }
`
I am wondering why the access token is v1.0 and not v2.0. Is this because of daemon? For AzureAD--Instance I use
https://login.microsoftonline.com/{0}/oauth2/v2.0
Instead of https://login.microsoftonline.com/{0}.
But no v2.0 or scopes.

**Comment by jmprieur** [comment]
@V4A001 : the token is v1.0 because the web API requests a v1.0 token. See https://docs.microsoft.com/azure/active-directory/develop/scenario-protected-web-api-app-registration#accepted-token-version

**Comment by V4A001** [comment]
> @V4A001 : the token is v1.0 because the web API requests a v1.0 token. See https://docs.microsoft.com/azure/active-directory/develop/scenario-protected-web-api-app-registration#accepted-token-version

Thank you. I changed the manifest: "If the value is 2, the web API accepts v2.0 tokens." And V2.0 tokens are now issues by Azure AD. It seems daemon apps can only issues roles and no scopes.

I am still thinking over the solution how to identify the multiple daemons from various third party systems which use the same app_role. They have different client id which can be linked to an external Cosmos database which I can cache in Redis to keep it performant. However, every time the token would come in a validation needs to take place.

To reduce the effort of validating with an external db in the web api middleware, I was wondering if sending a fixed additional claim in the jwt token would help me identify the external system and pass it through. It looks like third party claim integration with Azure AD is an option or add custom claims withclientclaims . However, those claims seems to become roles, so I think it is not possible to sent over 1 identifier. Any ideas?

Maybe I just need to stick to the clientid as unique identifier and validate it with a look up to the external database on every request and update the claimsprincipal accordingly. I think it is quite some overhead, but I do not see a way to do this differently. Every third party sent already a header with an unique identifier, but this unique identifier can be set wrongly in the external system, and thus route a message wrongly in my SAAS service.

                //.WithClientClaims(certificate, 
                //    new Dictionary<string, string> { { "UniqueNumber", uniqueNumber} })

**Comment by V4A001** [comment]
@jmprieur : hi you did not answer my other questions. I am still doubting if the approach is right. I went to create the app registration programmatically through C# for every external daemon app. For now Azure AD, want to move to Azure B2C but that is not supported I believe. It seems I cannot register the v2.0 version through C# in Azure AD:

`var application = new Application
            {
                /**/"accessTokenAcceptedVersion": 2,**
                DisplayName = $"xxx",
                Description = $"xx",
                SignInAudience = "AzureADMyOrg",
                IsFallbackPublicClient = false,
                AppRoles = new List<AppRole> { applicationRole },
                Notes = $"Automatically created through subscription portal on {DateTime.Now.ToLongDateString()}",
               
            };`

**Comment by V4A001** [comment]
I believe creating a separate application registration for every application with different api's, clientid and aud does not match with the setup at the SAAS part. That has only one. So I think multiple daemons won't work with azure ad / azure b2c. I read something about creating a jwt token at the deamon site, will have a look in that.

**Comment by jmprieur** [comment]
@V4A001 
- B2C does not support daemon applications (as B2C is about users only). Are you trying to create a B2C daemon app?

**Comment by jmprieur** [comment]
In case this helps, we have a new tool to create and configure apps: https://github.com/AzureAD/microsoft-identity-web/tree/master/tools/app-provisioning-tool

The code for the app creation / update is in https://github.com/AzureAD/microsoft-identity-web/blob/master/tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/MicrosoftIdentityPlatformApplicationManager.cs.

It does not handle daemon apps though, but it does handle B2C apps (and conversions of AAD apps to B2C apps)

**Comment by V4A001** [comment]
@jmprieur very nice and helpful. The second example helps a lot. I have the creation of deamon apps working now for Azure AD. Good to hear confirmation that B2C will not work. 

I am still doubting if app registration is the way to go for multiple daemon apps. I can create multiple app registration for every external system now automatically, but when the JWT arrives at our webapi it only allows one clientid.
services.AddMicrosoftIdentityWebApiAuthentication(configuration, AzureAdWebApiConfig.SectionName);
Or should I code something to allow multiple app registrations on one JWT endpoint? I have coded already a own permission requirement to check if the created deamon app is subscribed. I am not sure how to do this technically and if the approach is good. Why not except app registrations from the external tenants and do the app registration there? I guess that approach is less likely as logins etc are now in our Azure AD visible and otherwise we need to code that.

`protected async override Task<Task> HandleRequirementAsync(AuthorizationHandlerContext context, WebApiPermissionRequirement requirement)
        {
            if (context.User.Identity == null || !context.User.Identity.IsAuthenticated)
            {
                _logger.LogError("AuthenticationScheme: Bearer was not authenticated.");
                context.Fail();
                return Task.CompletedTask;
            }`

Nice, this helps!
`   var application = new Application
            {
                //"accessTokenAcceptedVersion": 2,
                DisplayName = $"xx",
                Description = $"xx",
                SignInAudience = "AzureADMyOrg",
                IsFallbackPublicClient = false,
                AppRoles = new List<AppRole> { applicationRole },
                Notes = $"Automatically created through subscription portal on {DateTime.Now.ToLongDateString()}",
                **Api = new ApiApplication()
                {
                    RequestedAccessTokenVersion = 2,
                }**
            };  `
